[
  {
    "original_filename": "0091_wall_with_sloped_profile",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<style>\n.blue { color: blue; }\n.teal { color: teal; }\n.maroon { color: maroon; }\n.green { color: green; }\n</style>"
  },
  {
    "original_filename": "0091_wall_with_sloped_profile",
    "header_text": "Creating a Wall with a Sloped Profile",
    "local_header_href": "#creating-a-wall-with-a-sloped-profile",
    "chunk_text": "<h3>Creating a Wall with a Sloped Profile</h3><p>Here is a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2008/11/wall-elevation-profile.html#comments\">\nquestion from Winnie</a>\n\non the creation of walls with a sloped profile:</p><p><strong>Question:</strong>\nI'm having problems trying to create walls that have constant sloped top edge.\nI tried using the NewWall method and passed in a CurveArray that contains the edges of the wall that would create a sloped top but the result was still a rectangular wall.\nAlso, how would you alter an existing wall to have a top sloped edge?</p><p><strong>Answer:</strong>\nUsing NewWall and supplying a profile to define the slope is exactly the right approach.\nI implemented a minimal new command named CmdSlopedWall to do this.\nHere is the code for the Execute method to create a wall with a sloped upper edge:</p><pre class=\"code\">\n<span class=\"teal\">Application</span> app = commandData.Application;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Application</span> ac\n  = app.Create;\n \n<span class=\"teal\">CurveArray</span> profile = ac.NewCurveArray();\n \n<span class=\"blue\">double</span> length = 10;\n<span class=\"blue\">double</span> heightStart = 5;\n<span class=\"blue\">double</span> heightEnd = 8;\n \n<span class=\"teal\">XYZ</span> p = ac.NewXYZ( 0.0, 0.0, 0.0 );\n<span class=\"teal\">XYZ</span> q = ac.NewXYZ( length, 0.0, 0.0 );\n \nprofile.Append( ac.NewLineBound( p, q ) );\n \np.X = q.X;\nq.Z = heightEnd;\n \nprofile.Append( ac.NewLineBound( p, q ) );\n \np.Z = q.Z;\nq.X = 0.0;\nq.Z = heightStart;\n \nprofile.Append( ac.NewLineBound( p, q ) );\n \np.X = q.X;\np.Z = q.Z;\nq.Z = 0.0;\n \nprofile.Append( ac.NewLineBound( p, q ) );\n \n<span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \n<span class=\"teal\">Wall</span> wall = doc.Create.NewWall( profile,\n  <span class=\"blue\">false</span> );\n \n<span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Succeeded;\n</pre><p>This is what the resulting wall looks like:</p><img alt=\"Wall with a sloped profile\" src=\"img/wall_with_sloped_profile.png\"/><p>Regarding your second query on the modification of an existing wall:\napplying a profile to an existing wall which has none to start with is currently not supported by the API.\nSuch a method would be similar to the Truss SetProfile method, but walls do not currently support this.</p><p>Here is \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/files/bc10022.zip\">\nversion 1.0.0.22</a>\n\nof the complete Visual Studio solution with this new command implementation.</p>"
  }
]