[
  {
    "original_filename": "0125_new_area",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<style>\n.blue { color: blue; }\n.teal { color: teal; }\n.maroon { color: maroon; }\n.green { color: green; }\n.gray { color: gray; }\n</style>"
  },
  {
    "original_filename": "0125_new_area",
    "header_text": "Create an Area",
    "local_header_href": "#create-an-area",
    "chunk_text": "<h3>Create an Area</h3><a href=\"http://thebuildingcoder.typepad.com/blog/2009/03/more-questions.html?cid=6a00e553e16897883301156f20ba0d970c#comment-6a00e553e16897883301156f20ba0d970c\">\nquestion</a><p><strong>Question:</strong>\nI would like to create an area element overlaid on a room in an area plan view.</p><p><strong>Answer:</strong>\nThe Revit API provides one method on the Document class in the Autodesk.Revit.Creation namespace for creating new areas,</p><pre>\nArea NewArea( ViewPlan areaView, UV point );\n</pre><a href=\"http://thebuildingcoder.typepad.com/blog/2009/03/create-room-on-level-in-phase.html\">\nhow to create a room</a><pre>\nRoom NewRoom( Level level, UV point );\n</pre><p>An area can only be created in an area plan view.\nThe determination of the area boundaries is automatic, given a point in its interior.<p>\n<p>Therefore, if a room already exists, you just need to determine a point in its interior and feed that and the area plan view to the NewArea method.\nOne easy way to obtain a point in the interior of a room is to use its location point.\nThat returns an XYZ instance.\nI checked that the returned Z coordinate was zero and simply discarded that to create the UV point required by the NewArea method.\nOf course, there may be more complex situations where some kind of transformation is required, but I am not sure.</p>\n<p>Here is the implementation of the Execute method of a new external command class CmdNewArea which demonstrates this.\nFirst, it checks that the current view is an area plan view.\nIt then checks whether a single room has been selected, or prompts you to do so interactively.\nOnce these preliminaries have been completed, the following code creates a new area element based on the selected room boundaries:</p>\n<pre class=\"code\">\n<span class=\"teal\">CmdResult</span> rc = <span class=\"teal\">CmdResult</span>.Failed;\n \n<span class=\"teal\">ViewPlan</span> view = commandData.View <span class=\"blue\">as</span> <span class=\"teal\">ViewPlan</span>;\n \n<span class=\"blue\">if</span>( <span class=\"blue\">null</span> == view\n  || view.ViewType != <span class=\"teal\">ViewType</span>.AreaPlan )\n{\n  message = <span class=\"maroon\">\"Please run this command in an area plan view.\"</span>;\n  <span class=\"blue\">return</span> rc;\n}\n \n<span class=\"teal\">Application</span> app = commandData.Application;\n<span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \n<span class=\"teal\">Element</span> room = <span class=\"teal\">Util</span>.GetSingleSelectedElement( doc );\n \n<span class=\"blue\">if</span>( <span class=\"blue\">null</span> == room || !(room <span class=\"blue\">is</span> <span class=\"teal\">Room</span>) )\n{\n  room = <span class=\"teal\">Util</span>.SelectSingleElement( doc, <span class=\"maroon\">\"a room\"</span> );\n}\n \n<span class=\"blue\">if</span>( <span class=\"blue\">null</span> == room || !( room <span class=\"blue\">is</span> <span class=\"teal\">Room</span> ) )\n{\n  message = <span class=\"maroon\">\"Please select a single room element.\"</span>;\n}\n<span class=\"blue\">else</span>\n{\n  <span class=\"teal\">Location</span> loc = room.Location;\n  <span class=\"teal\">LocationPoint</span> lp = loc <span class=\"blue\">as</span> <span class=\"teal\">LocationPoint</span>;\n  <span class=\"teal\">XYZ</span> p = lp.Point;\n  <span class=\"teal\">UV</span> q = <span class=\"blue\">new</span> <span class=\"teal\">UV</span>( p.X, p.Y );\n  <span class=\"teal\">Area</span> area = doc.Create.NewArea( view, q );\n  rc = <span class=\"teal\">CmdResult</span>.Succeeded;\n}\n<span class=\"blue\">return</span> rc;\n</pre>\n<p>Here is\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/files/bc10030.zip\">\nversion 1.0.0.30</a>\n\nof the complete Visual Studio solution with the new command.</p>\n</p></p>"
  }
]