[
  {
    "original_filename": "0180_newlineload",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<style>\n\npre { \n  font-size : 95%; \n  line-height : 120%; \n  background-color : lightgrey;\n  white-space : wrap;\n  color: darkblue;\n  background-color : linen;\n}\n\npre.code { \n  color: black;\n  background-color : white; \n}\n\n.blue { color: blue; }\n.teal { color: teal; }\n.maroon { color: maroon; }\n.green { color: green; }\n.gray { color: gray; }\n\n</style>"
  },
  {
    "original_filename": "0180_newlineload",
    "header_text": "NewLineLoad",
    "local_header_href": "#newlineload",
    "chunk_text": "<h3>NewLineLoad</h3><p>In Revit Structure, a new line load is created using the NewLineLoad method.\nIt provides four different overloads, which we wish to explore here in a little more detail:</p><ul>\n<li>NewLineLoad(XYZ, XYZ, XYZ, XYZ, XYZ, XYZ, Boolean, Boolean, Boolean, LineLoadType, SketchPlane): unhosted line load using data at two points.\n<li>NewLineLoad(XYZArray, XYZArray, XYZArray, Boolean, Boolean, Boolean, LineLoadType, SketchPlane): unhosted line load using data at an array of points.\n<li>NewLineLoad(Element, XYZArray, XYZArray, Boolean, Boolean, Boolean, LineLoadType, SketchPlane): hosted line load using data at an array of points. \n<li>NewLineLoad(Reference, XYZArray, XYZArray, Boolean, Boolean, Boolean, LineLoadType, SketchPlane): hosted line load using data at an array of points. \n</li></li></li></li></ul><p>The first few arguments vary, and provide for the different methods of defining the line load location or host element. \nThe last five are always the same:</p><ul>\n<li>Boolean uniform.\n<li>Boolean projected.\n<li>Boolean isReaction.\n<li>LineLoadType symbol.\n<li>SketchPlane.\n</li></li></li></li></li></ul><p>The arguments differing between the overloads are:</p><ul>\n<li>XYZ p1, XYZ f1, XYZ m1, XYZ p2, XYZ f2, XYZ m2: two points and the forces and moments at each to define an unhosted line load.\n<li>XYZArray points, XYZArray forces, XYZArray moments: arrays to define the points, forces and moments of an unhosted line load.\n<li>Element, XYZArray forces, XYZArray moments: an element and arrays of forces and moments to define a hosted line load.\n<li>Reference, XYZArray forces, XYZArray moments: a curve reference and arrays of forces and moments to define a hosted line load.\n</li></li></li></li></ul><p>The first one takes two triples of XYZ arguments for the point coordinates, force and moment at each of two given points.</p><p>The three others take XYZArray arguments to define the forces and moments.\nThe overload taking three arrays, one each for the points, forces and moments, is the only one that can accommodate an arbitrary number greater than one of points, forces and moments.</p><p>The last two overloads define hosted line loads.\nHere, these arrays are expected to have exactly two entries, which can then be distributed evenly from start to end point along the host element or curve.\nAn attempt to add a third entry to the force array, for example, will cause an exception to be thrown.</p><p>Jiri Smerak of \n\n<a href=\"http://dlubal.de\">\nIng.-Software Dlubal GmbH</a>\n\nhas done some further research on how to use these methods.\nHe implemented an external command for testing the various overloads and their parameter combinations.\nI used his code as a basis to implement a new Building Coder sample command CmdNewLineLoad.\nIt successfully creates:</p><ul>\n<li>An unhosted line load defined by two points.</li>\n<li>A hosted line load on a beam element.</li>\n<li>A hosted line load on a beam's analytical curve.</li>\n</ul><p>Jiri tested creating hosted line loads on braces and columns and confirms that that works as well.\nHe also tested the overloads taking a reference parameter, and that works fine on a beam or column's analytical line reference, including arc and nurbs beams.\n</p><p>Here is the code for the external command Execute method:</p><pre class=\"code\">\n<span class=\"teal\">Application</span> app = commandData.Application;\n<span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Application</span> ca\n  = app.Create;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Document</span> cd\n  = doc.Create;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Filter</span> cf\n  = ca.Filter;\n \n<span class=\"green\">// determine line load symbol to use:</span>\n \n<span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; symbols = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;();\n<span class=\"teal\">Filter</span> f1 = cf.NewTypeFilter( <span class=\"blue\">typeof</span>( <span class=\"teal\">LineLoadType</span> ) );\n<span class=\"blue\">int</span> n = doc.get_Elements( f1, symbols );\n \n<span class=\"teal\">LineLoadType</span> loadSymbol \n  = symbols[0] <span class=\"blue\">as</span> <span class=\"teal\">LineLoadType</span>;\n \n<span class=\"green\">// sketch plane and arrays of forces and moments:</span>\n \n<span class=\"teal\">Plane</span> plane = ca.NewPlane( <span class=\"teal\">XYZ</span>.BasisZ, <span class=\"teal\">XYZ</span>.Zero );\n<span class=\"teal\">SketchPlane</span> skplane = cd.NewSketchPlane( plane );\n \n<span class=\"teal\">XYZ</span> forceA = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 0, 5 );\n<span class=\"teal\">XYZ</span> forceB = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 0, 10 );\n<span class=\"teal\">XYZArray</span> forces = <span class=\"blue\">new</span> <span class=\"teal\">XYZArray</span>();\nforces.Append( forceA );\nforces.Append( forceB );\n \n<span class=\"teal\">XYZ</span> momentA = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 0, 0 );\n<span class=\"teal\">XYZ</span> momentB = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 0, 0 );\n<span class=\"teal\">XYZArray</span> moments = <span class=\"blue\">new</span> <span class=\"teal\">XYZArray</span>();\nmoments.Append( momentA );\nmoments.Append( momentB );\n \n<span class=\"teal\">BuiltInCategory</span> bic \n  = <span class=\"teal\">BuiltInCategory</span>.OST_StructuralFraming;\n \nf1 = cf.NewTypeFilter( <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilyInstance</span> ) );\n<span class=\"teal\">Filter</span> f2 = cf.NewCategoryFilter( bic );\n<span class=\"teal\">Filter</span> f3 = cf.NewLogicAndFilter( f1, f2 );\n \n<span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; beams = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;();\n \nn = doc.get_Elements( f3, beams );\n \n<span class=\"teal\">XYZ</span> p1 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 0, 0 );\n<span class=\"teal\">XYZ</span> p2 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 3, 0, 0 );\n<span class=\"teal\">XYZArray</span> points = <span class=\"blue\">new</span> <span class=\"teal\">XYZArray</span>();\npoints.Append( p1 );\npoints.Append( p2 );\n \n<span class=\"green\">// create a new unhosted line load on points:</span>\n \n<span class=\"teal\">LineLoad</span> lineLoadNoHost = cd.NewLineLoad( \n  points, forces, moments, \n  <span class=\"blue\">false</span>, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>, \n  loadSymbol, skplane );\n \n<span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Unhosted line load works.\"</span> );\n \n<span class=\"green\">// create new line loads on beam:</span>\n \n<span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> e <span class=\"blue\">in</span> beams )\n{\n  <span class=\"blue\">try</span>\n  {\n    <span class=\"teal\">LineLoad</span> lineLoad = cd.NewLineLoad(\n      e, forces, moments,\n      <span class=\"blue\">false</span>, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>,\n      loadSymbol, skplane );\n \n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Hosted line load on beam works.\"</span> );\n  }\n  <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> ex )\n  {\n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Hosted line load on beam fails: \"</span>\n      + ex.Message );\n  }\n \n  <span class=\"teal\">FamilyInstance</span> i = e <span class=\"blue\">as</span> <span class=\"teal\">FamilyInstance</span>;\n \n  <span class=\"teal\">AnalyticalModelFrame</span> amFrame \n    = i.AnalyticalModel <span class=\"blue\">as</span> <span class=\"teal\">AnalyticalModelFrame</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Curve</span> curve <span class=\"blue\">in</span> amFrame.Curves )\n  {\n    <span class=\"blue\">try</span>\n    {\n      <span class=\"teal\">LineLoad</span> lineLoad = cd.NewLineLoad( \n        curve.Reference, forces, moments, \n        <span class=\"blue\">false</span>, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>, \n        loadSymbol, skplane );\n \n      <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Hosted line load on \"</span>\n        + <span class=\"maroon\">\"AnalyticalModelFrame curve works.\"</span> );\n    }\n    <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> ex )\n    {\n      <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Hosted line load on \"</span>\n        + <span class=\"maroon\">\"AnalyticalModelFrame curve fails: \"</span> \n        + ex.Message );\n    }\n  }\n}\n<span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Succeeded;\n</pre><p>The command creates one free-standing line load on a pair of given points.\nIt also picks up all family instances with the structural framing category and creates line loads on both the elements and their analytical model curves.\nI ran it this minimal project containing one single beam on a work plane grid:</p><img alt=\"One beam on a work plane grid\" src=\"img/newlineloadbeam1.png\"/><p>This is the report resulting from running the command in this minimal sample project:</p><pre>\nUnhosted line load works.\nHosted line load on beam works.\nHosted line load on AnalyticalModelFrame curve works.\n</pre><p>Here you see the line loads added, one on the given points and the other two hosted by the beam:</p><img alt=\"Line loads added\" src=\"img/newlineloadbeam2.png\"/><p>Here is\n\n<a href=\"zip/bc11041.zip\">\nversion 1.1.0.41</a>\n\nof the complete Visual Studio solution including the new command.</p><p>Thank you very much Jiri for all your research!</p>"
  }
]