[
  {
    "original_filename": "0254_select_model_elements_2",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0254_select_model_elements_2",
    "header_text": "Select Model Elements 2",
    "local_header_href": "#select-model-elements-2",
    "chunk_text": "<h3>Select Model Elements 2</h3><p>We already had several stabs at the topic of \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/06/category-comparison-and-model-element-selection-revisited.html\">\nselecting all model elements</a>,\n\ni.e. all elements in a Revit BIM which contribute to the building geometry.\nTheir main characteristic is that they have a non-null geometry which is visible on the graphics screen and really contributes to the physical building model.\nUnfortunately, some elements which are not part of the building itself also have valid geometry and need to be eliminated.\n\n<p>The latest version of the code that we presented still made use of a full iteration over all document elements, i.e. something like this:\n<pre class=\"code\">\n  <span class=\"teal\">Application</span> app = commandData.Application;\n  <span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \n  <span class=\"teal\">ElementIterator</span> it = doc.Elements;\n \n  <span class=\"blue\">while</span>( it.MoveNext() )\n  {\n    <span class=\"teal\">Element</span> e = it.Current <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n    <span class=\"green\">// . . .</span>\n  }\n</pre>\n<p>As we all know by now, this kind of full iteration over all document elements is unnecessarily time consuming and seldom useful, because an application is almost always only interested in a small subset of them.\nWe will convert the model element selection to use element filtering, similarly to the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/02/converting-to-filters.html\">\nconversion to use filters</a> we \n\ndescribed for the Revit SDK FrameBuilder sample.\n\n<p>We can add both a type filter to eliminate a list of classes that we are not interested in, and also a built-in category filter to eliminate unwanted categories.\nHere is the list of unwanted types, i.e. classes of elements which are not model elements:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"teal\">Type</span>[] _types_to_skip = <span class=\"blue\">new</span> <span class=\"teal\">Type</span>[] {\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">BasePoint</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">DetailLine</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Dimension</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Family</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilyBase</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">FillPattern</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">gbXMLParamElem</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">GraphicsStyle</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">LinePattern</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">MaterialOther</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ModelLine</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Phase</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">PrintSetting</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ProjectInfo</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ProjectUnit</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ReferencePlane</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Room</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">RoomTag</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Sketch</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">SketchPlane</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Symbol</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">TextNote</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ViewDrafting</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ViewPlan</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">ViewSheet</span> ),\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">WallType</span> ),\n};\n</pre>\n<p>If you run into some additional unwanted element in your model that is not listed here, you can easily add it. \nYou might want to let us know as well by submitting a comment on it.\n\n<p>We define the following helper method to more succinctly create a type filter which eliminates all of these classes. \nGiven an existing type filter 'f', it adds another type 't' to it and returns the new expanded filter:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"teal\">Filter</span> OrType(\n  <span class=\"teal\">Filter</span> f,\n  <span class=\"teal\">Type</span> t,\n  Autodesk.Revit.Creation.<span class=\"teal\">Filter</span> cf )\n{\n  <span class=\"teal\">Filter</span> f2 = cf.NewTypeFilter( t );\n  <span class=\"blue\">return</span> cf.NewLogicOrFilter( f, f2 );\n}\n</pre>\n<p>We can make use of it to implement the first step of our external command Execute method like this:\n\n<pre class=\"code\">\n<span class=\"teal\">Application</span> app = commandData.Application;\n<span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Filter</span> cf\n  = app.Create.Filter;\n \n<span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; els = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;();\n<span class=\"teal\">Filter</span> f = cf.NewTypeFilter( <span class=\"blue\">typeof</span>( <span class=\"teal\">Symbol</span> ) );\n<span class=\"blue\">foreach</span>( <span class=\"teal\">Type</span> t <span class=\"blue\">in</span> _types_to_skip )\n{\n  f = OrType( f, t, cf );\n}\nf = cf.NewLogicNotFilter( f );\n<span class=\"blue\">int</span> n = doc.get_Elements( f, els );\n</pre>\n<p>In addition to the unwanted types, we know some built-in categories whose elements also do not contribute to the building geometry and should be eliminated, for instance:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"blue\">int</span>[] _bics_to_skip = <span class=\"blue\">new</span> <span class=\"blue\">int</span>[] {\n  ( <span class=\"blue\">int</span> ) <span class=\"teal\">BuiltInCategory</span>.OST_PreviewLegendComponents,\n  ( <span class=\"blue\">int</span> ) <span class=\"teal\">BuiltInCategory</span>.OST_IOSSketchGrid,\n  ( <span class=\"blue\">int</span> ) <span class=\"teal\">BuiltInCategory</span>.OST_Cameras,\n};\n</pre>\n<p>We have converted them to integer values to make use of the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/06/category-comparison-and-model-element-selection-revisited.html\">\nlanguage independent category comparison</a>. \n\nThe following helper method encapsulates the code to determine whether a given built-in category integer value is included in this list and the associated element thus needs to be skipped.\nIt makes use of the generic Array.Exists method:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"blue\">bool</span> SkipThisBic( <span class=\"blue\">int</span> bic )\n{\n  <span class=\"blue\">return</span> <span class=\"teal\">Array</span>.Exists&lt;<span class=\"blue\">int</span>&gt;(\n    _bics_to_skip,\n    <span class=\"blue\">delegate</span>( <span class=\"blue\">int</span> i )\n    {\n      <span class=\"blue\">return</span> i == bic;\n    } );\n}\n</pre>\n<p>With these preparations in place, we can iterate over and list the model elements like this in the rest of the implementation of the external command Execute method:\n\n<pre class=\"code\">\n<span class=\"blue\">string</span> s = <span class=\"blue\">string</span>.Empty;\nn = 0;\n \nGeo.<span class=\"teal\">Options</span> opt = app.Create.NewGeometryOptions();\n \n<span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> e <span class=\"blue\">in</span> els )\n{\n  <span class=\"blue\">if</span>( (<span class=\"blue\">null</span> != e.Category)\n    &amp;&amp; !SkipThisBic( e.Category.Id.Value )\n    &amp;&amp; (<span class=\"blue\">null</span> != e.get_Geometry( opt )) )\n  {\n    ++n;\n    s += <span class=\"blue\">string</span>.Format( \n      <span class=\"maroon\">\"\\r\\n  Category={0}; Name={1}; Id={2}\"</span>,\n      e.Category.Name, e.Name, e.Id.Value );\n  }\n}\n \ns = <span class=\"blue\">string</span>.Format(\n  <span class=\"maroon\">\"Project contains {0} model element{1}{2}\"</span>,\n  n,\n  ( 1 == n ? <span class=\"maroon\">\"\"</span> : <span class=\"maroon\">\"s\"</span> ),\n  ( 0 == n ? <span class=\"maroon\">\".\"</span> : <span class=\"maroon\">\":\"</span> ) )\n+ s;\n \n<span class=\"teal\">LabUtils</span>.InfoMsg( s );\n \n<span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Failed;\n</pre>\n<p>Here is today's snapshot of the updated version of the \n\n<a href=\"zip/rac_labs_2009-11-24.zip\">\nRevit API introduction labs</a>, \n\nincluding the version of Lab 2-2 to select all model elements as described above.\n</p></p></p></p></p></p></p></p></p></p></p>"
  }
]