[
  {
    "original_filename": "0306_uv_coords_fbx",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0306_uv_coords_fbx",
    "header_text": "Texture Data UV Coordinates and FBX",
    "local_header_href": "#texture-data-uv-coordinates-and-fbx",
    "chunk_text": "<h3>Texture Data UV Coordinates and FBX</h3><p>Still on vacation in Andalusia, mostly dealing with pretty basic issues and facts of life such as cold rainy weather and a leaking roof, here is another quick post from cold storage:\n\n<p><strong>Question:</strong> How can I access the texture data on a Revit model using the Revit API?\n\nI am interested in extracting the UV coordinates, colour and texture data on element faces.\nHow can I retrieve the UV texture coordinate information?\n\n<p>I am currently using the FBX SDK to retrieve the texture file name from the texture library.\nIs this the preferred method?\nAny samples would be greatly appreciated!\n\n<p>A closely related question came up again recently in an email from Ben Nolan:\n\n<p><strong>Question:</strong> I love the Building Coder.\nBut there's a topic you haven't covered â€“ do you know if it's possible to export textures coordinates from within the Revit SDK?\nWe've seen the UVArray class, but can't work out how to get an UVArray from a mesh or other geometry object.\n\n<p><strong>Answer:</strong> The Revit API has some ability to extract information about material assets from an RVT file.\n\nFor example, the following code snippet traverses some of the asset information available in Revit.\nIt can be extended by handling the remaining AssetPropertyType enum cases.\nIt also queries the faces of an element and extracts XYZ information from its triangulation vertices.\nIt attempts to extract some UV information, but that is probably not useful for the texture mapping context:\n\n<pre>\nElementSet collection = doc.Selection.Elements;\nforeach (Autodesk.Revit.Element e in collection)\n{\n  String s = \"\";\n  Asset a = e.Category.Material.RenderAppearance;\n  for (int index = 0; index &lt; a.Size; index++)\n  {\n    AssetProperty ap = a[index];\n    if (ap.Type == AssetPropertyType.APT_String)\n    {\n      AssetPropertyString value_str\n        = a[index] as AssetPropertyString;\n\n      s += ap.Name + \": \" + value_str.Value + \"\\n\";\n    }\n    if (ap.Type == AssetPropertyType.APT_Boolean)\n    {\n      AssetPropertyBoolean value_bool\n        = a[index] as AssetPropertyBoolean;\n\n      s += ap.Name + \": \" + value_bool.Value + \"\\n\";\n    }\n    if (ap.Type == AssetPropertyType.APT_Float)\n    {\n      AssetPropertyFloat value_float\n        = a[index] as AssetPropertyFloat;\n\n      s += ap.Name + \": \" + value_float.Value + \"\\n\";\n    }\n  }\n  MessageBox.Show(s);\n\n  Options options = app.Create.NewGeometryOptions();\n  options.DetailLevel = Options.DetailLevels.Fine;\n  Element geom = e.get_Geometry(options);\n\n  foreach (GeometryObject geomObject in geom.Objects)\n  {\n    if (geomObject.GetType() == typeof(Mesh))\n    {\n    }\n    else if (geomObject.GetType() == typeof(Solid))\n    {\n      s = \"\";\n      int nbFace = 0;\n      Solid geomSolid = (Solid)geomObject;\n      foreach (Face geomFace in geomSolid.Faces)\n      {\n\n/*\n        Mesh geomMesh = geomFace.Triangulate();\n        XYZArray vertices = geomMesh.Vertices;\n        int nbVertex = vertices.Size;\n        uint indexA = 0; uint indexB = 0; uint indexC = 0;\n        for (int i = 0; i &lt; geomMesh.NumTriangles; i++)\n        {\n          MeshTriangle triangle = geomMesh.get_Triangle(i);\n          indexA = triangle.get_Index(0);\n          indexB = triangle.get_Index(1);\n          indexC = triangle.get_Index(2);\n        }\n*/\n\n        foreach (EdgeArray geomEdges in geomFace.EdgeLoops)\n        {\n          foreach (Edge geomEdge in geomEdges)\n          {\n            foreach (UV geomUV in\n              geomEdge.TessellateOnFace(geomFace))\n            {\n              s += \"Face: \"+ nbFace\n                + \" UV: \" + geomUV.U + \" \" + geomUV.V + \"\\n\";\n            }\n          }\n        }\n        nbFace++;\n      }\n      MessageBox.Show(s);\n    }\n  }\n}\n</pre>\n<p>It would be nice to be able to directly obtain the UV information something like this, analogously to the XYZ data for the face mesh vertices:\n\n<pre>\nMesh geomMesh = geomFace.Triangulate();\nXYZArray vertices = geomMesh.Vertices;\nUVArray uvs = geomMesh.UVs;\n</pre>\n<p>However the mesh vertices accessible through the API are the XYZ coordinates of each vertex.\nThe texture mapping is probably defined by the UV coordinates for each vertex that would be calculated if the mesh was unfolded and flattened into a plane.\nThat information is currently not accessible through the API.\n\n<p>There is an alternative approach, though, using the FBX file format.\n\n<p>The FBX format is purpose-built for exchanging information about materials, appearance, and rendering properties. By contrast, the Revit API has only limited ability to extract information about material assets from an RVT file.\n\n<p>The FBX format is consistent amongst other Autodesk products such as Maya and 3DStudio.\n\n<p>In the FBX SDK, the ImportScene sample program might be helpful.\nYou can use it like this:\n\n<ul>\n<li>Create a wall in Revit Architecture.\n<li>Export an FBX file using File &gt; Export &gt; 3DS Max FBX.\n<li>Run the FBX SDK sample 'ImportScene' on the generated FBX file.\n<li>Import the FBX file into 3DS Max.\n</li></li></li></li></ul>\n<p>3DS Max reads and displays the Revit model including all its Mesh, UV information, Material and Texture information.\nThis means that the FBX file has all the required information.\nThe support file assetlibrary_base.fbx probably also includes some library material and texture information.\n\n<p>I removed the comment from the following line 93 in main.cxx:\n\n<pre>\nlSdkManager-&gt;GetIOPluginRegistry()-&gt;RegisterReader(\n  CreateMyOwnReader,\n  GetMyOwnReaderInfo,\n  lPluginId,\n  lRegisteredCount,\n  FillOwnReaderIOSettings );\n</pre>\n<p>Then the sample displays UV coordinates like these:\n\n<pre>\nMesh Name: Basic Wall kudo [105571]\nControl Points\nControl Point 0\nCoordinates: -47.403542, 16.331938, 0.000000\n . . .\nControl Point 7\nCoordinates: 33.961288, 17.198078, 0.000000\n\nPolygons\nPolygon 0\nCoordinates: -47.403542, 16.331938, 26.246719\nTexture UV (on layer 0): 0.000000, 26.246719\nCoordinates: -47.403542, 16.331938, 0.000000\nTexture UV (on layer 0): 0.000000, 0.000000\nCoordinates: 33.961288, 16.331938, 26.246719\nTexture UV (on layer 0): 81.364830, 26.246719\n</pre>\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]