[
  {
    "original_filename": "0489_get_sketch",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<html>\n<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<script language=\"JavaScript\">\n// from http://www.sevenwires.com/play/UpsideDownLetters.html\nfunction flipString(aString) {\n  var last = aString.length - 1;\n  var result = new Array(aString.length)\n  for (var i = last; i >= 0; --i) {\n    var c = aString.charAt(i)\n    var r = flipTable[c]\n    result[last - i] = r != undefined ? r : c\n    }\n  return result.join('')\n}\nvar flipTable = {\na : '\\u0250',\nb : 'q',\nc : '\\u0254',\nd : 'p',\ne : '\\u01DD',\nf : '\\u025F',\ng : '\\u0183',\nh : '\\u0265',\ni : '\\u0131',\nj : '\\u027E',\nk : '\\u029E',\nl : '\\u05DF',\nm : '\\u026F',\nn : 'u',\nr : '\\u0279',\nt : '\\u0287',\nv : '\\u028C',\nw : '\\u028D',\ny : '\\u028E',\n'.' : '\\u02D9',\n'[' : ']',\n'(' : ')',\n'{' : '}',\n'?' : '\\u00BF',\n'!' : '\\u00A1',\n\"\\'\" : ',',\n'<' : '>',\n'_' : '\\u203E',\n'\"' : '\\u201E',\n'\\\\' : '\\\\',\n';' : '\\u061B',\n'\\u203F' : '\\u2040',\n'\\u2045' : '\\u2046',\n'\\u2234' : '\\u2235'\n}\nfor (i in flipTable) {\n  flipTable[flipTable[i]] = i\n}\n</script>\n</head>\n<body onload=\"document.all.flipped.innerHTML=flipString(document.all.flipped.innerHTML)\">\n<!-- \n\n<body onload=\"alert('onload');document.all.flipped.innerHTML=flipString('the final trailing comma');alert('done');\">\n\n1264869 [How do I find the elevation profile (sketch) of a wall]\n1265025 [Filled region, sketch and sketch plane]\nhttp://adn.autodesk.com/adn/servlet/devnote?siteID=4814862&id=16037230&linkID=4901650\n\n-->\n<h3>Access to Sketch and Sketch Plane</h3>\n<p>I just presented my first Revit API class here at AU 2010, \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=6943&amp;jid=614479\">\nCP228-2</a>, on the optimal use of the Revit 2011 programming features and the Idling event.\nI already posted my AU\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/09/autodesk-university-2010-classes.html\">\nclass descriptions</a> and\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/autodesk-university-2010-class-materials.html\">\nmaterials</a>.\n\nThe presentation went well and was good fun. \nThe next one, \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=7246&amp;jid=614479\">\nCP234-2</a>,\n\non Revit 2011 programming optimization and filtered element collectors, is scheduled in an hour's time.\nRight now I am sitting in on \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=7107&amp;jid=613470\">\nMatt Mason's presentation on Revit parameters</a>.\n\n<p>Meanwhile, here is another interesting application of the doc.Delete method to access related elements that we already explored several times in the past for determining\n\n<!--\n\n107_room_on_level_in_phase.htm:      doc.Delete( room );\n146_host_reference.htm:&nbsp; &nbsp; delIds = doc.Delete( wall );\n150_unload_family_type.htm:&nbsp; &nbsp; &nbsp; doc.Delete( e );\n216_remove_geometry_rfa.htm:&nbsp; <span class=\"teal\">ElementIdSet</span> ids =\n247_title_block_of_sheet.htm:doc.Delete method to detect dependent elements</a>.\n307_unmodified_geometry.htm:<p>Probably the most reliable way to solve this prob\n314_object_relationship.htm:&nbsp; <span class=\"teal\">ElementIdSet</span> ids =\n334_anonymous_methods_vb.htm:&nbsp; &nbsp; doc.Delete( symbol );\n360_p2c.htm:&nbsp; doc.Delete( pipe );\n419_transaction_migration.htm:&nbsp; &nbsp; delIds = doc.Delete( wall );\n476_purge_text_note_types.htm:&nbsp; doc.Delete( textNoteTypes );\n479_launch_command.htm:&nbsp; &nbsp; <span class=\"green\">// doc.delete(nw) may n\n484_failure_api.htm:&nbsp; &nbsp; doc.Delete( elem );\n488_mirror_in_new_family.htm:&nbsp; familyDoc.Delete(famInst)\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/object-relationships.html\">\nall kinds of useful object relationships</a>.\n\nNow Joe Ye picked it up again to solve the following questions:\n\n<p><strong>Question:</strong> When creating a floor, roof, filled region, etc., a sketch and a sketch plane are required. \nI want to retrieve the sketch and sketch plane from an existing element. \nHowever there is no API to do that. \nCould you please tell me how to find these objects? \n\n<p><strong>Answer:</strong> When creating a floor, slab and filled region etc., you draw a profile to define the element shape.  \nRevit automatically creates a sketch and sketch plane for the profile. \nIf the host element is deleted, the sketch and sketch plane are deleted accordingly. \nThe Document.Delete method returns all deleted element ids. \nThis mechanism can be used as follows to access the desired elements:\n\n<ul>\n<li>Create a temporary transaction.\n<li>Delete the target element inside the transaction.\n<li>The sketch and sketch plane ids are included in the returned element id list. \n<li>Filter out the target elements. \n<li>Roll back the transaction to restore the target and all dependent elements and the model to its original state.\n</li></li></li></li></li></ul>\n<!--\n\n<p>Here is some sample code showing the usage:\n\n<pre class=\"code\">\nusing System;\nusing System.Collections.Generic;\n//using System.Windows.Forms;\nusing Autodesk.Revit.ApplicationServices;\nusing Autodesk.Revit.Attributes;\nusing Autodesk.Revit.DB;\nusing Autodesk.Revit.UI;\nusing Autodesk.Revit.UI.Selection;\n\n\n[TransactionAttribute(TransactionMode.Manual)]\n[RegenerationAttribute(RegenerationOption.Manual)]\npublic class RevitCommand : IExternalCommand\n{\n    public Result Execute(ExternalCommandData commandData,\n      ref string messages,\n      ElementSet elements)\n    {\n      UIApplication app = commandData.Application;\n      UIDocument uiDoc = app.ActiveUIDocument;\n      Document doc = uiDoc.Document;\n\n      Selection sel = uiDoc.Selection;\n      Reference ref1 = sel.PickObject(ObjectType.Element, \"Please pick an element\");\n      Element elem = ref1.Element;\n      Transaction trans = new Transaction(doc);\n      trans.Start(\"test\");\n      ICollection<ElementId> ids = doc.Delete(elem);\n\n      trans.RollBack();\n      string strName = \"Host Id = \" + elem.Id.IntegerValue.ToString() + \"\\r\\n\";\n      foreach (ElementId id in ids)\n      {\n        Element elemIter = doc.get_Element(id);\n        if (elemIter is Sketch || elemIter is SketchPlane)\n        {\n          strName += \"Id = \" + id.IntegerValue.ToString() + \";\" + elemIter.Name\n            + \" ;\" + elemIter.GetType().ToString() + \"\\r\\n\";\n        }\n      }\n\n      TaskDialog.Show(\"test\", strName);\n   \n      return Result.Succeeded;\n    }\n}\n</pre>\n\n-->\n<p>Using this approach, all elements that are closely related with a specified element can be retrieved. \nFor example, the detail lines that form the profile of a wall can be found.\n\n<p>Here is another similar question that can be answered using the same approach:\n\n<p><strong>Question:</strong> I need to find out whether a given wall has an elevation profile and if so which. \nI tried using a filtered element collector to retrieve all sketch objects in the model, but they have no properties that I can use to associate them with the wall.\n\n<p>Is there a way for a given wall element to find if there is a SketchPlane associated with it that defines its elevation profile? \n\n<p>Or, alternatively, is there a way for a given SketchPlane to find which object in the database it is attached to? \n\n<p><strong>Answer:</strong> Just like above, one possible way is to delete the wall in a transaction using Document.Delete, which returns the deleted element ids. The wall and the sketch will be returned in the ElementId list. Then roll back the transaction, so the model remains unchanged.\n\n<p>Here is the resulting list of elements that were deleted due to the deletion of a specific sample wall element hosting them.\nAs you can see, the sketch element is included in the list:</p>\n<center>\n<img alt=\"Wall with sketch\" src=\"img/wall_with_sketch.png\" width=\"400\"/>\n</center>\n<p>I used Joe's suggestion to create a new Building Coder sample external command CmdGetSketchElements to retrieve and list all the sketch elements associated with a selected host.\n\n<p>I added a variable 'showOnlySketchElements' to choose whether to list only the sketch elements, or all related elements.\n\n<p>I first implemented the string building code explicitly, then commented it out and rewrote it using generic Linq methods. \nYou can judge for yourself which variation you find clearer (and see whether you spot the obvious flaw in the StringBuilder implementation (<span id=\"flipped\">the final trailing comma</span>)):\n\n<pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n[<span class=\"teal\">Regeneration</span>( <span class=\"teal\">RegenerationOption</span>.Manual )]\n<span class=\"blue\">class</span> <span class=\"teal\">CmdGetSketchElements</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">const</span> <span class=\"blue\">string</span> _caption = <span class=\"maroon\">\"Retrieve Sketch Elements\"</span>;\n \n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n    <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n    <span class=\"teal\">Application</span> app = uiapp.Application;\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n    <span class=\"teal\">Selection</span> sel = uidoc.Selection;\n \n    <span class=\"teal\">Reference</span> r = sel.PickObject( <span class=\"teal\">ObjectType</span>.Element, \n      <span class=\"maroon\">\"Please pick an element\"</span> );\n \n    <span class=\"teal\">Element</span> elem = r.Element;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n \n    trans.Start( _caption );\n \n    <span class=\"teal\">ICollection</span>&lt;<span class=\"teal\">ElementId</span>&gt; ids = doc.Delete( elem );\n \n    trans.RollBack();\n \n    <span class=\"blue\">bool</span> showOnlySketchElements = <span class=\"blue\">true</span>;\n \n    <span class=\"green\">/*</span>\n<span class=\"green\">    StringBuilder s = new StringBuilder( </span>\n<span class=\"green\">      _caption</span>\n<span class=\"green\">      + \" for host element \"</span>\n<span class=\"green\">      + Util.ElementDescription( elem )</span>\n<span class=\"green\">      + \": \" );</span>\n \n<span class=\"green\">    foreach( ElementId id in ids )</span>\n<span class=\"green\">    {</span>\n<span class=\"green\">      Element e = doc.get_Element( id );</span>\n \n<span class=\"green\">      if( !showOnlySketchElements</span>\n<span class=\"green\">        || e is Sketch</span>\n<span class=\"green\">        || e is SketchPlane )</span>\n<span class=\"green\">      {</span>\n<span class=\"green\">        s.Append( Util.ElementDescription( e ) + \", \" );</span>\n<span class=\"green\">      }</span>\n<span class=\"green\">    }</span>\n<span class=\"green\">    */</span>\n \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; a = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;(\n      ids.Select( id =&gt; doc.get_Element( id ) ) );\n \n    <span class=\"blue\">string</span> s = _caption\n      + <span class=\"maroon\">\" for host element \"</span>\n      + <span class=\"teal\">Util</span>.ElementDescription( elem )\n      + <span class=\"maroon\">\": \"</span>;\n \n    s += <span class=\"blue\">string</span>.Join( <span class=\"maroon\">\", \"</span>,\n      a.Where( e =&gt; !showOnlySketchElements\n        || e <span class=\"blue\">is</span> <span class=\"teal\">Sketch</span>\n        || e <span class=\"blue\">is</span> <span class=\"teal\">SketchPlane</span> )\n      .Select( e =&gt; <span class=\"teal\">Util</span>.ElementDescription( e ) )\n      .ToArray() );\n \n    <span class=\"teal\">Util</span>.InfoMsg( s );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>Here is a simple sample model with a single floor element:\n\n<center>\n<img alt=\"Floor with sketch\" src=\"img/floor_with_sketch.png\"/>\n</center>\n<p>Running the command on this returns the following list of all related elements:\n\n<p>Retrieve Sketch Elements for host element Floors &lt;130589 Generic Floor - 400mm&gt;: SketchPlane &lt;130587 Level 1&gt;, Sketch &lt;130588 Sketch&gt;, Floors &lt;130589 Generic Floor - 400mm&gt;, &lt;Sketch&gt; &lt;130592 Model Lines&gt;, &lt;Sketch&gt; &lt;130595 Model Lines&gt;, &lt;Sketch&gt; &lt;130598 Model Lines&gt;, &lt;Sketch&gt; &lt;130601 Model Lines&gt;, &lt;Sketch&gt; &lt;130604 Model Lines&gt;, &lt;Sketch&gt; &lt;130607 Model Lines&gt;, &lt;Sketch&gt; &lt;130610 Model Lines&gt;, SketchPlane &lt;130621 Level 1&gt;, Sketch &lt;130622 Sketch&gt;, Floor opening cut &lt;130623 Opening Cut&gt;, &lt;Sketch&gt; &lt;130643 Model Lines&gt;, &lt;Sketch&gt; &lt;130667 Model Lines&gt;, &lt;Sketch&gt; &lt;130686 Model Lines&gt;, &lt;Sketch&gt; &lt;130702 Model Lines&gt;, &lt;Sketch&gt; &lt;130721 Model Lines&gt;, &lt;Sketch&gt; &lt;130752 Model Lines&gt;, Automatic Sketch Dimensions &lt;130775 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130776 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130777 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130778 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130779 Linear Dimension Style&gt;, SketchPlane &lt;130832 Level 1&gt;, Sketch &lt;130833 Sketch&gt;, Floor opening cut &lt;130834 Opening Cut&gt;, &lt;Sketch&gt; &lt;130848 Model Lines&gt;, &lt;Sketch&gt; &lt;130861 Model Lines&gt;, &lt;Sketch&gt; &lt;130878 Model Lines&gt;, &lt;Sketch&gt; &lt;130894 Model Lines&gt;, Automatic Sketch Dimensions &lt;130909 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130910 Linear Dimension Style&gt;, SketchPlane &lt;131013 Level 1&gt;, Sketch &lt;131014 Sketch&gt;, Floor opening cut &lt;131015 Opening Cut&gt;, &lt;Sketch&gt; &lt;131062 Model Lines&gt;, Automatic Sketch Dimensions &lt;131065 Linear Dimension Style&gt;\n\n<p>As you can see, there are a large number of elements associated with this floor, including the sketch elements that we are interested in.\n\n<p>Setting 'showOnlySketchElements' to true returns the sketch elements only:\n\n<p>Retrieve Sketch Elements for host element Floors &lt;130589 Generic Floor - 400mm&gt;: SketchPlane &lt;130587 Level 1&gt;, Sketch &lt;130588 Sketch&gt;, SketchPlane &lt;130621 Level 1&gt;, Sketch &lt;130622 Sketch&gt;, SketchPlane &lt;130832 Level 1&gt;, Sketch &lt;130833 Sketch&gt;, SketchPlane &lt;131013 Level 1&gt;, Sketch &lt;131014 Sketch&gt;\n\n<p>Here is\n\n<!-- C:\\a\\doc\\revit\\blog\\zip\\bc_11_81.zip -->\n<a href=\"zip/bc_11_81.zip\">\nversion 2011.0.81.0</a>\n\nof The Building Coder samples including the complete source code and Visual Studio solution with the new command.\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></body>\n</html>"
  },
  {
    "original_filename": "0489_get_sketch",
    "header_text": "Access to Sketch and Sketch Plane",
    "local_header_href": "#access-to-sketch-and-sketch-plane",
    "chunk_text": "<h3>Access to Sketch and Sketch Plane</h3><p>I just presented my first Revit API class here at AU 2010, \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=6943&amp;jid=614479\">\nCP228-2</a>, on the optimal use of the Revit 2011 programming features and the Idling event.\nI already posted my AU\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/09/autodesk-university-2010-classes.html\">\nclass descriptions</a> and\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/autodesk-university-2010-class-materials.html\">\nmaterials</a>.\n\nThe presentation went well and was good fun. \nThe next one, \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=7246&amp;jid=614479\">\nCP234-2</a>,\n\non Revit 2011 programming optimization and filtered element collectors, is scheduled in an hour's time.\nRight now I am sitting in on \n\n<a href=\"http://au.autodesk.com/?nd=event_class&amp;session_id=7107&amp;jid=613470\">\nMatt Mason's presentation on Revit parameters</a>.\n\n<p>Meanwhile, here is another interesting application of the doc.Delete method to access related elements that we already explored several times in the past for determining\n\n<!--\n\n107_room_on_level_in_phase.htm:      doc.Delete( room );\n146_host_reference.htm:&nbsp; &nbsp; delIds = doc.Delete( wall );\n150_unload_family_type.htm:&nbsp; &nbsp; &nbsp; doc.Delete( e );\n216_remove_geometry_rfa.htm:&nbsp; <span class=\"teal\">ElementIdSet</span> ids =\n247_title_block_of_sheet.htm:doc.Delete method to detect dependent elements</a>.\n307_unmodified_geometry.htm:<p>Probably the most reliable way to solve this prob\n314_object_relationship.htm:&nbsp; <span class=\"teal\">ElementIdSet</span> ids =\n334_anonymous_methods_vb.htm:&nbsp; &nbsp; doc.Delete( symbol );\n360_p2c.htm:&nbsp; doc.Delete( pipe );\n419_transaction_migration.htm:&nbsp; &nbsp; delIds = doc.Delete( wall );\n476_purge_text_note_types.htm:&nbsp; doc.Delete( textNoteTypes );\n479_launch_command.htm:&nbsp; &nbsp; <span class=\"green\">// doc.delete(nw) may n\n484_failure_api.htm:&nbsp; &nbsp; doc.Delete( elem );\n488_mirror_in_new_family.htm:&nbsp; familyDoc.Delete(famInst)\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/object-relationships.html\">\nall kinds of useful object relationships</a>.\n\nNow Joe Ye picked it up again to solve the following questions:\n\n<p><strong>Question:</strong> When creating a floor, roof, filled region, etc., a sketch and a sketch plane are required. \nI want to retrieve the sketch and sketch plane from an existing element. \nHowever there is no API to do that. \nCould you please tell me how to find these objects? \n\n<p><strong>Answer:</strong> When creating a floor, slab and filled region etc., you draw a profile to define the element shape.  \nRevit automatically creates a sketch and sketch plane for the profile. \nIf the host element is deleted, the sketch and sketch plane are deleted accordingly. \nThe Document.Delete method returns all deleted element ids. \nThis mechanism can be used as follows to access the desired elements:\n\n<ul>\n<li>Create a temporary transaction.\n<li>Delete the target element inside the transaction.\n<li>The sketch and sketch plane ids are included in the returned element id list. \n<li>Filter out the target elements. \n<li>Roll back the transaction to restore the target and all dependent elements and the model to its original state.\n</li></li></li></li></li></ul>\n<!--\n\n<p>Here is some sample code showing the usage:\n\n<pre class=\"code\">\nusing System;\nusing System.Collections.Generic;\n//using System.Windows.Forms;\nusing Autodesk.Revit.ApplicationServices;\nusing Autodesk.Revit.Attributes;\nusing Autodesk.Revit.DB;\nusing Autodesk.Revit.UI;\nusing Autodesk.Revit.UI.Selection;\n\n\n[TransactionAttribute(TransactionMode.Manual)]\n[RegenerationAttribute(RegenerationOption.Manual)]\npublic class RevitCommand : IExternalCommand\n{\n    public Result Execute(ExternalCommandData commandData,\n      ref string messages,\n      ElementSet elements)\n    {\n      UIApplication app = commandData.Application;\n      UIDocument uiDoc = app.ActiveUIDocument;\n      Document doc = uiDoc.Document;\n\n      Selection sel = uiDoc.Selection;\n      Reference ref1 = sel.PickObject(ObjectType.Element, \"Please pick an element\");\n      Element elem = ref1.Element;\n      Transaction trans = new Transaction(doc);\n      trans.Start(\"test\");\n      ICollection<ElementId> ids = doc.Delete(elem);\n\n      trans.RollBack();\n      string strName = \"Host Id = \" + elem.Id.IntegerValue.ToString() + \"\\r\\n\";\n      foreach (ElementId id in ids)\n      {\n        Element elemIter = doc.get_Element(id);\n        if (elemIter is Sketch || elemIter is SketchPlane)\n        {\n          strName += \"Id = \" + id.IntegerValue.ToString() + \";\" + elemIter.Name\n            + \" ;\" + elemIter.GetType().ToString() + \"\\r\\n\";\n        }\n      }\n\n      TaskDialog.Show(\"test\", strName);\n   \n      return Result.Succeeded;\n    }\n}\n</pre>\n\n-->\n<p>Using this approach, all elements that are closely related with a specified element can be retrieved. \nFor example, the detail lines that form the profile of a wall can be found.\n\n<p>Here is another similar question that can be answered using the same approach:\n\n<p><strong>Question:</strong> I need to find out whether a given wall has an elevation profile and if so which. \nI tried using a filtered element collector to retrieve all sketch objects in the model, but they have no properties that I can use to associate them with the wall.\n\n<p>Is there a way for a given wall element to find if there is a SketchPlane associated with it that defines its elevation profile? \n\n<p>Or, alternatively, is there a way for a given SketchPlane to find which object in the database it is attached to? \n\n<p><strong>Answer:</strong> Just like above, one possible way is to delete the wall in a transaction using Document.Delete, which returns the deleted element ids. The wall and the sketch will be returned in the ElementId list. Then roll back the transaction, so the model remains unchanged.\n\n<p>Here is the resulting list of elements that were deleted due to the deletion of a specific sample wall element hosting them.\nAs you can see, the sketch element is included in the list:</p>\n<center>\n<img alt=\"Wall with sketch\" src=\"img/wall_with_sketch.png\" width=\"400\"/>\n</center>\n<p>I used Joe's suggestion to create a new Building Coder sample external command CmdGetSketchElements to retrieve and list all the sketch elements associated with a selected host.\n\n<p>I added a variable 'showOnlySketchElements' to choose whether to list only the sketch elements, or all related elements.\n\n<p>I first implemented the string building code explicitly, then commented it out and rewrote it using generic Linq methods. \nYou can judge for yourself which variation you find clearer (and see whether you spot the obvious flaw in the StringBuilder implementation (<span id=\"flipped\">the final trailing comma</span>)):\n\n<pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n[<span class=\"teal\">Regeneration</span>( <span class=\"teal\">RegenerationOption</span>.Manual )]\n<span class=\"blue\">class</span> <span class=\"teal\">CmdGetSketchElements</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">const</span> <span class=\"blue\">string</span> _caption = <span class=\"maroon\">\"Retrieve Sketch Elements\"</span>;\n \n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n    <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n    <span class=\"teal\">Application</span> app = uiapp.Application;\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n    <span class=\"teal\">Selection</span> sel = uidoc.Selection;\n \n    <span class=\"teal\">Reference</span> r = sel.PickObject( <span class=\"teal\">ObjectType</span>.Element, \n      <span class=\"maroon\">\"Please pick an element\"</span> );\n \n    <span class=\"teal\">Element</span> elem = r.Element;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n \n    trans.Start( _caption );\n \n    <span class=\"teal\">ICollection</span>&lt;<span class=\"teal\">ElementId</span>&gt; ids = doc.Delete( elem );\n \n    trans.RollBack();\n \n    <span class=\"blue\">bool</span> showOnlySketchElements = <span class=\"blue\">true</span>;\n \n    <span class=\"green\">/*</span>\n<span class=\"green\">    StringBuilder s = new StringBuilder( </span>\n<span class=\"green\">      _caption</span>\n<span class=\"green\">      + \" for host element \"</span>\n<span class=\"green\">      + Util.ElementDescription( elem )</span>\n<span class=\"green\">      + \": \" );</span>\n \n<span class=\"green\">    foreach( ElementId id in ids )</span>\n<span class=\"green\">    {</span>\n<span class=\"green\">      Element e = doc.get_Element( id );</span>\n \n<span class=\"green\">      if( !showOnlySketchElements</span>\n<span class=\"green\">        || e is Sketch</span>\n<span class=\"green\">        || e is SketchPlane )</span>\n<span class=\"green\">      {</span>\n<span class=\"green\">        s.Append( Util.ElementDescription( e ) + \", \" );</span>\n<span class=\"green\">      }</span>\n<span class=\"green\">    }</span>\n<span class=\"green\">    */</span>\n \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; a = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;(\n      ids.Select( id =&gt; doc.get_Element( id ) ) );\n \n    <span class=\"blue\">string</span> s = _caption\n      + <span class=\"maroon\">\" for host element \"</span>\n      + <span class=\"teal\">Util</span>.ElementDescription( elem )\n      + <span class=\"maroon\">\": \"</span>;\n \n    s += <span class=\"blue\">string</span>.Join( <span class=\"maroon\">\", \"</span>,\n      a.Where( e =&gt; !showOnlySketchElements\n        || e <span class=\"blue\">is</span> <span class=\"teal\">Sketch</span>\n        || e <span class=\"blue\">is</span> <span class=\"teal\">SketchPlane</span> )\n      .Select( e =&gt; <span class=\"teal\">Util</span>.ElementDescription( e ) )\n      .ToArray() );\n \n    <span class=\"teal\">Util</span>.InfoMsg( s );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>Here is a simple sample model with a single floor element:\n\n<center>\n<img alt=\"Floor with sketch\" src=\"img/floor_with_sketch.png\"/>\n</center>\n<p>Running the command on this returns the following list of all related elements:\n\n<p>Retrieve Sketch Elements for host element Floors &lt;130589 Generic Floor - 400mm&gt;: SketchPlane &lt;130587 Level 1&gt;, Sketch &lt;130588 Sketch&gt;, Floors &lt;130589 Generic Floor - 400mm&gt;, &lt;Sketch&gt; &lt;130592 Model Lines&gt;, &lt;Sketch&gt; &lt;130595 Model Lines&gt;, &lt;Sketch&gt; &lt;130598 Model Lines&gt;, &lt;Sketch&gt; &lt;130601 Model Lines&gt;, &lt;Sketch&gt; &lt;130604 Model Lines&gt;, &lt;Sketch&gt; &lt;130607 Model Lines&gt;, &lt;Sketch&gt; &lt;130610 Model Lines&gt;, SketchPlane &lt;130621 Level 1&gt;, Sketch &lt;130622 Sketch&gt;, Floor opening cut &lt;130623 Opening Cut&gt;, &lt;Sketch&gt; &lt;130643 Model Lines&gt;, &lt;Sketch&gt; &lt;130667 Model Lines&gt;, &lt;Sketch&gt; &lt;130686 Model Lines&gt;, &lt;Sketch&gt; &lt;130702 Model Lines&gt;, &lt;Sketch&gt; &lt;130721 Model Lines&gt;, &lt;Sketch&gt; &lt;130752 Model Lines&gt;, Automatic Sketch Dimensions &lt;130775 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130776 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130777 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130778 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130779 Linear Dimension Style&gt;, SketchPlane &lt;130832 Level 1&gt;, Sketch &lt;130833 Sketch&gt;, Floor opening cut &lt;130834 Opening Cut&gt;, &lt;Sketch&gt; &lt;130848 Model Lines&gt;, &lt;Sketch&gt; &lt;130861 Model Lines&gt;, &lt;Sketch&gt; &lt;130878 Model Lines&gt;, &lt;Sketch&gt; &lt;130894 Model Lines&gt;, Automatic Sketch Dimensions &lt;130909 Linear Dimension Style&gt;, Automatic Sketch Dimensions &lt;130910 Linear Dimension Style&gt;, SketchPlane &lt;131013 Level 1&gt;, Sketch &lt;131014 Sketch&gt;, Floor opening cut &lt;131015 Opening Cut&gt;, &lt;Sketch&gt; &lt;131062 Model Lines&gt;, Automatic Sketch Dimensions &lt;131065 Linear Dimension Style&gt;\n\n<p>As you can see, there are a large number of elements associated with this floor, including the sketch elements that we are interested in.\n\n<p>Setting 'showOnlySketchElements' to true returns the sketch elements only:\n\n<p>Retrieve Sketch Elements for host element Floors &lt;130589 Generic Floor - 400mm&gt;: SketchPlane &lt;130587 Level 1&gt;, Sketch &lt;130588 Sketch&gt;, SketchPlane &lt;130621 Level 1&gt;, Sketch &lt;130622 Sketch&gt;, SketchPlane &lt;130832 Level 1&gt;, Sketch &lt;130833 Sketch&gt;, SketchPlane &lt;131013 Level 1&gt;, Sketch &lt;131014 Sketch&gt;\n\n<p>Here is\n\n<!-- C:\\a\\doc\\revit\\blog\\zip\\bc_11_81.zip -->\n<a href=\"zip/bc_11_81.zip\">\nversion 2011.0.81.0</a>\n\nof The Building Coder samples including the complete source code and Visual Studio solution with the new command.\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]