[
  {
    "original_filename": "0579_set_preview_image",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0579_set_preview_image",
    "header_text": "Set Preview Image",
    "local_header_href": "#set-preview-image",
    "chunk_text": "<h3>Set Preview Image</h3><p>While I am \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/improved-mep-element-shape-and-mount-ararat.html#2\">\naway</a>, \n\nhere is a useful article to keep you occupied by my colleague Saikat Bhattacharya:\n\n<h3>Setting preview image/view for a Revit document using Revit 2012 API</h3>\n<p><strong>Question:</strong> How can I set the preview image/view for a Revit document using the Revit 2012 API?\nIn particular, when I load an older version of Revit document and do a SaveAs using the API, how can I set its preview image? \n\n\n<p><strong>Answer:</strong> There are two ways to set a preview image on a Revit document using the API.\n\n<p>The first approach uses DocumentPreviewSettings to assign a permanent view to the document to always be used for preview settings. This is done by serializing this preview id into the document. Using this approach, the preview view will be permanently set for the document.\n\n<p>In the user interface, when we save a file, typically a permanent view for the preview generation is not assigned. It is only assigned if the users click on the Options button in the SaveAs dialog and select a view other than 'Active view/sheet' in the Preview Source of the dialog. It is this permanent view that can be extracted and set using the DocumentPreviewSettings API. If there is no permanent preview view assigned here, Revit will use the default active view/sheet to generate the preview.\n\n<p>The other approach set a temporary preview view id which will be used during the single save operation and is not serialized to the document. This can be done using the Document.Save(SaveOptions) or Document.SaveAs(SaveAsOptions). Both these option classes have a setting for the preview view id.\n\n<p>In a typical use case of OpenDocumentFile(), performing certain changes to the document and then saving the file either using a Save or SaveAs results in Revit having no way to know how to save a preview and so previews are lost. This is where Save(SaveOptions) or SaveAs(SaveAsOptions) helps. However, setting the temporary preview view settings using the save options can become challenging since API users would still not know which view to be set as preview – the Document.ActiveView does not work for an un-displayed document. Here, there are two ways of approaching this:\n\n<p><strong>1.</strong> Using a new API called StartingViewSettings, which helps access the initial view settings for a document which returns the view that will be initially opened when a model is opened. This view is usually set by the user and can be accessed from the user interface by accessing the 'Manage' tab in which we need to click on the 'Starting View' button. If API users get a valid view from the StartingViewSettings and end up using this for setting the preview view, it is recommended that this view be set as preview using the temporary setting (which is to use the Save(SaveOptions) or the SaveAs(SaveAsOptions) method and not the DocumentPreviewSettings. StartingViewSettings works only for Revit projects and will throw an exception if used with a Revit family file (RFA). If the starting view has not been set by the user, we will see '&lt;Last Viewed&gt;' as the current settings. On the API side, this means that the StartingViewSettings.ViewId will return a InvalidElementId in which case we need to follow the second approach.\n\n<p><strong>2.</strong> The other approach is to make an algorithmic choice e.g. finding the 3D view (ensuring that this is not a template) and using this view as temporary preview view setting. If no 3D views are found, then the API user can decide on using plan views instead, etc. If you end up using this algorithmic approach for setting the preview view, it is recommended that the preview be set using the temporary setting (which is to use the Save(SaveOptions) or the SaveAs(SaveAsOptions) method and not the DocumentPreviewSettings. \n\n<p>The following lines of code show a typical use of the various APIs which help in setting the preview. \nIt covers all the various approaches mentioned above:\n\n<pre class=\"code\">\n  <span class=\"green\">// Open Revit file</span>\n  <span class=\"teal\">Document</span> doc = cmdData.Application.Application\n    .OpenDocumentFile( file.FullName );\n \n  <span class=\"green\">// Create transaction and start</span>\n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"T1\"</span> );\n  trans.Start();\n \n  doc.Regenerate();\n \n  <span class=\"green\">// Create thumbnails for preview </span>\n  <span class=\"teal\">DocumentPreviewSettings</span> previewSettings =\n    doc.GetDocumentPreviewSettings();\n \n  <span class=\"teal\">SaveAsOptions</span> saveOpts = <span class=\"blue\">new</span> <span class=\"teal\">SaveAsOptions</span>();\n \n  <span class=\"green\">// Check for permanent preview view</span>\n  <span class=\"blue\">if</span>( doc\n    .GetDocumentPreviewSettings()\n    .PreviewViewId\n    .Equals( <span class=\"teal\">ElementId</span>.InvalidElementId ) )\n  {\n    <span class=\"green\">// Access the intial view</span>\n    <span class=\"teal\">StartingViewSettings</span> startingViewSettings \n      = <span class=\"teal\">StartingViewSettings</span>.GetStartingViewSettings( \n        doc );\n \n    <span class=\"blue\">if</span>( !startingViewSettings.ViewId.Equals( \n      <span class=\"teal\">ElementId</span>.InvalidElementId ) )\n    {\n      <span class=\"green\">// If valid, then set the viewId</span>\n      <span class=\"green\">//previewSettings.PreviewViewId </span>\n      <span class=\"green\">//  = startingViewSettings.ViewId;</span>\n \n      saveOpts.PreviewViewId \n        = startingViewSettings.ViewId;\n    }\n    <span class=\"blue\">else</span>\n    {\n      <span class=\"green\">// Algorithmic approach - look for 3D views</span>\n \n      <span class=\"teal\">FilteredElementCollector</span> collector \n        = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n          .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">View</span> ) );\n \n      IEnumerable views \n        = <span class=\"blue\">from</span> Autodesk.Revit.DB.<span class=\"teal\">View</span> f\n          <span class=\"blue\">in</span> collector\n          <span class=\"blue\">where</span> ( f.ViewType == <span class=\"teal\">ViewType</span>.ThreeD\n            &amp;&amp; !f.IsTemplate )\n          <span class=\"blue\">select</span> f;\n \n      <span class=\"blue\">bool</span> bNotFound = <span class=\"blue\">true</span>;\n \n      <span class=\"blue\">foreach</span>( <span class=\"teal\">View</span> vw <span class=\"blue\">in</span> views )\n      {\n        <span class=\"blue\">if</span>( !vw.IsTemplate )\n        {\n          <span class=\"green\">//If we were to set the preview view permanently, </span>\n          <span class=\"green\">// we would use the following two commented lines</span>\n          <span class=\"green\">//previewSettings.PreviewViewId = vw.Id;</span>\n          <span class=\"green\">//previewSettings.ForceViewUpdate( true );</span>\n \n          <span class=\"green\">// Set the temporary view</span>\n          saveOpts.PreviewViewId = vw.Id;\n          bNotFound = <span class=\"blue\">false</span>;\n          <span class=\"blue\">break</span>;\n        }\n      }\n \n      <span class=\"green\">// If no 3D view is obtained, look for other valid views</span>\n      <span class=\"blue\">if</span>( bNotFound )\n      {\n        IEnumerable viewsNon3D\n          = <span class=\"blue\">from</span> <span class=\"teal\">View</span> fNon3D\n            <span class=\"blue\">in</span> collector\n            <span class=\"blue\">where</span> ( fNon3D.ViewType == <span class=\"teal\">ViewType</span>.FloorPlan\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.EngineeringPlan\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.Elevation\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.Section\n              &amp;&amp; !fNon3D.IsTemplate )\n            <span class=\"blue\">select</span> fNon3D;\n \n        <span class=\"blue\">foreach</span>( <span class=\"teal\">View</span> vw <span class=\"blue\">in</span> viewsNon3D )\n        {\n          <span class=\"blue\">if</span>( !vw.IsTemplate )\n          {\n            <span class=\"green\">// If we were to set the preview view permanently, </span>\n            <span class=\"green\">// we would use the following two commented lines</span>\n            <span class=\"green\">//previewSettings.PreviewViewId = vw.Id;</span>\n            <span class=\"green\">//previewSettings.ForceViewUpdate( true );</span>\n \n            saveOpts.PreviewViewId = vw.Id;\n            <span class=\"blue\">break</span>;\n          }\n        }\n      }\n    }\n  }\n \n  <span class=\"green\">// Commit transaction</span>\n  trans.Commit();\n \n  <span class=\"green\">// Save Revit file to target destination</span>\n  doc.SaveAs( destPath + <span class=\"maroon\">\"\\\\\"</span> + file.Name, saveOpts );\n \n  <span class=\"green\">// Close document</span>\n  doc.Close();\n \n</pre>\n<p>Many thanks to Saikat for this useful explanation!\n</p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0579_set_preview_image",
    "header_text": "Setting preview image/view for a Revit document using Revit 2012 API",
    "local_header_href": "#setting-preview-imageview-for-a-revit-document-using-revit-2012-api",
    "chunk_text": "<h3>Setting preview image/view for a Revit document using Revit 2012 API</h3><p><strong>Question:</strong> How can I set the preview image/view for a Revit document using the Revit 2012 API?\nIn particular, when I load an older version of Revit document and do a SaveAs using the API, how can I set its preview image? \n\n\n<p><strong>Answer:</strong> There are two ways to set a preview image on a Revit document using the API.\n\n<p>The first approach uses DocumentPreviewSettings to assign a permanent view to the document to always be used for preview settings. This is done by serializing this preview id into the document. Using this approach, the preview view will be permanently set for the document.\n\n<p>In the user interface, when we save a file, typically a permanent view for the preview generation is not assigned. It is only assigned if the users click on the Options button in the SaveAs dialog and select a view other than 'Active view/sheet' in the Preview Source of the dialog. It is this permanent view that can be extracted and set using the DocumentPreviewSettings API. If there is no permanent preview view assigned here, Revit will use the default active view/sheet to generate the preview.\n\n<p>The other approach set a temporary preview view id which will be used during the single save operation and is not serialized to the document. This can be done using the Document.Save(SaveOptions) or Document.SaveAs(SaveAsOptions). Both these option classes have a setting for the preview view id.\n\n<p>In a typical use case of OpenDocumentFile(), performing certain changes to the document and then saving the file either using a Save or SaveAs results in Revit having no way to know how to save a preview and so previews are lost. This is where Save(SaveOptions) or SaveAs(SaveAsOptions) helps. However, setting the temporary preview view settings using the save options can become challenging since API users would still not know which view to be set as preview – the Document.ActiveView does not work for an un-displayed document. Here, there are two ways of approaching this:\n\n<p><strong>1.</strong> Using a new API called StartingViewSettings, which helps access the initial view settings for a document which returns the view that will be initially opened when a model is opened. This view is usually set by the user and can be accessed from the user interface by accessing the 'Manage' tab in which we need to click on the 'Starting View' button. If API users get a valid view from the StartingViewSettings and end up using this for setting the preview view, it is recommended that this view be set as preview using the temporary setting (which is to use the Save(SaveOptions) or the SaveAs(SaveAsOptions) method and not the DocumentPreviewSettings. StartingViewSettings works only for Revit projects and will throw an exception if used with a Revit family file (RFA). If the starting view has not been set by the user, we will see '&lt;Last Viewed&gt;' as the current settings. On the API side, this means that the StartingViewSettings.ViewId will return a InvalidElementId in which case we need to follow the second approach.\n\n<p><strong>2.</strong> The other approach is to make an algorithmic choice e.g. finding the 3D view (ensuring that this is not a template) and using this view as temporary preview view setting. If no 3D views are found, then the API user can decide on using plan views instead, etc. If you end up using this algorithmic approach for setting the preview view, it is recommended that the preview be set using the temporary setting (which is to use the Save(SaveOptions) or the SaveAs(SaveAsOptions) method and not the DocumentPreviewSettings. \n\n<p>The following lines of code show a typical use of the various APIs which help in setting the preview. \nIt covers all the various approaches mentioned above:\n\n<pre class=\"code\">\n  <span class=\"green\">// Open Revit file</span>\n  <span class=\"teal\">Document</span> doc = cmdData.Application.Application\n    .OpenDocumentFile( file.FullName );\n \n  <span class=\"green\">// Create transaction and start</span>\n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"T1\"</span> );\n  trans.Start();\n \n  doc.Regenerate();\n \n  <span class=\"green\">// Create thumbnails for preview </span>\n  <span class=\"teal\">DocumentPreviewSettings</span> previewSettings =\n    doc.GetDocumentPreviewSettings();\n \n  <span class=\"teal\">SaveAsOptions</span> saveOpts = <span class=\"blue\">new</span> <span class=\"teal\">SaveAsOptions</span>();\n \n  <span class=\"green\">// Check for permanent preview view</span>\n  <span class=\"blue\">if</span>( doc\n    .GetDocumentPreviewSettings()\n    .PreviewViewId\n    .Equals( <span class=\"teal\">ElementId</span>.InvalidElementId ) )\n  {\n    <span class=\"green\">// Access the intial view</span>\n    <span class=\"teal\">StartingViewSettings</span> startingViewSettings \n      = <span class=\"teal\">StartingViewSettings</span>.GetStartingViewSettings( \n        doc );\n \n    <span class=\"blue\">if</span>( !startingViewSettings.ViewId.Equals( \n      <span class=\"teal\">ElementId</span>.InvalidElementId ) )\n    {\n      <span class=\"green\">// If valid, then set the viewId</span>\n      <span class=\"green\">//previewSettings.PreviewViewId </span>\n      <span class=\"green\">//  = startingViewSettings.ViewId;</span>\n \n      saveOpts.PreviewViewId \n        = startingViewSettings.ViewId;\n    }\n    <span class=\"blue\">else</span>\n    {\n      <span class=\"green\">// Algorithmic approach - look for 3D views</span>\n \n      <span class=\"teal\">FilteredElementCollector</span> collector \n        = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n          .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">View</span> ) );\n \n      IEnumerable views \n        = <span class=\"blue\">from</span> Autodesk.Revit.DB.<span class=\"teal\">View</span> f\n          <span class=\"blue\">in</span> collector\n          <span class=\"blue\">where</span> ( f.ViewType == <span class=\"teal\">ViewType</span>.ThreeD\n            &amp;&amp; !f.IsTemplate )\n          <span class=\"blue\">select</span> f;\n \n      <span class=\"blue\">bool</span> bNotFound = <span class=\"blue\">true</span>;\n \n      <span class=\"blue\">foreach</span>( <span class=\"teal\">View</span> vw <span class=\"blue\">in</span> views )\n      {\n        <span class=\"blue\">if</span>( !vw.IsTemplate )\n        {\n          <span class=\"green\">//If we were to set the preview view permanently, </span>\n          <span class=\"green\">// we would use the following two commented lines</span>\n          <span class=\"green\">//previewSettings.PreviewViewId = vw.Id;</span>\n          <span class=\"green\">//previewSettings.ForceViewUpdate( true );</span>\n \n          <span class=\"green\">// Set the temporary view</span>\n          saveOpts.PreviewViewId = vw.Id;\n          bNotFound = <span class=\"blue\">false</span>;\n          <span class=\"blue\">break</span>;\n        }\n      }\n \n      <span class=\"green\">// If no 3D view is obtained, look for other valid views</span>\n      <span class=\"blue\">if</span>( bNotFound )\n      {\n        IEnumerable viewsNon3D\n          = <span class=\"blue\">from</span> <span class=\"teal\">View</span> fNon3D\n            <span class=\"blue\">in</span> collector\n            <span class=\"blue\">where</span> ( fNon3D.ViewType == <span class=\"teal\">ViewType</span>.FloorPlan\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.EngineeringPlan\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.Elevation\n              || fNon3D.ViewType == <span class=\"teal\">ViewType</span>.Section\n              &amp;&amp; !fNon3D.IsTemplate )\n            <span class=\"blue\">select</span> fNon3D;\n \n        <span class=\"blue\">foreach</span>( <span class=\"teal\">View</span> vw <span class=\"blue\">in</span> viewsNon3D )\n        {\n          <span class=\"blue\">if</span>( !vw.IsTemplate )\n          {\n            <span class=\"green\">// If we were to set the preview view permanently, </span>\n            <span class=\"green\">// we would use the following two commented lines</span>\n            <span class=\"green\">//previewSettings.PreviewViewId = vw.Id;</span>\n            <span class=\"green\">//previewSettings.ForceViewUpdate( true );</span>\n \n            saveOpts.PreviewViewId = vw.Id;\n            <span class=\"blue\">break</span>;\n          }\n        }\n      }\n    }\n  }\n \n  <span class=\"green\">// Commit transaction</span>\n  trans.Commit();\n \n  <span class=\"green\">// Save Revit file to target destination</span>\n  doc.SaveAs( destPath + <span class=\"maroon\">\"\\\\\"</span> + file.Name, saveOpts );\n \n  <span class=\"green\">// Close document</span>\n  doc.Close();\n \n</pre>\n<p>Many thanks to Saikat for this useful explanation!\n</p></p></p></p></p></p></p></p></p></p>"
  }
]