[
  {
    "original_filename": "0663_set_new_pipe_type_prop",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0663_set_new_pipe_type_prop",
    "header_text": "Set New Pipe Type Properties",
    "local_header_href": "#set-new-pipe-type-properties",
    "chunk_text": "<h3>Set New Pipe Type Properties</h3><p>Here is an interesting Revit MEP API question on setting the preferred elbow, tee and junction type information after creating a new Revit MEP pipe type, answered by my colleague Joe Ye in Beijing:\n\n<p><strong>Question:</strong> I am creating a new Revit MEP pipe type by filtering for all element types of the category OST_PipeCurves and selecting the one named \"Standard\".\nOn the resulting new ElementType instance, I would like to define the preferred settings as follows:\n\n<ul>\n<li>Change the preferred elbow from 'Elbow - Generic: Standard ' to 'Elbow - Thread - MI - Class 150: Standard'.\n<li>Change the preferred tee from 'Tee - Generic: Standard' to 'Tee - Thread - MI - Class 150: Standard'.\n<li>Change the preferred junction type from 'Tee' to 'Tap'.\n</li></li></li></ul>\n<p>Can you show me in C# how to achieve this, please?\n\n\n<p><strong>Answer:</strong> These three changes can be achieved by changing the values of some properties on the PipeType element:\n\n<ul>\n<li>Elbow: the default elbow fitting of the MEP curve type. \n<li>Tee: the default tee fitting of the MEP curve type.\n<li>PreferredJunctionType: the preferred junction type of the MEP curve type.\n</li></li></li></ul>\n<p>The values stored in the first two properties are family symbols.\nYou need to find the desired target element in the Revit database and assign it to them.\n\n<p>For example, for the elbow, you can filter out the desired FamilySymbol 'Elbow - Thread - MI - Class 150: Standard'. \nThis element's class is 'FamilySymbol' and its built-in category is 'OST_PipeFitting'.\nUse these two filters and the traverse the returned element collection to find the target FamilySymbol by name comparison, and assign it to the Elbow property.\n\n<p>Instead of using the PipeType Elbow property, you can also use the generic Revit parameter access and the appropriate built-in parameter.\nThis can be determined by exploring an existing pipe type using the RevitLookup database snoop tool.\nIn that case, you can assign the value by calling the Parameter.Set(ElementId) method and passing in the family symbol element id.\n\n<p>Setting the desired tee is similar to the elbow.\nIn this case, you can filter out the target FamilySymbol 'Tee - Thread - MI - Class 150: Standard' and assign it to the Tee property, or its element id to the equivalent parameter.\n\n<p>For the preferred Junction Type, you specify your choice using an integer value to indicate one of the two available options. \n0 indicates Tap, and 1 indicates Tee.\n\n<p>So in your case, you would assign the integer value 0 to the 'Preferred Junction Type' property or parameter.\n\n<p>The complete code making use of the generic parameter access might look like this:\n\n<pre class=\"code\">\n<span class=\"blue\">using</span> System;\n<span class=\"blue\">using</span> System.Collections.Generic;\n<span class=\"blue\">using</span> System.Linq;\n<span class=\"blue\">using</span> Autodesk.Revit.ApplicationServices;\n<span class=\"blue\">using</span> Autodesk.Revit.Attributes;\n<span class=\"blue\">using</span> Autodesk.Revit.DB;\n<span class=\"blue\">using</span> Autodesk.Revit.DB.Plumbing;\n<span class=\"blue\">using</span> Autodesk.Revit.UI;\n \n[<span class=\"teal\">TransactionAttribute</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RevitCommand</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute( \n    <span class=\"teal\">ExternalCommandData</span> commandData, \n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages, \n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> app = commandData.Application;\n    <span class=\"teal\">Document</span> rvtDoc = app.ActiveUIDocument.Document;\n \n    <span class=\"teal\">FilteredElementCollector</span> collector \n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( rvtDoc );\n \n    collector.OfCategory( <span class=\"teal\">BuiltInCategory</span>.OST_PipeCurves );\n    collector.OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">ElementType</span> ) );\n \n    <span class=\"teal\">PipeType</span> pipeType = <span class=\"blue\">null</span>;\n\n    <span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> ptype <span class=\"blue\">in</span> collector )\n    {\n      <span class=\"blue\">if</span>( <span class=\"blue\">string</span>.Compare( ptype.Name, <span class=\"maroon\">\"standard\"</span>, <span class=\"blue\">true</span> ) == 0 )\n      {\n        pipeType = ptype <span class=\"blue\">as</span> <span class=\"teal\">PipeType</span>;\n        <span class=\"blue\">break</span>;\n      }\n    }\n \n    <span class=\"blue\">if</span>( pipeType != <span class=\"blue\">null</span> )\n    {\n      <span class=\"blue\">string</span> name = <span class=\"maroon\">\"ADNNewType\"</span>;\n \n      <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( rvtDoc )\n      trans.Start(  <span class=\"maroon\">\"Set Pipe Type Information\"</span> );\n \n      <span class=\"teal\">ElementType</span> newType = pipeType.Duplicate( name );\n \n      <span class=\"blue\">if</span>( newType != <span class=\"blue\">null</span> )\n      {\n        <span class=\"teal\">ElementId</span> id1 = FindFamilyType( rvtDoc, \n          <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilySymbol</span> ), \n          <span class=\"maroon\">\"Elbow - Threaded - MI - Class 150\"</span>, <span class=\"maroon\">\"Standard\"</span>, \n          <span class=\"teal\">BuiltInCategory</span>.OST_PipeFitting ).Id;\n \n        <span class=\"teal\">ElementId</span> id2 = FindFamilyType( rvtDoc, \n          <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilySymbol</span> ), \n          <span class=\"maroon\">\"Tee - Threaded - MI - Class 150\"</span>, <span class=\"maroon\">\"Standard\"</span>, \n          <span class=\"teal\">BuiltInCategory</span>.OST_PipeFitting ).Id;\n \n        newType.get_Parameter( \n          <span class=\"teal\">BuiltInParameter</span>.RBS_CURVETYPE_DEFAULT_ELBOW_PARAM )\n            .Set( id1 );\n \n        newType.get_Parameter( \n          <span class=\"teal\">BuiltInParameter</span>.RBS_CURVETYPE_DEFAULT_TEE_PARAM )\n            .Set( id2 );\n \n        newType.get_Parameter( \n          <span class=\"teal\">BuiltInParameter</span>.RBS_CURVETYPE_PREFERRED_BRANCH_PARAM )\n            .Set( 0 );\n      }\n      trans.Commit();\n    }\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Find an element of the given type, name, </span>\n  <span class=\"gray\">///</span><span class=\"green\"> and category (optional).</span>\n  <span class=\"gray\">///</span><span class=\"green\"> You can use this, for example, to find a </span>\n  <span class=\"gray\">///</span><span class=\"green\"> specific wall and window family with the </span>\n  <span class=\"gray\">///</span><span class=\"green\"> given name, e.g.:</span>\n  <span class=\"gray\">///</span><span class=\"green\"> FindFamilyType( _doc, GetType(WallType), </span>\n  <span class=\"gray\">///</span><span class=\"green\">   \"Basic Wall\", \"Generic - 200mm\" ) </span>\n  <span class=\"gray\">///</span><span class=\"green\"> FindFamilyType( _doc, GetType(FamilySymbol), </span>\n  <span class=\"gray\">///</span><span class=\"green\">   \"M_Single-Flush\", \"0915 x 2134mm\", </span>\n  <span class=\"gray\">///</span><span class=\"green\">   BuiltInCategory.OST_Doors ) </span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">Element</span> FindFamilyType( \n    <span class=\"teal\">Document</span> rvtDoc, \n    <span class=\"teal\">Type</span> targetType,\n    <span class=\"blue\">string</span> targetFamilyName, \n    <span class=\"blue\">string</span> targetTypeName, \n    <span class=\"teal\">Nullable</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt; targetCategory )\n  {\n    <span class=\"blue\">var</span> collector \n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( rvtDoc )\n        .OfClass( targetType );\n \n    <span class=\"blue\">if</span>( targetCategory.HasValue )\n    {\n      collector.OfCategory( targetCategory.Value );\n    }\n \n    <span class=\"green\">// Parse the collection for the given names </span>\n    <span class=\"green\">// using LINQ</span>\n \n    <span class=\"blue\">var</span> targetElems =\n        <span class=\"blue\">from</span> element <span class=\"blue\">in</span> collector\n        <span class=\"blue\">where</span> element.Name.Equals( targetTypeName ) \n          &amp;&amp; element.get_Parameter( \n            <span class=\"teal\">BuiltInParameter</span>.SYMBOL_FAMILY_NAME_PARAM )\n              .AsString().Equals( targetFamilyName )\n        <span class=\"blue\">select</span> element;\n \n    <span class=\"green\">// Put the result as a list of element fo accessibility. </span>\n \n    <span class=\"teal\">IList</span>&lt;<span class=\"teal\">Element</span>&gt; elems = targetElems.ToList();\n \n    <span class=\"green\">// Return the result.</span>\n \n    <span class=\"blue\">if</span>( elems.Count &gt; 0 )\n    {\n      <span class=\"blue\">return</span> elems[0];\n    }\n    <span class=\"blue\">return</span> <span class=\"blue\">null</span>;\n  }\n}\n</pre>\n<p>By the way, these preferred element options can also be set to None.\nThis is achieved just like we described for \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/08/set-underlay-display-property-to-none.html\">\nsetting the underlay display property</a>,\n\nby using the parameter setting approach and providing ElementId.InvalidElementId as a value, e.g.\n\n<pre class=\"code\">\n    newType.get_Parameter( \n      <span class=\"teal\">BuiltInParameter</span>.RBS_CURVETYPE_DEFAULT_ELBOW_PARAM )\n        .Set( ElementId.InvalidElementId );\n</pre>\n<p>Many thanks to Joe for this solution!\n</p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]