[
  {
    "original_filename": "0724_host_reference_plane",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0724_host_reference_plane",
    "header_text": "Hosting a Light Fitting on a Reference Plane",
    "local_header_href": "#hosting-a-light-fitting-on-a-reference-plane",
    "chunk_text": "<h3>Hosting a Light Fitting on a Reference Plane</h3><p>It is sometimes a challenge to determine which of the numerous \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/01/newfamilyinstance-overloads.html\">\noverloads of the NewFamilyInstance method</a> to \n\nuse to achieve a desired effect.\nHere is a question on using it to host a light fitting by Simon Jones, with an initial answer by Saikat Bhattacharya, followed by lots more research by Simon to nail down the right solution that really works.\n\n<p><strong>Question:</strong> How can I host a light fitting onto a reference plane?\n\n<p>I tried several different ways without any luck so far.\n\n<p>When I use the following, the light is hosted by the reference plane but doesn't move with it:\n\n<pre class=\"code\">\n  mRevitDoc.Document.Create.NewFamilyInstance(\n    pt, mFamilySymbol, refDir, mReferencePlane,\n    StructuralType.NonStructural);\n</pre>\n<p>What should I use instead to make the fitting remain attached to the plane at all times?\n\n<p><strong>Answer:</strong> The following modification to your code addresses your requirement.\n\n<p>It uses the overload of NewFamilyInstance taking a reference, point, vector and symbol to insert a new instance of a family onto a face referenced by the input Reference instance, using a location and reference direction.\n\n<p>This creates a family instance which moves when the ReferencePlane is moved.\n\n<p>For simplicity, I have hard coded the element id of the ReferencePlane of my test project.\n\n<p>Before running this code, please select the lighting instance on the base work plane.\nThis code then creates a lighting instance on the reference plane (along with the existing lighting fixture on the reference).\n\n<p>Now you can move the reference plane to the other side of the wall and confirm that the new lighting fixture instance moves along with it too.\n\n<pre class=\"code\">\n  <span class=\"teal\">Selection</span> sel = uidoc.Selection;\n \n  <span class=\"teal\">ElementSet</span> elemSet = sel.Elements;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  trans.Start( <span class=\"maroon\">\"Lights Camera Action!\"</span> );\n \n  <span class=\"teal\">IEnumerator</span> iter = elemSet.ForwardIterator();\n \n  <span class=\"teal\">Element</span> element;\n \n  <span class=\"teal\">ReferencePlane</span> mReferencePlane = <span class=\"blue\">null</span>;\n  <span class=\"teal\">FamilyInstance</span> mFamilyInstance = <span class=\"blue\">null</span>;\n  <span class=\"teal\">FamilySymbol</span> mFamilySymbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">while</span>( iter.MoveNext() )\n  {\n    element = iter.Current <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n \n    <span class=\"teal\">FamilyInstance</span> fi = element <span class=\"blue\">as</span> <span class=\"teal\">FamilyInstance</span>;\n \n    mFamilyInstance = fi;\n    mFamilySymbol = fi.Symbol;\n  }\n \n  mReferencePlane = doc.get_Element(\n    <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( 615738 ) ) <span class=\"blue\">as</span> <span class=\"teal\">ReferencePlane</span>;\n \n  <span class=\"teal\">XYZ</span> pt = <span class=\"teal\">XYZ</span>.Zero;\n  <span class=\"teal\">XYZ</span> refDir = <span class=\"teal\">XYZ</span>.BasisZ;\n \n  uidoc.Document.Create.NewFamilyInstance(\n    mReferencePlane.Reference, pt, refDir,\n    mFamilySymbol );\n \n  trans.Commit();\n</pre>\n<!--\n<p><strong>Response:</strong> This is still an issue for me as I need to be able to host from a Reference Plane and not a Work Plane.\n\n<p><strong>Answer:</strong> I created a model containing a Reference plane with a lighting fixture on it already.\nUsing the code above, you can use the other lighting fixture instance in the model, which currently is on the work plane, and host it on the Reference plane (and not the Work plane grid).\nThe reference plane element id is hard coded.\nIn 3D view you would see this:</p>\n\n<center>\n<img src=\"img/lighting_fixture_on_ref_plane_1.png\" alt=\"Lighting fixture on reference plane\" width=\"400\"/>\n</center>\n\n<p>The lighting fixture closer to the wall is hosted on the Reference Plane:</p>\n\n<center>\n<img src=\"img/lighting_fixture_on_ref_plane_2.png\" alt=\"Lighting fixture on reference plane\" width=\"400\"/>\n</center>\n\n<p>You can pre-select the lighting fixture farthest from the wall (currently on work plane), and the code will host it on the Reference Plane (which already has one lighting fixture just for example).\nThe code will host the light to the Reference Plane and then you can move the Reference Plane to the other side of the wall.\nYou will find that both the lights on the Reference Plane move with the Reference Plane, just as desired.\n-->\n<p><strong>Response:</strong> Perfect, got it working now.\n\n<p>The issue was that I was trying to place the light on a horizontal reference plane and it seems that the <refdir> argument was set incorrectly.\nTo begin with, strangely enough, it seemed that I needed to use a null vector for the reference direction for a horizontal reference plane:\n\n<pre class=\"code\">\n  XYZ refDir = new XYZ(0,0,0);\n</pre>\n<p>Before that, I was using:\n\n<pre class=\"code\">\n  XYZ refDir = new XYZ(0,0,1);\n</pre>\n<p>That caused my error.\n\n<p>Here is a current snapshot of my\n\n<a href=\"zip/LightingFixtureInsert.cs\">\nC# code</a> and some\n\n<a href=\"zip/LightingFixturePositions.txt\">\nsample input data</a>.\n\nThe code will read a TXT file and place lights on a named reference plane.\n\n<p>I explored the effect of the reference direction used in more detail.\nHere are my findings:\n\n<p>The reference direction required obviously depends on the orientation of the reference plane.\nSo I guess the sensible thing to do is to use a direction relative to the plane's normal.\n\n<p>However, my solution requires taking ceiling layouts from AutoCAD and reading them into Revit via a txt file exported from AutoCAD.\nWithin Revit we use horizontal reference planes drawn from right to left (as even with manual insertion that effects the orientation of the light); therefore, this is the solution I require and am happy that I have.\n\n<p>From what I can work out, the reference direction needs to point in the direction the reference plane is drawn; therefore 0,0,1 works for vertical planes, and 1,0,0 for horizontal ones.\nFor a quick hack, the following works for both vertical and horizontal ref planes:\n\n<pre class=\"code\">\n  XYZ refDir = new XYZ(\n    rp.Normal.Z, rp.Normal.X, rp.Normal.Y );\n</pre>\n<p>Here are the results of my tests prior to adding the above hack:\n\n<h4>Vertical Reference Plane along the End Wall</h4>\n<p><strong>1.</strong> Vertical RP +ve Y (drawn bottom to top), RefDir 0,0,1:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane test 1\" src=\"img/lighting_fixture_on_ref_plane_test1.png\" width=\"400\"/>\n</center>\n<p><strong>2.</strong> Vertical RP -ve Y (drawn top to bottom), RefDir 0,0,1:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test2.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> The lights have been placed on the other side of the reference plane.\n\n<p><strong>3.</strong> Vertical RP -ve Y (drawn top to bottom), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test3.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Same side of ref plane, but now they're rotated around 90 degrees.\n\n<h4>Horizontal Reference Plane along the Underside of the Ceiling</h4>\n<p><strong>4.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test4.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Attached to the underside of the reference plane (as required).\n\n<p><strong>5.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test5.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Attached to the topside of the reference plane (not as required).\n\n<p><strong>6.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,1 &amp; Horizontal RP -ve X (drawn right to left), RefDir 0,0,1:\n\n<center>\n<img src=\"img/lighting_fixture_on_ref_plane_test6.png\"/>\n</center>\n<p><strong>Result:</strong> 'Error code: 5'.\n\n<p><strong>7.</strong> Horizontal RP -ve X (drawn right to left), RefDir 1,0,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test7.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Look OK.\n\n<p><strong>8.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,1,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test8.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Lights rotated 90 degrees.\n\n<p>Many thanks to Simon and Saikat for this example and all the research!\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></refdir></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0724_host_reference_plane",
    "header_text": "Vertical Reference Plane along the End Wall",
    "local_header_href": "#vertical-reference-plane-along-the-end-wall",
    "chunk_text": "<h4>Vertical Reference Plane along the End Wall</h4><p><strong>1.</strong> Vertical RP +ve Y (drawn bottom to top), RefDir 0,0,1:</p><center>\n<img alt=\"Lighting fixture on reference plane test 1\" src=\"img/lighting_fixture_on_ref_plane_test1.png\" width=\"400\"/>\n</center><p><strong>2.</strong> Vertical RP -ve Y (drawn top to bottom), RefDir 0,0,1:</p><center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test2.png\" width=\"400\"/>\n</center><p><strong>Result:</strong> The lights have been placed on the other side of the reference plane.\n\n<p><strong>3.</strong> Vertical RP -ve Y (drawn top to bottom), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test3.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Same side of ref plane, but now they're rotated around 90 degrees.\n\n<h4>Horizontal Reference Plane along the Underside of the Ceiling</h4>\n<p><strong>4.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test4.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Attached to the underside of the reference plane (as required).\n\n<p><strong>5.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test5.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Attached to the topside of the reference plane (not as required).\n\n<p><strong>6.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,1 &amp; Horizontal RP -ve X (drawn right to left), RefDir 0,0,1:\n\n<center>\n<img src=\"img/lighting_fixture_on_ref_plane_test6.png\"/>\n</center>\n<p><strong>Result:</strong> 'Error code: 5'.\n\n<p><strong>7.</strong> Horizontal RP -ve X (drawn right to left), RefDir 1,0,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test7.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Look OK.\n\n<p><strong>8.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,1,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test8.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Lights rotated 90 degrees.\n\n<p>Many thanks to Simon and Saikat for this example and all the research!\n</p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0724_host_reference_plane",
    "header_text": "Horizontal Reference Plane along the Underside of the Ceiling",
    "local_header_href": "#horizontal-reference-plane-along-the-underside-of-the-ceiling",
    "chunk_text": "<h4>Horizontal Reference Plane along the Underside of the Ceiling</h4><p><strong>4.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,0,0:</p><center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test4.png\" width=\"400\"/>\n</center><p><strong>Result:</strong> Attached to the underside of the reference plane (as required).\n\n<p><strong>5.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,0:</p>\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test5.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Attached to the topside of the reference plane (not as required).\n\n<p><strong>6.</strong> Horizontal RP +ve X (drawn left to right), RefDir 0,0,1 &amp; Horizontal RP -ve X (drawn right to left), RefDir 0,0,1:\n\n<center>\n<img src=\"img/lighting_fixture_on_ref_plane_test6.png\"/>\n</center>\n<p><strong>Result:</strong> 'Error code: 5'.\n\n<p><strong>7.</strong> Horizontal RP -ve X (drawn right to left), RefDir 1,0,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test7.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Look OK.\n\n<p><strong>8.</strong> Horizontal RP -ve X (drawn right to left), RefDir 0,1,0:\n\n<center>\n<img alt=\"Lighting fixture on reference plane\" src=\"img/lighting_fixture_on_ref_plane_test8.png\" width=\"400\"/>\n</center>\n<p><strong>Result:</strong> Lights rotated 90 degrees.\n\n<p>Many thanks to Simon and Saikat for this example and all the research!\n</p></p></p></p></p></p></p></p></p>"
  }
]