[
  {
    "original_filename": "0764_pipe_cap",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0764_pipe_cap",
    "header_text": "Create a Pipe Cap",
    "local_header_href": "#create-a-pipe-cap",
    "chunk_text": "<h3>Create a Pipe Cap</h3><p>Happily mixing the different Revit versions, let me follow up my work on the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/the-revit-2013-mep-api-and-external-services.html\">\nRevit MEP 2013 API</a> and the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/the-adn-mep-sample-adnrme-for-revit-mep-2013.html\">\nupdated AdnRme sample</a> by \n\nanother MEP related topic.\n\n<p>Before getting to that, though, here is a brief heads-up for a new technology preview on Autodesk Labs:\n\n\n<a name=\"1\"></a>\n<h4>BIM Coordinator</h4>\n<p>The effective organization of project data in shared or related coordinates is essential to effective collaboration across disciplines and good quality project information. \n\n<a href=\"http://labs.autodesk.com/utilities/bim_coordinator\">\nBIM Coordinator</a> for \n\nAutoCAD Civil 3D and Revit is a technology preview that assists project team members with building and site grids.</p>\n<iframe allowfullscreen=\"\" frameborder=\"0\" height=\"274\" src=\"http://www.youtube.com/embed/aSxbv7QPero\" width=\"480\"></iframe>\n<p>Here is a brief overview taken from the labs:\n\n<p><b>Building grids</b> are generally selected based on the layout and shape of the building, usually using the lower left corner of the selected orientation as a reference point. Building grids are established by the lead designer of a project for use by all members of the building design team. This grid ensures that different disciplines' building designs use the same reference for purposes of building analyses, drawing production, and other tasks requiring coordinated building data.\n\n<p><b>Site grids</b> are generally based on Northing and Easting coordinates. They are usually established for a region; although arbitrary grids can be established for a single project or site. For example, in the UK most sites are related to the Ordinance Survey (OS) grid. Site elevations (levels) are also based on an OS benchmark or other site/project benchmark.\n\n<p><a href=\"http://labs.autodesk.com/utilities/bim_coordinator\">\nBIM Coordinator</a> automates the more error-prone manual steps in the coordination of site and building grids between the AutoCAD and Revit environments, currently for the 2012 versions. The tool specifies one common XYZ point and its orientation in the XY plane between the two coordinate systems. This reference point defines the relationship between the building and site grid.\n\n<p>Miroslav Schonauer will be explaining some background and sharing source code from this utility at the upcoming \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/02/aec-devcamp-coming-up-again.html\">\nAEC DevCamp</a> in \n\nWaltham June 6-7.\n \n\n<a name=\"2\"></a>\n<h4>Create a Pipe Cap</h4>\n<p>Back to the Revit MEP API, I presented an example to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreate a pipe cap</a> in \n\nRevit 2011 over a year ago.\n\n<p>Now Mick Kulik of\n\n<a href=\"http://www.hydracad.com\">\nHydratec, Inc.</a> discovered \n\nthat the existing sample code did not work in his case, and worked together with Saikat Bhattacharya at the AutoCAD DevLab in San Rafael to fix this issue for Revit 2012.\n\n<p>Here is the original problem and its solution:\n\n<p><strong>Question:</strong> Following the post about \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreating a pipe cap</a>, \n\nI was not able to get a cap to connect to a pipe in Revit MEP 2012.\nThe Error is \"Line is too short\". \nIs there a new way to connect caps to pipes in Revit MEP 2012?\n\n<p><strong>Answer:</strong> Saikat came down to give us a hand last week at the AutoCAD DevLab in San Rafael.\nHe had some sample code to attach caps to sloping pipes.\nI was able to massage his code to fit our needs, and have attached his \n\n<a href=\"zip/CapAtStartOfPipe.zip\">\nsample project CapAtStartOfPipe.zip</a> containing \n\nthe entire source code and Visual Studio solution implementing this command.\n\n<p>Saikat's code worked on all the cases we tested except when trying to connect the cap to a non-sloped vertical pipe, so I built in a case to handle it which worked for my test cases:\n\n<pre class=\"code\">\n  <span class=\"green\">// rotate the cap if necessary</span>\n \n  <span class=\"green\">// rotate about Z first</span>\n\n  <span class=\"teal\">XYZ</span> pipeHorizontalDirection \n    = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( dir.X, dir.Y, 0.0 ).Normalize();\n \n  <span class=\"teal\">ConnectorSet</span> c2 \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> capConnector = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> c2 )\n  { \n    capConnector = c; \n  }\n \n  <span class=\"teal\">XYZ</span> connectorDirection \n    = -capConnector.CoordinateSystem.BasisZ;\n \n  <span class=\"blue\">double</span> zRotationAngle \n    = pipeHorizontalDirection.AngleTo( \n      connectorDirection );\n \n  <span class=\"teal\">Transform</span> trf = <span class=\"teal\">Transform</span>.get_Rotation( \n    start, <span class=\"teal\">XYZ</span>.BasisZ, zRotationAngle );\n \n  <span class=\"teal\">XYZ</span> testRotation = trf.OfVector( \n    connectorDirection ).Normalize();\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n    pipeHorizontalDirection ) - 1 ) &gt; 0.00001 )\n  {\n    zRotationAngle = -zRotationAngle;\n  }\n \n  <span class=\"teal\">Line</span> axis = doc.Application.Create.NewLineBound( \n    start, start + <span class=\"teal\">XYZ</span>.BasisZ );\n \n  <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n    doc, fi.Id, axis, zRotationAngle );\n \n  <span class=\"green\">// Need to rotate vertically?</span>\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( dir.DotProduct( <span class=\"teal\">XYZ</span>.BasisZ ) ) \n    &gt; 0.000001 )\n  {\n    <span class=\"green\">// if pipe is straight up and down, </span>\n    <span class=\"green\">// kludge it my way else</span>\n \n    <span class=\"blue\">if</span>( dir.X == 0 &amp;&amp; dir.Y == 0 &amp;&amp; dir.Z != 0 )\n    {\n      <span class=\"teal\">XYZ</span> yaxis = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0.0, 1.0, 0.0 );\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( yaxis );\n \n      <span class=\"blue\">if</span>( dir.Z == 1 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLine( \n        start, yaxis, <span class=\"blue\">false</span> );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n    }\n    <span class=\"blue\">else</span>\n    {\n<span class=\"blue\">      #region</span> sloped pipes\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( \n        pipeHorizontalDirection );\n \n      <span class=\"teal\">XYZ</span> normal = pipeHorizontalDirection\n        .CrossProduct( <span class=\"teal\">XYZ</span>.BasisZ );\n \n      trf = <span class=\"teal\">Transform</span>.get_Rotation( \n        start, normal, rotationAngle );\n \n      testRotation = trf.OfVector( dir ).Normalize();\n \n      <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n        pipeHorizontalDirection ) - 1 ) &lt; 0.00001 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLineBound( \n        start, start + normal );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n \n<span class=\"blue\">      #endregion</span>\n    }\n  }\n \n  doc.Regenerate();\n \n  <span class=\"green\">// pick connector on cap:</span>\n \n  <span class=\"teal\">ConnectorSet</span> connectors \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Debug</span>.Assert( 1 == connectors.Size, \n    <span class=\"maroon\">\"expected only one connector on pipe cap element\"</span> );\n \n  <span class=\"teal\">Connector</span> cap_end = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  { \n    cap_end = c; \n  }\n \n  <span class=\"green\">// pick closest connector on pipe:</span>\n \n  connectors = pipe.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> pipe_end = <span class=\"blue\">null</span>;\n  <span class=\"blue\">double</span> dist = <span class=\"blue\">double</span>.MaxValue;\n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  {\n    <span class=\"teal\">XYZ</span> p = c.Origin;\n    <span class=\"blue\">double</span> d = p.DistanceTo( start );\n    <span class=\"blue\">if</span>( d &lt; dist )\n    {\n      dist = d;\n      pipe_end = c;\n    }\n  }\n  pipe_end.ConnectTo( cap_end );\n \n  doc.Regenerate();\n \n  <span class=\"green\">// After ConnectTo, the cap size is double, so </span>\n  <span class=\"green\">// need to change the nominal radius to half.</span>\n \n  <span class=\"blue\">if</span>( fi != <span class=\"blue\">null</span> )\n  {\n    <span class=\"teal\">ConnectorSet</span> pipeConnectors \n      = pipe.ConnectorManager.Connectors;\n \n    <span class=\"teal\">Connector</span> pipeEnd = <span class=\"blue\">null</span>;\n \n    <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> pipeConnectors )\n    {\n      pipeEnd = c;\n    }\n    <span class=\"blue\">double</span> radius = pipeEnd.Radius;\n \n    <span class=\"teal\">Parameter</span> para = fi.get_Parameter( \n      <span class=\"maroon\">\"Nominal Radius\"</span> );\n \n    <span class=\"blue\">if</span>( para != <span class=\"blue\">null</span> &amp;&amp; !para.IsReadOnly )\n    {\n      para.Set( radius );\n    }\n  }\n</pre>\n<p>Here is a screen capture of the result of testing caps on a vertical pipe:</p>\n<center>\n<img alt=\"Cap test on vertical pipe\" src=\"img/CapTest1.png\"/>\n</center>\n<p>Many thanks to Saikat and Mick for providing this new sample!\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0764_pipe_cap",
    "header_text": "BIM Coordinator",
    "local_header_href": "#bim-coordinator",
    "chunk_text": "<h4>BIM Coordinator</h4><p>The effective organization of project data in shared or related coordinates is essential to effective collaboration across disciplines and good quality project information. \n\n<a href=\"http://labs.autodesk.com/utilities/bim_coordinator\">\nBIM Coordinator</a> for \n\nAutoCAD Civil 3D and Revit is a technology preview that assists project team members with building and site grids.</p><iframe allowfullscreen=\"\" frameborder=\"0\" height=\"274\" src=\"http://www.youtube.com/embed/aSxbv7QPero\" width=\"480\"></iframe><p>Here is a brief overview taken from the labs:\n\n<p><b>Building grids</b> are generally selected based on the layout and shape of the building, usually using the lower left corner of the selected orientation as a reference point. Building grids are established by the lead designer of a project for use by all members of the building design team. This grid ensures that different disciplines' building designs use the same reference for purposes of building analyses, drawing production, and other tasks requiring coordinated building data.\n\n<p><b>Site grids</b> are generally based on Northing and Easting coordinates. They are usually established for a region; although arbitrary grids can be established for a single project or site. For example, in the UK most sites are related to the Ordinance Survey (OS) grid. Site elevations (levels) are also based on an OS benchmark or other site/project benchmark.\n\n<p><a href=\"http://labs.autodesk.com/utilities/bim_coordinator\">\nBIM Coordinator</a> automates the more error-prone manual steps in the coordination of site and building grids between the AutoCAD and Revit environments, currently for the 2012 versions. The tool specifies one common XYZ point and its orientation in the XY plane between the two coordinate systems. This reference point defines the relationship between the building and site grid.\n\n<p>Miroslav Schonauer will be explaining some background and sharing source code from this utility at the upcoming \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/02/aec-devcamp-coming-up-again.html\">\nAEC DevCamp</a> in \n\nWaltham June 6-7.\n \n\n<a name=\"2\"></a>\n<h4>Create a Pipe Cap</h4>\n<p>Back to the Revit MEP API, I presented an example to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreate a pipe cap</a> in \n\nRevit 2011 over a year ago.\n\n<p>Now Mick Kulik of\n\n<a href=\"http://www.hydracad.com\">\nHydratec, Inc.</a> discovered \n\nthat the existing sample code did not work in his case, and worked together with Saikat Bhattacharya at the AutoCAD DevLab in San Rafael to fix this issue for Revit 2012.\n\n<p>Here is the original problem and its solution:\n\n<p><strong>Question:</strong> Following the post about \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreating a pipe cap</a>, \n\nI was not able to get a cap to connect to a pipe in Revit MEP 2012.\nThe Error is \"Line is too short\". \nIs there a new way to connect caps to pipes in Revit MEP 2012?\n\n<p><strong>Answer:</strong> Saikat came down to give us a hand last week at the AutoCAD DevLab in San Rafael.\nHe had some sample code to attach caps to sloping pipes.\nI was able to massage his code to fit our needs, and have attached his \n\n<a href=\"zip/CapAtStartOfPipe.zip\">\nsample project CapAtStartOfPipe.zip</a> containing \n\nthe entire source code and Visual Studio solution implementing this command.\n\n<p>Saikat's code worked on all the cases we tested except when trying to connect the cap to a non-sloped vertical pipe, so I built in a case to handle it which worked for my test cases:\n\n<pre class=\"code\">\n  <span class=\"green\">// rotate the cap if necessary</span>\n \n  <span class=\"green\">// rotate about Z first</span>\n\n  <span class=\"teal\">XYZ</span> pipeHorizontalDirection \n    = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( dir.X, dir.Y, 0.0 ).Normalize();\n \n  <span class=\"teal\">ConnectorSet</span> c2 \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> capConnector = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> c2 )\n  { \n    capConnector = c; \n  }\n \n  <span class=\"teal\">XYZ</span> connectorDirection \n    = -capConnector.CoordinateSystem.BasisZ;\n \n  <span class=\"blue\">double</span> zRotationAngle \n    = pipeHorizontalDirection.AngleTo( \n      connectorDirection );\n \n  <span class=\"teal\">Transform</span> trf = <span class=\"teal\">Transform</span>.get_Rotation( \n    start, <span class=\"teal\">XYZ</span>.BasisZ, zRotationAngle );\n \n  <span class=\"teal\">XYZ</span> testRotation = trf.OfVector( \n    connectorDirection ).Normalize();\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n    pipeHorizontalDirection ) - 1 ) &gt; 0.00001 )\n  {\n    zRotationAngle = -zRotationAngle;\n  }\n \n  <span class=\"teal\">Line</span> axis = doc.Application.Create.NewLineBound( \n    start, start + <span class=\"teal\">XYZ</span>.BasisZ );\n \n  <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n    doc, fi.Id, axis, zRotationAngle );\n \n  <span class=\"green\">// Need to rotate vertically?</span>\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( dir.DotProduct( <span class=\"teal\">XYZ</span>.BasisZ ) ) \n    &gt; 0.000001 )\n  {\n    <span class=\"green\">// if pipe is straight up and down, </span>\n    <span class=\"green\">// kludge it my way else</span>\n \n    <span class=\"blue\">if</span>( dir.X == 0 &amp;&amp; dir.Y == 0 &amp;&amp; dir.Z != 0 )\n    {\n      <span class=\"teal\">XYZ</span> yaxis = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0.0, 1.0, 0.0 );\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( yaxis );\n \n      <span class=\"blue\">if</span>( dir.Z == 1 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLine( \n        start, yaxis, <span class=\"blue\">false</span> );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n    }\n    <span class=\"blue\">else</span>\n    {\n<span class=\"blue\">      #region</span> sloped pipes\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( \n        pipeHorizontalDirection );\n \n      <span class=\"teal\">XYZ</span> normal = pipeHorizontalDirection\n        .CrossProduct( <span class=\"teal\">XYZ</span>.BasisZ );\n \n      trf = <span class=\"teal\">Transform</span>.get_Rotation( \n        start, normal, rotationAngle );\n \n      testRotation = trf.OfVector( dir ).Normalize();\n \n      <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n        pipeHorizontalDirection ) - 1 ) &lt; 0.00001 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLineBound( \n        start, start + normal );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n \n<span class=\"blue\">      #endregion</span>\n    }\n  }\n \n  doc.Regenerate();\n \n  <span class=\"green\">// pick connector on cap:</span>\n \n  <span class=\"teal\">ConnectorSet</span> connectors \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Debug</span>.Assert( 1 == connectors.Size, \n    <span class=\"maroon\">\"expected only one connector on pipe cap element\"</span> );\n \n  <span class=\"teal\">Connector</span> cap_end = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  { \n    cap_end = c; \n  }\n \n  <span class=\"green\">// pick closest connector on pipe:</span>\n \n  connectors = pipe.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> pipe_end = <span class=\"blue\">null</span>;\n  <span class=\"blue\">double</span> dist = <span class=\"blue\">double</span>.MaxValue;\n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  {\n    <span class=\"teal\">XYZ</span> p = c.Origin;\n    <span class=\"blue\">double</span> d = p.DistanceTo( start );\n    <span class=\"blue\">if</span>( d &lt; dist )\n    {\n      dist = d;\n      pipe_end = c;\n    }\n  }\n  pipe_end.ConnectTo( cap_end );\n \n  doc.Regenerate();\n \n  <span class=\"green\">// After ConnectTo, the cap size is double, so </span>\n  <span class=\"green\">// need to change the nominal radius to half.</span>\n \n  <span class=\"blue\">if</span>( fi != <span class=\"blue\">null</span> )\n  {\n    <span class=\"teal\">ConnectorSet</span> pipeConnectors \n      = pipe.ConnectorManager.Connectors;\n \n    <span class=\"teal\">Connector</span> pipeEnd = <span class=\"blue\">null</span>;\n \n    <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> pipeConnectors )\n    {\n      pipeEnd = c;\n    }\n    <span class=\"blue\">double</span> radius = pipeEnd.Radius;\n \n    <span class=\"teal\">Parameter</span> para = fi.get_Parameter( \n      <span class=\"maroon\">\"Nominal Radius\"</span> );\n \n    <span class=\"blue\">if</span>( para != <span class=\"blue\">null</span> &amp;&amp; !para.IsReadOnly )\n    {\n      para.Set( radius );\n    }\n  }\n</pre>\n<p>Here is a screen capture of the result of testing caps on a vertical pipe:</p>\n<center>\n<img alt=\"Cap test on vertical pipe\" src=\"img/CapTest1.png\"/>\n</center>\n<p>Many thanks to Saikat and Mick for providing this new sample!\n</p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0764_pipe_cap",
    "header_text": "Create a Pipe Cap",
    "local_header_href": "#create-a-pipe-cap",
    "chunk_text": "<h4>Create a Pipe Cap</h4><p>Back to the Revit MEP API, I presented an example to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreate a pipe cap</a> in \n\nRevit 2011 over a year ago.\n\n<p>Now Mick Kulik of\n\n<a href=\"http://www.hydracad.com\">\nHydratec, Inc.</a> discovered \n\nthat the existing sample code did not work in his case, and worked together with Saikat Bhattacharya at the AutoCAD DevLab in San Rafael to fix this issue for Revit 2012.\n\n<p>Here is the original problem and its solution:\n\n<p><strong>Question:</strong> Following the post about \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/create-a-pipe-cap.html\">\ncreating a pipe cap</a>, \n\nI was not able to get a cap to connect to a pipe in Revit MEP 2012.\nThe Error is \"Line is too short\". \nIs there a new way to connect caps to pipes in Revit MEP 2012?\n\n<p><strong>Answer:</strong> Saikat came down to give us a hand last week at the AutoCAD DevLab in San Rafael.\nHe had some sample code to attach caps to sloping pipes.\nI was able to massage his code to fit our needs, and have attached his \n\n<a href=\"zip/CapAtStartOfPipe.zip\">\nsample project CapAtStartOfPipe.zip</a> containing \n\nthe entire source code and Visual Studio solution implementing this command.\n\n<p>Saikat's code worked on all the cases we tested except when trying to connect the cap to a non-sloped vertical pipe, so I built in a case to handle it which worked for my test cases:\n\n<pre class=\"code\">\n  <span class=\"green\">// rotate the cap if necessary</span>\n \n  <span class=\"green\">// rotate about Z first</span>\n\n  <span class=\"teal\">XYZ</span> pipeHorizontalDirection \n    = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( dir.X, dir.Y, 0.0 ).Normalize();\n \n  <span class=\"teal\">ConnectorSet</span> c2 \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> capConnector = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> c2 )\n  { \n    capConnector = c; \n  }\n \n  <span class=\"teal\">XYZ</span> connectorDirection \n    = -capConnector.CoordinateSystem.BasisZ;\n \n  <span class=\"blue\">double</span> zRotationAngle \n    = pipeHorizontalDirection.AngleTo( \n      connectorDirection );\n \n  <span class=\"teal\">Transform</span> trf = <span class=\"teal\">Transform</span>.get_Rotation( \n    start, <span class=\"teal\">XYZ</span>.BasisZ, zRotationAngle );\n \n  <span class=\"teal\">XYZ</span> testRotation = trf.OfVector( \n    connectorDirection ).Normalize();\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n    pipeHorizontalDirection ) - 1 ) &gt; 0.00001 )\n  {\n    zRotationAngle = -zRotationAngle;\n  }\n \n  <span class=\"teal\">Line</span> axis = doc.Application.Create.NewLineBound( \n    start, start + <span class=\"teal\">XYZ</span>.BasisZ );\n \n  <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n    doc, fi.Id, axis, zRotationAngle );\n \n  <span class=\"green\">// Need to rotate vertically?</span>\n \n  <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( dir.DotProduct( <span class=\"teal\">XYZ</span>.BasisZ ) ) \n    &gt; 0.000001 )\n  {\n    <span class=\"green\">// if pipe is straight up and down, </span>\n    <span class=\"green\">// kludge it my way else</span>\n \n    <span class=\"blue\">if</span>( dir.X == 0 &amp;&amp; dir.Y == 0 &amp;&amp; dir.Z != 0 )\n    {\n      <span class=\"teal\">XYZ</span> yaxis = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0.0, 1.0, 0.0 );\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( yaxis );\n \n      <span class=\"blue\">if</span>( dir.Z == 1 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLine( \n        start, yaxis, <span class=\"blue\">false</span> );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n    }\n    <span class=\"blue\">else</span>\n    {\n<span class=\"blue\">      #region</span> sloped pipes\n \n      <span class=\"blue\">double</span> rotationAngle = dir.AngleTo( \n        pipeHorizontalDirection );\n \n      <span class=\"teal\">XYZ</span> normal = pipeHorizontalDirection\n        .CrossProduct( <span class=\"teal\">XYZ</span>.BasisZ );\n \n      trf = <span class=\"teal\">Transform</span>.get_Rotation( \n        start, normal, rotationAngle );\n \n      testRotation = trf.OfVector( dir ).Normalize();\n \n      <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Abs( testRotation.DotProduct( \n        pipeHorizontalDirection ) - 1 ) &lt; 0.00001 )\n      {\n        rotationAngle = -rotationAngle;\n      }\n \n      axis = doc.Application.Create.NewLineBound( \n        start, start + normal );\n \n      <span class=\"teal\">ElementTransformUtils</span>.RotateElement( \n        doc, fi.Id, axis, rotationAngle );\n \n<span class=\"blue\">      #endregion</span>\n    }\n  }\n \n  doc.Regenerate();\n \n  <span class=\"green\">// pick connector on cap:</span>\n \n  <span class=\"teal\">ConnectorSet</span> connectors \n    = fi.MEPModel.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Debug</span>.Assert( 1 == connectors.Size, \n    <span class=\"maroon\">\"expected only one connector on pipe cap element\"</span> );\n \n  <span class=\"teal\">Connector</span> cap_end = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  { \n    cap_end = c; \n  }\n \n  <span class=\"green\">// pick closest connector on pipe:</span>\n \n  connectors = pipe.ConnectorManager.Connectors;\n \n  <span class=\"teal\">Connector</span> pipe_end = <span class=\"blue\">null</span>;\n  <span class=\"blue\">double</span> dist = <span class=\"blue\">double</span>.MaxValue;\n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> connectors )\n  {\n    <span class=\"teal\">XYZ</span> p = c.Origin;\n    <span class=\"blue\">double</span> d = p.DistanceTo( start );\n    <span class=\"blue\">if</span>( d &lt; dist )\n    {\n      dist = d;\n      pipe_end = c;\n    }\n  }\n  pipe_end.ConnectTo( cap_end );\n \n  doc.Regenerate();\n \n  <span class=\"green\">// After ConnectTo, the cap size is double, so </span>\n  <span class=\"green\">// need to change the nominal radius to half.</span>\n \n  <span class=\"blue\">if</span>( fi != <span class=\"blue\">null</span> )\n  {\n    <span class=\"teal\">ConnectorSet</span> pipeConnectors \n      = pipe.ConnectorManager.Connectors;\n \n    <span class=\"teal\">Connector</span> pipeEnd = <span class=\"blue\">null</span>;\n \n    <span class=\"blue\">foreach</span>( <span class=\"teal\">Connector</span> c <span class=\"blue\">in</span> pipeConnectors )\n    {\n      pipeEnd = c;\n    }\n    <span class=\"blue\">double</span> radius = pipeEnd.Radius;\n \n    <span class=\"teal\">Parameter</span> para = fi.get_Parameter( \n      <span class=\"maroon\">\"Nominal Radius\"</span> );\n \n    <span class=\"blue\">if</span>( para != <span class=\"blue\">null</span> &amp;&amp; !para.IsReadOnly )\n    {\n      para.Set( radius );\n    }\n  }\n</pre>\n<p>Here is a screen capture of the result of testing caps on a vertical pipe:</p>\n<center>\n<img alt=\"Cap test on vertical pipe\" src=\"img/CapTest1.png\"/>\n</center>\n<p>Many thanks to Saikat and Mick for providing this new sample!\n</p></p></p></p></p></p></p>"
  }
]