[
  {
    "original_filename": "0804_ur1_line_origin_end",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0804_ur1_line_origin_end",
    "header_text": "UR1 and Line Origin versus Start and End Point",
    "local_header_href": "#ur1-and-line-origin-versus-start-and-end-point",
    "chunk_text": "<h3>UR1 and Line Origin versus Start and End Point</h3><p>My official vacation time has begun.\nI still have rather a backlog of important, pending, almost completed projects, unanswered blog comments, and unavoidable meetings, so I will be online now and then in spite of that.\n\n<p>I also want to keep us all updated on important little titbits such as the UR1:\n\n\n<a name=\"1\"></a>\n<h4>Revit 2013 Update Release 1</h4>\n<p>The Revit 2013 Update Release 1 is now available for download and installation from the web and within the product through Communication Center.  \nHere are links to the appropriate update pages:\n\n<ul>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?siteID=123112&amp;id=20121968&amp;linkID=16831210\">Revit 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20121970&amp;siteID=123112&amp;linkID=9273944\">Revit Architecture 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20122070&amp;siteID=123112&amp;linkID=12828318\">Revit MEP 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20122015&amp;siteID=123112&amp;linkID=9280927\">Revit Structure 2013 UR1</a>\n</li></li></li></li></ul>\n<p>The build identifier is 20120716_1115.\n\n<p>Here is a list of the API enhancements implemented in this update:\n\n<ul>\n<li>Allows Document.PostFailure to be used to post multiple errors during a single transaction that do\nnot reference an ElementId.\n<li>Improves stability using UIApplication.DoDragDrop when a Revit command (such as the Wall\ntool) was active.\n<li>Improves stability by disabling keyboard shortcuts (except view zoom shortcuts) when a\nPreviewControl is active.\n<li>Improves stability in ReferenceIntersector.FindNearest() when no matching target pick is found.\n<li>Corrects validation logic to allow NewFamilyInstance to place face-based families on transformed\nfamily instances.\n<li>Dimension.Above and Dimension.Below now update the dimension after their data is changed\nwithout requiring any user action.\n<li>The properties MechanicalSystem.SystemType, ElectricalConnector.SystemType,\nPipeConnector.SystemType are obsolete in Revit 2013. Instead query the parameter\nRBS_DUCT_CONNECTOR_SYSTEM_CLASSIFICATION_PARAM on ConnectorElement.\n<li>Corrects data reported with ConnectorManager.UnusedConnectors.\n<li>Fixes a file corruption that could occur when extensible storage data was added to an element in\na central file.\n<li>Improves stability when saving a file with extensible storage data that overwrites an existing file\nthat also contains extensible storage.\n<li>RVT Links created with RevitLinkType.Create will remain loaded when the RVT containing the\nlink is reopened.\n<li>Previously, setting 'suppressBendRadius' to true in method Rebar.GetCenterlineCurves() would\ncause both fillet bends and user-drawn, parameterized arcs to be omitted from the collection of\ncurves returned by the method. The method now omits only the fillet bends; the drawn arcs are\nincluded along with the straight edges.\n<li>Updates Rebar.GetCenterlineCurves() method with an additional argument: a MultiplanarOption\n(enum), which should be set to IncludeAllMultiplanarCurves or IncludeOnlyPlanarCurves. This\nargument controls whether all curves of a multi-planar Rebar instance are returned, or only those\nwhich lie in the primary plane.\n<li>Enables method Rebar.ComputeDrivingCurves(). This method returns a collection of curves that\nincludes the lines and arcs that drive the shape, but excludes fillets and hooks. It is equivalent to\ncalling GetCenterlinCurves(adjustForSelfIntersection=false, suppressHooks=true,\nsuppressBendRadius=true, multiplanarOption=IncludeOnlyPlanarCurves)\n<li>Improvements have been made in RebarShape methods that deal with matching RebarShapes to\ncollections of curves: CreateFromCurvesAndShape(), RebarShapeMatchesCurvesAndHooks().\n<li>Corrects behavior ot RebarShape.Create() method to not ignore the out-of-plane bend diameter\nspecified in the RebarShapeMultiplanarDefinition argument object, and always used an internal\ndefault value.\n</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul>\n<p>Meanwhile, here is a neat little interesting and basic geometrical Revit API question that arose last week:\n\n\n<a name=\"2\"></a>\n<h4>Relationship of Line Origin, Start and End Point</h4>\n<p><strong>Question:</strong> When examining the AnalyticalSurface of a floor in my sample model, I noticed that the Origin property of a certain Line instance is not equal to either of its end points returned by the EndPoint property (get_EndPoint method in C#).\n\n<p>Until now, I had assumed that the Origin property of a line is always equal to one of its end points.\n\n<p>Could you please clarify:\n\n<ol type=\"a\">\n<li>What exactly is the definition of a line's Origin property?\n<li>How does the line origin relate to its end points?\n</li></li></ol>\n<p><strong>Answer:</strong> I already presented some basic facts on the Revit API \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curves.html\">\nlines, curves</a> and their\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curve-parameterisation.html\">\nparameterisations</a> from \n\nScott Conover's AU 2009 class on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/analyse-building-geometry.html\">\nanalysing building geometry</a>,\n\nwhich he has continued updating, most recently for the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/devcamp-day-one.html#4\">AEC DevCamp 2012</a>\n\n(<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/obj-model-exporter-take-one.html#2\">finalised material</a>).\n\n<p>To answer your questions directly:\n\n<ol type=\"a\">\n<li>The line origin and direction define the location of the infinite unbounded line. \nThe start and end point of the bounded line can lie anywhere along this line.\n\n<li>The origin always lies somewhere on the infinite unbounded line. \nThere is no guarantee that it will coincide with either the start or end point of the bounded line, though.\nThe origin of a bounded line may even lie outside the bounded part of the infinite line.\n</li></li></ol>\n<p>I hope this helps clarify things.\n\n<p>Anyway, now I'm off to the sunny \n\n<a href=\"http://en.wikipedia.org/wiki/Provence\">\nProvence</a>!\n</p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0804_ur1_line_origin_end",
    "header_text": "Revit 2013 Update Release 1",
    "local_header_href": "#revit-2013-update-release-1",
    "chunk_text": "<h4>Revit 2013 Update Release 1</h4><p>The Revit 2013 Update Release 1 is now available for download and installation from the web and within the product through Communication Center.  \nHere are links to the appropriate update pages:\n\n<ul>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?siteID=123112&amp;id=20121968&amp;linkID=16831210\">Revit 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20121970&amp;siteID=123112&amp;linkID=9273944\">Revit Architecture 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20122070&amp;siteID=123112&amp;linkID=12828318\">Revit MEP 2013 UR1</a>\n<li><a href=\"http://usa.autodesk.com/adsk/servlet/ps/dl/item?id=20122015&amp;siteID=123112&amp;linkID=9280927\">Revit Structure 2013 UR1</a>\n</li></li></li></li></ul>\n<p>The build identifier is 20120716_1115.\n\n<p>Here is a list of the API enhancements implemented in this update:\n\n<ul>\n<li>Allows Document.PostFailure to be used to post multiple errors during a single transaction that do\nnot reference an ElementId.\n<li>Improves stability using UIApplication.DoDragDrop when a Revit command (such as the Wall\ntool) was active.\n<li>Improves stability by disabling keyboard shortcuts (except view zoom shortcuts) when a\nPreviewControl is active.\n<li>Improves stability in ReferenceIntersector.FindNearest() when no matching target pick is found.\n<li>Corrects validation logic to allow NewFamilyInstance to place face-based families on transformed\nfamily instances.\n<li>Dimension.Above and Dimension.Below now update the dimension after their data is changed\nwithout requiring any user action.\n<li>The properties MechanicalSystem.SystemType, ElectricalConnector.SystemType,\nPipeConnector.SystemType are obsolete in Revit 2013. Instead query the parameter\nRBS_DUCT_CONNECTOR_SYSTEM_CLASSIFICATION_PARAM on ConnectorElement.\n<li>Corrects data reported with ConnectorManager.UnusedConnectors.\n<li>Fixes a file corruption that could occur when extensible storage data was added to an element in\na central file.\n<li>Improves stability when saving a file with extensible storage data that overwrites an existing file\nthat also contains extensible storage.\n<li>RVT Links created with RevitLinkType.Create will remain loaded when the RVT containing the\nlink is reopened.\n<li>Previously, setting 'suppressBendRadius' to true in method Rebar.GetCenterlineCurves() would\ncause both fillet bends and user-drawn, parameterized arcs to be omitted from the collection of\ncurves returned by the method. The method now omits only the fillet bends; the drawn arcs are\nincluded along with the straight edges.\n<li>Updates Rebar.GetCenterlineCurves() method with an additional argument: a MultiplanarOption\n(enum), which should be set to IncludeAllMultiplanarCurves or IncludeOnlyPlanarCurves. This\nargument controls whether all curves of a multi-planar Rebar instance are returned, or only those\nwhich lie in the primary plane.\n<li>Enables method Rebar.ComputeDrivingCurves(). This method returns a collection of curves that\nincludes the lines and arcs that drive the shape, but excludes fillets and hooks. It is equivalent to\ncalling GetCenterlinCurves(adjustForSelfIntersection=false, suppressHooks=true,\nsuppressBendRadius=true, multiplanarOption=IncludeOnlyPlanarCurves)\n<li>Improvements have been made in RebarShape methods that deal with matching RebarShapes to\ncollections of curves: CreateFromCurvesAndShape(), RebarShapeMatchesCurvesAndHooks().\n<li>Corrects behavior ot RebarShape.Create() method to not ignore the out-of-plane bend diameter\nspecified in the RebarShapeMultiplanarDefinition argument object, and always used an internal\ndefault value.\n</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul>\n<p>Meanwhile, here is a neat little interesting and basic geometrical Revit API question that arose last week:\n\n\n<a name=\"2\"></a>\n<h4>Relationship of Line Origin, Start and End Point</h4>\n<p><strong>Question:</strong> When examining the AnalyticalSurface of a floor in my sample model, I noticed that the Origin property of a certain Line instance is not equal to either of its end points returned by the EndPoint property (get_EndPoint method in C#).\n\n<p>Until now, I had assumed that the Origin property of a line is always equal to one of its end points.\n\n<p>Could you please clarify:\n\n<ol type=\"a\">\n<li>What exactly is the definition of a line's Origin property?\n<li>How does the line origin relate to its end points?\n</li></li></ol>\n<p><strong>Answer:</strong> I already presented some basic facts on the Revit API \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curves.html\">\nlines, curves</a> and their\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curve-parameterisation.html\">\nparameterisations</a> from \n\nScott Conover's AU 2009 class on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/analyse-building-geometry.html\">\nanalysing building geometry</a>,\n\nwhich he has continued updating, most recently for the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/devcamp-day-one.html#4\">AEC DevCamp 2012</a>\n\n(<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/obj-model-exporter-take-one.html#2\">finalised material</a>).\n\n<p>To answer your questions directly:\n\n<ol type=\"a\">\n<li>The line origin and direction define the location of the infinite unbounded line. \nThe start and end point of the bounded line can lie anywhere along this line.\n\n<li>The origin always lies somewhere on the infinite unbounded line. \nThere is no guarantee that it will coincide with either the start or end point of the bounded line, though.\nThe origin of a bounded line may even lie outside the bounded part of the infinite line.\n</li></li></ol>\n<p>I hope this helps clarify things.\n\n<p>Anyway, now I'm off to the sunny \n\n<a href=\"http://en.wikipedia.org/wiki/Provence\">\nProvence</a>!\n</p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0804_ur1_line_origin_end",
    "header_text": "Relationship of Line Origin, Start and End Point",
    "local_header_href": "#relationship-of-line-origin-start-and-end-point",
    "chunk_text": "<h4>Relationship of Line Origin, Start and End Point</h4><p><strong>Question:</strong> When examining the AnalyticalSurface of a floor in my sample model, I noticed that the Origin property of a certain Line instance is not equal to either of its end points returned by the EndPoint property (get_EndPoint method in C#).\n\n<p>Until now, I had assumed that the Origin property of a line is always equal to one of its end points.\n\n<p>Could you please clarify:\n\n<ol type=\"a\">\n<li>What exactly is the definition of a line's Origin property?\n<li>How does the line origin relate to its end points?\n</li></li></ol>\n<p><strong>Answer:</strong> I already presented some basic facts on the Revit API \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curves.html\">\nlines, curves</a> and their\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/curve-parameterisation.html\">\nparameterisations</a> from \n\nScott Conover's AU 2009 class on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/analyse-building-geometry.html\">\nanalysing building geometry</a>,\n\nwhich he has continued updating, most recently for the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/devcamp-day-one.html#4\">AEC DevCamp 2012</a>\n\n(<a href=\"http://thebuildingcoder.typepad.com/blog/2012/06/obj-model-exporter-take-one.html#2\">finalised material</a>).\n\n<p>To answer your questions directly:\n\n<ol type=\"a\">\n<li>The line origin and direction define the location of the infinite unbounded line. \nThe start and end point of the bounded line can lie anywhere along this line.\n\n<li>The origin always lies somewhere on the infinite unbounded line. \nThere is no guarantee that it will coincide with either the start or end point of the bounded line, though.\nThe origin of a bounded line may even lie outside the bounded part of the infinite line.\n</li></li></ol>\n<p>I hope this helps clarify things.\n\n<p>Anyway, now I'm off to the sunny \n\n<a href=\"http://en.wikipedia.org/wiki/Provence\">\nProvence</a>!\n</p></p></p></p></p></p></p>"
  }
]