[
  {
    "original_filename": "0824_categories",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0824_categories",
    "header_text": "Categories Collection Item Accessor Fails",
    "local_header_href": "#categories-collection-item-accessor-fails",
    "chunk_text": "<h3>Categories Collection Item Accessor Fails</h3><p>The document settings categories collection Item property returns null for certain built-in categories, and even throws an exception for certain others.\nYou should be aware of this.\n\n<p>I mentioned a related issue back in the Revit 2011 timeframe, describing \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/05/categories.html\">\nThe Building Coder CmdCategories sample command</a>.\n\n<p>Still, this is a bit unexpected and has caused issues for several developers.\n\n<p>Here are some examples:\n\n<p><strong>Question 1:</strong> For some reason I cannot obtain the category for stacked walls, e.g. using\n\n<pre class=\"code\">\n  Dim cat As Category = Doc.Settings.Categories\n    .Item(BuiltInCategory.OST_StackedWalls)\n</pre>\n<p>This call returns nothing even though I have stacked walls in my document. \nI can also find the BuiltinCategory.OST_StackedWalls using RevitLookup. \n\n<p>Should I be looking somewhere else?\n\n<p><strong>Question 2:</strong> I am adding several parameters through\n\n<pre class=\"code\">\n  doc.ParameterBindings.Insert(\n    information, caseTying, bipgroup );\n</pre>\n<p>Sometimes I get an error, even though the parameters all seem OK.\n\n<p>The stack trace says NullReferenceException in BindingMap.Insert.\n\n<p>What is causing this?\n\n<p>Here is a code snippet demonstrating the problem:\n\n<pre class=\"code\">\n  <span class=\"teal\">DefinitionFile</span> sharedParametersFile\n    = app.OpenSharedParameterFile();\n \n  <span class=\"teal\">DefinitionGroup</span> group = sharedParametersFile\n    .Groups.Create( <span class=\"maroon\">\"Reinforcement\"</span> );\n \n  <span class=\"teal\">Definition</span> def = group.Definitions.Create(\n    <span class=\"maroon\">\"ReinforcementParameter\"</span>, <span class=\"teal\">ParameterType</span>.Text );\n \n  <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt; bics\n    = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt;();\n \n  <span class=\"green\">//bics.Add(BuiltInCategory.OST_AreaRein);</span>\n  <span class=\"green\">//bics.Add(BuiltInCategory.OST_FabricAreas);</span>\n  <span class=\"green\">//bics.Add(BuiltInCategory.OST_FabricReinforcement);</span>\n  <span class=\"green\">//bics.Add(BuiltInCategory.OST_PathRein);</span>\n  <span class=\"green\">//bics.Add(BuiltInCategory.OST_Rebar);</span>\n \n  bics.Add( <span class=\"teal\">BuiltInCategory</span>\n    .OST_IOSRebarSystemSpanSymbolCtrl );\n \n  <span class=\"teal\">CategorySet</span> catset = <span class=\"blue\">new</span> <span class=\"teal\">CategorySet</span>();\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">BuiltInCategory</span> bic <span class=\"blue\">in</span> bics )\n  {\n    catset.Insert(\n      doc.Settings.Categories.get_Item( bic ) );\n  }\n \n  <span class=\"teal\">InstanceBinding</span> binding\n    = app.Create.NewInstanceBinding( catset );\n \n  doc.ParameterBindings.Insert( def, binding,\n    <span class=\"teal\">BuiltInParameterGroup</span>.PG_CONSTRUCTION );\n</pre>\n<p><strong>Answer:</strong> The first issue is due to OST_StackedWalls being marked 'Hidden to User', causing certain internal methods to return false.\nAs a final result, the Categories Item accessor returns null. \n\n<p>'Hidden to User' means that the user interface to Object Styles, Visibility/Graphics, and Export Layers will not include these categories.\n\n<p>It does not mean that the categories are hidden everywhere in the product. \nSome features get a specific category from an element and display its name. \nFor example, the status prompt displays the category of the element that the mouse is hovering over, and the Selection Filter dialog displays the categories of selected elements. \nThis works because other methods return all categories regardless of the 'Hidden to User' flag. \n\n<p>Aside from OST_StackedWalls, here are some other categories that may correspond to real elements that users can see, select, and whose category name may appear:\n\n<ul>\n<li>OST_Reveals\n<li>OST_ArcWallRectOpening\n<li>OST_SWallRectOpening\n<li>OST_SitePropertyLineSegment\n<li>OST_RvtLinks\n<li>OST_LegendComponents\n<li>OST_ConnectorElem\n</li></li></li></li></li></li></li></ul>\n<p>Some features also display lists of categories that don't come from the CategoryTableInterface methods. \nSchedules, project parameters, the Family Category and Parameters dialog are examples. \nTypically those can also include 'Hidden to User' categories. \nFor example, OST_SitePropertyLineSegment is a schedulable category despite being 'Hidden to User'.\n\n<p>In some cases it may be incorrect for the API to prevent people from working with 'Hidden to User' categories. \nOf course any APIs for category-related features should have proper validation so that people can only use appropriate categories. For example, APIs for category visibility, project parameters, and schedules should restrict which categories can be used for those features, just like the UI does. We have to be careful about exposing 'Hidden to User' categories without checking other APIs for proper validation. For example, the project parameters API may allow more categories that it should. \n\n<!--\n<p>In any case, all document categories are accessible using filtered element collectors, including the specific hidden categories mentioned above, which is why you see them in RevitLookup.\n\n<p>Since you have the RevitLookup source, you can debug it and see how they are found.\n\nC:\\a\\j\\adn\\case\\sfdc\\07367840\\snoop.jpg\n\n<p>This obviously applies to everything you see there.\n-->\n<p>I expanded The Building Coder samples CmdCategories external command to determine and display a list of all the built-in categories causing the Categories.Item property to either return null or throw an exception.\nHere is the code that demonstrates that:\n\n<pre class=\"code\">\n  <span class=\"teal\">Array</span> bics = <span class=\"teal\">Enum</span>.GetValues(\n    <span class=\"blue\">typeof</span>( <span class=\"teal\">BuiltInCategory</span> ) );\n \n  <span class=\"blue\">int</span> nBics = bics.Length;\n \n  <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"{0} built-in categories and the \"</span>\n    + <span class=\"maroon\">\"corresponding document ones:\"</span>, nBics );\n \n  <span class=\"teal\">Category</span> cat;\n  <span class=\"blue\">string</span> s;\n \n  <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt; bics_null\n    = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt;();\n \n  <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt; bics_exception\n    = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">BuiltInCategory</span>&gt;();\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">BuiltInCategory</span> bic <span class=\"blue\">in</span> bics )\n  {\n    <span class=\"blue\">try</span>\n    {\n      cat = categories.get_Item( bic );\n \n      <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == cat )\n      {\n        bics_null.Add( bic );\n        s = <span class=\"maroon\">\"&lt;null&gt;\"</span>;\n      }\n      <span class=\"blue\">else</span>\n      {\n        s = <span class=\"blue\">string</span>.Format( <span class=\"maroon\">\"{0} ({1})\"</span>,\n          cat.Name, cat.Id.IntegerValue );\n      }\n    }\n    <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> ex )\n    {\n      bics_exception.Add( bic );\n \n      s = ex.GetType().Name + <span class=\"maroon\">\" \"</span> + ex.Message;\n    }\n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"  {0} --&gt; {1}\"</span>, \n      bic.ToString(), s );\n  }\n \n  <span class=\"blue\">int</span> nBicsNull = bics_null.Count;\n  <span class=\"blue\">int</span> nBicsException = bics_exception.Count;\n \n  <span class=\"teal\">TaskDialog</span> dlg = <span class=\"blue\">new</span> <span class=\"teal\">TaskDialog</span>(\n    <span class=\"maroon\">\"Hidden Built-in Categories\"</span> );\n \n  s = <span class=\"blue\">string</span>.Format(\n    <span class=\"maroon\">\"{0} categories obtained from the Categories collection;\\r\\n\"</span>\n    + <span class=\"maroon\">\"{1} built-in categories;\\r\\n\"</span>\n    + <span class=\"maroon\">\"{2} built-in categories retrieve null result;\\r\\n\"</span>\n    + <span class=\"maroon\">\"{3} built-in categories throw an exception:\\r\\n\"</span>,\n    nCategories, nBics, nBicsNull, nBicsException );\n \n  <span class=\"teal\">Debug</span>.Print( s );\n \n  dlg.MainInstruction = s;\n \n  s = bics_exception\n    .Aggregate&lt;<span class=\"teal\">BuiltInCategory</span>, <span class=\"blue\">string</span>&gt;(\n      <span class=\"blue\">string</span>.Empty,\n      ( a, bic ) =&gt; a + <span class=\"maroon\">\"\\n\"</span> + bic.ToString() );\n \n  <span class=\"teal\">Debug</span>.Print( s );\n \n  dlg.MainContent = s;\n \n  dlg.Show();\n</pre>\n<!-- \n<p>It now also demonstrates how to retrieve all document categories through a filtered element collector.\n\n<p>Trying to use OfClass with the Category class throws an Autodesk.Revit.Exceptions.ArgumentException exception saying \"Input type Autodesk.Revit.DB.Category is not a recognized Revit API type\".\n\n<p>Instead, we have to retrieve generic Element, like this:\n\n<pre class=\"code\">\n</pre>\n-->\n<p>This is the resulting output in an empty architectural project reporting the count of document categories, built-in categories, and built-in categories for which a document category cannot be retrieved, either because the call the Categories.Item returns null or throws an exception:</p>\n<center>\n<img alt=\"Document and built-in category counts\" src=\"img/bic_hidden.png\"/>\n</center>\n<p>To spell it out in full text:\n\n<ul>\n<li>259 categories obtained from the Categories collection;\n<li>897 built-in categories;\n<li>358 built-in categories retrieve null result;\n<li>12 built-in categories throw an exception:\n<ul>\n<li>OST_FurnitureHiddenLines\n<li>OST_SplitterProfile\n<li>OST_HostTemplate\n<li>OST_MassFaceSplitter\n<li>OST_MassCutter\n<li>OST_ZoningEnvelope\n<li>OST_StairsSupports\n<li>OST_InstanceDrivenLineStyle\n<li>OST_CurtainGridsSystem\n<li>OST_StairsStringerCarriage\n<li>OST_IOSNotSilhouette\n<li>OST_InvisibleLines\n</li></li></li></li></li></li></li></li></li></li></li></li></ul>\n</li></li></li></li></ul>\n<p>The complete lists of built-in categories for which no corresponding document category can be retrieved are logged to the Visual Studio debug output window.\nThey obviously depend on the document that you run this command in.\n\n<p>You should probably run it yourself in the documents you are working with to be aware of what is going on.\nIn any case, all code accessing the Categories.Item property with untested built-in categories needs to implement appropriate handling of these conditions.\n\n<p>Here is the updated \n\n<a href=\"zip/bc_13_99_1.zip\">version 2013.0.99.1</a> of \n\nThe Building Coder samples including the expanded version of the CmdCategories external command displaying the list of hidden built-in categories.\n\n<p><strong>Addendum:</strong> Saikat presented another example of an inaccessible category, the \n\n<!-- Accessing Profiles Category while OmniClass Code and Description access -->\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/accessing-profiles-category-while-omniclass-code-and-description-access.html\">\nProfiles category OST_ProfileFamilies</a>.\n\n<a name=\"2\"></a>\n<h4>Brute Force Computing</h4>\n<p>I stumbled across this interesting article on \n\n<a href=\"http://bits.blogs.nytimes.com/2012/09/11/the-brute-force-computing-revolution\">\nbrute force computing</a> explaining\n\none interesting aspect of cloud based computing and access to huge amounts of computing power.\n\n<p>One fact I was totally unaware of, and that had me a bit surprised in the past year or two, is that \"brute force computing is behind Google's successful language translation. \nBy comparing thousands of Web pages in different languages to find patterns, in one year Google was able to discern and refine translation better than linguistic theorists had been able to do with their fancy programs for years.\"\n\n<p>As you of course know, Autodesk offers the \n\n<a href=\"https://360.autodesk.com\">\nAutodesk 360</a> cloud-based \n\nplatform providing access to storage, a collaboration workspace, and a fast-growing number of cloud services to help improve design, visualisation, simulation, and work sharing.\n\n\n<a name=\"3\"></a>\n<h4>Blending Profiles with Different Vertex Counts</h4>\n<p>Arjen de Pater raised a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html?cid=6a00e553e168978833017744a73173970d#comment-6a00e553e168978833017744a73173970d\">\nquestion</a> on \n\nusing the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html\">\nNewBlend method</a> that\n\nMikako Harada just addressed:\n\n<p><strong>Question:</strong> I want to create a blend with 8 curves in the BottomProfile and 4 curves in the TopProfile.\n\n<p>When I try this the Document.FamilyCreate.NewBlend method throws an ApplicationException saying \"Unexpected internal error: code 1. at Autodesk.Revit.Creation.FamilyItemFactory.NewBlend(Boolean isSolid, CurveArray topProfile, CurveArray baseProfile, SketchPlane sketchPlane)\u001d\".\n\n<p>How can I create such a blend?\n\n<p><strong>Answer:</strong> There are some points you need to pay attention to. \nThese points are documented in the page explaining the NewBlend method in Revit API help file RevitAPI.chm file. \nIt also includes sample code to create a blend form:\n\n<ol>\n<li>The two profiles should be parallel.\n<li>Each of the profiles must be planar.\n<li>If the profile shape is circle or ellipse, it must be split into at least two segments, so that Revit can find vertices to use for mapping the blend.\n</li></li></li></ol>\n<p>Once that is clear, you should definitely ensure that you can create the same shape through the user interface, as recommended for\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/debug-geometric-form-creation.html\">\ndebugging form creation</a>.\n\nIf that fails, then it will fail through the API as well.\nIt may provide you with a more informative error message, though.\n\n<p><strong>Response:</strong> Yes, I can create the blend in the UI.\n\n<p>The problem is the different number of curves in the BottomProfile and TopProfile because the NewBlend method lacks a parameter for the VertexConnectionMap.\n\n<p><strong>Answer:</strong> Ah.\nWell, here are two \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/newsweptblend.html\">\nNewSweptBlend</a>\n<a href=\"http://adndevblog.typepad.com/aec/2012/08/newsweptblend-code-sample.html\">\nsamples</a>, which may or may not prove useful. \n\n<p>However, Mikako hopefully provided the ultimate solution by demonstrating\n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/blending-two-profiles-with-different-topbottom-vertex-counts-.html\">\nblending two profiles with different top and bottom vertex counts</a>.\n\n\n<a name=\"4\"></a>\n<h4>Creating a ViewPlan in a Family Document</h4>\n<p>On the topic of Revit API blog posts by my colleagues on the \n\n<a href=\"http://adndevblog.typepad.com/aec\">\nAEC DevBlog</a>,\n\nhere is another interesting topic brought up by Saikat Bhattacharya: \n\n<p>You can \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/creating-a-new-viewplan-in-a-family-document-using-the-revit-api.html\">\ncreate a new ViewPlan in a family document </a> using\n\nthe View.Duplicate method taking a ViewDuplicateOption, something that I was not previously aware of.\n\n<p>You cannot use the NewViewPlan method to achieve this in a family document, because it throws an InvalidOperationException,\nas Saikat explains very clearly.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0824_categories",
    "header_text": "Brute Force Computing",
    "local_header_href": "#brute-force-computing",
    "chunk_text": "<h4>Brute Force Computing</h4><p>I stumbled across this interesting article on \n\n<a href=\"http://bits.blogs.nytimes.com/2012/09/11/the-brute-force-computing-revolution\">\nbrute force computing</a> explaining\n\none interesting aspect of cloud based computing and access to huge amounts of computing power.\n\n<p>One fact I was totally unaware of, and that had me a bit surprised in the past year or two, is that \"brute force computing is behind Google's successful language translation. \nBy comparing thousands of Web pages in different languages to find patterns, in one year Google was able to discern and refine translation better than linguistic theorists had been able to do with their fancy programs for years.\"\n\n<p>As you of course know, Autodesk offers the \n\n<a href=\"https://360.autodesk.com\">\nAutodesk 360</a> cloud-based \n\nplatform providing access to storage, a collaboration workspace, and a fast-growing number of cloud services to help improve design, visualisation, simulation, and work sharing.\n\n\n<a name=\"3\"></a>\n<h4>Blending Profiles with Different Vertex Counts</h4>\n<p>Arjen de Pater raised a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html?cid=6a00e553e168978833017744a73173970d#comment-6a00e553e168978833017744a73173970d\">\nquestion</a> on \n\nusing the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html\">\nNewBlend method</a> that\n\nMikako Harada just addressed:\n\n<p><strong>Question:</strong> I want to create a blend with 8 curves in the BottomProfile and 4 curves in the TopProfile.\n\n<p>When I try this the Document.FamilyCreate.NewBlend method throws an ApplicationException saying \"Unexpected internal error: code 1. at Autodesk.Revit.Creation.FamilyItemFactory.NewBlend(Boolean isSolid, CurveArray topProfile, CurveArray baseProfile, SketchPlane sketchPlane)\u001d\".\n\n<p>How can I create such a blend?\n\n<p><strong>Answer:</strong> There are some points you need to pay attention to. \nThese points are documented in the page explaining the NewBlend method in Revit API help file RevitAPI.chm file. \nIt also includes sample code to create a blend form:\n\n<ol>\n<li>The two profiles should be parallel.\n<li>Each of the profiles must be planar.\n<li>If the profile shape is circle or ellipse, it must be split into at least two segments, so that Revit can find vertices to use for mapping the blend.\n</li></li></li></ol>\n<p>Once that is clear, you should definitely ensure that you can create the same shape through the user interface, as recommended for\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/debug-geometric-form-creation.html\">\ndebugging form creation</a>.\n\nIf that fails, then it will fail through the API as well.\nIt may provide you with a more informative error message, though.\n\n<p><strong>Response:</strong> Yes, I can create the blend in the UI.\n\n<p>The problem is the different number of curves in the BottomProfile and TopProfile because the NewBlend method lacks a parameter for the VertexConnectionMap.\n\n<p><strong>Answer:</strong> Ah.\nWell, here are two \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/newsweptblend.html\">\nNewSweptBlend</a>\n<a href=\"http://adndevblog.typepad.com/aec/2012/08/newsweptblend-code-sample.html\">\nsamples</a>, which may or may not prove useful. \n\n<p>However, Mikako hopefully provided the ultimate solution by demonstrating\n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/blending-two-profiles-with-different-topbottom-vertex-counts-.html\">\nblending two profiles with different top and bottom vertex counts</a>.\n\n\n<a name=\"4\"></a>\n<h4>Creating a ViewPlan in a Family Document</h4>\n<p>On the topic of Revit API blog posts by my colleagues on the \n\n<a href=\"http://adndevblog.typepad.com/aec\">\nAEC DevBlog</a>,\n\nhere is another interesting topic brought up by Saikat Bhattacharya: \n\n<p>You can \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/creating-a-new-viewplan-in-a-family-document-using-the-revit-api.html\">\ncreate a new ViewPlan in a family document </a> using\n\nthe View.Duplicate method taking a ViewDuplicateOption, something that I was not previously aware of.\n\n<p>You cannot use the NewViewPlan method to achieve this in a family document, because it throws an InvalidOperationException,\nas Saikat explains very clearly.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0824_categories",
    "header_text": "Blending Profiles with Different Vertex Counts",
    "local_header_href": "#blending-profiles-with-different-vertex-counts",
    "chunk_text": "<h4>Blending Profiles with Different Vertex Counts</h4><p>Arjen de Pater raised a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html?cid=6a00e553e168978833017744a73173970d#comment-6a00e553e168978833017744a73173970d\">\nquestion</a> on \n\nusing the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/newblend-sample.html\">\nNewBlend method</a> that\n\nMikako Harada just addressed:\n\n<p><strong>Question:</strong> I want to create a blend with 8 curves in the BottomProfile and 4 curves in the TopProfile.\n\n<p>When I try this the Document.FamilyCreate.NewBlend method throws an ApplicationException saying \"Unexpected internal error: code 1. at Autodesk.Revit.Creation.FamilyItemFactory.NewBlend(Boolean isSolid, CurveArray topProfile, CurveArray baseProfile, SketchPlane sketchPlane)\u001d\".\n\n<p>How can I create such a blend?\n\n<p><strong>Answer:</strong> There are some points you need to pay attention to. \nThese points are documented in the page explaining the NewBlend method in Revit API help file RevitAPI.chm file. \nIt also includes sample code to create a blend form:\n\n<ol>\n<li>The two profiles should be parallel.\n<li>Each of the profiles must be planar.\n<li>If the profile shape is circle or ellipse, it must be split into at least two segments, so that Revit can find vertices to use for mapping the blend.\n</li></li></li></ol>\n<p>Once that is clear, you should definitely ensure that you can create the same shape through the user interface, as recommended for\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/debug-geometric-form-creation.html\">\ndebugging form creation</a>.\n\nIf that fails, then it will fail through the API as well.\nIt may provide you with a more informative error message, though.\n\n<p><strong>Response:</strong> Yes, I can create the blend in the UI.\n\n<p>The problem is the different number of curves in the BottomProfile and TopProfile because the NewBlend method lacks a parameter for the VertexConnectionMap.\n\n<p><strong>Answer:</strong> Ah.\nWell, here are two \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/newsweptblend.html\">\nNewSweptBlend</a>\n<a href=\"http://adndevblog.typepad.com/aec/2012/08/newsweptblend-code-sample.html\">\nsamples</a>, which may or may not prove useful. \n\n<p>However, Mikako hopefully provided the ultimate solution by demonstrating\n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/blending-two-profiles-with-different-topbottom-vertex-counts-.html\">\nblending two profiles with different top and bottom vertex counts</a>.\n\n\n<a name=\"4\"></a>\n<h4>Creating a ViewPlan in a Family Document</h4>\n<p>On the topic of Revit API blog posts by my colleagues on the \n\n<a href=\"http://adndevblog.typepad.com/aec\">\nAEC DevBlog</a>,\n\nhere is another interesting topic brought up by Saikat Bhattacharya: \n\n<p>You can \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/creating-a-new-viewplan-in-a-family-document-using-the-revit-api.html\">\ncreate a new ViewPlan in a family document </a> using\n\nthe View.Duplicate method taking a ViewDuplicateOption, something that I was not previously aware of.\n\n<p>You cannot use the NewViewPlan method to achieve this in a family document, because it throws an InvalidOperationException,\nas Saikat explains very clearly.\n</p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0824_categories",
    "header_text": "Creating a ViewPlan in a Family Document",
    "local_header_href": "#creating-a-viewplan-in-a-family-document",
    "chunk_text": "<h4>Creating a ViewPlan in a Family Document</h4><p>On the topic of Revit API blog posts by my colleagues on the \n\n<a href=\"http://adndevblog.typepad.com/aec\">\nAEC DevBlog</a>,\n\nhere is another interesting topic brought up by Saikat Bhattacharya: \n\n<p>You can \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/creating-a-new-viewplan-in-a-family-document-using-the-revit-api.html\">\ncreate a new ViewPlan in a family document </a> using\n\nthe View.Duplicate method taking a ViewDuplicateOption, something that I was not previously aware of.\n\n<p>You cannot use the NewViewPlan method to achieve this in a family document, because it throws an InvalidOperationException,\nas Saikat explains very clearly.\n</p></p></p>"
  }
]