[
  {
    "original_filename": "0873_close_active_doc",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0873_close_active_doc",
    "header_text": "Installing a Macro and Closing the Active Document",
    "local_header_href": "#installing-a-macro-and-closing-the-active-document",
    "chunk_text": "<h3>Installing a Macro and Closing the Active Document</h3><p>You can close an open Revit document programmatically.\nUnfortunately, though, this only works for all except the last one.\n\n<p>People keep running into this issue, of course.\nIt even motivated René Gerlach to implement a workaround using SendKeys.SendWait to send an Alt-F4 keystroke to Revit to\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html\">\nclose the active window</a>,\n\nand Arnošt Löbel to\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html#2\">\nwarn gravely</a> against its use and even publish a\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html#3\">\nWindows message workaround disclaimer</a>.</p>\n<p>Well, happily, such an adventurous workaround is not at all required.\nAnother workaround making use only of fully supported API calls is obvious and simple, once you think  of it: if you really want to close the current document, and it happens to be the last one, all you have to do is open some other document first.\nYou can use a dummy document for this purpose.\nOnce it has been opened, the other 'real' document can be closed.</p>\n<p>Steven Mycynek of the Revit API development team provided a sample add-in named UiClose implementing this.\nHere is the description in his own words:</p>\n<blockquote>\n<p>Enclosed is some sample code I use to close the active document through the API.\nI am sure it has some limitations and bugs, but it's a nice start.\n\n<p>To use, simply install the UiClose macro to your macros folder and place the _placeHolder_.rvt dummy model into C:/uiclose or some other location where the main macro can find it.\n\n<p>The demo application closes the active document, opening _placeholder_.rvt when necessary, and will not accidentally close the placeholder document.\n\n<p>It might also be possible to do something with events in an application to make this more automatic, but this wraps it up for now.\n\n</p></p></p></p></blockquote>\n<p>Steve implemented this as a SharpDevelop macro.</p>\n<p>The macro files need to be placed in the appropriate\n\n<a href=\"http://wikihelp.autodesk.com/Revit/enu/2013/Help/00001-Revit_He0/3032-Customiz3032/3207-Automati3207/3208-Getting_3208/3209-Upgradin3209\">\nmacro directory</a>:</p>\n<ul>\n<li>Windows XP: C:\\Documents and Settings\\All Users\\Application Data\\Autodesk\\Revit\\Macros\\&lt;release&gt;\\&lt;product&gt;\\VstaMacros</li>\n<li>Windows 7: C:\\ProgramData\\Autodesk\\Revit\\Macros\\&lt;release&gt;\\&lt;product&gt;\\VstaMacros</li>\n</ul>\n<p>In my case, this resolves to</p>\n<ul>\n<li>C:\\Documents and Settings\\All Users\\Application Data\\Autodesk\\Revit\\Macros\\2013\\Revit\\VstaMacros</li>\n</ul>\n<p>Actually, to see the UiClose macro in the SharpDevelop IDE, I had to place the UiClose folder into the AppHookup subdirectory, so its full path ends up as:</p>\n<ul>\n<li>C:\\Documents and Settings\\All Users\\Application Data\\Autodesk\\Revit\\Macros\\2013\\Revit\\VstaMacros\\AppHookup\\UiClose</li>\n</ul>\n<p>Now I see the UiClose module and its CloseActiveDocDemo macro in the Manage &gt; Macros &gt; Macro Manager:</p>\n<center>\n<img alt=\"UiClose CloseActiveDocDemo macro\" src=\"img/UiClose.png\" width=\"400\"/>\n</center>\n<p>When I run the macro, the current active document is closed.\nIf it is the last one, the placeholder document is opened in its stead.</p>\n<p>If it has unsaved changes, a dialogue box prompting me whether to save or not is displayed.\nThe macro could obviously be improved to check for that before trying to close the document to avoid such an interruption, or handle it more gracefully.</p>\n<p>The macro itself is a trivial one-liner, since it just calls the CloseAndSave method provided by the CloseHelper helper class:</p>\n<pre class=\"code&gt;\">\n  <span class=\"blue\">public</span> <span class=\"blue\">void</span> CloseActiveDocDemo()\n  {\n    Autodesk.Revit.UI.<span class=\"teal\">UIDocument</span> doc\n      = <span class=\"blue\">this</span>.ActiveUIDocument;\n \n    CloseHelper.CloseAndSave( doc );\n  }\n</pre>\n<p>The rest of the ThisApplication class methods deal with setting up and managing the helper class:</p>\n<pre class=\"code&gt;\">\n<span class=\"blue\">public</span> <span class=\"blue\">partial</span> <span class=\"blue\">class</span> <span class=\"teal\">ThisApplication</span>\n{\n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> Module_Startup(\n    <span class=\"blue\">object</span> sender,\n    <span class=\"teal\">EventArgs</span> e )\n  {\n    m_CloseHelper = <span class=\"blue\">new</span> UiCloseHelper(\n      <span class=\"blue\">this</span>,\n      <span class=\"maroon\">@\"C:\\\\uiClose\\\\_placeholder_.rvt\"</span> );\n  }\n \n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> Module_Shutdown(\n    <span class=\"blue\">object</span> sender,\n    <span class=\"teal\">EventArgs</span> e )\n  {\n  }\n \n<span class=\"blue\">  #region</span> Revit Macros generated code\n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> InternalStartup()\n  {\n    <span class=\"blue\">this</span>.Startup += <span class=\"blue\">new</span> System.<span class=\"teal\">EventHandler</span>(\n      Module_Startup );\n \n    <span class=\"blue\">this</span>.Shutdown += <span class=\"blue\">new</span> System.<span class=\"teal\">EventHandler</span>(\n      Module_Shutdown );\n  }\n \n  <span class=\"blue\">public</span> UiCloseHelper CloseHelper\n  {\n    <span class=\"blue\">get</span>\n    {\n      <span class=\"blue\">return</span> m_CloseHelper;\n    }\n  }\n \n  <span class=\"blue\">private</span> UiCloseHelper m_CloseHelper;\n<span class=\"blue\">  #endregion</span>\n}\n</pre>\n<p>So finally, let's take a look at the UiCloseHelper implementation in all its glory:</p>\n<pre class=\"code&gt;\">\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> A helper class to keep a placeholder document </span>\n<span class=\"gray\">///</span><span class=\"green\"> open in Revit to allow closing the active </span>\n<span class=\"gray\">///</span><span class=\"green\"> document in Revit.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">UiCloseHelper</span>\n{\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Constructor -- initializes object with </span>\n  <span class=\"gray\">///</span><span class=\"green\"> a UIApplication and location of a </span>\n  <span class=\"gray\">///</span><span class=\"green\"> placeholder document.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"uiAppInterface\"&gt;</span><span class=\"green\">The Revit UI Application, pass either a UIApplication or an ApplicationEntryPoint</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"placeholderPath\"&gt;</span><span class=\"green\">Path to a dummy .rvt file.</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"blue\">public</span> UiCloseHelper(\n    <span class=\"blue\">dynamic</span> uiAppInterface,\n    <span class=\"blue\">string</span> placeholderPath )\n  {\n    m_uiAppInterface = uiAppInterface;\n \n    <span class=\"blue\">if</span>( m_uiAppInterface == <span class=\"blue\">null</span> )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>(\n        <span class=\"maroon\">\"m_uiAppInterface\"</span> );\n    }\n \n    <span class=\"blue\">if</span>( ( !( uiAppInterface <span class=\"blue\">is</span> Autodesk.Revit.UI.<span class=\"teal\">UIApplication</span> ) )\n        &amp;&amp; ( !( uiAppInterface <span class=\"blue\">is</span> Autodesk.Revit.UI.Macros.<span class=\"teal\">ApplicationEntryPoint</span> ) ) )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentException</span>(\n        <span class=\"maroon\">\"Must pass a UIApplication or ApplicationEntryPoint.\"</span> );\n    }\n \n    SetPlaceHolderPath( placeholderPath );\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Closes a UIDocument with the same </span>\n  <span class=\"gray\">///</span><span class=\"green\"> interface as UIDocument.Close</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"uiDoc\"&gt;</span><span class=\"green\">The document to close</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;returns&gt;</span><span class=\"green\">True if successful, false otherwise.</span><span class=\"gray\">&lt;/returns&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> CloseAndSave(\n    Autodesk.Revit.UI.<span class=\"teal\">UIDocument</span> uiDoc )\n  {\n    <span class=\"blue\">if</span>( uiDoc == <span class=\"blue\">null</span> )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"uiDoc\"</span> );\n    }\n \n    RejectClosingPlaceHolder( uiDoc );\n \n    <span class=\"blue\">if</span>( !EnsureActivePlaceHolder( m_uiAppInterface ) )\n      <span class=\"blue\">return</span> <span class=\"blue\">false</span>;\n \n    <span class=\"blue\">return</span> uiDoc.SaveAndClose();\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Closes a DB.Document with the same </span>\n  <span class=\"gray\">///</span><span class=\"green\"> interface as DB.Document.Close</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"doc\"&gt;</span><span class=\"green\">The DB.Document to close</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;returns&gt;</span><span class=\"green\">True if successful, false otherwise.</span><span class=\"gray\">&lt;/returns&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> Close( Autodesk.Revit.DB.<span class=\"teal\">Document</span> doc )\n  {\n    <span class=\"blue\">return</span> Close( doc, <span class=\"blue\">true</span> );\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Closes a DB.Document with the same </span>\n  <span class=\"gray\">///</span><span class=\"green\"> interface as DB.Document.Close</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"doc\"&gt;</span><span class=\"green\">The DB.Document to close</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"saveModified\"&gt;</span><span class=\"green\">true to save the document if modified, false to not save.</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;returns&gt;</span><span class=\"green\">True if successful, false otherwise.</span><span class=\"gray\">&lt;/returns&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> Close(\n    Autodesk.Revit.DB.<span class=\"teal\">Document</span> doc,\n    <span class=\"blue\">bool</span> saveModified )\n  {\n    <span class=\"blue\">if</span>( doc == <span class=\"blue\">null</span> )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"doc\"</span> );\n    }\n \n    RejectClosingPlaceHolder( doc );\n \n    <span class=\"blue\">if</span>( !EnsureActivePlaceHolder( m_uiAppInterface ) )\n      <span class=\"blue\">return</span> <span class=\"blue\">false</span>;\n \n    <span class=\"blue\">return</span> doc.Close( saveModified );\n  }\n \n<span class=\"blue\">  #region</span> Helper methods\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Throws an exception if the user </span>\n  <span class=\"gray\">///</span><span class=\"green\"> passes the placeholder document.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"doc\"&gt;</span><span class=\"green\">The document to test to ensure it is not the placeholder document.</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> RejectClosingPlaceHolder(\n    Autodesk.Revit.DB.<span class=\"teal\">Document</span> doc )\n  {\n    <span class=\"blue\">if</span>( doc.Title == System.IO.<span class=\"teal\">Path</span>.GetFileName(\n      <span class=\"blue\">this</span>.m_placeHolderPath ) )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentException</span>(\n        <span class=\"maroon\">\"Cannot close placeholder doc: \"</span> + doc.Title );\n    }\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Throws an exception if the user </span>\n  <span class=\"gray\">///</span><span class=\"green\"> passes the placeholder document.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"doc\"&gt;</span><span class=\"green\">The document to check</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> RejectClosingPlaceHolder(\n    Autodesk.Revit.UI.<span class=\"teal\">UIDocument</span> uiDoc )\n  {\n    RejectClosingPlaceHolder( uiDoc.Document );\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Ensures that the placeholder document is open </span>\n  <span class=\"gray\">///</span><span class=\"green\"> and active to that another open document can be closed.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">private</span> <span class=\"blue\">bool</span> EnsureActivePlaceHolder(\n    <span class=\"blue\">dynamic</span> application )\n  {\n    <span class=\"blue\">try</span>\n    {\n      <span class=\"blue\">if</span>( m_placeHolderDoc == <span class=\"blue\">null</span> )\n      {\n        m_placeHolderDoc = application\n          .OpenAndActivateDocument( m_placeHolderPath );\n      }\n      <span class=\"blue\">else</span>\n      {\n        m_placeHolderDoc.SaveAndClose();\n        m_placeHolderDoc = application\n          .OpenAndActivateDocument( m_placeHolderPath );\n      }\n      <span class=\"blue\">return</span> <span class=\"blue\">true</span>;\n    }\n    <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> )\n    {\n      <span class=\"blue\">return</span> <span class=\"blue\">false</span>;\n    }\n  }\n \n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Sets the path of the placeholder document.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;param name=\"path\"&gt;</span><span class=\"green\">Path to placeholder/dummy document.</span><span class=\"gray\">&lt;/param&gt;</span>\n  <span class=\"blue\">private</span> <span class=\"blue\">void</span> SetPlaceHolderPath( <span class=\"blue\">string</span> path )\n  {\n    m_placeHolderPath = path;\n \n    <span class=\"blue\">if</span>( !System.IO.<span class=\"teal\">File</span>.Exists( m_placeHolderPath ) )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentException</span>(\n        <span class=\"maroon\">\"File not found: \"</span> + path );\n    }\n    <span class=\"blue\">if</span>( !( System.IO.<span class=\"teal\">Path</span>.GetExtension( m_placeHolderPath ) != <span class=\"maroon\">\"rvt\"</span> ) )\n    {\n      <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentException</span>( <span class=\"maroon\">\"Placeholder: \"</span>\n        + path + <span class=\"maroon\">\" is not a revit file.\"</span> );\n    }\n  }\n<span class=\"blue\">  #endregion</span>\n \n<span class=\"blue\">  #region</span> Data\n  <span class=\"blue\">private</span> Autodesk.Revit.UI.<span class=\"teal\">UIDocument</span> m_placeHolderDoc;\n  <span class=\"blue\">private</span> <span class=\"blue\">string</span> m_placeHolderPath;\n  <span class=\"blue\">private</span> <span class=\"blue\">dynamic</span> m_uiAppInterface;\n<span class=\"blue\">  #endregion</span>\n}\n</pre>\n<p>It reads a lot harder than it actully is  :-)</p>\n<p>Here is\n\n<a href=\"zip/UiClose.zip\">\nUiClose.zip</a> containing the macro source code and its associated\n\n<a href=\"zip/_placeholder_.rvt\">\nplaceholder</a> project document.\n\n<p>Many thanks to Steve for providing this useful and interesting workaround!</p>\n</p></p>"
  }
]