[
  {
    "original_filename": "0913_match_view_tag_room",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0913_match_view_tag_room",
    "header_text": "Rename View by Matching Elevation Tag with Room",
    "local_header_href": "#rename-view-by-matching-elevation-tag-with-room",
    "chunk_text": "<h3>Rename View by Matching Elevation Tag with Room</h3><p>Today is the last morning meeting with my European DevTech colleagues here in Brittany, and time to travel back to Switzerland.</p><p>Before leaving, here is a useful real-world productivity tool by Trevor Taylor of ZGF,\n\n<a href=\"http://www.zgf.com\">Zimmer Gunsul Frasca Architects LLP</a>,\n\nwith his own description of the task and its solution:</p><p>The task I want to address is to match interior elevation tags with the rooms they fall inside.\n\n<p>This is used to track back and rename the corresponding views.\n\n<p>Naming interior elevation views is a major time-burner as there can be thousands of views in a project to rename, and they have to be coordinated when the room numbers  or names change.\nIf we don’t tie view names to rooms, we have no hope of ever keeping track of so many views.\n\n<p>I originally attacked  this by trying to determine the location of the view tags in the model, but had to give up on that one.</p>\n<p>Ben Bishoff of <a href=\"http://www.ideate.com\">Ideate</a> gave me the idea to approach the problem from the view rather than from the interior elevation tag, so I worked backwards from the view cropbox property using the RevitLookup app and arrived at this simple solution:\n\n<p><strong>1.</strong> Collect all views of class ‘ViewSection’, then filter down to those of ‘Interior Elevation’ type:</p>\n<pre class=\"code\">\n  <span class=\"teal\">FilteredElementCollector</span> collector\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( m_doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">ViewSection</span> ) );\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">ViewSection</span> current <span class=\"blue\">in</span> collector )\n  {\n    <span class=\"teal\">ViewFamilyType</span> vft = m_doc.GetElement(\n      current.GetTypeId() ) <span class=\"blue\">as</span> <span class=\"teal\">ViewFamilyType</span>;\n \n    <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != vft\n      &amp;&amp; vft.Name == <span class=\"maroon\">\"Interior Elevation\"</span> )\n    {\n      m_int_elevation_views.Add( current );\n    }\n  }\n</pre>\n<p><strong>2.</strong> Construct a point at the midpoint of the front bottom edge of each interior elevation view's CropBox.\nThe CropBox is conveniently relative to the projection plane of the view.\nX is to right, Y is up, and Z is the view depth:\n\n<pre class=\"code\">\n  <span class=\"green\">// Construct a point at the midpoint of the </span>\n  <span class=\"green\">// front bottom edge of the elev view cropbox</span>\n \n  <span class=\"blue\">double</span> xmax = v.CropBox.Max.X;\n  <span class=\"blue\">double</span> xmin = v.CropBox.Min.X;\n  <span class=\"blue\">double</span> zmax = v.CropBox.Max.Z;\n \n  <span class=\"teal\">XYZ</span> pt = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>(\n    xmax - 0.5 * ( xmax - xmin ),\n    1.0,\n    zmin );\n</pre>\n<p><strong>3.</strong> Get pt's translation to project's coordinate system:\n\n<pre class=\"code\">\n  <span class=\"green\">// Get pt's translation to </span>\n  <span class=\"green\">// project coordinate system</span>\n \n  pt = v.CropBox.Transform.OfPoint( pt );\n \n</pre>\n<p>That takes care of the heavy lifting. Pass pt to the GetRoomAtPoint method and you obtain the room, if there is one to get:\n\n<p><strong>4.</strong> Retrieve the room:\n\n<pre class=\"code\">\n  Autodesk.Revit.DB.Architecture.<span class=\"teal\">Room</span> rm\n    = m_doc.GetRoomAtPoint( pt );\n</pre>\n<p>It does exactly what I want it to now and will save our teams countless hours on large projects by organizing the names of interior elevation views by room name:</p>\n<center>\n<img alt=\"Elevation renaming map\" src=\"img/elevation_renaming_map.png\"/>\n</center>\n<p>Here is a\n\n<a href=\"zip/interior_elevation_view_organizer_2.zip\">\ncomplete sample project</a> including a test model in case you’d like to check it out yourself.\n\n<p>Many thanks to Trevor for this useful tool, his research, implementation, and generous sharing.</p>\n<p>Before I sign off, here are two other nice pointers, not related to Revit:</p>\n<a name=\"2\"></a>\n<h4>Au Bout du Monde and Super-Sonic Stereo</h4>\n<p>Brittany is at the end of the earth, or Finisterre, au bout du monde, and I have seen many restaurants, a parking place, and a number of other establishments named after that around here.</p>\n<p>That reminded me of one of my favourite humorous YouTube films, a Russian cartoon also named\n\n<a href=\"http://www.youtube.com/watch?v=jsoKbk6GXQc\">Au Bout du Monde</a>,\n\nby Konstantin Bronzit:</p>\n<center>\n<iframe allowfullscreen=\"\" frameborder=\"0\" height=\"315\" src=\"http://www.youtube.com/embed/jsoKbk6GXQc\" width=\"420\"></iframe>\n</center>\n<p>It was very fitting to share with my colleagues, since two of us are Russian as well.\nWe enjoyed it a lot, and I hope you like it as much as I do.</p>\n<p>While we are at it, yesterday, my son Christopher pointed out another quite nice blog with explanations of what-if questions, the most recent one featuring sound sources, asking\n\n<a href=\"http://what-if.xkcd.com/37\">what if my stereo flew around at super-sonic speed?</a>\n\nI enjoyed that as well, and so might you.</p>\n<p>Last but not least, today is the first day of spring and\n\n<a href=\"http://en.wikipedia.org/wiki/Equinox\">\nvernal equinox</a>!</p>\n<center>\n<img alt=\"Spring and vernal equinox\" src=\"img/anoixi.jpeg\" width=\"400\"/>\n</center>\n<p>Off we go to the airport...</p>\n</p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0913_match_view_tag_room",
    "header_text": "Au Bout du Monde and Super-Sonic Stereo",
    "local_header_href": "#au-bout-du-monde-and-super-sonic-stereo",
    "chunk_text": "<h4>Au Bout du Monde and Super-Sonic Stereo</h4><p>Brittany is at the end of the earth, or Finisterre, au bout du monde, and I have seen many restaurants, a parking place, and a number of other establishments named after that around here.</p><p>That reminded me of one of my favourite humorous YouTube films, a Russian cartoon also named\n\n<a href=\"http://www.youtube.com/watch?v=jsoKbk6GXQc\">Au Bout du Monde</a>,\n\nby Konstantin Bronzit:</p><center>\n<iframe allowfullscreen=\"\" frameborder=\"0\" height=\"315\" src=\"http://www.youtube.com/embed/jsoKbk6GXQc\" width=\"420\"></iframe>\n</center><p>It was very fitting to share with my colleagues, since two of us are Russian as well.\nWe enjoyed it a lot, and I hope you like it as much as I do.</p><p>While we are at it, yesterday, my son Christopher pointed out another quite nice blog with explanations of what-if questions, the most recent one featuring sound sources, asking\n\n<a href=\"http://what-if.xkcd.com/37\">what if my stereo flew around at super-sonic speed?</a>\n\nI enjoyed that as well, and so might you.</p><p>Last but not least, today is the first day of spring and\n\n<a href=\"http://en.wikipedia.org/wiki/Equinox\">\nvernal equinox</a>!</p><center>\n<img alt=\"Spring and vernal equinox\" src=\"img/anoixi.jpeg\" width=\"400\"/>\n</center><p>Off we go to the airport...</p>"
  }
]