[
  {
    "original_filename": "1154_directshape_min_size",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "1154_directshape_min_size",
    "header_text": "DirectShape Performance and Minimum Size",
    "local_header_href": "#directshape-performance-and-minimum-size",
    "chunk_text": "<h3>DirectShape Performance and Minimum Size</h3><p>One of the exciting API enhancements in Revit 2015 is the Import API functionality providing the new\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/04/whats-new-in-the-revit-2015-api.html#3.09\">\nDirectShape and TessellatedShapeBuilder</a> classes.</p><p>These enable significant <a href=\"#2\">performance enhancements</a> and powerful new possibilities for generating libraries and importing geometry, especially repetitive shapes.</p><p>On the other hand, the same limitations on <a href=\"#3\">minimum size</a> apply as in the past.</p><a name=\"2\"></a>"
  },
  {
    "original_filename": "1154_directshape_min_size",
    "header_text": "DirectShape Performance",
    "local_header_href": "#directshape-performance",
    "chunk_text": "<h4>DirectShape Performance</h4><p>Regarding the performance, here is a first enthusiastic reaction and quick report from a developer after the initial introduction during the beta phase last December:</p><p>I examined the DirectShape functionality a little.</p><p>My results are very interesting.</p><p>I implemented a benchmark generating 'room solids'.</p><p>In the past, I had to create a new family for this, define its geometry using freeform elements, save the family, load it into the project and place an instance.</p><p>That method took about 2 hours for 1390 rooms and increased the file size by about 60 Kb per room.</p><p>My first alternative test implementation using DirectShape elements takes 40 seconds in total and increases the file size by 2 Kb per room.</p><p>This offers fantastic new possibilities to create quick \"permanent\" geometry!</p><p>Not to mention how much simpler the code is now!</p><p>Knowing the Revit API, there is one obvious limitation, though...</p><a name=\"3\"></a>"
  },
  {
    "original_filename": "1154_directshape_min_size",
    "header_text": "DirectShape Minimum Size",
    "local_header_href": "#directshape-minimum-size",
    "chunk_text": "<h4>DirectShape Minimum Size</h4><p>Here is a question that came up a couple of times now:</p><p><strong>Question:</strong> I created a DirectShape in Revit 2015 from a collection of faces using TessellatedShapeBuilder.</p><p>The minimum length for edges accepted by Revit is 0.0026 feet. If I use 0.0025 feet Revit crashes.</p><p>Can I change this tolerance?</p><p>Or is any other way to construct DirectShape elements that accepts edges smaller than 0.0026 feet?</p><p><strong>Answer:</strong> Unfortunately, the answer is no and no.</p><p>This tolerance cannot be changed, and I am not aware of any other way to create DirectShape elements to circumvent that limitation.</p><p>You\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/think-big-in-revit.html\">\nhave to think big</a> when\n\ncreating objects in Revit, to the chagrin of people wishing to represent very detailed metal and sub-millimetre wood construction.</p><p>The limitation in creating individual model line segments lies around 1/16 of an inch, and the same applies to DirectShape element edges.</p><p>I implemented a little external command to test this.</p><p>It defines a static Boolean switch variable named <code>Iterate_until_crash</code>.</p><p>It is set to false by default, in which case the external command simply creates a DirectShape tetrahedron with an edge length of 0.5 feet like this:</p><center>\n<img alt=\"DirectShape tetrahedron\" src=\"img/direct_shape_min_size_1.png\" width=\"138\"/>\n</center><p>It reports its accomplished task like this in the Visual Studio debugging output window:</p><pre>\nCreating DirectShape tetrahedron with side length 0.5...\n</pre><p>When Iterate_until_crash is set to true, the code enters an infinite loop creating successive DirectShape elements in each iteration, each with half of the preceding edge length.</p><p>It throws and exception quite soon, though, so none of the shapes end up being committed, and the debug output now reports:</p><pre>\nCreating DirectShape tetrahedron with side length 0.5...\nCreating DirectShape tetrahedron with side length 0.25...\nCreating DirectShape tetrahedron with side length 0.125...\nCreating DirectShape tetrahedron with side length 0.0625...\nCreating DirectShape tetrahedron with side length 0.03125...\nCreating DirectShape tetrahedron with side length 0.015625...\nCreating DirectShape tetrahedron with side length 0.0078125...\nCreating DirectShape tetrahedron with side length 0.00390625...\nCreating DirectShape tetrahedron with side length 0.001953125...\n</pre><ul>\n<li>A first chance exception of type 'Autodesk.Revit.Exceptions.InvalidOperationException' occurred in RevitAPI.dll</li>\n<li>Creating DirectShape tetrahedron with side length 0.001953125 threw exception 'could not create consistent vertex list'</li>\n</ul><p>The exception is passed back to the standard Revit failure handler:</p><center>\n<img alt=\"DirectShape minimum size\" src=\"img/direct_shape_min_size_2.png\"/>\n</center><p>Here is the entire external command implementation:</p><pre class=\"code\">\n<span class=\"blue\">#region</span> Namespaces\n<span class=\"blue\">using</span> System;\n<span class=\"blue\">using</span> System.Linq;\n<span class=\"blue\">using</span> System.Collections.Generic;\n<span class=\"blue\">using</span> System.Diagnostics;\n<span class=\"blue\">using</span> Autodesk.Revit.ApplicationServices;\n<span class=\"blue\">using</span> Autodesk.Revit.Attributes;\n<span class=\"blue\">using</span> Autodesk.Revit.DB;\n<span class=\"blue\">using</span> Autodesk.Revit.UI;\n<span class=\"blue\">using</span> Autodesk.Revit.UI.Selection;\n<span class=\"blue\">#endregion</span>\n \n<span class=\"blue\">namespace</span> DirectShapeMinSize\n{\n  [<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n  <span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">Command</span> : <span class=\"teal\">IExternalCommand</span>\n  {\n    <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n    <span class=\"gray\">///</span><span class=\"green\"> Set this to true to iterate through smaller </span>\n    <span class=\"gray\">///</span><span class=\"green\"> and smaller tetrahedron sizes until we hit</span>\n    <span class=\"gray\">///</span><span class=\"green\"> Revit's precision limit.</span>\n    <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n    <span class=\"blue\">static</span> <span class=\"blue\">bool</span> Iterate_until_crash = <span class=\"blue\">false</span>;\n \n    <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n      <span class=\"teal\">ExternalCommandData</span> commandData,\n      <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n      <span class=\"teal\">ElementSet</span> elements )\n    {\n      <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n      <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n      <span class=\"teal\">Application</span> app = uiapp.Application;\n      <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n      <span class=\"green\">// Find GraphicsStyle</span>\n \n      <span class=\"teal\">FilteredElementCollector</span> collector\n        = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n          .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">GraphicsStyle</span> ) );\n \n      <span class=\"teal\">GraphicsStyle</span> style = collector.Cast&lt;<span class=\"teal\">GraphicsStyle</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">GraphicsStyle</span>&gt;( gs =&gt; gs.Name.Equals( <span class=\"maroon\">\"&lt;Sketch&gt;\"</span> ) );\n \n      <span class=\"teal\">ElementId</span> graphicsStyleId = <span class=\"blue\">null</span>;\n \n      <span class=\"blue\">if</span>( style != <span class=\"blue\">null</span> )\n      {\n        graphicsStyleId = style.Id;\n      }\n \n      <span class=\"green\">// Modify document within a transaction</span>\n \n      <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n      {\n        tx.Start( <span class=\"maroon\">\"Create DirectShape\"</span> );\n \n        <span class=\"blue\">double</span> length = 1; <span class=\"green\">// foot</span>\n \n        <span class=\"blue\">try</span>\n        {\n          <span class=\"blue\">do</span>\n          {\n            length = 0.5 * length;\n \n            <span class=\"teal\">Debug</span>.Print(\n                <span class=\"maroon\">\"Creating DirectShape tetrahedron with side length {0}...\"</span>,\n                length );\n \n            <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; args = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt;( 3 );\n \n            <span class=\"teal\">TessellatedShapeBuilder</span> builder = <span class=\"blue\">new</span> <span class=\"teal\">TessellatedShapeBuilder</span>();\n \n            builder.OpenConnectedFaceSet( <span class=\"blue\">false</span> );\n \n            args.Add( <span class=\"teal\">XYZ</span>.Zero );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisX );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisY );\n            builder.AddFace( <span class=\"blue\">new</span> <span class=\"teal\">TessellatedFace</span>( args, <span class=\"teal\">ElementId</span>.InvalidElementId ) );\n \n            args.Clear();\n            args.Add( <span class=\"teal\">XYZ</span>.Zero );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisX );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisZ );\n            builder.AddFace( <span class=\"blue\">new</span> <span class=\"teal\">TessellatedFace</span>( args, <span class=\"teal\">ElementId</span>.InvalidElementId ) );\n \n            args.Clear();\n            args.Add( <span class=\"teal\">XYZ</span>.Zero );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisY );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisZ );\n            builder.AddFace( <span class=\"blue\">new</span> <span class=\"teal\">TessellatedFace</span>( args, <span class=\"teal\">ElementId</span>.InvalidElementId ) );\n \n            args.Clear();\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisX );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisY );\n            args.Add( length * <span class=\"teal\">XYZ</span>.BasisZ );\n            builder.AddFace( <span class=\"blue\">new</span> <span class=\"teal\">TessellatedFace</span>( args, <span class=\"teal\">ElementId</span>.InvalidElementId ) );\n \n            builder.CloseConnectedFaceSet();\n \n            <span class=\"teal\">TessellatedShapeBuilderResult</span> result\n              = builder.Build(\n                <span class=\"teal\">TessellatedShapeBuilderTarget</span>.Solid,\n                <span class=\"teal\">TessellatedShapeBuilderFallback</span>.Abort,\n                graphicsStyleId );\n \n            <span class=\"green\">// Pre-release code from DevDays</span>\n \n            <span class=\"green\">//DirectShape ds = DirectShape.CreateElement(</span>\n            <span class=\"green\">//  doc, result.GetGeometricalObjects(), \"A\", \"B\");</span>\n \n            <span class=\"green\">//ds.SetCategoryId(new ElementId(</span>\n            <span class=\"green\">//  BuiltInCategory.OST_GenericModel));</span>\n \n            <span class=\"green\">// Code updated for Revit UR1</span>\n \n            <span class=\"teal\">ElementId</span> categoryId = <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>(\n              <span class=\"teal\">BuiltInCategory</span>.OST_GenericModel );\n \n            <span class=\"teal\">DirectShape</span> ds = <span class=\"teal\">DirectShape</span>.CreateElement(\n              doc, categoryId, <span class=\"maroon\">\"A\"</span>, <span class=\"maroon\">\"B\"</span> );\n \n            ds.SetShape( result.GetGeometricalObjects() );\n \n            ds.Name = <span class=\"maroon\">\"Test\"</span>;\n          }\n          <span class=\"blue\">while</span>( Iterate_until_crash &amp;&amp; 0 &lt; length );\n        }\n        <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> e )\n        {\n          <span class=\"teal\">Debug</span>.Print(\n            <span class=\"maroon\">\"Creating DirectShape tetrahedron with side length {0} \"</span>\n            + <span class=\"maroon\">\"threw exception '{1}'\"</span>,\n            length, e.Message );\n \n          message = e.Message;\n          <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n        }\n        tx.Commit();\n      }\n      <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n    }\n  }\n}\n</pre><p>For your convenience, here is\n\n<a href=\"zip/DirectShapeMinSize.zip\">DirectShapeMinSize.zip</a> providing\n\nthe complete source code, Visual Studio solution and add-in manifest for the DirectShapeMinSize external command.</p>"
  }
]