[
  {
    "original_filename": "1362_answer_day_create_roof",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!---\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n- change selected instance type\n  email [Revit API]\n  taking a second look at this question, i note that most of what the developer needs is already implemented in the external command Lab3_4_ChangeSelectedInstanceType in the module https://github.com/jeremytammik/AdnRevitApiLabsXtra/blob/master/XtraCs/Labs3.cs\n\n- IterateOverCollector\n  email [Regarding [CaseNo:11090027.] ElementIdを取得する方法] Ryuji Ogasawara \n\n- creating an electrical family\n  email [RFA API (especially in Electrical content context)]\n\n#dotnet #csharp #geometry\n#fsharp #dynamobim #python\n#grevit\n#responsivedesign #typepad\n#ah8 #augi #au2015 #dotnet #dynamobim\n#stingray #adsklabs #cloud #rendering\n#3dweb #3dviewapi #html5 #threejs #webgl #3d #apis #mobile #vr #ecommerce\n#Markdown #Fusion360 #Fusion360Hackathon #revitapi #3dwebcoder\n#javascript\n#au2015 #rtceur\n#RestSharp #restapi\n#au2015\n#mongoosejs #mongodb #nodejs\n#au2015 #rtceur\n\nRevit API, Jeremy Tammik, akn_include\n\nRevit Answer Day and Creating a Roof #revitapi #bim #aec #3dwebcoder #adsk #adskdevnetwrk\n\nToday I'll highlight two items, plus an addendum for Kinjal and Carolina\n&ndash; Revit Answer Day\n&ndash; Creating a Roof\n&ndash; Setting FootPrintRoof Slope...\n\n-->"
  },
  {
    "original_filename": "1362_answer_day_create_roof",
    "header_text": "Revit Answer Day and Creating a Roof",
    "local_header_href": "#revit-answer-day-and-creating-a-roof",
    "chunk_text": "### Revit Answer Day and Creating a Roof\n\nToday I'll just highlight two items that were also already pointed out\nby [Jaime Rosales](http://adndevblog.typepad.com/aec/jaime-rosales.html) on\nthe [AEC DevBlog](http://adndevblog.typepad.com/aec), plus an addendum for Kinjal and Carolina:\n\n- [Revit Answer Day](#2)\n- [Creating a Roof](#3)\n- [Setting FootPrintRoof Slope](#4)"
  },
  {
    "original_filename": "1362_answer_day_create_roof",
    "header_text": "<a name=\"2\"></a>Revit Answer Day",
    "local_header_href": "#a-name2arevit-answer-day",
    "chunk_text": "#### <a name=\"2\"></a>Revit Answer Day\n\nDo you have any Revit or Revit LT questions that you’ve always wanted to get answered?\n\nIf so, please join the next instalment\nof [Ask Autodesk Anything](http://www.autode.sk/answerdays) events,\nthe [Revit Answer Day](http://forums.autodesk.com/t5/revit-answer-day/revit-answer-day-october-7th-2015/td-p/5787599) on\nOctober 7, 2015.\n\nThis event is dedicated to answering your questions about Revit and Revit LT.\nWe’ll have some DevTech engineers attending the event to answer your API questions.\nThe event runs from 6 am to 6 pm Pacific Time and will take place in Autodesk Community.\nYou can spend a minute, an hour, or the whole day in the Autodesk Community to interact directly with the folks who can answer every question about Revit you can think of."
  },
  {
    "original_filename": "1362_answer_day_create_roof",
    "header_text": "<a name=\"3\"></a>Creating a Roof",
    "local_header_href": "#a-name3acreating-a-roof",
    "chunk_text": "#### <a name=\"3\"></a>Creating a Roof\n\nThis question was asked last week both on\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api/help-creating-roof/m-p/5828806)\nand [Stack Overflow](http://stackoverflow.com/questions/32718999/creating-a-roof-function/32732012#32732012):\n\n**Question:**\nI'm having trouble programmatically creating a roof.\nI know how to create a stairs, for example: I start a `StairsEditScope`, use `CreateSketchedLanding` with the right parameters to create my stairs and commit the `StairsEditScope`.\nI can't find a clue on how to create a roof from scratch, though.\nAny leads?\n\n**Answer:**\nPlease always search the Revit API help file RevitAPI.chm and\nthe [Revit online help](http://help.autodesk.com/view/RVT/2016/ENU) before\nasking questions like this.\n\nHere is the sample code provided by the latter, in the section\non [Roofs](http://help.autodesk.com/view/RVT/2016/ENU/?guid=GUID-33E6A6BD-96AA-4FAF-B660-1DD0C06CCD29):\n\n<pre class=\"code\">\n&nbsp; <span class=\"green\">// Before invoking this sample, select some walls </span>\n&nbsp; <span class=\"green\">// to add a roof over. Make sure there is a level </span>\n&nbsp; <span class=\"green\">// named &quot;Roof&quot; in the document.</span>\n&nbsp;\n&nbsp; <span class=\"teal\">Level</span> level\n&nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n&nbsp; &nbsp; &nbsp; .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) )\n&nbsp; &nbsp; &nbsp; .Where&lt;<span class=\"teal\">Element</span>&gt;( e =&gt;\n&nbsp; &nbsp; &nbsp; &nbsp; !<span class=\"blue\">string</span>.IsNullOrEmpty( e.Name )\n&nbsp; &nbsp; &nbsp; &nbsp; &amp;&amp; e.Name.Equals( <span class=\"maroon\">&quot;Roof&quot;</span> ) )\n&nbsp; &nbsp; &nbsp; .FirstOrDefault&lt;<span class=\"teal\">Element</span>&gt;() <span class=\"blue\">as</span> <span class=\"teal\">Level</span>;\n&nbsp;\n&nbsp; <span class=\"teal\">RoofType</span> roofType\n&nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n&nbsp; &nbsp; &nbsp; .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RoofType</span> ) )\n&nbsp; &nbsp; &nbsp; .FirstOrDefault&lt;<span class=\"teal\">Element</span>&gt;() <span class=\"blue\">as</span> <span class=\"teal\">RoofType</span>;\n&nbsp;\n&nbsp; <span class=\"green\">// Get the handle of the application</span>\n&nbsp; <span class=\"teal\">Application</span> application = doc.Application;\n&nbsp;\n&nbsp; <span class=\"green\">// Define the footprint for the roof based on user selection</span>\n&nbsp; <span class=\"teal\">CurveArray</span> footprint = application.Create\n&nbsp; &nbsp; .NewCurveArray();\n&nbsp;\n&nbsp; <span class=\"teal\">UIDocument</span> uidoc = <span class=\"blue\">new</span> <span class=\"teal\">UIDocument</span>( doc );\n&nbsp;\n&nbsp; <span class=\"teal\">ICollection</span>&lt;<span class=\"teal\">ElementId</span>&gt; selectedIds\n&nbsp; &nbsp; = uidoc.Selection.GetElementIds();\n&nbsp;\n&nbsp; <span class=\"blue\">if</span>( selectedIds.Count != 0 )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">ElementId</span> id <span class=\"blue\">in</span> selectedIds )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">Element</span> element = doc.GetElement( id );\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">Wall</span> wall = element <span class=\"blue\">as</span> <span class=\"teal\">Wall</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( wall != <span class=\"blue\">null</span> )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">LocationCurve</span> wallCurve = wall.Location <span class=\"blue\">as</span> <span class=\"teal\">LocationCurve</span>;\n&nbsp; &nbsp; &nbsp; &nbsp; footprint.Append( wallCurve.Curve );\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">ModelCurve</span> modelCurve = element <span class=\"blue\">as</span> <span class=\"teal\">ModelCurve</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( modelCurve != <span class=\"blue\">null</span> )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; footprint.Append( modelCurve.GeometryCurve );\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; }\n&nbsp; }\n&nbsp; <span class=\"blue\">else</span>\n&nbsp; {\n&nbsp; &nbsp; <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">Exception</span>(\n&nbsp; &nbsp; &nbsp; <span class=\"maroon\">&quot;Please select a curve loop, wall loop or &quot;</span>\n&nbsp; &nbsp; &nbsp; + <span class=\"maroon\">&quot;combination of walls and curves to &quot;</span>\n&nbsp; &nbsp; &nbsp; + <span class=\"maroon\">&quot;create a footprint roof.&quot;</span> );\n&nbsp; }\n&nbsp;\n&nbsp; <span class=\"teal\">ModelCurveArray</span> footPrintToModelCurveMapping\n&nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">ModelCurveArray</span>();\n&nbsp;\n&nbsp; <span class=\"teal\">FootPrintRoof</span> footprintRoof\n&nbsp; &nbsp; = doc.Create.NewFootPrintRoof(\n&nbsp; &nbsp; &nbsp; footprint, level, roofType,\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">out</span> footPrintToModelCurveMapping );\n&nbsp;\n&nbsp; <span class=\"teal\">ModelCurveArrayIterator</span> iterator\n&nbsp; &nbsp; = footPrintToModelCurveMapping.ForwardIterator();\n&nbsp;\n&nbsp; iterator.Reset();\n&nbsp; <span class=\"blue\">while</span>( iterator.MoveNext() )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">ModelCurve</span> modelCurve = iterator.Current <span class=\"blue\">as</span> <span class=\"teal\">ModelCurve</span>;\n&nbsp; &nbsp; footprintRoof.set_DefinesSlope( modelCurve, <span class=\"blue\">true</span> );\n&nbsp; &nbsp; footprintRoof.set_SlopeAngle( modelCurve, 0.5 );\n&nbsp; }\n</pre>\n\nTo test it, please make sure you have some walls to hold up the roof and one of your levels is named `Roof`.\n\nI just created a simple four-wall rectangle, selected them and ran the command.\n\nThis code creates a footprint roof.\n\nRevit also provides other kinds.\n\nIt is important to understand the Revit product and the various roof types from an end user point of view before thinking about driving them programmatically.\n\nThe footprint roof created above is defined by a horizontal outline and is created using the `Document.NewFootPrintRoof` method. Such a roof can be flat, or you can specify a slope for each edge of the outline profile.\n\nThe Building Coder [Xtra labs](https://github.com/jeremytammik/AdnRevitApiLabsXtra) provides\nanother working sample in the external\ncommand [Lab2_0_CreateLittleHouse in Labs2.cs](https://github.com/jeremytammik/AdnRevitApiLabsXtra/blob/master/XtraCs/Labs2.cs).\n\n[The Building Coder](http://thebuildingcoder.typepad.com/) also\nprovides these other roof-related posts:\n\n- [RoomsRoofs SDK Sample](http://thebuildingcoder.typepad.com/blog/2008/09/roomsroofs-sdk.html)\n- [Roof Eave Cut](http://thebuildingcoder.typepad.com/blog/2009/08/roof-eave-cut-in-revit-and-aca.html)\n- [Creating an Extrusion Roof](http://thebuildingcoder.typepad.com/blog/2014/09/events-again-and-creating-an-extrusion-roof.html)\n\n<center>\n<img src=\"img/little_house_roof.png\" alt=\"Little house roof\" width=\"220\"/>\n</center>"
  },
  {
    "original_filename": "1362_answer_day_create_roof",
    "header_text": "<a name=\"4\"></a>Addendum &ndash; Setting FootPrintRoof Slope",
    "local_header_href": "#a-name4aaddendum-ndash-setting-footprintroof-slope",
    "chunk_text": "#### <a name=\"4\"></a>Addendum &ndash; Setting FootPrintRoof Slope\n\nFor Kinjal and Carolina, to answer the Revit discussion forum thread\non [Creating a surface through the Revit API](http://forums.autodesk.com/t5/revit-api/create-a-surface-through-revit-api/m-p/5872832):\n\nHere are all the discussions I found on this, before hitting the [last and hopefully ultimate answer above](#3) that I already forgot I had written:\n\n- [Slope is slope, not radians](http://thebuildingcoder.typepad.com/blog/2010/08/slope-is-slope-not-radians.html)\n- [Modifying floor slope programmatically &ndash; or not](http://thebuildingcoder.typepad.com/blog/2014/03/creating-a-sloped-floor.html#3)\n- [New opening](http://forums.autodesk.com/t5/Revit-API/New-Opening/m-p/5104388)\n- [The discussion with Dodd on creating a sloped floor](http://thebuildingcoder.typepad.com/blog/2014/03/creating-a-sloped-floor.html#comment-2231365409)\n- Internal ADN cases 09714390 *New Opening*, 08886290 *create footprint roof* and 07928659 *Revit 2013如何设置屋顶的坡度*\n\nI hope this helps once and for all and I do not forget about this answer again."
  }
]