[
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!---\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n#dotnet #csharp\n#fsharp #python\n#grevit\n#responsivedesign #typepad\n#ah8 #augi #dotnet\n#stingray #adsklabs #rendering\n#3dweb #3dviewapi #html5 #threejs #webgl #3d #apis #mobile #vr #ecommerce\n#Markdown #Fusion360 #Fusion360Hackathon\n#javascript\n#RestSharp #restapi\n#mongoosejs #mongodb #nodejs\n#rtceur\n#geometry #3d\n\nRevit API, Jeremy Tammik, akn_include\n\nPickPoint with #WPF and No Threads #revitapi #bim #aec #3dwebcoder #adsk #au2015 #apis #xaml\n\nHere is another contribution from Saied Zarrinmehr, of the BIM-SIM Research Group at the Texas A&amp;M University, on the thread safety of the Selection.PickPoint method in Revit 2014 and 2015, resulting in a sample testing different methods for hiding and unhiding a WPF window. I trust they are interesting and useful for people working with Revit 2016 as well. Before getting to that, Calvin and Hobbes anniversary...\n\n-->"
  },
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "PickPoint with WPF and No Threads Attached",
    "local_header_href": "#pickpoint-with-wpf-and-no-threads-attached",
    "chunk_text": "### PickPoint with WPF and No Threads Attached\n\nHere is another contribution from Saied Zarrinmehr of the BIM-SIM Research Group at\nthe [Texas A&M University](https://www.tamu.edu), on\nthe thread safety of the Selection.PickPoint method in Revit 2014 and 2015, resulting in a sample testing different methods for hiding and unhiding a WPF window.\n\nI trust they are interesting and useful for people working with Revit 2016 as well.\n\nBefore getting to that, I also have to mention that yesterday was a most important anniversary, brought to my attention by Miles Tryon-Petith at the [University of Wisconsin-Madison](http://www.wisc.edu):\n\nThe first publication of [Calvin and Hobbes](https://en.wikipedia.org/wiki/Calvin_and_Hobbes) 30 years ago!\n\n<center>\n<img src=\"img/calvin_hobbes_1985-11-18.jpg\" alt=\"Calvin and Hobbes\">\n</center>\n\nThank you, Miles, for the notice.\n\nLast year, Saied already shared with us how\nto [create topography contours and building masses](http://thebuildingcoder.typepad.com/blog/2014/11/creating-topography-contours-and-building-masses.html).\n\nHere is the new topic:"
  },
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "<a name=\"2\"></a>Question",
    "local_header_href": "#a-name2aquestion",
    "chunk_text": "#### <a name=\"2\"></a>Question\n\nI have developed a library for some spatial analysis tasks (crowd simulation, Isovist calculation, etc.) which works with BIM data in Revit. I wanted my library to have minimum dependency to any external library, including Revit API libraries, to be able to use it for IFC and other data schemes. Therefore, I designed a series of interface and abstract classes in C# for getting data and sometimes for visualization. The main platform for visualization is however a WPF window. I have difficulties with the uidoc.Selection.PickPoint function in Revit API library. Is it thread safe?\n\nMy code snippet for visualization is like this:\n\n<pre class=\"code\">\n  public interface IVisualize\n  {\n    void VisualizeBoundary(UV[] points, double elevation);\n    void VisualizeLine(UVLine line, double elevation);\n    void VisualizePoint(UV pnt, double size, double elevation);\n    void VisualizeLines(ICollection<UVLine> lines, double elevation);\n    UV PickPoint(string message);\n  }\n</pre>\n\nIn the following code the Interface is implemented. The Revit document is passed to this class as a static method of the IExternalCommand Interface (ForceModel.doc).\n\n<pre class=\"code\">\n  public class RevitVisualizer : IVisualize\n  {\n    [STAThread]\n    public void VisualizeBoundary(SpatialAnalysis.Geometry.UV[] points, double elevation)\n    {\n      using (Transaction t = new Transaction(ForceModel.doc, \"Draw Boundary\"))\n      {\n        t.Start();\n        FailureHandlingOptions failOpt = t.GetFailureHandlingOptions();\n        failOpt.SetFailuresPreprocessor(new CurveDrawingWarningSwallower());\n        t.SetFailureHandlingOptions(failOpt);\n        Plane p = ForceModel.doc.Application.Create.NewPlane(XYZ.BasisZ, new XYZ(0, 0, elevation));\n        SketchPlane skp = SketchPlane.Create(ForceModel.doc, p);\n        for (int i = 0; i < points.Length; i++)\n        {\n          try\n          {\n            XYZ p1 = new XYZ(points[i].U, points[i].V, elevation);\n            int j = (i == points.Length - 1) ? 0 : i + 1;\n            XYZ p2 = new XYZ(points[j].U, points[j].V, elevation);\n            Line l = Line.CreateBound(p1, p2);\n            ForceModel.doc.Create.NewModelCurve(l, skp);\n          }\n          catch (Exception e)\n          { MessageBox.Show(e.Message); }\n        }\n        t.Commit();\n      }\n    }\n    [STAThread]\n    public void VisualizeLine(UVLine line, double elevation)\n    {\n      using (Transaction t = new Transaction(ForceModel.doc, \"Draw Barriers\"))\n      {\n        t.Start();\n        FailureHandlingOptions failOpt = t.GetFailureHandlingOptions();\n        failOpt.SetFailuresPreprocessor(new CurveDrawingWarningSwallower());\n        t.SetFailureHandlingOptions(failOpt);\n        Plane p = ForceModel.doc.Application.Create.NewPlane(XYZ.BasisZ, new XYZ(0, 0, elevation));\n        SketchPlane skp = SketchPlane.Create(ForceModel.doc, p);\n        try\n        {\n          XYZ p1 = new XYZ(line.Start.U, line.Start.V, elevation);\n          XYZ p2 = new XYZ(line.End.U, line.End.V, elevation);\n          Line l = Line.CreateBound(p1, p2);\n          ForceModel.doc.Create.NewModelCurve(l, skp);\n        }\n        catch (Exception e)\n        { MessageBox.Show(e.Message); }\n\n        t.Commit();\n      }\n    }\n    [STAThread]\n    public void VisualizePoint(SpatialAnalysis.Geometry.UV pnt, double size, double elevation)\n    {\n      XYZ p1 = new XYZ(pnt.U - size / 2, pnt.V - size / 2, elevation);\n      XYZ p2 = new XYZ(pnt.U + size / 2, pnt.V + size / 2, elevation);\n      XYZ q1 = new XYZ(pnt.U + size / 2, pnt.V - size / 2, elevation);\n      XYZ q2 = new XYZ(pnt.U - size / 2, pnt.V + size / 2, elevation);\n      using (Transaction t = new Transaction(ForceModel.doc, \"Show Point\"))\n      {\n        t.Start();\n        FailureHandlingOptions failOpt = t.GetFailureHandlingOptions();\n        failOpt.SetFailuresPreprocessor(new CurveDrawingWarningSwallower());\n        t.SetFailureHandlingOptions(failOpt);\n        Plane pln = ForceModel.doc.Application.Create.NewPlane(XYZ.BasisZ, new XYZ(0, 0, elevation));\n        SketchPlane skp = SketchPlane.Create(ForceModel.doc, pln);\n        Line l1 = Line.CreateBound(p1, p2);\n        Line l2 = Line.CreateBound(q1, q2);\n        ForceModel.doc.Create.NewModelCurve(l1, skp);\n        ForceModel.doc.Create.NewModelCurve(l2, skp);\n        t.Commit();\n      }\n      p1 = null; p2 = null; q1 = null; q2 = null;\n    }\n    [STAThread]\n    public void VisualizeLines(ICollection<UVLine> lines, double elevation)\n    {\n      using (Transaction t = new Transaction(ForceModel.doc, \"Draw lines\"))\n      {\n        t.Start();\n        FailureHandlingOptions failOpt = t.GetFailureHandlingOptions();\n        failOpt.SetFailuresPreprocessor(new CurveDrawingWarningSwallower());\n        t.SetFailureHandlingOptions(failOpt);\n        Plane p = ForceModel.doc.Application.Create.NewPlane(XYZ.BasisZ, new XYZ(0, 0, elevation));\n        SketchPlane skp = SketchPlane.Create(ForceModel.doc, p);\n        foreach (UVLine item in lines)\n        {\n          try\n          {\n            XYZ p1 = new XYZ(item.Start.U, item.Start.V, elevation);\n            XYZ p2 = new XYZ(item.End.U, item.End.V, elevation);\n            Line l = Line.CreateBound(p1, p2);\n            ForceModel.doc.Create.NewModelCurve(l, skp);\n          }\n          catch (Exception e)\n          { MessageBox.Show(e.Message); }\n        }\n        t.Commit();\n      }\n    }\n    [STAThread]\n    public SpatialAnalysis.Geometry.UV PickPoint(string message)\n    {\n      UIDocument uidoc = new Autodesk.Revit.UI.UIDocument(ForceModel.doc);\n      XYZ xyz = uidoc.Selection.PickPoint(message);\n      return new SpatialAnalysis.Geometry.UV(xyz.X, xyz.Y);\n    }\n  }\n</pre>\n\nThe problem that I have is with the PickPoint method. I want to use this function to allow the users to draw the visibility polygons in Revit if they want. It works great for the first time of use. But from the second time of using it, when drawing anything the following exception is raised: \"Starting a transaction from an external application running outside of API context is not allowed\". After that the connection of my app to Revit is lost. My code snippet for drawing an Isovist follows. The MainViewer.TargetVisualizer is a static instance of RevitVisualizer class.\n\n<pre class=\"code\">\n    private void drawinRevit()\n    {\n      // hide the window\n      this._host.Hide();\n      // pick a point using the Interface\n      UV p = MainViewer.TargetVisualizer.PickPoint(\"Pick a vantage point to draw polygonal Isovist\");\n      //show the form again\n      this._host.Show();\n      try\n      {\n        HashSet<UVLine> blocks = this._host.cellularFloor.VisualBlocks(p, this._host.isoDepth);\n        //calculate the isovist polygon\n        Barrier isovistPolygon = this._host.barrierEnvironment.IsovistPolygon(p, this._host.isoDepth, blocks);\n        //visualize it\n        isovistPolygon.Visualize(MainViewer.TargetVisualizer, this._host.barrierEnvironment.Elevation);\n      }\n      catch (Exception error0)\n      {\n        MessageBox.Show(error0.Message);\n      }\n    }\n</pre>\n\nHere is the Barrier class:\n\n<pre class=\"code\">\n  public class Barrier\n  {\n    public UV[] BoundaryPoints { get; set; }\n    public bool AscendingOrder { get; set; }\n    public bool IsHole { get; set; }\n    public int Length\n    {\n      get { return this.BoundaryPoints.Length; }\n    }\n    public bool IsHole { get; set; }\n    public Barrier(UV[] points)\n    {\n      this.AscendingOrder = true;\n      this.BoundaryPoints = points;\n    }\n    public void Visualize(IVisualize visualizer, double evevation)\n    {\n      visualizer.VisualizeBoundary(this.BoundaryPoints, evevation);\n    }\n    public static void VisualizeBarriers(IVisualize visualizer, Barrier[] barriers, double height = 0)\n    {\n      foreach (Barrier item in barriers)\n      {\n        visualizer.VisualizeBoundary(item.BoundaryPoints, height);\n      }\n    }\n  }\n</pre>\n\nI have no problem with any other interface or abstract classes that use Revit API. It is only after using the uidoc.Selection.PickPoint when the problem starts. What is the reason for it? How can I fix it?"
  },
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "<a name=\"3\"></a>Answer",
    "local_header_href": "#a-name3aanswer",
    "chunk_text": "#### <a name=\"3\"></a>Answer\n\nThank you for your very clear and interesting description.\n\nI like your approach very much, including the dependency minimisation.\n\nI have recently heard of other issues with PickObject, so it seems to be a stumbling point.\n\nI cannot say off-hand what the problem is.\n\nI can say off-hand that the Revit API is absolutely never thread safe:\n\n- [No multithreading in Revit](http://thebuildingcoder.typepad.com/blog/2011/06/no-multithreading-in-revit.html)\n- [The Revit API is never ever thread safe](http://thebuildingcoder.typepad.com/blog/2014/11/the-revit-api-is-never-ever-thread-safe.html)\n\nCan you reconsider your approach under this assumption?\n\nHave you read and understood the approach you need to take to drive Revit from outside?\n\nDo you understand that the Revit API can never be used except in a valid Revit API context, and such a context is exclusively provided within event handler callback functions that you notify Revit about and that it then calls back?\n\nThis is extensively documented by The Building Coder topic group on [Idling and External Events for Modeless Access and Driving Revit from Outside](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.28).\n\nThe best way to drive Revit from outside is via external events.\n\nA good sample on how to architecture an add-in to use them is the ModelessDialog &gt; ModelessForm_ExternalEvent Revit SDK sample.\n\nOnce you can confirm understanding and implementing all the above, if the problem persists, I will pass on your query to the development team.\n\nRe-reading your description, though, it seems that you are trying to drive Revit directly from outside.\n\nSorry, no go.\n\nUnfortunately, this also means that your abstract interface class may become more complex.\n\nI hope you can find a really simple solution for that too.\n\nI really look forward to seeing this solved and hope that you will be willing and happy to share that in public.\n\nActually, I am planning an extensive blog post on the recent other problems that people encountered using pick point and trying to access the Revit API in illegal ways, so this question of yours and my answer may fit in quite well there as well just as they stand."
  },
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "<a name=\"4\"></a>Response",
    "local_header_href": "#a-name4aresponse",
    "chunk_text": "#### <a name=\"4\"></a>Response\n\nThanks for taking your time and extensively elaborating the subject. Well I learned Revit's lack of support for multi-threading in the hard way!\n\nI tried using the modeless method described in ModelessDialog &gt; ModelessForm_ExternalEvent SDK samples. It works, but from what I read this does not seem like a stable way of connecting to Revit and poses unknown challenges. For the moment I'd rather go with providing implementation for IExternalCommand interface, which is legal and straight forward.  By the way, illegal connection to Revit is not an unlawful action, is it!?\n\nAttached is a [simple project](zip/sz_PickPointTest_1.zip) that you can run to see the problems that uidoc.Selection.PickPoint causes. In this simplified project if you click on the red button the API uidoc.Selection.PickPoint method will be called. And if you click on the green button the WPF mouse click event will be triggered to pick a point.  In both cases a fake isovist is produced and visualized both in WPF and Revit. When points are picked from WPF no exception is raised. When using the Revit API Pick point method for the first time, you will not encounter any exception. However, after that you will receive exceptions for any kind of drawing in Revit. It occurs to me that the  uidoc.Selection.PickPoint forces the app out of the main thread which is provided by IExternalCommand interface. You should be able to reproduce the problem now with the attached project.\n\nI used an empty Architectural Template Revit Project for testing the code."
  },
  {
    "original_filename": "1377_wpf_thread_pickpoint",
    "header_text": "<a name=\"5\"></a>WPF Window Hiding",
    "local_header_href": "#a-name5awpf-window-hiding",
    "chunk_text": "#### <a name=\"5\"></a>WPF Window Hiding\n\nI have solved the problem. I tested different methods for hiding and unhiding the WPF window, which includes\n\n- For Hiding: `this.Visibility = System.Windows.Visibility.Hidden` and for unhiding: `this.Visibility = System.Windows.Visibility.Visible`\n- For Hiding: `this.Hide()` and for unhiding: `this.Show()`\n- For Hiding: `this.Hide()` and for unhiding: `this.ShowDialog()`\n\nThe thread Id of the WPF window will not change in any of the cases after using the API PickPoint method. The [attached project](zip/sz_PickPointTest_2.zip) shows that the third of the above methods works properly. I also found that every line of code after ShowDialog will wait for the WPF window to close to execute. I tested two different locations for unhiding the window. They are inside first and second code region alternatives. You may want to check lines 51 to 93 in the attached project, change it and see it for yourself.\n\nI still do not completely understand what's happening and I appreciate your explanation. However, the good news is that the problem is solved.\n\nMany thanks to Saied for sharing this research and solution!\n\nOh and regarding your question on \"illegal connection to Revit is not an unlawful action, is it?\" &ndash; nope, it will just hurt you and your customers if you crash Revit and corrupt the model. Nothing worse than that, though &nbsp; :-)\n\nMaybe others can chip in and help with further explanations?\n\nThank you!"
  }
]