[
  {
    "original_filename": "1409_filter_section_view",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!---\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n- http://forums.autodesk.com/t5/revit-api/boundingboxintersectsfilter-not-working/td-p/5912235\n\n- Basic access to Revit API and SDK, what is what? -- http://forums.autodesk.com/t5/revit-api/revit-api-online/m-p/6061199\n\n\n#dotnet #csharp\n#fsharp #python\n#grevit\n#responsivedesign #typepad\n#ah8 #augi #dotnet\n#stingray #rendering\n#3dweb #3dviewAPI #html5 #threejs #webgl #3d #mobile #vr #ecommerce\n#Markdown #Fusion360 #Fusion360Hackathon\n#javascript\n#RestSharp #restAPI\n#mongoosejs #mongodb #nodejs\n#rtceur\n#xaml\n#3dweb #a360 #3dwebaccel #webgl @adskForge\n@AutodeskReCap @Adsk3dsMax\n#revitAPI #bim #aec #3dwebcoder #adsk #adskdevnetwrk @jimquanci @keanw\n#au2015 #rtceur\n#eraofconnection\n#RMS @researchdigisus\n@adskForge #3dwebaccel\n#a360\n @github\n\nRevit API, Jeremy Tammik, akn_include\n\nAPI, SDK and View Section Box Element Intersection #revitAPI #3dwebcoder @AutodeskRevit #bim #aec #adsk #adskdevnetwrk\n\nTrying to keep track of the overwhelming information flow provided by the numerous discussions on\nthe Revit API discussion forum is impossible.\nHere are two little titbits from the past few days\n&ndash; Basic Revit API and SDK Access, Online and Offline\n&ndash; Filtering for Elements Intersecting a View Section Box...\n\n-->"
  },
  {
    "original_filename": "1409_filter_section_view",
    "header_text": "API, SDK and View Section Box Element Intersection",
    "local_header_href": "#api-sdk-and-view-section-box-element-intersection",
    "chunk_text": "### API, SDK and View Section Box Element Intersection\n\nTrying to keep track of the overwhelming information flow provided by the numerous discussions on\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api/bd-p/160) is impossible.\n\nHere are two little titbits from the past few days:\n\n- [Basic Revit API and SDK Access, Online and Offline](#2)\n- [Filtering for Elements Intersecting a View Section Box](#3)"
  },
  {
    "original_filename": "1409_filter_section_view",
    "header_text": "<a name=\"2\"></a>Basic Revit API and SDK Access, Online and Offline",
    "local_header_href": "#a-name2abasic-revit-api-and-sdk-access-online-and-offline",
    "chunk_text": "#### <a name=\"2\"></a>Basic Revit API and SDK Access, Online and Offline\n\nHere is a very basic question, raised by Miguel Rus in the Revit API discussion forum thread\non [Revit API online](http://forums.autodesk.com/t5/revit-api/revit-api-online/m-p/6061199) that\nI reproduce here for the sake of clarity and future reference.\n\nIt belongs to the category of things to read and understand even before getting started &nbsp; :-)\n\n**Question:** I am trying to find an the online API for Revit 2016 but I can't seem to finds it.\nCould someone point me in the right direction.\nThe offline CHM is not of any help as the firewall at my office is blocking the connection to the Internet.\n\n**Answer:** The Revit API, the application developer interface, is always included with Revit itself.\n\nAs far as I know, the end user product cannot run without the API installed. The API is provided by certain .NET assemblies located in the same folder as Revit.exe itself, such as `RevitAPI.dll` and `RevitAPIUI.dll`.\n\nI guess what you mean is the Revit SDK, the software developers kit.\n\nIt contains important and helpful API documentation and samples, such as the Revit API help file `RevitAPI.chm` that you refer to.\n\nThe SDK is installed by running an executable file, `RevitSDK.exe`.\n\nYou can install the SDK from various places. It is included under 'Tools' in the standard Revit product installation.\n\nIt is also available from the main entry point for information on and getting started with the Revit API,\nthe [Revit Developer Centre](http://www.autodesk.com/developrevit).\n\nThe Building Coder provides more hints\non [getting started with the Revit API](http://thebuildingcoder.typepad.com/blog/about-the-author.html#2).\n\nIf you are asking specifically about <u>Revit API help online</u>, then The Building Coder discussion\nabout [Revit API help online](http://thebuildingcoder.typepad.com/blog/2014/01/revit-api-help-online-and-hiking-on-la-palma.html) might\npossibly help.\n\n:-)\n\nUnfortunately, the version pointed to there is for Revit 2014 and has not been updated: [www.revitapisearch.com](http://www.revitapisearch.com).\n\nI would recommend simply using the CHM provided by the SDK; you can rely on that, always, store it locally, always keep it at hand, whether online or off..."
  },
  {
    "original_filename": "1409_filter_section_view",
    "header_text": "<a name=\"3\"></a>Filtering for Elements Intersecting a View Section Box",
    "local_header_href": "#a-name3afiltering-for-elements-intersecting-a-view-section-box",
    "chunk_text": "#### <a name=\"3\"></a>Filtering for Elements Intersecting a View Section Box\n\nHere is a useful and important piece of information on determining all elements intersecting a view's section box, shared by Jan Tepelmann\nat [Inreal Technologies](https://www.inreal-tech.com) in the Revit API discussion forum thread\non [BoundingBoxIntersectsFilter not working](http://forums.autodesk.com/t5/revit-api/boundingboxintersectsfilter-not-working/td-p/5912235):\n\n**Question:** I'm a programmer at Inreal Technologies and were developing Enscape 3D, a rendering plugin for Revit.\n\nCurrently we are working on speeding up the switching between two 3D views. Right now we just recreate the scene to render but this is obviously very slow.\n\nSo I came up with the following code to find out which elements were added, removed and modified when you switch from one view (the start view) to another view (the target view). The idea behind the code is, that we want to know all elements which got cut by the start view's section box or will get cut by the target view section box. For those elements the geometry has to be updated:\n\n<pre class=\"code\">\n&nbsp; <span class=\"blue\">public</span> <span class=\"blue\">static</span> DiffUpdateElementIds Calculate(\n&nbsp; &nbsp; <span class=\"teal\">View3D</span> startView, <span class=\"teal\">View3D</span> targetView )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"blue\">var</span> diffElements = <span class=\"blue\">new</span> DiffUpdateElementIds();\n&nbsp;\n&nbsp; &nbsp; <span class=\"green\">//... here added and removed elements are calculated </span>\n&nbsp; &nbsp; <span class=\"green\">// (with exclude filter). This works just fine </span>\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">if</span>( startView.IsSectionBoxActive\n&nbsp; &nbsp; &nbsp; || targetView.IsSectionBoxActive )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">ElementFilter</span> intersectFilterStart = <span class=\"blue\">null</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">ElementFilter</span> intersectFilterTarget = <span class=\"blue\">null</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( startView.IsSectionBoxActive )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; Logger.info( <span class=\"maroon\">&quot;start View has SectionBox&quot;</span> );\n&nbsp; &nbsp; &nbsp; &nbsp; intersectFilterStart\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">BoundingBoxIntersectsFilter</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">new</span> <span class=\"teal\">Outline</span>( startView.GetSectionBox().Min,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; startView.GetSectionBox().Max ) );\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( targetView.IsSectionBoxActive )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; Logger.info( <span class=\"maroon\">&quot;target View has SectionBox&quot;</span> );\n&nbsp; &nbsp; &nbsp; &nbsp; intersectFilterTarget\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">BoundingBoxIntersectsFilter</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">new</span> <span class=\"teal\">Outline</span>( targetView.GetSectionBox().Min,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; targetView.GetSectionBox().Max ) );\n&nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">ElementFilter</span> intersectFilter;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( intersectFilterStart != <span class=\"blue\">null</span>\n&nbsp; &nbsp; &nbsp; &nbsp; &amp;&amp; intersectFilterTarget == <span class=\"blue\">null</span> )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; intersectFilter = intersectFilterStart;\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">else</span> <span class=\"blue\">if</span>( intersectFilterStart == <span class=\"blue\">null</span>\n&nbsp; &nbsp; &nbsp; &nbsp; &amp;&amp; intersectFilterTarget != <span class=\"blue\">null</span> )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; intersectFilter = intersectFilterTarget;\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">else</span>\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; intersectFilter = <span class=\"blue\">new</span> <span class=\"teal\">LogicalOrFilter</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; intersectFilterStart, intersectFilterTarget );\n&nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">var</span> cutElementsStartView\n&nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; startView.Document, startView.Id )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .WherePasses( intersectFilter );\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">var</span> cutElementsTargetView\n&nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; targetView.Document, targetView.Id )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .WherePasses( intersectFilter );\n&nbsp;\n&nbsp; &nbsp; &nbsp; diffElements.ModifiedElements\n&nbsp; &nbsp; &nbsp; &nbsp; = cutElementsStartView.UnionWith(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cutElementsTargetView ).ToElementIds();\n&nbsp; &nbsp; }\n&nbsp; &nbsp; <span class=\"blue\">return</span> diffElements;\n&nbsp; }\n</pre>\n\nThe problem now is that it misses a ceiling in the Advanced Sample Project when I switch from the default 3D view to \"03 - Floor Public - Day Rendering\" view, cf. this screen snapshot:\n\n<center>\n<img src=\"img/ceiling_not_cut.png\" alt=\"Ceiling not cut\" width=\"600\">\n</center>\n\nWhat am I missing? I have to say that I'm relatively new to the filtering API so any help is appreciated.\n\n**Answer:** I could solve the problem now by myself.\n\nMaybe itâ€™s useful for someone else who has the same problem:\n\n<pre class=\"code\">\n&nbsp; <span class=\"blue\">if</span>( startView.IsSectionBoxActive )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">Transform</span> t = startView.GetSectionBox().Transform;\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Outline</span> o = <span class=\"blue\">new</span> <span class=\"teal\">Outline</span>(\n&nbsp; &nbsp; &nbsp; t.OfPoint( startView.GetSectionBox().Min ),\n&nbsp; &nbsp; &nbsp; t.OfPoint( startView.GetSectionBox().Max ) );\n&nbsp;\n&nbsp; &nbsp; intersectFilterStart\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">BoundingBoxIntersectsFilter</span>( o );\n&nbsp; }\n&nbsp; <span class=\"blue\">if</span>( targetView.IsSectionBoxActive )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">Transform</span> t = targetView.GetSectionBox().Transform;\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Outline</span> o = <span class=\"blue\">new</span> <span class=\"teal\">Outline</span>(\n&nbsp; &nbsp; &nbsp; t.OfPoint( targetView.GetSectionBox().Min ),\n&nbsp; &nbsp; &nbsp; t.OfPoint( targetView.GetSectionBox().Max ) );\n&nbsp;\n&nbsp; &nbsp; intersectFilterTarget\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">BoundingBoxIntersectsFilter</span>( o );\n&nbsp; }\n</pre>\n\nThe code I was missing is to apply the view section box transform. I was just missing that the section box can have a transformation. I thought the box is always defined in world space, but that's not true. Sometimes it is not and then the old code did not work. So hopefully this helps someone who has the same issue.\n\nNow everything is working and the switch between two 3D views is <b><i>much</i></b> faster then before.\n\nGreat! &nbsp; :-)\n\nMany thanks to Jan for sharing this!"
  }
]