[
  {
    "original_filename": "1444_filter_view_bb",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<title>The Building Coder</title>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!--\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\nFiltering for View Specific Elements #revitAPI #3dwebcoder @AutodeskForge #adsk #aec #bim #socket.io\n\nWhile preparing for the Forge DevCon in SF and the Athens Forge meetup and web server workshop at The Cube Athens, I also happened to hear about the solution to the question raised by Chema in the Revit API discussion forum thread on deleting an area in a drafting view &ndash; I need to delete some elements (detail items) in a given area of my drafting view...\n\n-->"
  },
  {
    "original_filename": "1444_filter_view_bb",
    "header_text": "Filtering for View Specific Elements",
    "local_header_href": "#filtering-for-view-specific-elements",
    "chunk_text": "### Filtering for View Specific Elements\n\nWhile preparing for \nthe [Forge DevCon](http://forge.autodesk.com/conference) in SF and \nthe [Athens Forge meetup](http://www.meetup.com/de-DE/I-love-3D-Athens/events/230543759) and\n[web server workshop](http://www.meetup.com/de-DE/I-love-3D-Athens/events/230544059) \nat [The Cube Athens](http://thecube.gr), \nI also happened to hear about the solution to the question raised by Chema in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api/bd-p/160) thread\non [deleting an area in a drafting view](http://forums.autodesk.com/t5/revit-api/delete-an-area-in-a-drafting-view/td-p/6342882):\n\n**Question:** I am working on a tool that creates schematics. I need to delete some elements (detail items) in a given area of my drafting view:\n\n<center>\n <img src=\"img/filter_detail_item.png\" alt=\"Filter detail item\" width=\"433\">\n</center>\n\nIn the above example I need to remove the lower detail item and keep the other two. I am trying to use the `ElementOwnerViewFilter` combined with the `BoundingBoxIntersectsFilter` as shown below.\n\n<pre class=\"code\">\n<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;CleardBArea(\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc,\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;vId,\n&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;dBPos,\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;width,\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;height&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;min&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;0,&nbsp;(&nbsp;height&nbsp;/&nbsp;4&nbsp;)&nbsp;*&nbsp;dBPos,&nbsp;0&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;max&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;width,&nbsp;(&nbsp;height&nbsp;/&nbsp;4&nbsp;)&nbsp;*&nbsp;(&nbsp;dBPos&nbsp;+&nbsp;1&nbsp;),&nbsp;0&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Outline</span>&nbsp;outline&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Outline</span>(&nbsp;min,&nbsp;max&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxIntersectsFilter</span>&nbsp;bbF\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxIntersectsFilter</span>(&nbsp;outline&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementOwnerViewFilter</span>&nbsp;eOVF\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ElementOwnerViewFilter</span>(&nbsp;vId&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;vColl\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WherePasses(&nbsp;eOVF&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WherePasses(&nbsp;bbF&nbsp;);\n \n&nbsp;&nbsp;ClearElements(&nbsp;vColl&nbsp;);\n}\n</pre>\n\nIt works fine if I try to delete model lines, but unfortunately, when I try to delete detail items, the filter ignores it.\n\nCould you please recommend any other way to develop it?\n\nI attached a zip file [filter_detail_item.zip](zip/filter_detail_item.zip) with the minimal information to reproduce my problem: a Revit 2015 project file containing a macro that should remove half of the drafting view. It works with all elements excepts the family instances.\n\n\nAnswer: The `BoundingBoxIntersectsFilter` is intended for use with a model geometry bounding box. \n\nA detail item only has a view specific geometry bounding box, so it fails to filter them. \n\nThe workaround is to retrieve the view specific bounding box and use `Outline.Intersects` to perform the equivalent check, e.g., like this:\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">var</span>&nbsp;b1&nbsp;=&nbsp;detailItem.get_BoundingBox(&nbsp;<span style=\"color:blue;\">this</span>.ActiveView&nbsp;);\n  <span style=\"color:#2b91af;\">XYZ</span>&nbsp;min&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>();\n  <span style=\"color:#2b91af;\">XYZ</span>&nbsp;max&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;1.969,&nbsp;0.656,&nbsp;0&nbsp;);\n  <span style=\"color:blue;\">var</span>&nbsp;outline&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Outline</span>(&nbsp;min,&nbsp;max&nbsp;);\n  <span style=\"color:blue;\">var</span>&nbsp;outlineOfDetailItem&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Outline</span>(&nbsp;b1.Min,&nbsp;b1.Max&nbsp;);\n  outline.Intersects(&nbsp;outlineOfDetailItem,&nbsp;0.00001&nbsp;);\n</pre>"
  }
]