[
  {
    "original_filename": "1446_point_bc_2017_sdk",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<title>The Building Coder</title>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"3dwc.css\"/>\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst&amp;lang=css\" defer=\"defer\"></script>\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst\" defer=\"defer\"></script>\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\"></script>\n</head>\n\n<!---\n\nPoint Boundary Condition and Revit 2017 SDK @AutodeskForge @CubeAthens #3dwebcoder #revitapi\n\nI arrived safe and sound in San Francisco via Vancouver and am now working on the final preparations for the Forge DevCon and 3D Web Fest.\nBefore getting to that, here are some quick notes from my short exploration last week to produce a rather overdue list of the new Revit 2017 SDK samples and on creating a point boundary condition on a structural column\n&ndash; New Revit 2017 SDK Samples\n&ndash; Creating Point Boundary Condition on End of Structural Column...\n\n-->"
  },
  {
    "original_filename": "1446_point_bc_2017_sdk",
    "header_text": "Point Boundary Condition and Revit 2017 SDK",
    "local_header_href": "#point-boundary-condition-and-revit-2017-sdk",
    "chunk_text": "### Point Boundary Condition and Revit 2017 SDK\n\nI arrived safe and sound in San Francisco via Vancouver and am now working on the final preparations for \nthe [Forge DevCon](http://forge.autodesk.com/conference) \nand [3D Web Fest](http://www.3dwebfest.com).\n\n<center>\n  <img src=\"/p/2016/2016-06-13_greens/471_golden_gate_and_marina.jpg\" alt=\"Golden Gate Bridge and Marina\" width=\"450\">\n</center>\n\nBefore getting to that, here are some quick notes from my short exploration last week to produce a rather overdue list of the new Revit 2017 SDK samples and on creating a point boundary condition on a structural column:\n\n- [New Revit 2017 SDK Samples](#2)\n- [Creating Point Boundary Condition on End of Structural Column](#3)"
  },
  {
    "original_filename": "1446_point_bc_2017_sdk",
    "header_text": "<a name=\"2\"></a>New Revit 2017 SDK Samples",
    "local_header_href": "#a-name2anew-revit-2017-sdk-samples",
    "chunk_text": "#### <a name=\"2\"></a>New Revit 2017 SDK Samples\n\nI used to pay much more attention in the past to the topic of new samples and Revit API functionality.\n\nObviously, the larger the API grows, the less difference each individual enhancement makes, and the more specialised the modifications become.\n\nI trust you already discovered these samples yourself if they are important to you:\n\n- Samples/CapitalizeAllTextNotes\n- Samples/GenericStructuralConnection\n- Samples/GeometryAPI/BRepBuilderExample\n- Samples/PlacementOptions\n- Structural Analysis SDK/Examples/CodeCheckingConcreteExample and CalculationPointsSelector\n\nHere is the procedure I used to produce that list:\n\n<pre>\n/a/lib/revit/2016/SDK $ find . -type d &gt; /a/lib/revit/jeremy/ls2016.txt\n/a/lib/revit/2016/SDK $ cd ../../2017/SDK/\n/a/lib/revit/2017/SDK $ find . -type d &gt; /a/lib/revit/jeremy/ls2017.txt\n/a/lib/revit/2017/SDK $ cd ../../jeremy/\n/a/lib/revit/jeremy $ diff ls2016.txt ls2017.txt\n123c123\n&lt; ./REX SDK/Visual Studio templates/Items/Autodesk/Revit Extensions 2016\n---\n&gt; ./REX SDK/Visual Studio templates/Items/Autodesk/Revit Extensions 2017\n126c126\n&lt; ./REX SDK/Visual Studio templates/Projects/Autodesk/Revit Extensions 2016\n---\n&gt; ./REX SDK/Visual Studio templates/Projects/Autodesk/Revit Extensions 2017\n170a171,173\n&gt; ./Samples/CapitalizeAllTextNotes\n&gt; ./Samples/CapitalizeAllTextNotes/CS\n&gt; ./Samples/CapitalizeAllTextNotes/CS/Properties\n384a388,390\n&gt; ./Samples/GenericStructuralConnection\n&gt; ./Samples/GenericStructuralConnection/CS\n&gt; ./Samples/GenericStructuralConnection/CS/Properties\n385a392,395\n&gt; ./Samples/GeometryAPI/BRepBuilderExample\n&gt; ./Samples/GeometryAPI/BRepBuilderExample/CS\n&gt; ./Samples/GeometryAPI/BRepBuilderExample/CS/Properties\n&gt; ./Samples/GeometryAPI/BRepBuilderExample/CS/Resources\n531a542,544\n&gt; ./Samples/PlacementOptions\n&gt; ./Samples/PlacementOptions/CS\n&gt; ./Samples/PlacementOptions/CS/Properties\n695a709,710\n&gt; ./Structural Analysis SDK/Examples/ASCE-7-10/bin\n&gt; ./Structural Analysis SDK/Examples/ASCE-7-10/bin/Release\n702a718,719\n&gt; ./Structural Analysis SDK/Examples/Concrete/CodeCheckingConcreteExample/bin\n&gt; ./Structural Analysis SDK/Examples/Concrete/CodeCheckingConcreteExample/bin/Release\n709a727\n&gt; ./Structural Analysis SDK/Examples/Concrete/CodeCheckingConcreteExample/UIComponents/CalculationPointsSelector\n714a733,734\n&gt; ./Structural Analysis SDK/Examples/Concrete/ConcreteCalculationsExample/bin\n&gt; ./Structural Analysis SDK/Examples/Concrete/ConcreteCalculationsExample/bin/Release\n716a737,738\n&gt; ./Structural Analysis SDK/Examples/ExtensibleStorageDocumentation/bin\n&gt; ./Structural Analysis SDK/Examples/ExtensibleStorageDocumentation/bin/Release\n719a742,743\n&gt; ./Structural Analysis SDK/Examples/ExtensibleStorageUI/bin\n&gt; ./Structural Analysis SDK/Examples/ExtensibleStorageUI/bin/Release\n723a748,749\n&gt; ./Structural Analysis SDK/Examples/ResultsInRevit/QueryingResults/bin\n&gt; ./Structural Analysis SDK/Examples/ResultsInRevit/QueryingResults/bin/Release\n725a752,753\n&gt; ./Structural Analysis SDK/Examples/ResultsInRevit/StoringResults/bin\n&gt; ./Structural Analysis SDK/Examples/ResultsInRevit/StoringResults/bin/Release\n727a756,757\n&gt; ./Structural Analysis SDK/Examples/SectionPropertiesExplorer/bin\n&gt; ./Structural Analysis SDK/Examples/SectionPropertiesExplorer/bin/Release\n</pre>"
  },
  {
    "original_filename": "1446_point_bc_2017_sdk",
    "header_text": "<a name=\"3\"></a>Creating Point Boundary Condition on End of Structural Column",
    "local_header_href": "#a-name3acreating-point-boundary-condition-on-end-of-structural-column",
    "chunk_text": "#### <a name=\"3\"></a>Creating Point Boundary Condition on End of Structural Column\n\n**Question:** I am trying to create a fixed boundary conditions at the beginning of a column following the example code in the Revit API help file RevitAPI.chm, but the endpoint reference of the `Curve` associated to the column analytical model keeps returning a null value.\n\nAm I missing something?\n\n**Answer:** Creating a boundary condition on end of column should work correctly.\n\nHere is a code snippet from one of the Revit automatic regression tests.\n\nIt creates a point boundary condition on the ends of each analytical column:\n\n<pre class=\"code\">\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;Create&nbsp;a&nbsp;point&nbsp;load&nbsp;on&nbsp;all&nbsp;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;analytical&nbsp;column&nbsp;end&nbsp;points.&nbsp;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:blue;\">void</span>&nbsp;CreatePointLoadOnColumnEnd(&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Find&nbsp;all&nbsp;AM&nbsp;column&nbsp;instances&nbsp;in&nbsp;the&nbsp;document</span>\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;columns\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfCategory(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_ColumnAnalytical&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">AnalyticalModel</span>&nbsp;am&nbsp;<span style=\"color:blue;\">in</span>&nbsp;columns&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;curve&nbsp;=&nbsp;am.GetCurve();\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AnalyticalModelSelector</span>&nbsp;selector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">AnalyticalModelSelector</span>(&nbsp;curve&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;selector.CurveSelector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:#2b91af;\">AnalyticalCurveSelector</span>.EndPoint;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Reference</span>&nbsp;endPointRef&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;am.GetReference(&nbsp;selector&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;NewPointBoundaryConditions&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundaryConditions</span>&nbsp;newPointBC&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;doc.Create.NewPointBoundaryConditions(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;endPointRef,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Fixed,&nbsp;0,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Spring,&nbsp;1.0,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Fixed,&nbsp;0,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Fixed,&nbsp;0,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Fixed,&nbsp;0,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TranslationRotationValue</span>.Fixed,&nbsp;0&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;newPointBC.SetOrientTo(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundaryConditionsOrientTo</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.HostLocalCoordinateSystem&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n}\n</pre>\n\nYou can run this code in the Revit Macro Manager to verify.\n\nI added it \nto [The Building Coder Samples](https://github.com/jeremytammik/the_building_coder_samples) \n[release 2017.0.127.5](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2017.0.127.5)\nin the module \n[CmdNewLineLoad.cs](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdNewLineLoad.cs#L30-L77)."
  }
]