[
  {
    "original_filename": "1525_move_section_view",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!--\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n- 12600423 [Move Location of Section View]\n  http://forums.autodesk.com/t5/revit-api-forum/move-location-of-section-view/m-p/6831743\n\n#RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge\n\nToday, let's recap the Revit API discussion forum thread on moving the location of a section vie raised by Danny Bentley, BIM Structural Technician at SOM in California, since Danny very kindly created a video and GitHub repo to demonstrate and share the solution, which will certainly be of use to others as well. By the way, Danny also writes Bentley's Revit Dynamo &amp API blog on his personal exploration of the Revit API and Dynamo...\n\n&ndash; \n...\n\n-->"
  },
  {
    "original_filename": "1525_move_section_view",
    "header_text": "Moving the Section View Location",
    "local_header_href": "#moving-the-section-view-location",
    "chunk_text": "### Moving the Section View Location\n\nToday, let's recap \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [moving the location of a section view](http://forums.autodesk.com/t5/revit-api-forum/move-location-of-section-view/m-p/6831743) raised\nby [Danny Bentley](http://forums.autodesk.com/t5/user/viewprofilepage/user-id/2615791),\nBIM Structural Technician at [SOM](http://www.som.com) in California, since Danny very kindly created a video and GitHub repo to demonstrate and share the solution, which will certainly be of use to others as well.\n\n<center>\n<img src=\"img/danny_bentley_x120.jpg\" alt=\"Danny Bentley\" width=\"120\"/>\n</center>\n\nBy the way, Danny also\nwrites [Bentley's Revit Dynamo &amp; API blog](http://revitdynamoapi.blogspot.ch/) on\nhis personal exploration of the Revit API and Dynamo.\n\nWhy does it have a `ch` domain, Danny?\n\nAnyway, here is the issue moving the location of a section view:\n\n**Question:** I saw a great post on the *The Building Coder* on how\nto [create a section view to be aligned with a wall](http://thebuildingcoder.typepad.com/blog/2012/06/create-section-view-parallel-to-wall.html).\n\nI'm working on a project in which the wall angle will change and I need to rotate an existing section to match it.  \n \nIs it possible to set a curve similar to a wall?  I can't seem to find any curve or location point on the section view in RevitLookup.\n\n<pre class=\"code\">\n  <span style=\"color:#2b91af;\">LocationCurve</span>&nbsp;locationCurve&nbsp;=&nbsp;wall.WallCurve;\n   \n  <span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;);\n  t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Move&nbsp;Wall&quot;</span>&nbsp;);\n  locationCurve.Curve&nbsp;=&nbsp;LinkedProfile;\n  t.Commit();\n</pre>\n\n**Answer:** Thank you for your query and appreciation.\n \nFirst of all, out of habit, I repeat:\n \nFor your own comfort and security,\n[all use of transactions should be encapsulated in a `using` statement](http://thebuildingcoder.typepad.com/blog/2012/04/using-using-automagically-disposes-and-rolls-back.html).\n\nThe Building Coder defines an entire topic group\non [handling transactions and transaction groups](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.53).\n \nI think you can indeed change the wall location curve in a manner similar to what you show.\n \nHowever, the code you list above is guaranteed not to work.\n\n<u>Beginning of misunderstanding</u>\n\nLook:\n \nIn this line, you make a copy of the wall location curve:\n  \n<pre class=\"code\">\n  <span style=\"color:#2b91af;\">LocationCurve</span>&nbsp;locationCurve&nbsp;=&nbsp;wall.WallCurve;\n</pre>\n  \nThen, you change something in the copy:\n  \n<pre class=\"code\">\n  locationCurve.Curve = LinkedProfile;\n</pre>\n\nAnd then you expect the wall to change?\n \nGood luck with that.\n \nYou might have better luck with\n \n<pre class=\"code\">\n  wall.WallCurve = LinkedProfile;\n</pre>\n\nYou might also want to take a look at\nthe [ADN Xtra labs](https://github.com/jeremytammik/AdnRevitApiLabsXtra) sample\ncommand [Lab2_5_SelectAndMoveWallAndAddColumns](https://github.com/jeremytammik/AdnRevitApiLabsXtra/blob/master/XtraCs/Labs2.cs#L837-L1102).\n \nIt moves a wall using \n \n<pre class=\"code\">\n  wall.Location.Move( v )\n</pre>\n\nby a given vector v.\n\n<u>End of misunderstanding</u>\n\nOh, no, re-reading your query, I see you are trying to modify the section view, not the wall location line.\n \nNo, the section view does not have a location line.\n \nIt is controlled differently. The Revit SDK sample DynamicModelUpdate shows how to dynamically update a section view to follow a window placed in the model. You can adapt that to follow a wall in a similar fashion.\n \nHere is a quick rundown of the places to look in that sample step by step:\n \n- Folder `2017.1/SDK/Samples/DynamicModelUpdate/CS`\n- Module `SectionUpdater.cs`\n- Method `public void Execute(UpdaterData data)`\n- Variables and method call:\n\n<pre class=\"code\">\n<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;window&nbsp;=&nbsp;doc.GetElement(&nbsp;m_windowId&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>;\n\n<span style=\"color:#2b91af;\">ViewSection</span>&nbsp;section&nbsp;=&nbsp;doc.GetElement(&nbsp;m_sectionId&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>;\n\nRejustSectionView(&nbsp;doc,&nbsp;window,&nbsp;section&nbsp;);\n</pre>\n\n- Method implementation and action:\n \n<pre class=\"code\">\n<span style=\"color:blue;\">internal</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;RejustSectionView(&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc,\n  <span style=\"color:#2b91af;\">Element</span>&nbsp;elem,&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>&nbsp;section&nbsp;)\n \n<span style=\"color:#2b91af;\">ElementTransformUtils</span>.RotateElement(doc,&nbsp;m_sectionElement.Id,\n  axis,&nbsp;rotateAngle);\n\n<span style=\"color:#2b91af;\">ElementTransformUtils</span>.MoveElement(doc,&nbsp;m_sectionElement.Id,\n  translationVec);\n</pre>\n\n**Response:** Perfect!  I forget the many awesome examples in the SDK.  I really need to look through them instead of always using Google. \n\n**Answer:** I think you need to use both SDK and Internet searches, and more besides, as described\nin [how to research to find a Revit API solution](http://thebuildingcoder.typepad.com/blog/2017/01/virtues-of-reproduction-research-mep-settings-ontology.html#3).\n \n**Response:** I just wanted to add my solution in case anyone else is looking to align section views and create aligned sections.  \n \nHere is a [30-second video on YouTube](https://www.youtube.com/watch?v=gkgV2Ff6zC8) showing my add-in in action:\n\n<center>\n<iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/gkgV2Ff6zC8?rel=0\" frameborder=\"0\" allowfullscreen></iframe>\n</center>\n\nThe source code is provided on GitHub, in [dannysbentley Sections repo](https://github.com/dannysbentley/Sections).\n\nIt sports four external commands:\n\n- CommandUpdate\n- CommandCreateStart\n- CommandCreateEnd\n- CommandCreatePerpendicular\n\nIt also creates a neat little external application presenting a custom ribbon panel to drive them.\n\nMany thanks to Danny for sharing this solution!"
  }
]