[
  {
    "original_filename": "1623_rotate_adjust_conduit",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- 13766538 [创建线管图形形状与实际情况不符]\n  Rotate to Adjust Conduit End\n  Conduit end will exceed the elbow while modifying conduit diameters before elbows are created\n  [Q] one end of his specific conduit element will exceed the elbow”, see attached Observed.jpg and Expected.jpg.\n  There are 5 conduit elements will be created with his codes, but one conduit is in different size and conduit type.\n  After my investigation, I found the following:\n  - It will show up if I changed conduit diameters before creating elbows with his codes. (Included the conduit element with different size and type)\n  - Remove the creation codes of the different size and type one, but change diameters as usual, then this issue won’t appear.\n  [A] Hi Eason, It happened to me as well on pipes and valves.\n  What I’ve done to fix this is after the fitting creation I’ve applied a ElementTransformUtils.Rotate() passing a zero radians angle to the family instance.\n  http://thebuildingcoder.typepad.com/blog/2014/06/refresh-element-graphics-display.html\n  using (Transaction trans = new Transaction(Document, \"虚假旋转线管\"))\n  {\n    trans.Start();\n    var axis = Line.CreateBound(XYZ.Zero, XYZ.BasisX);\n    var ids = createdConduits.Select( c => c.Id )\n    .ToList();\n    \n    ElementTransformUtils.RotateElements(Document, ids, axis, 0);\n    trans.Commit();\n  }  \n\n- 13840360 [How do I create conduit between 2 connectors?]\n  https://forums.autodesk.com/t5/revit-api-forum/how-do-i-create-conduit-between-2-connectors/m-p/7727929\n\nRotation adjusts and fixes conduit end #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/rotationfixconduit\n\nI listed several possible approaches to trigger a refresh of an element's graphics display.\nHere is another one: Applying element rotation to adjust and fix conduit end...\n\n--->"
  },
  {
    "original_filename": "1623_rotate_adjust_conduit",
    "header_text": "Rotation Adjusts and Fixes Conduit End",
    "local_header_href": "#rotation-adjusts-and-fixes-conduit-end",
    "chunk_text": "### Rotation Adjusts and Fixes Conduit End\n\nQuite a while ago, I listed a bunch of possible approaches\nto [refresh element graphics display](http://thebuildingcoder.typepad.com/blog/2014/06/refresh-element-graphics-display.html).\n\nHere comes a new one to join the gang:\n\n\n####<a name=\"2\"></a>Applying Element Rotation to Adjust and Fix Conduit End\n\n**Question:** I am creating a series of several conduit elements.\n\nOne conduit is in a different size and conduit type.\n\nWhen I modify the conduit diameters before the elbow is created, one of the conduit ends exceeds the elbow.\n\nThe observed result looks like this:\n\n<center>\n<img src=\"img/conduit_end_observed.jpg\" alt=\"Conduit end extending too far\" width=\"400\"/>\n</center>\n\nI am expecting it to look like this:\n\n<center>\n<img src=\"img/conduit_end_expected.jpg\" alt=\"Conduit end adjusted\" width=\"400\"/>\n</center>\n\nIf I remove the code to set the different size and type, and change diameters as usual, then this issue does not appear.\n\n**Answer by Paolo Serra:** This happened to me as well on pipes and valves.\n\nI fixed this after the fitting creation by applying a call to `ElementTransformUtils.Rotate` to the family instance, passing in a zero radians angle.\n\n<pre class=\"code\">\n<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;trans&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n{\n&nbsp;&nbsp;trans.Start(&nbsp;<span style=\"color:#a31515;\">&quot;虚假旋转线管&quot;</span>&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;ids&nbsp;=&nbsp;conduits.Select(&nbsp;c&nbsp;=&gt;&nbsp;c.Id&nbsp;).ToList();\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;axis&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.Zero,&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisX&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementTransformUtils</span>.RotateElements(&nbsp;doc,&nbsp;ids,&nbsp;axis,&nbsp;0&nbsp;);\n&nbsp;&nbsp;trans.Commit();\n}\n</pre>\n\n\n<!----\n####<a name=\"3\"></a>Creatng a Conduit Between Two Connectors\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [how to create conduit between two connectors](https://forums.autodesk.com/t5/revit-api-forum/how-do-i-create-conduit-between-2-connectors/m-p/7727929):\n\n**Queston:**\n\n**Answer:**\n---->"
  }
]