[
  {
    "original_filename": "1633_show_elements",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- open view using UIDocument.ShowElements\n  13922857 [Change active document]\n  https://forums.autodesk.com/t5/revit-api-forum/change-active-document/m-p/7787792\n  https://forums.autodesk.com/t5/revit-api-forum/how-to-open-and-active-a-new-document-that-is-not-saved/m-p/7710749\n  Zoom To Awesome!\n\nSwitch view or document by showing elements #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/showelements\n\nA recent discussion on using the <code>ShowElements</code> method to toggle between documents and views brought up a few interesting points\n&ndash; Open and active an unsaved document\n&ndash; Zoom to selected elements\n&ndash; Toggle between documents and views...\n\n--->"
  },
  {
    "original_filename": "1633_show_elements",
    "header_text": "Switch View or Document by Showing Elements",
    "local_header_href": "#switch-view-or-document-by-showing-elements",
    "chunk_text": "### Switch View or Document by Showing Elements\n\nA recent discussion on using the `ShowElements` method to toggle between documents and views brought up a few interesting points:\n\n- [Open and active an unsaved document](#2)\n- [Zoom to selected elements](#3)\n- [Toggle between documents and views](#4)\n\n####<a name=\"2\"></a>Open and Active an Unsaved Document\n\nNormally, you can open and switch between documents using the `OpenAndActivateDocument` method.\n\nHowever, it requires a file path, which may not have been defined yet, in the case of a newly created document.\n\nIn that case, you can open and switch between different documents and their views by calling the `UIDocument` `ShowElements` method instead.\n\nThis was discussed again in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [changing the active document](https://forums.autodesk.com/t5/revit-api-forum/change-active-document/m-p/7787792),\nand previously\nin [how to open and active a new document that is not saved](https://forums.autodesk.com/t5/revit-api-forum/how-to-open-and-active-a-new-document-that-is-not-saved/m-p/7710749):\n\n**Question:** When you have 2 Revit projects open and want to switch between them, it can be done with:\n\n<pre class=\"code\">\n  application.OpenAndActivateDocument(file);\n</pre>\n\nI used `Document.PathName` to get the filename required.\n\nNow I run into problems with files on Revit Server and BIM 360 docs, because their `Document.Pathname` stays empty.\n\nSo, my question is, how do I switch between those documents (when `Document.Pathname` is empty)?\n\nIs there a way to switch between documents without having to specify the file name?\n\n**Answer:** The only way I have found is indirectly via `UIDocument.ShowElements`.\n\nYou pick an element from the DB document you want to change to, create a `UIDocument` object from a DB document and use `UIDocument.ShowElements`. You have to handle the occasional “No good view found” dialogue, but it seems to always switch the active document regardless of what is found. Helps if it is a `View` specific element.\n\nNot sure if there is a better way...\n\nWhen you call `UIDocument.ShowElements`, the active `Document` will change to the document you are showing elements in, therefore:\n\nIf you filter for any element in one of the views of the newly created document, you can call it using that element to activate that document.\n\nSometimes you get the dialogue 'No good view found', which is odd, considering you know there is at least one view with the element in considering you are filtering for it by view. You can handle the appearance of this dialogue and the `ActiveDocument` still gets changed. I believe the new document generally has a view with `Elevation` markers, hence there is always something to find and show.\n\nI don't know the implications of changing the `ActiveDocument` this way or why the API has no ability to directly change the `ActiveDocument` directly, but I suspect if it were easy in terms of how the API works, it would have been done by now.\n\nThis workaround was also mentioned in The Building Coder discussion\non [mirroring in a new family and changing active view](http://thebuildingcoder.typepad.com/blog/2010/11/mirroring-in-a-new-family-and-changing-active-view.html):\n\n> The first issue that arises is that the mirror command requires a current active view, which is not automatically present in the family document. Joe discovers a workaround for that issue using the `ShowElements` method. It generates an unwanted warning message, so a second step is required to deal with eliminating that as well.\n\n> As you can see on reading the final solution carefully, you can use the `ShowElements` method to change the active view and even switch it between the family and project documents. The official Revit 2011 API does not provide any method to switch the active view, but using `ShowElements` can be used to create a workaround for that.\"\n\nI implemented a new external\ncommand [CmdSwitchDoc](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdSwitchDoc.cs)\nin [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples) to try this out, in\n[release 2018.0.138.1](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2018.0.138.1).\n\nIt demonstrates two uses of the `ShowElements` method:\n\n- [Zoom to selected elements](#3)\n- [Toggle between documents and views](#4)\n\n####<a name=\"3\"></a>Zoom to Selected Elements\n\n<pre class=\"code\">\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;Zoom&nbsp;to&nbsp;the&nbsp;given&nbsp;elements,&nbsp;switching&nbsp;view&nbsp;if&nbsp;needed.</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&nbsp;name</span><span style=\"color:gray;\">=</span><span style=\"color:gray;\">&quot;</span>ids<span style=\"color:gray;\">&quot;</span><span style=\"color:gray;\">&gt;&lt;/</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&nbsp;name</span><span style=\"color:gray;\">=</span><span style=\"color:gray;\">&quot;</span>message<span style=\"color:gray;\">&quot;</span><span style=\"color:gray;\">&gt;</span><span style=\"color:green;\">Error&nbsp;message&nbsp;on&nbsp;failure</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&nbsp;name</span><span style=\"color:gray;\">=</span><span style=\"color:gray;\">&quot;</span>elements<span style=\"color:gray;\">&quot;</span><span style=\"color:gray;\">&gt;</span><span style=\"color:green;\">Elements&nbsp;causing&nbsp;failure</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">param</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">returns</span><span style=\"color:gray;\">&gt;&lt;/</span><span style=\"color:gray;\">returns</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:#2b91af;\">Result</span>&nbsp;ZoomToElements(&nbsp;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>&nbsp;uidoc,\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;ids,\n&nbsp;&nbsp;<span style=\"color:blue;\">ref</span>&nbsp;<span style=\"color:blue;\">string</span>&nbsp;message,\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementSet</span>&nbsp;elements&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;n&nbsp;=&nbsp;ids.Count;\n\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;0&nbsp;==&nbsp;n&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;message&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;Please&nbsp;select&nbsp;at&nbsp;least&nbsp;one&nbsp;element&nbsp;to&nbsp;zoom&nbsp;to.&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Cancelled;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">try</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;uidoc.ShowElements(&nbsp;ids&nbsp;);\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">catch</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;uidoc.Document;\n\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;id&nbsp;<span style=\"color:blue;\">in</span>&nbsp;ids&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;=&nbsp;doc.GetElement(&nbsp;id&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elements.Insert(&nbsp;e&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;}\n\n&nbsp;&nbsp;&nbsp;&nbsp;message&nbsp;=&nbsp;<span style=\"color:blue;\">string</span>.Format(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Cannot&nbsp;zoom&nbsp;to&nbsp;element{0}.&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1&nbsp;==&nbsp;n&nbsp;?&nbsp;<span style=\"color:#a31515;\">&quot;&quot;</span>&nbsp;:&nbsp;<span style=\"color:#a31515;\">&quot;s&quot;</span>&nbsp;);\n\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Failed;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Succeeded;\n}\n</pre>\n\nThis functionality is similar to that provided by\nthe [Zoom to Awesome! add-in](https://bimopedia.com/2013/04/02/zoom-to-awesome) by Phil Read.\n\nHere is a 40-second demo by Luke Johnson\nof [using Zoom to Awesome](https://knowledge.autodesk.com/support/revit-products/getting-started/caas/screencast/Main/Details/8e9a043d-9383-496b-8e86-6ec3ab055c0e.html),\nalso showing how to add a keyboard shortcut:\n\n<center>\n<iframe width=\"400\" height=\"470\" src=\"https://screencast.autodesk.com/Embed/Timeline/8e9a043d-9383-496b-8e86-6ec3ab055c0e\" frameborder=\"0\" allowfullscreen webkitallowfullscreen></iframe>\n</center>\n\n####<a name=\"4\"></a>Toggle Between Documents and Views\n\n<pre class=\"code\">\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;Toggle&nbsp;back&nbsp;and&nbsp;forth&nbsp;between&nbsp;two&nbsp;different&nbsp;documents</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:blue;\">void</span>&nbsp;ToggleViews(&nbsp;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;view1,&nbsp;\n&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;filepath2&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;view1.Document;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>&nbsp;uidoc&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>(&nbsp;doc&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Application</span>&nbsp;app&nbsp;=&nbsp;doc.Application;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIApplication</span>&nbsp;uiapp&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">UIApplication</span>(&nbsp;app&nbsp;);\n\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Select&nbsp;some&nbsp;elements&nbsp;in&nbsp;the&nbsp;first&nbsp;document</span>\n\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;idsView1\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc,&nbsp;view1.Id&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.ToElementIds();\n\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Open&nbsp;the&nbsp;second&nbsp;file</span>\n\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>&nbsp;uidoc2&nbsp;=&nbsp;uiapp\n&nbsp;&nbsp;&nbsp;&nbsp;.OpenAndActivateDocument(&nbsp;filepath2&nbsp;);\n\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc2&nbsp;=&nbsp;uidoc2.Document;\n\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Do&nbsp;something&nbsp;in&nbsp;second&nbsp;file</span>\n\n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc2&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Change&nbsp;Scale&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;doc2.ActiveView.get_Parameter(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.VIEW_SCALE_PULLDOWN_METRIC&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Set(&nbsp;20&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();\n&nbsp;&nbsp;}\n\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Save&nbsp;modified&nbsp;second&nbsp;file</span>\n\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">SaveAsOptions</span>&nbsp;opt&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">SaveAsOptions</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;OverwriteExistingFile&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>\n&nbsp;&nbsp;};\n\n&nbsp;&nbsp;doc2.SaveAs(&nbsp;filepath2,&nbsp;opt&nbsp;);\n\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Switch&nbsp;back&nbsp;to&nbsp;original&nbsp;file;</span>\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;in&nbsp;a&nbsp;new&nbsp;file,&nbsp;doc.PathName&nbsp;is&nbsp;empty</span>\n\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;!<span style=\"color:blue;\">string</span>.IsNullOrEmpty(&nbsp;doc.PathName&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;uiapp.OpenAndActivateDocument(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;doc.PathName&nbsp;);\n\n&nbsp;&nbsp;&nbsp;&nbsp;doc2.Close(&nbsp;<span style=\"color:blue;\">false</span>&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;no&nbsp;problem&nbsp;here,&nbsp;says&nbsp;Remy</span>\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Avoid&nbsp;using&nbsp;OpenAndActivateDocument</span>\n\n&nbsp;&nbsp;&nbsp;&nbsp;uidoc.ShowElements(&nbsp;idsView1&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;uidoc.RefreshActiveView();\n\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//doc2.Close(&nbsp;false&nbsp;);&nbsp;//&nbsp;Remy&nbsp;says:&nbsp;Revit&nbsp;throws&nbsp;the&nbsp;exception&nbsp;and&nbsp;doesn&#39;t&nbsp;close&nbsp;the&nbsp;file</span>\n&nbsp;&nbsp;}\n}\n</pre>\n\n<center>\n<img src=\"img/toggle.png\" alt=\"Toggle\" width=\"183\"/>\n</center>"
  }
]