[
  {
    "original_filename": "1642_rot_bbfilter_outline",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- you cannot rotate the outline; rotate the elements instead, or create a solid yourself\n  https://forums.autodesk.com/t5/revit-api-forum/boundingbox-outline-and-boundingboxisinsidefilter/m-p/7921336\n  \nBounding box filter is always axis aligned #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/bbfilteraxisaligned\n\nThis is pretty obvious, once you think about it, and apparently worth pointing out anyway:\nThe outline defining a bounding box filter is always aligned with the cardinal axes\n&ndash; Rotating <code>Min</code> and <code>Max</code> distorts the box\n&ndash; Rotate target elements or use a solid filter...\n\n--->"
  },
  {
    "original_filename": "1642_rot_bbfilter_outline",
    "header_text": "Bounding Box Filter is Always Axis Aligned",
    "local_header_href": "#bounding-box-filter-is-always-axis-aligned",
    "chunk_text": "### Bounding Box Filter is Always Axis Aligned\n\nThis is pretty obvious, once you think about it, and apparently worth pointing out anyway:\n\nThe outline defining a bounding box filter is always aligned with the cardinal axes.\n\nThis question was clarified in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread \non [`BoundingBox` outline and `BoundingBoxIsInsideFilter`](https://forums.autodesk.com/t5/revit-api-forum/boundingbox-outline-and-boundingboxisinsidefilter/m-p/7921336):\n\n- [Rotating `Min` and `Max` distorts the box](#2) \n- [Rotate target elements or use a solid filter](#3) \n\n####<a name=\"2\"></a>Rotating Min and Max Distorts the Box\n\n**Question:** I have a question about a bounding box.\n\nI tried to get its outline and retrieve the elements inside it.\n\nI encountered 3 cases:\n\n- Rotation = 0 deg &ndash; My code works fine with a horizontal bounding box:\n\n<center>\n<img src=\"img/rotated_bounding_box_1.png\" alt=\"Bounding box rotated 0 degrees\" width=\"545\"/>\n</center>\n\n- Rotation = 10 ~ 20 deg &ndash; I can still get the BoundingBox outline, but cannot select all elements inside:\n\n<center>\n<img src=\"img/rotated_bounding_box_2.png\" alt=\"Bounding box rotated 10 ~ 20 degrees\" width=\"575\"/>\n</center>\n\n- Rotation > 45 deg &ndash; I cannot get the BoundingBox outline. The error message says, \"outline is an empty outline\":\n\n<center>\n<img src=\"img/rotated_bounding_box_3.png\" alt=\"Bounding box rotated &gt; 45 degrees\" width=\"621\"/>\n</center>\n\nHere is the code; the exception is thrown by the `Outline` constructor:\n\n<pre class=\"code\">\n  <span style=\"color:#2b91af;\">View3D</span>&nbsp;curView3d&nbsp;=&nbsp;doc.ActiveView&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">View3D</span>;\n  <span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;box&nbsp;=&nbsp;curView3d.GetSectionBox();\n  <span style=\"color:#2b91af;\">Transform</span>&nbsp;t&nbsp;=&nbsp;box.Transform;\n   \n  <span style=\"color:#2b91af;\">Outline</span>&nbsp;o&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Outline</span>(&nbsp;\n  &nbsp;&nbsp;t.OfPoint(&nbsp;box.Min&nbsp;),&nbsp;\n  &nbsp;&nbsp;t.OfPoint(&nbsp;box.Max&nbsp;)&nbsp;);\n   \n  <span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;collector&nbsp;\n  &nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;);\n   \n  <span style=\"color:#2b91af;\">BoundingBoxIsInsideFilter</span>&nbsp;bbfilter&nbsp;\n  &nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxIsInsideFilter</span>(&nbsp;o&nbsp;);\n   \n  <span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;insideList&nbsp;=&nbsp;collector\n  &nbsp;&nbsp;.WhereElementIsNotElementType()\n  &nbsp;&nbsp;.WherePasses(&nbsp;bbfilter&nbsp;)\n  &nbsp;&nbsp;.Where(&nbsp;x&nbsp;=&gt;&nbsp;x.GetTypeId().IntegerValue&nbsp;!=&nbsp;-1&nbsp;)\n  &nbsp;&nbsp;.Where(&nbsp;x&nbsp;=&gt;&nbsp;x.IsPhysicalElement()&nbsp;)\n  &nbsp;&nbsp;.Select(&nbsp;x&nbsp;=&gt;&nbsp;x.Id&nbsp;)\n  &nbsp;&nbsp;.ToList();\n   \n  uidoc.Selection.SetElementIds(&nbsp;insideList&nbsp;);\n</pre>\n\n\n####<a name=\"3\"></a>Rotate Target Elements or Use a Solid Filter\n\n**Answer:** As said, this is pretty obvious, once you think about it.\n\nThe outline defining a bounding box filter is always aligned with the cardinal axes.\n\nIf you simply grab the `Min` and `Max` point of the bounding box and rotate them far enough, they will end up in positions that specify an empty `Outline`.\n\nHence the exception.\n\nYou seem to be expecting a rotated box. Instead, it creates an axis aligned outline, which won't have the same proportions as the original box (the min and max were rotated).\n\nYou can solve this problem by doing the opposite, i.e., rotating the elements' outlines and not the BBox's outline (new outline from all rotated corners, so you lose some precision).\n\nWe ended up doing that is one case and it worked pretty well. \n\nAnother approach that comes to mind:\n\nInstead of using the [`BoundingBoxIsInsideFilter` class](http://www.revitapidocs.com/2018.1/eb8735d7-28fc-379d-9de9-1e02326851f5.htm) with an axis-aligned bounding box,\nyou could simply create your own `Solid` representing the rotated box and use\nan [`ElementIntersectsSolidFilter`](http://www.revitapidocs.com/2018.1/19276b94-fa39-64bb-bfb8-c16967c83485.htm).\n\nNote that the `BoundingBoxIsInsideFilter` is a quick filter, whereas the `ElementIntersectsSolidFilter` is slow,\ncf. [Quick, Slow and LINQ Element Filtering](http://thebuildingcoder.typepad.com/blog/2015/12/quick-slow-and-linq-element-filtering.html)."
  }
]