[
  {
    "original_filename": "1663_explode_nested_families",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\nSimplifying nested family instances in the #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/simplifynestedinstance\n\nJosé Alberto Torres Jaraute implemented an add-in tool to protect the intellectual property built into a complex hierarchy of nested family instances by replacing them with a flatter and simpler hierarchy, yet retaining all the relevant non-confidential custom data.\nBasically, his tool also enables location of overlapping elements and duplicates elimination.\nIn the course of this work, Alberto raised a number of questions in\nthe Revit API discussion forum\n&ndash; Explode nested families\n&ndash; Insert a curve-based family instance associated to a face\n&ndash; Explode family instance to get all the components of a family in project\n&ndash; Change the host and work plane of a family...\n\n--->"
  },
  {
    "original_filename": "1663_explode_nested_families",
    "header_text": "Simplifying Nested Family Instances",
    "local_header_href": "#simplifying-nested-family-instances",
    "chunk_text": "### Simplifying Nested Family Instances\n\nJosé [Alberto Torres](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/71628) Jaraute has\nbeen working on an add-in tool to protect the intellectual property built into a complex hierarchy of nested family instances by replacing them with a flatter and simpler hierarchy, yet retaining all the relevant non-confidential custom data.\n\nBasically, his tool also enables location of overlapping elements and duplicates elimination.\n\nIn the course of this work, Alberto raised a number of questions in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160):\n\n- [Explode nested families](https://forums.autodesk.com/t5/revit-api-forum/explode-nested-familes/m-p/8042667)\n- [Insert a curve-based family instance associated to a face](https://forums.autodesk.com/t5/revit-api-forum/insert-a-family-curvebased-with-newfamilyinstance-associated-to/m-p/7390334)\n- [Explode family instance to get all the components of a family in project](https://forums.autodesk.com/t5/revit-api-forum/explode-familyinstance-to-get-all-the-components-of-the-family/m-p/6984603)\n- [Change the host and work plane of a family](https://forums.autodesk.com/t5/revit-api-forum/is-there-no-way-to-change-the-host-and-work-plan-of-a-family/m-p/7252070)\n\nThese discussions led to a fruitful conclusion, and Alberto now very kindly reports on the successful project completion:\n \nI use the term `SET` to denote all the `FamilyInstance` children of a `FamilyInstance` with multiple sub-instances.\n\nI implemented the following procedure to deal with a `SET`:\n\n- Select a `SET`.\n- Save in a class the main corporate parameters of this `SET`: Phases, Manufacturer, custom data, etc.\n- Remove all `FamilyInstance` daughters with `GetSubComponentIds` to a collection of element ids.\n- Go through each element of the collection and convert it to a `FamilyInstance`.\n- From each element, retrieve its transformation from `GeometryInstance` and extract the insertion point and `BasisX` to determine its rotation.\n- Create a `SketchPlane` using this data and the normal vector it defines.\n- Analyse the `FamilySymbol`, `Mirrored` and `FacingFlipped` properties.\n- Insert a new `FamilyInstance` into the new `SketchPlane` taking the insertion point and rotation of the original family into account:\n\n<pre class=\"code\">\n      doc.Create.NewFamilyInstance(\n        point, symbol, xvec, sketchPlane,\n        StructuralType.NonStructural );\n</pre>\n\n- Copy all the parameter data of the original family instance to the new one.\n- Copy the saved parameters of the SET to the new family instance.\n- Determine whether the original family instance has `Mirrored` or `FacingFlipped` set.\n- If either of them is `true`, calculate and apply the corresponding mirroring, calculating it from the work plane, the reference plane or the corresponding reference line.\n- Last and very important: extract all extrusions from the general parent `SET` and recreate them as `DirectShape` elements, using the name of the family instance with an auto-numbering suffix.\n- Finally, after asking the user, group all the new elements in a `Group` with the name of the `SET` plus an auto-numbering suffix.\n\nI also implemented an event to cancel the warnings displayed when inserting a new family instance at a point where another one already exists. It is removed again after terminating this process.\n\nUnfortunately, I cannot share the complete code for confidentiality reasons.\n\nThank you very much for the fruitful discussions!\n\nMany thanks to Alberto for sharing his experience and workflow!\n\nBy the way, in case you are interested in flattening and simplifying, you might also want to check out the more radical approach \nof [flattening all elements to `DirectShape`](http://thebuildingcoder.typepad.com/blog/2015/11/flatten-all-elements-to-directshape.html).\n\n<center>\n<img src=\"img/nesting_matryoshka_dolls.png\" alt=\"Nested matryoshka dolls\" width=\"270\"/>\n</center>"
  }
]