[
  {
    "original_filename": "1807_createviaoffset",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n</head>\n\n<!---\n\n- https://autodesk.slack.com/archives/C0SR6NAP8/p1576232650000100?thread_ts=1576185616.111700&cid=C0SR6NAP8\n\n- Room boundary polygons\n  https://forums.autodesk.com/t5/revit-api-forum/room-boundary-polygons/m-p/9157379\n  CreateViaOffset to offset room boundary inwards or outwards\n  https://forums.autodesk.com/t5/revit-api-forum/createviaoffset/m-p/9159500\n  CreateViaOffset(CurveLoop original,IList<double> offsetDists,XYZ normal)\n  https://forums.autodesk.com/t5/revit-api-forum/createviaoffset-curveloop-original-ilist-lt-double-gt/m-p/9196659  \n\ntwitter:\n\nBIM project dashboard, the CreateViaOffset method and the outer footprint of a room including its surrounding walls in the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon http://bit.ly/outerroomoutline\n\nAn inconclusive struggle to use <code>CurveLoop.CreateViaOffset</code> leads us once again to thank the powers that be for the integer-based 2D Boolean Clipper library, and some thoughts on project dashboards\n&ndash; Extracting data for project dashboard\n&ndash; Specifying a list of offsets to <code>CreateViaOffset</code>\n&ndash; Alternatives to determine room outline including surrounding walls...\n\nlinkedin:\n\nBIM project dashboard, the CreateViaOffset method and the outer footprint of a room including its surrounding walls in the #RevitAPI\n\nhttp://bit.ly/outerroomoutline\n\nAn inconclusive struggle to use CurveLoop.CreateViaOffset leads us once again to thank the powers that be for the integer-based 2D Boolean Clipper library, and some thoughts on project dashboards:\n\n- Extracting data for project dashboard\n- Specifying a list of offsets to CreateViaOffset\n- Alternatives to determine room outline including surrounding walls...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<p style=\"font-size: 80%; font-style:italic\"></p>\n\n-->"
  },
  {
    "original_filename": "1807_createviaoffset",
    "header_text": "Dashboard, CreateViaOffset and Room Outer Outline",
    "local_header_href": "#dashboard-createviaoffset-and-room-outer-outline",
    "chunk_text": "### Dashboard, CreateViaOffset and Room Outer Outline\n\nAn inconclusive struggle to use `CurveLoop.CreateViaOffset` leads us once again to thank the powers that be for the integer-based 2D Boolean Clipper library, and some thoughts on project dashboards:\n\n- [Extracting data for project dashboard](#2)\n- [Specifying a list of offsets to `CreateViaOffset`](#3)\n- [Alternatives to determine room outline including surrounding walls](#4)"
  },
  {
    "original_filename": "1807_createviaoffset",
    "header_text": "Extracting Data for Project Dashboard",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Extracting Data for Project Dashboard\n\n**Question:** We are investigating whether some parts of our project management procedures can be automated. Today, we create an overview using PowerBI on project progression by combining data from financials, project controlling (hours, job packages etc.) and the likes. However, progress on the content and completion of design tasks is done manually with input from the project manager, making it difficult to track progress directly.\n \nThe assumption is that many of our graphic files such as .dwg contain data that describes how many documents that have been created and how many tasks have been completed. If can to extract this data, it could be built into some tool to provide an overview. \n \nLet’s imagine we are preparing a renovation of a building and know that we have to complete a set number of PI diagrams as part of the overall design. If this information can easily be extracted from the .dwg files, we could add this to the PowerBI datasets to be included in the overall reporting.\n \nToday, many projects are running smoothly due to experienced project leaders. We would like to create smooth systems to support the process as well as mitigate the risk of not being able to attract senior or skilled enough people to handle the project.\n \nWe tried to investigate whether or not information/lists/drawing overviews from Revit and AutoCAD can be exported into something like .csv, .xlsx and similar user/human friendly formats. Until now, we have not been able to answer this question. We have talked with different people from Autodesk chat support and read several of your blog post answers.\n \nCould you somehow simplify this for me? Is it at all possible to generally export overview of the content of a dwg file in a simple format readable for other applications?\n \n**Answer:** I am not currently very involved with AutoCAD and DWG development, more with Revit RVT.\n \n However, I can certainly confirm that it is definitely both possible and easy to extract all the data you can possibly want from both of them.\n \nYou can do that using AutoCAD and Revit add-ins making use of the desktop .NET APIs.\n \nIf you are making use of any cloud-based workflows and storage, you can also do so online in the web, e.g., making use of the Forge APIs.\n \nIn fact, several people have already done so to create a number of different so-called dashboards that implement exactly what you are asking for.\n \nHere are two in-depth demonstrations of such technology from Autodesk University 2018, a year ago:\n \n- [Using Forge to revolutionise coordinated project information](https://www.autodesk.com/autodesk-university/class/Using-Forge-Revolutionize-Coordinated-Project-Information-2018)\n- [How to Use Forge and BIM 360 to get insight and improve the BIM management of your project](https://www.autodesk.com/autodesk-university/class/How-Use-Forge-and-BIM-360-Get-Insight-and-Improve-BIM-Management-Your-Project-2018)\n \nBy the way, the latter also mentions PowerBI.\n \nThese are just two random hits that popped up in my first quick Internet search\nfor [Autodesk Forge project overview](https://duckduckgo.com/?q=autodesk+forge+project+overview).\n\nMaybe you should try it yourself with 'dashboard' and other such terms.\n\nThere are probably much more advanced samples available today, a year later.\n\nHere is a [link to view all Forge samples](https://forge.autodesk.com/categories/code-samples).\n\nYou might also want to search for 'dashboard' on the Forge blog site using the Google search\nstring [dashboard site:forge.autodesk.com/blog](https://www.google.com/search?q=dashboard+site%3Aforge.autodesk.com%2Fblog)."
  },
  {
    "original_filename": "1807_createviaoffset",
    "header_text": "Specifying a List of Offsets to CreateViaOffset",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Specifying a List of Offsets to CreateViaOffset\n\nStephen Harrison has been valiantly and persistently working on a solution to crop views to rooms, as discussed in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) threads\non [room boundary polygons](https://forums.autodesk.com/t5/revit-api-forum/room-boundary-polygons/m-p/9157379),\n[CreateViaOffset to offset room boundary inwards or outwards](https://forums.autodesk.com/t5/revit-api-forum/createviaoffset/m-p/9159500) and\n[CreateViaOffset taking a list of offset distances](https://forums.autodesk.com/t5/revit-api-forum/createviaoffset-curveloop-original-ilist-lt-double-gt/m-p/9196659).\n\nI set up\nthe [CropViewToRoom GitHub repository](https://github.com/jeremytammik/CropViewToRoom) to\nplay around with various approaches.\n\nI now received some useful guidance from the development on the latest question in this series:\n\n**Question:** I have raised a previous post regarding generating views from rooms but feel that has probably run its course.\n\nThe problem I now face is how to follow the outer face of the wall where the wall changes thickness over its length and when room separators are utilised.\n\nWhen the walls step back like this, there is an error “Curve loop couldn't be properly trimmed”:\n\n<center>\n<img src=\"img/createviaoffset_with_list_1.png\" alt=\"Walls with varying thicknesses\" width=\"300\"> <!--458-->\n<p style=\"font-size: 80%; font-style:italic\">Walls with varying thicknesses</p>\n</center>\n\nRegarding room separators, another problem occurs with a separator like this, Error “Curve loop couldn't be properly trimmed”:\n\n<center>\n<img src=\"img/createviaoffset_with_list_2.png\" alt=\"Walls with room separator\" width=\"213\"> <!--213-->\n<p style=\"font-size: 80%; font-style:italic\">Walls with room separator</p>\n</center>\n\nThere have been no errors so far in situations like this:\n\n<center>\n<img src=\"img/createviaoffset_with_list_3.png\" alt=\"Walls with room separator offset\" width=\"300\"> <!--342-->\n<p style=\"font-size: 80%; font-style:italic\">Walls with room separator offset</p>\n</center>\n\nI am working in C# with Revit 2020 and utilising the following to create the offset:\n\n<pre>\n  CreateViaOffset(\n    CurveLoop original,\n    IList&lt;double&gt; offsetDists,\n    XYZ normal)\n</pre>\n\n`offsetDists` is set to the thicknesses of the surrounding walls plus a standard set offset for the room separator.\n\n\n**Answer:** I integrated and cleaned up your code\nin [CropViewToRoom release 2020.0.0.2](https://github.com/jeremytammik/CropViewToRoom/releases/tag/2020.0.0.2) for\nfurther analysis.\n\nI have not solved it yet, but at least uncovered one definite problem.\n\nIn the room separator model, the curve loop that you assemble has 11 elements, whereas the wall thickness list only has 10. That obviously causes a problem.\n\nI implemented a new method `CreateModelCurves` that creates a set of model curves to display the curve loop:\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">void</span>&nbsp;CreateModelCurves(\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;view,\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">CurveLoop</span>&nbsp;loop&nbsp;)\n  {\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;view.Document;\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">SketchPlane</span>&nbsp;sp&nbsp;=&nbsp;view.SketchPlane;\n   \n  &nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;curve&nbsp;<span style=\"color:blue;\">in</span>&nbsp;loop&nbsp;)\n  &nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;doc.Create.NewModelCurve(&nbsp;curve,&nbsp;sp&nbsp;);\n  &nbsp;&nbsp;}\n  }\n</pre>\n\nThe result for the room separator model looks like this:\n\n<center>\n<img src=\"img/createviaoffset_with_list_room_separator_loop.png\" alt=\"Room separator boundary model curve loop\" width=\"300\"> <!--964-->\n<p style=\"font-size: 80%; font-style:italic\">Room separator boundary model curve loop</p>\n</center>\n\nI leave it up to you to figure out where that extra segment is coming from, what it represents, and how to deal with the wall thickness for that one.\n\nMaybe that will help sort out the other issue as well.\n\nI also reproduced the exception you mentioned creating the offset loop for the wall thickness sample model RVT.\n\nI sent the following question to the development team for a usage example of the method to see what we might be doing wrong.\n\nI am having trouble using\nthe [CreateViaOffset method taking a list of doubles for different offsets](https://www.revitapidocs.com/2020/3097f423-9b0e-5496-bae2-3a82b6875414.htm):\n\nCan you provide a simple sample showing how to use this method?\n\nI tested it passing in five curves representing the following five walls:\n\n<center>\n<img src=\"img/createviaoffset_with_list_wall_width_error_rvt.png\" alt=\"Rectangular room with five walls\" width=\"300\"> <!--846-->\n<p style=\"font-size: 80%; font-style:italic\">Rectangular room with five walls</p>\n</center>\n\nStarting with the bottom horizontal wall and moving counterclockwise to the right, top two and left, I pass in five straight line segment curves and curves and the corresponding five offset distances:\n\n<pre>\n  5 curves with lengths 9.19,9.51,3.61,5.58,9.51\n  and 5 thicknesses 1.08,.43,.43,.76,1.08\n</pre>\n\nThis call throws an `Autodesk.Revit.Exceptions.InvalidOperationException` saying 'Curve loop couldn't be properly trimmed.'\n\n**Answer from the development team:** \nIn the customer's example, it looks like one of the walls is split in two and meet in the middle.\nPerhaps the curves he has are not colinear to start?\nThat, it would seem, could easily result in a disconnected loop.\n\nThis is a sample from our add-in code:\n\n<pre class=\"code\">\n  <span style=\"color:green;\">//&nbsp;previously&nbsp;filled&nbsp;list&nbsp;with&nbsp;simple&nbsp;double&nbsp;</span>\n  <span style=\"color:green;\">//&nbsp;values&nbsp;that&nbsp;represent&nbsp;the&nbsp;distance&nbsp;to&nbsp;offset;&nbsp;</span>\n  <span style=\"color:green;\">//&nbsp;that&nbsp;distance&nbsp;is&nbsp;calculated&nbsp;as&nbsp;the&nbsp;length&nbsp;of&nbsp;</span>\n  <span style=\"color:green;\">//&nbsp;a&nbsp;segment&nbsp;that&nbsp;is&nbsp;perpendicular&nbsp;on&nbsp;the&nbsp;curve&nbsp;</span>\n  <span style=\"color:green;\">//&nbsp;to&nbsp;be&nbsp;offset</span>\n   \n  <span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:blue;\">double</span>&gt;&nbsp;offsetArray;\n  <span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">Curve</span>&gt;&nbsp;polyCurves&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">Curve</span>&gt;();\n   \n  <span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;curve&nbsp;<span style=\"color:blue;\">in</span>&nbsp;contour3D.curves&nbsp;)\n  {\n  &nbsp;&nbsp;polyCurves.Add(&nbsp;curve.asRevitCurve(&nbsp;\n  &nbsp;&nbsp;&nbsp;&nbsp;doc.Application&nbsp;)&nbsp;);\n  }\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;polyCurves.none()&nbsp;)\n  &nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">false</span>;\n   \n  <span style=\"color:#2b91af;\">CurveLoop</span>&nbsp;curveLoop&nbsp;=&nbsp;<span style=\"color:#2b91af;\">CurveLoop</span>.Create(\n  &nbsp;&nbsp;polyCurves&nbsp;);\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;curveLoop&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n  {\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;normal&nbsp;=&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisZ;\n   \n  &nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;curveLoop.HasPlane()&nbsp;)\n  &nbsp;&nbsp;&nbsp;&nbsp;normal&nbsp;=&nbsp;curveLoop.GetPlane().Normal;\n   \n  &nbsp;&nbsp;curveLoop&nbsp;=&nbsp;<span style=\"color:#2b91af;\">CurveLoop</span>.CreateViaOffset(&nbsp;\n  &nbsp;&nbsp;&nbsp;&nbsp;curveLoop,&nbsp;offsetArray,&nbsp;normal&nbsp;);\n   \n  &nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;curveLoop&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n  &nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;do&nbsp;stuff&nbsp;with&nbsp;curve</span>\n  &nbsp;&nbsp;}\n  }\n</pre>\n\nIt's nothing special. BUT... \n\nI suspect the problem stems from the little vertical segment where the different width walls meet.\nWe had problems with this method treating small segments from a structural contour, so the code above is put in a big try/catch and if it fails, we go to another offset algorithm that is far worse in general but treats small segments/self-intersections slightly better (Revit's offset seems more sceptical to prolong segments when it's the case, and I couldn't find code for self-intersections).\nL.E. Edited testing assumptions that are invalid since offset is positive, not negative.\n\nI tested on our code the drawing provided as follows: the contour line is based on the exterior contour of the wall; the first curve in loop is the small one, contour being parsed clockwise; based on your/their code, the offset array is:\n\n<pre>\n  [0]\t0.75616799999999995\tdouble\n  [1]\t0.42808400000000002\tdouble\n  [2]\t0.42808400000000002\tdouble\n  [3]\t1.0842520000000000\tdouble\n  [4]\t1.0842520000000000\tdouble\n  [5]\t0.75616799999999995\tdouble\n</pre>\n\nI tried both positive and negative offsets, and here is the result:\n\n<center>\n<img src=\"img/createviaoffset_with_list_success.png\" alt=\"Successful result\" width=\"600\"> <!--1044-->\n<p style=\"font-size: 80%; font-style:italic\">Successful result</p>\n</center>\n\nNo exceptions, everything worked.\n\nI still stand on my original assumption that it has to do with the small segment, depending on the epsilon set by the add-in; instead of using wall thickness + 0.1 (which is in imperial feet, if not converted), you may try with a fixed percentage based on the wall thickness instead, e.g., 5-10%? &ndash; that may reduce problems with peculiar situations like teeny weeny tiny segments after offset that can't be handled properly.\n\n**Response:** Thank you again for your time and patience in helping me resolve this issue. It is much appreciated.\n\nAll my tests would suggest that the suspected short vertical were the walls meet is the problem. However, I make the following observations.\n\nI have previously tried a fixed percentage based on the wall thickness instead of +0.1 but received the same error.\n\nI have tried exaggerated the wall thickness difference substantially and still received the same error.\n\nIf I have understood the response from the development team correctly, the solution they have proposed needs to be placed in a try catch as it may still fail and a therefore a more complex solution is required in this instance ? Is this alternative solution available through the API and if so, how may it be implemented?\n\n**Answer:** Yes, they suggest using a moderate percentage of the wall thickness, I believe, e.g., 10-20%.\nI guess that for your needs, 110-120% is required.\nThey also say that they tested it that way, and it worked well, offsetting both inwards and outwards.\nThe sample code that they provided was extracted from some internal Revit module and is thus not present in the SDK nor restricted to using the public API.\nIt just shows an example of using the method, regardless of where the input comes from.\n\nI'll try out this percentage thingy on your sample models and see how I fare.\n\nLater: I tried to follow the devteam suggestion of using a percentage instead of a fixed additional offset, and it did not work for me at all.\nI tried both 110%, which would suit your needs, and 10%.\nIn both cases, it still throws the `InvalidOperationException` saying 'loop couldn't be properly trimmed.'\n\nMaybe they tested on a more recent development version of Revit.\n\nSo, I think it might be time to step away from `CreateViaOffset` for the time being.\n\nOn the other hand, your goal is almost reached: you have the room boundary, its boundary elements and their thicknesses.\nFrom those, it is possible to create a curve loop tracing the outside edges of the walls.\n\n**Addendum from the development team:** \nYes, I did test it with unpublished development code; however, we use `CreateViaOffset` in our add-in starting with 2019.1, methinks, and 100% certain in 2020 &ndash; it was fairly ok.\nThe only thing that comes to mind is that we might not be taking the same curves (maybe external curve vs. wall center line, or... dunno). IDEA: instead of taking the contours/whatever from walls, take the bounding box and offset that with the thickest wall... it's not ideal nor pretty, but if its urgent, it should get the job done, best for square rooms, bad and very bad for anything else..."
  },
  {
    "original_filename": "1807_createviaoffset",
    "header_text": "How to Determine Room Outline Including Surrounding Walls",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> How to Determine Room Outline Including Surrounding Walls\n\n**Question:** I started to look at the possibility of tracing the outside of the walls several weeks ago, when I was at a loss utilising `CreateViaOffset`.\n\nI was finding it difficult to create the closed loop necessary, and particularly how I would achieve this were the wall thickness changes across its length.\n\nCould you point me in the right direction, possibly some sample code that I could examine and see if I could get it to work to my requirements.\n\nHope you have a good festive season.\n\n**Answer:** I see several possible alternative approaches avoiding the use of `CreateViaOffset`, based on:\n\n- Room boundary curves and wall thicknesses\n- Room boundary curves and wall bottom face edges\n- Projection of 3D union of room and wall solids\n- 2D union of room and wall footprints\n\nThe most immediate and pure Revit API approach would be to get the curves representing the room boundaries, determine the wall thicknesses, offset the wall boundary curves outwards by wall thickness plus minimum offset, and ensure that everything is well connected by adding small connecting segments in the gaps where the offset jumps.\n\nSeveral slightly more complex pure Revit API approaches could be designed by using the wall solids instead of just offsetting the room boundary curves based on the wall thickness. For instance, we could query the wall bottom face for its edges, determine and patch together all the bits of edge segments required to go around the outside of the wall instead of the inside.\n\nSlightly more complex still, and still pure Revit API: determine the room closed shell solid, unite it with all the wall solids, and make use of the extrusion analyser to project this union vertically onto the XY plane and grab its outside edge.\n\nFinally, making use of a minimalistic yet powerful 2D Boolean operation library, perform the projection onto the XY plane first, and unite the room footprint with all its surrounding wall footprints in 2D instead. Note that the 2D Booleans are integer based. To make use of those, I convert the geometry from imperial feet units using real numbers to integer-based millimetres.\n\nThe two latter approaches are both implemented in\nmy [ElementOutline add-in](https://github.com/jeremytammik/ElementOutline).\n\nI mentioned it here in two previous threads:\n\n- [Question regarding SVG data](https://forums.autodesk.com/t5/revit-api-forum/question-regarding-svg-data-from-revit/m-p/9106146)\n- [How do I get the outline and stakeout path of a built-in loft family](https://forums.autodesk.com/t5/revit-api-forum/how-do-i-get-the-outline-and-stakeout-path-of-a-built-in-loft/m-p/9148138)\n\nProbably all the pure Revit API approaches will run into various problematic exceptional cases, whereas the 2D Booleans seem very fast, reliable and robust and may well be able to handle all the exceptional cases that can possibly occur, so I would recommend trying that out first.\n\nI hope this suggestion makes for a nice gift to you in this festive season.\n\nHappy advent!\n\n\n<!---\nZ:\\a\\src\\rvt\\CropViewToRoom\\test\\wall_width_error.rvt\n-->"
  }
]