[
  {
    "original_filename": "1828_change_room_level",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n</head>\n\n<!---\n\n- /a/doc/revit/tbc/git/a/img/panel_boards_api_pole_breaker_count.jpg\n  \n- [A Guide to Console Commands](https://css-tricks.com/a-guide-to-console-commands)\n\ntwitter:\n\nMove existing rooms between levels while retaining their information, thoughts on managing slots in panel schedules, and useful JavaScript debugging console hints for the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon https://bit.ly/panelslotroomlevel\n\nAn amazing solution to move existing rooms between levels while retaining all their information, some thoughts on managing slots in panel schedules, and a couple of useful JavaScript debugging console hints\n&ndash; Moving rooms to other levels\n&ndash; Slots in panel schedules\n&ndash; JavaScript debugging console commands...\n\nlinkedin:\n\nMove existing rooms between levels while retaining their information, thoughts on managing slots in panel schedules, and useful JavaScript debugging console hints for the #RevitAPI\n\nhttps://bit.ly/panelslotroomlevel\n\nAn amazing solution to move existing rooms between levels while retaining all their information, some thoughts on managing slots in panel schedules, and a couple of useful JavaScript debugging console hints:\n\n- Moving rooms to other levels\n- Slots in panel schedules\n- JavaScript debugging console commands...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"100\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1828_change_room_level",
    "header_text": "Panel Schedule Slots and Changing Room Level",
    "local_header_href": "#panel-schedule-slots-and-changing-room-level",
    "chunk_text": "### Panel Schedule Slots and Changing Room Level\n\nAn amazing solution to move existing rooms between levels while retaining all their information, some thoughts on managing slots in panel schedules, and a couple of useful JavaScript debugging console hints:\n\n- [Moving rooms to other levels](#2)\n- [Slots in panel schedules](#3)\n- [JavaScript debugging console commands](#4)"
  },
  {
    "original_filename": "1828_change_room_level",
    "header_text": "<a name=\"2\"></a>Moving Rooms to Other Levels",
    "local_header_href": "#a-name2amoving-rooms-to-other-levels",
    "chunk_text": "#### <a name=\"2\"></a>Moving Rooms to Other Levels\n\nAfter a year of discussion in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [how to change the associated level of rooms](https://forums.autodesk.com/t5/revit-api-forum/how-to-change-the-associated-level-of-rooms/m-p/9374610),\nSean Page now shares an amazing solution, to quote Mahshid Motie, who raised it in the first place:\n\n**Question:** I want to change the associated level of rooms to have them on the right building story.\nBoth using C# and in the user interface, the level parameter of the rooms is read-only and cannot be modified.\n\nSo far, I can only solve this by copying, pasting, and deleting.\n\n**Answer:** The concept of this intrigued me, so I set off on a way to make this happen.\nI think I have an OK solution that does not involve groups or really any work around at all.\n\nI don't know of any way to change the level directly.\n\nHowever, if you delete a room, you get a warning that it is deleted and still exists in the project &ndash; the 'not placed' message in room schedule.\n\nNow when you place a new room at the correct level, don't place an entirely new room, but pick the correct unplaced room:\n\n<center>\n<img src=\"img/new_unplaced_room.png\" alt=\"New unplaced room\" title=\"New unplaced room\" width=\"800\"/> <!-- 1264 -->\n</center>\n\nIt will retain all the properties of the deleted one, including the room number!\n\nConcept:\n\n- Select the rooms to move\n- Select the level to move them too\n- Press OK\n- Store the Room Location Point\n- Unplace the Room\n- Use a Failure Handler to bypass the \"Unplaced room in model\" warning\n- Get the Plan Topology for the level selected\n- Find an empty circuit in the Topology\n- There has to be at least one empty circuit (Room)\n- Replace the room\n- Move the room to the location it was in on the other level\n\nHere is the command code:\n\n<pre class=\"prettyprint\">using Autodesk.Revit.DB.Architecture;\nusing Autodesk.Revit.DB;\nusing System;\nusing System.Collections.Generic;\nusing System.ComponentModel;\nusing System.Data;\nusing System.Drawing;\nusing System.Linq;\nusing System.Text;\nusing System.Threading.Tasks;\nusing System.Windows.Forms;\n\nnamespace MyApp.Testing\n{\n  public partial class TestForm : System.Windows.Forms.Form\n  {\n    Document doc;\n    public TestForm(Document _doc)\n    {\n      InitializeComponent();\n      doc = _doc;\n    }\n\n    private void btnClose_Click(object sender, EventArgs e)\n    {\n      Close();\n    }\n\n    private void TestForm_Load(object sender, EventArgs e)\n    {\n      foreach (Room room in Helpers.Collectors.ByCategory(doc, BuiltInCategory.OST_Rooms))\n      {\n        if (room.Area > 0 && room.Location != null)\n        {\n          ListViewItem item = listView1.Items.Add(room.Number + \" - \" + room.Name);\n          item.Tag = room;\n        }\n      }\n\n      SortedList<string, Level> levels = new SortedList<string, Level>();\n      foreach (Level level in Helpers.Collectors.ByCategoryNotElementType(doc, BuiltInCategory.OST_Levels))\n      {\n        levels.Add(level.Name, level);\n      }\n\n      cboLevel.DataSource = levels.ToList();\n      cboLevel.DisplayMember = \"Key\";\n      cboLevel.ValueMember = \"Value\";\n    }\n\n    private void btmOK_Click(object sender, EventArgs e)\n    {\n      try\n      {\n        using (TransactionGroup transGroup = new TransactionGroup(doc))\n        {\n          transGroup.Start(\"Move Rooms\");\n          foreach (ListViewItem item in listView1.CheckedItems)\n          {\n            Room room = (Room)item.Tag;\n            LocationPoint rmPT = room.Location as LocationPoint;\n            XYZ roomPoint = rmPT.Point;\n            double offset = room.LimitOffset;\n            using (Transaction trans1 = new Transaction(doc))\n            {\n              trans1.Start(\"Unplace Room\");\n              FailureHandlingOptions failOptions = trans1.GetFailureHandlingOptions();\n              failOptions.SetFailuresPreprocessor(new UnplacedRoomWarning());\n              trans1.SetFailureHandlingOptions(failOptions);\n\n              room.Unplace();\n              trans1.Commit();\n            }\n\n            using (Transaction trans2 = new Transaction(doc))\n            {\n              trans2.Start(\"New Room\");\n              Level level = (Level)cboLevel.SelectedValue;\n              PlanTopology topo = doc.get_PlanTopology(level);\n              PlanCircuitSet circuits = topo.Circuits;\n\n              foreach (PlanCircuit circuit in circuits)\n              {\n                if (!circuit.IsRoomLocated)\n                {\n                  Room newRoom = doc.Create.NewRoom(room, circuit);\n                  newRoom.get_Parameter(BuiltInParameter.ROOM_UPPER_LEVEL).Set(level.Id);\n                  newRoom.LimitOffset = offset;\n                  XYZ move = new XYZ(roomPoint.X - rmPT.Point.X, roomPoint.Y - rmPT.Point.Y, rmPT.Point.Z);\n                  ElementTransformUtils.MoveElement(doc, newRoom.Id, move);\n                  break;\n                }\n              }\n              trans2.Commit();\n            }\n          }\n          transGroup.Assimilate();\n          Close();\n        }\n      }\n      catch (Exception ex)\n      {\n        MessageBox.Show(ex.ToString());\n      }\n    }\n  }\n\n  public class UnplacedRoomWarning : IFailuresPreprocessor\n  {\n    public FailureProcessingResult PreprocessFailures(FailuresAccessor failuresAccessor)\n    {\n      IList<FailureMessageAccessor> failures = new List<FailureMessageAccessor>();\n      failures = failuresAccessor.GetFailureMessages();\n\n      foreach (FailureMessageAccessor failure in failures)\n      {\n        if (failure.GetSeverity() == FailureSeverity.Warning)\n        {\n          if (failure.GetFailureDefinitionId() == BuiltInFailures.RoomFailures.RoomUnplaceWarning || failure.GetFailureDefinitionId() == BuiltInFailures.RoomFailures.RoomHeightNegative)\n          {\n            failuresAccessor.DeleteWarning(failure);\n          }\n        }\n        else\n        {\n          failuresAccessor.ResolveFailure(failure);\n          return FailureProcessingResult.ProceedWithCommit;\n        }\n      }\n      return FailureProcessingResult.Continue;\n    }\n  }\n}\n</pre>\n\nThe simple Win Form layout:\n\n<center>\n<img src=\"img/select_placed_rooms.png\" alt=\"Select placed rooms\" title=\"Select placed rooms\" width=\"400\"/>\n</center>\n\nHere is the Win Form designer code:\n\n<pre class=\"prettyprint\">\nnamespace MyApp.Testing\n{\n  partial class TestForm\n  {\n    /// <summary>\n    /// Required designer variable.\n    /// </summary>\n    private System.ComponentModel.IContainer components = null;\n\n    /// <summary>\n    /// Clean up any resources being used.\n    /// </summary>\n    /// <param name=\"disposing\">true if managed resources should be disposed; otherwise, false.</param>\n    protected override void Dispose(bool disposing)\n    {\n      if (disposing && (components != null))\n      {\n        components.Dispose();\n      }\n      base.Dispose(disposing);\n    }\n\n    #region Windows Form Designer generated code\n\n    /// <summary>\n    /// Required method for Designer support - do not modify\n    /// the contents of this method with the code editor.\n    /// </summary>\n    private void InitializeComponent()\n    {\n      this.btnClose = new System.Windows.Forms.Button();\n      this.btmOK = new System.Windows.Forms.Button();\n      this.listView1 = new System.Windows.Forms.ListView();\n      this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));\n      this.cboLevel = new System.Windows.Forms.ComboBox();\n      this.label1 = new System.Windows.Forms.Label();\n      this.label2 = new System.Windows.Forms.Label();\n      this.SuspendLayout();\n      // \n      // btnClose\n      // \n      this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));\n      this.btnClose.Location = new System.Drawing.Point(216, 526);\n      this.btnClose.Name = \"btnClose\";\n      this.btnClose.Size = new System.Drawing.Size(75, 23);\n      this.btnClose.TabIndex = 0;\n      this.btnClose.Text = \"Close\";\n      this.btnClose.UseVisualStyleBackColor = true;\n      this.btnClose.Click += new System.EventHandler(this.btnClose_Click);\n      // \n      // btmOK\n      // \n      this.btmOK.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));\n      this.btmOK.Location = new System.Drawing.Point(297, 526);\n      this.btmOK.Name = \"btmOK\";\n      this.btmOK.Size = new System.Drawing.Size(75, 23);\n      this.btmOK.TabIndex = 1;\n      this.btmOK.Text = \"OK\";\n      this.btmOK.UseVisualStyleBackColor = true;\n      this.btmOK.Click += new System.EventHandler(this.btmOK_Click);\n      // \n      // listView1\n      // \n      this.listView1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) \n      | System.Windows.Forms.AnchorStyles.Left) \n      | System.Windows.Forms.AnchorStyles.Right)));\n      this.listView1.CheckBoxes = true;\n      this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {\n      this.columnHeader3});\n      this.listView1.FullRowSelect = true;\n      this.listView1.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.None;\n      this.listView1.HideSelection = false;\n      this.listView1.Location = new System.Drawing.Point(12, 27);\n      this.listView1.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);\n      this.listView1.Name = \"listView1\";\n      this.listView1.Size = new System.Drawing.Size(360, 464);\n      this.listView1.Sorting = System.Windows.Forms.SortOrder.Ascending;\n      this.listView1.TabIndex = 2;\n      this.listView1.UseCompatibleStateImageBehavior = false;\n      this.listView1.View = System.Windows.Forms.View.Details;\n      // \n      // columnHeader3\n      // \n      this.columnHeader3.Text = \"\";\n      this.columnHeader3.Width = 350;\n      // \n      // cboLevel\n      // \n      this.cboLevel.FormattingEnabled = true;\n      this.cboLevel.Location = new System.Drawing.Point(78, 499);\n      this.cboLevel.Name = \"cboLevel\";\n      this.cboLevel.Size = new System.Drawing.Size(294, 21);\n      this.cboLevel.TabIndex = 3;\n      // \n      // label1\n      // \n      this.label1.AutoSize = true;\n      this.label1.Location = new System.Drawing.Point(12, 502);\n      this.label1.Name = \"label1\";\n      this.label1.Size = new System.Drawing.Size(60, 13);\n      this.label1.TabIndex = 4;\n      this.label1.Text = \"Pick Level:\";\n      // \n      // label2\n      // \n      this.label2.AutoSize = true;\n      this.label2.Location = new System.Drawing.Point(12, 9);\n      this.label2.Name = \"label2\";\n      this.label2.Size = new System.Drawing.Size(112, 13);\n      this.label2.TabIndex = 4;\n      this.label2.Text = \"Select Placed Rooms:\";\n      // \n      // TestForm\n      // \n      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);\n      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;\n      this.ClientSize = new System.Drawing.Size(384, 561);\n      this.Controls.Add(this.label2);\n      this.Controls.Add(this.label1);\n      this.Controls.Add(this.cboLevel);\n      this.Controls.Add(this.listView1);\n      this.Controls.Add(this.btmOK);\n      this.Controls.Add(this.btnClose);\n      this.Name = \"TestForm\";\n      this.Text = \"TestForm\";\n      this.Load += new System.EventHandler(this.TestForm_Load);\n      this.ResumeLayout(false);\n      this.PerformLayout();\n\n    }\n\n    #endregion\n\n    private System.Windows.Forms.Button btnClose;\n    private System.Windows.Forms.Button btmOK;\n    private System.Windows.Forms.ListView listView1;\n    private System.Windows.Forms.ColumnHeader columnHeader3;\n    private System.Windows.Forms.ComboBox cboLevel;\n    private System.Windows.Forms.Label label1;\n    private System.Windows.Forms.Label label2;\n  }\n}\n</pre>\n\nTo see how this works live, here is a [20-second screen recording](zip/change_room_level.webm):\n\n<center>\n<!-- <iframe width=\"640\" height=\"620\" style=\"position: absolute; left: 0; top: 0; width: 100%; height: 100%;\" src=\"https://screencast.autodesk.com/Embed/Timeline/b427c037-3b56-415e-a2b9-55e17ef23475\" frameborder=\"0\" allowfullscreen=\"true\" webkitallowfullscreen=\"true\" scrolling=\"no\"></iframe> -->\n<iframe width=\"480\" height=\"270\" src=\"https://screencast.autodesk.com/Embed/Timeline/b427c037-3b56-415e-a2b9-55e17ef23475\" frameborder=\"0\" allowfullscreen=\"true\" webkitallowfullscreen=\"true\" scrolling=\"no\"></iframe>\n</center>\n\nMany thanks to Sean for the great idea and simple solution!"
  },
  {
    "original_filename": "1828_change_room_level",
    "header_text": "<a name=\"3\"></a>Slots in Panel Schedules",
    "local_header_href": "#a-name3aslots-in-panel-schedules",
    "chunk_text": "#### <a name=\"3\"></a>Slots in Panel Schedules\n\n**Question:** I would like to programmatically assign slots in a panel schedule as Spaces or Spares.\nI would also like to Lock and Unlock slots.\nCan this be done with the Revit API?\n\nIf there is no way via that API, is there any other way we can achieve it?\n\n<center>\n<img src=\"img/panel_boards_api_pole_breaker_count.jpg\" alt=\"Panel properties\" title=\"Panel properties\" width=\"490\"/>\n</center>\n\n**Answer:** The *Autodesk.Revit.DB.Electrical* [`PanelScheduleView` member methods](https://www.revitapidocs.com/2020/05d89377-2e7d-9e8f-7f57-192ecb2f23e8.htm) include: `IsSpace`, `IsSpare`, `IsSlotLocked`, `AddSpace`, `AddSpare`, `RemoveSpace`, `RemoveSpare`, etc.\n\nThere is currently no public API for lock and unlock.\n\nThat would suggest that only the locking is not possible.\n\nHowever, a more important question might be whether you really need to do that (caveat: just guessing your objectives).\n\nSpares/Spaces can certainly be defined in a panel schedule.\nHowever, there may be a good reason why this is not allowable in the API.\nThe question is, why would you want it to be?\nThings like the IEE (Institute of Electrical Engineers) define that 25% spare capacity should be allowed at a new install; how would you know youâ€™ve reached this minimum until you add a panel and start to populate it?\nAre you asking for a panel to be effectively blocked once it has reached this maximum fill point? In which case, this would be a product of the Max number of ways (breakers) property, not the panel schedule.\nThe panel schedule used (and size) is a result of the panel configuration &ndash; single/three phase, no. of breakers.\nThe placement of Spares or spaces would then be subject to the allocation of circuits once these have been assigned to phase and load balancing has been taken in to consideration.\nIt is not just a case that the last 25% of available circuits are used, as nice an idea as that is, they could be scattered across the panel."
  },
  {
    "original_filename": "1828_change_room_level",
    "header_text": "<a name=\"4\"></a>JavaScript Debugging Console Commands",
    "local_header_href": "#a-name4ajavascript-debugging-console-commands",
    "chunk_text": "#### <a name=\"4\"></a>JavaScript Debugging Console Commands\n\nIn case you ever work with the JavaScript debugging console, you might want to take a look at \nthis css-tricks [guide to console commands](https://css-tricks.com/a-guide-to-console-commands).\n\nI gleaned a bunch of interesting hints from it."
  }
]