[
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n</head>\n\n<!---\n\n- https://forums.autodesk.com/t5/revit-api-forum/createpipeconnector-from-referenceplane/m-p/9396013\n\n- https://forums.autodesk.com/t5/revit-api-forum/auto-route-a-pipe-system-between-plumbing-fixtures/m-p/9387502\n\ntwitter:\n\nNew team name, DAS, Developer Advocacy and Support, creating a new pipe connector for a hydraulic fitting family and automatic pipe system routing in the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon https://bit.ly/referenceautoroute\n\nToday we pick up two recent MEP related discussions, on creating a new pipe connector for a hydraulic fitting family and on automatic pipe system routing, and a couple of other odd items\n&ndash; The names they are a-changin\n&ndash; Getting a <code>ReferencePlane</code> for <code>CreatePipeConnector</code>\n&ndash; Auto-routing a pipe system between plumbing fixtures\n&ndash; Handling dialogue and failure messages\n&ndash; Retrieving a geometry reference...\n\nlinkedin:\n\nNew team name, DAS, Developer Advocacy and Support, creating a new pipe connector for a hydraulic fitting family and automatic pipe system routing in the #RevitAPI \n\nhttps://bit.ly/referenceautoroute\n\nToday we pick up two recent MEP related discussions, on creating a new pipe connector for a hydraulic fitting family and on automatic pipe system routing, and a couple of other odd items:\n\n- The names they are a-changin\n- Getting a <code>ReferencePlane</code> for <code>CreatePipeConnector</code>\n- Auto-routing a pipe system between plumbing fixtures\n- Handling dialogue and failure messages\n- Retrieving a geometry reference...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "Autorouting and Reference for CreatePipeConnector",
    "local_header_href": "#autorouting-and-reference-for-createpipeconnector",
    "chunk_text": "### Autorouting and Reference for CreatePipeConnector\n\nToday, let's pick up two recent MEP related discussions, on creating a new pipe connector for a hydraulic fitting family and on automatic pipe system routing, and a couple of other odd items of interest:\n\n- [The names they are a-changin](#2)\n- [Getting a `ReferencePlane` for `CreatePipeConnector`](#3)\n- [Auto-routing a pipe system between plumbing fixtures](#4)\n- [Handling dialogue and failure messages](#5)\n- [Retrieving a geometry reference](#6)"
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "<a name=\"2\"></a>The Names They are A-Changin",
    "local_header_href": "#a-name2athe-names-they-are-a-changin",
    "chunk_text": "#### <a name=\"2\"></a>The Names They are A-Changin\n\nIn these times of accelerating change, the name of my team has changed as well.\n\nFrom now on, I now work in the Autodesk DAS team:\n\n- RDP Registered Developer Program 1987-1995\n- ADN Autodesk Developer Network 1995-2015\n- FPD Forge Partner Development 2015-2020\n- DAS Developer Advocacy and Support 2020+\n\n<center>\n<img src=\"img/fpd_das.png\" alt=\"Developer Advocacy and Support\" title=\"Developer Advocacy and Support\" width=\"600\"/> <!-- 1169 -->\n</center>"
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "<a name=\"3\"></a>Getting a ReferencePlane for CreatePipeConnector",
    "local_header_href": "#a-name3agetting-a-referenceplane-for-createpipeconnector",
    "chunk_text": "#### <a name=\"3\"></a>Getting a ReferencePlane for CreatePipeConnector\n\nI had an interesting and fruitful conversation with Edouard Vnuk in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [CreatePipeConnector from ReferencePlane](https://forums.autodesk.com/t5/revit-api-forum/createpipeconnector-from-referenceplane/m-p/9396013):\n\n**Question:** I would like to create a connector from a reference plane.\nThe `CreatePipeConnector` function requires a `PlanarFace`.\nIs there another function, or how can I transform a `ReferencePlane` into `PlanarFace`?\n\n**Answer:** The [ReferencePlane documentation sample code](https://www.revitapidocs.com/2020/e7003ec7-1dbe-50a2-fb3d-a83a5a3b5b9f.htm) shows\nhow to call GetPlane to retrieve the DB Plane.\n\nMore to the point, the CreateAirHandler SDK sample to how to use the `CreatePipeConnector` method.\n\nWhen in doubt about how to call a Revit API method, one of the first places to always consult is the collection of Revit SDK samples.\nThat step often helps and may save time and effort for you and others.\n\n**Response:** I tried several codes without success.\n\nFirst code:\n\n<pre class=\"code\">\n  Autodesk.Revit.DB.Plane plane\n    = Reference_plane.GetPlane();\n\n  ConnectorElement connector = ConnectorElement\n    .CreatePipeConnector( family_document,\n      PipeSystemType.Global, plane );\n</pre>\n\nHowever, I can't compile this code, because the parameter must be a reference of planar face, and I don't know how to get it from the plane.\n\nSecond code:\n\n<pre class=\"code\">\n  ConnectorElement connector = ConnectorElement\n    .CreatePipeConnector( family_document,\n      PipeSystemType.Global,\n      Reference_plane.GetReference() );\n</pre>\n\nThis throws an exception during execution: The reference is not a planar face. Parameter name: planarFace.\n\nThese are the user interface steps I would like to complete programmatically:\n\n<center>\n<img src=\"img/pipe_connector_ui_1.jpg\" alt=\"Pipe connector placement user interface\" title=\"Pipe connector placement user interface\" width=\"454\"/> <!-- 454 -->\n<br/>\n<img src=\"img/pipe_connector_ui_2.jpg\" alt=\"Pipe connector placement user interface\" title=\"Pipe connector placement user interface\" width=\"637\"/> <!-- 637 -->\n<br/>\n<img src=\"img/pipe_connector_ui_3.jpg\" alt=\"Pipe connector placement user interface\" title=\"Pipe connector placement user interface\" width=\"391\"/> <!-- 391 -->\n<br/>\n<img src=\"img/pipe_connector_ui_4.jpg\" alt=\"Pipe connector placement user interface\" title=\"Pipe connector placement user interface\" width=\"500\"/> <!-- 922 -->\n</center>\n\nI looked the CreateAirHandler SDK sample example.\nHowever, if I understood correctly, it creates the connectors from an extruded volume that provides the required planar faces.\n\n**Answer:** Good. I see your point.\nSuch situations arise regularly.\nYou do have a real existing surface somewhere in the model that you can mount your connector on, don't you?\nOtherwise, you are modelling something that cannot be built.\nThe existing surface is part of some BIM element geometry.\nYou can identify the appropriate element and retrieve its geometry from the document by calling its Geometry property and providing an Options object with ComputeReferences set to true.\nThen, iterate through all its surfaces to identify the one you need.\nEt voila, that surface is equipped with a reference that you can use to create the connector.\n\n**Response:** What you told me inspired me to think about it.\nI am creating a converter.\nAnd so, I create automatically families from basic geometric shapes.\nTo add my connectors that do not rest on an existing face, I artificially added a cylinder that I masked where I wanted a connector.\nHere's what I get :\n\n<center>\n<img src=\"img/pipe_connector_in_family.jpg\" alt=\"Pipe connectors in family\" title=\"Pipe connectors in family\" width=\"300\"/> <!-- 388 -->\n<p style=\"font-size: 80%; font-style:italic\">Pipe connectors in family</p>\n<img src=\"img/pipe_connector_in_project.jpg\" alt=\"Pipe connectors in project\" title=\"Pipe connectors in project\" width=\"500\"/> <!-- 1388 -->\n<p style=\"font-size: 80%; font-style:italic\">Pipe connectors in project</p>\n</center>\n\nThank you so much.\n\nMany thanks to Edouard for raising this, the in-depth discussion and sharing his clean solution!"
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "<a name=\"4\"></a>Auto-routing a Pipe System Between Plumbing Fixtures",
    "local_header_href": "#a-name4aauto-routing-a-pipe-system-between-plumbing-fixtures",
    "chunk_text": "#### <a name=\"4\"></a>Auto-routing a Pipe System Between Plumbing Fixtures\n\nThe other item I would like to pick up here is\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [auto routing a pipe system between plumbing fixtures](https://forums.autodesk.com/t5/revit-api-forum/auto-route-a-pipe-system-between-plumbing-fixtures/m-p/9387502):\n\n**Question:** I'm wondering if there is something within the API that will allow me to place plumbing fixture families and then generate a plumbing layout like you can in Revit by using the \"Create Plumbing System --> Generate Layout\" or is this something I have to do one pipe, one connector at a time?\n\n<center>\n<img src=\"img/auto_route_pipe_system_1.png\" alt=\"Select elements and click create system\" title=\"Select elements and click create system\" width=\"600\"/> <!-- 936 -->\n<p style=\"font-size: 80%; font-style:italic\">Select elements and click create system</p>\n<img src=\"img/auto_route_pipe_system_generate_placeholder_button.png\" alt=\"Generate layout button\" title=\"Generate layout button\" width=\"142\"/> <!-- 142 -->\n<p style=\"font-size: 80%; font-style:italic\">Generate layout button</p>\n<img src=\"img/auto_route_pipe_system_generated_pipes.png\" alt=\"Auto generated pipes\" title=\"Auto generated pipes\" width=\"600\"/> <!-- 1069 -->\n<p style=\"font-size: 80%; font-style:italic\">Auto generated pipes</p>\n</center>\n\n**Answer:** You\ncan [create a placeholder piping system programmatically](https://thebuildingcoder.typepad.com/blog/2011/07/mep-placeholders.html) as well.\n\nOr you can create a piping system right away.\nHere is a series of samples that create a minimal bunch of pipes for\na [rolling offset in lots of different ways](http://thebuildingcoder.typepad.com/blog/2014/01/final-rolling-offset-using-pipecreate.html).\n\n**Response:** I am assuming from your response that if I want to connect from say, a water closet to a water heater, with pipes, I will have to explicitly call PipeCreate for each pipe, find connectors, insert each fitting... and then that process over and over until they connect?\nIs there a better work flow for what I'm trying to accomplish?\nSomething similar to what is in the Revit user interface?\n\n**Answer:** The discussions I pointed out already explain everything and cover your question in full.\nActually, here are some additional relevant discussions of this topic:\n\n- [Connector, neighbour, conduit, transition](https://thebuildingcoder.typepad.com/blog/2018/03/connector-neighbour-conduit-transition.html)\n- [MEP ductwork and changing pipe direction](https://thebuildingcoder.typepad.com/blog/2019/08/mep-ductwork-and-changing-pipe-direction.html)\n\nThe short answer is simply:\n\n- You can go any way you like.\n- You can just insert the pipes, no fittings. Then, if you connect the pipe connectors, Revit will automatically select and place and connect the appropriate fittings according to your routing preferences and adjust the pipe endpoints so they fit.\n- You can just insert all the fittings, no pipes. Then, if you connect the fitting connectors, Revit will automatically place and connect the appropriate pipes between them.\n\nThat is the gist of what I learned researching and implementing the rolling offset."
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "<a name=\"5\"></a>Handling Dialogue and Failure Messages",
    "local_header_href": "#a-name5ahandling-dialogue-and-failure-messages",
    "chunk_text": "#### <a name=\"5\"></a>Handling Dialogue and Failure Messages\n\nA recurring question on how to handle dialogue and failure messages keeps popping up when driving Revit programmatically, e.g.,\non [saving families out via Revit API](https://stackoverflow.com/questions/60831658/saving-families-out-vie-revit-api):\n\n**Question:** I am collecting all the families in a project and saving them out via the API using \n\n<pre class=\"code\">\n  familyDocument.SaveAs(fileName);\n</pre>\n\nIs there a way to catch the following dialogue box and perform an action?\n\n<center>\n<img src=\"img/failure_message.png\" alt=\"Failure message\" title=\"Failure message\" width=\"479\"/> <!-- 479 -->\n</center>\n\nFor instance, record the warning and close the dialogue box?\n\n**Answer:** The Revit API offers two different mechanisms to react to and handle dialogue and failure messages:\n\n- The [DialogBoxShowing event](https://www.revitapidocs.com/2020/cb46ea4c-2b80-0ec2-063f-dda6f662948a.htm) and\n- The [Failure API](https://www.revitapidocs.com/2020/d0795bd6-f092-90f2-5c2c-3876e616454c.htm).\n\nIf all of these fail, a third mechanism is provided by the Windows API, which enables hooking into and reacting to almost any system event, including a dialogue showing.\n\nAll three approaches are discussed and compared by The Building Coder in the topic group\non [detecting and handling dialogues and failures](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.32)."
  },
  {
    "original_filename": "1831_createpipeconnector",
    "header_text": "<a name=\"6\"></a>Retrieving a Geometry Reference",
    "local_header_href": "#a-name6aretrieving-a-geometry-reference",
    "chunk_text": "#### <a name=\"6\"></a>Retrieving a Geometry Reference\n\nLet's round off with a quick question \non [getting a reference to the upper face on rebar 51](https://forums.autodesk.com/t5/revit-api-forum/get-reference-upper-on-rebar-51/m-p/9396627):\n\n**Question:** This line of code works on some rebar '51' to retrieve a reference to the upper face, but not all:\n\n<pre class=\"prettyprint\">\nvar srep = $\"{rebar51.UniqueId}:2000000:{1002000+typ}:LINEAR\";\n\nvar refr = Reference.ParseFromStableRepresentation(\n  rebar51.Document, srep );\n</pre>\n\nIs there a simpler method to get a `Reference` to the upper top face of the rebar form '51'?\n\n**Answer:** You can ask the rebar for its geometry using\nthe [Element.Geometry property](https://www.revitapidocs.com/2020/d8a55a5b-2a69-d5ab-3e1f-6cf1ee43c8ec.htm).\n\nIt takes an `Options` argument in which you can specify `ComputeReferences` = `true`.\n\nIterate over the geometry solids and their faces, pick the face that you want, e.g., based on its normal vector (pointing upwards) and vertex locations (maximal Z values), and use the reference that it comes equipped with."
  }
]