[
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- Creating a material with texture in Autodesk Revit Forge Design Automation\n  https://stackoverflow.com/questions/62297851/creating-a-material-with-texture-in-autodesk-revit-forge-design-automation\n\n- cutting off pixels exporting image\n  https://forums.autodesk.com/t5/revit-api-forum/export-image-cutting-off-edge-pixels/m-p/9578304\n  https://forums.autodesk.com/t5/revit-api-forum/export-image-is-cutting-few-pixels-from-image-corners/m-p/9346019\n\n- change level of element\n  https://thebuildingcoder.typepad.com/blog/2014/03/creating-a-sloped-floor.html#comment-4952460602\n\n- Physics is cool\n  https://www.reddit.com/r/BeAmazed/comments/gxrq8p/physics_is_cool/?utm_source=share&utm_medium=web2x\n\n<blockquote class=\"reddit-card\" data-card-created=\"1591995928\"><a href=\"https://www.reddit.com/r/BeAmazed/comments/gxrq8p/physics_is_cool/\">Physics is cool</a> from <a href=\"http://www.reddit.com/r/BeAmazed\">r/BeAmazed</a></blockquote>\n<script async src=\"//embed.redditmedia.com/widgets/platform.js\" charset=\"UTF-8\"></script>\n\n- Forge job openings:\n  As you consider your network, here are some ways to think about the qualifications for Forge open roles:\n  Experience in a cloud environment such as AWS technologies\n  Critical thinkers, problem solvers, story tellers, goal oriented, smart, curiosity, empathy \n  Get started with sharing these roles today:\n  20WD39627 – Senior Vendor Manager – San Francisco\n  20WD38934 – Localization Software Engineer – Singapore\n  20WD37407 – Senior Product Manager, Data – Montreal\n  20WD40315 – Senior Data Engineer/Architect – Novi https://autodesk.rolepoint.com/?shorturl=xcqfd#job/ahBzfnJvbGVwb2ludC1wcm9kchALEgNKb2IYgIDItNTSsAoM\n\ntwitter:\n\nCreating a material with texture in Revit and Forge, exporting image without cutting off pixels, changing level of existing element and Forge job openings with the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon https://bit.ly/creatematerialtexture\n\nA bunch of interesting discussions on creating material with texture, modifying element level, cutting off image pixels and other things\n&ndash; Creating a material with texture in Revit and Forge\n&ndash; Export image cutting off pixels\n&ndash; Change level of existing element\n&ndash; Physics is cool\n&ndash; Forge job openings...\n\nlinkedin:\n\nCreating a material with texture in Revit and Forge, exporting image without cutting off pixels, changing level of existing element and Forge job openings with the #RevitAPI \n\nhttps://bit.ly/creatematerialtexture\n\nA bunch of interesting discussions on creating material with texture, modifying element level, cutting off image pixels and other things:\n\n- Creating a material with texture in Revit and Forge\n- Export image cutting off pixels\n- Change level of existing element\n- Physics is cool\n- Forge job openings...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Creating Material Texture and Retaining Pixels",
    "local_header_href": "#creating-material-texture-and-retaining-pixels",
    "chunk_text": "### Creating Material Texture and Retaining Pixels\n\nI have been quiet now for a while in shock and grieving about violence and racism in the world.\n\nMeanwhile, a bunch of interesting discussions on creating material with texture, modifying element level, cutting off image pixels and other things:\n\n- [Creating a material with texture in Revit and Forge](#2)\n- [Export image cutting off pixels](#3)\n- [Change level of existing element](#4)\n- [Physics is cool](#5)\n- [Forge job openings](#6)"
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Creating a Material with Texture in Revit and Forge",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Creating a Material with Texture in Revit and Forge\n\nThis topic has been very much en vogue lately.\nIt came up again in the context of Forge in the StackOverflow question\non [creating a material with texture in Autodesk Revit Forge Design Automation](https://stackoverflow.com/questions/62297851/creating-a-material-with-texture-in-autodesk-revit-forge-design-automation),\nwhere [maleficca](https://stackoverflow.com/users/12469767/maleficca) very kindly shares a complete solution for both environments:\n\n**Question:** I'm currently working on some Revit API code which is running in the **Autodesk Forge Design Automation cloud solution**.\n\nBasically, I'm trying to **create a material and attach a texture to it** via the following code:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;AddTexturePath(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;asset,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;texturePath&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;asset.NumberOfConnectedProperties&nbsp;==&nbsp;0&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset.AddConnectedAsset(&nbsp;<span style=\"color:#a31515;\">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;connectedAsset&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">Asset</span>)&nbsp;asset.GetConnectedProperty(&nbsp;0&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>&nbsp;path&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyString</span>)&nbsp;connectedAsset.FindByName(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;!path.IsValidValue(&nbsp;texturePath&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">File</span>.Create(&nbsp;<span style=\"color:#a31515;\">&quot;texture.png&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texturePath&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.GetFullPath(&nbsp;<span style=\"color:#a31515;\">&quot;texture.png&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;\n&nbsp;&nbsp;}\n</pre>\n\nThis is actually working well, as the value for the texture path:\n\n<pre class=\"code\">\n  path.Value = texturePath;\n</pre>\n\nNeeds to be a reference to an existing file. I do not have this file on the cloud instance of Forge, because the path to the texture name is specified by the user when he sends the request for the Workitem.\n\nThe problem is that this sets the texture path for the material as something like this:\n\n<pre class=\"code\">\n  T:\\Aces\\Jobs\\<workitem_id>\\texture.png\n</pre>\n\nWhich is basically the working folder for the Workitem instance. This path is useless, because a material with texture path like this needs to be manually re-linked in Revit. \n\nThe perfect outcome for me would be if I could somehow map the material texture path to some user-friendly directory like `C:\\Textures\\texture.png` and it seems that the Forge instance has a `C:\\` drive present (being probably a Windows instance of some sorts), but my code runs on low privileges, so it cannot create any kind of directories or files outside the working directory.\n\nDoes somebody have any idea how this could be resolved?\nAny help would be greatly appreciated!\n\n**Answer:** Congratulations on getting to this point.\nWould you like to share the code you use to create the material and attach the texture for the Revit API add-in developer community to enjoy, either here or in a new thread in the Revit API discussion forum?\nPeople keep asking for such samples... Thank you!\n\n**Response:** Here is my own answer and code sample:\n\nAfter a whole day of research, I pretty much arrived at a satisfying solution. Just for clarity &ndash; I am going to reference to **Autodesk Forge Design Automation API for Revit**, simply as **\"Forge\"**.\n\nBasically, the code provided above is correct.\nI did not find any possible way to create a file on Forge instance, in a directory different than the Workitem working directory which is:\n\n<pre class=\"code\">\n  T:\\Aces\\Jobs\\<workitem_id>\\texture.png\n</pre>\n\nInterestingly, there is a `C:\\` drive on the Forge instance, which contains Windows, Revit and .NET Framework installations (as Forge instance is basically some sort of Windows instance with Revit installed). It is possible to enumerate a lot of these directories, but none of the ones I've tried (and I've tried a lot &ndash; mostly the most obvious, public access Windows directories like `C:\\Users\\Public`, `C:\\Program Files`, etc.) allow for creation of directories or files. This corresponds to what is stated in \"Restrictions\" area of the Forge documentation:\n\n> Your application is run with low privileges, and will not be able to freely interact with the Windows OS:\n\n> - Write access is typically restricted to the job’s working folder.\n> - Registry access is mostly restricted, writing to the registry should be avoided.\n> - Any sub-process will also be executed with low privileges.\n\nSo, after trying to save the \"dummy\" texture file somewhere on the Forge `C:\\` drive, I've found another solution &ndash; **the texture path for your texture actually does not matter.**\n\nThis is because Revit offers an alternative for re-linking your textures.\nIf you fire up Revit, you can go to File &gt; Options &gt; Rendering, and under \"Additional render appearance paths\" field, you can specify the directories on your local machine, that Revit can use to look for missing textures.\nWith these, you can do the following operations in order to have full control on creating materials on Forge:\n\n1. Send Workitem to Forge, create the materials.\n2. Create a dummy texture in working directory, with the correct file name.\n3. Attach the dummy texture file to the material.\n4. Output the resulting file (.rvt or .rfa, depending on what you're creating on Forge).\n5. Place all textures into one folder (or multiple, this doesn't matter that much).\n6. Add the directories with the textures to the Additional render appearance paths.\n7. Revit will successfully re-link all the textures to new paths.\n\nI hope someone will find this useful!\n\nAdditionally, as per Jeremy's request, I post a code sample for creating material with texture and modifying different Appearance properties in Revit by using Revit API (in C#):\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;SetAppearanceParameters(\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;project,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Material</span>&nbsp;mat,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;MaterialData&nbsp;data&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;setParameters&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;project,&nbsp;<span style=\"color:#a31515;\">&quot;Set&nbsp;material&nbsp;parameters&quot;</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setParameters.Start();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetElement</span>&nbsp;genericAsset&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;project&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetElement</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.ToElements()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Cast&lt;<span style=\"color:#2b91af;\">AppearanceAssetElement</span>&gt;().Where(&nbsp;i\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&gt;&nbsp;i.Name.Contains(&nbsp;<span style=\"color:#a31515;\">&quot;Generic&quot;</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.FirstOrDefault();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetElement</span>&nbsp;newAsset&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;genericAsset.Duplicate(&nbsp;data.Name&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;=&nbsp;newAsset.Id;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>&nbsp;editAsset&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>(&nbsp;project&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset&nbsp;=&nbsp;editAsset.Start(&nbsp;newAsset.Id&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;assetProperty&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset[&nbsp;<span style=\"color:#a31515;\">&quot;generic_diffuse&quot;</span>&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SetColor(&nbsp;editableAsset,&nbsp;data.MaterialAppearance.Color&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SetGlossiness(&nbsp;editableAsset,&nbsp;data.MaterialAppearance.Gloss&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SetReflectivity(&nbsp;editableAsset,&nbsp;data.MaterialAppearance.Reflectivity&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SetTransparency(&nbsp;editableAsset,&nbsp;data.MaterialAppearance.Transparency&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;data.MaterialAppearance.Texture&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;&amp;&nbsp;data.MaterialAppearance.Texture.Length&nbsp;!=&nbsp;0&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AddTexturePath(&nbsp;assetProperty,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:maroon;\">$@&quot;C:\\</span>{data.MaterialIdentity.Manufacturer}<span style=\"color:maroon;\">\\textures\\</span>{data.MaterialAppearance.Texture}<span style=\"color:maroon;\">&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editAsset.Commit(&nbsp;<span style=\"color:blue;\">true</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setParameters.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;SetTransparency(\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;transparency&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDouble</span>&nbsp;genericTransparency&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset[&nbsp;<span style=\"color:#a31515;\">&quot;generic_transparency&quot;</span>&nbsp;]\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDouble</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;genericTransparency.Value&nbsp;=&nbsp;Convert.ToDouble(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transparency&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;SetReflectivity(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;reflectivity&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDouble</span>&nbsp;genericReflectivityZero\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyDouble</span>)&nbsp;editableAsset[&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;generic_reflectivity_at_0deg&quot;</span>&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;genericReflectivityZero.Value&nbsp;=&nbsp;Convert.ToDouble(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reflectivity&nbsp;)&nbsp;/&nbsp;100;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDouble</span>&nbsp;genericReflectivityAngle\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyDouble</span>)&nbsp;editableAsset[\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;generic_reflectivity_at_90deg&quot;</span>&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;genericReflectivityAngle.Value&nbsp;=&nbsp;Convert.ToDouble(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reflectivity&nbsp;)&nbsp;/&nbsp;100;\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;SetGlossiness(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;gloss&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDouble</span>&nbsp;glossProperty&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyDouble</span>)&nbsp;editableAsset[&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;generic_glossiness&quot;</span>&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;glossProperty.Value&nbsp;=&nbsp;Convert.ToDouble(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gloss&nbsp;)&nbsp;/&nbsp;100;\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;SetColor(\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>[]&nbsp;color&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyDoubleArray4d</span>&nbsp;genericDiffuseColor&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyDoubleArray4d</span>)&nbsp;editableAsset[&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;generic_diffuse&quot;</span>&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Color</span>&nbsp;newColor&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Color</span>(&nbsp;(<span style=\"color:blue;\">byte</span>)&nbsp;color[&nbsp;0&nbsp;],&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(<span style=\"color:blue;\">byte</span>)&nbsp;color[&nbsp;1&nbsp;],&nbsp;(<span style=\"color:blue;\">byte</span>)&nbsp;color[&nbsp;2&nbsp;]&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;genericDiffuseColor.SetValueAsColor(&nbsp;newColor&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;AddTexturePath(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;asset,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;texturePath&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;asset.NumberOfConnectedProperties&nbsp;==&nbsp;0&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset.AddConnectedAsset(&nbsp;<span style=\"color:#a31515;\">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;connectedAsset&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">Asset</span>)&nbsp;asset.GetConnectedProperty(&nbsp;0&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;prop&nbsp;=&nbsp;connectedAsset.FindByName(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>&nbsp;path&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AssetPropertyString</span>)&nbsp;connectedAsset.FindByName(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;fileName&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.GetFileName(&nbsp;texturePath&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">File</span>.Create(&nbsp;fileName&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;texturePath&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.GetFullPath(&nbsp;fileName&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;\n&nbsp;&nbsp;}\n</pre>\n\nHopefully it will come in handy to someone in the future!\n\nAlso, a huge thanks for The Building Coder; it has saved me a lot of hassle in my work with Revit API and enabled to create a lot of cool stuff!\n\nA great thanks back to maleficca for kindly sharing the two solutions, both for Forge and the Revit desktop API!"
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Export Image Cutting off Pixels",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Export Image Cutting off Pixels\n\nThis query just came up again in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [export image cutting off edge pixels](https://forums.autodesk.com/t5/revit-api-forum/export-image-cutting-off-edge-pixels/m-p/9578304):\n\n**Question:** I'm trying to export family type images from a family, but I'm getting the edge pixels cut off in my exported images.\n\nHere is the original image:\n\n<center>\n<img src=\"img/image_export_cutting_pixels_original.png\" alt=\"Original image\" title=\"Original image\" width=\"155\"/> <!-- 223 -->\n</center>\n\nThis is what comes out:\n\n<center>\n<img src=\"img/image_export_cutting_pixels_exported.png\" alt=\"Exported image\" title=\"Exported image\" width=\"150\"/> <!-- 150 -->\n</center>\n\nThis is what I currently have for my export image options\n\n<pre class=\"code\">\n&nbsp;&nbsp;img&nbsp;=&nbsp;ImageExportOptions()\n&nbsp;&nbsp;img.ZoomType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ZoomFitType</span>.FitToPage\n&nbsp;&nbsp;img.PixelSize&nbsp;=&nbsp;size\n&nbsp;&nbsp;img.ImageResolution&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageResolution</span>.DPI_150\n&nbsp;&nbsp;img.FitDirection&nbsp;=&nbsp;<span style=\"color:#2b91af;\">FitDirectionType</span>.Vertical\n&nbsp;&nbsp;img.ExportRange&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ExportRange</span>.SetOfViews\n&nbsp;&nbsp;img.SetViewsAndSheets(&nbsp;viewIds&nbsp;)\n&nbsp;&nbsp;img.HLRandWFViewsFileType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageFileType</span>.PNG\n&nbsp;&nbsp;img.FilePath&nbsp;=&nbsp;filepath\n&nbsp;&nbsp;img.ShadowViewsFileType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageFileType</span>.PNG\n</pre>\n\nA solution was provided by [alexpaduroiu](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/7761409) in a previous conversation\non why [export image is cutting a few pixels from image corners](https://forums.autodesk.com/t5/revit-api-forum/export-image-is-cutting-few-pixels-from-image-corners/m-p/9346019):\n\n**Question:** I have a small problem regarding `Decoument.ExportImage(ImageExportOptions options)`.\n\nI am trying to export a set of drafting views, but somehow the generated images cut the views edges.\n\nA sample image:\n\n<center>\n<img src=\"img/image_export_cutting_pixels_incomplete.png\" alt=\"Incomplete image\" title=\"Incomplete image\" width=\"400\"/> <!-- 500 -->\n</center>\n\nThis image has the bottom part not visible at all:\n\n<center>\n<img src=\"img/image_export_cutting_pixels_incomplete2.png\" alt=\"Incomplete image\" title=\"Incomplete image\" width=\"279\"/> <!-- 279 -->\n</center>\n\nThe cut is very small but very frustrating because I can't make it a whole or even offset the element to fit the images.\n\nImage Export Options used:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ImageExportOptions</span>&nbsp;imgExportOpts&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ImageExportOptions</span>()\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ZoomType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ZoomFitType</span>.FitToPage,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PixelSize&nbsp;=&nbsp;500,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FilePath&nbsp;=&nbsp;rbrImagesDirectory&nbsp;+&nbsp;<span style=\"color:maroon;\">@&quot;\\&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FitDirection&nbsp;=&nbsp;<span style=\"color:#2b91af;\">FitDirectionType</span>.Vertical,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HLRandWFViewsFileType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageFileType</span>.PNG,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ShadowViewsFileType&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageFileType</span>.PNG,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ImageResolution&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ImageResolution</span>.DPI_72,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ShouldCreateWebSite&nbsp;=&nbsp;<span style=\"color:blue;\">false</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;};\n \n  imgExportOpts.ExportRange&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ExportRange</span>.SetOfViews;\n</pre>\n\nI have tried to modify `FitDirectionType.Horizontal` and this makes it worse than it is now by cutting the bottom portion even more; in that case, for the first image, the bottom part of the bar is not visible at all.\n\nThe image doesn't have such a big cut in the edges but it will be nice to have some spaces there or at least to see the parts &nbsp; :-)\n\nIs there any way to zoom out the element or move it in order to be arranged better in image?\n\n**Answer:** Well, I have solved the problem!\n\nThe problem was with the drafting view I was trying to export. After creating a group of details in the drafting view, somehow the outline of the view wasn't big enough to include my details. don't know for sure why, but what I have done to resolve the problem was the following:\n\n<pre class=\"code\">\n&nbsp;&nbsp;drafting.CropBoxActive&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;drafting.CropBoxVisible&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n\n<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;ExtendViewCrop(\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;drafting,\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Group</span>&nbsp;detail&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;crop&nbsp;=&nbsp;(drafting&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>\n&nbsp;&nbsp;&nbsp;&nbsp;?&nbsp;drafting.CropBox\n&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;<span style=\"color:blue;\">null</span>);\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;crop&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;||&nbsp;crop.Max&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;||&nbsp;crop.Min&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>\n&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;crop.Transform&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;||&nbsp;detail&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;detailBox&nbsp;=&nbsp;detail.get_BoundingBox(&nbsp;drafting&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;extendedCrop&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>();\n&nbsp;&nbsp;extendedCrop.Transform&nbsp;=&nbsp;crop.Transform;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;detailBox&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;||&nbsp;detailBox.Max&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>\n&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;detailBox.Min&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;extendedCrop.Max&nbsp;=&nbsp;detailBox.Max\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;(extendedCrop.Transform.BasisX\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;extendedCrop.Transform.BasisY&nbsp;/&nbsp;2)&nbsp;*&nbsp;0.03;\n \n&nbsp;&nbsp;extendedCrop.Min&nbsp;=&nbsp;detailBox.Min\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;(-extendedCrop.Transform.BasisX\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;-extendedCrop.Transform.BasisY&nbsp;/&nbsp;2)&nbsp;*&nbsp;0.03;\n \n&nbsp;&nbsp;drafting.CropBox&nbsp;=&nbsp;extendedCrop;\n}\n</pre>\n\nSo basically, extending the view crops max and min on their direction with a small value so the detail will fit in my drafting.\n\nI am sure that there are lots of other better options doing this, but for now it did the trick.\n\nOf course I am open to more solutions &nbsp; :-)\n\nMany thanks to alexpaduroiu for this clear solution."
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Change Level of Existing Element",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Change Level of Existing Element\n\nAngelo Mastroberardino brought up this question in\nhis [comment](https://thebuildingcoder.typepad.com/blog/2014/03/creating-a-sloped-floor.html#comment-4952460602)\non [creating a sloped floor](https://thebuildingcoder.typepad.com/blog/2014/03/creating-a-sloped-floor.html):\n\n**Question:** Is it possible to re-set the reference Level of a Floor, once it is created ?\n\n**Answer:**  In general, the `Level` property is read-only and thus cannot be set after an element has been created.\nIt is specified during creation only and cannot be modified later.\n\nHere are some posts on levels, both general level handling issues and workarounds to set the level property on certain specific element types:\n\n- [Retrieve levels sorted by elevation](https://thebuildingcoder.typepad.com/blog/2014/11/webgl-goes-mobile-and-sorted-level-retrieval.html#3)\n- [Family instances lacking or with invalid level property](https://thebuildingcoder.typepad.com/blog/2011/01/family-instance-missing-level-property.html)\n- [Changing the level of a floor](https://thebuildingcoder.typepad.com/blog/2019/04/set-floor-level-and-use-ipc-for-disentanglement.html#3)\n- [Calculate a level for an element lacking the property](https://thebuildingcoder.typepad.com/blog/2019/03/assigning-a-level-to-an-element-missing-it.html)\n- A solution to [change the level of an existing room](https://thebuildingcoder.typepad.com/blog/2020/03/panel-schedule-slots-and-change-room-level.html)"
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Physics is Cool",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> Physics is Cool\n\nA very nice and surprising [physics experiment to try out at home](https://www.reddit.com/r/BeAmazed/comments/gxrq8p/physics_is_cool):\n\n<center>\n<!--\n<blockquote class=\"reddit-card\">\n<a href=\"https://www.reddit.com/r/BeAmazed/comments/gxrq8p/physics_is_cool/\">Physics is cool</a> \n</blockquote>\n<script async src=\"//embed.redditmedia.com/widgets/platform.js\" charset=\"UTF-8\"></script>\n-->\n\n<a href=\"https://www.reddit.com/r/BeAmazed/comments/gxrq8p/physics_is_cool\">\n<img src=\"img/cool_physics.png\" alt=\"Physics is cool\" title=\"Physics is cool\" width=\"125\"/> <!-- 125 -->\n</a>\n\n</center>"
  },
  {
    "original_filename": "1850_material_level_pixel",
    "header_text": "Forge Job Openings",
    "local_header_href": "#6",
    "chunk_text": "####<a name=\"6\"></a> Forge Job Openings\n\nAre you a critical thinker, problem solver, story teller, goal oriented, smart, curios, empathic, with experience in a cloud environment such as AWS?\n\nIf so, would you like to consider applying for a job in the Forge team?\n\n- [20WD39627 – Senior Vendor Manager – San Francisco](https://rolp.co/SS7ji)\n- [20WD38934 &ndash; Localization Software Engineer &ndash; Singapore](https://rolp.co/4Obwi)\n- [20WD37407 &ndash; Senior Product Manager, Data &ndash; Montreal](https://rolp.co/Q6cUi)\n- [20WD40315 &ndash; Senior Data Engineer/Architect &ndash; Novi ](https://rolp.co/pVKii)\n\nGood luck applying for one of these or the many other opportunities that you can find all over the world in\nthe [Autodesk career site](https://www.autodesk.com/careers)!"
  }
]