[
  {
    "original_filename": "1852_sect_box_2_view_crop",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- Set View Cropbox to a Section Box\n  https://forums.autodesk.com/t5/revit-api-forum/set-view-cropbox-to-a-section-box/m-p/9600049\n\ntwitter:\n\nTwo beautiful Revit API solutions to set view crop to section box and access room boundaries and intersections in linked models in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon https://bit.ly/crop2sectionbox\n\nTwo beautiful Revit API solutions to \n&ndash; Set view crop to section box and \n&ndash; Access room boundaries and intersections in linked models...\n\nlinkedin:\n\nTwo beautiful Revit API solutions to set view crop to section box and access room boundaries and intersections in linked models in the #RevitAPI\n\nhttps://bit.ly/crop2sectionbox\n\n- Set view crop to section box \n- Access room boundaries and intersections in linked models...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1852_sect_box_2_view_crop",
    "header_text": "Section to Crop, Linked Boundary and Intersection",
    "local_header_href": "#section-to-crop-linked-boundary-and-intersection",
    "chunk_text": "### Section to Crop, Linked Boundary and Intersection\n\nLet's wrap up this week by highlighting two beautiful \n[Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) solutions by \nRichard [RPThomas108](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) Thomas,\nwho continues sharing new ones at an impressive pace:\n\n- [Set view crop to section box](#2)\n- [Room boundaries and intersections in linked models](#3)\n\nBefore diving into those, here is a very nice [freecodecamp](https://www.freecodecamp.org/) quote of the week:\n\n> <i>People worry that computers will get too smart and take over the world.\nThe real problem is that computers are too stupid and they already have taken over the world &ndash; Pedro Domingos</i>"
  },
  {
    "original_filename": "1852_sect_box_2_view_crop",
    "header_text": "Set View Crop to Section Box",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Set View Crop to Section Box\n\nThe main result for today is Richard's solution to\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [setting view cropbox to a section box](https://forums.autodesk.com/t5/revit-api-forum/set-view-cropbox-to-a-section-box/m-p/9600049),\noriginally asked six years ago, in 2014, and now finally resolved:\n\n**Question:** A simple question: how do I set a 3D view crop box to match (the outer corners of) a section box?\n\n**Answer:** The Building Coder discussed how\nto [set view section box to match scope box](http://thebuildingcoder.typepad.com/blog/2012/08/set-view-section-box-to-match-scope-box.html).\n\nIn this different situation, the two boxes have different coordinate systems, so one has to transformed into the other.\nAlso consider below that the maximum and minimum points of the section box are not enough alone to properly frame the section box with a crop box.\nIf you transform P1 and P2 below from the coordinate space of the section box into the coordinate space of the view, you would end up with the red box.\nYou need to know the missing corners; then you can transform all of the eight corner points into the coordinate space of the view.\nYou then find the max/min `XYZ` from those and set crop box to green rectangle:\n\n<center>\n<img src=\"img/rpt_set_view_crop_to_section_box_1.png\" alt=\"Set view crop to section box\" title=\"Set view crop to section box\" width=\"500\"/> <!-- 761 -->\n</center>\n\nI wrote this extension method for that:\n\n<pre class=\"code\">\n&lt;Extension()&gt;\n<span style=\"color:blue;\">Public</span>&nbsp;<span style=\"color:blue;\">Sub</span>&nbsp;AdjustCropToSectionBox(View3D&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">View3D</span>)\n&nbsp;&nbsp;<span style=\"color:green;\">&#39;View3D&nbsp;crop&nbsp;can&#39;t&nbsp;have&nbsp;a&nbsp;shape&nbsp;assigned&nbsp;and&nbsp;can&#39;t&nbsp;be&nbsp;split</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;View3D.CropBoxActive&nbsp;=&nbsp;<span style=\"color:blue;\">False</span>&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;View3D.CropBoxActive&nbsp;=&nbsp;<span style=\"color:blue;\">True</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;View3D.IsSectionBoxActive&nbsp;=&nbsp;<span style=\"color:blue;\">False</span>&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Exit</span>&nbsp;<span style=\"color:blue;\">Sub</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;CropBox&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;=&nbsp;View3D.CropBox\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;SectionBox&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;=&nbsp;View3D.GetSectionBox\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;T&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;=&nbsp;CropBox.Transform\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Corners&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>()&nbsp;=&nbsp;BBCorners(SectionBox,&nbsp;T)\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MinX&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Min(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.X)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MinY&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Min(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.Y)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MinZ&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Min(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.Z)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MaxX&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Max(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.X)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MaxY&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Max(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.Y)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MaxZ&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;Corners.Max(<span style=\"color:blue;\">Function</span>(j)&nbsp;j.Z)\n \n&nbsp;&nbsp;CropBox.Min&nbsp;=&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(MinX,&nbsp;MinY,&nbsp;MinZ)\n&nbsp;&nbsp;CropBox.Max&nbsp;=&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(MaxX,&nbsp;MaxY,&nbsp;MaxZ)\n \n&nbsp;&nbsp;View3D.CropBox&nbsp;=&nbsp;CropBox\n<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Sub</span>\n \n<span style=\"color:blue;\">Private</span>&nbsp;<span style=\"color:blue;\">Function</span>&nbsp;BBCorners(\n&nbsp;&nbsp;SectionBox&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>,\n&nbsp;&nbsp;T&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Transform</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>()\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;SBMx&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;SectionBox.Max\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;SBMn&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;SectionBox.Min\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Btm_LL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;SBMn&nbsp;<span style=\"color:green;\">&#39;Lower&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Btm_LR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMx.X,&nbsp;SBMn.Y,&nbsp;SBMn.Z)&nbsp;<span style=\"color:green;\">&#39;Lower&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Btm_UL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMn.X,&nbsp;SBMx.Y,&nbsp;SBMn.Z)&nbsp;<span style=\"color:green;\">&#39;Upper&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Btm_UR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMx.X,&nbsp;SBMx.Y,&nbsp;SBMn.Z)&nbsp;<span style=\"color:green;\">&#39;Upper&nbsp;Right</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Top_UR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;SBMx&nbsp;<span style=\"color:green;\">&#39;Upper&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Top_UL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMn.X,&nbsp;SBMx.Y,&nbsp;SBMx.Z)&nbsp;<span style=\"color:green;\">&#39;Upper&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Top_LR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMx.X,&nbsp;SBMn.Y,&nbsp;SBMx.Z)&nbsp;<span style=\"color:green;\">&#39;Lower&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Top_LL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(SBMn.X,&nbsp;SBMn.Y,&nbsp;SectionBox.Max.Z)&nbsp;<span style=\"color:green;\">&#39;Lower&nbsp;Left</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Out&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>()&nbsp;=&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(7)&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;Btm_LL,&nbsp;Btm_LR,&nbsp;Btm_UL,&nbsp;Btm_UR,\n&nbsp;&nbsp;&nbsp;&nbsp;Top_UR,&nbsp;Top_UL,&nbsp;Top_LR,&nbsp;Top_LL}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">For</span>&nbsp;i&nbsp;=&nbsp;0&nbsp;<span style=\"color:blue;\">To</span>&nbsp;Out.Length&nbsp;-&nbsp;1\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">&#39;Transform&nbsp;bounding&nbsp;box&nbsp;corords&nbsp;to&nbsp;model&nbsp;coords</span>\n&nbsp;&nbsp;&nbsp;&nbsp;Out(i)&nbsp;=&nbsp;SectionBox.Transform.OfPoint(Out(i))\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">&#39;Transform&nbsp;bounding&nbsp;box&nbsp;coords&nbsp;to&nbsp;view&nbsp;coords</span>\n&nbsp;&nbsp;&nbsp;&nbsp;Out(i)&nbsp;=&nbsp;T.Inverse.OfPoint(Out(i))\n&nbsp;&nbsp;<span style=\"color:blue;\">Next</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;Out\n<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n</pre>\n\nIt is also worth considering that the extents of the section box may not be appropriate for how you wish to crop the view.\nThe section box below is relatively tight on the wall elements but due to the viewing angle there is a lot of spare space to the right.\nWhen you print that on a sheet it will not be evident why the view content is off centre and what the extra space is for:\n\n<center>\n<img src=\"img/rpt_set_view_crop_to_section_box_2.png\" alt=\"Set view crop to section box\" title=\"Set view crop to section box\" width=\"400\"/> <!-- 593 -->\n</center>\n\n**Response:** This solution worked great; I translated to C# and have posted it here for C# coders:\n \n<pre class=\"code\">\n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;AdjustViewCropToSectionBox(&nbsp;\n&nbsp;&nbsp;<span style=\"color:green;\">/*this*/</span>&nbsp;<span style=\"color:#2b91af;\">View3D</span>&nbsp;view&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;!view.IsSectionBoxActive&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;!view.CropBoxActive&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;view.CropBoxActive&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;CropBox&nbsp;=&nbsp;view.CropBox;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;SectionBox&nbsp;=&nbsp;view.GetSectionBox();\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;T&nbsp;=&nbsp;CropBox.Transform;\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Corners&nbsp;=&nbsp;BBCorners(&nbsp;SectionBox,&nbsp;T&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MinX&nbsp;=&nbsp;Corners.Min(&nbsp;j&nbsp;=&gt;&nbsp;j.X&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MinY&nbsp;=&nbsp;Corners.Min(&nbsp;j&nbsp;=&gt;&nbsp;j.Y&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MinZ&nbsp;=&nbsp;Corners.Min(&nbsp;j&nbsp;=&gt;&nbsp;j.Z&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MaxX&nbsp;=&nbsp;Corners.Max(&nbsp;j&nbsp;=&gt;&nbsp;j.X&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MaxY&nbsp;=&nbsp;Corners.Max(&nbsp;j&nbsp;=&gt;&nbsp;j.Y&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MaxZ&nbsp;=&nbsp;Corners.Max(&nbsp;j&nbsp;=&gt;&nbsp;j.Z&nbsp;);\n&nbsp;&nbsp;CropBox.Min&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;MinX,&nbsp;MinY,&nbsp;MinZ&nbsp;);\n&nbsp;&nbsp;CropBox.Max&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;MaxX,&nbsp;MaxY,&nbsp;MaxZ&nbsp;);\n&nbsp;&nbsp;view.CropBox&nbsp;=&nbsp;CropBox;\n}\n \n<span style=\"color:blue;\">private</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>[]&nbsp;BBCorners(&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;SectionBox,&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;T&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;sbmn&nbsp;=&nbsp;SectionBox.Min;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;sbmx&nbsp;=&nbsp;SectionBox.Max;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;Btm_LL&nbsp;=&nbsp;sbmn;&nbsp;<span style=\"color:green;\">//&nbsp;Lower&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Btm_LR&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmx.X,&nbsp;sbmn.Y,&nbsp;sbmn.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Lower&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Btm_UL&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmn.X,&nbsp;sbmx.Y,&nbsp;sbmn.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Upper&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Btm_UR&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmx.X,&nbsp;sbmx.Y,&nbsp;sbmn.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Upper&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;Top_UR&nbsp;=&nbsp;sbmx;&nbsp;<span style=\"color:green;\">//&nbsp;Upper&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Top_UL&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmn.X,&nbsp;sbmx.Y,&nbsp;sbmx.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Upper&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Top_LR&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmx.X,&nbsp;sbmn.Y,&nbsp;sbmx.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Lower&nbsp;Right</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Top_LL&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;sbmn.X,&nbsp;sbmn.Y,&nbsp;sbmx.Z&nbsp;);&nbsp;<span style=\"color:green;\">//&nbsp;Lower&nbsp;Left</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;Out&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>[&nbsp;8&nbsp;]&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;Btm_LL,&nbsp;Btm_LR,&nbsp;Btm_UL,&nbsp;Btm_UR,\n&nbsp;&nbsp;&nbsp;&nbsp;Top_UR,&nbsp;Top_UL,&nbsp;Top_LR,&nbsp;Top_LL&nbsp;};\n&nbsp;&nbsp;<span style=\"color:blue;\">for</span>(&nbsp;<span style=\"color:blue;\">int</span>&nbsp;i&nbsp;=&nbsp;0,&nbsp;loopTo&nbsp;=&nbsp;Out.Length&nbsp;-&nbsp;1;&nbsp;i&nbsp;&lt;=&nbsp;loopTo;&nbsp;i++&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Transform&nbsp;bounding&nbsp;box&nbsp;coords&nbsp;to&nbsp;model&nbsp;coords</span>\n&nbsp;&nbsp;&nbsp;&nbsp;Out[&nbsp;i&nbsp;]&nbsp;=&nbsp;SectionBox.Transform.OfPoint(&nbsp;Out[&nbsp;i&nbsp;]&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Transform&nbsp;bounding&nbsp;box&nbsp;coords&nbsp;to&nbsp;view&nbsp;coords</span>\n&nbsp;&nbsp;&nbsp;&nbsp;Out[&nbsp;i&nbsp;]&nbsp;=&nbsp;T.Inverse.OfPoint(&nbsp;Out[&nbsp;i&nbsp;]&nbsp;);\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;Out;\n}\n</pre>\n\nMany thanks to Richard and Frank for the solution and the C# translation.\n\nI added the new method `AdjustViewCropToSectionBox`\nto [release 2021.0.149.2](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2021.0.149.2)\nof [The Building Coder Samples](https://github.com/jeremytammik/the_building_coder_samples),\ncf. the [diff to the previous version](https://github.com/jeremytammik/the_building_coder_samples/compare/2021.0.149.1...2021.0.149.2)."
  },
  {
    "original_filename": "1852_sect_box_2_view_crop",
    "header_text": "Room Boundaries and Intersections in Linked Models",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Room Boundaries and Intersections in Linked Models\n\nYet another beautiful solution by Richard to determine the column finish area within a room of columns residing partially inside and partially outside the room interior.\n\nTrickier still, this includes handling of columns residing in linked files, copying the relevant elements into the main project file to retrieve the room boundaries there.\n\nNote that there seem to be problems retrieving room boundaries from rooms in linked files, so this transformation process can come in handy in all sorts of similar situations.\n\nSome of the recent issues that this solution helps resolve include:\n\n- Intersection in linked models\n- Transformation from linked into main host project and vice versa\n- Room boundary retrieval does not work well with linked models\n\nThe question was raised in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [how to calculate the column finish area of room](https://forums.autodesk.com/t5/revit-api-forum/how-to-calculate-the-column-finish-area-of-room/m-p/9576200):\n\n**Question:** We want to calculate the column finish area of columns in a room with columns present half inside the room and half outside; we have to ignore the outside finish area and only want the area which comes inside the room boundary.\n\nThis screen snapshot shows a typical situation:\n\n<center>\n<img src=\"img/column_finish_area_1.png\" alt=\"Column finish area\" title=\"Column finish area\" width=\"500\"/> <!-- 538 -->\n</center>\n\n**Answer:** Here is one possible approach:\n\n- Get column base curve.\n- Get the room bounding segments and their curves.\n- Get the intersections between column curves and the room curves.\n- Calculate circumference of the column curve lying in the room boundary.\n- Using room height calculate the area.\n\nPossibly slightly more straightforward: the `BoundarySegment` class has an `ElementID` property that identifies the `Element` that generated the boundary segment.\n\nIf you review these in RevitLookup, you get the segment length measured to the centre of the wall.\nThis length however likely depends on how the `GetBoundarySegments` is called, i.e.:\n\nUse `SpatialElementBoundaryOptions` `SpatialElementBoundaryLocation` `=` `Finish` instead of center; then you may get the curve length for each face which you can multiply with the room height.\n\nAlternatively, if you get the lines only to the centre of the wall, you can get the wall thickness and subtract one half of it from the line length.\n\n**Response:** We are trying to follow that approach to get the columns, but from the column edges we are not able to calculate the exact overlapping part with the room interior for the column part inside the room.\n\nIn our case, we don't know exactly how large a portion of the column is inside and how much is outside.\nAlso, the room is present in the active document and the column is in a linked document. \nHow can we get the column edges that come inside the room?\n\n**Answer:** That is slightly more challenging, but the same principles as noted previously apply.\n\nSummary of the code below:\n\n- Get solid from room using `Room.ClosedShell`\n- Transform solid to coord space of link containing columns using `SolidUtils.CreateTransformed`\n- Find the columns intersecting the transformed solid using `ElementIntersectsSolidFilter`\n- Copy each matching column back to the main doc using `ElementTransformUtils.CopyElements`\n- Measure the boundaries\n- Roll back the transaction \n\n<pre class=\"code\">\n  Private Function TObj75(ByVal commandData As Autodesk.Revit.UI.ExternalCommandData,\n    ByRef message As String, ByVal elements As Autodesk.Revit.DB.ElementSet) As Result\n  \n    If commandData.Application.ActiveUIDocument Is Nothing Then Return Result.Cancelled Else\n    Dim UIDoc As UIDocument = commandData.Application.ActiveUIDocument\n    Dim Doc As Document = UIDoc.Document\n  \n    Dim R As Reference = Nothing\n    Try\n      R = UIDoc.Selection.PickObject(Selection.ObjectType.Element, \"Pick a room any room.\")\n    Catch ex As Exception\n    End Try\n    If R Is Nothing Then Return Result.Cancelled Else\n  \n    Dim Room As Room = TryCast(Doc.GetElement(R), Room)\n    If Room Is Nothing Then Return Result.Cancelled Else\n  \n    Dim GeomEl As GeometryElement = Room.ClosedShell\n    Dim S As Solid = GeomEl(0) 'Assume single solid for brevity\n  \n    Dim FEClnk As New FilteredElementCollector(Doc)\n    Dim ECFlnk As New ElementClassFilter(GetType(RevitLinkInstance))\n    Dim Lnk As List(Of RevitLinkInstance) = FEClnk.WherePasses(ECFlnk).ToElements.Cast(Of RevitLinkInstance).ToList\n    Dim LinkDoc As Document = Lnk(0).GetLinkDocument() 'Assume single link containing columns for brevity\n  \n    Dim SolTransformed As Solid = SolidUtils.CreateTransformed(S, Lnk(0).GetTransform.Inverse)\n    'The solid in the coord system of the link\n    Dim ElintS As New ElementIntersectsSolidFilter(SolTransformed)\n    Dim ECF As New ElementCategoryFilter(BuiltInCategory.OST_StructuralColumns)\n    Dim LandF As New LogicalAndFilter(ElintS, ECF)\n    Dim FEC As New FilteredElementCollector(LinkDoc)\n    Dim Els As List(Of ElementId) = FEC.WherePasses(LandF).ToElementIds\n  \n    Using tx As New Transaction(Doc, \"Copy\")\n      If tx.Start = TransactionStatus.Started Then\n  \n        Dim NewIDs As List(Of ElementId) = ElementTransformUtils.CopyElements(LinkDoc, Els, Doc, Lnk(0).GetTransform, Nothing)\n        Dim Ops As New SpatialElementBoundaryOptions() With {.SpatialElementBoundaryLocation = SpatialElementBoundaryLocation.Finish}\n  \n        Dim BoundSegs As IList(Of IList(Of BoundarySegment)) = Room.GetBoundarySegments(Ops)\n        For i = 0 To BoundSegs.Count - 1\n          Dim SegLst As IList(Of BoundarySegment) = BoundSegs(i)\n          Debug.WriteLine(\"List: \" & CStr(i + 1)) 'List 0' just doesn't sound right\n  \n          For ix = 0 To SegLst.Count - 1\n            Dim Seg As BoundarySegment = SegLst(ix)\n            If NewIDs.Contains(Seg.ElementId) = False Then Continue For Else\n  \n            Debug.WriteLine(CStr(Seg.ElementId.IntegerValue) & \", \" & (Seg.GetCurve.Length * 304.8).ToString(\"F1\"))\n  \n            'Tried below to see what .LinkedElementId represented (not apparent)\n            'Debug.WriteLine(CStr(Seg.LinkElementId.IntegerValue) & \",\" & Seg.GetCurve.Length & \"FromLink\")\n          Next\n        Next\n  \n        tx.RollBack()\n      End If\n    End Using\n  \n  End Function\n</pre>\n\nProof of concept:\n\n<center>\n<img src=\"img/column_finish_area_2.png\" alt=\"Column finish area\" title=\"Column finish area\" width=\"300\"/> <!-- 464 -->\n</center>\n\nResults:\n\n<pre>\n  List: 1\n  427532, 400.0\n  427532, 750.0\n  427532, 400.0\n  427536, 275.0\n  427536, 200.0\n  427534, 200.0\n  427534, 750.0\n  427534, 200.0\n</pre>\n\nThis technique was first developed in the user interface. \nAs Revit users, we had long applied this technique in the UI, i.e., tab into a linked element, copy it to the clipboard and paste it to the same place within the host document.\n\nThe `ElementTransformUtils` is definitely a powerful feature of the API which sometimes gets overlooked in terms of how it can be applied to solve problems.\n\nBy the way, this solution simultaneously answers a number of other recent forum issues involving intersections and room boundaries in linked documents, including a previous thread\non [how to find the rooms geometry adjacent to walls](https://forums.autodesk.com/t5/revit-api-forum/how-to-find-the-rooms-geometry-adjacent-to-walls-in-revit-api/m-p/9576146),\nwhere an analogous approach can be applied.\n\nIt also shows once again how important and useful it is to fully develop and optimise a solution manually in the user interface before beginning to address it programmatically.\n\nMany thanks again to Richard for these nice solutions.\nYou are helping elevate to Revit developer community to a new level!"
  }
]