[
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- Asset Keyword Access\n  https://app.slack.com/client/T02NW42JD/C0SR6NAP8\n  Ryuji Ogasawara, RuoQian Lu and Joe Qiao \n\n- need to regen:\n  Set Different Materials to Parts of a Wall\n  https://forums.autodesk.com/t5/revit-api-forum/set-different-materials-to-parts-of-a-wall/m-p/10427403\n\n- need to regen:\n  Modifying group in api results in duplicate group\n  https://forums.autodesk.com/t5/revit-api-forum/modifying-group-in-api-results-in-duplicate-group/m-p/10374430\n\n- New post on Boost Your BIM\n  Topo From Lines now in the free Revit tool set\n  by harrymattison\n  This tool is an\"oldie but goodie\" that lets you create and update a toposurface from a set of model lines. A new version for 2022 was recently requested, so I added it to the Terrific Tool project and created a 2022 build. You can download the current installer here and if you like code, that is here\n  https://bitbucket.org/BoostYourBIM/boostyourbimterrifictools/src/master/BoostYourBIMTerrificTools/TopoFromLines.cs\n  https://bitbucket.org/BoostYourBIM/boostyourbimterrifictools/raw/cd5589e83a158f283774d7a5e9590f07d85c904a/Boost+Your+BIM+Terrific+Tools-SetupFiles/Boost+Your+BIM+Terrific+Tools.msi&data=04%7C01%7Cjeremy.tammik%40autodesk.com%7Ce709df334bc34c20e06f08d9371557e6%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637601387077658469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HBFqPbGzz8Js990PpjCS5UuexeYytjlaxnU/EIDMFTw%3D&reserved=0\n\ntwitter:\n\nadd #thebuildingcoder\n\nThe ever-present need to regenerate, access to various asset keyword properties and a free tool to create and update toposurface from a set of model lines with the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon https://bit.ly/assetkeyword\n\nTwo Revit API discussion forum threads reinforce the ever-present need to regenerate, the development team clarifies access to various asset keyword properties, and Harry Mattison shares a free tool to create and update a toposurface from a set of model lines\n&ndash; Asset keyword access\n&ndash; Modifying group requires regen\n&ndash; Modifying part material requires regen\n&ndash; Topo from lines...\n\nlinkedin:\n\nThe ever-present need to regenerate, access to various asset keyword properties and a free tool to create and update toposurface from a set of model lines with the #RevitAPI\n\nhttps://bit.ly/assetkeyword\n\nTwo Revit API discussion forum threads reinforce the ever-present need to regenerate, the development team clarifies access to various asset keyword properties, and Harry Mattison shares a free tool to create and update a toposurface from a set of model lines:\n\n- Asset keyword access\n- Modifying group requires regen\n- Modifying part material requires regen\n- Topo from lines...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n**Question:** \n\n**Answer:**\n\n**Response:**  \n\nMany thanks to  for this very helpful explanation!\n\n-->"
  },
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Topo from Lines, Asset Keyword and Regeneration",
    "local_header_href": "#topo-from-lines-asset-keyword-and-regeneration",
    "chunk_text": "### Topo from Lines, Asset Keyword and Regeneration\n\nTwo [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) threads\nreinforce the ever-present [need to regenerate](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.33),\nthe development team clarifies access to various asset keyword properties, and Harry Mattison shares a free tool to create and update a toposurface from a set of model lines:\n\n- [Asset keyword access](#2)\n- [Modifying group requires regen](#3)\n- [Modifying part material requires regen](#4)\n- [Topo from lines](#5)\n\n<center>\n<img src=\"img/keyword_clustering.png\" alt=\"Keyword clustering\" title=\"Keyword clustering\" width=\"425\"/> <!-- 850 -->\n</center>"
  },
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Asset Keyword Access",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Asset Keyword Access\n\n**Question:** I have an issue setting a string value to the material appearance asset keyword property.\nIn one material, it can be set as expected, but another material returns an error saying, \"The input value is invalid for this AssetPropertyString property; Parameter name: value\".\nI found the blog article\non [Material, Physical and Thermal Assets](https://thebuildingcoder.typepad.com/blog/2019/11/material-physical-and-thermal-assets.html) and the internal development ticket *REVIT-170824* which explains that the keyword property on the `Identity` tab is not exposed yet.\nHowever, I still expect the \"keyword\" property on the appearance tab to accept a string value.\nIn addition, I can see some error message in the journal file when I try to run the code below.\nIs it possible to set the \"keyword\" property of the appearance asset?\n\n<pre class=\"code\">\n<span style=\"color:blue;\">void</span>&nbsp;SetMaterialAppearanceAssetKeywordProperty(\n&nbsp;&nbsp;AppearanceAssetElement&nbsp;assetElem,\n&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;new_keyword&nbsp;)\n{\n&nbsp;&nbsp;Document&nbsp;doc&nbsp;=&nbsp;assetElem.Document;\n\n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;Transaction&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;Transaction(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Transaction&nbsp;Set&nbsp;Keyword&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;AppearanceAssetEditScope&nbsp;editScope&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;AppearanceAssetEditScope(&nbsp;assetElem.Document&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asset&nbsp;editableAsset&nbsp;=&nbsp;editScope.Start(&nbsp;assetElem.Id&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">try</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;parameter&nbsp;=&nbsp;editableAsset.FindByName(&nbsp;<span style=\"color:#a31515;\">&quot;keyword&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;parameter&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AssetPropertyString&nbsp;propKeyword&nbsp;=&nbsp;parameter&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;AssetPropertyString;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;propKeyword&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">string</span>.IsNullOrEmpty(&nbsp;propKeyword.Value&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;propKeyword.Value&nbsp;=&nbsp;new_keyword;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;!propKeyword.Value.Contains(&nbsp;new_keyword&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;val&nbsp;=&nbsp;propKeyword.Value&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;:&nbsp;&quot;</span>+&nbsp;new_keyword;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;propKeyword.Value&nbsp;=&nbsp;val;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">catch</span>(&nbsp;Exception&nbsp;ex&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Debug.WriteLine(&nbsp;ex.Message&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editScope.Commit(&nbsp;<span style=\"color:blue;\">true</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();\n&nbsp;&nbsp;}\n}\n</pre>\n\n**Answer:** Yes, indeed, we already have a request *REVIT-171312* for this improvement.\n\nThe API does support modification of the `Keyword` property on an appearance asset.\nYou can set keyword under the `Appearance` tab in the material dialog through API.\nYou currently cannot set the `Keyword` property for `Structural` and `Thermal` through the API. \n\nAfter testing, I can reproduce this issue in the public release Revit 2022.\nIt works in my internal development version, however.\nI created an issue *REVIT-179045* to track why this fails in Revit 2022 and will evaluate it for an upcoming point release fix.\nHere is our understanding of the current situation accessing the keyword property in the various tabs:\n\n- For keywords under the `Identity` tab, which is the keyword for `Material`, there is currently no API exposed for either `get` or `set`.\n- Keywords under `Appearance` can be both `get` and `set` using the code above.\n- Keywords under `Thermal` and `Structural` can be read using `get`, as described in the article\non [material, physical and thermal assets](https://thebuildingcoder.typepad.com/blog/2019/11/material-physical-and-thermal-assets.html).\n`Set` is currently not supported for historical reasons (cf. internal tickets *REVIT-171312* and *REVIT-170824*)."
  },
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Modifying Group Requires Regen",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Modifying Group Requires Regen\n\nForgetting or not realising\nthe [need to regenerate](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.33) and\naccessing stale data can lead to pretty confusing and challenging problems.\n\nAs already noted in some previous examples, certain operations require more than just a call to `Regenerate`, e.g., starting and committing two or more separate transactions in a row.\nHappily, in such cases, they can be assimilated into one single `TransactionGroup`, cf. the additional discussion\non [handling transactions and transaction groups](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.50).\n\nIt took a lengthy discussion with input from a couple of experienced add-in developers to clarify this need in the thread\non [modifying group in API results in duplicate group](https://forums.autodesk.com/t5/revit-api-forum/modifying-group-in-api-results-in-duplicate-group/m-p/10374430)."
  },
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Modifying Part Material Requires Regen",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Modifying Part Material Requires Regen\n\nAnother example of \nthe [need to regenerate](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.33) was\nraised and solved\nby Joseph [@jrtlatta](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/7726218) Latta\nand Richard [@RPThomas108](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) Thomas in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread on how\nto [set different materials to parts of a wall](https://forums.autodesk.com/t5/revit-api-forum/set-different-materials-to-parts-of-a-wall/m-p/10427403).\n\nIn this case, careful observation and thorough understanding of the user interface helps significantly to resolve the problem, since the property to modify is greyed out &ndash; disabled or enabled &ndash; depending on the setting of another value:\n\n**Question:** I am trying to set different materials to different parts of a wall as shown in the picture below:\n\n<center>\n<img src=\"img/different_materials_to_parts.png\" alt=\"Different materials to parts\" title=\"Different materials to parts\" width=\"500\"/> <!-- 1328 -->\n</center>\n\nMy current method allows me to set all the parts to have the same material, but doesn't let me assign each part its own material. Here is my current approach:\n\n- Get all the parts in the file (this is a controlled file where I know exactly what parts are there)\n- Check whether a part is currently set to material \"Facade Material\" &ndash; this is how I've organized my wall ahead of time and I only want to change the material of parts of the wall that have material \"Facade Material\"\n- Set each part's built-in parameter \"Material by original\" to false\n- Set each part's built-in material parameter to my desired one\n\nThe issue is, once I set the material parameter for a given part, then it changes the material parameters for all the other parts.\nI'm not sure if the concept of instance parameter vs type parameter vs family parameter holds for Parts, but from the object browser in Revit, the material parameter seems to be an instance parameter.\n\n<pre class=\"code\">\n&nbsp;&nbsp;IEnumerable&lt;Part&gt;&nbsp;facadePanels2&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;FilteredElementCollector(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;Part&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Cast&lt;Part&gt;();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;Part&nbsp;p&nbsp;<span style=\"color:blue;\">in</span>&nbsp;facadePanels2&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;trans&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;Transaction(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Modify1&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameter&nbsp;pMat&nbsp;=&nbsp;p.get_Parameter(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BuiltInParameter.DPART_MATERIAL_ID_PARAM&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Diagnostics.Debug.Print(&nbsp;pMat.AsValueString()&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pMat.AsValueString()&nbsp;==&nbsp;<span style=\"color:#a31515;\">&quot;Facade&nbsp;Material&quot;</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Diagnostics.Debug.Print(&nbsp;<span style=\"color:#a31515;\">&quot;Facade&nbsp;Material&nbsp;Found&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameter&nbsp;pOrig&nbsp;=&nbsp;p.get_Parameter(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BuiltInParameter.DPART_MATERIAL_BY_ORIGINAL&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pOrig.IsReadOnly&nbsp;==&nbsp;<span style=\"color:blue;\">false</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pOrig.Set(&nbsp;0&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pMat.IsReadOnly&nbsp;==&nbsp;<span style=\"color:blue;\">false</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ElementId&nbsp;matId&nbsp;=&nbsp;materialIds[&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;getMaterialOfPart(&nbsp;p,&nbsp;panels,&nbsp;viewDefault3D&nbsp;)&nbsp;];\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pMat.Set(&nbsp;matId&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n</pre>\n\nAny thoughts?\n\nI've seen this thing done before, so I know it's possible.\n\n**Answer:** First, thoughts that have little to do with your question:\n\n- I mostly recommend avoiding use of `AsValueString`.\nI prefer the methods that return the raw parameter value: `AsInteger`, `AsDouble`, `AsElementId`, `AsString`.\n- Why do you start a new transaction for each part in the loop?\nCan't you just use one single large transaction and run the loop within that?\n\n**Response:** I figured it out.\nIt had to do with my transactions.\n\nOnce I wrapped the setting of the two parameters (`pOrig` and `pMat`) in their own transactions for each part, it now works properly.\nIt looks like all other parameters get set to read only when you change 1 parameter for a part in a single transaction?\n\nHere's the code that's working, for those who care:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;Part&nbsp;p&nbsp;<span style=\"color:blue;\">in</span>&nbsp;facadePanels2&nbsp;)\n&nbsp;&nbsp;{ \n&nbsp;&nbsp;&nbsp;&nbsp;Parameter&nbsp;pMat&nbsp;=&nbsp;p.get_Parameter(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BuiltInParameter.DPART_MATERIAL_ID_PARAM&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pMat.AsElementId().IntegerValue&nbsp;==&nbsp;309859&nbsp;)&nbsp;<span style=\"color:green;\">//&nbsp;&quot;Facade&nbsp;Material&quot;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Diagnostics.Debug.Print(&nbsp;<span style=\"color:#a31515;\">&quot;Facade&nbsp;Material&nbsp;Found&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameter&nbsp;pOrig&nbsp;=&nbsp;p.get_Parameter(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BuiltInParameter.DPART_MATERIAL_BY_ORIGINAL&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pOrig.IsReadOnly&nbsp;==&nbsp;<span style=\"color:blue;\">false</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;trans&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;Transaction(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Modify1&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pOrig.Set(&nbsp;0&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;pMat.IsReadOnly&nbsp;==&nbsp;<span style=\"color:blue;\">false</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ElementId&nbsp;matId&nbsp;=&nbsp;materialIds[&nbsp;getMaterialOfPart(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p,&nbsp;panels,&nbsp;viewDefault3D&nbsp;)&nbsp;];\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;trans&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;Transaction(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Modify1&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pMat.Set(&nbsp;matId&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n</pre>\n\n**Answer:** Yes.\nThat makes sense, since the second parameter would also be greyed out in UI if the first is not set to false, i.e., the ability to set thew second parameter is dependent on the value of first.\n\nThis also highlights the importance of order when batch processing built-in parameter values.\nThere are a few add-ins out there that populate parameter values, but they probably are not considering such relationships between parameters.\n\nIn that case, you can probably increase performance by using only one transaction after all and replacing the multiple mini-transactions by calls to `doc.Regenerate` after each call to set `DPART_MATERIAL_BY_ORIGINAL`.\n\nMany thanks to Joseph and Richard for sharing and explaining this!"
  },
  {
    "original_filename": "1910_asset_keyword",
    "header_text": "Topo From Lines",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> Topo From Lines\n\n[Harry Mattison](https://twitter.com/BoostYourBIM)'s new post\non [Boost Your BIM](https://boostyourbim.wordpress.com) presents\n[Topo From Lines now in the free Revit tool set](https://boostyourbim.wordpress.com/2021/06/24/topo-from-lines-now-in-the-free-revit-tool-set):\n\n> This tool is an \"oldie but goodie\" that lets you create and update a toposurface from a set of model lines.\nA new version for 2022 was recently requested, so I added it to the Terrific Tool project and created a 2022 build.\nYou can download the current installer here and if you like code, that is [here](https://bitbucket.org/BoostYourBIM/boostyourbimterrifictools/src/master/BoostYourBIMTerrificTools/TopoFromLines.cs).\n\n<center>\n<img src=\"img/topofromlinesscreenshot.jpg\" alt=\"Topo from lines\" title=\"Topo from lines\" width=\"327\"/> <!-- 654 -->\n</center>\n\nMany thanks to Harry for implementing and sharing this and so many other useful tools!"
  }
]