[
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- ricaun shared\n  RevitAddin.CommandLoader - Compile/Running 'IExternalCommand' with Revit open!\n  https://forums.autodesk.com/t5/revit-api-forum/revitaddin-commandloader-compile-running-iexternalcommand-with/td-p/11742530\n  > I present my first RevitAddin open-source project CommandLoader. With this plugin is possible to compile IExternalCommand directly in Revit, and the command is added as a PushButton in the Addins Tab.\n  Here is a video explaining the features and some limitations.\n  [Compile/Running 'IExternalCommand' with Revit open!](https://youtu.be/l4V4-vohcWY)\n  <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/l4V4-vohcWY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\n  RevitAddin.CommandLoader project compiles IExternalCommand with Revit open using CodeDom.Compiler and creates a PushButton on the Revit ribbon.\n  [GitHub repository](https://github.com/ricaun-io/RevitAddin.CommandLoader)\n\n- richard implemented a very nice little sample using the TessellatedShapeBuilder to create a DirectShape\n  create a [pyramid](https://en.wikipedia.org/wiki/Pyramid_(geometry)), or,\n  more specifically, a right pyramid with a regular base for the ...\n  on [Is it possible to create a solid from the edges of Pyramids?]\n  https://forums.autodesk.com/t5/revit-api-forum/is-it-possible-to-create-a-solid-from-the-edges-of-pyramids/td-p/11729445\n\n- richard suggested how to\n  How to modify levels extents (X and Y direction)\n  https://forums.autodesk.com/t5/revit-api-forum/how-to-modify-levels-extents-x-and-y-direction/td-p/11731529\n\n- how to filter for subsets of elements\n  https://autodesk.slack.com/archives/C0SR6NAP8/p1675998082315159\n  Shen Wang\n  Scott Conover\n\n- switch document display units:\n  Converting All Parameter Values from Imperial Units to Metric Units\n  https://forums.autodesk.com/t5/revit-api-forum/converting-all-parameter-values-from-imperial-units-to-metric/m-p/11728282#M69113\n\n- workaround for REVIT-20249\n  REVIT-20249 [As a Revit user, I want my material tags to stop displaying \"?\" after minor changes to the model, so that I don't have to waste time regen-ing or nudging all material tags right before printing a drawing set]\n  Workaround as stated by one customer: \"Standard Operating Procedure around here is right before printing, select a material tag > right click > select all instances in entire project > nudge right > nudge left, then print.\"\n\n- sublime text\n  Sublime Text: remember cursor position plugin\n  https://gmpy.dev/blog/2022/sublime-text-remember-cursor-position-plugin\n\ntwitter:\n\nCommand loader dynamically loads, compiles and runs add-in code, a DirectShape pyramid builder, level element X and Y extents, filtering for subsets of elements and switching document display units with the @AutodeskRevit #RevitAPI #BIM @AutodeskAPS https://autode.sk/rvtaddincodeloader\n\nPyramid Builder, CommandLoader, and more\n&ndash; Dynamic load, compile and run code\n&ndash; DirectShape pyramids\n&ndash; Modify level element X and Y extents\n&ndash; How to filter for subsets of elements\n&ndash; Switch document display units\n&ndash; Material tags displaying '?'\n&ndash; Sublime Text...\n\nlinkedin:\n\nCommand loader dynamically loads, compiles and runs add-in code, a DirectShape pyramid builder, level element X and Y extents, filtering for subsets of elements and switching document display units with the #RevitAPI \n\nhttps://autode.sk/rvtaddincodeloader\n\n- Dynamic load, compile and run code\n- DirectShape pyramids\n- Modify level element X and Y extents\n- How to filter for subsets of elements\n- Switch document display units\n- Material tags displaying '?'\n- Sublime Text...\n\n#bim #DynamoBim #AutodeskAPS #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\" height=\"\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n<pre class=\"code\">\n</pre>\n\n-->"
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Pyramid Builder, CommandLoader, et al",
    "local_header_href": "#pyramid-builder-commandloader-et-al",
    "chunk_text": "### Pyramid Builder, CommandLoader, et al\n\nHappy St. Valentine's Day!\n\nLots of activity in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) and\nelsewhere:\n\n- [Dynamic load, compile and run code](#2)\n- [DirectShape pyramids](#3)\n- [Modify level element X and Y extents](#4)\n- [How to filter for subsets of elements](#5)\n- [Switch document display units](#6)\n- [Material tags displaying '?'](#7)\n- [Sublime Text](#8)"
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Dynamic Load, Compile and Run Code",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Dynamic Load, Compile and Run Code\n\nRecently, several [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) threads\nrevolved around how to dynamically load and compile Revit add-ins.\n\nLuiz Henrique [@ricaun](https://github.com/ricaun) Cassettari now shared a solution for that,\n[RevitAddin.CommandLoader &ndash; compile and run `IExternalCommand` with Revit open](https://forums.autodesk.com/t5/revit-api-forum/revitaddin-commandloader-compile-running-iexternalcommand-with/td-p/11742530):\n\nI present my first Revit add-in open-source project CommandLoader.\nWith this plugin is possible to compile `IExternalCommand` directly in Revit, and the command is added as a `PushButton` in the Addins Tab.\nHere is an 8-minute video explaining the features and some limitations, [compile and run 'IExternalCommand' with Revit open](https://youtu.be/l4V4-vohcWY):\n\n<center>\n<iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/l4V4-vohcWY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\n</center>\n\nRevitAddin.CommandLoader project compiles `IExternalCommand` with Revit open using `CodeDom.Compiler` and creates a `PushButton` on the Revit ribbon.\n\n- [RevitAddin.CommandLoader GitHub repository](https://github.com/ricaun-io/RevitAddin.CommandLoader)"
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "DirectShape Pyramids",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> DirectShape Pyramids\n\nRichard [RPThomas108](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) Thomas\nimplemented a very nice little sample using the `TessellatedShapeBuilder` to create `DirectShape`\n[regular pyramids](https://en.wikipedia.org/wiki/Pyramid_(geometry)) to answer\nthe question [is it possible to create a solid from the edges of pyramids?](https://forums.autodesk.com/t5/revit-api-forum/is-it-possible-to-create-a-solid-from-the-edges-of-pyramids/td-p/11729445)\n\n<center>\n<img src=\"img/pyramids.png\" alt=\"Pyramids\" title=\"Pyramids\" width=\"400\"/> <!-- 491 x 509 pixels -->\n</center>\n\n**Answer:** Yes.\nYou can do so with `TessellatedShapeBuilder`, but you only need the points, not the edges:\n\n<pre class=\"prettyprint\">\n  Private Function Obj_230204a( _\n    ByVal commandData As Autodesk.Revit.UI.ExternalCommandData,\n    ByRef message As String,\n    ByVal elements As Autodesk.Revit.DB.ElementSet) As Result\n\n    Dim UIApp As UIApplication = commandData.Application\n    Dim UIDoc As UIDocument = commandData.Application.ActiveUIDocument\n    If UIDoc Is Nothing Then Return Result.Cancelled Else\n    Dim IntDoc As Document = UIDoc.Document\n\n    Const NumberOfSides As Integer = 6\n    Const BaseRadius As Double = 1\n    Const ApexHeight As Double = 2\n\n    Dim Seg As Double = 2.0 / NumberOfSides\n    Dim Points As XYZ() = New XYZ(NumberOfSides - 1) {}\n    For i = 0 To NumberOfSides - 1\n      Dim P As Double = i * Seg\n      Dim X As Double = Math.Sin(Math.PI * P) * BaseRadius\n      Dim Y As Double = Math.Cos(Math.PI * P) * BaseRadius\n\n      Points(i) = New XYZ(X, Y, 0)\n    Next\n    Dim builder As New TessellatedShapeBuilder()\n    builder.OpenConnectedFaceSet(True)\n\n    'The bottom face\n    builder.AddFace(New TessellatedFace(Points, ElementId.InvalidElementId))\n\n    'Side faces\n    Dim ApexPt As New XYZ(0, 0, ApexHeight)\n\n    For i = 0 To Points.Length - 1\n      Dim J As Integer = i + 1\n      If i = Points.Length - 1 Then\n        J = 0\n      End If\n\n      Dim P1 As XYZ = Points(i)\n      Dim P2 As XYZ = Points(J)\n      builder.AddFace(New TessellatedFace(New XYZ(2) {P1, P2, ApexPt}, ElementId.InvalidElementId))\n    Next\n    builder.CloseConnectedFaceSet()\n\n    builder.Target = TessellatedShapeBuilderTarget.Solid\n    builder.Fallback = TessellatedShapeBuilderFallback.Abort\n    builder.Build()\n\n    Dim Res As TessellatedShapeBuilderResult = builder.GetBuildResult\n    If Res.Outcome = TessellatedShapeBuilderOutcome.Solid Then\n\n      Using Tx As New Transaction(IntDoc, \"Pyramid\")\n        If Tx.Start = TransactionStatus.Started Then\n\n          Dim ds As DirectShape = DirectShape.CreateElement(IntDoc, New ElementId(BuiltInCategory.OST_GenericModel))\n          ds.SetShape(Res.GetGeometricalObjects())\n\n          Tx.Commit()\n        End If\n      End Using\n\n    End If\n\n    Return Result.Succeeded\n  End Function\n</pre>\n\nRough C# translation from VB.NET:\n\n<pre class=\"prettyprint\">\n  public Result Obj_230204a(\n    Autodesk.Revit.UI.ExternalCommandData commandData,\n    ref string message,\n    Autodesk.Revit.DB.ElementSet elements)\n  {\n    UIApplication UIApp = commandData.Application;\n    UIDocument UIDoc = commandData.Application.ActiveUIDocument;\n    if (UIDoc == null)\n      return Result.Cancelled;\n    Document IntDoc = UIDoc.Document;\n\n    const int NumberOfSides = 6;\n    const double BaseRadius = 1;\n    const double ApexHeight = 2;\n\n    double Seg = 2.0 / NumberOfSides;\n    XYZ[] Points = new XYZ[NumberOfSides];\n    for (int i = 0; i <= NumberOfSides - 1; i++)\n    {\n      double P = i * Seg;\n      double X = Math.Sin(Math.PI * P) * BaseRadius;\n      double Y = Math.Cos(Math.PI * P) * BaseRadius;\n\n      Points[i] = new XYZ(X, Y, 0);\n    }\n    TessellatedShapeBuilder builder = new TessellatedShapeBuilder();\n    builder.OpenConnectedFaceSet(true);\n\n    //The bottom face\n    builder.AddFace(new TessellatedFace(Points, ElementId.InvalidElementId));\n\n    //Side faces\n    XYZ ApexPt = new XYZ(0, 0, ApexHeight);\n\n    for (int i = 0; i <= Points.Length - 1; i++)\n    {\n      int J = i + 1;\n      if (i == Points.Length - 1)\n      {\n        J = 0;\n      }\n\n      XYZ P1 = Points[i];\n      XYZ P2 = Points[J];\n      builder.AddFace(new TessellatedFace(new XYZ[3] {\n      P1,\n      P2,\n      ApexPt\n    }, ElementId.InvalidElementId));\n    }\n    builder.CloseConnectedFaceSet();\n\n    builder.Target = TessellatedShapeBuilderTarget.Solid;\n    builder.Fallback = TessellatedShapeBuilderFallback.Abort;\n    builder.Build();\n\n    TessellatedShapeBuilderResult Res = builder.GetBuildResult();\n\n    if (Res.Outcome == TessellatedShapeBuilderOutcome.Solid)\n    {\n      using (Transaction Tx = new Transaction(IntDoc, \"Pyramid\"))\n      {\n\n        if (Tx.Start() == TransactionStatus.Started)\n        {\n          DirectShape ds = DirectShape.CreateElement(IntDoc,\n            new ElementId(BuiltInCategory.OST_GenericModel));\n          ds.SetShape(Res.GetGeometricalObjects());\n\n          Tx.Commit();\n        }\n      }\n    }\n    return Result.Succeeded;\n  }\n</pre>\n\nMany thanks to Richard for the nice sample!"
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Modify Level Element X and Y Extents",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Modify Level Element X and Y Extents\n\nRichard also suggested [how to modify level extents in X and Y direction](https://forums.autodesk.com/t5/revit-api-forum/how-to-modify-levels-extents-x-and-y-direction/td-p/11731529):\n\n**Question:** I can get levels extents with `get_BoundingBox` and am looking for something like `set_BoundingBox`. I want to keep the level's Z elevation at the same level and stretch its bounding box in X and Y direction:\n\n<center>\n<img src=\"img/level_extent_x_y.png\" alt=\"Level X Y extent\" title=\"Level X Y extent\" width=\"500\"/> <!-- 923 × 435 pixels -->\n</center>\n\n**Answer:** There is some functionality on the `DatumPlane` class that `Level` inherits from, e.g.:\n\n- DatumPlane.SetCurveInView\n- DatumPlane.Maximize3DExtent\n- DatumPlane.PropagateToViews\n\nSeems better to maximize the extents and propagate to views rather than individually manipulating curves."
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "How to Filter for Subsets of Elements",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> How to Filter for Subsets of Elements\n\nSome very basic hints on generic filtering came up in this question:\n\n**Question:** ... on the parsed element structure of the Revit model; you could think of it as the model tree in Navisworks.\nUsers want to access the parsed structured data and graphic elements of the BIM, select objects by filtering Revit views, grids, family categories or MEP systems, and then create assemblies after selecting elements for documentation.\n\nExample 1: a relatively complex building includes multiple piping systems.\nThe user needs to quickly select the circuit of a certain piping system on a certain floor.\n\nExample 2: in a section of linear engineering, such as an elevated road, the user needs to quickly select the elements between two grids:\n\n<center>\n<img src=\"img/elevated_road.png\" alt=\"Elevated road\" title=\"Elevated road\" width=\"500\"/> <!-- 1000 × 491 pixels -->\n</center>\n\n**Answer:** The Revit API provides many ways to filter down to the elements you are looking for.\nIt depends on the particular need.\nIn Example 1, you might want to start with the elements in the target system, but then filter further with an `ElementParameterFilter` for the reference level and/or with a geometric filter like `BoundingBoxIntersectsFilter` or `ElementIntersectsSolidFilter`.\nExample 2 seems more geometric, so filter first by certain categories and then use the geometric filters after calculating a shape that represents the space between grids.\nFor more information on all the filters, please refer to the knowledgebase article\non [Applying Filters](https://knowledge.autodesk.com/support/revit/learn-explore/caas/CloudHelp/cloudhelp/2014/ENU/Revit/files/GUID-A2686090-69D5-48D3-8DF9-0AC4CC4067A5-htm.html)."
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Switch Document Display Units",
    "local_header_href": "#6",
    "chunk_text": "####<a name=\"6\"></a> Switch Document Display Units\n\nIn the thread\non [converting all parameter values from imperial to metric units](https://forums.autodesk.com/t5/revit-api-forum/converting-all-parameter-values-from-imperial-units-to-metric/m-p/11728282),\n<i>nikolaEXEZM</i> shared two simple macros showing how to switch document display units between Imperial and Metric.\n> Works with both project and family documents.\nJust create a new Macro Module, and paste in the code below:\n\n<pre class=\"prettyprint\">\npublic void ChangeUnitsToImperial()\n{\n  Document doc = this.ActiveUIDocument.Document;\n\n  Document templateDoc = Application.OpenDocumentFile(\n    @\"C:\\ProgramData\\Autodesk\\RVT \"\n      + this.Application.VersionNumber\n      + @\"\\Templates\\English-Imperial\\default.rte\");\n\n  using (Transaction ta = new Transaction(doc))\n  {\n    ta.Start(\"Change Project Units to Imperial\");\n    doc.SetUnits(templateDoc.GetUnits());\n    ta.Commit();\n  }\n}\n\npublic void ChangeUnitsToMetric()\n{\n  Document doc = this.ActiveUIDocument.Document;\n\n  Document templateDoc = Application.OpenDocumentFile(\n    @\"C:\\ProgramData\\Autodesk\\RVT \"\n      + this.Application.VersionNumber\n      + @\"\\Templates\\English\\DefaultMetric.rte\");\n\n  using (Transaction ta = new Transaction(doc))\n  {\n    ta.Start(\"Change Project Units to Metric\");\n    doc.SetUnits(templateDoc.GetUnits());\n    ta.Commit();\n  }\n}\n</pre>\n\nMany thanks to Nikola for sharing these."
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Material Tags Displaying '?'",
    "local_header_href": "#7",
    "chunk_text": "####<a name=\"7\"></a> Material Tags Displaying '?'\n\nA couple of threads mentioned a problem with material tags displaying question marks '?' after minor changes to the model, forcing the user to waste time regenerating or nudging all material tags every time right before printing a drawing set.\nA workaround for this was mentioned in the ticket <i>REVIT-20249</i>:\n\n> Standard Operating Procedure around here is right before printing, select a material tag &gt; right click &gt; select all instances in entire project &gt; nudge right &gt; nudge left &gt; print."
  },
  {
    "original_filename": "1982_builder_loader",
    "header_text": "Sublime Text",
    "local_header_href": "#8",
    "chunk_text": "####<a name=\"8\"></a> Sublime Text\n\nClosing with a non-Revit topic, I recently updated my computer to\nthe [MacBook Pro M1 ARM](https://thebuildingcoder.typepad.com/blog/2022/12/exploring-arm-chatgpt-nairobi-and-the-tsp.html#11).\nThen, I updated the OS to MacOS Ventura, and my beloved and trusty old Komodo Edit text editor stopped working.\nIt has not been maintained for years.\nSearching for a new minimalist text editor, I happened\nupon [Sublime Text](https://www.sublimetext.com/) and\nstarted using that.\nI am glad to report that it works perfectly for me.\n\nI love the way that all settings are stored in JSON and take effect the moment you save the JSON file.\n\nToday, I also added my first own key binding, also saved in JSON and taking immediate effect on saving the file.\n\nNow, to round it off, I installed my first plugin, implemented in Python by Giampaolo Rodola:\n[Sublime Text: remember cursor position plugin](https://gmpy.dev/blog/2022/sublime-text-remember-cursor-position-plugin).\nSame procedure: install the Python file in the appropriate location\n&ndash; <i>~/Library/Application Support/Sublime Text/Packages/User</i>, in my case\n&ndash; and it immediately starts working.\n\nI wish everything worked like this."
  }
]