[
  {
    "original_filename": "2041_hide_linked",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!-- https://highlightjs.org/#usage\n<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css\">\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js\"></script>\n<script>hljs.highlightAll();</script>\n-->\n\n<!-- https://prismjs.com -->\n<link href=\"https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.min.css\" rel=\"stylesheet\" />\n<script src=\"https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js\"></script>\n<style> code[class*=language-], pre[class*=language-] { font-size : 90%; } </style>\n</head>\n\n<!---\n\n- hide elements in linked model\n  https://forums.autodesk.com/t5/revit-ideas/hide-elements-in-linked-model/idc-p/12786934#M57768\n  Hide elements in linked file\n  https://forums.autodesk.com/t5/revit-api-forum/hide-elements-in-linked-file/td-p/5777305\n  @lvirone\n  Lorenzo VIRONE\n  I've found a solution:\n  //Select elements using UIDocument and then use PostCommand \"HideElements\"\n  //elemsFromRevitLinkInstance is \"List<Element>\", there are the elements you want to hide in the link\n  var refs = elemsFromRevitLinkInstance.Select(x => new Reference(x).CreateLinkReference(revitLinkInstance)).ToList();\n  uidoc.Selection.SetReferences(refs);\n  uidoc.Application.PostCommand(RevitCommandId.LookupPostableCommandId(PostableCommand.HideElements));\n  demonstrate how to preselect elements for PostCommand processing\n\ntwitter:\n\nThe video recording on What's New in the Revit 2025 API has been released, and we discuss a nice example combining element pre-selection and PostCommand for hiding linked elements in the @AutodeskRevit #RevitAPI #BIM @DynamoBIM https://autode.sk/hidelinkedelement\n\nThe video recording on what's new in the Revit 2025 API has been released, and we discuss a nice example combining element pre-selection and PostCommand\n&ndash; Revit 2025 API video\n&ndash; Hiding linked elements...\n\nlinkedin:\n\nThe video recording on What's New in the Revit 2025 API has been released, and we discuss a nice example combining element pre-selection and PostCommand for hiding linked elements in the #RevitAPI\n\nhttps://autode.sk/hidelinkedelement\n\n- Revit 2025 API video\n- Hiding linked elements...\n\n#BIM #DynamoBIM #AutodeskAPS #Revit #API #IFC #SDK #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "2041_hide_linked",
    "header_text": "Revit 2025 API Video and Hiding Linked Elements",
    "local_header_href": "#revit-2025-api-video-and-hiding-linked-elements",
    "chunk_text": "### Revit 2025 API Video and Hiding Linked Elements\n\nThe video recording on what's new in the Revit 2025 API has been released, and we discuss a nice example combining element pre-selection and `PostCommand`:\n\n- [Revit 2025 API video](#2)\n- [Hiding linked elements](#3)"
  },
  {
    "original_filename": "2041_hide_linked",
    "header_text": "Revit 2025 API Video",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Revit 2025 API Video\n\nBoris Shafiro and Michael Morris present the video recording of the presentations\non [What's new in Autodesk Revit 2025 API](https://www.youtube.com/playlist?list=PLuFh5NgXkweMoOwwM2NlYmQ7FdMKPEBS_).\nIt consists of three parts:\n\n- [Introduction and .NET 8 Migration](https://youtu.be/ONLf4BuGBU8) (7 minutes)\n- [Breaking changes and removed API](https://youtu.be/huj3ynWwejA) (15 minutes)\n- [New APIs and Capabilities](https://youtu.be/jExac5Kv-Qs) (40 minutes)\n\n<center>\n<img src=\"img/rvt2025apivideo.png\" alt=\"Revit 2025 API video\" title=\"Revit 2025 API video\" width=\"800\"/>\n</center>\n\nPlease also refer to the following previous articles related to Revit 2025 API:\n\n- [Revit 2025 and RevitLookup 2025](https://thebuildingcoder.typepad.com/blog/2024/04/revit-2025-and-revitlookup-2025.html)\n- [The Building Coder Samples 2025](https://thebuildingcoder.typepad.com/blog/2024/04/the-building-coder-samples-2025.html)\n- [RevitLookup Hotfix and the Revit 2025 SDK](https://thebuildingcoder.typepad.com/blog/2024/04/revitlookup-hotfix-and-the-revit-2025-sdk.html)\n- [What's New in the Revit 2025 API](https://thebuildingcoder.typepad.com/blog/2024/04/whats-new-in-the-revit-2025-api.html)\n- [Migrating VB to .NET Core 8](https://thebuildingcoder.typepad.com/blog/2024/05/migrating-vb-to-net-core-8-and-ai-news.html)\n- [Revit 2025.1](https://thebuildingcoder.typepad.com/blog/2024/05/revit-20251-and-handling-lack-of-ui-in-da.html)"
  },
  {
    "original_filename": "2041_hide_linked",
    "header_text": "Hiding Linked Elements",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Hiding Linked Elements\n\nTurning to a topic that has not yet been addressed by the new release, the open Revit Ideas wish list item\nto [hide elements in linked model](https://forums.autodesk.com/t5/revit-ideas/hide-elements-in-linked-model/idc-p/12786934),\nLorenzo Virone shared a solution using `PostCommand` and element pre-selection via `Selection.SetReferences`.\nHe explains the detailed approach in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread on how\nto [hide elements in linked file](https://forums.autodesk.com/t5/revit-api-forum/hide-elements-in-linked-file/td-p/5777305):\n\nThis solution also demonstrates how to preselect elements for `PostCommand` processing:\n\n<pre><code class=\"language-cs\">// Select elements using UIDocument\n// then use PostCommand \"HideElements\"\n// elemsFromRevitLinkInstance is \"List&lt;Element&gt;\"\n// these are the elements you want to hide in the link\n\nvar refs = elemsFromRevitLinkInstance.Select( x\n  => new Reference(x).CreateLinkReference(revitLinkInstance))\n    .ToList();\n\nuidoc.Selection.SetReferences(refs);\n\nuidoc.Application.PostCommand(\n  RevitCommandId.LookupPostableCommandId(\n    PostableCommand.HideElements));\n</code></pre>\n\n**Response:** Can you provide a description of the process for using your code to hide elements only in a linked model?\nI am not familiar with the API and deploying a script like this.\n\n**Answer:**\nHere is an sample that selects the first RevitLinkInstance, retrieve its floors and hides them:\n\n<pre><code class=\"language-cs\">// Get a link\nvar filter = new ElementClassFilter(typeof(RevitLinkInstance));\n\nvar firstInstanceLink\n  = (RevitLinkInstance) new FilteredElementCollector(doc)\n    .WherePasses(filter)\n    .FirstElement();\n\n// Get its floors\nfilter = new ElementClassFilter(typeof(Floor));\nvar elemsFromRevitLinkInstance\n  = new FilteredElementCollector(\n    firstInstanceLink.GetLinkDocument())\n      .WherePasses(filter)\n      .ToElements();\n\n// Isolate them\nvar refs = elemsFromRevitLinkInstance.Select( x\n  => new Reference(x).CreateLinkReference(firstInstanceLink))\n    .ToList();\n\nuidoc.Selection.SetReferences(refs);\n\nuidoc.Application.PostCommand(\n  RevitCommandId.LookupPostableCommandId(\n    PostableCommand.HideElements));\n</code></pre>\n\nMany thanks to Lorenzo for addressing this need and sharing his helpful solution!"
  }
]