[
  {
    "original_filename": "0200_electrical_and_lighting",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0200_electrical_and_lighting",
    "header_text": "Electrical Settings and Lighting Fixtures",
    "local_header_href": "#electrical-settings-and-lighting-fixtures",
    "chunk_text": "<h3>Electrical Settings and Lighting Fixtures</h3><p>Here are two recent questions on\n\n<a href=\"#1\">\nelectrical settings of distribution systems</a>\n\nand\n\n<a href=\"#2\">\nfamily instances for lighting fixtures</a>\n\nhandled by Saikat Bhattacharya and Joe Ye, respectively.</p><p>By the way, this is a special occasion, namely the 200<sup>th</sup> post to The Building Coder.\nI will resist the temptation to declare this as a birthday post like I did \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/02/utilizing-revit-api-resources.html\">\npost number 100</a>,\n\nbecause the first real annual birthday of The Building Coder is coming up quite soon now anyway, and we don't want to exaggerate, do we?</p><a name=\"1\"></a>"
  },
  {
    "original_filename": "0200_electrical_and_lighting",
    "header_text": "Reading and Writing the Electrical Settings of Distribution Systems",
    "local_header_href": "#reading-and-writing-the-electrical-settings-of-distribution-systems",
    "chunk_text": "<h4>Reading and Writing the Electrical Settings of Distribution Systems</h4><p><strong>Question:</strong>\nIs there any way to use the Revit API to read and write the data under Electrical Settings, e.g. the Distribution System rows?</p><p><strong>Answer:</strong>\nTo do a quick check, I used the RvtMgdDbg tool and found out that the active document contains a DistributionSysType container which lists all the distribution systems available from the user interface.\nHere are the electrical settings displayed in the user interface:</p><center>\n<img alt=\"Electrical Settings\" src=\"img/electrical_settings.jpg\"/>\n</center><p>Here, we have selected the DistributionSysType instance using\n\nRvtMgdDbg\n\nto show the same information as the user interface as accessed through the API:</p><center>\n<img alt=\"DistributionSysType in RvtMgdDbg\" src=\"img/electrical_settings2.jpg\"/>\n</center><p>Thus, the DistributionSysType class might be what you looking for.</p><a name=\"2\"></a>"
  },
  {
    "original_filename": "0200_electrical_and_lighting",
    "header_text": "Creating Hosted Family Instances for Lighting Fixtures",
    "local_header_href": "#creating-hosted-family-instances-for-lighting-fixtures",
    "chunk_text": "<h4>Creating Hosted Family Instances for Lighting Fixtures</h4><p><strong>Question:</strong>\nI am loading a batch of lighting fixtures using .NET but I am having some issues.\n\nI programmatically set the host to be the ceiling by using parameters showing that the host is the ceiling when the fixture is loaded.\nHowever, the properties of the resulting fixture do not reflect this.\n\nAlso, the fixture created cannot be copied.\n\nIn sum, the properties of the fixtures are not the same as the properties of a fixture created manually and inserted by Revit itself.\n\nI used the following code to load the fixture:\n\n<pre>\nFamilyInstance inst\n  = doc.Create.NewFamilyInstance(\n    location, symbol, ceil,\n    StructuralType.NonStructural );\n</pre>\n<p>In this call, location is the location of the fixture.\nI set its Z coordinate to zero in order to inherit the host elevation, but this does not work.\nSymbol is the family symbol to be inserted, and ceil the selected host ceiling.</p>\n<p><strong>Answer:</strong>\nI reproduced the issue.\nUsing your method, I found the created light fixture is located above the ceiling, although the Z elevation is the same.\nThe host property is null, as is the parameter value of HOST_ID_PARAM.\nSo I think the issue is caused by the level setting.</p>\n\nI changed the code to use another override of NewFamilyInstance, which takes the level as an argument:\n\n<pre>\nDocument.NewFamilyInstance(\n  XYZ,\n  FamilySymbol,\n  Element,\n  Level,\n  StructuralType )\n</pre>\n<p>The lighting fixture now has a valid host property. Here is the updated code for the Execute method of the external command:</p>\n<pre class=\"code\">\n<span class=\"teal\">Application</span> app = commandData.Application;\n<span class=\"teal\">Document</span> doc = app.ActiveDocument;\n \nAutodesk.Revit.Creation.<span class=\"teal\">Filter</span> cf\n  = app.Create.Filter;\n \n<span class=\"green\">// get a lighting fixture family symbol:</span>\n \n<span class=\"teal\">Filter</span> f1 = cf.NewTypeFilter(\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilySymbol</span> ) );\n \n<span class=\"teal\">Filter</span> f2 = cf.NewCategoryFilter(\n  <span class=\"teal\">BuiltInCategory</span>.OST_LightingFixtures );\n \n<span class=\"teal\">Filter</span> f = cf.NewLogicAndFilter( f1, f2 );\n \n<span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt; symbols = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">Element</span>&gt;();\ndoc.get_Elements( f, symbols );\n \n<span class=\"teal\">FamilySymbol</span> sym = <span class=\"blue\">null</span>;\n \n<span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> elem <span class=\"blue\">in</span> symbols )\n{\n  sym = elem <span class=\"blue\">as</span> <span class=\"teal\">FamilySymbol</span>; <span class=\"green\">// get the first one.</span>\n  <span class=\"blue\">break</span>;\n}\n \n<span class=\"blue\">if</span>( <span class=\"blue\">null</span> == sym )\n{\n  message = <span class=\"maroon\">\"No lighting fixture symbol found.\"</span>;\n  <span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Failed;\n}\n \n<span class=\"green\">// pick the ceiling:</span>\n \ndoc.Selection.StatusbarTip\n  = <span class=\"maroon\">\"Please select ceiling to host lighting fixture\"</span>;\n \ndoc.Selection.PickOne();\n \n<span class=\"teal\">Element</span> ceiling = <span class=\"blue\">null</span>;\n \n<span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> elem <span class=\"blue\">in</span> doc.Selection.Elements )\n{\n  ceiling = elem <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n  <span class=\"blue\">break</span>;\n}\n \n<span class=\"green\">// get the level 1:</span>\n \n<span class=\"teal\">ElementIterator</span> it = doc.get_Elements(\n  <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) );\n \n<span class=\"teal\">Level</span> level = <span class=\"blue\">null</span>;\n \n<span class=\"blue\">while</span>( it.MoveNext() )\n{\n  level = it.Current <span class=\"blue\">as</span> <span class=\"teal\">Level</span>;\n \n  <span class=\"blue\">if</span>( level.Name.Equals( <span class=\"maroon\">\"Level 1\"</span> ) )\n    <span class=\"blue\">break</span>;\n}\n \n<span class=\"blue\">if</span>( <span class=\"blue\">null</span> == level )\n{\n  message = <span class=\"maroon\">\"Level 1 not found.\"</span>;\n  <span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Failed;\n}\n \n<span class=\"green\">// create the family instance:</span>\n \n<span class=\"teal\">XYZ</span> p = app.Create.NewXYZ( -43, 28, 0 );\n \n<span class=\"teal\">FamilyInstance</span> instLight\n  = doc.Create.NewFamilyInstance(\n    p, sym, ceiling, level,\n    <span class=\"teal\">StructuralType</span>.NonStructural );\n \n<span class=\"blue\">return</span> <span class=\"teal\">CmdResult</span>.Succeeded;\n</pre>\n<p>Thank you very much Joe and Saikat for these answers!\n</p></p>"
  }
]