[
  {
    "original_filename": "0215_elevation_section_view",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0215_elevation_section_view",
    "header_text": "Elevation and Section Views",
    "local_header_href": "#elevation-and-section-views",
    "chunk_text": "<h3>Elevation and Section Views</h3><p>Here are some questions handled by Joe Ye, on creation of and line work in elevation views and the cut plane definition of a section view.</p><p><strong>Question:</strong> There are different specialised kinds of views derived from the Autodesk.Revit.Elements.View class, and I see several methods in the Revit API to create some of these, such as 3D, Plan, Section, Sheet and Drafting.\nHowever, I cannot find a method to create an Elevation View.\nHow can I do that?\n\n<p><strong>Answer:</strong> Unfortunately, the Revit API currently does not provide any method to create an elevation view.\nAt the moment, you can use the NewViewSection method to create a vertical section view very similar to an elevation view.\nBy using a large bounding box which does not intersect with the building model, it can display the same view as an elevation view:\n\n<center>\n<img alt=\"Section view\" src=\"img/section_view.png\"/>\n</center>\n<p><strong>Question:</strong> Once I have created an elevation view, how would I change the line work of certain elements in that view?\nIn the user interface, Revit provides the Linework tool in the ribbon for this action.\nHow can I achieve this through the API?\n\n<p><strong>Answer:</strong> As regards modifying the line work displayed in an elevation view, you can use the CutLinePatternOverrideByElement method on the View object to set the line weight for specified elements.\nFor more information about this method, please see the Revit API help file RevitAPI.chm file in SDK.\n\n<p><strong>Question:</strong> How can I get the cut plane definition from a section view programmatically?\nI just need any point inside the cut plane and the normal vector of the plane to continue to do some other calculations.\n\n<p><strong>Answer:</strong> The section view class provides the properties you need.\nThe Origin property of a section view is a point in the world coordinate system or WCS located in the cut plane of the section view.\nThe ViewDirection property of a section view returns a WCS vector indicating the direction towards the viewer.\nYou can use the section view Origin as the cut plane origin, and the ViewDirection as its normal vector.\nDepending to your usage, you might need to reverse the direction of the ViewDirection.\n\n<p>Thank you very much Joe for these answers!\n</p></p></p></p></p></p></p>"
  }
]