[
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "Transformations",
    "local_header_href": "#transformations",
    "chunk_text": "<h3>Transformations</h3><p>This is part 7 of Scott Conover's AU 2009 class on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/analyse-building-geometry.html\">\nanalysing building geometry</a>, \n\nexploring coordinate transformations and the placement and orientation of family instances.\nFor completeness sake, here are some back pointers to previous blog posts dealing with transforms and related issues:\n\n<ul>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/03/transform.html\">The Transform class</a>.</li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2008/12/polygon-transformation.html\">Polygon transformation</a>.</li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/03/transform-instance-coordinates.html\">Instance coordinate transformation</a>.</li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/05/transform-an-element.html\">Transforming an element</a>.</li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/scale-a-curve.html\">Scaling a curve</a>.</li>\n</ul>\n<p>So now I hand the word back to Scott:\n\n<h4>Coordinate Transformations</h4>\n<p>Revit and the Revit API use coordinate transformations in a variety of ways. \nIn most cases, transformations are represented in the API as Transform objects. \nA transform object represents a homogenous transformation combining elements of rotation, translation, and less commonly, scaling and reflection:</p>\n<center>\n<img alt=\"Matrix composition\" src=\"img/abg7_matrix_equation.png\"/>\n</center>\n<p>In this matrix, the 3 x 3 matrix represents the rotation applied via the transform, while the 1 x 3 matrix represents the translation. Scaling and mirror properties, if applied, show up as multipliers on the matrix members. Mathematically, a transformation of a point looks like this:</p>\n<center>\n<img alt=\"Matrix transformation\" src=\"img/abg7_matrix_transformation.png\"/>\n</center>\n<p>In the Transform class you have direct access to the members of the transformation matrix:</p>\n<ul>\n<li>The properties BasisX, BasisY, and BasisZ are the unit vectors of the rotated coordinate system.\n<li>The Origin property is the translation vector.\n</li></li></ul>\n<p>Use the Transform.OfPoint() and Transform.OfVector() methods to apply the transformation to a given input point or vector. You can also use the Transformed indexed properties (on Curve, Profile, and Mesh) to transform geometry you extracted from Revit into an alternate coordinate system.</p>\n<p>You obtain a transform from a variety of operations:</p>\n<ul>\n<li>From the Instance class: the transformation applied to the instance.\n<li>From a Reference containing an Instance.\n<li>From a Panel (curtain panel) element.\n<li>From a 3D bounding box.\n<li>From static properties on Transform: .Identity, .Reflection, .Rotation, .Translation.\n<li>By multiplying two Transforms together: Transform.Multiply().\n<li>By scaling a transform and possibly its origin: Transform.ScaleBasis() and Transform.ScaleBasisAndOrigin().\n<li>By constructing one from scratch: Transform constructor.\n</li></li></li></li></li></li></li></li></ul>\n<p>Typically Transforms are right-handed coordinate systems, but mirror operations will produce left-handed coordinate systems. Note that Revit sometimes produces left-handed coordinate systems via flip operations on certain elements.</p>\n<h4>Transformation of Instances</h4>\n<p>The Instance class stores geometry data in the SymbolGeometry property using a local coordinate system. \nIt also provides a Transform instance to convert the local coordinate system to a world coordinate space. To get the same geometry data as the Revit application from the Instance class, use the transform property to convert each geometry object retrieved from the SymbolGeometry property.</p>\n<a name=\"south_facing_windows\"></a>\n<h4>South facing windows</h4>\n<p>Similarly to the example selecting all \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/south-facing-walls.html\">\nsouth facing walls</a>,\n\nwe can use the transform of the Instance stored in a window FamilyInstance to find south facing windows:</p>\n<center>\n<img alt=\"South facing windows\" src=\"img/abg7_south_facing_windows.png\"/>\n</center>\n<p>The Y direction of the transform is the facing direction; however, the flipped status of the window affects the result. \nIf a family instance is flipped in X, its FlippedHand property is true.\nIf it is flipped in Y, its FlippedFacing property is true.\nIf either one of these is set, and the other not, the result must be reversed.\nHere is the GetWindowDirection method implementing this:</p>\n<pre class=\"code\">\n<span class=\"blue\">protected</span> <span class=\"teal\">XYZ</span> GetWindowDirection( <span class=\"teal\">FamilyInstance</span> window )\n{\n  <span class=\"teal\">Options</span> options = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n \n  <span class=\"green\">// Extract the geometry of the window.</span>\n \n  Autodesk.Revit.Geometry.<span class=\"teal\">Element</span> geomElem \n    = window.get_Geometry( options );\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> geomObj <span class=\"blue\">in</span> geomElem.Objects )\n  {\n    <span class=\"green\">// We expect there to be one main Instance </span>\n    <span class=\"green\">// in each window.  Ignore the rest of the geometry.</span>\n \n    <span class=\"teal\">Instance</span> instance = geomObj <span class=\"blue\">as</span> <span class=\"teal\">Instance</span>;\n    <span class=\"blue\">if</span>( instance != <span class=\"blue\">null</span> )\n    {\n      <span class=\"green\">// Obtain the Instance transform and the </span>\n      <span class=\"green\">// nominal facing direction (Y-direction).</span>\n \n      <span class=\"teal\">Transform</span> t = instance.Transform;\n \n      <span class=\"teal\">XYZ</span> facingDirection = t.BasisY;\n \n      <span class=\"green\">// If the window is flipped in one direction, </span>\n      <span class=\"green\">// but not the other, the transform is left handed.  </span>\n      <span class=\"green\">// The Y direction needs to be reversed to </span>\n      <span class=\"green\">// obtain the facing direction.</span>\n \n      <span class=\"blue\">if</span>( ( window.FacingFlipped &amp;&amp; !window.HandFlipped )\n        || ( !window.FacingFlipped &amp;&amp; window.HandFlipped ) )\n      {\n        facingDirection = -facingDirection;\n      }\n \n      <span class=\"green\">// Because the need to perform this operation </span>\n      <span class=\"green\">// on instances is so common, the Revit API exposes </span>\n      <span class=\"green\">// this calculation directly as the FacingOrientation </span>\n      <span class=\"green\">// property as shown in GetWindowDirectionAlternate()</span>\n \n      <span class=\"blue\">return</span> facingDirection;\n    }\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">XYZ</span>.BasisZ;\n}\n</pre>\n<p>Because the need to perform this operation on instances is so common, the Revit API exposes this calculation directly as the FacingOrientation property:</p>\n<pre class=\"code\">\n<span class=\"blue\">protected</span> <span class=\"teal\">XYZ</span> GetWindowDirectionAlternate( \n  <span class=\"teal\">FamilyInstance</span> window )\n{\n  <span class=\"blue\">return</span> window.FacingOrientation;\n}\n</pre>\n<h4>Nested instances</h4>\n<p>Note that instances may be nested inside other instances. Each instance has a Transform which represents the transformation from the coordinates of the symbol geometry to the coordinates of the instance. In order to get the coordinates of the geometry of one of these nested instances in the coordinates of the document, you will need to concatenate the transforms together using Transform.Multiply().</p>\n<p>Next, we look at the Revit project location, which also affects the location and transformations of the elements in the project.</p>\n</p></p>"
  },
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "Coordinate Transformations",
    "local_header_href": "#coordinate-transformations",
    "chunk_text": "<h4>Coordinate Transformations</h4><p>Revit and the Revit API use coordinate transformations in a variety of ways. \nIn most cases, transformations are represented in the API as Transform objects. \nA transform object represents a homogenous transformation combining elements of rotation, translation, and less commonly, scaling and reflection:</p><center>\n<img alt=\"Matrix composition\" src=\"img/abg7_matrix_equation.png\"/>\n</center><p>In this matrix, the 3 x 3 matrix represents the rotation applied via the transform, while the 1 x 3 matrix represents the translation. Scaling and mirror properties, if applied, show up as multipliers on the matrix members. Mathematically, a transformation of a point looks like this:</p><center>\n<img alt=\"Matrix transformation\" src=\"img/abg7_matrix_transformation.png\"/>\n</center><p>In the Transform class you have direct access to the members of the transformation matrix:</p><ul>\n<li>The properties BasisX, BasisY, and BasisZ are the unit vectors of the rotated coordinate system.\n<li>The Origin property is the translation vector.\n</li></li></ul><p>Use the Transform.OfPoint() and Transform.OfVector() methods to apply the transformation to a given input point or vector. You can also use the Transformed indexed properties (on Curve, Profile, and Mesh) to transform geometry you extracted from Revit into an alternate coordinate system.</p><p>You obtain a transform from a variety of operations:</p><ul>\n<li>From the Instance class: the transformation applied to the instance.\n<li>From a Reference containing an Instance.\n<li>From a Panel (curtain panel) element.\n<li>From a 3D bounding box.\n<li>From static properties on Transform: .Identity, .Reflection, .Rotation, .Translation.\n<li>By multiplying two Transforms together: Transform.Multiply().\n<li>By scaling a transform and possibly its origin: Transform.ScaleBasis() and Transform.ScaleBasisAndOrigin().\n<li>By constructing one from scratch: Transform constructor.\n</li></li></li></li></li></li></li></li></ul><p>Typically Transforms are right-handed coordinate systems, but mirror operations will produce left-handed coordinate systems. Note that Revit sometimes produces left-handed coordinate systems via flip operations on certain elements.</p>"
  },
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "Transformation of Instances",
    "local_header_href": "#transformation-of-instances",
    "chunk_text": "<h4>Transformation of Instances</h4><p>The Instance class stores geometry data in the SymbolGeometry property using a local coordinate system. \nIt also provides a Transform instance to convert the local coordinate system to a world coordinate space. To get the same geometry data as the Revit application from the Instance class, use the transform property to convert each geometry object retrieved from the SymbolGeometry property.</p><a name=\"south_facing_windows\"></a>"
  },
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "South facing windows",
    "local_header_href": "#south-facing-windows",
    "chunk_text": "<h4>South facing windows</h4><p>Similarly to the example selecting all \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/south-facing-walls.html\">\nsouth facing walls</a>,\n\nwe can use the transform of the Instance stored in a window FamilyInstance to find south facing windows:</p><center>\n<img alt=\"South facing windows\" src=\"img/abg7_south_facing_windows.png\"/>\n</center><p>The Y direction of the transform is the facing direction; however, the flipped status of the window affects the result. \nIf a family instance is flipped in X, its FlippedHand property is true.\nIf it is flipped in Y, its FlippedFacing property is true.\nIf either one of these is set, and the other not, the result must be reversed.\nHere is the GetWindowDirection method implementing this:</p><pre class=\"code\">\n<span class=\"blue\">protected</span> <span class=\"teal\">XYZ</span> GetWindowDirection( <span class=\"teal\">FamilyInstance</span> window )\n{\n  <span class=\"teal\">Options</span> options = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n \n  <span class=\"green\">// Extract the geometry of the window.</span>\n \n  Autodesk.Revit.Geometry.<span class=\"teal\">Element</span> geomElem \n    = window.get_Geometry( options );\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> geomObj <span class=\"blue\">in</span> geomElem.Objects )\n  {\n    <span class=\"green\">// We expect there to be one main Instance </span>\n    <span class=\"green\">// in each window.  Ignore the rest of the geometry.</span>\n \n    <span class=\"teal\">Instance</span> instance = geomObj <span class=\"blue\">as</span> <span class=\"teal\">Instance</span>;\n    <span class=\"blue\">if</span>( instance != <span class=\"blue\">null</span> )\n    {\n      <span class=\"green\">// Obtain the Instance transform and the </span>\n      <span class=\"green\">// nominal facing direction (Y-direction).</span>\n \n      <span class=\"teal\">Transform</span> t = instance.Transform;\n \n      <span class=\"teal\">XYZ</span> facingDirection = t.BasisY;\n \n      <span class=\"green\">// If the window is flipped in one direction, </span>\n      <span class=\"green\">// but not the other, the transform is left handed.  </span>\n      <span class=\"green\">// The Y direction needs to be reversed to </span>\n      <span class=\"green\">// obtain the facing direction.</span>\n \n      <span class=\"blue\">if</span>( ( window.FacingFlipped &amp;&amp; !window.HandFlipped )\n        || ( !window.FacingFlipped &amp;&amp; window.HandFlipped ) )\n      {\n        facingDirection = -facingDirection;\n      }\n \n      <span class=\"green\">// Because the need to perform this operation </span>\n      <span class=\"green\">// on instances is so common, the Revit API exposes </span>\n      <span class=\"green\">// this calculation directly as the FacingOrientation </span>\n      <span class=\"green\">// property as shown in GetWindowDirectionAlternate()</span>\n \n      <span class=\"blue\">return</span> facingDirection;\n    }\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">XYZ</span>.BasisZ;\n}\n</pre><p>Because the need to perform this operation on instances is so common, the Revit API exposes this calculation directly as the FacingOrientation property:</p><pre class=\"code\">\n<span class=\"blue\">protected</span> <span class=\"teal\">XYZ</span> GetWindowDirectionAlternate( \n  <span class=\"teal\">FamilyInstance</span> window )\n{\n  <span class=\"blue\">return</span> window.FacingOrientation;\n}\n</pre>"
  },
  {
    "original_filename": "0290_abg07_transform",
    "header_text": "Nested instances",
    "local_header_href": "#nested-instances",
    "chunk_text": "<h4>Nested instances</h4><p>Note that instances may be nested inside other instances. Each instance has a Transform which represents the transformation from the coordinates of the symbol geometry to the coordinates of the instance. In order to get the coordinates of the geometry of one of these nested instances in the coordinates of the document, you will need to concatenate the transforms together using Transform.Multiply().</p><p>Next, we look at the Revit project location, which also affects the location and transformations of the elements in the project.</p>"
  }
]