[
  {
    "original_filename": "0381_highlight_elements",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0381_highlight_elements",
    "header_text": "Highlight Elements",
    "local_header_href": "#highlight-elements",
    "chunk_text": "<h3>Highlight Elements</h3><p>I arrived in Boston and am now acclimatising in preparation for the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/devcamp-devlabs-and-updated-api-training-schedule.html\">\nAEC DevCamp</a> conference \n\n(<a href=\"http://devcamps2010.autodeskevents.net/index.cfm?event=cms.page&amp;id=SID3FA5EEFA001D080A3456040FDD1BD93C\">web site</a>) starting \n\non Monday and the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/03/devcamp-devlabs-and-updated-api-training-schedule.html#devlabs\">\nDevLabs</a> in Waltham following afterwards\n\n(<a href=\"http://usa.autodesk.com/adsk/servlet/item?id=6703509&amp;siteID=123112&amp;cname=DevLab (AEC), Waltham, Jun 10 2010, 201039\">register</a>).\n\n<p>Meanwhile, here is a quick \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/05/pre-post-and-pick-select.html?cid=6a00e553e1689788330133efe49023970b#comment-6a00e553e1689788330133efe49023970b\">\nquestion from Soub</a> that \n\nwe have actually provided a solution for a couple of times in the past but not explicitly pointed out yet.\n\n<p><strong>Question:</strong> I have a question related to the API for highlighting elements in Revit Architecture based on the Element ID input.\nCould you please help me by explaining how to highlight multiple elements based on IDs?\n\n<p><strong>Answer:</strong> There is really no difference between highlighting a single element or multiple ones.\nAll you need to do is add them to the current selection set managed by the Revit UI document, or to the third argument to the Execute method, and then return a Cancelled or Failed result code.\n\n<p>An example of the first approach is provided by the command\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/01/south-facing-walls.html\">\nhighlighting south facing walls</a>.\n\nThe main lines of interest there in this context are the ones accessing the current selection set, adding specific elements to it, and setting the property to the new collection:\n\n<pre class=\"code\">\n<span class=\"teal\">SelElementSet</span> selElements = Document.Selection.Elements;\n \n<span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Wall</span>&gt; walls = CollectExteriorWalls();\n \n<span class=\"blue\">foreach</span>( <span class=\"teal\">Wall</span> wall <span class=\"blue\">in</span> walls )\n{\n  <span class=\"teal\">XYZ</span> exteriorDirection = GetExteriorWallDirection( wall );\n \n  <span class=\"blue\">bool</span> isSouthFacing = IsSouthFacing( exteriorDirection );\n \n  <span class=\"blue\">if</span>( isSouthFacing )\n  {\n    selElements.Add( wall );\n  }\n}\n \nDocument.Selection.Elements = selElements;\n</pre>\n<p>The code presented there is based on Revit 2010.\nIt has been updated for the Revit 2011 API in the DirectionCalculation SDK sample and now looks like this:\n\n<pre class=\"code\">\n  <span class=\"teal\">UIDocument</span> uiDoc = <span class=\"blue\">new</span> <span class=\"teal\">UIDocument</span>( Document );\n \n  Autodesk.Revit.UI.Selection.<span class=\"teal\">SelElementSet</span>\n    selElements = uiDoc.Selection.Elements;\n \n  <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Wall</span>&gt; walls\n    = CollectExteriorWalls();\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Wall</span> wall <span class=\"blue\">in</span> walls )\n  {\n    <span class=\"teal\">XYZ</span> exteriorDirection\n      = GetExteriorWallDirection( wall );\n \n    <span class=\"blue\">if</span>( useProjectLocationNorth )\n    {\n      exteriorDirection\n        = TransformByProjectLocation(\n          exteriorDirection );\n    }\n \n    <span class=\"blue\">bool</span> isSouthFacing\n      = IsSouthFacing( exteriorDirection );\n \n    <span class=\"blue\">if</span>( isSouthFacing )\n      selElements.Insert( wall );\n  }\n \n  <span class=\"green\">// Select all walls which had the proper direction.</span>\n  uiDoc.Selection.Elements = selElements;\n</pre>\n<p>As said, you can also highlight elements graphically by adding them to the third argument of an external command Execute method and then returning a Cancelled or Failed result code:\n\n<pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> revit,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n  <span class=\"teal\">ElementSet</span> elements )\n{\n  <span class=\"green\">// . . .</span>\n \n  <span class=\"teal\">Element</span> e;\n \n  <span class=\"green\">// . . .</span>\n \n  elements.Insert( e );\n\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n}\n</pre>\n<p>This is demonstrated by the Lab1_2_CommandArguments of the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/05/pre-post-and-pick-select.html\">\nRevit API introduction labs</a>.\n</p></p></p></p></p></p></p></p>"
  }
]