[
  {
    "original_filename": "0428_flex_duct_start_tangent",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0428_flex_duct_start_tangent",
    "header_text": "Flex Duct Start Tangent",
    "local_header_href": "#flex-duct-start-tangent",
    "chunk_text": "<h3>Flex Duct Start Tangent</h3><p>Still zipping around in Pattaya with my brother Marcus, and still blogging a bit now and then as well ...\n\n<p>Here is a suggestion for a workaround to specify the start and end tangents of a flex duct or pipe that evolved through a recent\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/08/structural-dynamic-model-update-sample.html?cid=6a00e553e168978833013485f297dc970c#comment-6a00e553e168978833013485f297dc970c\">\nexchange</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/08/structural-dynamic-model-update-sample.html?cid=6a00e553e1689788330133f2dfa073970b#comment-6a00e553e1689788330133f2dfa073970b\">\nof</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/08/structural-dynamic-model-update-sample.html?cid=6a00e553e1689788330134860dce69970c#comment-6a00e553e1689788330134860dce69970c\">\ncomments</a> with Zhu XiaoMeng:\n\n<p><strong>Question:</strong> In the Revit application UI, I can create a FlexDuct properly with the start tangent of the Hermite curve in a reasonable direction.\nBut when I create a flex duct in the API, the start tangent is always horizontal. \nHow can I do the same thing in API as in the UI?\n\n<p>The initial code is as follows:\n\n<pre class=\"code\">\n  <span class=\"teal\">FlexDuct</span> flexDuct = doc.Create.NewFlexDuct( \n    points, flexducttype );\n</pre>\n<p><strong>Answer:</strong> One thing to note regarding this is that it does not seem to be related to the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/07/debugging-in-visual-studio-2010-express.html?cid=6a00e553e168978833013485ce109c970c#comment-6a00e553e168978833013485ce109c970c\">\nHermite spline issue</a> that we recently discussed.\n\n<p>Here is a suggestion for a possible workaround: \n\n<ol>\n<li>Place a fitting with a connector temporarily where the direction of the connector matches the desired tangent. \n<li>Place the flex duct or pipe and attach it to the connector. \n<li>Delete the fitting.\n</li></li></li></ol>\n<p><strong>Response:</strong> I did as what you say, but I get confused with the second step.\nI placed a fitting with two side connectors in the right place, and then placed the flex duct in the right position, but they did not join. \nSo the tangent did not change. \nSo the point is: how can I get them joined?\n\n<p>Here is my current code:\n\n<pre class=\"code\">\n  <span class=\"teal\">Family</span> fittingFamily \n    = lstElem.Where( e =&gt; e.Name == <span class=\"maroon\">\"M_xyz\"</span> )\n    .Select( e =&gt; e <span class=\"blue\">as</span> <span class=\"teal\">Family</span> )\n    .FirstOrDefault();\n \n  <span class=\"teal\">FamilySymbol</span> fittingType = fittingFamily\n    .Symbols\n    .ToList()\n    .First();\n \n  <span class=\"blue\">const</span> <span class=\"blue\">double</span> fitLen = 1.5;\n \n  <span class=\"blue\">var</span> vectDown \n    = ( samplePoints[1] - samplePoints[0] )\n      .Normalize();\n \n  <span class=\"blue\">var</span> fittPos = ptA - vectDown * fitLen;\n \n  <span class=\"green\">// vectAb is the vector pointing from </span>\n  <span class=\"green\">// ptA(samplePoints[First]) to </span>\n  <span class=\"green\">// ptB(samplePoints[Last])</span>\n \n  <span class=\"green\">//  remove the z values (as the </span>\n  <span class=\"green\">// flexDuct first tangent do)</span>\n \n  <span class=\"blue\">var</span> vectAbHoriz = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( vectAb.X, vectAb.Y, 0 );\n \n  <span class=\"teal\">FamilyInstance</span> fittingInstance \n    = _doc.Create.NewFamilyInstance( \n      fittPos, fittingType, \n      StructuralType.NonStructural );\n \n  <span class=\"teal\">Line</span> axis2 = _app.Create.NewLine( \n    fittPos, vectDown.CrossProduct( <span class=\"teal\">XYZ</span>.BasisZ ), \n    <span class=\"blue\">false</span> );\n \n  <span class=\"green\">// rotate the fitting to the desired angle</span>\n \n  <span class=\"blue\">bool</span> success = _doc.Rotate( fittingInstance, \n    axis2, -vectDown.AngleTo( vectAbHoriz ) );\n \n  SortedList valuePairs = <span class=\"blue\">new</span> SortedList();\n \n  valuePairs[<span class=\"maroon\">\"xyz 01\"</span>] = fitLen;\n \n  ChangeParametersValue( fittingInstance, valuePairs );\n \n  <span class=\"teal\">FlexDuct</span> flexDuct2 = CreateDuct( \n    samplePoints, flexDuctType );\n</pre>\n<p><strong>Answer:</strong> You probably have to explicitly connect them with each other as demonstrated in the AutoRoute and AvoidObstruction SDK samples.\n\n<p><strong>Response:</strong> Thank you, it's solved! \n\n<p>Here is my way in case some one else encounters the same problem: \n\n<p>Find the right connector of the fitting as well as the right connector of flexDuct, and call the connector ConnectTo method to join them. \n\n<p>Before deleting the temporary fitting, call the document Regenerate method, otherwise the tangent will not change!\n\n<p>Very many thanks to Zhu XiaoMeng for this discussion and sharing the successful result!\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]