[
  {
    "original_filename": "0442_access_curtain_grid_panel",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0442_access_curtain_grid_panel",
    "header_text": "Access to Curtain Grid Panels",
    "local_header_href": "#access-to-curtain-grid-panels",
    "chunk_text": "<h3>Access to Curtain Grid Panels</h3><p>Here is some strange behaviour noted by Daren Thomas of the\n\n<a href=\"http://www.gt.arch.ethz.ch\">Professur für Gebäudetechnik, Institut für Hochbautechnik</a> at\n\nthe technical university ETH Zürich and author of the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/12/revit-python-shell.html\">\nRevit Python shell</a> which\n\nled to the discovery and quick fix of a problem in the curtain grid API.\nSince Daren also provides a workaround for the problem for immediate use, I think it worthwhile to note it here.\n\n<p><strong>Question:</strong> I just came by some strange behaviour in Autodesk Revit Architecture 2011: It seems that reading a Wall.CurtainGrid.Panels requires a transaction.\n\n<p>Here is a repro (using RevitPythonShell to avoid having to create a new project etc.):\n\n<ul>\n<li>Create a new Revit project.\n<li>Add a wall.\n<li>Change the wall type to CurtainGrid.\n<li>Remember the element ID of wall (Manage &gt; Inquiry &gt; IDs of Selection), in my case 127699.\n<li>Go to Add-Ins &gt; Open Python Shell.\n<li>Type following sequence of commands (this can be translated to C# pretty easily, as it is mainly about the API); copy to a text editor to see the truncated lines:\n</li></li></li></li></li></li></ul>\n<pre class=\"code\">\n&gt;&gt;&gt;import clr\n\n&gt;&gt;&gt;clr.AddReference('RevitAPI')\n\n&gt;&gt;&gt;from Autodesk.Revit.DB import *\n\n&gt;&gt;&gt;doc = __revit__.ActiveUIDocument.Document\n\n&gt;&gt;&gt;cw = doc.get_Element(ElementId(127699)) # substitute actual ID here\n\n&gt;&gt;&gt;cw\n\n&lt;Autodesk.Revit.DB.Wall object at\n  0x000000000000002B [Autodesk.Revit.DB.Wall]&gt;\n\n&gt;&gt;&gt;cw.CurtainGrid\n\n&lt;Autodesk.Revit.DB.CurtainGrid object at\n  0x000000000000002C [Autodesk.Revit.DB.CurtainGrid]&gt;\n\n&gt;&gt;&gt;cw.CurtainGrid.Panels\n\nIronTextBoxControl error: Attempt to modify the model outside of transaction.\n\n&gt;&gt;&gt;\n</pre>\n<p>By the way, this little script also amply demonstrates how extremely easy and powerfully a Revit model can be accessed programmatically and interactively through the Python shell.</p>\n<p>This dialog with RevitPythonShell shows that accessing the wall and its CurtainGrid property is ok, but accessing the Panels property triggers the exception.\nThe RevitPythonShell runs with TransactionMode.Manual.\nThis behaviour is not restricted to RevitPythonShell scripts – this is only for the repro.\nI came across this behaviour with a C# plug-in that also uses TransactionMode.Manual.\n\n<p>What is the rationale behind this behaviour?\n\n<p><strong>Answer:</strong> Several of the CurtainGrid APIs were ensuring that they had write access to the underlying objects, even when only read  access was required.\n\n<p>This behaviour has now been reported and corrected.\n\n<p><strong>Response:</strong> I'm not sure how fixes are deployed with Revit, but assume they are just included in the annual release – so for your readers, you might want to mention a workaround:\n\n<p>Starting a transaction and then calling the method Transaction.Rollback for tasks that don't need transactions but do read curtain wall panels.\n\n<p>Ideally, you want to place the transaction code as close to the curtain wall code as possible, but not inside an inner loop as that can slow things down considerably (been there, done that, getting t-shirts printed to prove).\n\n<p><strong>Answer:</strong> Yes, I would love to mention this in the blog and provide a workaround for those who run into this issue.\n\n<p>Do you happen to have some sample code ready to demonstrate exactly what you mean?\n\n<p>Or even (miraculously?) a reproducible sample project with one external command showing the problem and another one showing the solution?\n\n<p><strong>Response:</strong> I went through the trouble to build such a project.\n\n<p>You will find attached a C# solution (Visual Studio 2010) that creates the two external commands requested.\nInside the solution is also a sample Revit project file SingleCurtainWall.rvt containing four walls, one of which is a CurtainWall with one panel.\nA sample add-in file can also be found inside the solution.\n\n<p>Also, here are some screenshots of the output of said external commands; first the exception being thrown when the transaction workaround is not implemented:</p>\n<center>\n<img alt=\"CurtainGrid Panels transaction bug\" src=\"img/CurtainGridPanelsTransactionBug.png\"/>\n</center>\n<p>With the workaround in place, the panels become accessible:</p>\n<center>\n<img alt=\"CurtainGrid Panels transaction workaround\" src=\"img/CurtainGridPanelsWorkAround.png\"/>\n</center>\n<p>For completeness sake, here is the source code of the initial command causing the problem for comparison with the workaround listed below:\n\n<pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n[<span class=\"teal\">Regeneration</span>( <span class=\"teal\">RegenerationOption</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">TriggerCurtainGridPanelsTransactionBug</span>\n  : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"blue\">var</span> doc = commandData.Application\n      .ActiveUIDocument.Document;\n \n    <span class=\"blue\">var</span> walls = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Wall</span> ) )\n      .Cast&lt;<span class=\"teal\">Wall</span>&gt;();\n \n    <span class=\"blue\">foreach</span>( <span class=\"blue\">var</span> wall <span class=\"blue\">in</span> walls )\n    {\n      <span class=\"blue\">if</span>( wall.WallType.Kind == <span class=\"teal\">WallKind</span>.Curtain )\n      {\n        <span class=\"teal\">TaskDialog</span>.Show(\n          <span class=\"maroon\">\"CurtainGridPanelsTransactionBug\"</span>,\n          <span class=\"blue\">string</span>.Format(\n            <span class=\"maroon\">\"CurtainWall has {0} panels.\"</span>,\n            wall.CurtainGrid.Panels.Size ) );\n      }\n    }\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>This is the updated code with the added transaction required to access the curtain grid panel data, which can be discarded after use:\n\n<pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n[<span class=\"teal\">Regeneration</span>( <span class=\"teal\">RegenerationOption</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">WorkAroundCurtainGridPanelsTransactionBug</span>\n  : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"blue\">var</span> doc = commandData.Application\n      .ActiveUIDocument.Document;\n \n    <span class=\"blue\">var</span> walls = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Wall</span> ) )\n      .Cast&lt;<span class=\"teal\">Wall</span>&gt;();\n \n    <span class=\"green\">// workaround: create a transaction</span>\n \n    <span class=\"blue\">var</span> transaction = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n      <span class=\"maroon\">\"CurtainGridPanelsTransactionBug\"</span> );\n \n    transaction.Start();\n \n    <span class=\"blue\">try</span>\n    {\n      <span class=\"blue\">foreach</span>( <span class=\"blue\">var</span> wall <span class=\"blue\">in</span> walls )\n      {\n        <span class=\"blue\">if</span>( wall.WallType.Kind == <span class=\"teal\">WallKind</span>.Curtain )\n        {\n          <span class=\"teal\">TaskDialog</span>.Show(\n            <span class=\"maroon\">\"CurtainGridPanelsTransactionBug\"</span>,\n            <span class=\"blue\">string</span>.Format(\n              <span class=\"maroon\">\"CurtainWall has {0} panels.\"</span>,\n              wall.CurtainGrid.Panels.Size ) );\n        }\n      }\n    }\n    <span class=\"blue\">finally</span>\n    {\n      <span class=\"green\">// we don't really want to change the document!</span>\n \n      transaction.RollBack();\n    }\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>For yet more completeness sake, here is\n\n<a href=\"zip/CurtainGridPanelsTransaction.zip\">\nCurtainGridPanelsTransaction.zip</a> containing\n\nthe entire source code, Visual Studio 2008 and 2010 solution, and a sample file SingleCurtainWall.rvt to test it on.\n\n<p>I guess I got carried away on this task...\n\n<p>Many thanks to Daren for all his research, workaround, and complete documentation of this issue!\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]