[
  {
    "original_filename": "0479_launch_command",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0479_launch_command",
    "header_text": "Launching a Revit Command",
    "local_header_href": "#launching-a-revit-command",
    "chunk_text": "<h3>Launching a Revit Command</h3><p>One question that I frequently hear is how to launch a built-in Revit command programmatically.\n\n<p>We recently discussed a specific case related to this issue in some depth,\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html\">\nhow to close the active document</a>\n\nand especially pointed out\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html#2\">\nwhy this is risky, undesirable and not supported</a>.\n\n<p>To close the active document, we used the SendKeys.SendWait method provided in the .NET framework System.Windows.Forms namespace.\nMany of the other attempts that I have seen in the past to launch a Revit command were also based on this method, but unsuccessful.\n\n<p>Here is now a solution that actually does work, suggested by Robert Pleysier of\n\n<a href=\"http://www.alfadevelopment.nl\">\nALFA Development</a> in the Netherlands.\n\nInstead of SendKeys, he uses the native Windows API PostMessage call to send the Windows messages WM_KEYDOWN and WM_KEYUP for each required keystroke to the Revit process main window handle.\n\n<p>The reason for Robert to launch a Revit command at all is the requirement to predefine which wall type should be active when the user enters the new wall creation command.\nSince there is no API method available to programmatically predefine the current wall type to be used by this command, Robert selects an existing wall with the desired type and then uses the 'Create Similar' command to set up its type as the new default user interface wall type.\nIf no wall with the desired type exists yet in the model, a temporary wall is created and then deleted again.\n\n<p>Here is the question initially raised by Robert, and his own answer and solution:\n\n<p><strong>Question:</strong> In the Revit API you can use the function PromptForFamilyInstancePlacement to place family symbols.\n\n<p>Is it possible to place a Wall with this function or another function from code?\n\n<p>I want to change the wall or other system family type by code in the property dialog.\n\n<p>After that I want to activate the Revit wall or stair function by code, so a user can draw his or her own wall or stair with the right wall or stair type.\n\n<p><strong>Answer:</strong> I solved the issue by using a key press function \"cs\" for \"create similar\".\n\n<p>Based on Robert's example code showing how he did this, I implemented a new Building Code sample command CmdPressKey which illustrates his solution.\n\n<p>First of all, here is the helper class Press which accesses the Windows API methods and implements the public method Keys to actually send keystrokes using PostMessage. It requires the namespace System.Runtime.InteropServices:\n\n<pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">Press</span>\n{\n  [<span class=\"teal\">DllImport</span>( <span class=\"maroon\">\"USER32.DLL\"</span> )]\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"blue\">extern</span> <span class=\"blue\">bool</span> PostMessage(\n    <span class=\"teal\">IntPtr</span> hWnd, <span class=\"blue\">uint</span> msg, <span class=\"blue\">uint</span> wParam, <span class=\"blue\">uint</span> lParam );\n \n  [<span class=\"teal\">DllImport</span>( <span class=\"maroon\">\"user32.dll\"</span> )]\n  <span class=\"blue\">static</span> <span class=\"blue\">extern</span> <span class=\"blue\">uint</span> MapVirtualKey(\n    <span class=\"blue\">uint</span> uCode, <span class=\"blue\">uint</span> uMapType );\n \n  <span class=\"blue\">enum</span> <span class=\"teal\">WH_KEYBOARD_LPARAM</span> : <span class=\"blue\">uint</span>\n  {\n    KEYDOWN = 0x00000001,\n    KEYUP = 0xC0000001\n  }\n \n  <span class=\"blue\">enum</span> <span class=\"teal\">KEYBOARD_MSG</span> : <span class=\"blue\">uint</span>\n  {\n    WM_KEYDOWN = 0x100,\n    WM_KEYUP = 0x101\n  }\n \n  <span class=\"blue\">enum</span> <span class=\"teal\">MVK_MAP_TYPE</span> : <span class=\"blue\">uint</span>\n  {\n    VKEY_TO_SCANCODE = 0,\n    SCANCODE_TO_VKEY = 1,\n    VKEY_TO_CHAR = 2,\n    SCANCODE_TO_LR_VKEY = 3\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Post one single keystroke.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">static</span> <span class=\"blue\">void</span> OneKey( <span class=\"teal\">IntPtr</span> handle, <span class=\"blue\">char</span> letter )\n  {\n    <span class=\"blue\">uint</span> scanCode = MapVirtualKey( letter,\n      ( <span class=\"blue\">uint</span> ) <span class=\"teal\">MVK_MAP_TYPE</span>.VKEY_TO_SCANCODE );\n \n    <span class=\"blue\">uint</span> keyDownCode = ( <span class=\"blue\">uint</span> )\n      <span class=\"teal\">WH_KEYBOARD_LPARAM</span>.KEYDOWN\n      | ( scanCode &lt;&lt; 16 );\n \n    <span class=\"blue\">uint</span> keyUpCode = ( <span class=\"blue\">uint</span> )\n      <span class=\"teal\">WH_KEYBOARD_LPARAM</span>.KEYUP\n      | ( scanCode &lt;&lt; 16 );\n \n    PostMessage( handle,\n      ( <span class=\"blue\">uint</span> ) <span class=\"teal\">KEYBOARD_MSG</span>.WM_KEYDOWN,\n      letter, keyDownCode );\n \n    PostMessage( handle,\n      ( <span class=\"blue\">uint</span> ) <span class=\"teal\">KEYBOARD_MSG</span>.WM_KEYUP,\n      letter, keyUpCode );\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Post a sequence of keystrokes.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"blue\">void</span> Keys( <span class=\"blue\">string</span> command )\n  {\n    <span class=\"teal\">IntPtr</span> revitHandle = System.Diagnostics.<span class=\"teal\">Process</span>\n      .GetCurrentProcess().MainWindowHandle;\n \n    <span class=\"blue\">foreach</span>( <span class=\"blue\">char</span> letter <span class=\"blue\">in</span> command )\n    {\n      OneKey( revitHandle, letter );\n    }\n  }\n}\n</pre>\n<p>With this in place, we can go ahead and implement the external command.\nIt requires two helper methods: GetFirstWallTypeNamed retrieves the appropriate wall type for a given wall type name, and GetFirstWallUsingType retrieves the first wall element encountered in the model making use of a given wall type.\nBoth of these obviously use filtered element collectors, and both of them even use parameter filters.\nGetFirstWallTypeNamed uses the built-in parameter SYMBOL_NAME_PARAM and a string equality filter to do its job, i.e. to return the first wall type with the given name:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"teal\">WallType</span> GetFirstWallTypeNamed(\n  <span class=\"teal\">Document</span> doc,\n  <span class=\"blue\">string</span> name )\n{\n  <span class=\"green\">// built-in parameter storing this </span>\n  <span class=\"green\">// wall type's name:</span>\n \n  <span class=\"teal\">BuiltInParameter</span> bip\n    = <span class=\"teal\">BuiltInParameter</span>.SYMBOL_NAME_PARAM;\n \n  <span class=\"teal\">ParameterValueProvider</span> provider\n    = <span class=\"blue\">new</span> <span class=\"teal\">ParameterValueProvider</span>(\n      <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( bip ) );\n \n  <span class=\"teal\">FilterStringRuleEvaluator</span> evaluator\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilterStringEquals</span>();\n \n  <span class=\"teal\">FilterRule</span> rule = <span class=\"blue\">new</span> <span class=\"teal\">FilterStringRule</span>(\n    provider, evaluator, name, <span class=\"blue\">false</span> );\n \n  <span class=\"teal\">ElementParameterFilter</span> filter\n    = <span class=\"blue\">new</span> <span class=\"teal\">ElementParameterFilter</span>( rule );\n \n  <span class=\"teal\">FilteredElementCollector</span> collector\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">WallType</span> ) )\n      .WherePasses( filter );\n \n  <span class=\"blue\">return</span> collector.FirstElement() <span class=\"blue\">as</span> <span class=\"teal\">WallType</span>;\n}\n</pre>\n<p>GetFirstWallUsingType uses the built-in parameter ELEM_TYPE_PARAM and a numerical equality filter to retrieve all walls using the required wall type, because their corresponding parameter value will equal the wall type element id.\nWe don't care which wall is used to launch the \"Create Similar\" command, so we simply return the first one encountered:\n\n<pre class=\"code\">\n<span class=\"blue\">static</span> <span class=\"teal\">Wall</span> GetFirstWallUsingType(\n  <span class=\"teal\">Document</span> doc,\n  <span class=\"teal\">WallType</span> wallType )\n{\n  <span class=\"green\">// built-in parameter storing this </span>\n  <span class=\"green\">// wall's wall type element id:</span>\n \n  <span class=\"teal\">BuiltInParameter</span> bip\n    = <span class=\"teal\">BuiltInParameter</span>.ELEM_TYPE_PARAM;\n \n  <span class=\"teal\">ParameterValueProvider</span> provider\n    = <span class=\"blue\">new</span> <span class=\"teal\">ParameterValueProvider</span>(\n      <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( bip ) );\n \n  <span class=\"teal\">FilterNumericRuleEvaluator</span> evaluator\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilterNumericEquals</span>();\n \n  <span class=\"teal\">FilterRule</span> rule = <span class=\"blue\">new</span> <span class=\"teal\">FilterElementIdRule</span>(\n    provider, evaluator, wallType.Id );\n \n  <span class=\"teal\">ElementParameterFilter</span> filter\n    = <span class=\"blue\">new</span> <span class=\"teal\">ElementParameterFilter</span>( rule );\n \n  <span class=\"teal\">FilteredElementCollector</span> collector\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Wall</span> ) )\n      .WherePasses( filter );\n \n  <span class=\"blue\">return</span> collector.FirstElement() <span class=\"blue\">as</span> <span class=\"teal\">Wall</span>;\n}\n</pre>\n<p>With the support class and helper methods in place, the external command mainline Execute method implementation is short and sweet:\n\n<pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n  <span class=\"teal\">ElementSet</span> elements )\n{\n  <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n  <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n  <span class=\"teal\">Application</span> app = uiapp.Application;\n  <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n  <span class=\"green\">// name of target wall type that we want to use:</span>\n \n  <span class=\"blue\">string</span> wallTypeName = <span class=\"maroon\">\"Generic - 203\"</span>;\n \n  <span class=\"teal\">WallType</span> wallType = GetFirstWallTypeNamed(\n    doc, wallTypeName );\n \n  <span class=\"teal\">Wall</span> wall = GetFirstWallUsingType(\n    doc, wallType );\n \n  <span class=\"green\">// select the wall in the UI</span>\n \n  uidoc.Selection.Elements.Add( wall );\n \n  <span class=\"blue\">if</span>( 0 == uidoc.Selection.Elements.Size )\n  {\n    <span class=\"green\">// no wall with the correct wall type found</span>\n \n    <span class=\"teal\">FilteredElementCollector</span> collector\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc );\n \n    <span class=\"teal\">Level</span> ll = collector\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) )\n      .FirstElement() <span class=\"blue\">as</span> <span class=\"teal\">Level</span>;\n \n    <span class=\"green\">// place a new wall with the </span>\n    <span class=\"green\">// correct wall type in the project</span>\n \n    <span class=\"teal\">Line</span> geomLine = app.Create.NewLineBound(\n      <span class=\"teal\">XYZ</span>.Zero, <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 2, 0, 0 ) );\n \n    <span class=\"teal\">Transaction</span> t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(\n      doc, <span class=\"maroon\">\"Create dummy wall\"</span> );\n \n    t.Start();\n \n    <span class=\"teal\">Wall</span> nw = doc.Create.NewWall( geomLine,\n      wallType, ll, 1, 0, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n    t.Commit();\n \n    <span class=\"green\">// Select the new wall in the project</span>\n \n    uidoc.Selection.Elements.Add( nw );\n \n    <span class=\"green\">// Start command create similar. In the </span>\n    <span class=\"green\">// property menu, our wall type is set current</span>\n \n    <span class=\"teal\">Press</span>.Keys( <span class=\"maroon\">\"CS\"</span> );\n \n    <span class=\"green\">// select the new wall in the project, </span>\n    <span class=\"green\">// so we can delete it</span>\n \n    uidoc.Selection.Elements.Add( nw );\n \n    <span class=\"green\">// erase the selected wall (remark: </span>\n    <span class=\"green\">// doc.delete(nw) may not be used, </span>\n    <span class=\"green\">// this command will undo)</span>\n \n    <span class=\"teal\">Press</span>.Keys( <span class=\"maroon\">\"DE\"</span> );\n \n    <span class=\"green\">// start up wall command</span>\n \n    <span class=\"teal\">Press</span>.Keys( <span class=\"maroon\">\"WA\"</span> );\n  }\n  <span class=\"blue\">else</span>\n  {\n    <span class=\"green\">// the correct wall is already selected:</span>\n \n    <span class=\"teal\">Press</span>.Keys( <span class=\"maroon\">\"CS\"</span> ); <span class=\"green\">// start \"create similar\"</span>\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>As you see, an arbitrary dummy wall of the required type is created if none previously exists.\nFor this, we start up a transaction of our own, so we are obviously using manual transaction mode.\nAnd so we have to, since we have to close our transaction again before the Revit commands are invoked.\n\n<p>Robert says the following about this code:\nHere is a part or our code to start a Revit command.\nThe aim of the code is to set a wall type current in the Revit property window.\nWe only start up the wall command with the API and let the user do the drawing of the wall.\nThis solution can also be used to launch other Revit commands.\n\n<p>When I start up the standard sample project rac_basic_sample_project.rvt, switch to Level 1, and launch this command from the Revit ribbon, I immediately enter the standard Revit wall command.\nThe desired wall type is active, in this case the type named \"Generic - 203\", and I can immediately start placing new walls of that type.\n\n<p>There have been many other queries on how to programmatically set up the type before launching a Revit command, and this looks as if it could solve them.\n\n<p>I have to repeat the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html#2\">\nwarning about the risks involved with using this</a>, though,\n\nand also point back to the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/10/closing-the-active-document-and-why-not-to.html#3\">\ndisclaimer</a> accompanying that warning.\n\n<p>Still, if this is just for your personal use, you might find it pretty handy.\n\n<p>Here is\n\n<!-- C:\\a\\doc\\revit\\blog\\zip\\bc_11_80.zip -->\n<a href=\"zip/bc_11_80.zip\">\nversion 2011.0.80.0</a>\n\nof The Building Coder samples including the complete source code and Visual Studio solution with the new command.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]