[
  {
    "original_filename": "0512_lang_indep_subcat",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0512_lang_indep_subcat",
    "header_text": "Language Independent Subcategory Creation",
    "local_header_href": "#language-independent-subcategory-creation",
    "chunk_text": "<h3>Language Independent Subcategory Creation</h3><p>Here is a snapshot of a lengthy conversation that I have been leading with Gregory Mertens of\n\n<a href=\"http://www.mertens3d.com\">\nmertens3d.com</a> for \n\na while, starting out with a language independence issue and touching on other topics such as category and subcategory creation, use of built-in parameters, use of debug assertions and exception handling.\n\n<p>We looked at a couple of category related issues in the past:\n\n<ul>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/06/category-comparison-and-model-element-selection-revisited.html\">Category comparison</a>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/get-and-set-family-category-and-parameters.html\">Family categories</a>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/09/adding-a-category-to-a-parameter-binding.html\">Categories and parameter bindings</a>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2009/10/system-versus-user-family-category.html\">System versus user defined categories</a>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2010/05/categories.html\">Complete list of categories</a>\n</li></li></li></li></li></ul>\n<p>We have not yet looked at any examples of creating subcategories.\nTop level categories cannot be created, by the way.\n\n<p>Here is an example of creating subcategories, eliminating a language dependence in the process, and some thoughts on this, raised by Gregory:\n\n<p><strong>Question:</strong> I am using the following code to create new line subcategories\n(to see the truncated lines of VB code in full, please copy to a text editor):\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Sub</span> createNewLineSubCategory( _\n  <span class=\"blue\">ByRef</span> newSubCatName <span class=\"blue\">As</span> <span class=\"blue\">String</span>, _\n  <span class=\"blue\">ByRef</span> thisSubColor <span class=\"blue\">As</span> Autodesk.Revit.DB.Color)\n \n  <span class=\"blue\">Dim</span> oneCat <span class=\"blue\">As</span> Autodesk.Revit.DB.Category\n \n  <span class=\"blue\">Dim</span> mySubCat <span class=\"blue\">As</span> Autodesk.Revit.DB.Category\n \n  <span class=\"blue\">Dim</span> docTransaction <span class=\"blue\">As</span> <span class=\"blue\">New</span> Autodesk.Revit.DB.Transaction(ptr2Doc)\n \n  <span class=\"blue\">For</span> <span class=\"blue\">Each</span> oneCat <span class=\"blue\">In</span> ptr2Doc.Settings.Categories\n    <span class=\"blue\">If</span> oneCat.Name = <span class=\"maroon\">\"Lines\"</span> <span class=\"blue\">Then</span>\n \n      <span class=\"green\">'we need to cruise through each subcategory and make sure it doesn't</span>\n      <span class=\"green\">'already exist</span>\n \n      <span class=\"green\">' Dim allSubCategories As Autodesk.Revit.DB.CategoryNameMap = oneCat.SubCategories</span>\n \n      <span class=\"green\">' Dim oneSubCategory As Autodesk.Revit.DB.Category</span>\n      <span class=\"green\">'we know it doens't exist, because we tested for it prior to this routine</span>\n \n      <span class=\"blue\">Try</span>\n        docTransaction.SetName(<span class=\"maroon\">\"allSubCategories\"</span>)\n        docTransaction.Start()\n        mySubCat = ptr2Doc.Settings.Categories.NewSubcategory(oneCat, newSubCatName)\n        mySubCat.LineColor = thisSubColor\n        docTransaction.Commit()\n \n      <span class=\"blue\">Catch</span> ex <span class=\"blue\">As</span> Exception\n        MsgBox(ex.ToString)\n      <span class=\"blue\">End</span> <span class=\"blue\">Try</span>\n \n      <span class=\"blue\">Exit</span> <span class=\"blue\">For</span>\n    <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n  <span class=\"blue\">Next</span>\n \n<span class=\"blue\">End</span> <span class=\"blue\">Sub</span>\n</pre>\n<p>It works great when run on an English installation of Revit.\n\n<p>However, it doesn't work when I run it on an Italian install.\nIt looks like what is \"Lines\" to English users is \"Linee\" (2 e's) to Italian.\n\n<p>I suspect that I'm not coding this correctly.\nSurely I am not supposed to have a separate check for each language.\n\n<p>Could you comment on the correct way to code so that all language versions of Revit work correctly (at least relative to this issue)?\n\n<p><strong>Answer:</strong> To put it briefly,\n\n<ol>\n<li>Do not use the language dependent string comparison oneCat.Name = \"Lines\".\n<li>Find out what the built-in category is instead  ... OST_Lines?\n<li>Do not iterate over the entire collection of categories, use get_Item instead: Categories.Item Property (BuiltInCategory).\n<li>Send me your final code once you have solved this, please.\n</li></li></li></li></ol>\n<p><strong>Response:</strong> Thanks for the very quick and helpful response.\n\n<p>Here is some new code that works:\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Sub</span> createNewLineSubCategory( _\n  <span class=\"blue\">ByRef</span> newSubCatName <span class=\"blue\">As</span> <span class=\"blue\">String</span>, _\n  <span class=\"blue\">ByRef</span> newSubCatColor <span class=\"blue\">As</span> Autodesk.Revit.DB.Color)\n \n  <span class=\"blue\">Dim</span> lineCat <span class=\"blue\">As</span> Autodesk.Revit.DB.Category\n \n  <span class=\"blue\">Dim</span> lineSubCat <span class=\"blue\">As</span> Autodesk.Revit.DB.Category\n \n  <span class=\"blue\">Dim</span> docTransaction <span class=\"blue\">As</span> <span class=\"blue\">New</span> Autodesk.Revit.DB.Transaction(ptr2Doc)\n \n  lineCat = ptr2Doc.Settings.Categories.Item(BuiltInCategory.OST_Lines)\n \n  <span class=\"blue\">Try</span>\n    docTransaction.SetName(<span class=\"maroon\">\"hatch22 - Create SubCategory\"</span>)\n    docTransaction.Start()\n    lineSubCat = ptr2Doc.Settings.Categories.NewSubcategory(lineCat, newSubCatName)\n    lineSubCat.LineColor = newSubCatColor\n    docTransaction.Commit()\n \n  <span class=\"blue\">Catch</span> ex <span class=\"blue\">As</span> Exception\n    MsgBox(ex.ToString)\n  <span class=\"blue\">End</span> <span class=\"blue\">Try</span>\n \n<span class=\"blue\">End</span> <span class=\"blue\">Sub</span>\n</pre>\n<p>That (of course) led to other issues:\nI had to look through the rest of my code to see if there were any other places where I was using language dependant comparisons.\nOne of them I solved like this:\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Sub</span> changeLineStyleGeneric( _\n  <span class=\"blue\">ByVal</span> thisElement <span class=\"blue\">As</span> Autodesk.Revit.DB.Element, _\n  <span class=\"blue\">ByRef</span> newLineStyleID <span class=\"blue\">As</span> Autodesk.Revit.DB.ElementId)\n \n  <span class=\"blue\">Dim</span> param <span class=\"blue\">As</span> Parameter\n  <span class=\"blue\">Dim</span> parameters <span class=\"blue\">As</span> ParameterSet\n \n  <span class=\"blue\">If</span> <span class=\"blue\">Not</span> IsNothing(newLineStyleID) <span class=\"blue\">Then</span>\n    parameters = thisElement.Parameters\n    <span class=\"blue\">For</span> <span class=\"blue\">Each</span> param <span class=\"blue\">In</span> parameters\n \n      <span class=\"blue\">If</span> param.Definition.ParameterGroup = BuiltInParameterGroup.PG_GRAPHICS _\n         <span class=\"blue\">And</span> _\n        <span class=\"blue\">Not</span> param.AsElementId.IntegerValue = -1 <span class=\"blue\">Then</span>\n \n        <span class=\"blue\">Try</span>\n          param.Set(newLineStyleID)\n        <span class=\"blue\">Catch</span> ex <span class=\"blue\">As</span> Exception\n          MsgBox(ex.ToString)\n        <span class=\"blue\">End</span> <span class=\"blue\">Try</span>\n \n      <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n    <span class=\"blue\">Next</span>\n  <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n \n<span class=\"blue\">End</span> <span class=\"blue\">Sub</span>\n</pre>\n<p>Here is how I determined the right parameter, without searching for the language dependent string \"linestyle\":\n\n<pre class=\"code\">\n  <span class=\"blue\">If</span> param.Definition.ParameterGroup = BuiltInParameterGroup.PG_GRAPHICS _\n    <span class=\"blue\">And</span> <span class=\"blue\">Not</span> param.AsElementId.IntegerValue = -1 <span class=\"blue\">Then</span>\n</pre>\n<p>The portion above doesn't feel very clean to me.\nThoughts?\n\n<p>I don't feel confident that my routine won't come across some other (undesired) parameter that has no ID and is in PG_GRAPHICS.\nAm I somehow guaranteed that my test will come up with one and only one parameter (for that test)?\n(I suppose one thing I should do is research what it means to be 'PG_GRAPHICS').\n\n<p>I came up with the test while debugging.\nAt first I was only testing for PG_GRAPHICS.\nIt turned out that sometimes this caused errors (not all the time).\nI traced down the error and discovered that there were some parameters that met the PG_GRAPHICS test, but did not have an element ID (they were = -1).\n\n<p>What bothers me is that I don't know that other (possibly future) parameters won't pass both tests.\nDoes that make sense?\nIt seems to me there should be an absolute way to know if I've come across a parameter that holds the line style.\n\n<p>Oh ... it just occurred to me.\nMaybe I could check.\nMaybe after getting the ID  parameter that I suspect points to a line style parameter I could inspect that ID's element and verify that it is in fact a line style.\nIt seems odd that Revit would work that way internally though.\nThis does seem a bit inefficient, though.\n\n<p>I just don't know what I don't know here.\n\n<p>It does work, though, so far.\n\n<p><strong>Answer:</strong> All I can suggest is to add lots of\n\n<a href=\"http://en.wikipedia.org/wiki/Assertion_%28computing%29\">\nassertions</a> using\n\nthe System.Diagnostics namespace and the Debug.Assert method, and run the code on lots of large and varied test cases.\n\n<p><strong>Response:</strong> When I started this program (which is based on code I wrote some 15 years ago for AutoCAD), I looked around on the web and was surprised that I couldn't find any other apps (other than hatchkit) that did this.\nI would have done it anyway, just for the learning experience, and I'm glad I did.\nWow... there's nothing like reality.\n\n<p>So here's what I'm doing now.\nI feel more comfortable with it and it seems to work.\nStill testing though:\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Sub</span> changeLineStyleGeneric( _\n  <span class=\"blue\">ByVal</span> thisCurveElement <span class=\"blue\">As</span> CurveElement, _\n  <span class=\"blue\">ByRef</span> newLineStyleID <span class=\"blue\">As</span> ElementId)\n\n  <span class=\"blue\">Dim</span> param <span class=\"blue\">As</span> Parameter\n  <span class=\"blue\">Dim</span> parameters <span class=\"blue\">As</span> ParameterSet\n\n  <span class=\"blue\">If</span> <span class=\"blue\">Not</span> IsNothing(newLineStyleID) <span class=\"blue\">Then</span>\n    parameters = thisCurveElement.Parameters\n    <span class=\"blue\">For</span> <span class=\"blue\">Each</span> param <span class=\"blue\">In</span> parameters\n\n      <span class=\"green\">' a different approach:</span>\n      <span class=\"green\">' to make sure we have the correct parameter, </span>\n      <span class=\"green\">' make sure its value is the same as the known </span>\n      <span class=\"green\">' linestyle ID</span>\n\n      <span class=\"blue\">If</span> param.AsElementId = _\n        thisCurveElement.LineStyle.Id <span class=\"blue\">Then</span>\n\n        <span class=\"blue\">Try</span>\n          param.Set(newLineStyleID)\n        <span class=\"blue\">Catch</span> ex <span class=\"blue\">As</span> Exception\n          MsgBox(ex.ToString)\n        <span class=\"blue\">End</span> <span class=\"blue\">Try</span>\n\n      <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n    <span class=\"blue\">Next</span>\n  <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n<span class=\"blue\">End</span> <span class=\"blue\">Sub</span>\n</pre>\n<p>I changed my subs input parameter from Autodesk.Revit.DB.Element to Autodesk.Revit.DB.CurveElement.\nThis allows me to access thisCurveElement.LineStyle.Id which I then compare to the parameter value.\nIf they are equal, then I am confident that I have the correct parameter and I can assign my new linestyle ID to that parameter.\n\n<p>I looked to see if I could set thisCurveElement.LineStyle.ID directly, but it's read-only.\nI didn't see any other method for assigning the ID.\n\n<p>I also tried playing around with \"BuiltInParameter.BUILDING_CURVE_GSTYLE\" but couldn't get anywhere with that.\n\n<p>Makes sense?\n\n<p><strong>Answer:</strong> Have you checked the curve element parameters using the built-in parameter checker or RevitLookup snoop enum parameters?\n\n<p>As said, you should be able to determine what built-in parameter to use instead of looping through all of the parameters.\n\n<p>I did, in fact, and it looks like \"BuiltInParameter.BUILDING_CURVE_GSTYLE\"  may indeed be what you are looking for.\n\n<p>Although, on second thoughts, there are several others as well, which all refer to the line style element id.\nIn your loop you set all of them, not just one.\nMaybe it is necessary to set more than one of them, which is why your loop works and just setting \"BuiltInParameter.BUILDING_CURVE_GSTYLE\" does not.\nHere they all are for one detail curve I looked at, all have an ElementId storage type, are read-write, and refer to the GraphicsStyle 'Medium Lines' 185:\n\n<ul>\n<li>BUILDING_CURVE_GSTYLE: Line Style\n<li>BUILDING_CURVE_GSTYLE_PLUS_INVISIBLE: Subcategory\n<li>FAMILY_CURVE_GSTYLE_FOR_2010_MASS: Subcategory\n<li>FAMILY_CURVE_GSTYLE_PLUS_INVISIBLE: Subcategory\n<li>FAMILY_CURVE_GSTYLE_PLUS_INVISIBLE_PLUS_STICK_SYM: Subcategory\n<li>FAMILY_CURVE_GSTYLE_PLUS_INVISIBLE_MINUS_ANALYTICAL: Subcategory\n<li>FAMILY_CURVE_GSTYLE_PLUS_INVISIBLE_PLUS_STICK_SYM_MINUS_ANALYTICAL: Subcategory\n</li></li></li></li></li></li></li></ul>\n<p>I would eliminate the try-catch inside the loop, because that should only be used when it is absolutely unavoidable.\n\n<p>You could add a debug assertion to check that the value of the LineStyle.Id property really does equal the newly set one after changing it.\n\n<p><strong>Response:</strong> Continued thanks.\nRegarding the built-in parameter, I was not quite sure how to use it, so I did a search for \"BuiltInParameter\" in the \"Revit 2011 API\" chm.\nThe first item listed had the following sample code:\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Function</span> FindWithBuiltinParameterID( _\n  <span class=\"blue\">ByVal</span> wall <span class=\"blue\">As</span> Wall) <span class=\"blue\">As</span> Parameter\n \n  <span class=\"green\">' Use the WALL_BASE_OFFSET paramametId</span>\n  <span class=\"green\">' to get the base offset parameter of the wall.</span>\n\n  <span class=\"blue\">Dim</span> paraIndex <span class=\"blue\">As</span> BuiltInParameter _\n    = BuiltInParameter.WALL_BASE_OFFSET\n \n  <span class=\"blue\">Dim</span> parameter <span class=\"blue\">As</span> Parameter _\n    = wall.Parameter(paraIndex)\n \n  <span class=\"blue\">Return</span> parameter\n<span class=\"blue\">End</span> <span class=\"blue\">Function</span>\n</pre>\n<p>This translates easily to my case below:\n\n<pre class=\"code\">\n<span class=\"blue\">Public</span> <span class=\"blue\">Sub</span> ChangeLineStyleGeneric( _\n  <span class=\"blue\">ByVal</span> thisCurveElement <span class=\"blue\">As</span> CurveElement, _\n  <span class=\"blue\">ByRef</span> newLineStyleID <span class=\"blue\">As</span> ElementId)\n \n  <span class=\"blue\">If</span> <span class=\"blue\">Not</span> IsNothing(newLineStyleID) <span class=\"blue\">Then</span>\n    <span class=\"blue\">Dim</span> paraIndex <span class=\"blue\">As</span> BuiltInParameter _\n      = BuiltInParameter.BUILDING_CURVE_GSTYLE\n \n    <span class=\"blue\">Dim</span> parameter <span class=\"blue\">As</span> Parameter _\n      = thisCurveElement.Parameter(paraIndex)\n \n    parameter.Set(newLineStyleID)\n  <span class=\"blue\">End</span> <span class=\"blue\">If</span>\n \n<span class=\"blue\">End</span> <span class=\"blue\">Sub</span>\n</pre>\n<p>This seems to work.\n\n<p>Regarding the try/catch statement:\n\n<ol>\n<li>Why should that be avoided?\n<li>Is it ok to wrap the whole routine in one?\nIt is used on page 25 of the Revit 2011 API Developer Guide.pdf.\n</li></li></ol>\n<p>Regarding the parameter checker and snoop, I played  around a little.\nI had not noticed the \"Built-in Enums Snoop...\" button previously.\n\n<p>Wow... so much to learn!\n\n<p>Does \" BuiltInParamsChecker.vb\" provide me with any information that \"Revit Lookup\" does not?\n\n<p><strong>Answer:</strong>\n<ul>\n<li>Yes, indeed, the developer guide is an invaluable resource and should always be kept close at hand!\n<li>Every exception handler is resource intensive and will significantly slow down execution and consume resources.\nAn exception handler should be designed to handle unexpected, exceptional cases only.\n<a href=\"http://www.jacopretorius.net/2009/10/exceptions-should-be-exceptional.html\">Exceptions should be exceptional</a>.\nTherefore, it is normally sufficient to implement a single top-level handler at the level of the application mainline, e.g. in the external command Execute method.\n<li>The built-in parameter checker provides some addition functionality such as listing the built-in enumeration value, display name, data storage type, database value, string value etc. separately in independent columns and allowing you to sort on any of them.\nThat can make it much easier to find something you are looking for, especially in elements with numerous parameters attached.\n</li></li></li></ul>\n<p>The discussion and learning continues...\n\n<p>Wait, that's not all!\nHere is the complete utility that we are discussing:\n\n<h4>Hatch22 – a Revit Hatch Utility</h4>\n<p>Here is a free\n\n<a href=\"http://mertens3d.com/revit-2011-addin-portal/hatch22\">\nhatch utility</a> catchily named\n\n<a href=\"http://mertens3d.com/revit-2011-addin-portal/hatch22\">\nHatch22</a> that\n\nGregory is currently working on.\n\nI love Catch 22 by Joseph Heller, by the way!\n\n<!--\n<p>Gregory says: I loved the book too.\nI still remember reading it in college.\nI can picture myself sitting on the couch, laughing out loud and then coming to the part where ____ gets cut in half by the low flying airplane.\nI remember how unexpected that was and how much more powerful it was because of the humour that preceded it.\nIn case you don't know, he wrote a follow up book (\"Closing Time\") with many of the same characters.\nIt takes place years later. ...didn't interest me as much.\n-->\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0512_lang_indep_subcat",
    "header_text": "Hatch22 – a Revit Hatch Utility",
    "local_header_href": "#hatch22-a-revit-hatch-utility",
    "chunk_text": "<h4>Hatch22 – a Revit Hatch Utility</h4><p>Here is a free\n\n<a href=\"http://mertens3d.com/revit-2011-addin-portal/hatch22\">\nhatch utility</a> catchily named\n\n<a href=\"http://mertens3d.com/revit-2011-addin-portal/hatch22\">\nHatch22</a> that\n\nGregory is currently working on.\n\nI love Catch 22 by Joseph Heller, by the way!\n\n<!--\n<p>Gregory says: I loved the book too.\nI still remember reading it in college.\nI can picture myself sitting on the couch, laughing out loud and then coming to the part where ____ gets cut in half by the low flying airplane.\nI remember how unexpected that was and how much more powerful it was because of the humour that preceded it.\nIn case you don't know, he wrote a follow up book (\"Closing Time\") with many of the same characters.\nIt takes place years later. ...didn't interest me as much.\n-->\n</p>"
  }
]