[
  {
    "original_filename": "0596_create_extrusion_fam",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0596_create_extrusion_fam",
    "header_text": "Creating and Inserting an Extrusion Family",
    "local_header_href": "#creating-and-inserting-an-extrusion-family",
    "chunk_text": "<h3>Creating and Inserting an Extrusion Family</h3><p>Today is the \n\n<a href=\"http://en.wikipedia.org/wiki/Pentecost\">\nPentecost</a> or\n\n<a href=\"http://en.wikipedia.org/wiki/Whit_Monday\">\nWhit Monday</a> holiday\n\nin Neuchâtel, which gave me some time to explore an interesting and important issue in a bit more depth.\n\n<p>Several developers recently asked about creating families programmatically, so here is a first simple example to demonstrate this.\nIt creates a new structural stiffener family as an extrusion of a profile based on a list of XYZ points and inserts an instance of it into the current document.\nHere are the required steps one by one:\n\n<ol>\n<li><a href=\"#1\">Create an extrusion element from a profile based on a list of XYZ points</a>.\n<li><a href=\"#2\">Create a new structural stiffener family using the extrusion element</a>.\n<li><a href=\"#3\">Insert an instance of the new family into the current document</a>.\n</li></li></li></ol>\n<a name=\"1\"></a>\n<h4>1. Creating an Extrusion for a Profile</h4>\n<p>The extrusion profile is defined by a list of XYZ points, in millimetres.\nIn this example, we just use a very trivial rectangular shape.\nThe thickness is also given in millimetres:\n\n<pre class=\"code\">\n  <span class=\"blue\">static</span> <span class=\"blue\">int</span> n = 4;\n \n  <span class=\"blue\">static</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; _countour = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt;( n )\n  {\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0 , -75 , 0 ),\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 508, -75 , 0 ), \n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 508, 75 , 0 ),\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 75 , 0 )\n  };\n \n  <span class=\"blue\">const</span> <span class=\"blue\">double</span> _thicknessMm = 20.0; \n</pre>\n<p>Since all the input data is given in millimetres, and the extrusion has to be defined in the internal \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/01/unit-conversion-and-new-blogs.html\">Revit database unit</a> for \n\nlength, which is \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/internal-imperial-units.html\">feet</a>, \n\nwe need a conversion method for that, e.g.:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Conversion factor from millimetre to foot</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">const</span> <span class=\"blue\">double</span> _mm_to_foot = 1 / 304.8;\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given length to feet</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">double</span> MmToFoot( <span class=\"blue\">double</span> length_in_mm )\n  {\n    <span class=\"blue\">return</span> _mm_to_foot * length_in_mm;\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given point defined in millimetre units to feet</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">XYZ</span> MmToFootPoint( <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">return</span> p.Multiply( _mm_to_foot );\n  }\n</pre>\n<p>In order to create an extrusion from the contour data, we need a sketch plane and a CurveArrArray instance.\nThe curve array array contains a list of loops, since the extrusion may require an outer loop and optional inner loops representing cavities.\n\n<p>Here is a helper method to create  CurveArray from our XYZ point list:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given list of XYZ points </span>\n  <span class=\"gray\">///</span><span class=\"green\"> to a CurveArray instance. </span>\n  <span class=\"gray\">///</span><span class=\"green\"> The points are defined in millimetres, </span>\n  <span class=\"gray\">///</span><span class=\"green\"> the returned CurveArray in feet.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">CurveArray</span> CreateProfile( \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; pts, \n    <span class=\"teal\">CreationApplication</span> creapp )\n  {\n    <span class=\"teal\">CurveArray</span> profile = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"blue\">int</span> n = _countour.Count;\n \n    <span class=\"blue\">for</span>( <span class=\"blue\">int</span> i = 0; i &lt; n; ++i )\n    {\n      <span class=\"blue\">int</span> j = (0 == i) ? n - 1 : i - 1;\n \n      profile.Append( creapp.NewLineBound(\n        MmToFootPoint( pts[j] ), \n        MmToFootPoint( pts[i] ) ) );\n    }\n    <span class=\"blue\">return</span> profile;\n  }\n</pre>\n\nIn this case, the method is designed to work in a family based on the structural stiffener family template, which contains a sketch plane in the XY plane named \"Ref. Level\" that we can work with.\nActually, it redundantly contains three of them, and we can simply pick the first one.\nOne way to select the existing sketch plane if we know the exact structure of the document we are working with is to explicitly use a hard coded element id for it:\n\n<pre class=\"code\">\n  <span class=\"teal\">SketchPlane</span> sketch = doc.get_Element( \n    <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( 501 ) ) <span class=\"blue\">as</span> <span class=\"teal\">SketchPlane</span>;\n</pre>\n<p>That has the advantage of not being language dependent, but makes us completely dependent on the internal database structure of the family template file instead.\nA slightly more flexible approach is to search for the element by name using a helper function such as this:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return the first element found of the </span>\n  <span class=\"gray\">///</span><span class=\"green\"> specific target type with the given name.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">Element</span> FindElement(\n    <span class=\"teal\">Document</span> doc,\n    <span class=\"teal\">Type</span> targetType,\n    <span class=\"blue\">string</span> targetName )\n  {\n    <span class=\"blue\">return</span> <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( targetType )\n      .First&lt;<span class=\"teal\">Element</span>&gt;( e =&gt; e.Name.Equals( targetName ) );\n  }\n</pre>\n<p>This method is making use of <a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/language-integrated-query-linq.html\">LINQ</a>.\nA more efficient approach would use a filtered element collector based on a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/parameter-filter.html\">parameter</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/element-name-parameter-filter-correction.html\">filter</a> to \n\ncheck the name instead.\nThe advantage of that approach is that the filtering then happens on the internal Revit side, before the retrieved element data is passed out from Revit to the managed .NET environment.\nIn our case, there are not many sketch planes in the document to examine, so the overhead is negligible.\n\n<p>Using this method to find the sketch plane, and with the curve array and thickness in hand, the call to create the extrusion element in a family document can be set up like this:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Create an extrusion from a given thickness </span>\n  <span class=\"gray\">///</span><span class=\"green\"> and list of XYZ points defined in millimetres</span>\n  <span class=\"gray\">///</span><span class=\"green\"> in the given family document, which  must </span>\n  <span class=\"gray\">///</span><span class=\"green\"> contain a sketch plane named \"Ref. Level\".</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">Extrusion</span> CreateExtrusion( \n    <span class=\"teal\">Document</span> doc, \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; pts, \n    <span class=\"blue\">double</span> thickness )\n  {\n    <span class=\"teal\">FamilyItemFactory</span> factory = doc.FamilyCreate;\n \n    <span class=\"teal\">CreationApplication</span> creapp = doc.Application.Create;\n \n    <span class=\"teal\">SketchPlane</span> sketch = FindElement( doc, \n      <span class=\"blue\">typeof</span>( <span class=\"teal\">SketchPlane</span> ), <span class=\"maroon\">\"Ref. Level\"</span> ) \n        <span class=\"blue\">as</span> <span class=\"teal\">SketchPlane</span>;\n \n    <span class=\"teal\">CurveArrArray</span> curveArrArray = <span class=\"blue\">new</span> <span class=\"teal\">CurveArrArray</span>();\n \n    curveArrArray.Append( CreateProfile( pts, creapp ) );\n \n    <span class=\"blue\">double</span> extrusionHeight = MmToFoot( thickness );\n \n    <span class=\"blue\">return</span> factory.NewExtrusion( <span class=\"blue\">true</span>, \n      curveArrArray, sketch, extrusionHeight );\n  }\n</pre>\n<p>Next, let us see how to create a new family document in the background to make use of this method.\n\n\n<a name=\"2\"></a>\n<h4>2. Creating an Extrusion Family</h4>\n<p>Creating a new family to contain our extrusion is a simple process:\n\n<ul>\n<li>Open the appropriate family template file.\n<li>Create the extrusion.\n<li>Save and close the file.\n</li></li></li></ul>\n<p>In theory, it should be possible to avoid the last step of saving the newly generated family document to a disk file, since it is possible to load the generated family document into a project environment straight from memory.\nUnfortunately, I was unable to get this to work, because the call to 'fdoc.LoadFamily( doc )' caused a \"serious error\".\nSaving the family to a disk file and using 'doc.LoadFamily( filename, out family )' instead works, though.\n\n<p>It would also not be necessary to require a different file to be open to start with, but if it is not, it is impossible to close the family document.\nIt has to be closed, though, in order to use the new Revit 2012 API OpenAndActivateDocument method on it, in case we want to see the results of our new family definition in the family environment instead of looking at an insertion in the project environment.\n\n<pre class=\"code\">\n  <span class=\"blue\">string</span> templateFileName = <span class=\"teal\">Path</span>.Combine( _path,\n    _family_template_name + _family_template_ext );\n \n  <span class=\"teal\">Document</span> fdoc = app.NewFamilyDocument( \n    templateFileName );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == fdoc )\n  {\n    message = <span class=\"maroon\">\"Cannot create family document.\"</span>;\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n  }\n \n  <span class=\"teal\">Transaction</span> t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( fdoc,\n    <span class=\"maroon\">\"Create structural stiffener family\"</span> );\n \n  t.Start();\n \n  CreateExtrusion( fdoc, _countour, _thicknessMm );\n \n  t.Commit();\n \n  <span class=\"green\">// save our new family background document</span>\n  <span class=\"green\">// and reopen it in the Revit user interface:</span>\n \n  <span class=\"blue\">string</span> filename = <span class=\"teal\">Path</span>.Combine( \n    <span class=\"teal\">Path</span>.GetTempPath(), _family_name + _rfa_ext );\n \n  <span class=\"teal\">SaveAsOptions</span> opt = <span class=\"blue\">new</span> <span class=\"teal\">SaveAsOptions</span>();\n  opt.OverwriteExistingFile = <span class=\"blue\">true</span>;\n \n  fdoc.SaveAs( filename, opt );\n \n  <span class=\"green\">// cannot close the newly generated family file</span>\n  <span class=\"green\">// if it is the only open document; that throws </span>\n  <span class=\"green\">// an exception saying \"The active document may </span>\n  <span class=\"green\">// not be closed from the API.\"</span>\n \n  fdoc.Close( <span class=\"blue\">false</span> );\n</pre>\n<p>Now that the family has been created and save to a file, we can either add a call to open it programmatically in the foreground to view it using 'uiapp.OpenAndActivateDocument( filename )', or, assuming that we have an open active project document in the Revit user interface, immediately insert an instance of it.\nIn this case, let's go for the latter.\n\n\n<a name=\"3\"></a>\n<h4>3. Inserting an Instance of the New Family</h4>\n<p>Inserting a new family instance is something that we already covered numerous times in the past.\nThe last contribution on \n\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/placing-a-line-based-detail-item-instance.html\">\nplacing a line based detail item instance</a> points \n\nto some previous posts on this topic.\n\n<p>Here is an example of how we can place an instance of our newly created stiffener family into the current project at a selected point.\nWe make use of one of the simplest overloads of the NewFamilyInstance method taking just a point, the family symbol, and a structural type argument.\n\n<p>Before inserting the instance, we need to ensure that the family is in fact loaded at all.\n\n<p>Before loading the family, we need to check whether it has already been loaded.\nThis may happen, for instance, if the command is run multiple times.\n\n<p>Once loaded, we extract the family symbol from its container family, prompt the user for an insertion point, and create the new instance:\n\n<ul>\n<li>Start a transaction.\n<li>Retrieve all families.\n<li>Check whether the one we need has been loaded already.\n<li>If not, load it.\n<li>Extract its one and only symbol.\n<li>Insert an instance of it.\n</li></li></li></li></li></li></ul>\n<p>Here is the code to achieve these steps:\n\n<pre class=\"code\">\n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n    <span class=\"maroon\">\"Insert structural stiffener family instance\"</span> );\n \n  t.Start();\n \n  <span class=\"green\">// load the family ... but check whether </span>\n  <span class=\"green\">// it was already loaded first</span>\n \n  <span class=\"teal\">Family</span> family = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">FilteredElementCollector</span> a \n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Family</span> ) );\n \n  <span class=\"blue\">int</span> n = a.Count&lt;<span class=\"teal\">Element</span>&gt;( \n    e =&gt; e.Name.Equals( _family_name ) );\n \n  <span class=\"blue\">if</span>( 0 &lt; n )\n  {\n    family = a.First&lt;<span class=\"teal\">Element</span>&gt;(\n      e =&gt; e.Name.Equals( _family_name ) ) \n        <span class=\"blue\">as</span> <span class=\"teal\">Family</span>;\n  }\n  <span class=\"blue\">else</span>\n  {\n    <span class=\"green\">// calling this without a prior call </span>\n    <span class=\"green\">// to SaveAs causes a \"serious error\":</span>\n    <span class=\"green\">//family = fdoc.LoadFamily( doc ); </span>\n \n    doc.LoadFamily( filename, <span class=\"blue\">out</span> family );\n  }\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> family.Symbols )\n  {\n    symbol = s;\n \n    <span class=\"green\">// our family only contains one</span>\n    <span class=\"green\">// symbol, so pick it and leave</span>\n \n    <span class=\"blue\">break</span>;\n  }\n \n  <span class=\"teal\">XYZ</span> p = uidoc.Selection.PickPoint(\n    <span class=\"maroon\">\"Please pick a point for family instance insertion\"</span> );\n\n  <span class=\"teal\">StructuralType</span> st = <span class=\"teal\">StructuralType</span>.UnknownFraming;\n\n  doc.Create.NewFamilyInstance( p, symbol, st );\n\n  t.Commit();\n</pre>\n<p>The steps presented above answer a whole bunch of questions and should provide a good starting point for your own further explorations.\n\n<p>Here is <a href=\"zip/Stiffener02.zip\">Stifferener.zip</a> containing the complete source code and Visual Studio solution of the external command implementing them.\n\n<p>Another very common question in this area is how to perform Boolean operations, both in the family and project context.\nThat is a topic that I would like to take a look at in the near future, expanding on the example presented here.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0596_create_extrusion_fam",
    "header_text": "1. Creating an Extrusion for a Profile",
    "local_header_href": "#1-creating-an-extrusion-for-a-profile",
    "chunk_text": "<h4>1. Creating an Extrusion for a Profile</h4><p>The extrusion profile is defined by a list of XYZ points, in millimetres.\nIn this example, we just use a very trivial rectangular shape.\nThe thickness is also given in millimetres:\n\n<pre class=\"code\">\n  <span class=\"blue\">static</span> <span class=\"blue\">int</span> n = 4;\n \n  <span class=\"blue\">static</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; _countour = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt;( n )\n  {\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0 , -75 , 0 ),\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 508, -75 , 0 ), \n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 508, 75 , 0 ),\n    <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 75 , 0 )\n  };\n \n  <span class=\"blue\">const</span> <span class=\"blue\">double</span> _thicknessMm = 20.0; \n</pre>\n<p>Since all the input data is given in millimetres, and the extrusion has to be defined in the internal \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/01/unit-conversion-and-new-blogs.html\">Revit database unit</a> for \n\nlength, which is \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/internal-imperial-units.html\">feet</a>, \n\nwe need a conversion method for that, e.g.:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Conversion factor from millimetre to foot</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">const</span> <span class=\"blue\">double</span> _mm_to_foot = 1 / 304.8;\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given length to feet</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">double</span> MmToFoot( <span class=\"blue\">double</span> length_in_mm )\n  {\n    <span class=\"blue\">return</span> _mm_to_foot * length_in_mm;\n  }\n \n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given point defined in millimetre units to feet</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">XYZ</span> MmToFootPoint( <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">return</span> p.Multiply( _mm_to_foot );\n  }\n</pre>\n<p>In order to create an extrusion from the contour data, we need a sketch plane and a CurveArrArray instance.\nThe curve array array contains a list of loops, since the extrusion may require an outer loop and optional inner loops representing cavities.\n\n<p>Here is a helper method to create  CurveArray from our XYZ point list:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Convert a given list of XYZ points </span>\n  <span class=\"gray\">///</span><span class=\"green\"> to a CurveArray instance. </span>\n  <span class=\"gray\">///</span><span class=\"green\"> The points are defined in millimetres, </span>\n  <span class=\"gray\">///</span><span class=\"green\"> the returned CurveArray in feet.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">CurveArray</span> CreateProfile( \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; pts, \n    <span class=\"teal\">CreationApplication</span> creapp )\n  {\n    <span class=\"teal\">CurveArray</span> profile = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"blue\">int</span> n = _countour.Count;\n \n    <span class=\"blue\">for</span>( <span class=\"blue\">int</span> i = 0; i &lt; n; ++i )\n    {\n      <span class=\"blue\">int</span> j = (0 == i) ? n - 1 : i - 1;\n \n      profile.Append( creapp.NewLineBound(\n        MmToFootPoint( pts[j] ), \n        MmToFootPoint( pts[i] ) ) );\n    }\n    <span class=\"blue\">return</span> profile;\n  }\n</pre>\n\nIn this case, the method is designed to work in a family based on the structural stiffener family template, which contains a sketch plane in the XY plane named \"Ref. Level\" that we can work with.\nActually, it redundantly contains three of them, and we can simply pick the first one.\nOne way to select the existing sketch plane if we know the exact structure of the document we are working with is to explicitly use a hard coded element id for it:\n\n<pre class=\"code\">\n  <span class=\"teal\">SketchPlane</span> sketch = doc.get_Element( \n    <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( 501 ) ) <span class=\"blue\">as</span> <span class=\"teal\">SketchPlane</span>;\n</pre>\n<p>That has the advantage of not being language dependent, but makes us completely dependent on the internal database structure of the family template file instead.\nA slightly more flexible approach is to search for the element by name using a helper function such as this:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return the first element found of the </span>\n  <span class=\"gray\">///</span><span class=\"green\"> specific target type with the given name.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">Element</span> FindElement(\n    <span class=\"teal\">Document</span> doc,\n    <span class=\"teal\">Type</span> targetType,\n    <span class=\"blue\">string</span> targetName )\n  {\n    <span class=\"blue\">return</span> <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( targetType )\n      .First&lt;<span class=\"teal\">Element</span>&gt;( e =&gt; e.Name.Equals( targetName ) );\n  }\n</pre>\n<p>This method is making use of <a href=\"http://thebuildingcoder.typepad.com/blog/2009/07/language-integrated-query-linq.html\">LINQ</a>.\nA more efficient approach would use a filtered element collector based on a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/parameter-filter.html\">parameter</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/element-name-parameter-filter-correction.html\">filter</a> to \n\ncheck the name instead.\nThe advantage of that approach is that the filtering then happens on the internal Revit side, before the retrieved element data is passed out from Revit to the managed .NET environment.\nIn our case, there are not many sketch planes in the document to examine, so the overhead is negligible.\n\n<p>Using this method to find the sketch plane, and with the curve array and thickness in hand, the call to create the extrusion element in a family document can be set up like this:\n\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Create an extrusion from a given thickness </span>\n  <span class=\"gray\">///</span><span class=\"green\"> and list of XYZ points defined in millimetres</span>\n  <span class=\"gray\">///</span><span class=\"green\"> in the given family document, which  must </span>\n  <span class=\"gray\">///</span><span class=\"green\"> contain a sketch plane named \"Ref. Level\".</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">Extrusion</span> CreateExtrusion( \n    <span class=\"teal\">Document</span> doc, \n    <span class=\"teal\">List</span>&lt;<span class=\"teal\">XYZ</span>&gt; pts, \n    <span class=\"blue\">double</span> thickness )\n  {\n    <span class=\"teal\">FamilyItemFactory</span> factory = doc.FamilyCreate;\n \n    <span class=\"teal\">CreationApplication</span> creapp = doc.Application.Create;\n \n    <span class=\"teal\">SketchPlane</span> sketch = FindElement( doc, \n      <span class=\"blue\">typeof</span>( <span class=\"teal\">SketchPlane</span> ), <span class=\"maroon\">\"Ref. Level\"</span> ) \n        <span class=\"blue\">as</span> <span class=\"teal\">SketchPlane</span>;\n \n    <span class=\"teal\">CurveArrArray</span> curveArrArray = <span class=\"blue\">new</span> <span class=\"teal\">CurveArrArray</span>();\n \n    curveArrArray.Append( CreateProfile( pts, creapp ) );\n \n    <span class=\"blue\">double</span> extrusionHeight = MmToFoot( thickness );\n \n    <span class=\"blue\">return</span> factory.NewExtrusion( <span class=\"blue\">true</span>, \n      curveArrArray, sketch, extrusionHeight );\n  }\n</pre>\n<p>Next, let us see how to create a new family document in the background to make use of this method.\n\n\n<a name=\"2\"></a>\n<h4>2. Creating an Extrusion Family</h4>\n<p>Creating a new family to contain our extrusion is a simple process:\n\n<ul>\n<li>Open the appropriate family template file.\n<li>Create the extrusion.\n<li>Save and close the file.\n</li></li></li></ul>\n<p>In theory, it should be possible to avoid the last step of saving the newly generated family document to a disk file, since it is possible to load the generated family document into a project environment straight from memory.\nUnfortunately, I was unable to get this to work, because the call to 'fdoc.LoadFamily( doc )' caused a \"serious error\".\nSaving the family to a disk file and using 'doc.LoadFamily( filename, out family )' instead works, though.\n\n<p>It would also not be necessary to require a different file to be open to start with, but if it is not, it is impossible to close the family document.\nIt has to be closed, though, in order to use the new Revit 2012 API OpenAndActivateDocument method on it, in case we want to see the results of our new family definition in the family environment instead of looking at an insertion in the project environment.\n\n<pre class=\"code\">\n  <span class=\"blue\">string</span> templateFileName = <span class=\"teal\">Path</span>.Combine( _path,\n    _family_template_name + _family_template_ext );\n \n  <span class=\"teal\">Document</span> fdoc = app.NewFamilyDocument( \n    templateFileName );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == fdoc )\n  {\n    message = <span class=\"maroon\">\"Cannot create family document.\"</span>;\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n  }\n \n  <span class=\"teal\">Transaction</span> t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( fdoc,\n    <span class=\"maroon\">\"Create structural stiffener family\"</span> );\n \n  t.Start();\n \n  CreateExtrusion( fdoc, _countour, _thicknessMm );\n \n  t.Commit();\n \n  <span class=\"green\">// save our new family background document</span>\n  <span class=\"green\">// and reopen it in the Revit user interface:</span>\n \n  <span class=\"blue\">string</span> filename = <span class=\"teal\">Path</span>.Combine( \n    <span class=\"teal\">Path</span>.GetTempPath(), _family_name + _rfa_ext );\n \n  <span class=\"teal\">SaveAsOptions</span> opt = <span class=\"blue\">new</span> <span class=\"teal\">SaveAsOptions</span>();\n  opt.OverwriteExistingFile = <span class=\"blue\">true</span>;\n \n  fdoc.SaveAs( filename, opt );\n \n  <span class=\"green\">// cannot close the newly generated family file</span>\n  <span class=\"green\">// if it is the only open document; that throws </span>\n  <span class=\"green\">// an exception saying \"The active document may </span>\n  <span class=\"green\">// not be closed from the API.\"</span>\n \n  fdoc.Close( <span class=\"blue\">false</span> );\n</pre>\n<p>Now that the family has been created and save to a file, we can either add a call to open it programmatically in the foreground to view it using 'uiapp.OpenAndActivateDocument( filename )', or, assuming that we have an open active project document in the Revit user interface, immediately insert an instance of it.\nIn this case, let's go for the latter.\n\n\n<a name=\"3\"></a>\n<h4>3. Inserting an Instance of the New Family</h4>\n<p>Inserting a new family instance is something that we already covered numerous times in the past.\nThe last contribution on \n\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/placing-a-line-based-detail-item-instance.html\">\nplacing a line based detail item instance</a> points \n\nto some previous posts on this topic.\n\n<p>Here is an example of how we can place an instance of our newly created stiffener family into the current project at a selected point.\nWe make use of one of the simplest overloads of the NewFamilyInstance method taking just a point, the family symbol, and a structural type argument.\n\n<p>Before inserting the instance, we need to ensure that the family is in fact loaded at all.\n\n<p>Before loading the family, we need to check whether it has already been loaded.\nThis may happen, for instance, if the command is run multiple times.\n\n<p>Once loaded, we extract the family symbol from its container family, prompt the user for an insertion point, and create the new instance:\n\n<ul>\n<li>Start a transaction.\n<li>Retrieve all families.\n<li>Check whether the one we need has been loaded already.\n<li>If not, load it.\n<li>Extract its one and only symbol.\n<li>Insert an instance of it.\n</li></li></li></li></li></li></ul>\n<p>Here is the code to achieve these steps:\n\n<pre class=\"code\">\n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n    <span class=\"maroon\">\"Insert structural stiffener family instance\"</span> );\n \n  t.Start();\n \n  <span class=\"green\">// load the family ... but check whether </span>\n  <span class=\"green\">// it was already loaded first</span>\n \n  <span class=\"teal\">Family</span> family = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">FilteredElementCollector</span> a \n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Family</span> ) );\n \n  <span class=\"blue\">int</span> n = a.Count&lt;<span class=\"teal\">Element</span>&gt;( \n    e =&gt; e.Name.Equals( _family_name ) );\n \n  <span class=\"blue\">if</span>( 0 &lt; n )\n  {\n    family = a.First&lt;<span class=\"teal\">Element</span>&gt;(\n      e =&gt; e.Name.Equals( _family_name ) ) \n        <span class=\"blue\">as</span> <span class=\"teal\">Family</span>;\n  }\n  <span class=\"blue\">else</span>\n  {\n    <span class=\"green\">// calling this without a prior call </span>\n    <span class=\"green\">// to SaveAs causes a \"serious error\":</span>\n    <span class=\"green\">//family = fdoc.LoadFamily( doc ); </span>\n \n    doc.LoadFamily( filename, <span class=\"blue\">out</span> family );\n  }\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> family.Symbols )\n  {\n    symbol = s;\n \n    <span class=\"green\">// our family only contains one</span>\n    <span class=\"green\">// symbol, so pick it and leave</span>\n \n    <span class=\"blue\">break</span>;\n  }\n \n  <span class=\"teal\">XYZ</span> p = uidoc.Selection.PickPoint(\n    <span class=\"maroon\">\"Please pick a point for family instance insertion\"</span> );\n\n  <span class=\"teal\">StructuralType</span> st = <span class=\"teal\">StructuralType</span>.UnknownFraming;\n\n  doc.Create.NewFamilyInstance( p, symbol, st );\n\n  t.Commit();\n</pre>\n<p>The steps presented above answer a whole bunch of questions and should provide a good starting point for your own further explorations.\n\n<p>Here is <a href=\"zip/Stiffener02.zip\">Stifferener.zip</a> containing the complete source code and Visual Studio solution of the external command implementing them.\n\n<p>Another very common question in this area is how to perform Boolean operations, both in the family and project context.\nThat is a topic that I would like to take a look at in the near future, expanding on the example presented here.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0596_create_extrusion_fam",
    "header_text": "2. Creating an Extrusion Family",
    "local_header_href": "#2-creating-an-extrusion-family",
    "chunk_text": "<h4>2. Creating an Extrusion Family</h4><p>Creating a new family to contain our extrusion is a simple process:\n\n<ul>\n<li>Open the appropriate family template file.\n<li>Create the extrusion.\n<li>Save and close the file.\n</li></li></li></ul>\n<p>In theory, it should be possible to avoid the last step of saving the newly generated family document to a disk file, since it is possible to load the generated family document into a project environment straight from memory.\nUnfortunately, I was unable to get this to work, because the call to 'fdoc.LoadFamily( doc )' caused a \"serious error\".\nSaving the family to a disk file and using 'doc.LoadFamily( filename, out family )' instead works, though.\n\n<p>It would also not be necessary to require a different file to be open to start with, but if it is not, it is impossible to close the family document.\nIt has to be closed, though, in order to use the new Revit 2012 API OpenAndActivateDocument method on it, in case we want to see the results of our new family definition in the family environment instead of looking at an insertion in the project environment.\n\n<pre class=\"code\">\n  <span class=\"blue\">string</span> templateFileName = <span class=\"teal\">Path</span>.Combine( _path,\n    _family_template_name + _family_template_ext );\n \n  <span class=\"teal\">Document</span> fdoc = app.NewFamilyDocument( \n    templateFileName );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == fdoc )\n  {\n    message = <span class=\"maroon\">\"Cannot create family document.\"</span>;\n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n  }\n \n  <span class=\"teal\">Transaction</span> t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( fdoc,\n    <span class=\"maroon\">\"Create structural stiffener family\"</span> );\n \n  t.Start();\n \n  CreateExtrusion( fdoc, _countour, _thicknessMm );\n \n  t.Commit();\n \n  <span class=\"green\">// save our new family background document</span>\n  <span class=\"green\">// and reopen it in the Revit user interface:</span>\n \n  <span class=\"blue\">string</span> filename = <span class=\"teal\">Path</span>.Combine( \n    <span class=\"teal\">Path</span>.GetTempPath(), _family_name + _rfa_ext );\n \n  <span class=\"teal\">SaveAsOptions</span> opt = <span class=\"blue\">new</span> <span class=\"teal\">SaveAsOptions</span>();\n  opt.OverwriteExistingFile = <span class=\"blue\">true</span>;\n \n  fdoc.SaveAs( filename, opt );\n \n  <span class=\"green\">// cannot close the newly generated family file</span>\n  <span class=\"green\">// if it is the only open document; that throws </span>\n  <span class=\"green\">// an exception saying \"The active document may </span>\n  <span class=\"green\">// not be closed from the API.\"</span>\n \n  fdoc.Close( <span class=\"blue\">false</span> );\n</pre>\n<p>Now that the family has been created and save to a file, we can either add a call to open it programmatically in the foreground to view it using 'uiapp.OpenAndActivateDocument( filename )', or, assuming that we have an open active project document in the Revit user interface, immediately insert an instance of it.\nIn this case, let's go for the latter.\n\n\n<a name=\"3\"></a>\n<h4>3. Inserting an Instance of the New Family</h4>\n<p>Inserting a new family instance is something that we already covered numerous times in the past.\nThe last contribution on \n\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/placing-a-line-based-detail-item-instance.html\">\nplacing a line based detail item instance</a> points \n\nto some previous posts on this topic.\n\n<p>Here is an example of how we can place an instance of our newly created stiffener family into the current project at a selected point.\nWe make use of one of the simplest overloads of the NewFamilyInstance method taking just a point, the family symbol, and a structural type argument.\n\n<p>Before inserting the instance, we need to ensure that the family is in fact loaded at all.\n\n<p>Before loading the family, we need to check whether it has already been loaded.\nThis may happen, for instance, if the command is run multiple times.\n\n<p>Once loaded, we extract the family symbol from its container family, prompt the user for an insertion point, and create the new instance:\n\n<ul>\n<li>Start a transaction.\n<li>Retrieve all families.\n<li>Check whether the one we need has been loaded already.\n<li>If not, load it.\n<li>Extract its one and only symbol.\n<li>Insert an instance of it.\n</li></li></li></li></li></li></ul>\n<p>Here is the code to achieve these steps:\n\n<pre class=\"code\">\n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n    <span class=\"maroon\">\"Insert structural stiffener family instance\"</span> );\n \n  t.Start();\n \n  <span class=\"green\">// load the family ... but check whether </span>\n  <span class=\"green\">// it was already loaded first</span>\n \n  <span class=\"teal\">Family</span> family = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">FilteredElementCollector</span> a \n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Family</span> ) );\n \n  <span class=\"blue\">int</span> n = a.Count&lt;<span class=\"teal\">Element</span>&gt;( \n    e =&gt; e.Name.Equals( _family_name ) );\n \n  <span class=\"blue\">if</span>( 0 &lt; n )\n  {\n    family = a.First&lt;<span class=\"teal\">Element</span>&gt;(\n      e =&gt; e.Name.Equals( _family_name ) ) \n        <span class=\"blue\">as</span> <span class=\"teal\">Family</span>;\n  }\n  <span class=\"blue\">else</span>\n  {\n    <span class=\"green\">// calling this without a prior call </span>\n    <span class=\"green\">// to SaveAs causes a \"serious error\":</span>\n    <span class=\"green\">//family = fdoc.LoadFamily( doc ); </span>\n \n    doc.LoadFamily( filename, <span class=\"blue\">out</span> family );\n  }\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> family.Symbols )\n  {\n    symbol = s;\n \n    <span class=\"green\">// our family only contains one</span>\n    <span class=\"green\">// symbol, so pick it and leave</span>\n \n    <span class=\"blue\">break</span>;\n  }\n \n  <span class=\"teal\">XYZ</span> p = uidoc.Selection.PickPoint(\n    <span class=\"maroon\">\"Please pick a point for family instance insertion\"</span> );\n\n  <span class=\"teal\">StructuralType</span> st = <span class=\"teal\">StructuralType</span>.UnknownFraming;\n\n  doc.Create.NewFamilyInstance( p, symbol, st );\n\n  t.Commit();\n</pre>\n<p>The steps presented above answer a whole bunch of questions and should provide a good starting point for your own further explorations.\n\n<p>Here is <a href=\"zip/Stiffener02.zip\">Stifferener.zip</a> containing the complete source code and Visual Studio solution of the external command implementing them.\n\n<p>Another very common question in this area is how to perform Boolean operations, both in the family and project context.\nThat is a topic that I would like to take a look at in the near future, expanding on the example presented here.\n</p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0596_create_extrusion_fam",
    "header_text": "3. Inserting an Instance of the New Family",
    "local_header_href": "#3-inserting-an-instance-of-the-new-family",
    "chunk_text": "<h4>3. Inserting an Instance of the New Family</h4><p>Inserting a new family instance is something that we already covered numerous times in the past.\nThe last contribution on \n\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/placing-a-line-based-detail-item-instance.html\">\nplacing a line based detail item instance</a> points \n\nto some previous posts on this topic.\n\n<p>Here is an example of how we can place an instance of our newly created stiffener family into the current project at a selected point.\nWe make use of one of the simplest overloads of the NewFamilyInstance method taking just a point, the family symbol, and a structural type argument.\n\n<p>Before inserting the instance, we need to ensure that the family is in fact loaded at all.\n\n<p>Before loading the family, we need to check whether it has already been loaded.\nThis may happen, for instance, if the command is run multiple times.\n\n<p>Once loaded, we extract the family symbol from its container family, prompt the user for an insertion point, and create the new instance:\n\n<ul>\n<li>Start a transaction.\n<li>Retrieve all families.\n<li>Check whether the one we need has been loaded already.\n<li>If not, load it.\n<li>Extract its one and only symbol.\n<li>Insert an instance of it.\n</li></li></li></li></li></li></ul>\n<p>Here is the code to achieve these steps:\n\n<pre class=\"code\">\n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n    <span class=\"maroon\">\"Insert structural stiffener family instance\"</span> );\n \n  t.Start();\n \n  <span class=\"green\">// load the family ... but check whether </span>\n  <span class=\"green\">// it was already loaded first</span>\n \n  <span class=\"teal\">Family</span> family = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">FilteredElementCollector</span> a \n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Family</span> ) );\n \n  <span class=\"blue\">int</span> n = a.Count&lt;<span class=\"teal\">Element</span>&gt;( \n    e =&gt; e.Name.Equals( _family_name ) );\n \n  <span class=\"blue\">if</span>( 0 &lt; n )\n  {\n    family = a.First&lt;<span class=\"teal\">Element</span>&gt;(\n      e =&gt; e.Name.Equals( _family_name ) ) \n        <span class=\"blue\">as</span> <span class=\"teal\">Family</span>;\n  }\n  <span class=\"blue\">else</span>\n  {\n    <span class=\"green\">// calling this without a prior call </span>\n    <span class=\"green\">// to SaveAs causes a \"serious error\":</span>\n    <span class=\"green\">//family = fdoc.LoadFamily( doc ); </span>\n \n    doc.LoadFamily( filename, <span class=\"blue\">out</span> family );\n  }\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> family.Symbols )\n  {\n    symbol = s;\n \n    <span class=\"green\">// our family only contains one</span>\n    <span class=\"green\">// symbol, so pick it and leave</span>\n \n    <span class=\"blue\">break</span>;\n  }\n \n  <span class=\"teal\">XYZ</span> p = uidoc.Selection.PickPoint(\n    <span class=\"maroon\">\"Please pick a point for family instance insertion\"</span> );\n\n  <span class=\"teal\">StructuralType</span> st = <span class=\"teal\">StructuralType</span>.UnknownFraming;\n\n  doc.Create.NewFamilyInstance( p, symbol, st );\n\n  t.Commit();\n</pre>\n<p>The steps presented above answer a whole bunch of questions and should provide a good starting point for your own further explorations.\n\n<p>Here is <a href=\"zip/Stiffener02.zip\">Stifferener.zip</a> containing the complete source code and Visual Studio solution of the external command implementing them.\n\n<p>Another very common question in this area is how to perform Boolean operations, both in the family and project context.\nThat is a topic that I would like to take a look at in the near future, expanding on the example presented here.\n</p></p></p></p></p></p></p></p></p>"
  }
]