[
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "The Revit Structure 2012 API",
    "local_header_href": "#the-revit-structure-2012-api",
    "chunk_text": "<h3>The Revit Structure 2012 API</h3><p>Sangsen recently submitted a\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\n\">\ncouple</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">of</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">comments</a> which\n\nmade it clear that a short overview of the new features of the Revit Structure 2012 API is overdue\n(see <a href=\"#2\">below</a> for the <a href=\"#2\">Q &amp; A</a>).\n\n<p>Here is a description written by Joe Ye for our Spring 2011 ADN AEC newsletter:\n\n<h4>Autodesk Revit Structure 2012 API Migration Tips</h4>\n<p>This article discusses changes made to the Revit Structure 2012 API.\nWe will quickly go over the list of items which have been changed, and look at the changes around rebar API in more detail.\n\n<h4>Overview of Revit Structure 2012 API Changes</h4>\n<p>The following is the list of changes made to the Revit Structure 2012 API:\n\n<ul>\n<li>Analytical model – analytical model class is now a subclass of Element. As a consequence of this change, when you create a new structural element, you will need to call Documentation.Regenerate() method before accessing its analytical model; i.e., the analytical model needs to be created first. Methods to access properties of an analytical model stay the same.\n\n<li>AnalyticalModelSelector – two constructors that take an index as an argument has been removed. You should use the version that accepts the curve directly.\n\n<li>SlabFoundationType – the enumeration value SlabFoundationType.Slab is now renamed as SlabOneWay. An additional option, SlabTwoWay has been added.\n\n<li>Track changes UI – Track change UI has been removed. If you wish to offer a similar functionality, you can implement a similar or more sophisticated functionality using transactions, events and updaters, aligning the Undo mechanism that the end user is familiar with.\n\n<li>NewBeamSystem() – this method accepts either sketch planes or the level.\n\n<li>NewTruss() – this method requires sketch plane as an argument.\n\n<li>Rebars and rebar shapes - syntaxes for creating rebar and rebar shape have been changed. The changes results in a simplified API, which is aligned to the UI.\n\n</li></li></li></li></li></li></li></ul>\n<p>Below, we discuss rebar changes.\n\n\n<h4>Migrating Rebar API Codes</h4>\n<p>If you have a code that creates a rebar shape in Revit Structure 2011, you will need to migrate it to use it in Revit Structure 2012.\nHere are the main changes in the steps to create a rebar shape:\n\n<p>In 2011,\n\n<ol>\n<li>Create a RebarShape inside the Document.\n<li>Create a RebarShapeDefinition inside the RebarShape.\n<li>Add data to the RebarShapeDefinition.\n<li>Commit the RebarShape.\n</li></li></li></li></ol>\n<p>In 2012,\n\n<ol>\n<li>Create a RebarShapeDefinition. It refers to the Document, but is not inside the document.\n<li>Add data to the RebarShapeDefinition.\n<li>Create a RebarShape inside the Document based on the RebarShapeDefinition. Only now the document is modified.\n</li></li></li></ol>\n<p>In addition, the following methods are replaced by new ones:\n\n<ul>\n<li>Autodesk.Revit.Creation.Document.NewRebarShape method <br/>&gt;\nRebarShape.Create(Document, RebarShapeDefinition, ... )\n\n<li>RebarShape.NewDefinitionBySegments method <br/>&gt;\nRebarShapeDefinitionBySegments constructor\n\n<li>RebarShape.NewDefinitionByArc method <br/>&gt;\nRebarShapeDefinitionByArc constructors\n</li></li></li></ul>\n<h4>Example: Migrating the RST Labs Code</h4>\n<p>Now, let's take a look at how to apply these changes to the rebar shape code, using our RST training labs code as an example. Here is the code for 2011, omitting some parameter definitions for simplicity:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in Revit Structure 2011</span>\n \n[<span class=\"teal\">Transaction</span>(<span class=\"teal\">TransactionMode</span>.Manual)]\n[<span class=\"teal\">Regeneration</span>(<span class=\"teal\">RegenerationOption</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateSimpleRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n  <span class=\"teal\">ElementSet</span> elements)\n{\n  <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n  <span class=\"teal\">Application</span> app = uiApp.Application;\n  <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"Lab4_2\"</span> );\n  trans.Start();\n \n  <span class=\"green\">// Create a newrebarshape.</span>\n \n  <span class=\"teal\">RebarShape</span> oRebarShape = doc.Create.NewRebarShape();\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n \n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n    = oRebarShape.NewDefinitionBySegments( 5 );\n \n  <span class=\"green\">// Add parameters with default value.</span>\n  <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def \n    = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter(def, 280);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.AddConstraintParallelToSegment( \n    0, pA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n  oRebarShape.set_HookAngle(0, 180);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.Commit();\n  trans.Commit();\n  shapeDef.CheckDefaultParameterValues( 0, 0 );\n \n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>Several lines above require changes in 2012.\n\n<p>First, remove the lines with Create.NewRebarShape(). We will add code of creating rebar shape later on via new method later:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = doc.Create.NewRebarShape(); <span class=\"green\">// Remove these lines</span>\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n</pre>\n<p>Replace the code creating RebarShapeDefinitionBySegments instance to use the constructor:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = oRebarShape.NewDefinitionBySegments( 5 ); <span class=\"green\">// 2011</span>\n</pre>\n<p>with this:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>( doc, 5 ); <span class=\"green\">// 2012</span>\n</pre>\n<p>The steps to create each shape segment are unchanged. However, in 2012, methods used to define rebar segment only accept ElementId as an argument instead of External Definition in 2011. Methods in RebarShapeParameters class provide a utility method to retrieve an element id of an external definition. We need to get the corresponding element id, and replace the reference to the parameter value (e.g., 'pA') with its corresponding ElementId variable (e.g., 'idA') in AddParameter() method a shape definition. For instance, original code like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2011.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter( def, 280 );\n</pre>\n<p>Will be modified like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2012.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n    .GetOrCreateElementIdForExternalDefinition( doc, def );\n \n  shapeDef.AddParameter( idA, 280 );\n</pre>\n<p>The RebarShape class provides a static method to create a RebarShape instance in 2012. \nThis method accommodates parameters to define the rebar shape's hook and hook angle. \nThe methods to set hook properties are removed. \nPut all the rebar shape properties in the call to the Create method. \nAfter you have defined the rebar segment, add the following line to create the rebar shape:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = <span class=\"teal\">RebarShape</span>.Create( doc,\n      shapeDef, <span class=\"blue\">null</span>, <span class=\"teal\">RebarStyle</span>.Standard,\n      <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      0 );\n</pre>\n<p>The RebarShapeDefinitionBySegments.Commit method is removed in Revit 2012.\nYou can simply delete it:\n\n<pre class=\"code\">\n  shapeDef.Commit(); <span class=\"green\">// take out this line</span>\n</pre>\n<p>That's it! Here is the final code in 2012, again keeping only one parameter to emphasize the changes we made:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in 2012</span>\n<span class=\"green\">//</span>\n[Transaction(<span class=\"teal\">TransactionMode</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n    <span class=\"teal\">Application</span> app = uiApp.Application;\n    <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(doc, <span class=\"maroon\">\"Lab4_1\"</span>);\n    trans.Start();\n \n    <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n      = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>(doc, 5);\n \n    <span class=\"green\">// Add parameters with default value.</span>\n \n    <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n    <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n    <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n      .GetOrCreateElementIdForExternalDefinition(\n        doc, def);\n \n    shapeDef.AddParameter(idA, 280);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Add constraints</span>\n \n    shapeDef.AddConstraintParallelToSegment(0, idA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Create a newrebarshape.</span>\n \n    <span class=\"teal\">RebarShape</span> oRebarShape = <span class=\"teal\">RebarShape</span>\n      .Create( doc, shapeDef, <span class=\"blue\">null</span>, \n        <span class=\"teal\">RebarStyle</span>.Standard,\n        <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        0 );\n \n    trans.Commit();\n \n    shapeDef.CheckDefaultParameterValues(0, 0);\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>All the API changes are documented in the 'Revit Platform API Changes and Additions.docx' and the 'What's New' section of the Revit API help file RevitAPI.chm provided with the Revit 2012 SDK. \nPlease refer to those for more information about the usage of individual classes and methods.\n\n<p>Many thanks to Joe for this overview!\n\n<p>Some of the Revit Structure API changes were also discussed in the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html#2\">Revit 2012 API webcast</a> and the associated materials.\n\n\n<a name=\"2\"></a>\n<h4>Sangsen's Questions</h4>\n<p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Autodesk Revit Structure 2012 API Migration Tips",
    "local_header_href": "#autodesk-revit-structure-2012-api-migration-tips",
    "chunk_text": "<h4>Autodesk Revit Structure 2012 API Migration Tips</h4><p>This article discusses changes made to the Revit Structure 2012 API.\nWe will quickly go over the list of items which have been changed, and look at the changes around rebar API in more detail.\n\n<h4>Overview of Revit Structure 2012 API Changes</h4>\n<p>The following is the list of changes made to the Revit Structure 2012 API:\n\n<ul>\n<li>Analytical model – analytical model class is now a subclass of Element. As a consequence of this change, when you create a new structural element, you will need to call Documentation.Regenerate() method before accessing its analytical model; i.e., the analytical model needs to be created first. Methods to access properties of an analytical model stay the same.\n\n<li>AnalyticalModelSelector – two constructors that take an index as an argument has been removed. You should use the version that accepts the curve directly.\n\n<li>SlabFoundationType – the enumeration value SlabFoundationType.Slab is now renamed as SlabOneWay. An additional option, SlabTwoWay has been added.\n\n<li>Track changes UI – Track change UI has been removed. If you wish to offer a similar functionality, you can implement a similar or more sophisticated functionality using transactions, events and updaters, aligning the Undo mechanism that the end user is familiar with.\n\n<li>NewBeamSystem() – this method accepts either sketch planes or the level.\n\n<li>NewTruss() – this method requires sketch plane as an argument.\n\n<li>Rebars and rebar shapes - syntaxes for creating rebar and rebar shape have been changed. The changes results in a simplified API, which is aligned to the UI.\n\n</li></li></li></li></li></li></li></ul>\n<p>Below, we discuss rebar changes.\n\n\n<h4>Migrating Rebar API Codes</h4>\n<p>If you have a code that creates a rebar shape in Revit Structure 2011, you will need to migrate it to use it in Revit Structure 2012.\nHere are the main changes in the steps to create a rebar shape:\n\n<p>In 2011,\n\n<ol>\n<li>Create a RebarShape inside the Document.\n<li>Create a RebarShapeDefinition inside the RebarShape.\n<li>Add data to the RebarShapeDefinition.\n<li>Commit the RebarShape.\n</li></li></li></li></ol>\n<p>In 2012,\n\n<ol>\n<li>Create a RebarShapeDefinition. It refers to the Document, but is not inside the document.\n<li>Add data to the RebarShapeDefinition.\n<li>Create a RebarShape inside the Document based on the RebarShapeDefinition. Only now the document is modified.\n</li></li></li></ol>\n<p>In addition, the following methods are replaced by new ones:\n\n<ul>\n<li>Autodesk.Revit.Creation.Document.NewRebarShape method <br/>&gt;\nRebarShape.Create(Document, RebarShapeDefinition, ... )\n\n<li>RebarShape.NewDefinitionBySegments method <br/>&gt;\nRebarShapeDefinitionBySegments constructor\n\n<li>RebarShape.NewDefinitionByArc method <br/>&gt;\nRebarShapeDefinitionByArc constructors\n</li></li></li></ul>\n<h4>Example: Migrating the RST Labs Code</h4>\n<p>Now, let's take a look at how to apply these changes to the rebar shape code, using our RST training labs code as an example. Here is the code for 2011, omitting some parameter definitions for simplicity:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in Revit Structure 2011</span>\n \n[<span class=\"teal\">Transaction</span>(<span class=\"teal\">TransactionMode</span>.Manual)]\n[<span class=\"teal\">Regeneration</span>(<span class=\"teal\">RegenerationOption</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateSimpleRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n  <span class=\"teal\">ElementSet</span> elements)\n{\n  <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n  <span class=\"teal\">Application</span> app = uiApp.Application;\n  <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"Lab4_2\"</span> );\n  trans.Start();\n \n  <span class=\"green\">// Create a newrebarshape.</span>\n \n  <span class=\"teal\">RebarShape</span> oRebarShape = doc.Create.NewRebarShape();\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n \n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n    = oRebarShape.NewDefinitionBySegments( 5 );\n \n  <span class=\"green\">// Add parameters with default value.</span>\n  <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def \n    = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter(def, 280);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.AddConstraintParallelToSegment( \n    0, pA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n  oRebarShape.set_HookAngle(0, 180);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.Commit();\n  trans.Commit();\n  shapeDef.CheckDefaultParameterValues( 0, 0 );\n \n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>Several lines above require changes in 2012.\n\n<p>First, remove the lines with Create.NewRebarShape(). We will add code of creating rebar shape later on via new method later:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = doc.Create.NewRebarShape(); <span class=\"green\">// Remove these lines</span>\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n</pre>\n<p>Replace the code creating RebarShapeDefinitionBySegments instance to use the constructor:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = oRebarShape.NewDefinitionBySegments( 5 ); <span class=\"green\">// 2011</span>\n</pre>\n<p>with this:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>( doc, 5 ); <span class=\"green\">// 2012</span>\n</pre>\n<p>The steps to create each shape segment are unchanged. However, in 2012, methods used to define rebar segment only accept ElementId as an argument instead of External Definition in 2011. Methods in RebarShapeParameters class provide a utility method to retrieve an element id of an external definition. We need to get the corresponding element id, and replace the reference to the parameter value (e.g., 'pA') with its corresponding ElementId variable (e.g., 'idA') in AddParameter() method a shape definition. For instance, original code like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2011.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter( def, 280 );\n</pre>\n<p>Will be modified like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2012.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n    .GetOrCreateElementIdForExternalDefinition( doc, def );\n \n  shapeDef.AddParameter( idA, 280 );\n</pre>\n<p>The RebarShape class provides a static method to create a RebarShape instance in 2012. \nThis method accommodates parameters to define the rebar shape's hook and hook angle. \nThe methods to set hook properties are removed. \nPut all the rebar shape properties in the call to the Create method. \nAfter you have defined the rebar segment, add the following line to create the rebar shape:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = <span class=\"teal\">RebarShape</span>.Create( doc,\n      shapeDef, <span class=\"blue\">null</span>, <span class=\"teal\">RebarStyle</span>.Standard,\n      <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      0 );\n</pre>\n<p>The RebarShapeDefinitionBySegments.Commit method is removed in Revit 2012.\nYou can simply delete it:\n\n<pre class=\"code\">\n  shapeDef.Commit(); <span class=\"green\">// take out this line</span>\n</pre>\n<p>That's it! Here is the final code in 2012, again keeping only one parameter to emphasize the changes we made:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in 2012</span>\n<span class=\"green\">//</span>\n[Transaction(<span class=\"teal\">TransactionMode</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n    <span class=\"teal\">Application</span> app = uiApp.Application;\n    <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(doc, <span class=\"maroon\">\"Lab4_1\"</span>);\n    trans.Start();\n \n    <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n      = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>(doc, 5);\n \n    <span class=\"green\">// Add parameters with default value.</span>\n \n    <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n    <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n    <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n      .GetOrCreateElementIdForExternalDefinition(\n        doc, def);\n \n    shapeDef.AddParameter(idA, 280);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Add constraints</span>\n \n    shapeDef.AddConstraintParallelToSegment(0, idA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Create a newrebarshape.</span>\n \n    <span class=\"teal\">RebarShape</span> oRebarShape = <span class=\"teal\">RebarShape</span>\n      .Create( doc, shapeDef, <span class=\"blue\">null</span>, \n        <span class=\"teal\">RebarStyle</span>.Standard,\n        <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        0 );\n \n    trans.Commit();\n \n    shapeDef.CheckDefaultParameterValues(0, 0);\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>All the API changes are documented in the 'Revit Platform API Changes and Additions.docx' and the 'What's New' section of the Revit API help file RevitAPI.chm provided with the Revit 2012 SDK. \nPlease refer to those for more information about the usage of individual classes and methods.\n\n<p>Many thanks to Joe for this overview!\n\n<p>Some of the Revit Structure API changes were also discussed in the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html#2\">Revit 2012 API webcast</a> and the associated materials.\n\n\n<a name=\"2\"></a>\n<h4>Sangsen's Questions</h4>\n<p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Overview of Revit Structure 2012 API Changes",
    "local_header_href": "#overview-of-revit-structure-2012-api-changes",
    "chunk_text": "<h4>Overview of Revit Structure 2012 API Changes</h4><p>The following is the list of changes made to the Revit Structure 2012 API:\n\n<ul>\n<li>Analytical model – analytical model class is now a subclass of Element. As a consequence of this change, when you create a new structural element, you will need to call Documentation.Regenerate() method before accessing its analytical model; i.e., the analytical model needs to be created first. Methods to access properties of an analytical model stay the same.\n\n<li>AnalyticalModelSelector – two constructors that take an index as an argument has been removed. You should use the version that accepts the curve directly.\n\n<li>SlabFoundationType – the enumeration value SlabFoundationType.Slab is now renamed as SlabOneWay. An additional option, SlabTwoWay has been added.\n\n<li>Track changes UI – Track change UI has been removed. If you wish to offer a similar functionality, you can implement a similar or more sophisticated functionality using transactions, events and updaters, aligning the Undo mechanism that the end user is familiar with.\n\n<li>NewBeamSystem() – this method accepts either sketch planes or the level.\n\n<li>NewTruss() – this method requires sketch plane as an argument.\n\n<li>Rebars and rebar shapes - syntaxes for creating rebar and rebar shape have been changed. The changes results in a simplified API, which is aligned to the UI.\n\n</li></li></li></li></li></li></li></ul>\n<p>Below, we discuss rebar changes.\n\n\n<h4>Migrating Rebar API Codes</h4>\n<p>If you have a code that creates a rebar shape in Revit Structure 2011, you will need to migrate it to use it in Revit Structure 2012.\nHere are the main changes in the steps to create a rebar shape:\n\n<p>In 2011,\n\n<ol>\n<li>Create a RebarShape inside the Document.\n<li>Create a RebarShapeDefinition inside the RebarShape.\n<li>Add data to the RebarShapeDefinition.\n<li>Commit the RebarShape.\n</li></li></li></li></ol>\n<p>In 2012,\n\n<ol>\n<li>Create a RebarShapeDefinition. It refers to the Document, but is not inside the document.\n<li>Add data to the RebarShapeDefinition.\n<li>Create a RebarShape inside the Document based on the RebarShapeDefinition. Only now the document is modified.\n</li></li></li></ol>\n<p>In addition, the following methods are replaced by new ones:\n\n<ul>\n<li>Autodesk.Revit.Creation.Document.NewRebarShape method <br/>&gt;\nRebarShape.Create(Document, RebarShapeDefinition, ... )\n\n<li>RebarShape.NewDefinitionBySegments method <br/>&gt;\nRebarShapeDefinitionBySegments constructor\n\n<li>RebarShape.NewDefinitionByArc method <br/>&gt;\nRebarShapeDefinitionByArc constructors\n</li></li></li></ul>\n<h4>Example: Migrating the RST Labs Code</h4>\n<p>Now, let's take a look at how to apply these changes to the rebar shape code, using our RST training labs code as an example. Here is the code for 2011, omitting some parameter definitions for simplicity:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in Revit Structure 2011</span>\n \n[<span class=\"teal\">Transaction</span>(<span class=\"teal\">TransactionMode</span>.Manual)]\n[<span class=\"teal\">Regeneration</span>(<span class=\"teal\">RegenerationOption</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateSimpleRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n  <span class=\"teal\">ElementSet</span> elements)\n{\n  <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n  <span class=\"teal\">Application</span> app = uiApp.Application;\n  <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"Lab4_2\"</span> );\n  trans.Start();\n \n  <span class=\"green\">// Create a newrebarshape.</span>\n \n  <span class=\"teal\">RebarShape</span> oRebarShape = doc.Create.NewRebarShape();\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n \n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n    = oRebarShape.NewDefinitionBySegments( 5 );\n \n  <span class=\"green\">// Add parameters with default value.</span>\n  <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def \n    = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter(def, 280);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.AddConstraintParallelToSegment( \n    0, pA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n  oRebarShape.set_HookAngle(0, 180);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.Commit();\n  trans.Commit();\n  shapeDef.CheckDefaultParameterValues( 0, 0 );\n \n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>Several lines above require changes in 2012.\n\n<p>First, remove the lines with Create.NewRebarShape(). We will add code of creating rebar shape later on via new method later:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = doc.Create.NewRebarShape(); <span class=\"green\">// Remove these lines</span>\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n</pre>\n<p>Replace the code creating RebarShapeDefinitionBySegments instance to use the constructor:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = oRebarShape.NewDefinitionBySegments( 5 ); <span class=\"green\">// 2011</span>\n</pre>\n<p>with this:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>( doc, 5 ); <span class=\"green\">// 2012</span>\n</pre>\n<p>The steps to create each shape segment are unchanged. However, in 2012, methods used to define rebar segment only accept ElementId as an argument instead of External Definition in 2011. Methods in RebarShapeParameters class provide a utility method to retrieve an element id of an external definition. We need to get the corresponding element id, and replace the reference to the parameter value (e.g., 'pA') with its corresponding ElementId variable (e.g., 'idA') in AddParameter() method a shape definition. For instance, original code like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2011.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter( def, 280 );\n</pre>\n<p>Will be modified like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2012.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n    .GetOrCreateElementIdForExternalDefinition( doc, def );\n \n  shapeDef.AddParameter( idA, 280 );\n</pre>\n<p>The RebarShape class provides a static method to create a RebarShape instance in 2012. \nThis method accommodates parameters to define the rebar shape's hook and hook angle. \nThe methods to set hook properties are removed. \nPut all the rebar shape properties in the call to the Create method. \nAfter you have defined the rebar segment, add the following line to create the rebar shape:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = <span class=\"teal\">RebarShape</span>.Create( doc,\n      shapeDef, <span class=\"blue\">null</span>, <span class=\"teal\">RebarStyle</span>.Standard,\n      <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      0 );\n</pre>\n<p>The RebarShapeDefinitionBySegments.Commit method is removed in Revit 2012.\nYou can simply delete it:\n\n<pre class=\"code\">\n  shapeDef.Commit(); <span class=\"green\">// take out this line</span>\n</pre>\n<p>That's it! Here is the final code in 2012, again keeping only one parameter to emphasize the changes we made:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in 2012</span>\n<span class=\"green\">//</span>\n[Transaction(<span class=\"teal\">TransactionMode</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n    <span class=\"teal\">Application</span> app = uiApp.Application;\n    <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(doc, <span class=\"maroon\">\"Lab4_1\"</span>);\n    trans.Start();\n \n    <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n      = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>(doc, 5);\n \n    <span class=\"green\">// Add parameters with default value.</span>\n \n    <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n    <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n    <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n      .GetOrCreateElementIdForExternalDefinition(\n        doc, def);\n \n    shapeDef.AddParameter(idA, 280);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Add constraints</span>\n \n    shapeDef.AddConstraintParallelToSegment(0, idA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Create a newrebarshape.</span>\n \n    <span class=\"teal\">RebarShape</span> oRebarShape = <span class=\"teal\">RebarShape</span>\n      .Create( doc, shapeDef, <span class=\"blue\">null</span>, \n        <span class=\"teal\">RebarStyle</span>.Standard,\n        <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        0 );\n \n    trans.Commit();\n \n    shapeDef.CheckDefaultParameterValues(0, 0);\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>All the API changes are documented in the 'Revit Platform API Changes and Additions.docx' and the 'What's New' section of the Revit API help file RevitAPI.chm provided with the Revit 2012 SDK. \nPlease refer to those for more information about the usage of individual classes and methods.\n\n<p>Many thanks to Joe for this overview!\n\n<p>Some of the Revit Structure API changes were also discussed in the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html#2\">Revit 2012 API webcast</a> and the associated materials.\n\n\n<a name=\"2\"></a>\n<h4>Sangsen's Questions</h4>\n<p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Migrating Rebar API Codes",
    "local_header_href": "#migrating-rebar-api-codes",
    "chunk_text": "<h4>Migrating Rebar API Codes</h4><p>If you have a code that creates a rebar shape in Revit Structure 2011, you will need to migrate it to use it in Revit Structure 2012.\nHere are the main changes in the steps to create a rebar shape:\n\n<p>In 2011,\n\n<ol>\n<li>Create a RebarShape inside the Document.\n<li>Create a RebarShapeDefinition inside the RebarShape.\n<li>Add data to the RebarShapeDefinition.\n<li>Commit the RebarShape.\n</li></li></li></li></ol>\n<p>In 2012,\n\n<ol>\n<li>Create a RebarShapeDefinition. It refers to the Document, but is not inside the document.\n<li>Add data to the RebarShapeDefinition.\n<li>Create a RebarShape inside the Document based on the RebarShapeDefinition. Only now the document is modified.\n</li></li></li></ol>\n<p>In addition, the following methods are replaced by new ones:\n\n<ul>\n<li>Autodesk.Revit.Creation.Document.NewRebarShape method <br/>&gt;\nRebarShape.Create(Document, RebarShapeDefinition, ... )\n\n<li>RebarShape.NewDefinitionBySegments method <br/>&gt;\nRebarShapeDefinitionBySegments constructor\n\n<li>RebarShape.NewDefinitionByArc method <br/>&gt;\nRebarShapeDefinitionByArc constructors\n</li></li></li></ul>\n<h4>Example: Migrating the RST Labs Code</h4>\n<p>Now, let's take a look at how to apply these changes to the rebar shape code, using our RST training labs code as an example. Here is the code for 2011, omitting some parameter definitions for simplicity:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in Revit Structure 2011</span>\n \n[<span class=\"teal\">Transaction</span>(<span class=\"teal\">TransactionMode</span>.Manual)]\n[<span class=\"teal\">Regeneration</span>(<span class=\"teal\">RegenerationOption</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateSimpleRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n  <span class=\"teal\">ElementSet</span> elements)\n{\n  <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n  <span class=\"teal\">Application</span> app = uiApp.Application;\n  <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"Lab4_2\"</span> );\n  trans.Start();\n \n  <span class=\"green\">// Create a newrebarshape.</span>\n \n  <span class=\"teal\">RebarShape</span> oRebarShape = doc.Create.NewRebarShape();\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n \n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n    = oRebarShape.NewDefinitionBySegments( 5 );\n \n  <span class=\"green\">// Add parameters with default value.</span>\n  <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def \n    = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter(def, 280);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.AddConstraintParallelToSegment( \n    0, pA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n  oRebarShape.set_HookAngle(0, 180);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.Commit();\n  trans.Commit();\n  shapeDef.CheckDefaultParameterValues( 0, 0 );\n \n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>Several lines above require changes in 2012.\n\n<p>First, remove the lines with Create.NewRebarShape(). We will add code of creating rebar shape later on via new method later:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = doc.Create.NewRebarShape(); <span class=\"green\">// Remove these lines</span>\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n</pre>\n<p>Replace the code creating RebarShapeDefinitionBySegments instance to use the constructor:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = oRebarShape.NewDefinitionBySegments( 5 ); <span class=\"green\">// 2011</span>\n</pre>\n<p>with this:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>( doc, 5 ); <span class=\"green\">// 2012</span>\n</pre>\n<p>The steps to create each shape segment are unchanged. However, in 2012, methods used to define rebar segment only accept ElementId as an argument instead of External Definition in 2011. Methods in RebarShapeParameters class provide a utility method to retrieve an element id of an external definition. We need to get the corresponding element id, and replace the reference to the parameter value (e.g., 'pA') with its corresponding ElementId variable (e.g., 'idA') in AddParameter() method a shape definition. For instance, original code like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2011.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter( def, 280 );\n</pre>\n<p>Will be modified like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2012.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n    .GetOrCreateElementIdForExternalDefinition( doc, def );\n \n  shapeDef.AddParameter( idA, 280 );\n</pre>\n<p>The RebarShape class provides a static method to create a RebarShape instance in 2012. \nThis method accommodates parameters to define the rebar shape's hook and hook angle. \nThe methods to set hook properties are removed. \nPut all the rebar shape properties in the call to the Create method. \nAfter you have defined the rebar segment, add the following line to create the rebar shape:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = <span class=\"teal\">RebarShape</span>.Create( doc,\n      shapeDef, <span class=\"blue\">null</span>, <span class=\"teal\">RebarStyle</span>.Standard,\n      <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      0 );\n</pre>\n<p>The RebarShapeDefinitionBySegments.Commit method is removed in Revit 2012.\nYou can simply delete it:\n\n<pre class=\"code\">\n  shapeDef.Commit(); <span class=\"green\">// take out this line</span>\n</pre>\n<p>That's it! Here is the final code in 2012, again keeping only one parameter to emphasize the changes we made:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in 2012</span>\n<span class=\"green\">//</span>\n[Transaction(<span class=\"teal\">TransactionMode</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n    <span class=\"teal\">Application</span> app = uiApp.Application;\n    <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(doc, <span class=\"maroon\">\"Lab4_1\"</span>);\n    trans.Start();\n \n    <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n      = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>(doc, 5);\n \n    <span class=\"green\">// Add parameters with default value.</span>\n \n    <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n    <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n    <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n      .GetOrCreateElementIdForExternalDefinition(\n        doc, def);\n \n    shapeDef.AddParameter(idA, 280);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Add constraints</span>\n \n    shapeDef.AddConstraintParallelToSegment(0, idA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Create a newrebarshape.</span>\n \n    <span class=\"teal\">RebarShape</span> oRebarShape = <span class=\"teal\">RebarShape</span>\n      .Create( doc, shapeDef, <span class=\"blue\">null</span>, \n        <span class=\"teal\">RebarStyle</span>.Standard,\n        <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        0 );\n \n    trans.Commit();\n \n    shapeDef.CheckDefaultParameterValues(0, 0);\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>All the API changes are documented in the 'Revit Platform API Changes and Additions.docx' and the 'What's New' section of the Revit API help file RevitAPI.chm provided with the Revit 2012 SDK. \nPlease refer to those for more information about the usage of individual classes and methods.\n\n<p>Many thanks to Joe for this overview!\n\n<p>Some of the Revit Structure API changes were also discussed in the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html#2\">Revit 2012 API webcast</a> and the associated materials.\n\n\n<a name=\"2\"></a>\n<h4>Sangsen's Questions</h4>\n<p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Example: Migrating the RST Labs Code",
    "local_header_href": "#example-migrating-the-rst-labs-code",
    "chunk_text": "<h4>Example: Migrating the RST Labs Code</h4><p>Now, let's take a look at how to apply these changes to the rebar shape code, using our RST training labs code as an example. Here is the code for 2011, omitting some parameter definitions for simplicity:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in Revit Structure 2011</span>\n \n[<span class=\"teal\">Transaction</span>(<span class=\"teal\">TransactionMode</span>.Manual)]\n[<span class=\"teal\">Regeneration</span>(<span class=\"teal\">RegenerationOption</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateSimpleRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n  <span class=\"teal\">ElementSet</span> elements)\n{\n  <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n  <span class=\"teal\">Application</span> app = uiApp.Application;\n  <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n  <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc, <span class=\"maroon\">\"Lab4_2\"</span> );\n  trans.Start();\n \n  <span class=\"green\">// Create a newrebarshape.</span>\n \n  <span class=\"teal\">RebarShape</span> oRebarShape = doc.Create.NewRebarShape();\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n \n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n    = oRebarShape.NewDefinitionBySegments( 5 );\n \n  <span class=\"green\">// Add parameters with default value.</span>\n  <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def \n    = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter(def, 280);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.AddConstraintParallelToSegment( \n    0, pA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span> );\n \n  oRebarShape.set_HookAngle(0, 180);\n \n  <span class=\"green\">// . . .</span>\n \n  shapeDef.Commit();\n  trans.Commit();\n  shapeDef.CheckDefaultParameterValues( 0, 0 );\n \n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre>\n<p>Several lines above require changes in 2012.\n\n<p>First, remove the lines with Create.NewRebarShape(). We will add code of creating rebar shape later on via new method later:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = doc.Create.NewRebarShape(); <span class=\"green\">// Remove these lines</span>\n \n  oRebarShape.Name = <span class=\"teal\">RstUtils</span>.msRebarShapeName;\n</pre>\n<p>Replace the code creating RebarShapeDefinitionBySegments instance to use the constructor:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = oRebarShape.NewDefinitionBySegments( 5 ); <span class=\"green\">// 2011</span>\n</pre>\n<p>with this:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef\n    = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>( doc, 5 ); <span class=\"green\">// 2012</span>\n</pre>\n<p>The steps to create each shape segment are unchanged. However, in 2012, methods used to define rebar segment only accept ElementId as an argument instead of External Definition in 2011. Methods in RebarShapeParameters class provide a utility method to retrieve an element id of an external definition. We need to get the corresponding element id, and replace the reference to the parameter value (e.g., 'pA') with its corresponding ElementId variable (e.g., 'idA') in AddParameter() method a shape definition. For instance, original code like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2011.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">Parameter</span> pA = shapeDef.AddParameter( def, 280 );\n</pre>\n<p>Will be modified like this:\n\n<pre class=\"code\">\n  <span class=\"green\">//  Add parameters with default value in 2012.</span>\n \n  <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter( <span class=\"maroon\">\"A\"</span> );\n \n  <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n    .GetOrCreateElementIdForExternalDefinition( doc, def );\n \n  shapeDef.AddParameter( idA, 280 );\n</pre>\n<p>The RebarShape class provides a static method to create a RebarShape instance in 2012. \nThis method accommodates parameters to define the rebar shape's hook and hook angle. \nThe methods to set hook properties are removed. \nPut all the rebar shape properties in the call to the Create method. \nAfter you have defined the rebar segment, add the following line to create the rebar shape:\n\n<pre class=\"code\">\n  <span class=\"teal\">RebarShape</span> oRebarShape\n    = <span class=\"teal\">RebarShape</span>.Create( doc,\n      shapeDef, <span class=\"blue\">null</span>, <span class=\"teal\">RebarStyle</span>.Standard,\n      <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n      0 );\n</pre>\n<p>The RebarShapeDefinitionBySegments.Commit method is removed in Revit 2012.\nYou can simply delete it:\n\n<pre class=\"code\">\n  shapeDef.Commit(); <span class=\"green\">// take out this line</span>\n</pre>\n<p>That's it! Here is the final code in 2012, again keeping only one parameter to emphasize the changes we made:\n\n<pre class=\"code\">\n<span class=\"green\">//  RstLab 4.1 code in 2012</span>\n<span class=\"green\">//</span>\n[Transaction(<span class=\"teal\">TransactionMode</span>.Manual)]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">RstLab4_1_CreateRebarShape</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> messages,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiApp = commandData.Application;\n    <span class=\"teal\">Application</span> app = uiApp.Application;\n    <span class=\"teal\">Document</span> doc = uiApp.ActiveUIDocument.Document;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>(doc, <span class=\"maroon\">\"Lab4_1\"</span>);\n    trans.Start();\n \n    <span class=\"teal\">RebarShapeDefinitionBySegments</span> shapeDef \n      = <span class=\"blue\">new</span> <span class=\"teal\">RebarShapeDefinitionBySegments</span>(doc, 5);\n \n    <span class=\"green\">// Add parameters with default value.</span>\n \n    <span class=\"green\">// GetOrCreateSharedParameter() is a helper function.</span>\n \n    <span class=\"teal\">ExternalDefinition</span> def = GetOrCreateSharedParameter(<span class=\"maroon\">\"A\"</span>);\n \n    <span class=\"teal\">ElementId</span> idA = <span class=\"teal\">RebarShapeParameters</span>\n      .GetOrCreateElementIdForExternalDefinition(\n        doc, def);\n \n    shapeDef.AddParameter(idA, 280);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Add constraints</span>\n \n    shapeDef.AddConstraintParallelToSegment(0, idA, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>);\n \n    <span class=\"green\">// . . .</span>\n \n    <span class=\"green\">// Create a newrebarshape.</span>\n \n    <span class=\"teal\">RebarShape</span> oRebarShape = <span class=\"teal\">RebarShape</span>\n      .Create( doc, shapeDef, <span class=\"blue\">null</span>, \n        <span class=\"teal\">RebarStyle</span>.Standard,\n        <span class=\"teal\">StirrupTieAttachmentType</span>.InteriorFace,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        180, <span class=\"teal\">RebarHookOrientation</span>.Left,\n        0 );\n \n    trans.Commit();\n \n    shapeDef.CheckDefaultParameterValues(0, 0);\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>All the API changes are documented in the 'Revit Platform API Changes and Additions.docx' and the 'What's New' section of the Revit API help file RevitAPI.chm provided with the Revit 2012 SDK. \nPlease refer to those for more information about the usage of individual classes and methods.\n\n<p>Many thanks to Joe for this overview!\n\n<p>Some of the Revit Structure API changes were also discussed in the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html#2\">Revit 2012 API webcast</a> and the associated materials.\n\n\n<a name=\"2\"></a>\n<h4>Sangsen's Questions</h4>\n<p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0602_rst_2012_api",
    "header_text": "Sangsen's Questions",
    "local_header_href": "#sangsens-questions",
    "chunk_text": "<h4>Sangsen's Questions</h4><p>Last but not least, Joe also took the time to answer Sangsen's questions:\n\n<ul>\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e16897883301538e695543970b#comment-6a00e553e16897883301538e695543970b\">Q:</a></b>\nIn Revit Structure 2012, BoundaryConditions.HostElement returns analytical model instead of family instance. \nCan you help me how to obtain the host element family instance?\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/set-preview-image.html?cid=6a00e553e168978833014e894193b5970d#comment-6a00e553e168978833014e894193b5970d\">A:</a></b>\nAfter getting the analytical model from the BoundaryConditions instance, you can call the AnalyticalModel.GetElementId method to retrieve the id of the Host element family instance.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e16897883301538e97d1a4970b#comment-6a00e553e16897883301538e97d1a4970b\">Q:</a></b>\nPlease explain the details about Analytical Changes option in Analytical Alignment property.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/03/revit-2012-api-features.html?cid=6a00e553e1689788330154332192dc970c#comment-6a00e553e1689788330154332192dc970c\">A:</a></b>\nThe big change to the analytical model in RST 2012 is the split of analytical model and its host physical model. \nThe latter are now standalone elements.\n\n<p>Accordingly, the change of analytical model in Revit 2012 is that the AnalyticalModel class is derived from the Element class instead of the IDisposable interface. \nThis means in Revit 2012, each AnalyticalModel instance is persistent and database resident. \nPreviously, AnalyticalModel instances lived in transient memory only.\n\n<p>This affects the way to get the analytical model object. \nNow we can retrieve them using the element filtering mechanism via FilteredElementCollecotr. \nPreviously the analytical model could only be retrieved from the host element.\n\n<p>With regard to the functionality of the AnalyticalModel class, new methods about alignment operation were introduced:\nGetAlignmentMethod, HasAlighment and SetAlignmentMethod.\n\n<p>The alignment option should work for a 2011 model opened in RST 2012.\n\n<li><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e889b37e1970d#comment-6a00e553e168978833014e889b37e1970d\">Q:</a></b>\nIn Revit 2012, how can I access an entity with its Analytical model details. Please post changes to the analytical model class.\n\n<p><b><a href=\"http://thebuildingcoder.typepad.com/blog/2011/05/revit-2012-api-webcast.html?cid=6a00e553e168978833014e89419b39970d#comment-6a00e553e168978833014e89419b39970d\">A:</a></b>\nThe host physical component of a given analytical model can be obtained by the AnalyticalModel.GetElementId method. \nIt returns the element id of the physical component.\n\n</p></li></p></p></p></p></p></li></p></li></ul>\n<p>Thank you very much again, Joe!\n\n</p></p>"
  }
]