[
  {
    "original_filename": "0641_floor_creation",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0641_floor_creation",
    "header_text": "Floor Creation",
    "local_header_href": "#floor-creation",
    "chunk_text": "<h3>Floor Creation</h3><p>I already presented examples on using the NewFloor method to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2008/11/editing-a-floor-profile.html\">\nedit a floor profile</a> and\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2009/02/boolean-operations-for-2d-polygons.html\">\nperform Boolean operations on two-dimensional polygons</a>.\n\n<p>Now Guming submitted a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/08/modeless-loose-connector-navigator-update.html?cid=6a00e553e168978833015391044035970b#comment-6a00e553e168978833015391044035970b\">\nsimpler question</a>, on \n\nhow to use the NewFloor method to create a floor from scratch, \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/08/modeless-loose-connector-navigator-update.html?cid=6a00e553e168978833015434f762a5970c#comment-6a00e553e168978833015434f762a5970c\">\ntwice</a> in \n\nfact, so let's have a look at that: \n\n<p><strong>Question:</strong> How can I use certain points to create a new floor? \nThe function NewFloor doesn't work for me.\n\n<p><strong>Answer:</strong> You create a new floor using the NewFloor method.\nYou need to provide the profile curves and specify whether it is structural or not.\nOther optional arguments can determine the floor type, level and a normal vector in case it is not horizontal.\nAccording to the help file, the profile curves must always be specified horizontally, regardless of the desired floor slope.\nHere are the argument lists of the three NewFloor overloads:\n\n<ul>\n<li>CurveArray profile, Boolean structural: Creates a floor within the project with the given horizontal profile using the default floor style.\n<li>CurveArray profile, FloorType, Level, Boolean structural: Creates a floor within the project with the given horizontal profile and floor style on the specified level.\n<li>CurveArray profile, FloorType, Level, Boolean structural, XYZ normal: Creates a floor within the project with the given horizontal profile and floor style on the specified level with the specified normal vector.\n</li></li></li></ul>\n<p>Further documentation on the use of this method is provided in the developer guide section 11.2 'Floors and Foundations'.\n\n<p>The Building Coder samples include the command \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2008/11/editing-a-floor-profile.html\">\nCmdEditFloor</a> which \n\nexercises the second one of the NewFloor overloads, and so does the Revit SDK sample application GenerateFloor.\n\n<p>CmdEditFloor reads a profile from an existing floor and modifies that, whereas GenerateFloor demonstrates how to generate a floor using the closed outline made by a selection of walls.\n\n<p>Guming, one problem with the input points that you list is that they are not horizontal.\nSome have a Z coordinate of 0, others 10.\nThat might be causing the method to fail for you.\n\n<p>Here is another related issue and interesting sample from a case handled by my colleagues Saikat Bhattacharya and Harry Mattison:\n\n<p><strong>Question:</strong> I wish to create a whole set of floors by automatically  generating slabs in every level of a project based on profiles. \n\n<p>When creating a set of floors using profiles, all the floors seem to be created with a non-zero value for the '\u001cHeight Offset from Level\u001d' parameter. \nWhy is this parameter value being set to a non-zero value?\n\n<p>In spite of this parameter value being set and the Level property showing the correct information, all the floors are being created on the same level. \nI can manually set this parameter value to zero to get the expected results, but I am not sure why it is being automatically set in the first place. \n\n<p><strong>Answer:</strong> The floors are created at the position of the profile curves. \nThe floors are associated with the specified level, but the level does not set the floor's height.\n\n<p>Therefore, all floors are created with the same set of profiles and each floor is associated with a different level. \nAll the profile curves have a Z coordinate equal to zero. \nSo when a floor is associated with a level at 28 feet and its curves are at 0, the offset will be -28.\n\n<p>You have two options: \n\n<ul>\n<li>Leave the Z value of all curve points at zero, create the floors, and set their FLOOR_HEIGHTABOVELEVEL_PARAM parameter value to zero.\n<li>Modify each and every curve Z coordinate before creating the floors to ensure that the parameter is set to zero to begin with.\n</li></li></ul>\n<p>Which method to choose depends on how you want your model built. \nIn some cases, you will want to associate with the nearest level and not use the offsets. \nIn other cases, you might not care about what level is related to the floor and position them using offsets only.\n\n<p>Presumably, if you set all the horizontal curve profile Z coordinates to the elevation of the level, the floor height above level parameter value will be automatically set to zero.\n\n<p>I implemented a sample application CreateFloors to demonstrate this.\nIt performs the following steps:\n\n<ul>\n<li>Create a list of all the levels in the project.\n<li>Determine the floor type to use, Generic - 12\".\n<li>Retrieve the first generic model named WP1 to use as a profile definition element.\n<li>Traverse the profile definition element geometry and collect all its curves.\n<li>Use these curves to generate a floor on each of the levels.\n<li>Set the height above level parameter on each floor to zero, to that it resides on the same height as its associated level.\n</li></li></li></li></li></li></ul>\n<p>Here is the source code to achieve these steps:\n\n<pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">Command</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n    <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n    <span class=\"teal\">Application</span> app = uiapp.Application;\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n    <span class=\"teal\">FilteredElementCollector</span> levels \n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) );\n \n    <span class=\"teal\">FloorType</span> floorType\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">FloorType</span> ) )\n        .First&lt;<span class=\"teal\">Element</span>&gt;( \n          e =&gt; e.Name.Equals( <span class=\"maroon\">\"Generic - 12\\\"\"</span> ) ) \n          <span class=\"blue\">as</span> <span class=\"teal\">FloorType</span>;\n \n    <span class=\"teal\">Element</span> profileElement\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">FamilyInstance</span> ) )\n        .OfCategory( <span class=\"teal\">BuiltInCategory</span>.OST_GenericModel )\n        .First&lt;<span class=\"teal\">Element</span>&gt;(\n          e =&gt; e.Name.Equals( <span class=\"maroon\">\"WP1\"</span> ) );\n \n    <span class=\"teal\">CurveArray</span> slabCurves = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"teal\">GeometryElement</span> geo = profileElement.get_Geometry( <span class=\"blue\">new</span> <span class=\"teal\">Options</span>() );\n \n    <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryInstance</span> inst <span class=\"blue\">in</span> geo.Objects )\n    {\n      <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> obj <span class=\"blue\">in</span> inst.SymbolGeometry.Objects )\n      {\n        <span class=\"blue\">if</span>( obj <span class=\"blue\">is</span> <span class=\"teal\">Curve</span> )\n        {\n          slabCurves.Append( obj <span class=\"blue\">as</span> <span class=\"teal\">Curve</span> );\n        }\n      }\n    }\n \n    <span class=\"teal\">XYZ</span> normal = <span class=\"teal\">XYZ</span>.BasisZ;\n \n    <span class=\"teal\">Transaction</span> trans = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n    trans.Start( <span class=\"maroon\">\"Create Floors\"</span> );\n \n    <span class=\"blue\">foreach</span>( <span class=\"teal\">Level</span> level <span class=\"blue\">in</span> levels )\n    {\n      <span class=\"teal\">Floor</span> newFloor = doc.Create.NewFloor( slabCurves, \n        floorType, level, <span class=\"blue\">false</span>, normal );\n \n      newFloor.get_Parameter( \n        <span class=\"teal\">BuiltInParameter</span>.FLOOR_HEIGHTABOVELEVEL_PARAM ).Set( 0 );\n    }\n \n    trans.Commit();\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre>\n<p>These are some sample levels to use to create floors on:\n\n<center>\n<img alt=\"Floor creation levels\" src=\"img/create_floor_levels.png\"/>\n</center>\n<p>This is the generic model that the floor profile is read from:\n\n<center>\n<img alt=\"Floor creation generic model\" src=\"img/create_floor_generic_model.png\"/>\n</center>\n<p>Here are the resulting floors:\n\n<center>\n<img alt=\"Floor creation result\" src=\"img/create_floor_floors.png\"/>\n</center>\n<p>Finally, here is \n\n<a href=\"zip/CreateFloors.zip\">CreateFloors.zip</a> containing \n\nthe complete Visual Studio solution, C# source code, and add-in manifest file of the CreateFloors external command.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]