[
  {
    "original_filename": "0695_load_adsk",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0695_load_adsk",
    "header_text": "Loading an Inventor ADSK Component",
    "local_header_href": "#loading-an-inventor-adsk-component",
    "chunk_text": "<h3>Loading an Inventor ADSK Component</h3><p>We held the DevLab in Munich yesterday before rushing off to get to Milano in the evening.\n\n<p>I slept a little bit in the taxi and plane on the way here.\nI was still dead tired on arrival at the hotel just before ten, but thought I absolutely must get out and have a teeny weeny little sniff of Italy anyway before going to bed.\nI went to a bar right next door and committed the deadly foreigner sin of having a cappuccino, which it is almost a criminal offence to drink except at breakfast time.\nQuite soon the very friendly couple at the neighbouring table, Agnès and Max, informed me that a free concert was going to start shortly next door.\nAgnès and Max are both a photographers, just like Dima, whom I met in \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/12/rex-content-generator.html\">\nJerusalem last Thursday</a>,\n\nso Thursday seems to be my meet-a-photographer day right now. \nCheck out \n\n<a href=\"http://www.penombre.it\">\nAgnès' site</a> and\n\n<a href=\"http://agnesweber.blogspot.com\">\nblog</a> and\n\n<a href=\"http://www.msvphoto.altervista.org\">\nMax' photos</a> and\n\n<a href=\"http://msvphoto.wordpress.com\">blog</a>.</p>\n<center>\n<img alt=\"Penombre\" src=\"img/penombre.jpg\"/>\n</center>\n<p>The concert was really great, by the Italian singer\n\n<a href=\"http://it.wikipedia.org/wiki/Folco_Orselli\">\nFolco</a>\n<a href=\"http://www.myspace.com/folcoorselli\">\nOrselli</a>.\n\nI liked it so much I bought his CD, asked for the very first autograph of my life, and ended up in bed rather late, or early, depending on your point of view  :-)\n\n\n\n\n\n<h4>Loading an Inventor Component ADSK File</h4>\n<p>One of the many interesting topics raised at the DevLab came from Martin Schmid, our MEP expert, working with both AutoCAD and Revit.\nHe brought an ADSK component file created in Inventor with the goal of loading it into Revit.\n\n<p>I tried one or two things to achieve this which \n\n<a href=\"#2\">\nfailed</a>\n\nbefore finding a \n\n<a href=\"#3\">\nsuccessful solution</a>, \n\nso you might want to skip straight to that if you are not interested in the blather.\n\n\n<a name=\"2\"></a>\n<h4>Failed Attempts</h4>\n<p>The first thing we tried was the LoadFamily method, which simply does not work at all and is not intended to do so either:\n\n<pre class=\"code\">\n  <span class=\"blue\">const</span> <span class=\"blue\">string</span> filename \n    = <span class=\"maroon\">\"C:/a/doc/revit/blog/src/LoadAdsk/Part1.adsk\"</span>;\n \n  <span class=\"green\">// Load ADSK using LoadFamily does not work;</span>\n  <span class=\"green\">// rc is false, and f is null:</span>\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load Adsk\"</span> );\n  <span class=\"teal\">Family</span> f = <span class=\"blue\">null</span>;\n  <span class=\"blue\">bool</span> rc = doc.LoadFamily( filename, <span class=\"blue\">out</span> f );\n  t.Commit();\n</pre>\n<p>This does not cause any error, but 'rc' is false and 'f' remains null.\n\n<p>The second attempt was trying to open the component as a document using OpenDocumentFile:\n\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc = app.OpenDocumentFile( filename );\n</pre>\n<p>This should achieve the same result as dragging and dropping the component onto the Revit window, which opens it in the family editor.\nIt does actually successfully open the ADSK in the family editor but it also displays an error saying \"Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\"</p>\n<center>\n<img alt=\"Error message on opening ADSK file\" src=\"img/adsk_openDocumentFile_error.png\"/>\n</center>\n<p>I am not yet sure whether this message is erroneous.\nMaybe you can simply ignore it and automatically dismiss it through the API.\n\n<p>Anyway, after those two failed attempts, we went on to find a solution which really works:\n\n\n\n<a name=\"3\"></a>\n<h4>Successful Workflow using OpenBuildingComponentDocument</h4>\n<p>Scott Reinemann pointed out that we should try the OpenBuildingComponentDocument method, and that works fine.\n\n<p>Here is the code that achieves exactly what we want:\n\n<ul>\n<li>Open the ADSK component family file.\n<li>Load the component family into the project.\n<li>Retrieve a family symbol from it.\n<li>Place an instance of the symbol.\n</li></li></li></li></ul>\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc \n    = app.OpenBuildingComponentDocument( filename );\n \n  <span class=\"teal\">Debug</span>.Print( \n    <span class=\"maroon\">\"Opened component document {0} with path '{1}'\"</span>,\n    adsk_doc.Title, adsk_doc.PathName );\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load ADSK component document\"</span> );\n  <span class=\"teal\">Family</span> f = adsk_doc.LoadFamily( doc );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Loaded component family {0}\"</span>,\n    f.Name );\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> f.Symbols )\n  {\n    symbol = s;\n    <span class=\"blue\">break</span>;\n  }\n \n  t.Start( <span class=\"maroon\">\"Place ADSK component document\"</span> );\n  <span class=\"teal\">FamilyInstance</span> i = doc.Create.NewFamilyInstance( \n    <span class=\"teal\">XYZ</span>.Zero, symbol, <span class=\"teal\">StructuralType</span>.NonStructural );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Placed component family instance {0}\"</span>,\n    i.Name );\n</pre>\n<p>Here is the Part1 symbol defined by the component family appearing in the project browser after being loaded:\n\n<center>\n<img alt=\"Part1 family symbol in project browser\" src=\"img/adsk_part1_project_browser.png\"/>\n</center>\n<p>This is the family instance placed in the project origin:</p>\n<center>\n<img alt=\"Part1 family instance\" src=\"img/adsk_part1_instance.png\"/>\n</center>\n<!-- SPR #217150 [OpenBuildingComponentDocument error setting PathName property] -->\n<p>Right now the PathName property remains empty, but the Title property is set as expected, so the messages printed to the Visual Studio debug output window say:\n\n<pre>\nOpened component document Part1 with path ''\nLoaded component family Part1\nPlaced component family instance Part1\n</pre>\n<p>This implementation automatically places the family instance hardwired at the origin and does not mimic the placement of a family when using the user interface, which displays a preview of the symbol at the cursor.  \n\n<p>To have that, you can make a call to \n\n<!-- \n\n402_place_family_instance.htm:&nbsp; &nbsp; uidoc.PromptForFamilyIns\n471_place_site_component.htm:PromptForFamilyInstancePlacement</a> an\n475_place_furniture.htm:PromptForFamilyInstancePlacement</a>, placin\n479_launch_command.htm:<p><strong>Question:</strong> In the Revit AP\n614_point_cloud_snap_freeze.htm:<span class=\"blue\">public</span> <sp\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html\">\nPromptForFamilyInstancePlacement</a> instead.\n\n<p>Here is \n\n<a href=\"zip/LoadAdsk.zip\">LoadAdsk.zip</a> containing \n\nthe source code and complete Visual Studio solution for this command as well as a sample component file Part1.adsk to play around with.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0695_load_adsk",
    "header_text": "Loading an Inventor Component ADSK File",
    "local_header_href": "#loading-an-inventor-component-adsk-file",
    "chunk_text": "<h4>Loading an Inventor Component ADSK File</h4><p>One of the many interesting topics raised at the DevLab came from Martin Schmid, our MEP expert, working with both AutoCAD and Revit.\nHe brought an ADSK component file created in Inventor with the goal of loading it into Revit.\n\n<p>I tried one or two things to achieve this which \n\n<a href=\"#2\">\nfailed</a>\n\nbefore finding a \n\n<a href=\"#3\">\nsuccessful solution</a>, \n\nso you might want to skip straight to that if you are not interested in the blather.\n\n\n<a name=\"2\"></a>\n<h4>Failed Attempts</h4>\n<p>The first thing we tried was the LoadFamily method, which simply does not work at all and is not intended to do so either:\n\n<pre class=\"code\">\n  <span class=\"blue\">const</span> <span class=\"blue\">string</span> filename \n    = <span class=\"maroon\">\"C:/a/doc/revit/blog/src/LoadAdsk/Part1.adsk\"</span>;\n \n  <span class=\"green\">// Load ADSK using LoadFamily does not work;</span>\n  <span class=\"green\">// rc is false, and f is null:</span>\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load Adsk\"</span> );\n  <span class=\"teal\">Family</span> f = <span class=\"blue\">null</span>;\n  <span class=\"blue\">bool</span> rc = doc.LoadFamily( filename, <span class=\"blue\">out</span> f );\n  t.Commit();\n</pre>\n<p>This does not cause any error, but 'rc' is false and 'f' remains null.\n\n<p>The second attempt was trying to open the component as a document using OpenDocumentFile:\n\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc = app.OpenDocumentFile( filename );\n</pre>\n<p>This should achieve the same result as dragging and dropping the component onto the Revit window, which opens it in the family editor.\nIt does actually successfully open the ADSK in the family editor but it also displays an error saying \"Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\"</p>\n<center>\n<img alt=\"Error message on opening ADSK file\" src=\"img/adsk_openDocumentFile_error.png\"/>\n</center>\n<p>I am not yet sure whether this message is erroneous.\nMaybe you can simply ignore it and automatically dismiss it through the API.\n\n<p>Anyway, after those two failed attempts, we went on to find a solution which really works:\n\n\n\n<a name=\"3\"></a>\n<h4>Successful Workflow using OpenBuildingComponentDocument</h4>\n<p>Scott Reinemann pointed out that we should try the OpenBuildingComponentDocument method, and that works fine.\n\n<p>Here is the code that achieves exactly what we want:\n\n<ul>\n<li>Open the ADSK component family file.\n<li>Load the component family into the project.\n<li>Retrieve a family symbol from it.\n<li>Place an instance of the symbol.\n</li></li></li></li></ul>\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc \n    = app.OpenBuildingComponentDocument( filename );\n \n  <span class=\"teal\">Debug</span>.Print( \n    <span class=\"maroon\">\"Opened component document {0} with path '{1}'\"</span>,\n    adsk_doc.Title, adsk_doc.PathName );\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load ADSK component document\"</span> );\n  <span class=\"teal\">Family</span> f = adsk_doc.LoadFamily( doc );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Loaded component family {0}\"</span>,\n    f.Name );\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> f.Symbols )\n  {\n    symbol = s;\n    <span class=\"blue\">break</span>;\n  }\n \n  t.Start( <span class=\"maroon\">\"Place ADSK component document\"</span> );\n  <span class=\"teal\">FamilyInstance</span> i = doc.Create.NewFamilyInstance( \n    <span class=\"teal\">XYZ</span>.Zero, symbol, <span class=\"teal\">StructuralType</span>.NonStructural );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Placed component family instance {0}\"</span>,\n    i.Name );\n</pre>\n<p>Here is the Part1 symbol defined by the component family appearing in the project browser after being loaded:\n\n<center>\n<img alt=\"Part1 family symbol in project browser\" src=\"img/adsk_part1_project_browser.png\"/>\n</center>\n<p>This is the family instance placed in the project origin:</p>\n<center>\n<img alt=\"Part1 family instance\" src=\"img/adsk_part1_instance.png\"/>\n</center>\n<!-- SPR #217150 [OpenBuildingComponentDocument error setting PathName property] -->\n<p>Right now the PathName property remains empty, but the Title property is set as expected, so the messages printed to the Visual Studio debug output window say:\n\n<pre>\nOpened component document Part1 with path ''\nLoaded component family Part1\nPlaced component family instance Part1\n</pre>\n<p>This implementation automatically places the family instance hardwired at the origin and does not mimic the placement of a family when using the user interface, which displays a preview of the symbol at the cursor.  \n\n<p>To have that, you can make a call to \n\n<!-- \n\n402_place_family_instance.htm:&nbsp; &nbsp; uidoc.PromptForFamilyIns\n471_place_site_component.htm:PromptForFamilyInstancePlacement</a> an\n475_place_furniture.htm:PromptForFamilyInstancePlacement</a>, placin\n479_launch_command.htm:<p><strong>Question:</strong> In the Revit AP\n614_point_cloud_snap_freeze.htm:<span class=\"blue\">public</span> <sp\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html\">\nPromptForFamilyInstancePlacement</a> instead.\n\n<p>Here is \n\n<a href=\"zip/LoadAdsk.zip\">LoadAdsk.zip</a> containing \n\nthe source code and complete Visual Studio solution for this command as well as a sample component file Part1.adsk to play around with.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0695_load_adsk",
    "header_text": "Failed Attempts",
    "local_header_href": "#failed-attempts",
    "chunk_text": "<h4>Failed Attempts</h4><p>The first thing we tried was the LoadFamily method, which simply does not work at all and is not intended to do so either:\n\n<pre class=\"code\">\n  <span class=\"blue\">const</span> <span class=\"blue\">string</span> filename \n    = <span class=\"maroon\">\"C:/a/doc/revit/blog/src/LoadAdsk/Part1.adsk\"</span>;\n \n  <span class=\"green\">// Load ADSK using LoadFamily does not work;</span>\n  <span class=\"green\">// rc is false, and f is null:</span>\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load Adsk\"</span> );\n  <span class=\"teal\">Family</span> f = <span class=\"blue\">null</span>;\n  <span class=\"blue\">bool</span> rc = doc.LoadFamily( filename, <span class=\"blue\">out</span> f );\n  t.Commit();\n</pre>\n<p>This does not cause any error, but 'rc' is false and 'f' remains null.\n\n<p>The second attempt was trying to open the component as a document using OpenDocumentFile:\n\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc = app.OpenDocumentFile( filename );\n</pre>\n<p>This should achieve the same result as dragging and dropping the component onto the Revit window, which opens it in the family editor.\nIt does actually successfully open the ADSK in the family editor but it also displays an error saying \"Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\"</p>\n<center>\n<img alt=\"Error message on opening ADSK file\" src=\"img/adsk_openDocumentFile_error.png\"/>\n</center>\n<p>I am not yet sure whether this message is erroneous.\nMaybe you can simply ignore it and automatically dismiss it through the API.\n\n<p>Anyway, after those two failed attempts, we went on to find a solution which really works:\n\n\n\n<a name=\"3\"></a>\n<h4>Successful Workflow using OpenBuildingComponentDocument</h4>\n<p>Scott Reinemann pointed out that we should try the OpenBuildingComponentDocument method, and that works fine.\n\n<p>Here is the code that achieves exactly what we want:\n\n<ul>\n<li>Open the ADSK component family file.\n<li>Load the component family into the project.\n<li>Retrieve a family symbol from it.\n<li>Place an instance of the symbol.\n</li></li></li></li></ul>\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc \n    = app.OpenBuildingComponentDocument( filename );\n \n  <span class=\"teal\">Debug</span>.Print( \n    <span class=\"maroon\">\"Opened component document {0} with path '{1}'\"</span>,\n    adsk_doc.Title, adsk_doc.PathName );\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load ADSK component document\"</span> );\n  <span class=\"teal\">Family</span> f = adsk_doc.LoadFamily( doc );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Loaded component family {0}\"</span>,\n    f.Name );\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> f.Symbols )\n  {\n    symbol = s;\n    <span class=\"blue\">break</span>;\n  }\n \n  t.Start( <span class=\"maroon\">\"Place ADSK component document\"</span> );\n  <span class=\"teal\">FamilyInstance</span> i = doc.Create.NewFamilyInstance( \n    <span class=\"teal\">XYZ</span>.Zero, symbol, <span class=\"teal\">StructuralType</span>.NonStructural );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Placed component family instance {0}\"</span>,\n    i.Name );\n</pre>\n<p>Here is the Part1 symbol defined by the component family appearing in the project browser after being loaded:\n\n<center>\n<img alt=\"Part1 family symbol in project browser\" src=\"img/adsk_part1_project_browser.png\"/>\n</center>\n<p>This is the family instance placed in the project origin:</p>\n<center>\n<img alt=\"Part1 family instance\" src=\"img/adsk_part1_instance.png\"/>\n</center>\n<!-- SPR #217150 [OpenBuildingComponentDocument error setting PathName property] -->\n<p>Right now the PathName property remains empty, but the Title property is set as expected, so the messages printed to the Visual Studio debug output window say:\n\n<pre>\nOpened component document Part1 with path ''\nLoaded component family Part1\nPlaced component family instance Part1\n</pre>\n<p>This implementation automatically places the family instance hardwired at the origin and does not mimic the placement of a family when using the user interface, which displays a preview of the symbol at the cursor.  \n\n<p>To have that, you can make a call to \n\n<!-- \n\n402_place_family_instance.htm:&nbsp; &nbsp; uidoc.PromptForFamilyIns\n471_place_site_component.htm:PromptForFamilyInstancePlacement</a> an\n475_place_furniture.htm:PromptForFamilyInstancePlacement</a>, placin\n479_launch_command.htm:<p><strong>Question:</strong> In the Revit AP\n614_point_cloud_snap_freeze.htm:<span class=\"blue\">public</span> <sp\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html\">\nPromptForFamilyInstancePlacement</a> instead.\n\n<p>Here is \n\n<a href=\"zip/LoadAdsk.zip\">LoadAdsk.zip</a> containing \n\nthe source code and complete Visual Studio solution for this command as well as a sample component file Part1.adsk to play around with.\n</p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0695_load_adsk",
    "header_text": "Successful Workflow using OpenBuildingComponentDocument",
    "local_header_href": "#successful-workflow-using-openbuildingcomponentdocument",
    "chunk_text": "<h4>Successful Workflow using OpenBuildingComponentDocument</h4><p>Scott Reinemann pointed out that we should try the OpenBuildingComponentDocument method, and that works fine.\n\n<p>Here is the code that achieves exactly what we want:\n\n<ul>\n<li>Open the ADSK component family file.\n<li>Load the component family into the project.\n<li>Retrieve a family symbol from it.\n<li>Place an instance of the symbol.\n</li></li></li></li></ul>\n<pre class=\"code\">\n  <span class=\"teal\">Document</span> adsk_doc \n    = app.OpenBuildingComponentDocument( filename );\n \n  <span class=\"teal\">Debug</span>.Print( \n    <span class=\"maroon\">\"Opened component document {0} with path '{1}'\"</span>,\n    adsk_doc.Title, adsk_doc.PathName );\n \n  t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc );\n  t.Start( <span class=\"maroon\">\"Load ADSK component document\"</span> );\n  <span class=\"teal\">Family</span> f = adsk_doc.LoadFamily( doc );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Loaded component family {0}\"</span>,\n    f.Name );\n \n  <span class=\"teal\">FamilySymbol</span> symbol = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">FamilySymbol</span> s <span class=\"blue\">in</span> f.Symbols )\n  {\n    symbol = s;\n    <span class=\"blue\">break</span>;\n  }\n \n  t.Start( <span class=\"maroon\">\"Place ADSK component document\"</span> );\n  <span class=\"teal\">FamilyInstance</span> i = doc.Create.NewFamilyInstance( \n    <span class=\"teal\">XYZ</span>.Zero, symbol, <span class=\"teal\">StructuralType</span>.NonStructural );\n  t.Commit();\n \n  <span class=\"teal\">Debug</span>.Print(\n    <span class=\"maroon\">\"Placed component family instance {0}\"</span>,\n    i.Name );\n</pre>\n<p>Here is the Part1 symbol defined by the component family appearing in the project browser after being loaded:\n\n<center>\n<img alt=\"Part1 family symbol in project browser\" src=\"img/adsk_part1_project_browser.png\"/>\n</center>\n<p>This is the family instance placed in the project origin:</p>\n<center>\n<img alt=\"Part1 family instance\" src=\"img/adsk_part1_instance.png\"/>\n</center>\n<!-- SPR #217150 [OpenBuildingComponentDocument error setting PathName property] -->\n<p>Right now the PathName property remains empty, but the Title property is set as expected, so the messages printed to the Visual Studio debug output window say:\n\n<pre>\nOpened component document Part1 with path ''\nLoaded component family Part1\nPlaced component family instance Part1\n</pre>\n<p>This implementation automatically places the family instance hardwired at the origin and does not mimic the placement of a family when using the user interface, which displays a preview of the symbol at the cursor.  \n\n<p>To have that, you can make a call to \n\n<!-- \n\n402_place_family_instance.htm:&nbsp; &nbsp; uidoc.PromptForFamilyIns\n471_place_site_component.htm:PromptForFamilyInstancePlacement</a> an\n475_place_furniture.htm:PromptForFamilyInstancePlacement</a>, placin\n479_launch_command.htm:<p><strong>Question:</strong> In the Revit AP\n614_point_cloud_snap_freeze.htm:<span class=\"blue\">public</span> <sp\n\n-->\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html\">\nPromptForFamilyInstancePlacement</a> instead.\n\n<p>Here is \n\n<a href=\"zip/LoadAdsk.zip\">LoadAdsk.zip</a> containing \n\nthe source code and complete Visual Studio solution for this command as well as a sample component file Part1.adsk to play around with.\n</p></p></p></p></p></p></p>"
  }
]