[
  {
    "original_filename": "0766_sel_face_linked_file",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0766_sel_face_linked_file",
    "header_text": "Selecting a Face in a Linked File",
    "local_header_href": "#selecting-a-face-in-a-linked-file",
    "chunk_text": "<h3>Selecting a Face in a Linked File</h3><p>Here is a chance to look at an interesting method that we never discussed yet, ConvertToStableRepresentation, and the hidden information that it provides access to.\nIt does what it says, converting a Reference to a stable string representation.\n\n\n<a name=\"1\"></a>\n<h4>Reference and Stable Representation</h4>\n<p>A reference provides a possibility to identify a piece of geometry, even though geometry is transient, not persistent, memory only, generated on the fly.\nStill, we sometimes need to identify a piece of it and remember which piece it was.\nFor instance, to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-by-iterating-faces.html\">\ndimension the distance</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-using-findreferencesbydirection.html\">\nbetween two parallel walls</a>, \n\nwe need to identify which wall face we are measuring from.\nThis can be achieved using references.\n\n<p>A stable representation can be used to preserve and restore a reference later in the same Revit session or even in a different session in the same document. \nThe ParseFromStableRepresentation method is used to restore the reference. \nThe representation is based on the internal Revit structure and is not intended to be parsed by anyone else except ParseFromStableRepresentation.\n\n<p>Here is a rather unexpected use of this method and the undocumented internals of the stable string representation:\n\n\n<a name=\"2\"></a>\n<h4>Face Selection in Linked File</h4>\n<p>Some Revit API functionality is limited to the current project and will not work for linked files.\nCurrently, this most heavily affects the geometric analysis, and methods like FindReferencesWithContextByDirection and its new optimised and simplified Revit 2013 wrapper class ReferenceIntersector.\n\n<p>Another affected area is the interactive element selection, which led to the following \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/04/revit-2013-product-guids-and-guid-algorithm.html?cid=6a00e553e1689788330168ea336953970c#comment-6a00e553e1689788330168ea336953970c\">\nquestion</a> by \n\n<a href=\"mailto:vlouzeau@gmail.com\">\nValentin Louzeau</a>:\n\n\n<p><strong>Question:</strong> I'm working on a plugin and asking the user to select a face, but it does not work in linked files. \nI found something using ObjectType.PointOnElement for selection but it doesn't seem to work for my needs. \nIs there an easy way to do that or do you already have a solution?\n\n<p><strong>Answer:</strong> Nope, sorry, there is no easy way to work on a face in a linked file, and I am not aware of any solution for this.\n\n<p><strong>Response:</strong> I found a solution using the method ConvertToStableRepresentation on the Reference class.\n\n<p>This string contains the ref document unique ID, its name, and the ID of the picked element in this document. \nYou can get its position in the ref doc and if you insert origin to origin, the element has the same position in the two documents.\n\n<p>Here is an example of a stable representation for a reference to a picked face on a wall in a linked file:\n\n<ul>\n<li>\"7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a1:0:RVTLINK/7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a0:161224:5:SURFACE\"\n</li></ul>\n<p>From this, the wall element id \"161224\" can be extracted.\n\n<p>Here is some code in which I tested making use of this:\n\n<pre class=\"code\">\n[<span class=\"teal\">TransactionAttribute</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">SelectFaceInLinkedFile</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute( \n    <span class=\"teal\">ExternalCommandData</span> commandData, \n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message, \n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n \n    <span class=\"teal\">PlanarFace</span> Plan = SelectFace( uiapp );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">PlanarFace</span> SelectFace( \n    <span class=\"teal\">UIApplication</span> uiapp )\n  {\n    <span class=\"teal\">Document</span> doc = uiapp.ActiveUIDocument.Document;\n \n    <span class=\"green\">// get all ref doc. </span>\n \n    <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; doc2 \n      = GetLinkedDocuments( doc );\n \n    <span class=\"green\">// get the ref of a selected plane</span>\n \n    <span class=\"teal\">Selection</span> sel = uiapp.ActiveUIDocument.Selection;\n \n    <span class=\"teal\">Reference</span> pickedRef = sel.PickObject( \n      <span class=\"teal\">ObjectType</span>.PointOnElement, \n      <span class=\"maroon\">\"Please select a Face\"</span> );\n \n    <span class=\"teal\">Element</span> elem = doc.GetElement( \n      pickedRef.ElementId );\n \n    <span class=\"green\">// get the true position picked </span>\n    <span class=\"green\">// in the active document</span>\n \n    <span class=\"teal\">XYZ</span> pos = pickedRef.GlobalPoint;\n \n    <span class=\"green\">// get the ID of the element containing the </span>\n    <span class=\"green\">// face you picked in the active document </span>\n    <span class=\"green\">// and in its host document</span>\n \n    <span class=\"blue\">string</span> s = pickedRef\n      .ConvertToStableRepresentation( doc );\n \n    <span class=\"blue\">string</span>[] tab_str = s.Split( <span class=\"maroon\">':'</span> );\n \n    <span class=\"blue\">string</span> id = tab_str[tab_str.Length - 3];\n \n    <span class=\"blue\">int</span> ID;\n    <span class=\"teal\">Int32</span>.TryParse( id, <span class=\"blue\">out</span> ID );\n \n    <span class=\"teal\">Type</span> et = elem.GetType();\n \n    <span class=\"blue\">if</span>( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkInstance</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">Instance</span> ) == et )\n    {\n      <span class=\"blue\">foreach</span>( <span class=\"teal\">Document</span> d <span class=\"blue\">in</span> doc2 )\n      {\n        <span class=\"blue\">if</span>( elem.Name.Contains( d.Title ) )\n        {\n          <span class=\"teal\">Element</span> element = d.GetElement( \n            <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( ID ) );\n \n          <span class=\"teal\">Options</span> ops = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n          ops.ComputeReferences = <span class=\"blue\">true</span>;\n \n          <span class=\"green\">// write the name of the element and the </span>\n          <span class=\"green\">// number of solids in this only for </span>\n          <span class=\"green\">// control to show the possibilities</span>\n \n          <span class=\"teal\">MessageBox</span>.Show( element.Name, \n            element.get_Geometry( ops )\n              .Objects.Size.ToString() );\n \n          <span class=\"teal\">GeometryObject</span> obj \n            = element.get_Geometry( ops )\n              .Objects.get_Item( 0 );\n \n          <span class=\"green\">// test all surfaces of solids in the </span>\n          <span class=\"green\">// element and return the one containing </span>\n          <span class=\"green\">// the picked point as a planarface to </span>\n          <span class=\"green\">// build my sketchplan</span>\n \n          <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> obj2 <span class=\"blue\">in</span> \n            element.get_Geometry( ops ).Objects )\n          {\n            <span class=\"blue\">if</span>( obj2.GetType() == <span class=\"blue\">typeof</span>( <span class=\"teal\">Solid</span> ) )\n            {\n              <span class=\"teal\">Solid</span> solid2 = obj2 <span class=\"blue\">as</span> <span class=\"teal\">Solid</span>;\n              <span class=\"blue\">foreach</span>( <span class=\"teal\">Face</span> face2 <span class=\"blue\">in</span> solid2.Faces )\n              {\n                <span class=\"blue\">try</span>\n                {\n                  <span class=\"blue\">if</span>( face2.Project( pos )\n                    .XYZPoint.DistanceTo( pos ) == 0 )\n                  {\n                    <span class=\"blue\">return</span> face2 <span class=\"blue\">as</span> <span class=\"teal\">PlanarFace</span>;\n                  }\n                }\n                <span class=\"blue\">catch</span>( <span class=\"teal\">NullReferenceException</span> )\n                {\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    <span class=\"blue\">return</span> <span class=\"blue\">null</span>;\n  }\n \n  <span class=\"green\">// this part is not mine, i found it on the internet, </span>\n  <span class=\"green\">// i don't anderstand all the code</span>\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">ExternalFileReference</span>&gt; \n    GetLinkedFileReferences( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> collector = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( \n      _document );\n \n    <span class=\"blue\">var</span> linkedElements = collector\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) )\n      .Select( x =&gt; x.GetExternalFileReference() )\n      .ToList();\n \n    <span class=\"blue\">return</span> linkedElements;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; \n    GetLinkedDocuments( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> linkedfiles = GetLinkedFileReferences( \n      _document );\n \n    <span class=\"blue\">var</span> linkedFileNames = linkedfiles\n      .Select( x =&gt; <span class=\"teal\">ModelPathUtils</span>\n        .ConvertModelPathToUserVisiblePath( \n          x.GetAbsolutePath() ) ).ToList();\n \n    <span class=\"blue\">return</span> _document.Application.Documents\n      .Cast&lt;<span class=\"teal\">Document</span>&gt;()\n      .Where( doc =&gt; linkedFileNames.Any( \n        fileName =&gt; doc.PathName.Equals( fileName ) ) );\n  }\n}\n</pre>\n<p>Here is \n\n<a href=\"zip/SelectFaceInLinkedFile.zip\">\nSelectFaceInLinkedFile.zip</a> containing \n\nValentin's sample code and Visual Studio solution.\n\n<p>Many thanks to Valentin for the novel use of this method and its undocumented embedded information.\n\n<p>This is obviously all undocumented internal stuff that is not guaranteed to work at all in any way, and actually is guaranteed to change at some point in the future (as everything must change) with no prior warning whatsoever, so use at your own risk or just ponder and enjoy.\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0766_sel_face_linked_file",
    "header_text": "Reference and Stable Representation",
    "local_header_href": "#reference-and-stable-representation",
    "chunk_text": "<h4>Reference and Stable Representation</h4><p>A reference provides a possibility to identify a piece of geometry, even though geometry is transient, not persistent, memory only, generated on the fly.\nStill, we sometimes need to identify a piece of it and remember which piece it was.\nFor instance, to \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-by-iterating-faces.html\">\ndimension the distance</a>\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-using-findreferencesbydirection.html\">\nbetween two parallel walls</a>, \n\nwe need to identify which wall face we are measuring from.\nThis can be achieved using references.\n\n<p>A stable representation can be used to preserve and restore a reference later in the same Revit session or even in a different session in the same document. \nThe ParseFromStableRepresentation method is used to restore the reference. \nThe representation is based on the internal Revit structure and is not intended to be parsed by anyone else except ParseFromStableRepresentation.\n\n<p>Here is a rather unexpected use of this method and the undocumented internals of the stable string representation:\n\n\n<a name=\"2\"></a>\n<h4>Face Selection in Linked File</h4>\n<p>Some Revit API functionality is limited to the current project and will not work for linked files.\nCurrently, this most heavily affects the geometric analysis, and methods like FindReferencesWithContextByDirection and its new optimised and simplified Revit 2013 wrapper class ReferenceIntersector.\n\n<p>Another affected area is the interactive element selection, which led to the following \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/04/revit-2013-product-guids-and-guid-algorithm.html?cid=6a00e553e1689788330168ea336953970c#comment-6a00e553e1689788330168ea336953970c\">\nquestion</a> by \n\n<a href=\"mailto:vlouzeau@gmail.com\">\nValentin Louzeau</a>:\n\n\n<p><strong>Question:</strong> I'm working on a plugin and asking the user to select a face, but it does not work in linked files. \nI found something using ObjectType.PointOnElement for selection but it doesn't seem to work for my needs. \nIs there an easy way to do that or do you already have a solution?\n\n<p><strong>Answer:</strong> Nope, sorry, there is no easy way to work on a face in a linked file, and I am not aware of any solution for this.\n\n<p><strong>Response:</strong> I found a solution using the method ConvertToStableRepresentation on the Reference class.\n\n<p>This string contains the ref document unique ID, its name, and the ID of the picked element in this document. \nYou can get its position in the ref doc and if you insert origin to origin, the element has the same position in the two documents.\n\n<p>Here is an example of a stable representation for a reference to a picked face on a wall in a linked file:\n\n<ul>\n<li>\"7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a1:0:RVTLINK/7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a0:161224:5:SURFACE\"\n</li></ul>\n<p>From this, the wall element id \"161224\" can be extracted.\n\n<p>Here is some code in which I tested making use of this:\n\n<pre class=\"code\">\n[<span class=\"teal\">TransactionAttribute</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">SelectFaceInLinkedFile</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute( \n    <span class=\"teal\">ExternalCommandData</span> commandData, \n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message, \n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n \n    <span class=\"teal\">PlanarFace</span> Plan = SelectFace( uiapp );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">PlanarFace</span> SelectFace( \n    <span class=\"teal\">UIApplication</span> uiapp )\n  {\n    <span class=\"teal\">Document</span> doc = uiapp.ActiveUIDocument.Document;\n \n    <span class=\"green\">// get all ref doc. </span>\n \n    <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; doc2 \n      = GetLinkedDocuments( doc );\n \n    <span class=\"green\">// get the ref of a selected plane</span>\n \n    <span class=\"teal\">Selection</span> sel = uiapp.ActiveUIDocument.Selection;\n \n    <span class=\"teal\">Reference</span> pickedRef = sel.PickObject( \n      <span class=\"teal\">ObjectType</span>.PointOnElement, \n      <span class=\"maroon\">\"Please select a Face\"</span> );\n \n    <span class=\"teal\">Element</span> elem = doc.GetElement( \n      pickedRef.ElementId );\n \n    <span class=\"green\">// get the true position picked </span>\n    <span class=\"green\">// in the active document</span>\n \n    <span class=\"teal\">XYZ</span> pos = pickedRef.GlobalPoint;\n \n    <span class=\"green\">// get the ID of the element containing the </span>\n    <span class=\"green\">// face you picked in the active document </span>\n    <span class=\"green\">// and in its host document</span>\n \n    <span class=\"blue\">string</span> s = pickedRef\n      .ConvertToStableRepresentation( doc );\n \n    <span class=\"blue\">string</span>[] tab_str = s.Split( <span class=\"maroon\">':'</span> );\n \n    <span class=\"blue\">string</span> id = tab_str[tab_str.Length - 3];\n \n    <span class=\"blue\">int</span> ID;\n    <span class=\"teal\">Int32</span>.TryParse( id, <span class=\"blue\">out</span> ID );\n \n    <span class=\"teal\">Type</span> et = elem.GetType();\n \n    <span class=\"blue\">if</span>( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkInstance</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">Instance</span> ) == et )\n    {\n      <span class=\"blue\">foreach</span>( <span class=\"teal\">Document</span> d <span class=\"blue\">in</span> doc2 )\n      {\n        <span class=\"blue\">if</span>( elem.Name.Contains( d.Title ) )\n        {\n          <span class=\"teal\">Element</span> element = d.GetElement( \n            <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( ID ) );\n \n          <span class=\"teal\">Options</span> ops = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n          ops.ComputeReferences = <span class=\"blue\">true</span>;\n \n          <span class=\"green\">// write the name of the element and the </span>\n          <span class=\"green\">// number of solids in this only for </span>\n          <span class=\"green\">// control to show the possibilities</span>\n \n          <span class=\"teal\">MessageBox</span>.Show( element.Name, \n            element.get_Geometry( ops )\n              .Objects.Size.ToString() );\n \n          <span class=\"teal\">GeometryObject</span> obj \n            = element.get_Geometry( ops )\n              .Objects.get_Item( 0 );\n \n          <span class=\"green\">// test all surfaces of solids in the </span>\n          <span class=\"green\">// element and return the one containing </span>\n          <span class=\"green\">// the picked point as a planarface to </span>\n          <span class=\"green\">// build my sketchplan</span>\n \n          <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> obj2 <span class=\"blue\">in</span> \n            element.get_Geometry( ops ).Objects )\n          {\n            <span class=\"blue\">if</span>( obj2.GetType() == <span class=\"blue\">typeof</span>( <span class=\"teal\">Solid</span> ) )\n            {\n              <span class=\"teal\">Solid</span> solid2 = obj2 <span class=\"blue\">as</span> <span class=\"teal\">Solid</span>;\n              <span class=\"blue\">foreach</span>( <span class=\"teal\">Face</span> face2 <span class=\"blue\">in</span> solid2.Faces )\n              {\n                <span class=\"blue\">try</span>\n                {\n                  <span class=\"blue\">if</span>( face2.Project( pos )\n                    .XYZPoint.DistanceTo( pos ) == 0 )\n                  {\n                    <span class=\"blue\">return</span> face2 <span class=\"blue\">as</span> <span class=\"teal\">PlanarFace</span>;\n                  }\n                }\n                <span class=\"blue\">catch</span>( <span class=\"teal\">NullReferenceException</span> )\n                {\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    <span class=\"blue\">return</span> <span class=\"blue\">null</span>;\n  }\n \n  <span class=\"green\">// this part is not mine, i found it on the internet, </span>\n  <span class=\"green\">// i don't anderstand all the code</span>\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">ExternalFileReference</span>&gt; \n    GetLinkedFileReferences( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> collector = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( \n      _document );\n \n    <span class=\"blue\">var</span> linkedElements = collector\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) )\n      .Select( x =&gt; x.GetExternalFileReference() )\n      .ToList();\n \n    <span class=\"blue\">return</span> linkedElements;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; \n    GetLinkedDocuments( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> linkedfiles = GetLinkedFileReferences( \n      _document );\n \n    <span class=\"blue\">var</span> linkedFileNames = linkedfiles\n      .Select( x =&gt; <span class=\"teal\">ModelPathUtils</span>\n        .ConvertModelPathToUserVisiblePath( \n          x.GetAbsolutePath() ) ).ToList();\n \n    <span class=\"blue\">return</span> _document.Application.Documents\n      .Cast&lt;<span class=\"teal\">Document</span>&gt;()\n      .Where( doc =&gt; linkedFileNames.Any( \n        fileName =&gt; doc.PathName.Equals( fileName ) ) );\n  }\n}\n</pre>\n<p>Here is \n\n<a href=\"zip/SelectFaceInLinkedFile.zip\">\nSelectFaceInLinkedFile.zip</a> containing \n\nValentin's sample code and Visual Studio solution.\n\n<p>Many thanks to Valentin for the novel use of this method and its undocumented embedded information.\n\n<p>This is obviously all undocumented internal stuff that is not guaranteed to work at all in any way, and actually is guaranteed to change at some point in the future (as everything must change) with no prior warning whatsoever, so use at your own risk or just ponder and enjoy.\n\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0766_sel_face_linked_file",
    "header_text": "Face Selection in Linked File",
    "local_header_href": "#face-selection-in-linked-file",
    "chunk_text": "<h4>Face Selection in Linked File</h4><p>Some Revit API functionality is limited to the current project and will not work for linked files.\nCurrently, this most heavily affects the geometric analysis, and methods like FindReferencesWithContextByDirection and its new optimised and simplified Revit 2013 wrapper class ReferenceIntersector.\n\n<p>Another affected area is the interactive element selection, which led to the following \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/04/revit-2013-product-guids-and-guid-algorithm.html?cid=6a00e553e1689788330168ea336953970c#comment-6a00e553e1689788330168ea336953970c\">\nquestion</a> by \n\n<a href=\"mailto:vlouzeau@gmail.com\">\nValentin Louzeau</a>:\n\n\n<p><strong>Question:</strong> I'm working on a plugin and asking the user to select a face, but it does not work in linked files. \nI found something using ObjectType.PointOnElement for selection but it doesn't seem to work for my needs. \nIs there an easy way to do that or do you already have a solution?\n\n<p><strong>Answer:</strong> Nope, sorry, there is no easy way to work on a face in a linked file, and I am not aware of any solution for this.\n\n<p><strong>Response:</strong> I found a solution using the method ConvertToStableRepresentation on the Reference class.\n\n<p>This string contains the ref document unique ID, its name, and the ID of the picked element in this document. \nYou can get its position in the ref doc and if you insert origin to origin, the element has the same position in the two documents.\n\n<p>Here is an example of a stable representation for a reference to a picked face on a wall in a linked file:\n\n<ul>\n<li>\"7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a1:0:RVTLINK/7c25d827-3c9c-4cca-b3a0-dd28ee09a289-0002e3a0:161224:5:SURFACE\"\n</li></ul>\n<p>From this, the wall element id \"161224\" can be extracted.\n\n<p>Here is some code in which I tested making use of this:\n\n<pre class=\"code\">\n[<span class=\"teal\">TransactionAttribute</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">public</span> <span class=\"blue\">class</span> <span class=\"teal\">SelectFaceInLinkedFile</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute( \n    <span class=\"teal\">ExternalCommandData</span> commandData, \n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message, \n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n \n    <span class=\"teal\">PlanarFace</span> Plan = SelectFace( uiapp );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">PlanarFace</span> SelectFace( \n    <span class=\"teal\">UIApplication</span> uiapp )\n  {\n    <span class=\"teal\">Document</span> doc = uiapp.ActiveUIDocument.Document;\n \n    <span class=\"green\">// get all ref doc. </span>\n \n    <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; doc2 \n      = GetLinkedDocuments( doc );\n \n    <span class=\"green\">// get the ref of a selected plane</span>\n \n    <span class=\"teal\">Selection</span> sel = uiapp.ActiveUIDocument.Selection;\n \n    <span class=\"teal\">Reference</span> pickedRef = sel.PickObject( \n      <span class=\"teal\">ObjectType</span>.PointOnElement, \n      <span class=\"maroon\">\"Please select a Face\"</span> );\n \n    <span class=\"teal\">Element</span> elem = doc.GetElement( \n      pickedRef.ElementId );\n \n    <span class=\"green\">// get the true position picked </span>\n    <span class=\"green\">// in the active document</span>\n \n    <span class=\"teal\">XYZ</span> pos = pickedRef.GlobalPoint;\n \n    <span class=\"green\">// get the ID of the element containing the </span>\n    <span class=\"green\">// face you picked in the active document </span>\n    <span class=\"green\">// and in its host document</span>\n \n    <span class=\"blue\">string</span> s = pickedRef\n      .ConvertToStableRepresentation( doc );\n \n    <span class=\"blue\">string</span>[] tab_str = s.Split( <span class=\"maroon\">':'</span> );\n \n    <span class=\"blue\">string</span> id = tab_str[tab_str.Length - 3];\n \n    <span class=\"blue\">int</span> ID;\n    <span class=\"teal\">Int32</span>.TryParse( id, <span class=\"blue\">out</span> ID );\n \n    <span class=\"teal\">Type</span> et = elem.GetType();\n \n    <span class=\"blue\">if</span>( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkInstance</span> ) == et\n      || <span class=\"blue\">typeof</span>( <span class=\"teal\">Instance</span> ) == et )\n    {\n      <span class=\"blue\">foreach</span>( <span class=\"teal\">Document</span> d <span class=\"blue\">in</span> doc2 )\n      {\n        <span class=\"blue\">if</span>( elem.Name.Contains( d.Title ) )\n        {\n          <span class=\"teal\">Element</span> element = d.GetElement( \n            <span class=\"blue\">new</span> <span class=\"teal\">ElementId</span>( ID ) );\n \n          <span class=\"teal\">Options</span> ops = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n          ops.ComputeReferences = <span class=\"blue\">true</span>;\n \n          <span class=\"green\">// write the name of the element and the </span>\n          <span class=\"green\">// number of solids in this only for </span>\n          <span class=\"green\">// control to show the possibilities</span>\n \n          <span class=\"teal\">MessageBox</span>.Show( element.Name, \n            element.get_Geometry( ops )\n              .Objects.Size.ToString() );\n \n          <span class=\"teal\">GeometryObject</span> obj \n            = element.get_Geometry( ops )\n              .Objects.get_Item( 0 );\n \n          <span class=\"green\">// test all surfaces of solids in the </span>\n          <span class=\"green\">// element and return the one containing </span>\n          <span class=\"green\">// the picked point as a planarface to </span>\n          <span class=\"green\">// build my sketchplan</span>\n \n          <span class=\"blue\">foreach</span>( <span class=\"teal\">GeometryObject</span> obj2 <span class=\"blue\">in</span> \n            element.get_Geometry( ops ).Objects )\n          {\n            <span class=\"blue\">if</span>( obj2.GetType() == <span class=\"blue\">typeof</span>( <span class=\"teal\">Solid</span> ) )\n            {\n              <span class=\"teal\">Solid</span> solid2 = obj2 <span class=\"blue\">as</span> <span class=\"teal\">Solid</span>;\n              <span class=\"blue\">foreach</span>( <span class=\"teal\">Face</span> face2 <span class=\"blue\">in</span> solid2.Faces )\n              {\n                <span class=\"blue\">try</span>\n                {\n                  <span class=\"blue\">if</span>( face2.Project( pos )\n                    .XYZPoint.DistanceTo( pos ) == 0 )\n                  {\n                    <span class=\"blue\">return</span> face2 <span class=\"blue\">as</span> <span class=\"teal\">PlanarFace</span>;\n                  }\n                }\n                <span class=\"blue\">catch</span>( <span class=\"teal\">NullReferenceException</span> )\n                {\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    <span class=\"blue\">return</span> <span class=\"blue\">null</span>;\n  }\n \n  <span class=\"green\">// this part is not mine, i found it on the internet, </span>\n  <span class=\"green\">// i don't anderstand all the code</span>\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">ExternalFileReference</span>&gt; \n    GetLinkedFileReferences( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> collector = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( \n      _document );\n \n    <span class=\"blue\">var</span> linkedElements = collector\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RevitLinkType</span> ) )\n      .Select( x =&gt; x.GetExternalFileReference() )\n      .ToList();\n \n    <span class=\"blue\">return</span> linkedElements;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Document</span>&gt; \n    GetLinkedDocuments( <span class=\"teal\">Document</span> _document )\n  {\n    <span class=\"blue\">var</span> linkedfiles = GetLinkedFileReferences( \n      _document );\n \n    <span class=\"blue\">var</span> linkedFileNames = linkedfiles\n      .Select( x =&gt; <span class=\"teal\">ModelPathUtils</span>\n        .ConvertModelPathToUserVisiblePath( \n          x.GetAbsolutePath() ) ).ToList();\n \n    <span class=\"blue\">return</span> _document.Application.Documents\n      .Cast&lt;<span class=\"teal\">Document</span>&gt;()\n      .Where( doc =&gt; linkedFileNames.Any( \n        fileName =&gt; doc.PathName.Equals( fileName ) ) );\n  }\n}\n</pre>\n<p>Here is \n\n<a href=\"zip/SelectFaceInLinkedFile.zip\">\nSelectFaceInLinkedFile.zip</a> containing \n\nValentin's sample code and Visual Studio solution.\n\n<p>Many thanks to Valentin for the novel use of this method and its undocumented embedded information.\n\n<p>This is obviously all undocumented internal stuff that is not guaranteed to work at all in any way, and actually is guaranteed to change at some point in the future (as everything must change) with no prior warning whatsoever, so use at your own risk or just ponder and enjoy.\n\n</p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]