[
  {
    "original_filename": "0772_pipe_insul_mater",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0772_pipe_insul_mater",
    "header_text": "Pipe Insulation and Insulation Material",
    "local_header_href": "#pipe-insulation-and-insulation-material",
    "chunk_text": "<h3>Pipe Insulation and Insulation Material</h3><p>I recently looked at the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/the-revit-2013-mep-api-and-external-services.html\">\nRevit MEP 2013 API</a> and \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/the-adn-mep-sample-adnrme-for-revit-mep-2013.html\">\nmigrated the AdnRme sample to it</a>.\n\n<p>To follow up on that, here is an unexpectedly hard Revit MEP 2013 question by Victor Chekalin, who recently created the nice \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/devblog-devcamp-element-and-project-wide-data.html\">\nDataStorage sample</a>.\n\nThe new question leads to some tricky and interesting aspects on how to access data or database elements through the Revit API that are not immediately accessible via the expected route or \"normal\" channels.\nWhere there's a will, there's a way, though  :-)\n\n<p><strong>Question:</strong> I always get Element materials using an Element.Materials property. \nBut now I've found the issue that I cannot retrieve PipeInsulation and pipe material using Materials property, although these elements have a material.\n\n<p>Furthermore, even if I can retrieve the pipe material via Pipe.PipeType.Material, I still cannot find any way to get PipeInsulation.\n\n<p>So I have two questions\n\n<ol>\n<li>Why there is no possibility to get PipeInsulation and pipe materials via Element.Materials Property?\n<li>Is there a way to get the PipeInsulation material?\n</li></li></ol>\n<p>I understand that pipe material is defined by the pipe type, but, for example, wall materials are defined by wall type as well and I can retrieve them from a wall instance without resorting to the wall type using the Wall.Materials property. Furthermore, the pipe material has a PipeMaterialType type not a Material type. \nWhy?\n\n<p>I looked at the API help, API Reference Guide and read the post on the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2011/06/the-revit-mep-2012-api.html\">\nRevit MEP 2012 API</a> describing\n\nthe new pipe and duct insulations, but I didn't find the answer how to retrieve PipeInsulation material via API. \n\n<p>PipeInsulation and PipeInsulationType don't have a Material property or GetMaterial method. \nThe Materials property has zero size.\n\n<p>By the way, why are so many differences accessing materials from pipe and pipe insulation compared to other elements? \nIt seems for me as if the MEP version has been created by other developers  :-)</p>\n<center>\n<img alt=\"Pipe insulation\" src=\"img/pipe_insulation2.png\"/>\n</center>\n<p><strong>Answer:</strong> As you are aware and point out, the pipe material is defined by the type and not the instance, so you would obviously query the type and not the instance for it.\n\n<p>Pipe insulation is a completely separate element from the pipe, so you have to access the insulation material from the insulation element, not from the pipe. Here is the relevant section from the Revit API 2012 help file What's New section:\n\n<h4 style=\"color:darkblue\">Duct and pipe insulation and lining</h4>\n<p style=\"color:darkblue\">The new classes\n\n<ul>\n<li style=\"color:darkblue\">DuctInsulation \n<li style=\"color:darkblue\">PipeInsulation \n<li style=\"color:darkblue\">DuctLining \n</li></li></li></ul>\n<p style=\"color:darkblue\">and related types support read/write and create access to duct and pipe insulation and lining. \nIn Revit 2012, these objects are now accessible as standalone elements related to their parent duct, pipe, or fitting.\n\n<p>Yes, you are correct in that the access to materials for pipes is different and more difficult compared to other elements such as walls.\n\n<p>There is actually on-going work in this area, and it is not yet complete; prior to 2013, pipes didn't have 'normal' materials, but rather just a string property. \nWe are aware that materials for Walls and other elements in general are directly API accessible from the Element, instead of having to dig into the type, and would like pipe and pipe insulation material access to be just as easy.\n\n<p>Again, as you saw, RevitLookup displays the pipe insulation with a MaterialSet which is not displayed in bold like it is for other elements, because it is empty:</p>\n<center>\n<img alt=\"Pipe insulation type in RevitLookup\" src=\"img/snoop_pipe_insulation_type.png\" width=\"400\"/>\n</center>\n<p>Still, we found a solution to your issue by using alternative access routes.\n\n<p>You can retrieve the parameter named 'Material' off the PipeInsulationType object from the PipeInsulation object. \nThe parameter is an ElementId.\n\n<p>This little difficulty is compounded by the fact that we did not immediately find any easy way to get the PipeInsulationType from a pipe.\n\n<p>One way that we found to achieve this is to use a filter to retrieve all PipeInsulation elements in the document and compare the HostElementId of each one to that of the original pipe.  \nWhen the matching one is found, you have the PipeInsulation element corresponding to that pipe, you can get the PipeInsulationType from that, and then get the material from the parameter.\n\n<p>We implemented the following helper classes and methods to demonstrate this:\n\n<ul>\n<li>PipeFilter: Restrict user selection to pipe element only.\n<li>GetSelectedElement: Return first pre-selected element or prompt user to select a pipe.\n<li>GetPipeInslationFromPipe: Return pipe insulation from given pipe.\n<li>GetMaterialFromPipeInsulation: Return material from given pipe insulation.\n<li>GetInsulationFromSelection: Prompt user to select a pipe, retrieve its insulation and insulation material, and report the results.\n</li></li></li></li></li></ul>\n<p>Here is the entire sample code exercising these:\n\n<pre class=\"code\">\n<span class=\"blue\">const</span> <span class=\"blue\">string</span> _caption = <span class=\"maroon\">\"Pipe Insulation Info\"</span>;\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Restrict user selection to pipe element only</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">class</span> <span class=\"teal\">PipeFilter</span> : <span class=\"teal\">ISelectionFilter</span>\n{\n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> AllowElement( <span class=\"teal\">Element</span> e )\n  {\n    <span class=\"blue\">return</span> e <span class=\"blue\">is</span> <span class=\"teal\">Pipe</span>;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> AllowReference( <span class=\"teal\">Reference</span> r, <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">return</span> <span class=\"blue\">true</span>;\n  }\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return first pre-selected element or </span>\n<span class=\"gray\">///</span><span class=\"green\"> prompt user to select a pipe.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">Element</span> GetSelectedElement( <span class=\"teal\">UIDocument</span> uidoc )\n{\n  <span class=\"teal\">Element</span> e = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">SelElementSet</span> elements = uidoc.Selection.Elements;\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == elements || elements.IsEmpty )\n  {\n    <span class=\"blue\">try</span>\n    {\n      <span class=\"teal\">Reference</span> r = uidoc.Selection.PickObject(\n        <span class=\"teal\">ObjectType</span>.Element,\n        <span class=\"blue\">new</span> <span class=\"teal\">PipeFilter</span>(),\n        <span class=\"maroon\">\"Please pick a pipe\"</span> );\n \n      e = uidoc.Document.GetElement( r.ElementId );\n    }\n    <span class=\"blue\">catch</span>( <span class=\"teal\">RvtOperationCanceledException</span> )\n    {\n    }\n  }\n  <span class=\"blue\">else</span> <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != elements &amp;&amp; !elements.IsEmpty )\n  {\n    <span class=\"teal\">IEnumerator</span> it = elements.GetEnumerator();\n \n    <span class=\"blue\">if</span>( it.MoveNext() )\n    {\n      e = it.Current <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n    }\n  }\n  <span class=\"blue\">return</span> e;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return pipe insulation from given pipe.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">PipeInsulation</span> GetPipeInslationFromPipe(\n  <span class=\"teal\">Pipe</span> pipe )\n{\n  <span class=\"blue\">if</span>( pipe == <span class=\"blue\">null</span> )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"pipe\"</span> );\n  }\n \n  <span class=\"teal\">Document</span> doc = pipe.Document;\n \n  <span class=\"teal\">FilteredElementCollector</span> fec\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">PipeInsulation</span> ) );\n \n  <span class=\"teal\">PipeInsulation</span> pipeInsulation = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">PipeInsulation</span> pi <span class=\"blue\">in</span> fec )\n  {\n    <span class=\"green\">// Find the pipe that has this inulation</span>\n \n    <span class=\"blue\">if</span>( pi.HostElementId == pipe.Id )\n      pipeInsulation = pi;\n  }\n  <span class=\"blue\">return</span> pipeInsulation;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return material from given pipe insulation.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">Material</span> GetMaterialFromPipeInsulation(\n  <span class=\"teal\">PipeInsulation</span> pipeInsulation )\n{\n  <span class=\"blue\">if</span>( pipeInsulation == <span class=\"blue\">null</span> )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"pipeInsulation\"</span> );\n  }\n \n  <span class=\"teal\">Document</span> doc = pipeInsulation.Document;\n \n  <span class=\"teal\">PipeInsulationType</span> pipeInsulationType\n    = doc.GetElement( pipeInsulation.GetTypeId() )\n      <span class=\"blue\">as</span> <span class=\"teal\">PipeInsulationType</span>;\n \n  <span class=\"teal\">Parameter</span> p = pipeInsulationType.get_Parameter(\n    <span class=\"maroon\">\"Material\"</span> );\n \n  <span class=\"blue\">return</span> <span class=\"blue\">null</span> == p\n    ? <span class=\"blue\">null</span>\n    : doc.GetElement( p.AsElementId() ) <span class=\"blue\">as</span> <span class=\"teal\">Material</span>;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Prompt user to select a pipe, retrieve its </span>\n<span class=\"gray\">///</span><span class=\"green\"> insulation and insulation material, </span>\n<span class=\"gray\">///</span><span class=\"green\"> and report the results.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">void</span> GetInsulationFromSelection(\n  <span class=\"teal\">UIDocument</span> uidoc )\n{\n  <span class=\"teal\">Element</span> e = GetSelectedElement( uidoc );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != e )\n  {\n    <span class=\"blue\">if</span>( e <span class=\"blue\">is</span> <span class=\"teal\">Pipe</span> )\n    {\n      <span class=\"teal\">PipeInsulation</span> pi\n        = GetPipeInslationFromPipe( e <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span> );\n \n      <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == pi )\n      {\n        <span class=\"teal\">TaskDialog</span>.Show( _caption,\n          <span class=\"maroon\">\"Insulation not found\"</span> );\n      }\n      <span class=\"blue\">else</span>\n      {\n        <span class=\"teal\">Material</span> material\n          = GetMaterialFromPipeInsulation( pi );\n \n        <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == material )\n        {\n          <span class=\"teal\">TaskDialog</span>.Show( _caption,\n            <span class=\"maroon\">\"Material not found\"</span> );\n        }\n        <span class=\"blue\">else</span>\n        {\n          <span class=\"teal\">TaskDialog</span>.Show( _caption,\n            <span class=\"blue\">string</span>.Format( <span class=\"maroon\">\"Material '{0}' &lt;{1}&gt;\"</span>,\n            material.Name, material.Id ) );\n        }\n      }\n    }\n    <span class=\"blue\">else</span>\n    {\n      <span class=\"teal\">TaskDialog</span>.Show( _caption, <span class=\"maroon\">\"Not a pipe\"</span> );\n    }\n  }\n}\n</pre>\n<p>Here is \n\n<a href=\"zip/PipeInsulationMaterial.zip\">PipeInsulationMaterial.zip</a> containing\n\nthe full Visual Studio solution, source code, and add-in manifest for this external command.\n\n<p>Many thanks to Steven Mycynek for researching and creating this solution!\n\n<p>Later, Martin Schmid pointed out that the GetPipeInslationFromPipe method using a filtered element collector and  comparing all pipe insulation element HostElementId properties with the target pipe can be simplified by calling the InsulationLiningBase GetInsulationIds method instead. \nIt takes the pipe element id and returns all pipe insulation element ids associated with it directly like this:\n\n<pre class=\"code\">\n  <span class=\"teal\">ICollection</span>&lt;<span class=\"teal\">ElementId</span>&gt; pipeInsulationIds \n    = <span class=\"teal\">InsulationLiningBase</span>.GetInsulationIds( \n      doc, pipe.Id );\n</pre>\n<p>Not so easy to find, though  :-)\n\n<p>I updated the code in the zip file above to take this approach into account as well, simply adding an assertion to verify that the result is the same.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0772_pipe_insul_mater",
    "header_text": "Duct and pipe insulation and lining",
    "local_header_href": "#duct-and-pipe-insulation-and-lining",
    "chunk_text": "<h4 style=\"color:darkblue\">Duct and pipe insulation and lining</h4><p style=\"color:darkblue\">The new classes\n\n<ul>\n<li style=\"color:darkblue\">DuctInsulation \n<li style=\"color:darkblue\">PipeInsulation \n<li style=\"color:darkblue\">DuctLining \n</li></li></li></ul>\n<p style=\"color:darkblue\">and related types support read/write and create access to duct and pipe insulation and lining. \nIn Revit 2012, these objects are now accessible as standalone elements related to their parent duct, pipe, or fitting.\n\n<p>Yes, you are correct in that the access to materials for pipes is different and more difficult compared to other elements such as walls.\n\n<p>There is actually on-going work in this area, and it is not yet complete; prior to 2013, pipes didn't have 'normal' materials, but rather just a string property. \nWe are aware that materials for Walls and other elements in general are directly API accessible from the Element, instead of having to dig into the type, and would like pipe and pipe insulation material access to be just as easy.\n\n<p>Again, as you saw, RevitLookup displays the pipe insulation with a MaterialSet which is not displayed in bold like it is for other elements, because it is empty:</p>\n<center>\n<img alt=\"Pipe insulation type in RevitLookup\" src=\"img/snoop_pipe_insulation_type.png\" width=\"400\"/>\n</center>\n<p>Still, we found a solution to your issue by using alternative access routes.\n\n<p>You can retrieve the parameter named 'Material' off the PipeInsulationType object from the PipeInsulation object. \nThe parameter is an ElementId.\n\n<p>This little difficulty is compounded by the fact that we did not immediately find any easy way to get the PipeInsulationType from a pipe.\n\n<p>One way that we found to achieve this is to use a filter to retrieve all PipeInsulation elements in the document and compare the HostElementId of each one to that of the original pipe.  \nWhen the matching one is found, you have the PipeInsulation element corresponding to that pipe, you can get the PipeInsulationType from that, and then get the material from the parameter.\n\n<p>We implemented the following helper classes and methods to demonstrate this:\n\n<ul>\n<li>PipeFilter: Restrict user selection to pipe element only.\n<li>GetSelectedElement: Return first pre-selected element or prompt user to select a pipe.\n<li>GetPipeInslationFromPipe: Return pipe insulation from given pipe.\n<li>GetMaterialFromPipeInsulation: Return material from given pipe insulation.\n<li>GetInsulationFromSelection: Prompt user to select a pipe, retrieve its insulation and insulation material, and report the results.\n</li></li></li></li></li></ul>\n<p>Here is the entire sample code exercising these:\n\n<pre class=\"code\">\n<span class=\"blue\">const</span> <span class=\"blue\">string</span> _caption = <span class=\"maroon\">\"Pipe Insulation Info\"</span>;\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Restrict user selection to pipe element only</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">class</span> <span class=\"teal\">PipeFilter</span> : <span class=\"teal\">ISelectionFilter</span>\n{\n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> AllowElement( <span class=\"teal\">Element</span> e )\n  {\n    <span class=\"blue\">return</span> e <span class=\"blue\">is</span> <span class=\"teal\">Pipe</span>;\n  }\n \n  <span class=\"blue\">public</span> <span class=\"blue\">bool</span> AllowReference( <span class=\"teal\">Reference</span> r, <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">return</span> <span class=\"blue\">true</span>;\n  }\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return first pre-selected element or </span>\n<span class=\"gray\">///</span><span class=\"green\"> prompt user to select a pipe.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">Element</span> GetSelectedElement( <span class=\"teal\">UIDocument</span> uidoc )\n{\n  <span class=\"teal\">Element</span> e = <span class=\"blue\">null</span>;\n \n  <span class=\"teal\">SelElementSet</span> elements = uidoc.Selection.Elements;\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == elements || elements.IsEmpty )\n  {\n    <span class=\"blue\">try</span>\n    {\n      <span class=\"teal\">Reference</span> r = uidoc.Selection.PickObject(\n        <span class=\"teal\">ObjectType</span>.Element,\n        <span class=\"blue\">new</span> <span class=\"teal\">PipeFilter</span>(),\n        <span class=\"maroon\">\"Please pick a pipe\"</span> );\n \n      e = uidoc.Document.GetElement( r.ElementId );\n    }\n    <span class=\"blue\">catch</span>( <span class=\"teal\">RvtOperationCanceledException</span> )\n    {\n    }\n  }\n  <span class=\"blue\">else</span> <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != elements &amp;&amp; !elements.IsEmpty )\n  {\n    <span class=\"teal\">IEnumerator</span> it = elements.GetEnumerator();\n \n    <span class=\"blue\">if</span>( it.MoveNext() )\n    {\n      e = it.Current <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n    }\n  }\n  <span class=\"blue\">return</span> e;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return pipe insulation from given pipe.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">PipeInsulation</span> GetPipeInslationFromPipe(\n  <span class=\"teal\">Pipe</span> pipe )\n{\n  <span class=\"blue\">if</span>( pipe == <span class=\"blue\">null</span> )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"pipe\"</span> );\n  }\n \n  <span class=\"teal\">Document</span> doc = pipe.Document;\n \n  <span class=\"teal\">FilteredElementCollector</span> fec\n    = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n      .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">PipeInsulation</span> ) );\n \n  <span class=\"teal\">PipeInsulation</span> pipeInsulation = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">PipeInsulation</span> pi <span class=\"blue\">in</span> fec )\n  {\n    <span class=\"green\">// Find the pipe that has this inulation</span>\n \n    <span class=\"blue\">if</span>( pi.HostElementId == pipe.Id )\n      pipeInsulation = pi;\n  }\n  <span class=\"blue\">return</span> pipeInsulation;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Return material from given pipe insulation.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"teal\">Material</span> GetMaterialFromPipeInsulation(\n  <span class=\"teal\">PipeInsulation</span> pipeInsulation )\n{\n  <span class=\"blue\">if</span>( pipeInsulation == <span class=\"blue\">null</span> )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">ArgumentNullException</span>( <span class=\"maroon\">\"pipeInsulation\"</span> );\n  }\n \n  <span class=\"teal\">Document</span> doc = pipeInsulation.Document;\n \n  <span class=\"teal\">PipeInsulationType</span> pipeInsulationType\n    = doc.GetElement( pipeInsulation.GetTypeId() )\n      <span class=\"blue\">as</span> <span class=\"teal\">PipeInsulationType</span>;\n \n  <span class=\"teal\">Parameter</span> p = pipeInsulationType.get_Parameter(\n    <span class=\"maroon\">\"Material\"</span> );\n \n  <span class=\"blue\">return</span> <span class=\"blue\">null</span> == p\n    ? <span class=\"blue\">null</span>\n    : doc.GetElement( p.AsElementId() ) <span class=\"blue\">as</span> <span class=\"teal\">Material</span>;\n}\n \n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Prompt user to select a pipe, retrieve its </span>\n<span class=\"gray\">///</span><span class=\"green\"> insulation and insulation material, </span>\n<span class=\"gray\">///</span><span class=\"green\"> and report the results.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">void</span> GetInsulationFromSelection(\n  <span class=\"teal\">UIDocument</span> uidoc )\n{\n  <span class=\"teal\">Element</span> e = GetSelectedElement( uidoc );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != e )\n  {\n    <span class=\"blue\">if</span>( e <span class=\"blue\">is</span> <span class=\"teal\">Pipe</span> )\n    {\n      <span class=\"teal\">PipeInsulation</span> pi\n        = GetPipeInslationFromPipe( e <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span> );\n \n      <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == pi )\n      {\n        <span class=\"teal\">TaskDialog</span>.Show( _caption,\n          <span class=\"maroon\">\"Insulation not found\"</span> );\n      }\n      <span class=\"blue\">else</span>\n      {\n        <span class=\"teal\">Material</span> material\n          = GetMaterialFromPipeInsulation( pi );\n \n        <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == material )\n        {\n          <span class=\"teal\">TaskDialog</span>.Show( _caption,\n            <span class=\"maroon\">\"Material not found\"</span> );\n        }\n        <span class=\"blue\">else</span>\n        {\n          <span class=\"teal\">TaskDialog</span>.Show( _caption,\n            <span class=\"blue\">string</span>.Format( <span class=\"maroon\">\"Material '{0}' &lt;{1}&gt;\"</span>,\n            material.Name, material.Id ) );\n        }\n      }\n    }\n    <span class=\"blue\">else</span>\n    {\n      <span class=\"teal\">TaskDialog</span>.Show( _caption, <span class=\"maroon\">\"Not a pipe\"</span> );\n    }\n  }\n}\n</pre>\n<p>Here is \n\n<a href=\"zip/PipeInsulationMaterial.zip\">PipeInsulationMaterial.zip</a> containing\n\nthe full Visual Studio solution, source code, and add-in manifest for this external command.\n\n<p>Many thanks to Steven Mycynek for researching and creating this solution!\n\n<p>Later, Martin Schmid pointed out that the GetPipeInslationFromPipe method using a filtered element collector and  comparing all pipe insulation element HostElementId properties with the target pipe can be simplified by calling the InsulationLiningBase GetInsulationIds method instead. \nIt takes the pipe element id and returns all pipe insulation element ids associated with it directly like this:\n\n<pre class=\"code\">\n  <span class=\"teal\">ICollection</span>&lt;<span class=\"teal\">ElementId</span>&gt; pipeInsulationIds \n    = <span class=\"teal\">InsulationLiningBase</span>.GetInsulationIds( \n      doc, pipe.Id );\n</pre>\n<p>Not so easy to find, though  :-)\n\n<p>I updated the code in the zip file above to take this approach into account as well, simply adding an assertion to verify that the result is the same.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  }
]