[
  {
    "original_filename": "0780_devlab_room_sep",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0780_devlab_room_sep",
    "header_text": "DevLab and Room Separation",
    "local_header_href": "#devlab-and-room-separation",
    "chunk_text": "<h3>DevLab and Room Separation</h3><p>Today is DevLab with almost fifty participants, so we are in several separate rooms.\nI never left the Revit room, and am busy enough with that.\nTalk about room separation.\n\n<p>Here are one or two little items that cropped up today, contributed by Eric Boehlke of\n\n<a href=\"http://www.truevis.com\">\ntruevis.com</a>.\n\nThe first is actually a question on the creation of room separation lines that I already replied to in response to a \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/03/on-creating-a-mass-from-3d-points.html?cid=6a00e553e168978833016303fac96e970d#comment-6a00e553e168978833016303fac96e970d\">\ncomment</a> from \n\nAmmar on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/03/on-creating-a-mass-from-3d-points.html\">\ncreating a mass</a>:\n\n<a name=\"2\"></a>\n<h4>Creating a Room Separation Line</h4>\n<p><strong>Question:</strong> It seems that we have no access to create room separation lines?\n\n<p><strong>Answer:</strong> Please check out the NewRoomBoundaryLines, NewSpaceBoundaryLines, NewSpaces and other related methods.\n\n<p>Eric ran into the same issue, and the answer I provided to Ammar does not show up in his Google search attempt, so here it is now, promoted to a main blog post status.\n\n<p>Here is Eric's code snippet to generate a 10 by 8 room by first creating a rectangular sequence of four room separation lines using the NewRoomBoundaryLines method on a given level:\n\n<pre class=\"code\">\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Create a room on a given level.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">void</span> CreateRoom( \n  <span class=\"teal\">Document</span> doc, \n  <span class=\"teal\">Level</span> level )\n{\n  <span class=\"teal\">Application</span> app = doc.Application;\n \n  Autodesk.Revit.Creation.<span class=\"teal\">Application</span> \n    appCreation = app.Create;\n \n  Autodesk.Revit.Creation.<span class=\"teal\">Document</span> \n    docCreation = doc.Create;\n \n  <span class=\"teal\">XYZ</span> pt1 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, -5, 0 );\n  <span class=\"teal\">XYZ</span> pt2 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 5, 0 );\n  <span class=\"teal\">XYZ</span> pt3 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 8, 5, 0 );\n  <span class=\"teal\">XYZ</span> pt4 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 8, -5, 0 );\n \n  <span class=\"teal\">Line</span> line1 = appCreation.NewLine( pt1, pt2, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line2 = appCreation.NewLine( pt2, pt3, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line3 = appCreation.NewLine( pt3, pt4, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line4 = appCreation.NewLine( pt4, pt1, <span class=\"blue\">true</span> );\n \n  <span class=\"teal\">CurveArray</span> curveArr = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n  curveArr.Append( line1 );\n  curveArr.Append( line2 );\n  curveArr.Append( line3 );\n  curveArr.Append( line4 );\n \n  docCreation.NewRoomBoundaryLines(\n    doc.ActiveView.SketchPlane,\n    curveArr, doc.ActiveView );\n \n  <span class=\"green\">// Create a new room</span>\n \n  <span class=\"teal\">UV</span> tagPoint = <span class=\"blue\">new</span> <span class=\"teal\">UV</span>( 4, 0 );\n \n  <span class=\"teal\">Room</span> room = docCreation.NewRoom( \n    level, tagPoint );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == room )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">Exception</span>( \n      <span class=\"maroon\">\"Create a new room failed.\"</span> );\n  }\n  room.Number = <span class=\"maroon\">\"42\"</span>;\n  room.Name = <span class=\"maroon\">\"Lobby\"</span>;\n \n  <span class=\"teal\">RoomTag</span> tag = docCreation.NewRoomTag( \n    room, tagPoint, doc.ActiveView );\n}\n</pre>\n<a name=\"3\"></a>\n<h4>CopyPathEx and Other Nifty Utilities</h4>\n<p>Eric also pointed to a list of \n\n<a href=\"http://revitlearningclub.blogspot.com/2011/12/great-freeware-for-revit-work.html\">\ngreat freeware for Revit work</a>,\n\nfrom which I immediately installed \n\n<b><a href=\"http://www.mlin.net/other.shtml\">PathCopyEx</a></b>\n<a href=\"http://www.mlin.net/files/PathCopyEx.msi\">PathCopyEx.msi</a>.\n\nMany thanks to Eric for his code snippet and helpful pointers!\n\n<p>Now I have to start thinking about getting down to the airport in time for my flight back home to Europe...\n</p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0780_devlab_room_sep",
    "header_text": "Creating a Room Separation Line",
    "local_header_href": "#creating-a-room-separation-line",
    "chunk_text": "<h4>Creating a Room Separation Line</h4><p><strong>Question:</strong> It seems that we have no access to create room separation lines?\n\n<p><strong>Answer:</strong> Please check out the NewRoomBoundaryLines, NewSpaceBoundaryLines, NewSpaces and other related methods.\n\n<p>Eric ran into the same issue, and the answer I provided to Ammar does not show up in his Google search attempt, so here it is now, promoted to a main blog post status.\n\n<p>Here is Eric's code snippet to generate a 10 by 8 room by first creating a rectangular sequence of four room separation lines using the NewRoomBoundaryLines method on a given level:\n\n<pre class=\"code\">\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Create a room on a given level.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">void</span> CreateRoom( \n  <span class=\"teal\">Document</span> doc, \n  <span class=\"teal\">Level</span> level )\n{\n  <span class=\"teal\">Application</span> app = doc.Application;\n \n  Autodesk.Revit.Creation.<span class=\"teal\">Application</span> \n    appCreation = app.Create;\n \n  Autodesk.Revit.Creation.<span class=\"teal\">Document</span> \n    docCreation = doc.Create;\n \n  <span class=\"teal\">XYZ</span> pt1 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, -5, 0 );\n  <span class=\"teal\">XYZ</span> pt2 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 5, 0 );\n  <span class=\"teal\">XYZ</span> pt3 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 8, 5, 0 );\n  <span class=\"teal\">XYZ</span> pt4 = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 8, -5, 0 );\n \n  <span class=\"teal\">Line</span> line1 = appCreation.NewLine( pt1, pt2, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line2 = appCreation.NewLine( pt2, pt3, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line3 = appCreation.NewLine( pt3, pt4, <span class=\"blue\">true</span> );\n  <span class=\"teal\">Line</span> line4 = appCreation.NewLine( pt4, pt1, <span class=\"blue\">true</span> );\n \n  <span class=\"teal\">CurveArray</span> curveArr = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n  curveArr.Append( line1 );\n  curveArr.Append( line2 );\n  curveArr.Append( line3 );\n  curveArr.Append( line4 );\n \n  docCreation.NewRoomBoundaryLines(\n    doc.ActiveView.SketchPlane,\n    curveArr, doc.ActiveView );\n \n  <span class=\"green\">// Create a new room</span>\n \n  <span class=\"teal\">UV</span> tagPoint = <span class=\"blue\">new</span> <span class=\"teal\">UV</span>( 4, 0 );\n \n  <span class=\"teal\">Room</span> room = docCreation.NewRoom( \n    level, tagPoint );\n \n  <span class=\"blue\">if</span>( <span class=\"blue\">null</span> == room )\n  {\n    <span class=\"blue\">throw</span> <span class=\"blue\">new</span> <span class=\"teal\">Exception</span>( \n      <span class=\"maroon\">\"Create a new room failed.\"</span> );\n  }\n  room.Number = <span class=\"maroon\">\"42\"</span>;\n  room.Name = <span class=\"maroon\">\"Lobby\"</span>;\n \n  <span class=\"teal\">RoomTag</span> tag = docCreation.NewRoomTag( \n    room, tagPoint, doc.ActiveView );\n}\n</pre>\n<a name=\"3\"></a>\n<h4>CopyPathEx and Other Nifty Utilities</h4>\n<p>Eric also pointed to a list of \n\n<a href=\"http://revitlearningclub.blogspot.com/2011/12/great-freeware-for-revit-work.html\">\ngreat freeware for Revit work</a>,\n\nfrom which I immediately installed \n\n<b><a href=\"http://www.mlin.net/other.shtml\">PathCopyEx</a></b>\n<a href=\"http://www.mlin.net/files/PathCopyEx.msi\">PathCopyEx.msi</a>.\n\nMany thanks to Eric for his code snippet and helpful pointers!\n\n<p>Now I have to start thinking about getting down to the airport in time for my flight back home to Europe...\n</p></p></p></p></p></p>"
  },
  {
    "original_filename": "0780_devlab_room_sep",
    "header_text": "CopyPathEx and Other Nifty Utilities",
    "local_header_href": "#copypathex-and-other-nifty-utilities",
    "chunk_text": "<h4>CopyPathEx and Other Nifty Utilities</h4><p>Eric also pointed to a list of \n\n<a href=\"http://revitlearningclub.blogspot.com/2011/12/great-freeware-for-revit-work.html\">\ngreat freeware for Revit work</a>,\n\nfrom which I immediately installed \n\n<b><a href=\"http://www.mlin.net/other.shtml\">PathCopyEx</a></b>\n<a href=\"http://www.mlin.net/files/PathCopyEx.msi\">PathCopyEx.msi</a>.\n\nMany thanks to Eric for his code snippet and helpful pointers!\n\n<p>Now I have to start thinking about getting down to the airport in time for my flight back home to Europe...\n</p></p>"
  }
]