[
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "DivideParts in F#",
    "local_header_href": "#divideparts-in-f",
    "chunk_text": "<h3>DivideParts in F#</h3><p>My internet connection died last night. \nAfter worrying and testing quite a bit last night and this morning, I laid a temporary cable from my neighbour's router. \nShortly after I finished, my own connection came back up again, after about 14 hours downtime. \n<a href=\"http://en.wikipedia.org/wiki/Murphy%27s_law\">Murphy's law</a> remains valid, as always. \nVery reassuring :-) \nThere is lots of building work going on nearby, so probably they broke it and fixed it with no explanations given.\nAnyway, I am back to normal now and \n\n<a href=\"http://en.wikipedia.org/wiki/Crossed_fingers\">\nkeeping my fingers crossed</a>.\n\n<p>Last week, I presented a C# sample by Piotr Zurek of \n\n<a href=\"http://www.cadpro.co.nz/\">\nCADPRO Systems Ltd</a> exercising the \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/09/parts-assemblies-partutils-and-divideparts.html\">\nPartUtils class and its DivideParts method</a>.\n\n<p>As an experiment and for comparison purposes, Piotr decided to port this to F# as well.\nIn his own words:\n\n<p>As an exercise, I decided to port this example to F# to see how it works and whether the F# syntax offers any benefits over C#.\n\n\n<a name=\"2\"></a>\n<h4>Lessons Learned</h4>\n<p>Here are some of the lessons learned:\n\n<h5>Let Not Use</h5>\n<p>Initially, the F# version of the command ran fine only the first time I launched it, and failed in the call to PickObject with an InvalidOperationException saying \"The managed object is not valid\" on the second call.\n\n<p>After isolating the call to PickObject, I changed the following four initialisation statements:\n\n<pre class=\"code\">\n  <span class=\"blue\">use</span> uiApp = commandData.Application\n  <span class=\"blue\">use</span> app  = uiApp.Application\n  <span class=\"blue\">use</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">use</span> doc  = uiDoc.Document\n</pre>\n<p>It turns out that this is wrong, since the F# 'use' statement is just like 'using' in C#.\n\n<p>So when these objects fall out of scope, Dispose will be called on them.\nSince they belong to Revit, they don't like being disposed of by external code.\nChanging 'use' to 'let' fixed that problem:\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> uiApp = commandData.Application\n  <span class=\"blue\">let</span> app  = uiApp.Application\n  <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">let</span> doc  = uiDoc.Document\n</pre>\n<p>Thanks to Kean Walmsley for this explanation.\n\n\n<h5>Pattern Matching Versus :?</h5>\n<p>At one point, I made a little bit of use of F# pattern matching to implement the WallSelectionFilter AllowElement method like this:\n\n<pre class=\"code\">\n      <span class=\"blue\">member</span> x.AllowElement(element) =\n        <span class=\"blue\">match</span> element <span class=\"blue\">with</span>\n        | :? Wall <span class=\"blue\">as</span> element <span class=\"blue\">-&gt;</span> <span class=\"blue\">true</span>\n        | _ <span class=\"blue\">-&gt;</span> <span class=\"blue\">false</span>\n</pre>\n<p>However, on further consideration, it is clearer and more succinct to use the F# ':?' operator, which is an equivalent of 'is' in C#, like this:\n\n<pre class=\"code\">\n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n</pre>\n<h5>Implementing an Exception Handler</h5>\n<p>I initially removed the 'try-catch' exception handler around the call to PickObject to handle a user cancelling the pick operation.\nOn consideration, I found that it translates to 'try-with' in F#.\nThe piping symbol '|' means pretty much 'data received from the last operation':\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> reference = \n    <span class=\"blue\">try</span>\n      sel.PickObject(\n        ObjectType.Element, \n        <span class=\"blue\">new</span> WallSelectionFilter(), \n        <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n    <span class=\"blue\">with</span>\n      | :? Autodesk.Revit.Exceptions.\n        OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n</pre>\n<p>Exiting the mainline execution requires an if-else statement as well: if reference is null, return Result.Canceled. \nThe best solution is probably more \n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>, \n\nthough.\n\n\n<a name=\"3\"></a>\n<h4>Final Implementation</h4>\n<p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Lessons Learned",
    "local_header_href": "#lessons-learned",
    "chunk_text": "<h4>Lessons Learned</h4><p>Here are some of the lessons learned:\n\n<h5>Let Not Use</h5>\n<p>Initially, the F# version of the command ran fine only the first time I launched it, and failed in the call to PickObject with an InvalidOperationException saying \"The managed object is not valid\" on the second call.\n\n<p>After isolating the call to PickObject, I changed the following four initialisation statements:\n\n<pre class=\"code\">\n  <span class=\"blue\">use</span> uiApp = commandData.Application\n  <span class=\"blue\">use</span> app  = uiApp.Application\n  <span class=\"blue\">use</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">use</span> doc  = uiDoc.Document\n</pre>\n<p>It turns out that this is wrong, since the F# 'use' statement is just like 'using' in C#.\n\n<p>So when these objects fall out of scope, Dispose will be called on them.\nSince they belong to Revit, they don't like being disposed of by external code.\nChanging 'use' to 'let' fixed that problem:\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> uiApp = commandData.Application\n  <span class=\"blue\">let</span> app  = uiApp.Application\n  <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">let</span> doc  = uiDoc.Document\n</pre>\n<p>Thanks to Kean Walmsley for this explanation.\n\n\n<h5>Pattern Matching Versus :?</h5>\n<p>At one point, I made a little bit of use of F# pattern matching to implement the WallSelectionFilter AllowElement method like this:\n\n<pre class=\"code\">\n      <span class=\"blue\">member</span> x.AllowElement(element) =\n        <span class=\"blue\">match</span> element <span class=\"blue\">with</span>\n        | :? Wall <span class=\"blue\">as</span> element <span class=\"blue\">-&gt;</span> <span class=\"blue\">true</span>\n        | _ <span class=\"blue\">-&gt;</span> <span class=\"blue\">false</span>\n</pre>\n<p>However, on further consideration, it is clearer and more succinct to use the F# ':?' operator, which is an equivalent of 'is' in C#, like this:\n\n<pre class=\"code\">\n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n</pre>\n<h5>Implementing an Exception Handler</h5>\n<p>I initially removed the 'try-catch' exception handler around the call to PickObject to handle a user cancelling the pick operation.\nOn consideration, I found that it translates to 'try-with' in F#.\nThe piping symbol '|' means pretty much 'data received from the last operation':\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> reference = \n    <span class=\"blue\">try</span>\n      sel.PickObject(\n        ObjectType.Element, \n        <span class=\"blue\">new</span> WallSelectionFilter(), \n        <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n    <span class=\"blue\">with</span>\n      | :? Autodesk.Revit.Exceptions.\n        OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n</pre>\n<p>Exiting the mainline execution requires an if-else statement as well: if reference is null, return Result.Canceled. \nThe best solution is probably more \n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>, \n\nthough.\n\n\n<a name=\"3\"></a>\n<h4>Final Implementation</h4>\n<p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Let Not Use",
    "local_header_href": "#let-not-use",
    "chunk_text": "<h5>Let Not Use</h5><p>Initially, the F# version of the command ran fine only the first time I launched it, and failed in the call to PickObject with an InvalidOperationException saying \"The managed object is not valid\" on the second call.\n\n<p>After isolating the call to PickObject, I changed the following four initialisation statements:\n\n<pre class=\"code\">\n  <span class=\"blue\">use</span> uiApp = commandData.Application\n  <span class=\"blue\">use</span> app  = uiApp.Application\n  <span class=\"blue\">use</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">use</span> doc  = uiDoc.Document\n</pre>\n<p>It turns out that this is wrong, since the F# 'use' statement is just like 'using' in C#.\n\n<p>So when these objects fall out of scope, Dispose will be called on them.\nSince they belong to Revit, they don't like being disposed of by external code.\nChanging 'use' to 'let' fixed that problem:\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> uiApp = commandData.Application\n  <span class=\"blue\">let</span> app  = uiApp.Application\n  <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n  <span class=\"blue\">let</span> doc  = uiDoc.Document\n</pre>\n<p>Thanks to Kean Walmsley for this explanation.\n\n\n<h5>Pattern Matching Versus :?</h5>\n<p>At one point, I made a little bit of use of F# pattern matching to implement the WallSelectionFilter AllowElement method like this:\n\n<pre class=\"code\">\n      <span class=\"blue\">member</span> x.AllowElement(element) =\n        <span class=\"blue\">match</span> element <span class=\"blue\">with</span>\n        | :? Wall <span class=\"blue\">as</span> element <span class=\"blue\">-&gt;</span> <span class=\"blue\">true</span>\n        | _ <span class=\"blue\">-&gt;</span> <span class=\"blue\">false</span>\n</pre>\n<p>However, on further consideration, it is clearer and more succinct to use the F# ':?' operator, which is an equivalent of 'is' in C#, like this:\n\n<pre class=\"code\">\n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n</pre>\n<h5>Implementing an Exception Handler</h5>\n<p>I initially removed the 'try-catch' exception handler around the call to PickObject to handle a user cancelling the pick operation.\nOn consideration, I found that it translates to 'try-with' in F#.\nThe piping symbol '|' means pretty much 'data received from the last operation':\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> reference = \n    <span class=\"blue\">try</span>\n      sel.PickObject(\n        ObjectType.Element, \n        <span class=\"blue\">new</span> WallSelectionFilter(), \n        <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n    <span class=\"blue\">with</span>\n      | :? Autodesk.Revit.Exceptions.\n        OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n</pre>\n<p>Exiting the mainline execution requires an if-else statement as well: if reference is null, return Result.Canceled. \nThe best solution is probably more \n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>, \n\nthough.\n\n\n<a name=\"3\"></a>\n<h4>Final Implementation</h4>\n<p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Pattern Matching Versus :?",
    "local_header_href": "#pattern-matching-versus",
    "chunk_text": "<h5>Pattern Matching Versus :?</h5><p>At one point, I made a little bit of use of F# pattern matching to implement the WallSelectionFilter AllowElement method like this:\n\n<pre class=\"code\">\n      <span class=\"blue\">member</span> x.AllowElement(element) =\n        <span class=\"blue\">match</span> element <span class=\"blue\">with</span>\n        | :? Wall <span class=\"blue\">as</span> element <span class=\"blue\">-&gt;</span> <span class=\"blue\">true</span>\n        | _ <span class=\"blue\">-&gt;</span> <span class=\"blue\">false</span>\n</pre>\n<p>However, on further consideration, it is clearer and more succinct to use the F# ':?' operator, which is an equivalent of 'is' in C#, like this:\n\n<pre class=\"code\">\n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n</pre>\n<h5>Implementing an Exception Handler</h5>\n<p>I initially removed the 'try-catch' exception handler around the call to PickObject to handle a user cancelling the pick operation.\nOn consideration, I found that it translates to 'try-with' in F#.\nThe piping symbol '|' means pretty much 'data received from the last operation':\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> reference = \n    <span class=\"blue\">try</span>\n      sel.PickObject(\n        ObjectType.Element, \n        <span class=\"blue\">new</span> WallSelectionFilter(), \n        <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n    <span class=\"blue\">with</span>\n      | :? Autodesk.Revit.Exceptions.\n        OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n</pre>\n<p>Exiting the mainline execution requires an if-else statement as well: if reference is null, return Result.Canceled. \nThe best solution is probably more \n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>, \n\nthough.\n\n\n<a name=\"3\"></a>\n<h4>Final Implementation</h4>\n<p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Implementing an Exception Handler",
    "local_header_href": "#implementing-an-exception-handler",
    "chunk_text": "<h5>Implementing an Exception Handler</h5><p>I initially removed the 'try-catch' exception handler around the call to PickObject to handle a user cancelling the pick operation.\nOn consideration, I found that it translates to 'try-with' in F#.\nThe piping symbol '|' means pretty much 'data received from the last operation':\n\n<pre class=\"code\">\n  <span class=\"blue\">let</span> reference = \n    <span class=\"blue\">try</span>\n      sel.PickObject(\n        ObjectType.Element, \n        <span class=\"blue\">new</span> WallSelectionFilter(), \n        <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n    <span class=\"blue\">with</span>\n      | :? Autodesk.Revit.Exceptions.\n        OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n</pre>\n<p>Exiting the mainline execution requires an if-else statement as well: if reference is null, return Result.Canceled. \nThe best solution is probably more \n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>, \n\nthough.\n\n\n<a name=\"3\"></a>\n<h4>Final Implementation</h4>\n<p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Final Implementation",
    "local_header_href": "#final-implementation",
    "chunk_text": "<h4>Final Implementation</h4><p>Here is the final complete F# implementation of this external command:\n\n<pre class=\"code\">\n<span class=\"blue\">namespace</span> FSharpPanelBuilder\n \n<span class=\"blue\">open</span> System\n<span class=\"blue\">open</span> System.Collections.Generic\n \n<span class=\"blue\">open</span> Autodesk.Revit\n<span class=\"blue\">open</span> Autodesk.Revit.UI\n<span class=\"blue\">open</span> Autodesk.Revit.Attributes\n<span class=\"blue\">open</span> Autodesk.Revit.DB\n<span class=\"blue\">open</span> Autodesk.Revit.UI.Selection\n \n<span class=\"blue\">type</span> WallSelectionFilter() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> ISelectionFilter <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> x.AllowElement(element) = element :? Wall\n      <span class=\"blue\">member</span> x.AllowReference(reference, xyz) = <span class=\"blue\">false</span>\n  <span class=\"blue\">end</span>\n \n[&lt;Transaction(TransactionMode.Manual)&gt;]\n<span class=\"blue\">type</span> Command() =\n  <span class=\"blue\">class</span>\n    <span class=\"blue\">interface</span> IExternalCommand <span class=\"blue\">with</span>\n      <span class=\"blue\">member</span> this.Execute(commandData, \n                          message : string byref, \n                          elements ) =\n \n        <span class=\"blue\">try</span>\n          <span class=\"blue\">let</span> uiApp = commandData.Application\n          <span class=\"blue\">let</span> app  = uiApp.Application\n          <span class=\"blue\">let</span> uiDoc = uiApp.ActiveUIDocument\n          <span class=\"blue\">let</span> doc  = uiDoc.Document\n          <span class=\"blue\">let</span> sel = uiDoc.Selection\n \n          <span class=\"blue\">let</span> reference = \n            <span class=\"blue\">try</span>\n              sel.PickObject(\n                ObjectType.Element, \n                <span class=\"blue\">new</span> WallSelectionFilter(), \n                <span class=\"maroon\">\"Select a wall to split into panels\"</span>)\n            <span class=\"blue\">with</span>\n              | :? Autodesk.Revit.Exceptions.\n                OperationCanceledException <span class=\"blue\">-&gt;</span> <span class=\"blue\">null</span>\n \n          <span class=\"blue\">if</span> reference = <span class=\"blue\">null</span> <span class=\"blue\">then</span>\n            TaskDialog.Show(\n              <span class=\"maroon\">\"F# Panel Builder\"</span>, \n              <span class=\"maroon\">\"Operation was canceled\"</span>) |&gt; ignore\n            Autodesk.Revit.UI.Result.Cancelled\n          <span class=\"blue\">else</span>\n            <span class=\"blue\">let</span> wall = \n              doc.GetElement(reference.ElementId) :?&gt; Wall\n \n            <span class=\"blue\">let</span> locationCurve = \n              wall.Location :?&gt; LocationCurve\n \n            <span class=\"blue\">let</span> line = locationCurve.Curve :?&gt; Line\n \n            <span class=\"blue\">use</span> transaction = <span class=\"blue\">new</span> Transaction(doc)\n \n            <span class=\"blue\">let</span> status = transaction.Start(<span class=\"maroon\">\"Building panels\"</span>)\n \n            <span class=\"blue\">let</span> wallList = <span class=\"blue\">new</span> List&lt;ElementId&gt;(1)\n            wallList.Add(reference.ElementId)\n \n            PartUtils.CreateParts(doc, wallList)\n            doc.Regenerate()\n \n            <span class=\"blue\">let</span> parts = \n              PartUtils.GetAssociatedParts(\n                doc, wall.Id, <span class=\"blue\">false</span>, <span class=\"blue\">false</span>)\n \n            <span class=\"blue\">let</span> divisions = 15\n            <span class=\"blue\">let</span> origin = line.Origin\n \n            <span class=\"blue\">let</span> delta = \n              line.Direction.Multiply(\n                line.Length / (float)divisions)\n \n            <span class=\"blue\">let</span> shiftDelta = \n              Transform.get_Translation(delta)\n \n            <span class=\"blue\">let</span> rotation = \n              Transform.get_Rotation(\n                origin, XYZ.BasisZ, 0.5 * Math.PI)\n \n            <span class=\"blue\">let</span> wallWidthVector = \n              rotation.OfVector(\n                line.Direction.Multiply(2. * wall.Width))\n \n            <span class=\"blue\">let</span> <span class=\"blue\">mutable</span> intersectionLine = \n              app.Create.NewLineBound(\n                origin + wallWidthVector, \n                origin - wallWidthVector)\n \n            <span class=\"blue\">let</span> curveArray = <span class=\"blue\">new</span> List&lt;Curve&gt;()\n \n            <span class=\"blue\">for</span> i = 1 <span class=\"blue\">to</span> divisions <span class=\"blue\">do</span>\n              intersectionLine &lt;- \n                intersectionLine.get_Transformed(\n                  shiftDelta) :?&gt; Line\n \n              curveArray.Add(intersectionLine)\n \n            <span class=\"blue\">let</span> divisionSketchPlane = \n              doc.Create.NewSketchPlane(\n                <span class=\"blue\">new</span> Plane(XYZ.BasisZ, line.Origin))\n \n            <span class=\"blue\">let</span> intersectionElementsIds = \n              <span class=\"blue\">new</span> List&lt;ElementId&gt;()\n \n            <span class=\"blue\">let</span> partMaker = \n              PartUtils.DivideParts(\n                doc, parts, intersectionElementsIds, \n                curveArray, divisionSketchPlane.Id)\n \n            doc.ActiveView.PartsVisibility &lt;- \n              PartsVisibility.ShowPartsOnly\n \n            transaction.Commit() |&gt; ignore\n \n            Result.Succeeded\n \n        <span class=\"blue\">with</span> ex <span class=\"blue\">-&gt;</span>\n          TaskDialog.Show(\n            <span class=\"maroon\">\"F# Panel Builder\"</span>, \n            ex.Message) |&gt; ignore\n \n          Result.Failed\n \n  <span class=\"blue\">end</span>\n</pre>\n<p>The code is a straight translation from C# into F#, almost without making any use of F# specific concepts.\n\n<p>Later on, it would be nice to rewrite it to be a bit more\n\n<a href=\"http://en.wikipedia.org/wiki/Functional_programming\">functional</a>.\n\n<p>I really like how expressive and concise F# is, but switching between F# and C# causes me horrible headaches. :-)\n\n\n<a name=\"4\"></a>\n<h4>Git and GitHub Source Code Management</h4>\n<p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Git and GitHub Source Code Management",
    "local_header_href": "#git-and-github-source-code-management",
    "chunk_text": "<h4>Git and GitHub Source Code Management</h4><p>I placed the entire project on \n\n<a href=\"https://github.com\">\nGitHub</a>:\n\n<ul>\n<li><a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nhttps://github.com/pzurek/FSharpPanelBuilder</a>.\n</li></ul>\n<p>GitHub a source code collaboration platform based on the version control system git, a fast, efficient, distributed system for collaborative software development.\nIt enables you to easily fork, send pull requests and manage all your public and private git repositories.\n\n<p>I love it. \nHere at CADPRO I don't get too much chance to use it collaboratively, since I am usually the only person working on a project. \n\n<p>When playing with open source projects, that's another story and git is a brilliant tool for it. \nSome people claim that is it hard and too complicated, but for me that was the first distributed source control system I used and I didn't find it too hard to grasp. \n\n<p>The thing that makes Git amazing is GitHub. \nThey just put a nice desktop and web interface on it and make it nice and easy to use. \n\n<p>Besides looking at the \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder\">\nmain project page</a>, \n\nyou can \n\n<a href=\"https://github.com/pzurek/FSharpPanelBuilder/zipball/master\">\ndownload the whole project as a zip file</a>.\n\n<p>GitHub also provides a little tool that help with publishing source code on the Internet.\nGist.github.com allows you to create snippets of code and then embed them in other websites. \n\n<p>As an example, I pasted the \n\n<a href=\"https://gist.github.com/3702963\">\ncommand.fs file from the F# sample</a>.\n\n<p>Many thanks to Piotr for all this information, research and comparison!\n\n\n<a name=\"5\"></a>\n<h4>Retrieving Line Styles</h4>\n<p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p></p></p></p></p></p></p></p></p></p>"
  },
  {
    "original_filename": "0826_divide_parts_fsharp",
    "header_text": "Retrieving Line Styles",
    "local_header_href": "#retrieving-line-styles",
    "chunk_text": "<h4>Retrieving Line Styles</h4><p>Mikako Harada published sample code showing how to \n\n<a href=\"http://adndevblog.typepad.com/aec/2012/09/retrieving-a-list-of-line-styles.html\">\nretrieve all line styles</a> through\n\nthe CurveElement GetLineStyleIds property.\n\n<p>If you don't have a curve element handy to invoke the property on, you can simply create a temporary one, for instance a detail line in the currently active view.\nCreated in a separate transaction which is rolled back afterwards, it enables access to the line styles with no effect on the database.\n</p></p>"
  }
]