[
  {
    "original_filename": "1021_multi_reference_annot",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "1021_multi_reference_annot",
    "header_text": "MultiReferenceAnnotation Example",
    "local_header_href": "#multireferenceannotation-example",
    "chunk_text": "<h3>MultiReferenceAnnotation Example</h3><p>Miguel Angel Alanis asked on the Autodesk Revit API discussion forum for an\n\n<a href=\"http://forums.autodesk.com/t5/Autodesk-Revit-API/An-Example-for-using-MultiReferenceAnnotation/td-p/4412817\">\nexample of making use of the new MultiReferenceAnnotation</a>.\n\n<p>I put together this blog post to make sure the solution is easily found.</p>\n<p>First, a note on something more imminent:</p>\n<a name=\"2\"></a>\n<h4>Portathon Day 1</h4>\n<p>Today is the first day of the Portathon!</p>\n<ul>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/07/earn-100-submitting-an-autodesk-exchange-app.html\">Earn $100 Submitting an Autodesk Exchange App</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/08/exchange-app-videos-and-devtv-youtube-channel.html\">Exchange App Videos</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/08/adn-training-material-on-github-and-portathon-reminder.html#2\">Portathon reminder and video</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/09/cloud-and-appstore-usage-grows-portathon-reminder.html\">Cloud and AppStore usage growth</a></li>\n</ul>\n<p>Wish us all luck and much success, please.</p>\n<p>Looking forward to seeing you there!</p>\n<a name=\"3\"></a>\n<h4>MultiReferenceAnnotation Creation Sample Code</h4>\n<p>Back to the main topic:</p>\n<p><strong>Question:</strong> Is it possible to get an example to create a multi-rebar annotation?\n\n<p>I searched the Revit SDK and found I have to use the MultiReferenceAnnotation class, but I can't build an example with the current information.</p>\n<p>I use the Autodesk.Revit.Creation.Document.Create.NewTag method to create a normal rebar tag, and I notice the independent tag has a property named MultiReferenceAnnotationId.</p>\n<p><strong>Answer:</strong> Please note the MultiReferenceAnnotation.Create method taking a MultiReferenceAnnotationOptions argument.</p>\n<p>The minimum options are probably the type and ElementsToDimension.</p>\n<p>Here is an excerpt from an internal test suite.\nIt refers to a couple of hardcoded element ids.\nUse the documentation to figure out their use:</p>\n<pre class=\"code\">\n  <span class=\"blue\">var</span> view = GetElement&lt;<span class=\"teal\">View</span>&gt;( 124186 );\n \n  <span class=\"blue\">var</span> rebarList = GetElements&lt;<span class=\"teal\">Element</span>&gt;(\n    doc, <span class=\"blue\">new</span>[] { 280427 } ).ToList();\n \n  Assert.IsTrue( rebarList.Count &gt; 0,\n    <span class=\"maroon\">\"There are no rebars in the document!\"</span> );\n \n  <span class=\"teal\">IList</span>&lt;<span class=\"teal\">ElementId</span>&gt; elementIds\n    = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">ElementId</span>&gt;();\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> rebar <span class=\"blue\">in</span> rebarList )\n  {\n    elementIds.Add( rebar.Id );\n  }\n \n  <span class=\"teal\">MultiReferenceAnnotationType</span> type\n    = GetElement&lt;<span class=\"teal\">MultiReferenceAnnotationType</span>&gt;(\n      doc, 260544 );\n \n  Assert.IsNotNull( type,\n    <span class=\"maroon\">\"the MultiReferenceAnnotationType does not exist!\"</span> );\n \n  <span class=\"teal\">MultiReferenceAnnotationOptions</span> options\n    = <span class=\"blue\">new</span> <span class=\"teal\">MultiReferenceAnnotationOptions</span>( type );\n \n  options.TagHeadPosition = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 100, 0 );\n  options.DimensionLineOrigin = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 5, 5, 1 );\n  options.DimensionLineDirection = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 1, 0 );\n  options.DimensionPlaneNormal = view.ViewDirection;\n  options.SetElementsToDimension( elementIds );\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tran = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tran.Start( <span class=\"maroon\">\"Create_Rebar_Vertical\"</span> );\n \n    <span class=\"blue\">var</span> mra = <span class=\"teal\">MultiReferenceAnnotation</span>.Create(\n      doc, view.Id, options );\n \n    <span class=\"blue\">var</span> dimension = GetElement&lt;<span class=\"teal\">Dimension</span>&gt;(\n      doc, mra.DimensionId );\n \n    tran.Commit();\n  }\n</pre>\n<p>Many thanks to Miguel Angel for raising this issue.</p>\n<a name=\"4\"></a>\n<h4>Case Newsletter</h4>\n<p>By the way, I really enjoy the\n\n<a href=\"http://us1.campaign-archive1.com/?u=18e743860774ed83e735552b4&amp;id=e3e9f3aaeb&amp;e=c5bd394c2a\">\ncase newsletter</a> and\n\nthe fun items it points to, for instance this\n\n<a href=\"http://woodgears.ca/eyeball/index.html\">mental eyeballing exercise</a> and\n\n<a href=\"http://www.youtube.com/embed/p7l3_THa-Yk?rel=0\">lawn chair magic video</a>.</p>\n<p>Besides the fun stuff, it presents a lot of useful architectural programming news as well.</p>\n</p></p>"
  },
  {
    "original_filename": "1021_multi_reference_annot",
    "header_text": "Portathon Day 1",
    "local_header_href": "#portathon-day-1",
    "chunk_text": "<h4>Portathon Day 1</h4><p>Today is the first day of the Portathon!</p><ul>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/07/earn-100-submitting-an-autodesk-exchange-app.html\">Earn $100 Submitting an Autodesk Exchange App</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/08/exchange-app-videos-and-devtv-youtube-channel.html\">Exchange App Videos</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/08/adn-training-material-on-github-and-portathon-reminder.html#2\">Portathon reminder and video</a></li>\n<li><a href=\"http://thebuildingcoder.typepad.com/blog/2013/09/cloud-and-appstore-usage-grows-portathon-reminder.html\">Cloud and AppStore usage growth</a></li>\n</ul><p>Wish us all luck and much success, please.</p><p>Looking forward to seeing you there!</p><a name=\"3\"></a>"
  },
  {
    "original_filename": "1021_multi_reference_annot",
    "header_text": "MultiReferenceAnnotation Creation Sample Code",
    "local_header_href": "#multireferenceannotation-creation-sample-code",
    "chunk_text": "<h4>MultiReferenceAnnotation Creation Sample Code</h4><p>Back to the main topic:</p><p><strong>Question:</strong> Is it possible to get an example to create a multi-rebar annotation?\n\n<p>I searched the Revit SDK and found I have to use the MultiReferenceAnnotation class, but I can't build an example with the current information.</p>\n<p>I use the Autodesk.Revit.Creation.Document.Create.NewTag method to create a normal rebar tag, and I notice the independent tag has a property named MultiReferenceAnnotationId.</p>\n<p><strong>Answer:</strong> Please note the MultiReferenceAnnotation.Create method taking a MultiReferenceAnnotationOptions argument.</p>\n<p>The minimum options are probably the type and ElementsToDimension.</p>\n<p>Here is an excerpt from an internal test suite.\nIt refers to a couple of hardcoded element ids.\nUse the documentation to figure out their use:</p>\n<pre class=\"code\">\n  <span class=\"blue\">var</span> view = GetElement&lt;<span class=\"teal\">View</span>&gt;( 124186 );\n \n  <span class=\"blue\">var</span> rebarList = GetElements&lt;<span class=\"teal\">Element</span>&gt;(\n    doc, <span class=\"blue\">new</span>[] { 280427 } ).ToList();\n \n  Assert.IsTrue( rebarList.Count &gt; 0,\n    <span class=\"maroon\">\"There are no rebars in the document!\"</span> );\n \n  <span class=\"teal\">IList</span>&lt;<span class=\"teal\">ElementId</span>&gt; elementIds\n    = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">ElementId</span>&gt;();\n \n  <span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> rebar <span class=\"blue\">in</span> rebarList )\n  {\n    elementIds.Add( rebar.Id );\n  }\n \n  <span class=\"teal\">MultiReferenceAnnotationType</span> type\n    = GetElement&lt;<span class=\"teal\">MultiReferenceAnnotationType</span>&gt;(\n      doc, 260544 );\n \n  Assert.IsNotNull( type,\n    <span class=\"maroon\">\"the MultiReferenceAnnotationType does not exist!\"</span> );\n \n  <span class=\"teal\">MultiReferenceAnnotationOptions</span> options\n    = <span class=\"blue\">new</span> <span class=\"teal\">MultiReferenceAnnotationOptions</span>( type );\n \n  options.TagHeadPosition = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 100, 0 );\n  options.DimensionLineOrigin = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 5, 5, 1 );\n  options.DimensionLineDirection = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( 0, 1, 0 );\n  options.DimensionPlaneNormal = view.ViewDirection;\n  options.SetElementsToDimension( elementIds );\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tran = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tran.Start( <span class=\"maroon\">\"Create_Rebar_Vertical\"</span> );\n \n    <span class=\"blue\">var</span> mra = <span class=\"teal\">MultiReferenceAnnotation</span>.Create(\n      doc, view.Id, options );\n \n    <span class=\"blue\">var</span> dimension = GetElement&lt;<span class=\"teal\">Dimension</span>&gt;(\n      doc, mra.DimensionId );\n \n    tran.Commit();\n  }\n</pre>\n<p>Many thanks to Miguel Angel for raising this issue.</p>\n<a name=\"4\"></a>\n<h4>Case Newsletter</h4>\n<p>By the way, I really enjoy the\n\n<a href=\"http://us1.campaign-archive1.com/?u=18e743860774ed83e735552b4&amp;id=e3e9f3aaeb&amp;e=c5bd394c2a\">\ncase newsletter</a> and\n\nthe fun items it points to, for instance this\n\n<a href=\"http://woodgears.ca/eyeball/index.html\">mental eyeballing exercise</a> and\n\n<a href=\"http://www.youtube.com/embed/p7l3_THa-Yk?rel=0\">lawn chair magic video</a>.</p>\n<p>Besides the fun stuff, it presents a lot of useful architectural programming news as well.</p>\n</p>"
  },
  {
    "original_filename": "1021_multi_reference_annot",
    "header_text": "Case Newsletter",
    "local_header_href": "#case-newsletter",
    "chunk_text": "<h4>Case Newsletter</h4><p>By the way, I really enjoy the\n\n<a href=\"http://us1.campaign-archive1.com/?u=18e743860774ed83e735552b4&amp;id=e3e9f3aaeb&amp;e=c5bd394c2a\">\ncase newsletter</a> and\n\nthe fun items it points to, for instance this\n\n<a href=\"http://woodgears.ca/eyeball/index.html\">mental eyeballing exercise</a> and\n\n<a href=\"http://www.youtube.com/embed/p7l3_THa-Yk?rel=0\">lawn chair magic video</a>.</p><p>Besides the fun stuff, it presents a lot of useful architectural programming news as well.</p>"
  }
]