[
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<script src=\"http://thebuildingcoder.typepad.com/google-code-prettify/run_prettify.js\"></script>\n</head>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Planes, Projections and Picking Points",
    "local_header_href": "#planes-projections-and-picking-points",
    "chunk_text": "<h3>Planes, Projections and Picking Points</h3><p>Here is a query and some sample code from a Revit API newbie that led to several different interesting topics, in particular some ruminations on planes, projections, picking points and common extension methods that I hope will be of use to you too – yet another Monday monster post:</p><p><strong>Question:</strong> The macro below sets a work plane based on the active view and lets the user pick two points to get the area of a rectangle. This works for east and west elevation views, but returns an area of 0 in north and south elevation views. Any idea why this happens? If I set the work plane manually in north and south elevation views and run a version of the macro without the work plane transaction, it works fine.</p><p>Also, this macro measures along XYZ axes and won't give the correct area for, say, a wall bearing 45 degrees NE. Any ideas on how to make it more universal?</p><pre class=\"code\">\n  <span class=\"blue\">public</span> <span class=\"blue\">void</span> SetWorkPlaneAndPickPointsForArea(\n    <span class=\"teal\">UIDocument</span> uidoc )\n  {\n    <span class=\"teal\">Document</span> doc = uidoc.Document\n \n    <span class=\"blue\">double</span> differenceX;\n    <span class=\"blue\">double</span> differenceY;\n    <span class=\"blue\">double</span> differenceZ;\n    <span class=\"blue\">double</span> area;\n \n    <span class=\"teal\">Transaction</span> t = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc,\n      <span class=\"maroon\">\"Set Work Plane\"</span> );\n \n    t.Start();\n \n    <span class=\"teal\">Plane</span> plane = <span class=\"blue\">new</span> <span class=\"teal\">Plane</span>(\n      doc.ActiveView.ViewDirection,\n      doc.ActiveView.Origin );\n \n    <span class=\"teal\">SketchPlane</span> sp = doc.Create.NewSketchPlane(\n      plane );\n \n    doc.ActiveView.SketchPlane = sp;\n    doc.ActiveView.ShowActiveWorkPlane();\n \n    t.Commit();\n \n    <span class=\"teal\">XYZ</span> pt1 = uidoc.Selection.PickPoint();\n    <span class=\"teal\">XYZ</span> pt2 = uidoc.Selection.PickPoint();\n \n    <span class=\"blue\">double</span> pt1x = pt1.X;\n    <span class=\"blue\">double</span> pt1y = pt1.Y;\n    <span class=\"blue\">double</span> pt1z = pt1.Z;\n \n    <span class=\"blue\">double</span> pt2x = pt2.X;\n    <span class=\"blue\">double</span> pt2y = pt2.Y;\n    <span class=\"blue\">double</span> pt2z = pt2.Z;\n \n    <span class=\"blue\">bool</span> b;\n    <span class=\"blue\">int</span> caseSwitch = 0;\n \n    <span class=\"blue\">if</span>( b = ( pt1z == pt2z ) )\n    { caseSwitch = 1; }\n \n    <span class=\"blue\">if</span>( b = ( pt1y == pt2y ) )\n    { caseSwitch = 2; }\n \n    <span class=\"blue\">if</span>( b = ( pt1x == pt2x ) )\n    { caseSwitch = 3; }\n \n    <span class=\"blue\">switch</span>( caseSwitch )\n    {\n      <span class=\"blue\">case</span> 1:\n        differenceX = pt2x - pt1x;\n        differenceY = pt1y - pt2y;\n        area = differenceX * differenceY;\n        <span class=\"blue\">break</span>;\n \n      <span class=\"blue\">case</span> 2:\n        differenceX = pt2x - pt1x;\n        differenceZ = pt1z - pt2z;\n        area = differenceX * differenceZ;\n        <span class=\"blue\">break</span>;\n \n      <span class=\"blue\">default</span>:\n        differenceY = pt2y - pt1y;\n        differenceZ = pt1z - pt2z;\n        area = differenceY * differenceZ;\n        <span class=\"blue\">break</span>;\n    }\n \n    area = <span class=\"teal\">Math</span>.Round( area, 2 );\n \n    <span class=\"blue\">if</span>( area &lt; 0 )\n    { area = area * ( -1 ); }\n \n    <span class=\"teal\">TaskDialog</span>.Show( <span class=\"maroon\">\"Area\"</span>, area.ToString() );\n  }\n</pre><p><strong>Answer:</strong> Your query and sample code lead to a whole bunch of topics and suggestions, many of which are of general interest, I hope:</p><ul>\n<li><a href=\"#02\">Use the debugger</a></li>\n<li><a href=\"#03\">Encapsulate transaction in 'using' block</a></li>\n<li><a href=\"#04\">Implement read-only commands if possible</a></li>\n<li><a href=\"#05\">Never use direct comparison for floating point numbers</a></li>\n<li><a href=\"#06\">Use XYZ points instead of separate X, Y, Z double variables</a></li>\n<li><a href=\"#07\">The pick point methods throw an exception an cancel</a></li>\n<li><a href=\"#08\">Serious Suggestion for Improvement</a></li>\n<li><a href=\"#09\">Implementing a .NET extension method</a></li>\n<li><a href=\"#10\">Mathematical and Revit plane definition</a></li>\n<li><a href=\"#11\">Signed distance from a 3D point to a plane</a></li>\n<li><a href=\"#12\">Projecting a 3D point onto a plane</a></li>\n<li><a href=\"#13\">Projecting a 3D point into a plane</a></li>\n<li><a href=\"#14\">PickPointsForArea</a></li>\n<li><a href=\"#15\">The Building Coder samples updated</a></li>\n</ul><a name=\"02\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Use the Debugger",
    "local_header_href": "#use-the-debugger",
    "chunk_text": "<h4>Use the Debugger</h4><p>I would suggest you have a look at the points you are picking and their coordinates in the debugger.</p><p>That will probably show you the problem immediately.</p><a name=\"03\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Encapsulate Transaction in 'using' Block",
    "local_header_href": "#encapsulate-transaction-in-using-block",
    "chunk_text": "<h4>Encapsulate Transaction in 'using' Block</h4><p>The simplest and safest way to handle transactions in the Revit API is to encapsulate each transaction and transaction group in a 'using' statement, which will\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/04/using-using-automagically-disposes-and-rolls-back.html\">\nautomagically handle disposal and roll-back</a> for\n\nyou.\n\n\n<a name=\"04\"></a>\n<h4>Implement Read-only Commands if Possible</h4>\n<p>There is actually no need to construct a plane from the view direction and origin, and then create a sketch plane from that, because the view already has a built-in sketch plane that we can use, and that in turn has a plane defining it.</p>\n<p>This again obviates the need for the transaction, so we can make use of this method in a read-only command as well.</p>\n<a name=\"05\"></a>\n<h4>Never use Direct Comparison for Floating Point Numbers</h4>\n<p>You use the equality operator == to compare the floating point coordinates of the picked points.</p>\n<p>I would recommend never doing that, because they could always be off by an infinitesimal amount, in which case the comparison would return false, even if they are almost equal, within the possible precision. You need to use fuzzy comparison for floating point numbers. Look at this discussion on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/connector-orientation.html#2\">\nreal number equality testing</a>.</p>\n<p>That may well be the reason for the failures you mention for certain planes.</p>\n<a name=\"06\"></a>\n<h4>Use XYZ Points Instead of Separate X, Y, Z Double Variables</h4>\n<p>Your code could be shortened and made easier to read by using the Revit XYZ class or some other similar utility class instead of managing 3D point X, Y and Z coordinates in separate double variables.</p>\n<p>For instance, to calculate the vector v between two given points p1 and p2, you can simply use:</p>\n<pre class=\"code\">\n  v = p2 - p1;\n</pre>\n<p>Calculating the difference between each of the three coordinates separately and storing each of these in its own double variable would make the code several times longer and much harder to understand.</p>\n<a name=\"07\"></a>\n<h4>The Pick Point Methods Throw an Exception on Cancel</h4>\n<p>The Revit API methods prompting the user to pick a point throw an exception if the user cancels the operation.</p>\n<p>Unfortunately and admittedly, this totally violates the rule that\n\n<a href=\"http://www.jacopretorius.net/2009/10/exceptions-should-be-exceptional.html\">\nexceptions are and should remain exceptional</a>.</p>\n<p>Still, I always add a try-catch block around any pick point and other Revit API selection calls, catching the Autodesk.Revit.Exceptions.OperationCanceledException, terminating the command and returning gracefully with a result code saying Result.Cancelled or Result.Failed, as the case may be.</p>\n<a name=\"08\"></a>\n<h4>Serious Suggestion for Improvement</h4>\n<p>The main issue with the current implementation, just as you point out, is the hard-coded dependency on planes exactly aligned with the cardinal axes.\nThe current approach will fail if the plane is angled in any way.</p>\n<p>A better solution might be to project the two picked points onto the plane (since they are picked in the view plane, they should be located on it anyway) and determine their UV coordinates in it.</p>\n<p>That gives you 2D points to play with, and the area calculation is trivial.</p>\n<p>You would need something similar to the Revit API Face.Project method, which projects an XYZ point onto a face and returns an IntersectionResult object, from which the 2D UV parameters of the projected point can be determined.</p>\n<p>Unfortunately, the Revit API does not provide a similar method for the Plane class, so we have to define it ourselves.</p>\n<p>Alternatively, but rather a bit of an overkill, we might be able to make use the AutoCAD ARX\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2013/10/using-the-built-in-revit-acge-functionality.html\">\nAcGe functionality included with Revit</a>.</p>\n<p>It provides the Geometry.AcGe.Helper.orthoProjectIntoPlane method that does exactly what we need in this case.</p>\n<p>Since I love geometrical calculations and all too seldom have a chance to get a nice bite of one, I added some code to The Building Coder samples to demonstrate how to implement this for you.</p>\n<a name=\"09\"></a>\n<h4>Implementing a .NET Extension Method</h4>\n<p>First, I implemented three helper\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/02/getpolygon-extension-methods.html\">\n.NET extension methods</a> for\n\nthe Revit API Plane class:</p>\n<ul>\n<li>SignedDistanceTo – return the signed distance from a plane to a given point.</li>\n<li>ProjectOnto – project a given 3D XYZ point onto the plane.</li>\n<li>ProjectInto – project a given 3D XYZ point into the plane, returning the UV coordinates of the result in the local 2D plane coordinate system.</li>\n</ul>\n<p>To quote the MSDN documentation on <a href=\"http://msdn.microsoft.com/en-us/library/bb383977.aspx\">extension methods</a> in the C# Programming Guide: Extension methods enable you to \"add\" methods to existing types without creating a new derived type, recompiling, or otherwise modifying the original type. Extension methods are a special kind of static method, but they are called as if they were instance methods on the extended type. For client code written in C# and Visual Basic, there is no apparent difference between calling an extension method and the methods that are actually defined in a type.</p>\n<p>To implement an extension method, you create a static class with a static method taking a 'this' pointer to an instance of the class you are extending.\nIn my case, I added a class JtPlaneExtensionMethods to The Building Coder samples Util.cs module.</p>\n<p>Before getting into the details of implementing these methods, let's mention some basics about planes, their coordinate systems and projection onto them.</p>\n<a name=\"10\"></a>\n<h4>Mathematical and Revit plane definition</h4>\n<p>A\n\n<a href=\"http://en.wikipedia.org/wiki/Plane_(geometry)\">\nplane</a> can\n\nbe defined by just four real numbers: three specify its normal vector, and a fourth the signed distance from the world coordinate system origin.</p>\n<p>Revit planes are overspecified, in a way, since they define an origin plus X and Y vectors specifying the directions of the U and V coordinates of the 2D points in the plane, respectively.</p>\n<p>A Revit plane therefore has a well-defined 2D coordinate system embedded in it.</p>\n<a name=\"11\"></a>\n<h4>Signed Distance from a 3D Point to a Plane</h4>\n<p>The calculation of the\n\n<a href=\"http://en.wikipedia.org/wiki/Plane_(geometry)#Distance_from_a_point_to_a_plane\">\ndistance from a point to a plane</a> is\n\nstraightforward using the dot product.</p>\n<p>What is the\n\n<a href=\"http://en.wikipedia.org/wiki/Dot_product\">\ndot product</a>?</p>\n<p>Geometrically, you can simply see it as the length of the projection of one vector onto another:</p>\n<center>\n<img alt=\"Dot product\" src=\"img/220px-dot_product.png\" width=\"220\"/>\n</center>\n<p>Calculating the signed distance between a 3D point and a plane in space is easy using this:  determine the vector between the given point and any arbitrary point on the plane, e.g. its origin.\nThe dot product between that vector and the plane normal is the signed distance.\nThis assumes that the plane normal vector has unit length.\nThe result can be either zero, negative or positive, depending on whether the given point lies on the plane or on one or the other side of it.</p>\n<p>Here is my Revit API implementation of this; as said, it is a static method on the static JtPlaneExtensionMethods class:</p>\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return signed distance from plane to a given point.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"blue\">double</span> SignedDistanceTo(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"teal\">Debug</span>.Assert(\n      <span class=\"teal\">Util</span>.IsEqual( plane.Normal.GetLength(), 1 ),\n      <span class=\"maroon\">\"expected normalised plane normal\"</span> );\n \n    <span class=\"teal\">XYZ</span> v = p - plane.Origin;\n \n    <span class=\"blue\">return</span> plane.Normal.DotProduct( v );\n  }\n</pre>\n<a name=\"12\"></a>\n<h4>Projecting a 3D Point Onto a Plane</h4>\n<p>ProjectOnto returns a 3D XYZ point representing the projection of a given point in space onto the surface of the plane.\nThe result can be easily determined by subtracting the plane normal multiplied by the signed distance from the point:</p>\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Project given 3D XYZ point onto plane.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">XYZ</span> ProjectOnto(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">double</span> d = plane.SignedDistanceTo( p );\n \n    //XYZ q = p + d * plane.Normal; // wrong according to Ruslan Hanza and Alexander Pekshev in their comments below\n\n    <span class=\"teal\">XYZ</span> q = p - d * plane.Normal;\n \n    <span class=\"teal\">Debug</span>.Assert(\n      <span class=\"teal\">Util</span>.IsZero( plane.SignedDistanceTo( q ) ),\n      <span class=\"maroon\">\"expected point on plane to have zero distance to plane\"</span> );\n \n    <span class=\"blue\">return</span> q;\n  }\n</pre>\n<a name=\"13\"></a>\n<h4>Projecting a 3D Point Into a Plane</h4>\n<p>ProjectInto is similar to ProjectOnto but adds an important twist.\nInstead of a 3D XYZ point, it returns a 2D UV one representing the projection of the given point in the local coordinate system on the surface of the plane.</p>\n<p>The 3D point calculated by ProjectOnto above is in global 3D world coordinates.\nThe 2D point is in plane coordinates.</p>\n<p>It can be determined by calculating the dot product of the vector between the plane origin and the projected point with the plane X and Y vectors, respectively.\nThese two vectors determine the direction of the U and V coordinates on the plane surface:</p>\n<pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Project given 3D XYZ point into plane, </span>\n  <span class=\"gray\">///</span><span class=\"green\"> returning the UV coordinates of the result </span>\n  <span class=\"gray\">///</span><span class=\"green\"> in the local 2D plane coordinate system.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">UV</span> ProjectInto(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"teal\">XYZ</span> q = plane.ProjectOnto( p );\n    <span class=\"teal\">XYZ</span> o = plane.Origin;\n    <span class=\"teal\">XYZ</span> d = q - o;\n    <span class=\"blue\">double</span> u = d.DotProduct( plane.XVec );\n    <span class=\"blue\">double</span> v = d.DotProduct( plane.YVec );\n    <span class=\"blue\">return</span> <span class=\"blue\">new</span> <span class=\"teal\">UV</span>( u, v );\n  }\n</pre>\n<a name=\"14\"></a>\n<h4>PickPointsForArea</h4>\n<p>Wit these helper extension methods in hand, I can reimplement your SetWorkPlaneAndPickPointsForArea method like this, renaming it to PickPointsForArea, since no workplane manipulations are required any longer to achieve the same effect:</p>\n<pre class=\"code\">\n  <span class=\"blue\">public</span> <span class=\"blue\">void</span> PickPointsForArea(\n    <span class=\"teal\">UIDocument</span> uidoc )\n  {\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n    <span class=\"teal\">View</span> view = doc.ActiveView;\n \n    <span class=\"teal\">XYZ</span> p1, p2;\n \n    <span class=\"blue\">try</span>\n    {\n      p1 = uidoc.Selection.PickPoint(\n        <span class=\"maroon\">\"Please pick first point for area\"</span> );\n \n      p2 = uidoc.Selection.PickPoint(\n        <span class=\"maroon\">\"Please pick second point for area\"</span> );\n    }\n    <span class=\"blue\">catch</span>( Autodesk.Revit.Exceptions.<span class=\"teal\">OperationCanceledException</span> )\n    {\n      <span class=\"blue\">return</span>;\n    }\n \n    <span class=\"teal\">Plane</span> plane = view.SketchPlane.GetPlane();\n \n    <span class=\"teal\">UV</span> q1 = plane.ProjectInto( p1 );\n    <span class=\"teal\">UV</span> q2 = plane.ProjectInto( p2 );\n    <span class=\"teal\">UV</span> d = q2 - q1;\n \n    <span class=\"blue\">double</span> area = d.U * d.V;\n \n    area = <span class=\"teal\">Math</span>.Round( area, 2 );\n \n    <span class=\"blue\">if</span>( area &lt; 0 )\n    {\n      area = area * ( -1 );\n    }\n \n    <span class=\"teal\">TaskDialog</span>.Show( <span class=\"maroon\">\"Area\"</span>, area.ToString() );\n  }\n</pre>\n<a name=\"15\"></a>\n<h4>The Building Coder Samples Updated</h4>\n<p>I incorporated all the code presented above in The Building Coder samples.</p>\n<p>You can download the full solution from\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">\nThe Building Coder samples</a> GitHub\n\nrepository.</p>\n<p>The version discussed above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.111.2\">2015.0.111.2</a>.</p>\n<p>Here are direct links to the\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/Util.cs\">Util</a> and\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdPickPoint3d.cs\">CmdPickPoint3d</a> modules,\n\nin case you prefer not to clone the whole thing.</p>\n</p>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Implement Read-only Commands if Possible",
    "local_header_href": "#implement-read-only-commands-if-possible",
    "chunk_text": "<h4>Implement Read-only Commands if Possible</h4><p>There is actually no need to construct a plane from the view direction and origin, and then create a sketch plane from that, because the view already has a built-in sketch plane that we can use, and that in turn has a plane defining it.</p><p>This again obviates the need for the transaction, so we can make use of this method in a read-only command as well.</p><a name=\"05\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Never use Direct Comparison for Floating Point Numbers",
    "local_header_href": "#never-use-direct-comparison-for-floating-point-numbers",
    "chunk_text": "<h4>Never use Direct Comparison for Floating Point Numbers</h4><p>You use the equality operator == to compare the floating point coordinates of the picked points.</p><p>I would recommend never doing that, because they could always be off by an infinitesimal amount, in which case the comparison would return false, even if they are almost equal, within the possible precision. You need to use fuzzy comparison for floating point numbers. Look at this discussion on\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2012/05/connector-orientation.html#2\">\nreal number equality testing</a>.</p><p>That may well be the reason for the failures you mention for certain planes.</p><a name=\"06\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Use XYZ Points Instead of Separate X, Y, Z Double Variables",
    "local_header_href": "#use-xyz-points-instead-of-separate-x-y-z-double-variables",
    "chunk_text": "<h4>Use XYZ Points Instead of Separate X, Y, Z Double Variables</h4><p>Your code could be shortened and made easier to read by using the Revit XYZ class or some other similar utility class instead of managing 3D point X, Y and Z coordinates in separate double variables.</p><p>For instance, to calculate the vector v between two given points p1 and p2, you can simply use:</p><pre class=\"code\">\n  v = p2 - p1;\n</pre><p>Calculating the difference between each of the three coordinates separately and storing each of these in its own double variable would make the code several times longer and much harder to understand.</p><a name=\"07\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "The Pick Point Methods Throw an Exception on Cancel",
    "local_header_href": "#the-pick-point-methods-throw-an-exception-on-cancel",
    "chunk_text": "<h4>The Pick Point Methods Throw an Exception on Cancel</h4><p>The Revit API methods prompting the user to pick a point throw an exception if the user cancels the operation.</p><p>Unfortunately and admittedly, this totally violates the rule that\n\n<a href=\"http://www.jacopretorius.net/2009/10/exceptions-should-be-exceptional.html\">\nexceptions are and should remain exceptional</a>.</p><p>Still, I always add a try-catch block around any pick point and other Revit API selection calls, catching the Autodesk.Revit.Exceptions.OperationCanceledException, terminating the command and returning gracefully with a result code saying Result.Cancelled or Result.Failed, as the case may be.</p><a name=\"08\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Serious Suggestion for Improvement",
    "local_header_href": "#serious-suggestion-for-improvement",
    "chunk_text": "<h4>Serious Suggestion for Improvement</h4><p>The main issue with the current implementation, just as you point out, is the hard-coded dependency on planes exactly aligned with the cardinal axes.\nThe current approach will fail if the plane is angled in any way.</p><p>A better solution might be to project the two picked points onto the plane (since they are picked in the view plane, they should be located on it anyway) and determine their UV coordinates in it.</p><p>That gives you 2D points to play with, and the area calculation is trivial.</p><p>You would need something similar to the Revit API Face.Project method, which projects an XYZ point onto a face and returns an IntersectionResult object, from which the 2D UV parameters of the projected point can be determined.</p><p>Unfortunately, the Revit API does not provide a similar method for the Plane class, so we have to define it ourselves.</p><p>Alternatively, but rather a bit of an overkill, we might be able to make use the AutoCAD ARX\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2013/10/using-the-built-in-revit-acge-functionality.html\">\nAcGe functionality included with Revit</a>.</p><p>It provides the Geometry.AcGe.Helper.orthoProjectIntoPlane method that does exactly what we need in this case.</p><p>Since I love geometrical calculations and all too seldom have a chance to get a nice bite of one, I added some code to The Building Coder samples to demonstrate how to implement this for you.</p><a name=\"09\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Implementing a .NET Extension Method",
    "local_header_href": "#implementing-a-net-extension-method",
    "chunk_text": "<h4>Implementing a .NET Extension Method</h4><p>First, I implemented three helper\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/02/getpolygon-extension-methods.html\">\n.NET extension methods</a> for\n\nthe Revit API Plane class:</p><ul>\n<li>SignedDistanceTo – return the signed distance from a plane to a given point.</li>\n<li>ProjectOnto – project a given 3D XYZ point onto the plane.</li>\n<li>ProjectInto – project a given 3D XYZ point into the plane, returning the UV coordinates of the result in the local 2D plane coordinate system.</li>\n</ul><p>To quote the MSDN documentation on <a href=\"http://msdn.microsoft.com/en-us/library/bb383977.aspx\">extension methods</a> in the C# Programming Guide: Extension methods enable you to \"add\" methods to existing types without creating a new derived type, recompiling, or otherwise modifying the original type. Extension methods are a special kind of static method, but they are called as if they were instance methods on the extended type. For client code written in C# and Visual Basic, there is no apparent difference between calling an extension method and the methods that are actually defined in a type.</p><p>To implement an extension method, you create a static class with a static method taking a 'this' pointer to an instance of the class you are extending.\nIn my case, I added a class JtPlaneExtensionMethods to The Building Coder samples Util.cs module.</p><p>Before getting into the details of implementing these methods, let's mention some basics about planes, their coordinate systems and projection onto them.</p><a name=\"10\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Mathematical and Revit plane definition",
    "local_header_href": "#mathematical-and-revit-plane-definition",
    "chunk_text": "<h4>Mathematical and Revit plane definition</h4><p>A\n\n<a href=\"http://en.wikipedia.org/wiki/Plane_(geometry)\">\nplane</a> can\n\nbe defined by just four real numbers: three specify its normal vector, and a fourth the signed distance from the world coordinate system origin.</p><p>Revit planes are overspecified, in a way, since they define an origin plus X and Y vectors specifying the directions of the U and V coordinates of the 2D points in the plane, respectively.</p><p>A Revit plane therefore has a well-defined 2D coordinate system embedded in it.</p><a name=\"11\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Signed Distance from a 3D Point to a Plane",
    "local_header_href": "#signed-distance-from-a-3d-point-to-a-plane",
    "chunk_text": "<h4>Signed Distance from a 3D Point to a Plane</h4><p>The calculation of the\n\n<a href=\"http://en.wikipedia.org/wiki/Plane_(geometry)#Distance_from_a_point_to_a_plane\">\ndistance from a point to a plane</a> is\n\nstraightforward using the dot product.</p><p>What is the\n\n<a href=\"http://en.wikipedia.org/wiki/Dot_product\">\ndot product</a>?</p><p>Geometrically, you can simply see it as the length of the projection of one vector onto another:</p><center>\n<img alt=\"Dot product\" src=\"img/220px-dot_product.png\" width=\"220\"/>\n</center><p>Calculating the signed distance between a 3D point and a plane in space is easy using this:  determine the vector between the given point and any arbitrary point on the plane, e.g. its origin.\nThe dot product between that vector and the plane normal is the signed distance.\nThis assumes that the plane normal vector has unit length.\nThe result can be either zero, negative or positive, depending on whether the given point lies on the plane or on one or the other side of it.</p><p>Here is my Revit API implementation of this; as said, it is a static method on the static JtPlaneExtensionMethods class:</p><pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return signed distance from plane to a given point.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"blue\">double</span> SignedDistanceTo(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"teal\">Debug</span>.Assert(\n      <span class=\"teal\">Util</span>.IsEqual( plane.Normal.GetLength(), 1 ),\n      <span class=\"maroon\">\"expected normalised plane normal\"</span> );\n \n    <span class=\"teal\">XYZ</span> v = p - plane.Origin;\n \n    <span class=\"blue\">return</span> plane.Normal.DotProduct( v );\n  }\n</pre><a name=\"12\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Projecting a 3D Point Onto a Plane",
    "local_header_href": "#projecting-a-3d-point-onto-a-plane",
    "chunk_text": "<h4>Projecting a 3D Point Onto a Plane</h4><p>ProjectOnto returns a 3D XYZ point representing the projection of a given point in space onto the surface of the plane.\nThe result can be easily determined by subtracting the plane normal multiplied by the signed distance from the point:</p><pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Project given 3D XYZ point onto plane.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">XYZ</span> ProjectOnto(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"blue\">double</span> d = plane.SignedDistanceTo( p );\n \n    //XYZ q = p + d * plane.Normal; // wrong according to Ruslan Hanza and Alexander Pekshev in their comments below\n\n    <span class=\"teal\">XYZ</span> q = p - d * plane.Normal;\n \n    <span class=\"teal\">Debug</span>.Assert(\n      <span class=\"teal\">Util</span>.IsZero( plane.SignedDistanceTo( q ) ),\n      <span class=\"maroon\">\"expected point on plane to have zero distance to plane\"</span> );\n \n    <span class=\"blue\">return</span> q;\n  }\n</pre><a name=\"13\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "Projecting a 3D Point Into a Plane",
    "local_header_href": "#projecting-a-3d-point-into-a-plane",
    "chunk_text": "<h4>Projecting a 3D Point Into a Plane</h4><p>ProjectInto is similar to ProjectOnto but adds an important twist.\nInstead of a 3D XYZ point, it returns a 2D UV one representing the projection of the given point in the local coordinate system on the surface of the plane.</p><p>The 3D point calculated by ProjectOnto above is in global 3D world coordinates.\nThe 2D point is in plane coordinates.</p><p>It can be determined by calculating the dot product of the vector between the plane origin and the projected point with the plane X and Y vectors, respectively.\nThese two vectors determine the direction of the U and V coordinates on the plane surface:</p><pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Project given 3D XYZ point into plane, </span>\n  <span class=\"gray\">///</span><span class=\"green\"> returning the UV coordinates of the result </span>\n  <span class=\"gray\">///</span><span class=\"green\"> in the local 2D plane coordinate system.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">UV</span> ProjectInto(\n    <span class=\"blue\">this</span> <span class=\"teal\">Plane</span> plane,\n    <span class=\"teal\">XYZ</span> p )\n  {\n    <span class=\"teal\">XYZ</span> q = plane.ProjectOnto( p );\n    <span class=\"teal\">XYZ</span> o = plane.Origin;\n    <span class=\"teal\">XYZ</span> d = q - o;\n    <span class=\"blue\">double</span> u = d.DotProduct( plane.XVec );\n    <span class=\"blue\">double</span> v = d.DotProduct( plane.YVec );\n    <span class=\"blue\">return</span> <span class=\"blue\">new</span> <span class=\"teal\">UV</span>( u, v );\n  }\n</pre><a name=\"14\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "PickPointsForArea",
    "local_header_href": "#pickpointsforarea",
    "chunk_text": "<h4>PickPointsForArea</h4><p>Wit these helper extension methods in hand, I can reimplement your SetWorkPlaneAndPickPointsForArea method like this, renaming it to PickPointsForArea, since no workplane manipulations are required any longer to achieve the same effect:</p><pre class=\"code\">\n  <span class=\"blue\">public</span> <span class=\"blue\">void</span> PickPointsForArea(\n    <span class=\"teal\">UIDocument</span> uidoc )\n  {\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n    <span class=\"teal\">View</span> view = doc.ActiveView;\n \n    <span class=\"teal\">XYZ</span> p1, p2;\n \n    <span class=\"blue\">try</span>\n    {\n      p1 = uidoc.Selection.PickPoint(\n        <span class=\"maroon\">\"Please pick first point for area\"</span> );\n \n      p2 = uidoc.Selection.PickPoint(\n        <span class=\"maroon\">\"Please pick second point for area\"</span> );\n    }\n    <span class=\"blue\">catch</span>( Autodesk.Revit.Exceptions.<span class=\"teal\">OperationCanceledException</span> )\n    {\n      <span class=\"blue\">return</span>;\n    }\n \n    <span class=\"teal\">Plane</span> plane = view.SketchPlane.GetPlane();\n \n    <span class=\"teal\">UV</span> q1 = plane.ProjectInto( p1 );\n    <span class=\"teal\">UV</span> q2 = plane.ProjectInto( p2 );\n    <span class=\"teal\">UV</span> d = q2 - q1;\n \n    <span class=\"blue\">double</span> area = d.U * d.V;\n \n    area = <span class=\"teal\">Math</span>.Round( area, 2 );\n \n    <span class=\"blue\">if</span>( area &lt; 0 )\n    {\n      area = area * ( -1 );\n    }\n \n    <span class=\"teal\">TaskDialog</span>.Show( <span class=\"maroon\">\"Area\"</span>, area.ToString() );\n  }\n</pre><a name=\"15\"></a>"
  },
  {
    "original_filename": "1202_plane_proj_pick",
    "header_text": "The Building Coder Samples Updated",
    "local_header_href": "#the-building-coder-samples-updated",
    "chunk_text": "<h4>The Building Coder Samples Updated</h4><p>I incorporated all the code presented above in The Building Coder samples.</p><p>You can download the full solution from\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">\nThe Building Coder samples</a> GitHub\n\nrepository.</p><p>The version discussed above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.111.2\">2015.0.111.2</a>.</p><p>Here are direct links to the\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/Util.cs\">Util</a> and\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdPickPoint3d.cs\">CmdPickPoint3d</a> modules,\n\nin case you prefer not to clone the whole thing.</p>"
  }
]