[
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<script src=\"http://thebuildingcoder.typepad.com/google-code-prettify/run_prettify.js\"></script>\n</head>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "Events, Again, and Creating an Extrusion Roof",
    "local_header_href": "#events-again-and-creating-an-extrusion-roof",
    "chunk_text": "<h3>Events, Again, and Creating an Extrusion Roof</h3><p>Jon and Scott Wilson discussed some issues\n\n<a href=\"http://forums.autodesk.com/t5/revit-api/extrusion-roof-fails/td-p/5300295\">\ncreating extrusion roofs</a> on\n\narbitrary planes in the Revit API discussion forum in the past couple of days.</p><p>One neat spin-off is a simple little external command that shows the basic use of the NewExtrusionRoof method, so I took the opportunity of adding that to The Building Coder samples.</p><p>Before getting to the details of that, here is a little update on the upcoming events:</p><ul>\n<li><a href=\"#2\">October hackathons and AU Germany</a></li>\n<li><a href=\"#3\">Autodesk University in Las Vegas</a></li>\n<li><a href=\"#4\">DevDays registration and motto</a></li>\n<li><a href=\"#5\">DevDay meetups</a></li>\n<li><a href=\"#6\">Presentation best practices</a></li>\n<li><a href=\"#7\">Creating an extrusion roof</a></li>\n</ul><a name=\"2\"></a>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "October Hackathons and AU Germany",
    "local_header_href": "#october-hackathons-and-au-germany",
    "chunk_text": "<h4>October Hackathons and AU Germany</h4><p>October will be a busy travelling month for me, participating in hackathons in Zurich, Brussels and Berlin, with the German Autodesk University in Darmstadt taking place in between as well.</p><p>The\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/08/upcoming-event-calendar.html\">\nDevDay, meetup and hackathon event calendar</a> I\n\npublished a month ago remains valid.</p><a name=\"3\"></a>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "Autodesk University in Las Vegas",
    "local_header_href": "#autodesk-university-in-las-vegas",
    "chunk_text": "<h4>Autodesk University in Las Vegas</h4><p>As planned and announced, I am participating at Autodesk University in Las Vegas and the ADN DevDay and DevHack events preceding it.</p><center>\n<img alt=\"Autodesk University 2014\" src=\"img/AU14-Speaker-275x250.png\" width=\"275\"/>\n</center><p>My class proposals were not accepted, so my main responsibility besides the DevDay and DevHack will be to lead the Revit API expert panel\n\n<!--\n\nhttps://events.au.autodesk.com/connect/search.ww#loadSearch-searchPhrase=tammik&searchType=session&tc=0&sortBy=&i(11080)=\nhttps://events.au.autodesk.com/connect/sessionDetail.ww?SESSION_ID=5156\n\n-->\n<a href=\"https://events.au.autodesk.com/connect/sessionDetail.ww?SESSION_ID=5156\">\nSD5156 – Open House on the Factory Floor</a>.</p><p>You can check the\n\n<a href=\"https://events.au.autodesk.com/connect/dashboard.ww\">\nAU 2014 class catalogue</a> for\n\nthe complete list of classes.</p><a name=\"4\"></a>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "DevDays Registration and Motto",
    "local_header_href": "#devdays-registration-and-motto",
    "chunk_text": "<h4>DevDays Registration and Motto</h4><p>The\n\n<a href=\"http://autodeskdevdays.com\">\nDevDays registration</a> is\n\nnow open to ADN members. The participation is free of charge.</p><p>At several sites worldwide, you can stay on for a DevHack or an evening meetup.</p><p>The meetups are open for non-ADN members as well.</p><p>The\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/08/upcoming-event-calendar.html#2\">\nlist of sites</a> I\n\npublished a month ago remains valid.</p><p>This year's DevDays theme is <b>10x</b>, sharing how Autodesk is expanding its business and how you can join in on this 10x journey by using Cloud, Mobile and Desktop technologies to expand your user base by 10x while growing your revenue and profits.</p><a name=\"5\"></a>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "DevDay Meetups",
    "local_header_href": "#devday-meetups",
    "chunk_text": "<h4>DevDay Meetups</h4><p>The associated meetups offer an opportunity to gather with ADN partners, Autodesk and other local technologists in your community for a social and educational evening.  The focus will be on bringing 3D to the web and mobile devices.  Autodesk is investing in technology to make it easy for people to bring 3D content to the web across a whole range of industries and applications in addition to design and engineering.  We'll have lively discussions and sharing on where broader technologies are heading as well as how to make the web an engaging 3D experience for your customers and target users.</p><p>These meetups are open to non-ADN members, so feel free to invite your technology friends and join us for some food, beverages and engaging conversation!</p><p>You can check the locations at which evening meetups will be held by visiting\n\n<a href=\"http://autodeskdevdays.com/meetups\">autodeskdevdays.com/meetups</a>.\n\n\n\n<a name=\"6\"></a>\n<h4>Presentation Best Practices</h4>\n<p>With all these events and conferences coming up, we will be doing a lot of presenting.</p>\n<p>Here is a list of 33 presentation tips and tricks, pointed out by Jim Quanci, courtesy of\n\n<a href=\"http://www.inc.com/geoffrey-james/33-tricks-that-make-presentations-memorable.html\">Geoffrey James</a>,\n\nplus another nine important suggestions specific to discussing API and source code contributed by Stephen Preston:\n\n<ol>\n<li>Build your presentation around the decision you want made.</li>\n<li>Structure the presentation as a journey through a series of emotions.</li>\n<li>Keep it simple. Your audience doesn't want or need more complexity.</li>\n<li>Cut your intro down to a maximum of two sentences.</li>\n<li>Cut your presentations to half as long as you originally thought they should be.</li>\n<li>Include only simple graphics and highlight important data points.</li>\n<li>Use a slide background that's simple with a neutral color.</li>\n<li>Eliminate slides that you might need to skip due to time constraints.</li>\n<li>Expunge business buzzwords from your slides (and your vocabulary).</li>\n<li>Use large fonts in simple faces, like Arial.</li>\n<li>Limit the distracting use of special effects and visual gimcracks.</li>\n<li>Customize every presentation because every audience is different.</li>\n<li>Unless it's a keynote, cut your presentation down to 20 minutes or less.</li>\n<li>No matter what, rehearse your presentation at least 20 times.</li>\n<li>Schedule presentations when audiences can give you their full attention.</li>\n<li>Check your equipment setup well in advance.</li>\n<li>Have somebody else introduce you; it creates anticipation.</li>\n<li>Don't start with an apology lest you seem like a victim.</li>\n<li>Don't review your company's history because nobody cares.</li>\n<li>Kick off with a shocking fact, surprising insight, or unique perspective.</li>\n<li>Keep your front to your audience; don't look back at the screen.</li>\n<li>Be yourself; audiences immediately sense if you're not being genuine.</li>\n<li>Don't fidget with papers, jewelry, glasses, or clothing.</li>\n<li>Speak directly to individuals in the audience, moving from person to person.</li>\n<li>Tell a story that casts your audience as the hero and you as the sidekick.</li>\n<li>Use facts that are quantifiable, verifiable, memorable, and dramatic.</li>\n<li>Slow down. Slow down. Slow down.</li>\n<li>Never read from your slides. It irritates everyone. Never ever.</li>\n<li>Be upbeat and positive but don't tell jokes unless you're a comedian.</li>\n<li>Avoid hot buttons (e.g., politics) that will distract from your message.</li>\n<li>Identify and emphasize the next step you want the audience to take.</li>\n<li>Don't ask for extra time because you're late; instead end on schedule.</li>\n<li>Have a question or two up your sleeve in case nobody has one.</li>\n<li>Use a mouse if you're demoing something that requires zoom, pan and rotate (e.g. the viewer).</li>\n<li>Showing function signatures or very small snippets of code on your slides is OK; don't copy large code snippets into slides – switch to the IDE instead.</li>\n<li>Adjust the IDE font to be large enough to be seen from the back of the room.</li>\n<li>If you're live coding, make sure you have backup code in case you make a mistake – it's really hard to spot typos in your code when 500 people are staring at you – and don't spend more than one minute trying to fix your code before going to your backup.</li>\n<li>Live coding is cool, but not if its long or repetitive. Have code snippets available to copy and paste so you don't have to type everything.</li>\n<li>If you're talking through the code – run it in the debugger and step through it – don't just point at static lines of code and explain what would have happened if it was running.</li>\n<li>It's often a good idea to demonstrate what your finished code does before going back and showing how to write it.</li>\n<li>When you're sitting at your laptop debugging code, your head tends to drop down and you voice becomes quieter. Fight this tendency by sticking a post-it note at the top of your screen that says ‘speak up' or similar.</li>\n<li>Only sit behind your computer for as long as it takes to demo the code – then stand up again and move out from behind the table.</li>\n</ol>\n<p>Sounds too good to be true, doesn't it?\nLet's see how well we can abide by them all  :-)</p>\n<a name=\"7\"></a>\n<h4>Creating an Extrusion Roof</h4>\n<p>Back to some hard-core Revit API usage.</p>\n<p>In their discussion on\n\n<a href=\"http://forums.autodesk.com/t5/revit-api/extrusion-roof-fails/td-p/5300295\">\nextrusion roof failure</a> on\n\narbitrary planes in the Revit API discussion forum, Jon and Scott Wilson are looking at more subtle issues.</p>\n<p>Ignoring those for the moment, I just grabbed Jon's example code to demonstrate the basic use of the NewExtrusionRoof method, using it to add a new external command named CmdNewExtrusionRoof to The Building Coder samples.</p>\n<p>It generates this stair-shaped element, which in actual fact really is a roof:</p>\n<center>\n<img alt=\"NewExtrusionRoof\" src=\"img/NewExtrusionRoof.png\" width=\"295\"/>\n</center>\n<p>The completely self-contained external command Execute method mainline looks like this:</p>\n<pre class=\"code\">\n  <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n  <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n  <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tx.Start( <span class=\"maroon\">\"NewExtrusionRoof\"</span> );\n \n    <span class=\"teal\">RoofType</span> fs\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RoofType</span> ) )\n        .Cast&lt;<span class=\"teal\">RoofType</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">RoofType</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"teal\">Level</span> lvl\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) )\n        .Cast&lt;<span class=\"teal\">Level</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">Level</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"blue\">double</span> x = 1;\n \n    <span class=\"teal\">XYZ</span> origin = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 0, 0 );\n    <span class=\"teal\">XYZ</span> vx = <span class=\"teal\">XYZ</span>.BasisY;\n    <span class=\"teal\">XYZ</span> vy = <span class=\"teal\">XYZ</span>.BasisZ;\n \n    <span class=\"teal\">SketchPlane</span> sp = <span class=\"teal\">SketchPlane</span>.Create( doc,\n      <span class=\"blue\">new</span> Autodesk.Revit.DB.<span class=\"teal\">Plane</span>( vx, vy,\n        origin ) );\n \n    <span class=\"teal\">CurveArray</span> ca = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"teal\">XYZ</span>[] pts = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>[] {\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 0 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 4 ) };\n \n    <span class=\"blue\">int</span> n = pts.Length;\n \n    <span class=\"blue\">for</span>( <span class=\"blue\">int</span> i = 1; i &lt; n; ++i )\n    {\n      ca.Append( <span class=\"teal\">Line</span>.CreateBound(\n        pts[i - 1], pts[i] ) );\n    }\n \n    doc.Create.NewModelCurveArray( ca, sp );\n \n    <span class=\"teal\">View</span> v = doc.ActiveView;\n \n    <span class=\"teal\">ReferencePlane</span> rp\n      = doc.Create.NewReferencePlane2(\n        origin, origin + vx, origin + vy, v );\n \n    rp.Name = <span class=\"maroon\">\"MyRoofPlane\"</span>;\n \n    <span class=\"teal\">ExtrusionRoof</span> er\n      = doc.Create.NewExtrusionRoof(\n        ca, rp, lvl, fs, 0, 3 );\n \n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Extrusion roof element id: \"</span>\n      + er.Id.ToString() );\n \n    tx.Commit();\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n</pre>\n<p>You can download the most up-to-date version from\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">\nThe Building Coder samples</a> GitHub\n\nrepository.</p>\n<p>The version discussed above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.112.0\">2015.0.112.0</a>.</p>\n</p></p>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "Presentation Best Practices",
    "local_header_href": "#presentation-best-practices",
    "chunk_text": "<h4>Presentation Best Practices</h4><p>With all these events and conferences coming up, we will be doing a lot of presenting.</p><p>Here is a list of 33 presentation tips and tricks, pointed out by Jim Quanci, courtesy of\n\n<a href=\"http://www.inc.com/geoffrey-james/33-tricks-that-make-presentations-memorable.html\">Geoffrey James</a>,\n\nplus another nine important suggestions specific to discussing API and source code contributed by Stephen Preston:\n\n<ol>\n<li>Build your presentation around the decision you want made.</li>\n<li>Structure the presentation as a journey through a series of emotions.</li>\n<li>Keep it simple. Your audience doesn't want or need more complexity.</li>\n<li>Cut your intro down to a maximum of two sentences.</li>\n<li>Cut your presentations to half as long as you originally thought they should be.</li>\n<li>Include only simple graphics and highlight important data points.</li>\n<li>Use a slide background that's simple with a neutral color.</li>\n<li>Eliminate slides that you might need to skip due to time constraints.</li>\n<li>Expunge business buzzwords from your slides (and your vocabulary).</li>\n<li>Use large fonts in simple faces, like Arial.</li>\n<li>Limit the distracting use of special effects and visual gimcracks.</li>\n<li>Customize every presentation because every audience is different.</li>\n<li>Unless it's a keynote, cut your presentation down to 20 minutes or less.</li>\n<li>No matter what, rehearse your presentation at least 20 times.</li>\n<li>Schedule presentations when audiences can give you their full attention.</li>\n<li>Check your equipment setup well in advance.</li>\n<li>Have somebody else introduce you; it creates anticipation.</li>\n<li>Don't start with an apology lest you seem like a victim.</li>\n<li>Don't review your company's history because nobody cares.</li>\n<li>Kick off with a shocking fact, surprising insight, or unique perspective.</li>\n<li>Keep your front to your audience; don't look back at the screen.</li>\n<li>Be yourself; audiences immediately sense if you're not being genuine.</li>\n<li>Don't fidget with papers, jewelry, glasses, or clothing.</li>\n<li>Speak directly to individuals in the audience, moving from person to person.</li>\n<li>Tell a story that casts your audience as the hero and you as the sidekick.</li>\n<li>Use facts that are quantifiable, verifiable, memorable, and dramatic.</li>\n<li>Slow down. Slow down. Slow down.</li>\n<li>Never read from your slides. It irritates everyone. Never ever.</li>\n<li>Be upbeat and positive but don't tell jokes unless you're a comedian.</li>\n<li>Avoid hot buttons (e.g., politics) that will distract from your message.</li>\n<li>Identify and emphasize the next step you want the audience to take.</li>\n<li>Don't ask for extra time because you're late; instead end on schedule.</li>\n<li>Have a question or two up your sleeve in case nobody has one.</li>\n<li>Use a mouse if you're demoing something that requires zoom, pan and rotate (e.g. the viewer).</li>\n<li>Showing function signatures or very small snippets of code on your slides is OK; don't copy large code snippets into slides – switch to the IDE instead.</li>\n<li>Adjust the IDE font to be large enough to be seen from the back of the room.</li>\n<li>If you're live coding, make sure you have backup code in case you make a mistake – it's really hard to spot typos in your code when 500 people are staring at you – and don't spend more than one minute trying to fix your code before going to your backup.</li>\n<li>Live coding is cool, but not if its long or repetitive. Have code snippets available to copy and paste so you don't have to type everything.</li>\n<li>If you're talking through the code – run it in the debugger and step through it – don't just point at static lines of code and explain what would have happened if it was running.</li>\n<li>It's often a good idea to demonstrate what your finished code does before going back and showing how to write it.</li>\n<li>When you're sitting at your laptop debugging code, your head tends to drop down and you voice becomes quieter. Fight this tendency by sticking a post-it note at the top of your screen that says ‘speak up' or similar.</li>\n<li>Only sit behind your computer for as long as it takes to demo the code – then stand up again and move out from behind the table.</li>\n</ol>\n<p>Sounds too good to be true, doesn't it?\nLet's see how well we can abide by them all  :-)</p>\n<a name=\"7\"></a>\n<h4>Creating an Extrusion Roof</h4>\n<p>Back to some hard-core Revit API usage.</p>\n<p>In their discussion on\n\n<a href=\"http://forums.autodesk.com/t5/revit-api/extrusion-roof-fails/td-p/5300295\">\nextrusion roof failure</a> on\n\narbitrary planes in the Revit API discussion forum, Jon and Scott Wilson are looking at more subtle issues.</p>\n<p>Ignoring those for the moment, I just grabbed Jon's example code to demonstrate the basic use of the NewExtrusionRoof method, using it to add a new external command named CmdNewExtrusionRoof to The Building Coder samples.</p>\n<p>It generates this stair-shaped element, which in actual fact really is a roof:</p>\n<center>\n<img alt=\"NewExtrusionRoof\" src=\"img/NewExtrusionRoof.png\" width=\"295\"/>\n</center>\n<p>The completely self-contained external command Execute method mainline looks like this:</p>\n<pre class=\"code\">\n  <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n  <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n  <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tx.Start( <span class=\"maroon\">\"NewExtrusionRoof\"</span> );\n \n    <span class=\"teal\">RoofType</span> fs\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RoofType</span> ) )\n        .Cast&lt;<span class=\"teal\">RoofType</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">RoofType</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"teal\">Level</span> lvl\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) )\n        .Cast&lt;<span class=\"teal\">Level</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">Level</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"blue\">double</span> x = 1;\n \n    <span class=\"teal\">XYZ</span> origin = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 0, 0 );\n    <span class=\"teal\">XYZ</span> vx = <span class=\"teal\">XYZ</span>.BasisY;\n    <span class=\"teal\">XYZ</span> vy = <span class=\"teal\">XYZ</span>.BasisZ;\n \n    <span class=\"teal\">SketchPlane</span> sp = <span class=\"teal\">SketchPlane</span>.Create( doc,\n      <span class=\"blue\">new</span> Autodesk.Revit.DB.<span class=\"teal\">Plane</span>( vx, vy,\n        origin ) );\n \n    <span class=\"teal\">CurveArray</span> ca = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"teal\">XYZ</span>[] pts = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>[] {\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 0 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 4 ) };\n \n    <span class=\"blue\">int</span> n = pts.Length;\n \n    <span class=\"blue\">for</span>( <span class=\"blue\">int</span> i = 1; i &lt; n; ++i )\n    {\n      ca.Append( <span class=\"teal\">Line</span>.CreateBound(\n        pts[i - 1], pts[i] ) );\n    }\n \n    doc.Create.NewModelCurveArray( ca, sp );\n \n    <span class=\"teal\">View</span> v = doc.ActiveView;\n \n    <span class=\"teal\">ReferencePlane</span> rp\n      = doc.Create.NewReferencePlane2(\n        origin, origin + vx, origin + vy, v );\n \n    rp.Name = <span class=\"maroon\">\"MyRoofPlane\"</span>;\n \n    <span class=\"teal\">ExtrusionRoof</span> er\n      = doc.Create.NewExtrusionRoof(\n        ca, rp, lvl, fs, 0, 3 );\n \n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Extrusion roof element id: \"</span>\n      + er.Id.ToString() );\n \n    tx.Commit();\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n</pre>\n<p>You can download the most up-to-date version from\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">\nThe Building Coder samples</a> GitHub\n\nrepository.</p>\n<p>The version discussed above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.112.0\">2015.0.112.0</a>.</p>\n</p>"
  },
  {
    "original_filename": "1215_extrusion_roof",
    "header_text": "Creating an Extrusion Roof",
    "local_header_href": "#creating-an-extrusion-roof",
    "chunk_text": "<h4>Creating an Extrusion Roof</h4><p>Back to some hard-core Revit API usage.</p><p>In their discussion on\n\n<a href=\"http://forums.autodesk.com/t5/revit-api/extrusion-roof-fails/td-p/5300295\">\nextrusion roof failure</a> on\n\narbitrary planes in the Revit API discussion forum, Jon and Scott Wilson are looking at more subtle issues.</p><p>Ignoring those for the moment, I just grabbed Jon's example code to demonstrate the basic use of the NewExtrusionRoof method, using it to add a new external command named CmdNewExtrusionRoof to The Building Coder samples.</p><p>It generates this stair-shaped element, which in actual fact really is a roof:</p><center>\n<img alt=\"NewExtrusionRoof\" src=\"img/NewExtrusionRoof.png\" width=\"295\"/>\n</center><p>The completely self-contained external command Execute method mainline looks like this:</p><pre class=\"code\">\n  <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n  <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n  <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tx.Start( <span class=\"maroon\">\"NewExtrusionRoof\"</span> );\n \n    <span class=\"teal\">RoofType</span> fs\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">RoofType</span> ) )\n        .Cast&lt;<span class=\"teal\">RoofType</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">RoofType</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"teal\">Level</span> lvl\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">Level</span> ) )\n        .Cast&lt;<span class=\"teal\">Level</span>&gt;()\n        .FirstOrDefault&lt;<span class=\"teal\">Level</span>&gt;( a =&gt; <span class=\"blue\">null</span> != a );\n \n    <span class=\"blue\">double</span> x = 1;\n \n    <span class=\"teal\">XYZ</span> origin = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 0, 0 );\n    <span class=\"teal\">XYZ</span> vx = <span class=\"teal\">XYZ</span>.BasisY;\n    <span class=\"teal\">XYZ</span> vy = <span class=\"teal\">XYZ</span>.BasisZ;\n \n    <span class=\"teal\">SketchPlane</span> sp = <span class=\"teal\">SketchPlane</span>.Create( doc,\n      <span class=\"blue\">new</span> Autodesk.Revit.DB.<span class=\"teal\">Plane</span>( vx, vy,\n        origin ) );\n \n    <span class=\"teal\">CurveArray</span> ca = <span class=\"blue\">new</span> <span class=\"teal\">CurveArray</span>();\n \n    <span class=\"teal\">XYZ</span>[] pts = <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>[] {\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 0 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 1, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 1 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 2, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 2 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 3, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 3 ),\n      <span class=\"blue\">new</span> <span class=\"teal\">XYZ</span>( x, 4, 4 ) };\n \n    <span class=\"blue\">int</span> n = pts.Length;\n \n    <span class=\"blue\">for</span>( <span class=\"blue\">int</span> i = 1; i &lt; n; ++i )\n    {\n      ca.Append( <span class=\"teal\">Line</span>.CreateBound(\n        pts[i - 1], pts[i] ) );\n    }\n \n    doc.Create.NewModelCurveArray( ca, sp );\n \n    <span class=\"teal\">View</span> v = doc.ActiveView;\n \n    <span class=\"teal\">ReferencePlane</span> rp\n      = doc.Create.NewReferencePlane2(\n        origin, origin + vx, origin + vy, v );\n \n    rp.Name = <span class=\"maroon\">\"MyRoofPlane\"</span>;\n \n    <span class=\"teal\">ExtrusionRoof</span> er\n      = doc.Create.NewExtrusionRoof(\n        ca, rp, lvl, fs, 0, 3 );\n \n    <span class=\"teal\">Debug</span>.Print( <span class=\"maroon\">\"Extrusion roof element id: \"</span>\n      + er.Id.ToString() );\n \n    tx.Commit();\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n</pre><p>You can download the most up-to-date version from\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">\nThe Building Coder samples</a> GitHub\n\nrepository.</p><p>The version discussed above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.112.0\">2015.0.112.0</a>.</p>"
  }
]