[
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<script src=\"http://thebuildingcoder.typepad.com/google-code-prettify/run_prettify.js\"></script>\n</head>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "NewCrossFitting Connection Order",
    "local_header_href": "#newcrossfitting-connection-order",
    "chunk_text": "<h3>NewCrossFitting Connection Order</h3><p>A long, long time ago, Davex raised a very pertinent question on the error message and\n\n<a href=\"http://forums.autodesk.com/t5/revit-api/newcrossfitting-nondescriptive-exception-thrown/td-p/2824298\">\nnondescriptive exception thrown</a> by\n\nthe attempted creation of a new Revit MEP 2014 cross fitting.</p><p>I finally get around to addressing that.\nI very much hope that Davex also figured it out in the meantime...</p><p><strong>Question:</strong> I am attempting to create a cross fitting by calling Owner.Document.Create.NewCrossFitting, passing in 4 connectors to pipes that are on the same plane and lie along orthogonal lines.\nI've verified that the connectors are all at the same point.</p><p>When I try to call NewCrossFitting, an InvalidOperationException is thrown, with a message stating the obvious:</p><pre>\n  \"failed to insert cross\"\n</pre><p>Are there many scenarios where this exception can be thrown, or does it have one specific meaning?  If the former, is there a way to make a feature request of the Revit developers to write exception descriptions that aren't totally useless?</p><p>By the way, many other Revit MEP API method descriptions in the Revit API help file RevitAPI.chm and the developer guide are also very short indeed.\nI hope that more information about them will be made available one of these days.</p><p><strong>Answer:</strong> The API expects the four cross fitting connectors to be specified in the order main – main – side - side. When the input pipes are selected using the PickElementsByRectangle method, they end up cross selected, and the connection order passed in is main-side-main-side. Once you switch the order back to the expected sequence, the cross fitting will be successfully added.</p><p>I agree that the exception messages could be improved to warn users about these kinds of expectations. Part of problem is that in the distant past, these handwritten APIs were often created separately from the internal source code. It is a long overdue project to remove all the  handwritten APIs.</p><p><strong>Response:</strong> Thanks very much for pointing to the way out.\nThis works like a charm.</p><p>I once tried to swap the second with the fourth parameters and that failed as well, so I never tried the other order.</p><p>The secret is indeed the parameter order: main-main-side-side.</p><p>Thanks to Joe Ye and Liang Zhu for clarifying this.</p><a name=\"2\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "The Building Coder Sample CmdNewCrossFitting Command",
    "local_header_href": "#the-building-coder-sample-cmdnewcrossfitting-command",
    "chunk_text": "<h4>The Building Coder Sample CmdNewCrossFitting Command</h4><p>I added the solution to The Building Coder samples as a new external command CmdNewCrossFitting.</p><p>Among other things, it demonstrates use of a newly implemented Element extension method GetCurve, the PickElementsByRectangle selection functionality, ensuring that exactly 2, 3 or 4 pipes are selected, and last but not least, the NewTeeFitting and NewCrossFitting methods:</p><ul>\n<li><a href=\"#3\">The Element extension method GetCurve</a></li>\n<li><a href=\"#4\">Pipe direction</a></li>\n<li><a href=\"#5\">Parallel pipes predicate</a></li>\n<li><a href=\"#6\">CmdNewCrossFitting implementation</a></li>\n<li><a href=\"#7\">Results</a></li>\n<li><a href=\"#8\">Download</a></li>\n</ul><p>By the way, the NewElbowFitting that is also used below was already exercised by the CmdRollingOffset command implemented to\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/01/explicitly-placing-rolling-offset-pipe-elbow-fittings.html\">explicitly place rolling offset elbow fittings</a>.</p><a name=\"3\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "The Element Extension Method GetCurve",
    "local_header_href": "#the-element-extension-method-getcurve",
    "chunk_text": "<h4>The Element Extension Method GetCurve</h4><p>I implemented a new extension method for the Revit API Element class to provide direct access to the geometrical Curve element encapsulated in the Element Location property, if it exists:</p><pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"blue\">class</span> <span class=\"teal\">JtElementExtensionMethods</span>\n{\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return the curve from a Revit database Element </span>\n  <span class=\"gray\">///</span><span class=\"green\"> location curve, if it has one.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">public</span> <span class=\"blue\">static</span> <span class=\"teal\">Curve</span> GetCurve( <span class=\"blue\">this</span> <span class=\"teal\">Element</span> e )\n  {\n    <span class=\"teal\">Debug</span>.Assert( <span class=\"blue\">null</span> != e.Location,\n      <span class=\"maroon\">\"expected an element with a valid Location\"</span> );\n \n    <span class=\"teal\">LocationCurve</span> lc = e.Location <span class=\"blue\">as</span> <span class=\"teal\">LocationCurve</span>;\n \n    <span class=\"teal\">Debug</span>.Assert( <span class=\"blue\">null</span> != lc,\n      <span class=\"maroon\">\"expected an element with a valid LocationCurve\"</span> );\n \n    <span class=\"blue\">return</span> lc.Curve;\n  }\n}\n</pre><a name=\"4\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "Pipe Direction",
    "local_header_href": "#pipe-direction",
    "chunk_text": "<h4>Pipe Direction</h4><p>The analysis of the geometrical pipe relationships with each other obviously requires us to determine their direction. That is provided by the following trivial method:</p><pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Return the normalised direction of the given pipe.</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"teal\">XYZ</span> GetPipeDirection( <span class=\"teal\">Pipe</span> pipe )\n  {\n    <span class=\"teal\">Curve</span> c = pipe.GetCurve();\n    <span class=\"teal\">XYZ</span> dir = c.GetEndPoint( 1 ) - c.GetEndPoint( 1 );\n    dir = dir.Normalize();\n    <span class=\"blue\">return</span> dir;\n  }\n</pre><a name=\"5\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "Parallel Pipes Predicate",
    "local_header_href": "#parallel-pipes-predicate",
    "chunk_text": "<h4>Parallel Pipes Predicate</h4><p>A similarly trivial comparison of the directions of two given pipes tells us whether they are parallel or not:</p><pre class=\"code\">\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n  <span class=\"gray\">///</span><span class=\"green\"> Are the two given pipes parallel?</span>\n  <span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n  <span class=\"blue\">bool</span> IsPipeParallel( <span class=\"teal\">Pipe</span> p1, <span class=\"teal\">Pipe</span> p2 )\n  {\n    <span class=\"teal\">Line</span> c1 = p1.GetCurve() <span class=\"blue\">as</span> <span class=\"teal\">Line</span>;\n    <span class=\"teal\">Line</span> c2 = p2.GetCurve() <span class=\"blue\">as</span> <span class=\"teal\">Line</span>;\n    <span class=\"blue\">return</span> <span class=\"teal\">Math</span>.Sin( c1.Direction.AngleTo(\n      c2.Direction ) ) &lt; 0.01;\n  }\n</pre><a name=\"6\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "CmdNewCrossFitting Implementation",
    "local_header_href": "#cmdnewcrossfitting-implementation",
    "chunk_text": "<h4>CmdNewCrossFitting Implementation</h4><p>With these tools in hand, we are now ready for the interesting part.</p><p>We prompt the user to select 2, 3 or 4 pipes.</p><p>The selection process continues until she succeeds in doing so or cancels, in which case the ensuing exception is handled gracefully.</p><p>The number of pipes selected determines whether an elbow, tee or cross fitting is inserted.</p><p>The geometric relationships between the pipes are used to determine the correct order to pass in the connectors to the respective creation methods.</p><pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n  <span class=\"teal\">ExternalCommandData</span> commandData,\n  <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n  <span class=\"teal\">ElementSet</span> elements )\n{\n  <span class=\"teal\">UIApplication</span> app = commandData.Application;\n  <span class=\"teal\">UIDocument</span> uidoc = app.ActiveUIDocument;\n  <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n  <span class=\"teal\">IList</span>&lt;<span class=\"teal\">Element</span>&gt; pipes = <span class=\"blue\">null</span>;\n  <span class=\"blue\">int</span> n = 0;\n \n  <span class=\"green\">// Ensure that 2, 3 or 4 pipes are selected.</span>\n \n  <span class=\"blue\">while</span>( n &lt; 2 || 4 &lt; n )\n  {\n    <span class=\"blue\">if</span>( 0 != n )\n    {\n      <span class=\"teal\">Util</span>.InfoMsg( <span class=\"blue\">string</span>.Format(\n        <span class=\"maroon\">\"You picked {0} pipe{1}. \"</span>\n        + <span class=\"maroon\">\"Please only pick 2, 3 or 4.\"</span>,\n        n, <span class=\"teal\">Util</span>.PluralSuffix( n ) ) );\n    }\n \n    <span class=\"blue\">try</span>\n    {\n      <span class=\"teal\">Selection</span> sel = app.ActiveUIDocument.Selection;\n \n      <span class=\"teal\">ISelectionFilter</span> filter = <span class=\"blue\">new</span> <span class=\"teal\">CmdRollingOffset</span>\n        .<span class=\"teal\">PipeElementSelectionFilter</span>();\n \n      pipes = sel.PickElementsByRectangle(\n        filter, <span class=\"maroon\">\"Please pick some pipes.\"</span> );\n    }\n    <span class=\"blue\">catch</span>( Autodesk.Revit.Exceptions\n      .<span class=\"teal\">InvalidOperationException</span> )\n    {\n      <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Cancelled;\n    }\n    n = pipes.Count;\n  }\n \n  <span class=\"teal\">XYZ</span> pt = <span class=\"blue\">null</span>;\n \n  <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n  {\n    tx.Start( <span class=\"maroon\">\"CreateConnector\"</span> );\n    <span class=\"blue\">if</span>( pipes.Count() &lt;= 1 )\n      <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Cancelled;\n \n    <span class=\"teal\">Pipe</span> pipe1 = pipes[0] <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span>;\n    <span class=\"teal\">Pipe</span> pipe2 = pipes[1] <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span>;\n \n    <span class=\"teal\">Curve</span> curve1 = pipe1.GetCurve();\n    <span class=\"teal\">Curve</span> curve2 = pipe2.GetCurve();\n \n    <span class=\"teal\">XYZ</span> p1 = curve1.GetEndPoint( 0 );\n    <span class=\"teal\">XYZ</span> q1 = curve1.GetEndPoint( 1 );\n \n    <span class=\"teal\">XYZ</span> p2 = curve2.GetEndPoint( 0 );\n    <span class=\"teal\">XYZ</span> q2 = curve2.GetEndPoint( 1 );\n \n    <span class=\"blue\">if</span>( q1.DistanceTo( p2 ) &lt; 0.1 )\n    {\n      pt = ( q1 + p2 ) * 0.5;\n    }\n    <span class=\"blue\">else</span> <span class=\"blue\">if</span>( q1.DistanceTo( q2 ) &lt; 0.1 )\n    {\n      pt = ( q1 + q2 ) * 0.5;\n    }\n    <span class=\"blue\">else</span> <span class=\"blue\">if</span>( p1.DistanceTo( p2 ) &lt; 0.1 )\n    {\n      pt = ( p1 + p2 ) * 0.5;\n    }\n    <span class=\"blue\">else</span> <span class=\"blue\">if</span>( p1.DistanceTo( q2 ) &lt; 0.1 )\n    {\n      pt = ( p1 + q2 ) * 0.5;\n    }\n    <span class=\"blue\">else</span>\n    {\n      message = <span class=\"maroon\">\"Please select two pipes \"</span>\n        + <span class=\"maroon\">\"with near-by endpoints.\"</span>;\n \n      <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Failed;\n    }\n \n    <span class=\"teal\">Connector</span> c1 = <span class=\"teal\">Util</span>.GetConnectorClosestTo(\n      pipe1, pt );\n \n    <span class=\"teal\">Connector</span> c2 = <span class=\"teal\">Util</span>.GetConnectorClosestTo(\n      pipe2, pt );\n \n    <span class=\"blue\">if</span>( pipes.Count() == 2 )\n    {\n      <span class=\"blue\">if</span>( IsPipeParallel( pipe1, pipe2 ) == <span class=\"blue\">true</span> )\n      {\n        doc.Create.NewUnionFitting( c1, c2 );\n      }\n      <span class=\"blue\">else</span>\n      {\n        doc.Create.NewElbowFitting( c1, c2 );\n      }\n    }\n    <span class=\"blue\">else</span> <span class=\"blue\">if</span>( pipes.Count() == 3 )\n    {\n      <span class=\"teal\">Pipe</span> pipe3 = pipes[2] <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span>;\n \n      <span class=\"teal\">XYZ</span> v1 = GetPipeDirection( pipe1 );\n      <span class=\"teal\">XYZ</span> v2 = GetPipeDirection( pipe2 );\n      <span class=\"teal\">XYZ</span> v3 = GetPipeDirection( pipe3 );\n \n      <span class=\"teal\">Connector</span> c3 = <span class=\"teal\">Util</span>.GetConnectorClosestTo(\n        pipe3, pt );\n \n      <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Sin( v1.AngleTo( v2 ) ) &lt; 0.01 ) <span class=\"green\">//平行</span>\n      {\n        doc.Create.NewTeeFitting( c1, c2, c3 );\n      }\n      <span class=\"blue\">else</span> <span class=\"green\">//v1, 和v2 垂直.</span>\n      {\n        <span class=\"blue\">if</span>( <span class=\"teal\">Math</span>.Sin( v3.AngleTo( v1 ) ) &lt; 0.01 ) <span class=\"green\">//v3, V1 平行</span>\n        {\n          doc.Create.NewTeeFitting( c3, c1, c2 );\n        }\n        <span class=\"blue\">else</span> <span class=\"green\">//v3, v2 平行</span>\n        {\n          doc.Create.NewTeeFitting( c3, c2, c1 );\n        }\n      }\n    }\n    <span class=\"blue\">else</span> <span class=\"blue\">if</span>( pipes.Count() == 4 )\n    {\n      <span class=\"teal\">Pipe</span> pipe3 = pipes[2] <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span>;\n      <span class=\"teal\">Pipe</span> pipe4 = pipes[3] <span class=\"blue\">as</span> <span class=\"teal\">Pipe</span>;\n \n      <span class=\"teal\">Connector</span> c3 = <span class=\"teal\">Util</span>.GetConnectorClosestTo(\n        pipe3, pt );\n \n      <span class=\"teal\">Connector</span> c4 = <span class=\"teal\">Util</span>.GetConnectorClosestTo(\n        pipe4, pt );\n \n      <span class=\"green\">//以从哪c1为入口.</span>\n \n      <span class=\"green\">// The required connection order for a cross </span>\n      <span class=\"green\">// fitting is main – main – side - side.</span>\n \n      <span class=\"blue\">if</span>( IsPipeParallel( pipe1, pipe2 ) )\n      {\n        doc.Create.NewCrossFitting(\n          c1, c2, c3, c4 );\n      }\n      <span class=\"blue\">else</span> <span class=\"blue\">if</span>( IsPipeParallel( pipe1, pipe3 ) )\n      {\n        <span class=\"blue\">try</span>\n        {\n          doc.Create.NewCrossFitting(\n            c1, c3, c2, c4 );\n        }\n        <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> ex )\n        {\n          <span class=\"teal\">TaskDialog</span>.Show(\n            <span class=\"maroon\">\"Cannot insert cross fitting\"</span>,\n            ex.Message );\n        }\n      }\n      <span class=\"blue\">else</span> <span class=\"blue\">if</span>( IsPipeParallel( pipe1, pipe4 ) )\n      {\n        doc.Create.NewCrossFitting(\n          c1, c4, c2, c3 );\n      }\n    }\n    tx.Commit();\n  }\n  <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n}\n</pre><a name=\"7\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "Result",
    "local_header_href": "#result",
    "chunk_text": "<h4>Result</h4><p>Here is the initial starting point with four perpendicular pipes meeting in a common point:</p><center>\n<img alt=\"Four pipes meeting in a point\" src=\"img/cross_fitting_pipes.png\" width=\"452\"/>\n</center><p>The result of running the CmdNewCrossFitting command and selecting all four pipes now looks like this:</p><center>\n<img alt=\"The resulting cross fitting\" src=\"img/cross_fitting_result.png\"/>\n</center><a name=\"8\"></a>"
  },
  {
    "original_filename": "1233_newcrossfitting",
    "header_text": "Download",
    "local_header_href": "#download",
    "chunk_text": "<h4>Download</h4><p>The most up to date version of The Building Coder samples is always provided in\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">its GitHub repository</a>,\n\nand the version described above is\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.115.0\">\nrelease 2015.0.115.0</a>.</p>"
  }
]