[
  {
    "original_filename": "1287_post_request_inst",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<link href=\"bc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>"
  },
  {
    "original_filename": "1287_post_request_inst",
    "header_text": "PostRequestForElementTypePlacement Sample",
    "local_header_href": "#postrequestforelementtypeplacement-sample",
    "chunk_text": "<h3>PostRequestForElementTypePlacement Sample</h3><p>I am back from my vacation in the snow, full of new energy, and up to both ears in hot Revit API cases again instead of that frozen stuff  :-)</p><p>The creation document NewFamilyInstance method provides the traditional way to programmatically create a new family instance within a project, or a nested instance within a family document.</p><p>It does not support any user interaction whatsoever.</p><p>A little bit of user interaction is provided by the PromptForFamilyInstancePlacement method introduced in the\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2011-api.html\">Revit 2011 API</a>.</p><p>At least it shows a preview of the item to be placed and prompts the user for its location.</p><p>Numerous samples using the PromptForFamilyInstancePlacement method are available, most recently here, including sample code to execute it and\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2015/02/sending-escape-to-terminate-a-family-instance-placement-loop.html\">\nterminate its family instance placement loop</a>,\n\nand in the Revit API discussion forum, e.g.:</p><ul>\n<li><a href=\"http://forums.autodesk.com/t5/Revit-API/promptforfamilyinstanceplacement-spacebar-to-rotate-causes/m-p/4794701\">\nPromptForFamilyInstancePlacement spacebar to rotate</a></li>\n<li><a href=\"http://forums.autodesk.com/t5/revit-api/promptforf-amilyinsta-nceplaceme-nt-to-allow-adding-in-an/m-p/5439737\">\nPromptForFamilyInstancePlacement in an enclosed space</a></li>\n</ul><p>The PromptForFamilyInstancePlacement method does not offer all the possible user interaction functionality provided by the manual Revit user interface either, though.</p><p>The Revit 2015 API introduced the PostRequestForElementTypePlacement method to access the full Revit user interaction functionality, at the cost of giving up full programmatic control and passing the baton from the add-in code back to Revit, cf.\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/04/whats-new-in-the-revit-2015-api.html\">What's New in the Revit 2015 API</a> &gt;\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/04/whats-new-in-the-revit-2015-api.html#4\">Minor API additions</a> &gt;\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2014/04/whats-new-in-the-revit-2015-api.html#4.02\">Document API additions</a>.</p><p>Another interesting Revit API forum discussion on\n\n<a href=\"http://forums.autodesk.com/t5/Revit-API/Change-the-placement-option-for-PromptForFamilyInstancePlacement/m-p/3187174\">\nchanging the placement option for PromptForFamilyInstancePlacement</a> also\n\nincludes a snippet of sample code in VB.NET by PhillipM for using PostRequestForElementTypePlacement.</p><p>Its usage is extremely simple, since the add-in is asking Revit to do all the work and passing over control as well.</p><p>All you need to do is supply an element type for the user to place:</p><pre class=\"code\">\n[<span class=\"teal\">Transaction</span>( <span class=\"teal\">TransactionMode</span>.Manual )]\n<span class=\"blue\">class</span> <span class=\"teal\">CmdPostRequestInstancePlacement</span> : <span class=\"teal\">IExternalCommand</span>\n{\n  <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n    <span class=\"teal\">ExternalCommandData</span> commandData,\n    <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n    <span class=\"teal\">ElementSet</span> elements )\n  {\n    <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n    <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n    <span class=\"teal\">Document</span> doc = uidoc.Document;\n \n    <span class=\"teal\">ElementType</span> elementType\n      = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n        .OfCategory( <span class=\"teal\">BuiltInCategory</span>.OST_Walls )\n        .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">ElementType</span> ) )\n        .FirstElement() <span class=\"blue\">as</span> <span class=\"teal\">ElementType</span>;\n \n    uidoc.PostRequestForElementTypePlacement(\n      elementType );\n \n    <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n  }\n}\n</pre><p>There is no need to encapsulate the call in a transaction.</p><p>In spite of this, posting the request cannot be triggered in a read-only command, or an invalid operation exception will be triggered saying:</p><blockquote>\n<p>Revit encountered a Autodesk.Revit.Exceptions.InvalidOperationException: Starting a new transaction is not permitted. It could be because another transaction already started and has not been completed yet, or the document is in a state in which it cannot start a new transaction.</p>\n</blockquote><center>\n<img alt=\"PostRequestForElementTypePlacement requires a transaction\" src=\"img/post_request_requires_transaction.png\" width=\"417\"/>\n</center><p>I implemented this code in a new external command named CmdPostRequestInstancePlacement in\n\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples\">The Building Coder samples</a>\n<a href=\"https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2015.0.119.0\">version 2015.0.119.0</a>.</p><a name=\"2\"></a>"
  },
  {
    "original_filename": "1287_post_request_inst",
    "header_text": "The Fear of Fear",
    "local_header_href": "#the-fear-of-fear",
    "chunk_text": "<h4>The Fear of Fear</h4><p>Before signing off for today, here are some sweet and wise thoughts by Mr Ramesh on\n\n<a href=\"https://www.youtube.com/watch?v=CDlILJoYA3E\">fear and aliveness</a>:</p><center>\n<iframe allowfullscreen=\"\" frameborder=\"0\" height=\"236\" src=\"https://www.youtube.com/embed/CDlILJoYA3E\" width=\"420\"></iframe>\n</center><p>Mr Ramesh' invitation to become curious about experiencing your fears is so attractive and sensible that it could revolutionize the world! ... Becoming curious towards our fear...</p>"
  }
]