[
  {
    "original_filename": "1375_flatten_to_directshape",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!---\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n#dotnet #csharp\n#fsharp #python\n#grevit\n#responsivedesign #typepad\n#ah8 #augi #dotnet\n#stingray #adsklabs #rendering\n#3dweb #3dviewapi #html5 #threejs #webgl #3d #apis #mobile #vr #ecommerce\n#Markdown #Fusion360 #Fusion360Hackathon\n#javascript\n#RestSharp #restapi\n#mongoosejs #mongodb #nodejs\n#rtceur\n\n\nRevit API, Jeremy Tammik, akn_include\n\nFlatten Everything to DirectShape #revitapi #bim #aec #3dwebcoder #adsk #adskdevnetwrk #geometry #au2015 #3d #apis\n\nI am still busy preparing my presentations for Autodesk University and making slow progress due to handling too many Revit API issues in between. And blogging, as well. Here is a new cool sample contributed by Nikolay Shulga, Senior Principal Engineer in the Revit development team. In his own words\n&ndash; Name: Flatten\n&ndash; Motivation: I wanted to see whether DirectShapes could be used to lock down a Revit design &ndash; remove most intelligence, make it read-only, perhaps improve performance\n&ndash; Spec: converts full Revit elements into DirectShapes that hold the same shape and have the same categories\n&ndash; Implementation: see below\n&ndash; Cool API aspects: copy element’s geometry and use it elsewhere\n&ndash; Cool ways to use it: lock down your project; make a copy of your element for presentation/export\n&ndash; How it can be enhanced: the sky is the limit...\n\n-->"
  },
  {
    "original_filename": "1375_flatten_to_directshape",
    "header_text": "Flatten All Elements to DirectShape",
    "local_header_href": "#flatten-all-elements-to-directshape",
    "chunk_text": "### Flatten All Elements to DirectShape\n\nI am still busy preparing my presentations for Autodesk University and making slow progress due to handling too many Revit API issues in between.\n\nAnd blogging, as well.\n\nHere is a new cool sample contributed by Nikolay Shulga, Senior Principal Engineer in the Revit development team.\n\nIn his own words:\n\n- Name: Flatten\n- Motivation: I wanted to see whether DirectShapes could be used to lock down a Revit design &ndash; remove most intelligence, make it read-only, perhaps improve performance.\n- Spec: converts full Revit elements into DirectShapes that hold the same shape and have the same categories.\n- Implementation: see below.\n- Cool API aspects: copy element’s geometry and use it elsewhere.\n- Cool ways to use it: lock down your project; make a copy of your element for presentation/export.\n- How it can be enhanced: the sky is the limit.\n- A suitable sample model: any Revit project. Note that the code changes the current project &ndash; make a backup copy.\n\nThis fits in well with the growing interest in direct shapes, as you can observe by the rapidly growing number of entries in\nthe [DirectShape topic group](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.50).\n\nI implemented a new external\ncommand [CmdFlatten](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdFlatten.cs)\nin [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples) to\ntest and demonstrate this functionality.\n\nNikolay's original code was for a future release of Revit, so some backwards adaptation was necessary.\n\nYou can see the changes by looking at the last few GitHub commits.\n\nHere is the final result for running in Revit 2016:\n\n<pre class=\"code\">\n&nbsp; <span class=\"blue\">const</span> <span class=\"blue\">string</span> _direct_shape_appGUID = <span class=\"maroon\">&quot;Flatten&quot;</span>;\n&nbsp;\n&nbsp; <span class=\"teal\">Result</span> Flatten(\n&nbsp; &nbsp; <span class=\"teal\">Document</span> doc,\n&nbsp; &nbsp; <span class=\"teal\">ElementId</span> viewId )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">FilteredElementCollector</span> col\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc, viewId )\n&nbsp; &nbsp; &nbsp; &nbsp; .WhereElementIsNotElementType();\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Options</span> geometryOptions = <span class=\"blue\">new</span> <span class=\"teal\">Options</span>();\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">using</span>( <span class=\"teal\">Transaction</span> tx = <span class=\"blue\">new</span> <span class=\"teal\">Transaction</span>( doc ) )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( tx.Start( <span class=\"maroon\">&quot;Convert elements to DirectShapes&quot;</span> )\n&nbsp; &nbsp; &nbsp; &nbsp; == <span class=\"teal\">TransactionStatus</span>.Started )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">Element</span> e <span class=\"blue\">in</span> col )\n&nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">GeometryElement</span> gelt = e.get_Geometry(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; geometryOptions );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( <span class=\"blue\">null</span> != gelt )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span> appDataGUID = e.Id.ToString();\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// Currently create direct shape </span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// replacement element in the original </span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// document &#8211; no API to properly transfer </span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// graphic styles to a new document.</span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// A possible enhancement: make a copy </span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// of the current project and operate </span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// on the copy.</span>\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">DirectShape</span> ds\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"teal\">DirectShape</span>.CreateElement( doc,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; e.Category.Id, _direct_shape_appGUID,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; appDataGUID );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">try</span>\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ds.SetShape(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">GeometryObject</span>&gt;( gelt ) );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// Delete original element</span>\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; doc.Delete( e.Id );\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">catch</span>( Autodesk.Revit.Exceptions\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .<span class=\"teal\">ArgumentException</span> ex )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">Debug</span>.Print(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"maroon\">&quot;Failed to replace {0}; exception {1} {2}&quot;</span>,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">Util</span>.ElementDescription( e ),\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ex.GetType().FullName,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ex.Message );\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; tx.Commit();\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; }\n&nbsp; &nbsp; <span class=\"blue\">return</span> <span class=\"teal\">Result</span>.Succeeded;\n&nbsp; }\n&nbsp;\n&nbsp; <span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n&nbsp; &nbsp; <span class=\"teal\">ExternalCommandData</span> commandData,\n&nbsp; &nbsp; <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n&nbsp; &nbsp; <span class=\"teal\">ElementSet</span> elements )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n&nbsp; &nbsp; <span class=\"teal\">UIDocument</span> uidoc = uiapp.ActiveUIDocument;\n&nbsp; &nbsp; <span class=\"teal\">Document</span> doc = uidoc.Document;\n&nbsp;\n&nbsp; &nbsp; <span class=\"green\">// At the moment we convert to DirectShapes </span>\n&nbsp; &nbsp; <span class=\"green\">// &quot;in place&quot; - that lets us preserve GStyles </span>\n&nbsp; &nbsp; <span class=\"green\">// referenced by element shape without doing </span>\n&nbsp; &nbsp; <span class=\"green\">// anything special.</span>\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">return</span> Flatten( doc, uidoc.ActiveView.Id );\n&nbsp; }\n</pre>\n\nHere is a trivial example of flattening a wall to a direct shape:\n\n<center>\n<img src=\"img/flatten_01.png\" alt=\"Original wall element\" width=\"242\">\n</center>\n\nThis is the automatically generated DirectShape replacement element, retaining the wall category and storing its original element id:\n\n<center>\n<img src=\"img/flatten_02.png\" alt=\"DirectShape replacement element\" width=\"193\">\n</center>\n\nLet's try it out on a slightly more complex model:\n\n<center>\n<img src=\"img/flatten_03.png\" alt=\"Walls with doors and windows\" width=\"465\">\n</center>\n\nThe family instances get lost by the conversion in its current implementation:\n\n<center>\n<img src=\"img/flatten_04.png\" alt=\"DirectShape replacement element\" width=\"322\">\n</center>\n\nIf you wish to retain family instances, you should probably explore their geometry in a little bit more detail, e.g., to extract all the solids they contain and convert them individually.\n\nThe current version is provided in the\nmodule [CmdFlatten.cs](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdFlatten.cs)\nin [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples)\n[release 2016.0.123.0](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2016.0.123.0).\n\nHave fun playing with this, and many thanks to Nikolay for implementing and sharing it!"
  }
]