[
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!--\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n\n- why Autodesk has a Labs\n  I want to get the word out broadly as to why Autodesk has a Labs. I considered writing a Medium blog article, but rather than create yet another avenue, Dan Zucker suggested that I simply write an article on my blog:\n  http://labs.blogs.com/its_alive_in_the_lab/2016/04/why-does-autodesk-have-a-labs.html\n\n- http://blogs.autodesk.com/dalbiminpoi\n  It's my pleasure to announce a new blog dedicated to AEC in Italy (and in Italian), administrated by Stefano Toparini, authored by Ilaria lagazio and Stefano :\n  \"dal BIM in poi\" means \"Beyond BIM\".\n  Ilaria and Stefano will post there in order to drive and help adoption of our BIM Solutions in Italy.\n  STEFANO TOPARINI\n  Stefano si occupa da molti anni di BIM per le Infrastrutture nonché di reti tecnologiche e di gestione del territorio, con esperienze professionali maturate sia in Italia che all'estero. Lavora nella filiale Italiana di Autodesk Inc. da oltre 10 anni dopo esperienze in varie altre aziende di informatica e servizi nel mondo della progettazione e delle pubbliche amministrazioni.\n  ILARIA LAGAZIO\n  Laureata in Ingegneria Civile e specializzata in Strutture, dopo una breve esperienza nel campo della progettazione si dedica all’industrializzazione dei sistemi edilizi come Building System Development Manager, gestendo il flusso delle informazioni dei componenti edilizi dal modello al cantiere. L’interesse per l’industrializzazione del cantiere e la gestione del dato progettuale la porta ad una esperienza negli Emirati Arabi e dal 2008 in Autodesk , dove oggi ricopre il ruolo di Senior Technical Sales Specialist\n\nDetermining Wall Opening Areas per Room #revitAPI #3dwebcoder @AutodeskRevit #adsk #aec #bim @AutodeskLabs\n\nWe continue the rather exhaustive exploration of calculating net and gross wall areas per room, and two other announcements, pointers to interesting sources of information\n&ndash; Why Autodesk has a Labs\n&ndash; Dal BIM in poi &ndash; Italian BIM\n&ndash; Determining wall opening areas per room\n&ndash; Håvard's SpatialElementGeometryCalculator enhancement\n&ndash; External command mainline\n&ndash; Test run...\n\n-->"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "Determining Wall Opening Areas per Room",
    "local_header_href": "#determining-wall-opening-areas-per-room",
    "chunk_text": "### Determining Wall Opening Areas per Room\n\nWe continue the rather exhaustive exploration of calculating net and gross wall areas per room, and two other announcements, pointers to interesting sources of information besides The Building Coder:\n\n- [Why Autodesk has a Labs](#2)\n- [Dal BIM in poi &ndash; Italian BIM](#3)\n- [Determining wall opening areas per room](#4)\n- [Håvard's SpatialElementGeometryCalculator enhancement](#5)\n- [External command mainline](#6)\n- [Test run](#7)"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"2\"></a>Why Autodesk has a Labs",
    "local_header_href": "#a-name2awhy-autodesk-has-a-labs",
    "chunk_text": "#### <a name=\"2\"></a>Why Autodesk has a Labs\n\nI hope you know and appreciate that Autodesk has a Labs, and why.\n\nIf not, please refer to Scott Sheppard's\nexplanation [why Autodesk has a Labs](http://labs.blogs.com/its_alive_in_the_lab/2016/04/why-does-autodesk-have-a-labs.html)."
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"3\"></a>Dal BIM in Poi &ndash; Italian BIM",
    "local_header_href": "#a-name3adal-bim-in-poi-ndash-italian-bim",
    "chunk_text": "#### <a name=\"3\"></a>Dal BIM in Poi &ndash; Italian BIM\n\nIt is my pleasure to announce a new Italian AEC and BIM blog,\n[dal BIM in poi](http://blogs.autodesk.com/dalbiminpoi), by Ilaria Lagazio and Stefano Toparini.\n\n'Dal BIM in poi' means 'Beyond BIM'.\n\n*Stefano si occupa da molti anni di BIM per le Infrastrutture nonché di reti tecnologiche e di gestione del territorio, con esperienze professionali maturate sia in Italia che all'estero. Lavora nella filiale Italiana di Autodesk Inc. da oltre 10 anni dopo esperienze in varie altre aziende di informatica e servizi nel mondo della progettazione e delle pubbliche amministrazioni.*\n\nStefano has been working with BIM for Infrastructure and GIS for many years, with professional experience both in Italy and abroad. He has been with the Italian subsidiary of Autodesk Inc. for over 10 years after experiences in several other computer companies and services in the design and public administration domains.\n\n*Ilaria e Laureata in Ingegneria Civile e specializzata in Strutture, dopo una breve esperienza nel campo della progettazione si dedica all’industrializzazione dei sistemi edilizi come Building System Development Manager, gestendo il flusso delle informazioni dei componenti edilizi dal modello al cantiere. L’interesse per l’industrializzazione del cantiere e la gestione del dato progettuale la porta ad una esperienza negli Emirati Arabi e dal 2008 in Autodesk, dove oggi ricopre il ruolo di Senior Technical Sales Specialist.*\n\nIlaria graduated in civil engineering and specialised in structures. After a short experience in design she worked as Building System Development Manager, managing the information flow from BIM to construction site. Her interest in efficient construction site and project management took her to the UAE, and from 2008 onwards to Autodesk in the role as Senior Technical Sales Specialist.\n\nI wish the new blog and all its readers all the best and many exciting stories!"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"4\"></a>Determining Wall Opening Areas per Room",
    "local_header_href": "#a-name4adetermining-wall-opening-areas-per-room",
    "chunk_text": "#### <a name=\"4\"></a>Determining Wall Opening Areas per Room\n\nAs I pointed out last week in the preceding article on this topic, Håvard Dagsvik of the newly renamed Scandinavian AEC and BIM company [Symetri](http://www.symetri.com), previously CAD-Q, invested significant effort in enhancing our joint efforts to determine wall opening areas per room.\n\nHere are links to the previous discussions:\n\n- [Calculating gross and net wall areas](http://thebuildingcoder.typepad.com/blog/2015/03/calculating-gross-and-net-wall-areas.html)\n- [IFCExportUtils to determine the door and window area](http://thebuildingcoder.typepad.com/blog/2015/03/ifcexportutils-methods-determine-door-and-window-area.html)\n- [Determining wall cut area for a specific room](http://thebuildingcoder.typepad.com/blog/2016/04/determining-wall-cut-area-for-a-specific-room.html)\n\nThe results are captured in these two Revit add-in projects and GitHub repositories:\n\n- [SpatialElementGeometryCalculator](https://github.com/jeremytammik/SpatialElementGeometryCalculator)\n- [ExporterIfcUtilsWinArea](https://github.com/jeremytammik/ExporterIfcUtilsWinArea)"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"5\"></a>Håvard's SpatialElementGeometryCalculator Enhancement",
    "local_header_href": "#a-name5ahåvards-spatialelementgeometrycalculator-enhancement",
    "chunk_text": "#### <a name=\"5\"></a>Håvard's SpatialElementGeometryCalculator Enhancement\n\nI integrated Håvard's final running test code into\nthe [SpatialElementGeometryCalculator project](https://github.com/jeremytammik/SpatialElementGeometryCalculator) and\nam very happy to present the following results that you can now reproduce yourself as well.\n\nIn Håvard's own words:\n\nHere it is.\n\nSimplified and cleaned up.\n\nI couldn’t use the existing dictionary so I implemented a small class `SpatialBoundaryCache` to cache the core spatial data.\n\nI demonstrate how you can structure and present the resulting data, areas square metres, in three different ways:\n\n- By room\n- By wall type\n- By wall material\n\nMaterial is my choice because I need to know if the surface is plaster or concrete &ndash; note that walls can have different layers on each side.\n\nJust as before, I use both geometric analysis based on the wall solids as well as the IFC utility classes for the calculations.\n\nI removed the `GetAreaFromFamilyParameters` method because it is somewhat unreliable and I already use the IFC utils instead.\n\nI also used your `IsInRoom` method instead of mine.\n\nIn the long run, I think all of it will be just solid intersections also IsInRoom.\n\nBoth stacked walls and embedded curtain walls are handled, though probably not yet an embedded curtain wall within a stacked wall.\n\nThat could be solved following the same solid intersection logic.\n\nI am quite sure there is still room for improvement in the opening handler.\n\nTake a look and see what you make of it &nbsp; :-)\n\nI am attaching [the sample file](zip/SpatialElementGeometryCalculatorTest.rvt) that I worked with as well.\n\nMany thanks to Håvard for his research, hard work, and sharing this!\n\nI integrated Håvard's functionality in the\npublic  [SpatialElementGeometryCalculator GitHub project](https://github.com/jeremytammik/SpatialElementGeometryCalculator),\nin [release 2016.0.0.3](https://github.com/jeremytammik/SpatialElementGeometryCalculator/releases/tag/2016.0.0.3)."
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"6\"></a>External Command Mainline",
    "local_header_href": "#a-name6aexternal-command-mainline",
    "chunk_text": "#### <a name=\"6\"></a>External Command Mainline\n\nThe main execute method demonstrates how to:\n\n- Retrieve the rooms from the model\n- Run the `SpatialElementGeometryCalculator` calculator\n- Retrieve the results\n- Extract, sort and report the data\n\nHere is the complete implementation:\n\n<pre class=\"code\">\n<span class=\"blue\">public</span> <span class=\"teal\">Result</span> Execute(\n&nbsp; <span class=\"teal\">ExternalCommandData</span> commandData,\n&nbsp; <span class=\"blue\">ref</span> <span class=\"blue\">string</span> message,\n&nbsp; <span class=\"teal\">ElementSet</span> elements )\n{\n&nbsp; <span class=\"teal\">UIApplication</span> uiapp = commandData.Application;\n&nbsp; <span class=\"teal\">Document</span> doc = uiapp.ActiveUIDocument.Document;\n&nbsp; <span class=\"teal\">Result</span> rc;\n&nbsp;\n&nbsp; <span class=\"blue\">try</span>\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">SpatialElementBoundaryOptions</span> sebOptions\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">SpatialElementBoundaryOptions</span> {\n&nbsp; &nbsp; &nbsp; &nbsp; SpatialElementBoundaryLocation\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"teal\">SpatialElementBoundaryLocation</span>.Finish };\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">IEnumerable</span>&lt;<span class=\"teal\">Element</span>&gt; rooms\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">FilteredElementCollector</span>( doc )\n&nbsp; &nbsp; &nbsp; &nbsp; .OfClass( <span class=\"blue\">typeof</span>( <span class=\"teal\">SpatialElement</span> ) )\n&nbsp; &nbsp; &nbsp; &nbsp; .Where&lt;<span class=\"teal\">Element</span>&gt;( e =&gt; (e <span class=\"blue\">is</span> <span class=\"teal\">Room</span>) );\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">List</span>&lt;<span class=\"blue\">string</span>&gt; compareWallAndRoom = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"blue\">string</span>&gt;();\n&nbsp; &nbsp; <span class=\"teal\">OpeningHandler</span> openingHandler = <span class=\"blue\">new</span> <span class=\"teal\">OpeningHandler</span>();\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; lstSpatialBoundaryCache\n&nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt;();\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">Room</span> room <span class=\"blue\">in</span> rooms )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( room == <span class=\"blue\">null</span> ) <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( room.Location == <span class=\"blue\">null</span> ) <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( room.Area.Equals( 0 ) ) <span class=\"blue\">continue</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; Autodesk.Revit.DB.<span class=\"teal\">SpatialElementGeometryCalculator</span> calc =\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">new</span> Autodesk.Revit.DB.<span class=\"teal\">SpatialElementGeometryCalculator</span>(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; doc, sebOptions );\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">SpatialElementGeometryResults</span> results\n&nbsp; &nbsp; &nbsp; &nbsp; = calc.CalculateSpatialElementGeometry(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; room );\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">Solid</span> roomSolid = results.GetGeometry();\n&nbsp;\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">Face</span> face <span class=\"blue\">in</span> results.GetGeometry().Faces )\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">IList</span>&lt;<span class=\"teal\">SpatialElementBoundarySubface</span>&gt; boundaryFaceInfo\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = results.GetBoundaryFaceInfo( face );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"blue\">var</span> spatialSubFace <span class=\"blue\">in</span> boundaryFaceInfo )\n&nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( spatialSubFace.SubfaceType\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; != <span class=\"teal\">SubfaceType</span>.Side )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">SpatialBoundaryCache</span> spatialData\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = <span class=\"blue\">new</span> <span class=\"teal\">SpatialBoundaryCache</span>();\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">Wall</span> wall = doc.GetElement( spatialSubFace\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .SpatialBoundaryElement.HostElementId )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">as</span> <span class=\"teal\">Wall</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( wall == <span class=\"blue\">null</span> )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">WallType</span> wallType = doc.GetElement(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wall.GetTypeId() ) <span class=\"blue\">as</span> <span class=\"teal\">WallType</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( wallType.Kind == <span class=\"teal\">WallKind</span>.Curtain )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// Leave out, as curtain walls are not painted.</span>\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">LogCreator</span>.LogEntry( <span class=\"maroon\">&quot;WallType is CurtainWall&quot;</span> );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">continue</span>;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">HostObject</span> hostObject = wall <span class=\"blue\">as</span> <span class=\"teal\">HostObject</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">IList</span>&lt;<span class=\"teal\">ElementId</span>&gt; insertsThisHost\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; = hostObject.FindInserts(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">true</span>, <span class=\"blue\">false</span>, <span class=\"blue\">true</span>, <span class=\"blue\">true</span> );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">double</span> openingArea = 0;\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">ElementId</span> idInsert <span class=\"blue\">in</span> insertsThisHost )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span> countOnce = room.Id.ToString()\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; + wall.Id.ToString() + idInsert.ToString();\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">if</span>( !compareWallAndRoom.Contains( countOnce ) )\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"teal\">Element</span> elemOpening = doc.GetElement(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; idInsert ) <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; openingArea = openingArea\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; + openingHandler.GetOpeningArea(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wall, elemOpening, room, roomSolid );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; compareWallAndRoom.Add( countOnce );\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class=\"green\">// Cache SpatialElementBoundarySubface info.</span>\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialData.roomName = room.Name;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialData.idElement = wall.Id;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialData.idMaterial = spatialSubFace\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .GetBoundingElementFace().MaterialElementId;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialData.dblNetArea = <span class=\"teal\">Util</span>.sqFootToSquareM(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialSubFace.GetSubface().Area );\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; spatialData.dblOpeningArea = <span class=\"teal\">Util</span>.sqFootToSquareM(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; openingArea );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; lstSpatialBoundaryCache.Add( spatialData );\n&nbsp;\n&nbsp; &nbsp; &nbsp; &nbsp; } <span class=\"green\">// end foreach subface from which room bounding elements are derived</span>\n&nbsp;\n&nbsp; &nbsp; &nbsp; } <span class=\"green\">// end foreach Face</span>\n&nbsp;\n&nbsp; &nbsp; } <span class=\"green\">// end foreach Room</span>\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">List</span>&lt;<span class=\"blue\">string</span>&gt; t = <span class=\"blue\">new</span> <span class=\"teal\">List</span>&lt;<span class=\"blue\">string</span>&gt;();\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; groupedData\n&nbsp; &nbsp; &nbsp; = SortByRoom( lstSpatialBoundaryCache );\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">SpatialBoundaryCache</span> sbc <span class=\"blue\">in</span> groupedData )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; t.Add( sbc.roomName\n&nbsp; &nbsp; &nbsp; &nbsp; + <span class=\"maroon\">&quot;; all wall types and materials: &quot;</span>\n&nbsp; &nbsp; &nbsp; &nbsp; + sbc.AreaReport );\n&nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Util</span>.InfoMsg2( <span class=\"maroon\">&quot;Total Net Area in m2 by Room&quot;</span>,\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span>.Join(System.<span class=\"teal\">Environment</span>.NewLine, t ) );\n&nbsp;\n&nbsp; &nbsp; t.Clear();\n&nbsp;\n&nbsp; &nbsp; groupedData = SortByRoomAndWallType(\n&nbsp; &nbsp; &nbsp; lstSpatialBoundaryCache );\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">SpatialBoundaryCache</span> sbc <span class=\"blue\">in</span> groupedData )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"teal\">Element</span> elemWall = doc.GetElement(\n&nbsp; &nbsp; &nbsp; &nbsp; sbc.idElement ) <span class=\"blue\">as</span> <span class=\"teal\">Element</span>;\n&nbsp;\n&nbsp; &nbsp; &nbsp; t.Add( sbc.roomName + <span class=\"maroon\">&quot;; &quot;</span> + elemWall.Name\n&nbsp; &nbsp; &nbsp; &nbsp; + <span class=\"maroon\">&quot;(&quot;</span> + sbc.idElement.ToString() + <span class=\"maroon\">&quot;): &quot;</span>\n&nbsp; &nbsp; &nbsp; &nbsp; + sbc.AreaReport );\n&nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Util</span>.InfoMsg2( <span class=\"maroon\">&quot;Net Area in m2 by Wall Type&quot;</span>,\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span>.Join( System.<span class=\"teal\">Environment</span>.NewLine, t ) );\n&nbsp;\n&nbsp; &nbsp; t.Clear();\n&nbsp;\n&nbsp; &nbsp; groupedData = SortByRoomAndMaterial(\n&nbsp; &nbsp; &nbsp; lstSpatialBoundaryCache );\n&nbsp;\n&nbsp; &nbsp; <span class=\"blue\">foreach</span>( <span class=\"teal\">SpatialBoundaryCache</span> sbc <span class=\"blue\">in</span> groupedData )\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span> materialName\n&nbsp; &nbsp; &nbsp; &nbsp; = (sbc.idMaterial == <span class=\"teal\">ElementId</span>.InvalidElementId)\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ? <span class=\"blue\">string</span>.Empty\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : doc.GetElement( sbc.idMaterial ).Name;\n&nbsp;\n&nbsp; &nbsp; &nbsp; t.Add( sbc.roomName + <span class=\"maroon\">&quot;; &quot;</span> + materialName + <span class=\"maroon\">&quot;: &quot;</span>\n&nbsp; &nbsp; &nbsp; &nbsp; + sbc.AreaReport );\n&nbsp; &nbsp; }\n&nbsp;\n&nbsp; &nbsp; <span class=\"teal\">Util</span>.InfoMsg2(\n&nbsp; &nbsp; &nbsp; <span class=\"maroon\">&quot;Net Area in m2 by Outer Layer Material&quot;</span>,\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">string</span>.Join( System.<span class=\"teal\">Environment</span>.NewLine, t ) );\n&nbsp;\n&nbsp; &nbsp; rc = <span class=\"teal\">Result</span>.Succeeded;\n&nbsp; }\n&nbsp; <span class=\"blue\">catch</span>( <span class=\"teal\">Exception</span> ex )\n&nbsp; {\n&nbsp; &nbsp; <span class=\"teal\">TaskDialog</span>.Show( <span class=\"maroon\">&quot;Room Boundaries&quot;</span>,\n&nbsp; &nbsp; &nbsp; ex.Message + <span class=\"maroon\">&quot;\\r\\n&quot;</span> + ex.StackTrace );\n&nbsp;\n&nbsp; &nbsp; rc = <span class=\"teal\">Result</span>.Failed;\n&nbsp; }\n&nbsp; <span class=\"blue\">return</span> rc;\n}\n&nbsp;\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;summary&gt;</span>\n<span class=\"gray\">///</span><span class=\"green\"> Convert square feet to square meters</span>\n<span class=\"gray\">///</span><span class=\"green\"> with two decimal places precision.</span>\n<span class=\"gray\">///</span><span class=\"green\"> </span><span class=\"gray\">&lt;/summary&gt;</span>\n<span class=\"blue\">static</span> <span class=\"blue\">double</span> SqFootToSquareM( <span class=\"blue\">double</span> sqFoot )\n{\n&nbsp; <span class=\"blue\">return</span> <span class=\"teal\">Math</span>.Round( sqFoot * 0.092903, 2 );\n}\n&nbsp;\n<span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; SortByRoom(\n&nbsp; <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; lstRawData )\n{\n&nbsp; <span class=\"blue\">var</span> sortedCache\n&nbsp; &nbsp; = <span class=\"blue\">from</span> rawData <span class=\"blue\">in</span> lstRawData\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">group</span> rawData <span class=\"blue\">by</span> <span class=\"blue\">new</span> { room = rawData.roomName }\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">into</span> sortedData\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">select</span> <span class=\"blue\">new</span> <span class=\"teal\">SpatialBoundaryCache</span>()\n&nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; roomName = sortedData.Key.room,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; idElement = <span class=\"teal\">ElementId</span>.InvalidElementId,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblNetArea = sortedData.Sum( x =&gt; x.dblNetArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblOpeningArea = sortedData.Sum(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; y =&gt; y.dblOpeningArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; };\n&nbsp;\n&nbsp; <span class=\"blue\">return</span> sortedCache.ToList();\n}\n&nbsp;\n<span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; SortByRoomAndWallType(\n&nbsp; <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; lstRawData )\n{\n&nbsp; <span class=\"blue\">var</span> sortedCache\n&nbsp; &nbsp; = <span class=\"blue\">from</span> rawData <span class=\"blue\">in</span> lstRawData\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">group</span> rawData <span class=\"blue\">by</span> <span class=\"blue\">new</span>\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; room = rawData.roomName,\n&nbsp; &nbsp; &nbsp; &nbsp; wallid = rawData.idElement\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">into</span> sortedData\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">select</span> <span class=\"blue\">new</span> <span class=\"teal\">SpatialBoundaryCache</span>()\n&nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; roomName = sortedData.Key.room,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; idElement = sortedData.Key.wallid,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblNetArea = sortedData.Sum( x =&gt; x.dblNetArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblOpeningArea = sortedData.Sum(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; y =&gt; y.dblOpeningArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; };\n&nbsp;\n&nbsp; <span class=\"blue\">return</span> sortedCache.ToList();\n}\n&nbsp;\n<span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; SortByRoomAndMaterial(\n&nbsp; <span class=\"teal\">List</span>&lt;<span class=\"teal\">SpatialBoundaryCache</span>&gt; lstRawData )\n{\n&nbsp; <span class=\"blue\">var</span> sortedCache\n&nbsp; &nbsp; = <span class=\"blue\">from</span> rawData <span class=\"blue\">in</span> lstRawData\n&nbsp; &nbsp; &nbsp; <span class=\"blue\">group</span> rawData <span class=\"blue\">by</span> <span class=\"blue\">new</span>\n&nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; room = rawData.roomName,\n&nbsp; &nbsp; &nbsp; &nbsp; mid = rawData.idMaterial\n&nbsp; &nbsp; &nbsp; }\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">into</span> sortedData\n&nbsp; &nbsp; &nbsp; &nbsp; <span class=\"blue\">select</span> <span class=\"blue\">new</span> <span class=\"teal\">SpatialBoundaryCache</span>()\n&nbsp; &nbsp; &nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; roomName = sortedData.Key.room,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; idMaterial = sortedData.Key.mid,\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblNetArea = sortedData.Sum( x =&gt; x.dblNetArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dblOpeningArea = sortedData.Sum(\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; y =&gt; y.dblOpeningArea ),\n&nbsp; &nbsp; &nbsp; &nbsp; };\n&nbsp;\n&nbsp; <span class=\"blue\">return</span> sortedCache.ToList();\n}\n</pre>"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"7\"></a>Test Run",
    "local_header_href": "#a-name7atest-run",
    "chunk_text": "#### <a name=\"7\"></a>Test Run\n\nHere are the results from a test run on the sample model provided:\n\nThe simple test model looks like this in plan view:\n\n<center>\n<img src=\"img/SpatialElementGeometryCalculator1Test.png\" alt=\"Test model plan view\" width=\"400\">\n</center>\n\nIn 3D view, you can see the stacked wall and the opening spanning several different spaces:\n\n<center>\n<img src=\"img/SpatialElementGeometryCalculator2Test3d.png\" alt=\"Test model 3D view\" width=\"400\">\n</center>\n\nThe results sorted by room, wall type and material are presented in three sequential task dialogues.\n\nThe first one, by room, is the simplest:\n\n<center>\n<img src=\"img/SpatialElementGeometryCalculator6AreaByRoom2.png\" alt=\"Net, opening and gross area by room\" width=\"366\">\n</center>\n\nEach room is bounded by several different wall types:\n\n<center>\n<img src=\"img/SpatialElementGeometryCalculator7AreaByWallType2.png\" alt=\"Net, opening and gross area by wall type\" width=\"446\">\n</center>\n\nFinally, here are the areas grouped by material:\n\n<center>\n<img src=\"img/SpatialElementGeometryCalculator8AreaByMaterial2.png\" alt=\"Net, opening and gross area by material\" width=\"389\">\n</center>\n\nFor the sake of the search engines and legibility, here are the same results in text form as well, as reported on the Visual Studio debug console:\n\n<pre>\nTotal Net Area in m2 by Room\n\nRoom 3; all wall types and materials: net 150; opening 9.2; gross 159.2\nRoom 5; all wall types and materials: net 42; opening 3.97; gross 45.97\nRoom 6; all wall types and materials: net 120; opening 7; gross 127\nRoom 7; all wall types and materials: net 120; opening 2; gross 122\n\nNet Area in m2 by Wall Type\n\nRoom 3; Exterior - Block on Mtl. Stud(308814): net 30; opening 0; gross 30\nRoom 3; CW 102-85-215p(309825): net 45; opening 4; gross 49\nRoom 3; Wall4(310052): net 30; opening 0; gross 30\nRoom 3; Wall1(308815): net 45; opening 5.2; gross 50.2\nRoom 5; Wall1(308815): net 9; opening 1.97; gross 10.97\nRoom 5; Exterior - Block on Mtl. Stud(311213): net 3.6; opening 0.9; gross 4.5\nRoom 5; Exterior - Brick on Mtl. Stud(311214): net 8.4; opening 1.1; gross 9.5\nRoom 5; Wall1(310409): net 9; opening 0; gross 9\nRoom 5; Generic - 225mm Masonry(308816): net 12; opening 0; gross 12\nRoom 6; Exterior - Block on Mtl. Stud(308814): net 30; opening 0; gross 30\nRoom 6; Wall1(308815): net 30; opening 3; gross 33\nRoom 6; Generic - 225mm Masonry(308816): net 30; opening 2; gross 32\nRoom 6; Wall3(308817): net 30; opening 2; gross 32\nRoom 7; Exterior - Block on Mtl. Stud(308814): net 30; opening 0; gross 30\nRoom 7; Wall3(308817): net 30; opening 2; gross 32\nRoom 7; Generic - 225mm Masonry(308816): net 30; opening 0; gross 30\nRoom 7; Generic - 225mm Masonry(309758): net 30; opening 0; gross 30\n\nNet Area in m2 by Outer Layer Material\n\nRoom 3; Gypsum Wall Board: net 75; opening 4; gross 79\nRoom 3; Default Wall: net 75; opening 5.2; gross 80.2\nRoom 5; Default Wall: net 18; opening 1.97; gross 19.97\nRoom 5; Gypsum Wall Board: net 12; opening 2; gross 14\nRoom 5; Concrete Masonry Units: net 12; opening 0; gross 12\nRoom 6; Gypsum Wall Board: net 30; opening 0; gross 30\nRoom 6; Default Wall: net 60; opening 5; gross 65\nRoom 6; Concrete Masonry Units: net 30; opening 2; gross 32\nRoom 7; Gypsum Wall Board: net 30; opening 0; gross 30\nRoom 7; Default Wall: net 30; opening 2; gross 32\nRoom 7; Concrete Masonry Units: net 60; opening 0; gross 60\n</pre>\n\nWonderful, isn't it?\n\nThank you again, Håvard!"
  },
  {
    "original_filename": "1423_wall_opening_areas",
    "header_text": "<a name=\"8\"></a>Addendum",
    "local_header_href": "#a-name8aaddendum",
    "chunk_text": "#### <a name=\"8\"></a>Addendum\n\n[Zhbing0322](https://github.com/zhbing0322) added\na [comment](https://github.com/jeremytammik/SpatialElementGeometryCalculator/commit/18ebcd1283bf64a595505871987c3089d53037e6#commitcomment-19391593) on\na [commit](https://github.com/jeremytammik/SpatialElementGeometryCalculator/commit/18ebcd1283bf64a595505871987c3089d53037e6):\n\n> The result of `spatialSubFace.GetSubface().Area` is the Gross area of the Wall in a room."
  }
]