[
  {
    "original_filename": "1474_flip_section_view",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<title>The Building Coder</title>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"3dwc.css\"/>\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true\" defer=\"defer\"></script>\n</head>\n\n<!---\n\n12177368 [创建剖面视图时遇到的问题 -- When you create a cross-sectional view of the problems encountered]\n\nFlipping a Section View and @AutodeskForge Webinar 3 #revitapi #3dwebcoder @AutodeskRevit #aec #bim\n\nI already created a starting point for the new roomedit3d incarnation last week, in its own repository. This week, I agreed with Philippe to retain the new project in an own branch within the Forge boilerplate code sample collection. Hopefully, that will simplify keeping my BIM sample synchronised with any future updates make to that. Now I need to get started implementing and testing the actual viewer extension functionality itself. My main topic today is something different and purely Revit API oriented, besides the next Forge session\n&ndash; Flipping a section view\n&ndash; Forge webinar series...\n\n-->"
  },
  {
    "original_filename": "1474_flip_section_view",
    "header_text": "Flipping a Section View and Forge Webinar 3",
    "local_header_href": "#flipping-a-section-view-and-forge-webinar-3",
    "chunk_text": "### Flipping a Section View and Forge Webinar 3\n\nI already created a starting point for the\nnew [roomedit3d](https://github.com/jeremytammik/roomedit3d) incarnation\nlast week, in its own\nrepository [roomedit3dv3](https://github.com/jeremytammik/roomedit3dv3).\n\nHowever, please forget that right away.\n\nThis week, I agreed with Philippe to retain the new project in an own\ndedicated [roomedit3d branch](https://github.com/Autodesk-Forge/forge-boilers.nodejs/tree/roomedit3d) within his\noriginal [Forge boilerplate code sample collection](https://github.com/Autodesk-Forge/forge-boilers.nodejs).\n\nHopefully, that will simplify keeping my BIM sample synchronised with any future updates make to that.\n\nNow I need to get started implementing and testing the actual viewer extension functionality itself.\n\nMy main topic today is something different and purely Revit API oriented, besides the next Forge session:\n\n- [Flipping a section view](#2)\n- [Forge webinar series](#3)"
  },
  {
    "original_filename": "1474_flip_section_view",
    "header_text": "<a name=\"2\"></a>Flipping a Section View",
    "local_header_href": "#a-name2aflipping-a-section-view",
    "chunk_text": "#### <a name=\"2\"></a>Flipping a Section View\n\nHere is a recent interesting little case handled by Jim Jia and answered by Paolo Serra:\n\n**Question:** I want to create a new model with a section view based on an existing one with the same cross-sectional view but a different crop box.\n\nTo do so, I perform, these steps:\n\n1. Open the old model file, find the required cross-sectional view.\n\n2. Create a new model within the same bounding box, using the old model view CropBox created like this:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;transform&nbsp;=&nbsp;view.CropBox.Transform;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;box&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>();\n&nbsp;&nbsp;box.Enabled&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;maxPoint&nbsp;=&nbsp;view.CropBox.Max;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;minPoint&nbsp;=&nbsp;view.CropBox.Min;\n&nbsp;&nbsp;box.Transform&nbsp;=&nbsp;transform;\n&nbsp;&nbsp;box.Max&nbsp;=&nbsp;maxPoint;\n&nbsp;&nbsp;box.Min&nbsp;=&nbsp;minPoint;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>&nbsp;viewSection&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>.CreateSection(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;doc,&nbsp;view.GetTypeId(),&nbsp;box&nbsp;);\n</pre>\n\nThis works and I can create a cross-sectional view through this method, but in the opposite direction of the existing view, like this:\n\n<center>\n<img src=\"img/viewsection_flipped.png\" alt=\"Section view flipped\" width=\"515\">\n</center>\n\nHow can I flip the view direction to solve this problem?\n\n**Answer:** A few days ago I was trying to do the same.\n\nWhat worked for me was to reverse the `RightDirection` vector of the original view and recreate a transform to apply to the `BoundingBoxXYZ`.\n\nYou should also take into consideration the different transforms you might have in the two documents.\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;tr&nbsp;=&nbsp;view.CropBox.Transform;\n \n&nbsp;&nbsp;tr.BasisX&nbsp;=&nbsp;-view.RightDirection;\n&nbsp;&nbsp;tr.BasisY&nbsp;=&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisZ;\n&nbsp;&nbsp;tr.BasisZ&nbsp;=&nbsp;tr.BasisX.CrossProduct(&nbsp;tr.BasisY&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;bb&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>();\n&nbsp;&nbsp;bb.Transform&nbsp;=&nbsp;tr;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;min&nbsp;=&nbsp;view.CropBox.Min;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;max&nbsp;=&nbsp;view.CropBox.Max;\n&nbsp;&nbsp;bb.Min&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;min.X,&nbsp;min.Y,&nbsp;0&nbsp;);\n&nbsp;&nbsp;bb.Max&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;max.X,&nbsp;max.Y,&nbsp;-min.Z&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;vftId&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;.Cast&lt;<span style=\"color:#2b91af;\">ViewFamilyType</span>&gt;()\n&nbsp;&nbsp;&nbsp;&nbsp;.First(&nbsp;x&nbsp;=&gt;&nbsp;x.ViewFamily&nbsp;==&nbsp;<span style=\"color:#2b91af;\">ViewFamily</span>.Section&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Id;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;newView&nbsp;=&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>.CreateSection(&nbsp;doc,&nbsp;vftId,&nbsp;bb&nbsp;);\n</pre>\n\n**Response:** Thanks a lot, it works!\n\nMany thanks to Jim and Paolo for sharing this!"
  },
  {
    "original_filename": "1474_flip_section_view",
    "header_text": "<a name=\"3\"></a>Forge Webinar Series",
    "local_header_href": "#a-name3aforge-webinar-series",
    "chunk_text": "#### <a name=\"3\"></a>Forge Webinar Series\n\nTomorrow we are presenting the third session in the ongoing Forge webinar series, on the Model Derivative API.\n\nSupport documentation and recordings from the first two sessions for your future reference and enjoyment:\n\n- September 20 [Introduction to Autodesk Forge and the Autodesk App Store](http://adndevblog.typepad.com/cloud_and_mobile/2016/09/introduction-to-autodesk-forge-and-the-autodesk-app-store.html)\n- September 22 [Introduction to OAuth and Data Management API](http://adndevblog.typepad.com/cloud_and_mobile/2016/09/introduction-to-oauth-and-data-management-api.html)\n&ndash; on [OAuth](https://developer.autodesk.com/en/docs/oauth/v2/overview)\nand [Data Management API](https://developer.autodesk.com/en/docs/data/v2/overview), providing token-based authentication, authorization and a unified and consistent way to access data across A360, Fusion 360, and the Object Storage Service.\n\nUpcoming sessions continuing during the remainder of\nthe [Autodesk App Store Forge and Fusion 360 Hackathon](http://autodeskforge.devpost.com) until the end of October:\n\n- September 27 &ndash; [Model Derivative API](https://developer.autodesk.com/en/docs/model-derivative/v2/overview) &ndash; enable users to represent and share their designs in different formats and extract metadata.\n- September 29 &ndash; [Viewer API](https://developer.autodesk.com/en/docs/viewer/v2/overview) &ndash; \nformerly part of the 'View and Data API', a WebGL-based, JavaScript library for 3D and 2D model rendering a CAD data from seed models, e.g., [AutoCAD](http://www.autodesk.com/products/autocad/overview), [Fusion 360](http://www.autodesk.com/products/fusion-360/overview), [Revit](http://www.autodesk.com/products/revit-family/overview), and many other formats.\n- October 4 &ndash; [Design Automation API](https://developer.autodesk.com/en/docs/design-automation/v2/overview) &ndash; formerly known as 'AutoCAD I/O', run scripts on design files.\n- October 6 &ndash; [BIM360](https://developer.autodesk.com/en/docs/bim360/v1/overview) &ndash; develop apps that integrate with BIM 360 to extend its capabilities in the construction ecosystem.\n- October 11 &ndash; [Fusion 360 Client API](http://help.autodesk.com/view/NINVFUS/ENU/?guid=GUID-A92A4B10-3781-4925-94C6-47DA85A4F65A) &ndash; an integrated CAD, CAM, and CAE tool for product development, built for the new ways products are designed and made.\n- October 13 &ndash; Q&A on all APIs.\n- October 20 &ndash; Q&A on all APIs.\n- October 27 &ndash; Submitting a web service app to Autodesk App store.\n\n<center>\n<img src=\"img/forge_accelerator.png\" alt=\"Forge &ndash; build the future of making things together\" width=\"400\">\n</center>"
  }
]