[
  {
    "original_filename": "1519_model_vert_align_cs",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!--\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n- add to 'select all model elements'\n  http://forums.autodesk.com/t5/revit-api-forum/select-all-physical-items-in-model/m-p/6822940\n  \n- 12566528 [Textnote - vertical alignment on line i Revit 2016?]\n  http://forums.autodesk.com/t5/revit-api-forum/textnote-vertical-alignment-on-line-i-revit-2016/m-p/6810367\n\n- 2016 issues: vertical text alignment missing and setbarresults modification\n  comments by David Rushforth on whats-new-in-the-revit-2016-api:\n  http://thebuildingcoder.typepad.com/blog/2015/04/whats-new-in-the-revit-2016-api.html#comment-6a00e553e16897883301bb08261e9a970d\n  http://thebuildingcoder.typepad.com/blog/2015/04/add-in-migration-to-revit-2016-and-updated-wizards.html?cid=6a00e553e16897883301bb08264ea1970d#comment-6a00e553e16897883301bb08264ea1970d\n  10707501 [Text Note VerticalAlignment  is Read Only]\n  rvt65682 [VerticalAlignment is read-only]\n  http://forums.autodesk.com/t5/revit-api/creating-a-textnote-with-the-2016-api-changes/m-p/5629284\n  http://forums.autodesk.com/t5/revit-api/text-alignments/m-p/6272246\n  11708648 [Text alignments]\n  12566528 [Textnote - vertical alignment on line i Revit 2016?]\n  http://forums.autodesk.com/t5/revit-api-forum/textnote-vertical-alignment-on-line-i-revit-2016/m-p/6810367\n\n- pyRevit Idea: Add support for C# assemblies #143 -- https://github.com/eirannejad/pyRevit/issues/143 \n\n#RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge\n\nHappy New Year of the Rooster!\nThe Spring Festival is underway celebrating the Chinese New Year.\nMeanwhile, we continue our usual ongoing celebration of exciting Revit API news items\n&ndash; PyRevit dynamic <code>cs</code> script loader\n&ndash; Selecting all physical elements in model\n&ndash; Vertical <code>TextNote</code> alignment...\n\n#AULondon, #UI, #innovation, #RevitAPI, @AutodeskRevit\n\nDynamic Scripts, Model Elements and Vertical Alignment #RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge\n\nhttp://bit.ly/cs_phys_el_vert_al\n\n-->"
  },
  {
    "original_filename": "1519_model_vert_align_cs",
    "header_text": "Dynamic Scripts, Model Elements and Vertical Alignment",
    "local_header_href": "#dynamic-scripts-model-elements-and-vertical-alignment",
    "chunk_text": "### Dynamic Scripts, Model Elements and Vertical Alignment\n\nHappy New Year of the Rooster!\n\n<center>\n<!----\n<iframe width='480' height='360' frameborder='0' allowfullscreen\nsrc='http://player.ooyala.com/static/v4/stable/4.7.9/skin-plugin/iframe.html?ec=42Njdmazp8OPIKJRyChESz2RevNqe2aQ&pbid=ZTIxYmJjZDM2NWYzZDViZGRiOWJjYzc5&pcode=RvbGU6Z74XE_a3bj4QwRGByhq9h2'></iframe>\n---->\n<img src=\"img/year_of_the_rooster_2017.jpeg\" alt=\"Happy New Year of the Rooster!\" width=\"327\"/>\n</center>\n\nThe Spring Festival is underway celebrating \nthe [Chinese New Year](https://en.wikipedia.org/wiki/Chinese_New_Year) and \nanother [year of the Rooster](https://en.wikipedia.org/wiki/Rooster_(zodiac)),\ncf. e.g. [The Telegraph newspaper article](http://www.telegraph.co.uk/news/0/chinese-new-year/) covering all these aspects:\n\n- Popular Chinese New Year greetings\n- The personality of the Rooster\n- Lucky Signs for the Rooster\n- Which Chinese zodiac sign are you?\n- What does your Chinese zodiac sign mean?\n- Chinese New Year's Day taboos\n- When does the party start?\n\nMeanwhile, we continue our usual ongoing celebration of exciting Revit API news items:\n\n- [PyRevit dynamic `cs` script loader](#2)\n- [Selecting all physical elements in model](#3)\n- [Vertical `TextNote` alignment](#4)\n\n\n####<a name=\"2\"></a>PyRevit Dynamic `cs` Script Loader\n\n[Ehsan Iran-Nejad](https://github.com/eirannejad) announces happy news on \n[pyRevit](https://github.com/eirannejad/pyRevit), which provides support for IronPython scripts and an add-in tab in Revit.\n\nThe [idea #143 &ndash; add support for C# assemblies](https://github.com/eirannejad/pyRevit/issues/143#issuecomment-272913198) is\nalready implemented:\n\n**Idea:** I would like to propose adding support for loading C# assemblies.\n\nTo elaborate:\n\nInstead of executing a Python script, a button would dynamically load and execute an `IExternalCommand` from a C# assembly, a bit like the Revit SDK Add-in Manager.\n\n**Answer:** I'm glad you mentioned this.\n\npyRevit currently supports C# scripts.\n\nIt compiles them at runtime and creates executable commands for `IExternalCommand`.\n\nIt also supports `IExternalCommandAvailability`.\n\nJust as with the Add-In Manager, you can modify the C# code on the fly and reload pyRevit without closing the current Revit session.\n\nLook at the button bundle listed below.\n\nIt only has a `.cs` file instead of a `.py` file.\n\nThis is a work-in-progress feature and thus not announced yet, but technically you can create C# bundles right now already.\n\nThe unfinished component of this feature is that I need to make the compiler smart about the assemblies it needs to reference for the C# script to work.\n\nCurrently, it references these assemblies by default, which is more than enough for most commands:\n\n- RevitAPI\n- RevitAPIUI\n- IronPython\n- IronPython.Modules\n- Microsoft.Dynamic\n- Microsoft.Scripting\n- Microsoft.CSharp\n- System\n- System.Core\n- System.Drawing\n- System.Windows.Forms\n- PresentationCore\n- PresentationFramework\n- WindowsBase\n\nHere is [the bundle folder to `Test C# Script.pushbutton`](https://github.com/eirannejad/pyRevit/blob/master/extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Labs.pulldown/Test%20C%23%20Script.pushbutton/script.cs).\n\n\n\n####<a name=\"3\"></a>Selecting all Physical Elements in Model\n\nHere is yet another new solution \nfor [using `FilteredElementCollector` to select model elements, i.e., visible 3D elements](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.9b),\nfrom the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api/bd-p/160) thread \non [selecting all physical items in model](http://forums.autodesk.com/t5/revit-api-forum/select-all-physical-items-in-model/m-p/6822940):\n\n**Question:** I am trying to select all the model element instances in my model. i.e. anything that is a physical object, so I can change the value of a certain property on them. The property value will be different depending on where the instance is in the model. I have the below method but it is not picking up host families or the likes of ducts:\n\n<pre class=\"code\">\n<span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;GetFamilyInstanceModelElements(&nbsp;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementClassFilter</span>&nbsp;familyInstanceFilter&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ElementClassFilter</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;)&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;familyInstanceCollector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;elementsCollection&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;familyInstanceCollector.WherePasses(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;familyInstanceFilter&nbsp;).ToElements();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;modelElements&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;<span style=\"color:blue;\">in</span>&nbsp;elementsCollection&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;e.Category&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&amp;&amp;&nbsp;(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;e.LevelId&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&amp;&amp;&nbsp;(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;e.get_Geometry(&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Options</span>()&nbsp;)&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;modelElements.Add(&nbsp;e&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;modelElements;\n}\n</pre>\n\n**Answer 1:** Your filter looks OK to me.\n\nPlease note that the conversion from the `familyInstanceCollector` to the generic list `elementsCollection` is unnecessary and inefficient, as explained numerous times in the past, e.g.\nin the discussions \nof [`ToElementIds` performance](http://thebuildingcoder.typepad.com/blog/2012/12/toelementids-performance.html)\nand [use of LINQ with filtered element collectors](http://thebuildingcoder.typepad.com/blog/2015/12/quick-slow-and-linq-element-filtering.html#2).\n \nPlease also look at The Building Coder topic group\non [using `FilteredElementCollector` to select model elements, i.e., visible 3D elements](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.9b).\n\n**Answer 2:** When you  use a `FamilyInstance` filter, you only find user created families, i.e., RFA-based, and not the built-in system families.\n \nTry:\n\n<pre class=\"code\">\n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">class</span>&nbsp;<span style=\"color:#2b91af;\">JtElementExtensionMethods</span>\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">bool</span>&nbsp;IsPhysicalElement(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">this</span>&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;e.Category&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">false</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;e.ViewSpecific&nbsp;)&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">false</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;exclude&nbsp;specific&nbsp;unwanted&nbsp;categories</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;(&nbsp;(<span style=\"color:#2b91af;\">BuiltInCategory</span>)&nbsp;e.Category.Id.IntegerValue&nbsp;)&nbsp;==&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_HVAC_Zones&nbsp;)&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">false</span>;\n&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;e.Category.CategoryType&nbsp;==&nbsp;<span style=\"color:#2b91af;\">CategoryType</span>.Model&nbsp;&amp;&amp;&nbsp;e.Category.CanAddSubcategory;\n&nbsp;&nbsp;}\n}\n\n<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;SelectAllPhysicalElements(\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;.Where(&nbsp;e&nbsp;=&gt;&nbsp;e.IsPhysicalElement()&nbsp;);\n}\n</pre>\n\n**Answer 3:** I'd probably use `.WhereElementIsViewIndependent` in there somewhere also.\n\nFaster than some of the iteration/LINQ methods, cf. the comparison\nof [quick, slow and LINQ element filtering](http://thebuildingcoder.typepad.com/blog/2015/12/quick-slow-and-linq-element-filtering.html).\n\nExtracting element data from Revit to .NET and checking it there, e.g., with LINQ, costs at least twice as much time as leaving it on the Revit side and applying some kind of filter instead.\n \nTherefore, whenever possible, it pays off hugely to analyse all the element properties and how they are reflected in parameter values.\n \nThe parameter values can be filtered using a filtered element collector parameter filter.\n \n[50% speed improvement over using LINQ post-processing guaranteed](http://thebuildingcoder.typepad.com/blog/2010/06/element-name-parameter-filter-correction.html)!\n\nI added these new model element selection methods \nto [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples),\nimplementing [`SelectAllPhysicalElements` in release 2017.0.132.1](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2017.0.132.1) and\nadding the [`WhereElementIsViewIndependent` check in release 2017.0.132.2](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2017.0.132.2).\n\n**Answer 4:** I agree that you should use the `WhereElementIsViewIndependent` filter instead of checking `Element.ViewSpecific`.\n\nThe rest of the checks in the `IsPhysicalElement` predicate check properties of the `Element.Category` and I think those can't be filtered in a fast filter.\n \nAn alternative approach would be to define your own set of categories (maybe 20-30).\nAll elements in the 'physical' model would belong to that set, if you have defined it correctly.\nThen you can use an `ElementMulticategoryFilter` combined with `WhereElementIsNotElementType` and `WhereElementIsViewIndependent`.\n\nMany thanks to Frank 'Fair59' and Matt Taylor for the good suggestions!\n\n\n####<a name=\"4\"></a>Vertical TextNote Alignment\n\nThis is a continuation of\nthe [`TextNote` rotation issue](http://thebuildingcoder.typepad.com/blog/2017/01/textnote-rotation-forge-devcon-tensorflow-and-keras.html#3) discussed\nlast week, raised in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api/bd-p/160) thread \non [`TextNote` vertical alignment on line in Revit 2016](http://forums.autodesk.com/t5/revit-api-forum/textnote-vertical-alignment-on-line-i-revit-2016/m-p/6810367):\n\n**Question:**\n\nI've managed to position text notes rotated along lines.\n\n<center>\n<img src=\"img/rotate_text.png\" alt=\"Rotate text\" width=\"400\"/> <!-- 754 -->\n</center>\n \nNow I need to set the vertical alignment of the text, so the text is centred on the lines like this:\n\n<center>\n<img src=\"img/rotate_text_aligned.png\" alt=\"Rotate text\" width=\"400\"/> <!-- 623 -->\n</center>\n\nIn Revit 2015 I used the `TextAlignFlags.TEF_ALIGN_MIDDLE`, but it seems to be removed in 2016.\n \nIs there method to align the vertical position of the text, or do I have to calculate a new position of the text according to its height and scale?\n\n**Answer 1:**\n\n<b><i>&lt;`rant`&gt;</i></b>\n\nThe (frustrating) omission of the vertical text alignment mimics the user interface. Gah.\n\nLabels in tag families do have a modifiable vertical alignment, but these can't often be rotated. Gah.\n \nSo you're in the frustrating position of working out the text position manually. Gah.\n \nEnough to drive you gaga? ;-)\n\n<!----\n\nHere are some other examples of people running into this issue:\n\n2016 issues: vertical text alignment missing and setbarresults modification \n\n- [Comments by David Rushforth](http://thebuildingcoder.typepad.com/blog/2015/04/whats-new-in-the-revit-2016-api.html#comment-6a00e553e16897883301bb08261e9a970d)\non [What's New in the Revit 2016 API](http://thebuildingcoder.typepad.com/blog/2015/04/whats-new-in-the-revit-2016-api.html)\n- [Comment by ... ](http://thebuildingcoder.typepad.com/blog/2015/04/add-in-migration-to-revit-2016-and-updated-wizards.html?cid=6a00e553e16897883301bb08264ea1970d#comment-6a00e553e16897883301bb08264ea1970d)\non [xxx](http://thebuildingcoder.typepad.com/blog/2015/04/add-in-migration-to-revit-2016-and-updated-wizards.html)\n- [creating-a-textnote-with-the-2016-api-changes](http://forums.autodesk.com/t5/revit-api/creating-a-textnote-with-the-2016-api-changes/m-p/5629284)\n- [text-alignments](http://forums.autodesk.com/t5/revit-api/text-alignments/m-p/6272246)\n \n---->\n\nIt seems to me that the Revit developers have a mandate to stay away from simple drawing objects such as lines and text, and lean towards smarter objects like line-based families and tags. I commend that (if that is what is happening), but it also drives me nuts at times.\n\n<b><i>&lt;`/rant`&gt;</i></b>\n \nI was in the situation you are in. I ended up creating a line-based family with a nested annotation symbol in it. I needed to programmatically manage some of the family placement/scale etc. The bonus of this was that it allowed the user to modify the lines once placed (without needing an iUpdater to do so).\n \nIf you just want text, you may be able to get away with getting the centre of the text bounding box and moving it to the midpoint of your line. You'll probably need two transactions to do that.\n\n**Answer 2:**\n\nVery sorry about the frustrating situation.\n \nHave you raised a wish list for this in the Revit Idea Station?\n \nYou might get a lot of votes for that one.\n \nNow to go on with the topic at hand.\n \nIt has been discussed here in the past in the thread\non [text alignments](http://forums.autodesk.com/t5/revit-api/text-alignments/m-p/6272246).\n \nApparently, as far as the development team is concerned, the vertical alignment possibility should never have been implemented.\n \nArnošt Löbel explained that in detail in a discussion thread\non [creating a text note with the 2016 API changes](http://forums.autodesk.com/t5/revit-api/creating-a-textnote-with-the-2016-api-changes/m-p/5629284).\n \nPlease also refer to the comments by David Rushforth on [What's New in the Revit 2016 API](http://thebuildingcoder.typepad.com/blog/2015/04/whats-new-in-the-revit-2016-api.html).\n \nCan you check these out and see whether they help?\n \nI do hope we can resolve this somehow, because this request has cropped up a few times now.\n\nIs it possible to achieve what you show in your second figure using a custom line type?\n \nHere are two solutions that come up immediately in an Internet search:\n \n- [Creating linetype with text to represent utility and fence lines](https://knowledge.autodesk.com/support/revit-products/troubleshooting/caas/sfdcarticles/sfdcarticles...)\n- [YouTube video in Russian](https://www.youtube.com/watch?v=swR-zJkc1fQ)\n\n**Response:**\n\nFor now, I prefer to use simple text notes, as these texts are only used for sheet views.\n \nAlso, some users might need to delete or move a text element, to give way for more important geometry.\n \nThanks for the idea about getting values from the text bounding box. That's probably the best way of calculating the offset distance.\n \nI'm not using detail lines. The lines shown are actually pipe system, shown with single line representation.\n \nA line based family is too constricted for our needs.\n\n**Answer 3:**\n\nThe discussions you point to don't help me understand why vertical alignment isn't included in either the UI or the API.\n\nIf Revit could do everything as a user would want it, text wouldn't exist. It would all be internal/external databases, tags, references etc. That is not the case.\n\nSo, a user (or programmer) must be able to add text that can be positioned in a manner that editing the text element's content doesn't make it wrap in an undesirable way.\n \nThere are 21 ideas in the Idea Station using the search 'text alignment'.\n\nWhile the 'no vertical alignment' stance may make sense from an Autodesk point of view, it makes zero sense from a user viewpoint. Any user would have told the development team that. The 21 ideas voice this also.\n \nI've been using the Revit API since Revit 2011.\n\nOriginally, I was like, I'll use `TextNoteCreationData` to batch create text, because that'll be faster than creating them individually (after some testing).\n\nThat got deprecated in Revit 2013 and obsoleted in Revit 2014.\n\nIn Revit 2013, the `NewTextNote` creation method was heralded as being as efficient as the batch method.\n\nThen that was deprecated in Revit 2016, and obsoleted in Revit 2017.\n\nIn Revit 2016, enter the 'new' static `Create` method. A devolved version, in preparation for the Revit 2017 text element overhaul. Adjustment required after initial creation transaction.\n \nThe roadmap isn't clear.\n \nIt's not annoying, really, just disappointing, time sapping, and ambiguous. The 2017 'improvements' weren't enough!\n\nSorry, this message is longer than I wanted! And sorry it's another rant...\n\n**Answer 4:**\n\nNote that this is not supported functionality...\n \nBut it so happens that you can still set the vertical alignment through the `TEXT_ALIGN_VERT` built-in parameter.  \n \nIt needs to be set to `TextAlignFlags.TEF_ALIGN_TOP`, `TextAlignFlags.TEF_ALIGN_MIDDLE` or `TextAlignFlags.TEF_ALIGN_BOTTOM`, like in this C# snippet:\n \n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;AlignTextNote&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Parameter</span>&nbsp;p&nbsp;=&nbsp;textNote.get_Parameter(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.TEXT_ALIGN_VERT&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;p.Set(&nbsp;(<span style=\"color:#2b91af;\">Int32</span>)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TextAlignFlags</span>.TEF_ALIGN_MIDDLE&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;}\n</pre>\n\nHope that helps.\n \nMeanwhile we will have a look to see what is involved to get this formally exposed.\n\n**Response:**\n\nPerfect! Just what I needed."
  }
]