[
  {
    "original_filename": "1541_section_marker_endp",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!-- <script src=\"run_prettify.js\" type=\"text/javascript\"></script> --> \n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- new ttt\n  https://forums.autodesk.com/t5/revit-api-forum/how-can-i-get-the-coordinates-of-the-endpoints-for-a-section/m-p/6928342\n\n @ElasticsearchQA #RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge \n\nWe discussed several examples of using the temporary transaction trick TTT in the past.\nHere is a new exquisitly subtle variant for you to enjoy, provided by Frank @Fair59 Aarssen to get the coordinates of the endpoints for a section marker line segment. Question: I have a section marker that I would like to rotate around one of the endpoints of the line segment leader, but I haven't been able to figure out how to determine the endpoint coordinates...\n\n-->"
  },
  {
    "original_filename": "1541_section_marker_endp",
    "header_text": "TTT to Obtain Section Marker Endpoint",
    "local_header_href": "#ttt-to-obtain-section-marker-endpoint",
    "chunk_text": "### TTT to Obtain Section Marker Endpoint\n\nWe discussed several examples of using the temporary transaction trick TTT in the past, and it is also mentioned in The Building Coder topic group\non [handling transactions and transaction groups](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.53).\n\nHere is a new exquisitely subtle variant for you to enjoy, provided by\nFrank [@Fair59](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/2083518) Aarssen.\n\nHe uses it to answer \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) question\non [how to get the coordinates of the endpoints for a section marker line segment](https://forums.autodesk.com/t5/revit-api-forum/how-can-i-get-the-coordinates-of-the-endpoints-for-a-section/m-p/6928342),\nan issue that cannot be solved, according to the Revit development team:\n\n**Question:** I have a section marker that I would like to rotate around one of the endpoints of the line segment leader, but I haven't been able to figure out how to determine the endpoint coordinates:\n\n<center>\n<img src=\"img/section_marker_coordinates.png\" alt=\"Section marker coordinates\" width=\"439\"/>\n</center>\n\nI'm able to get the bounding box of the overall section marker but not these specific coordinates.\n\nHow can I do this?\n\nMy bigger problem involves reversing the effects of the built-in \"Mirror Project\" tool, and part of that includes reference section markers inside of another section that has been flipped.\n\nI would like to fix their orientation by rotating 180 degrees around the endpoint.\n\n**Answer:** The development team says that the section marker element is not exposed as a specific element type, so this position cannot be read at this time. \n\nHowever, Frank provided a workaround.\n \nA transaction needs to be active when you call the method, as the method temporarily hides the section tag and viewer_reference_label_text:\n \n<pre class=\"code\">\n<span style=\"color:#2b91af;\">Line</span>&nbsp;GetSectionLine(&nbsp;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;section,&nbsp;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;view&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">const</span>&nbsp;<span style=\"color:blue;\">double</span>&nbsp;correction&nbsp;=&nbsp;21.130014403&nbsp;/&nbsp;304.8;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;section.Document;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Category</span>&nbsp;cat&nbsp;=&nbsp;section.Category;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;==&nbsp;cat&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">throw</span>&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ArgumentException</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Section&nbsp;has&nbsp;null&nbsp;category&quot;</span>&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_Viewers\n&nbsp;&nbsp;&nbsp;&nbsp;!=&nbsp;(<span style=\"color:#2b91af;\">BuiltInCategory</span>)&nbsp;(cat.Id.IntegerValue)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">throw</span>&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ArgumentException</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Expected&nbsp;section&nbsp;with&nbsp;OST_Viewers&nbsp;category&quot;</span>&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;views&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;)&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;viewFromSection&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;v&nbsp;<span style=\"color:blue;\">in</span>&nbsp;views&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;section.Name&nbsp;==&nbsp;v.Name\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;&amp;&nbsp;section.GetTypeId()&nbsp;==&nbsp;v.GetTypeId()&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;viewFromSection&nbsp;=&nbsp;v;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">break</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;viewFromSection&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>&nbsp;vType&nbsp;=&nbsp;doc.GetElement(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;section.GetTypeId()&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;bb1&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">SubTransaction</span>&nbsp;st1&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">SubTransaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;st1.Start();\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Parameter</span>&nbsp;par&nbsp;=&nbsp;vType.get_Parameter(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.SECTION_TAG&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;par.Set(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>.InvalidElementId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;par&nbsp;=&nbsp;vType.get_Parameter(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.VIEWER_REFERENCE_LABEL_TEXT&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;par.Set(&nbsp;<span style=\"color:blue;\">string</span>.Empty&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;view.Scale&nbsp;=&nbsp;1;\n&nbsp;&nbsp;&nbsp;&nbsp;doc.Regenerate();\n&nbsp;&nbsp;&nbsp;&nbsp;bb1&nbsp;=&nbsp;section.get_BoundingBox(&nbsp;view&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;st1.RollBack();\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;bb&nbsp;=&nbsp;section.get_BoundingBox(&nbsp;view&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;pt1&nbsp;=&nbsp;bb.Min;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;pt2&nbsp;=&nbsp;bb.Max;\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;bb1&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;pt1&nbsp;=&nbsp;bb1.Min;\n&nbsp;&nbsp;&nbsp;&nbsp;pt2&nbsp;=&nbsp;bb1.Max;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;Origin&nbsp;=&nbsp;viewFromSection.Origin;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;ViewBasisX&nbsp;=&nbsp;viewFromSection.RightDirection;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;ViewBasisY&nbsp;=&nbsp;viewFromSection.ViewDirection;\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;ViewBasisX.X&nbsp;&lt;&nbsp;0&nbsp;^&nbsp;ViewBasisX.Y&nbsp;&lt;&nbsp;0&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;d&nbsp;=&nbsp;pt1.Y;\n&nbsp;&nbsp;&nbsp;&nbsp;pt1&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;pt1.X,&nbsp;pt2.Y,&nbsp;pt1.Z&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;pt2&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(&nbsp;pt2.X,&nbsp;d,&nbsp;pt2.Z&nbsp;);\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;ToPlane1&nbsp;=&nbsp;pt1.Add(&nbsp;ViewBasisY.Multiply(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;ViewBasisY.DotProduct(&nbsp;Origin.Subtract(&nbsp;pt1&nbsp;)&nbsp;)&nbsp;)&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;ToPlane2&nbsp;=&nbsp;pt2.Subtract(&nbsp;ViewBasisY.Multiply(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;ViewBasisY.DotProduct(&nbsp;pt2.Subtract(&nbsp;Origin&nbsp;)&nbsp;)&nbsp;)&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;correctionVector&nbsp;=&nbsp;ToPlane2.Subtract(&nbsp;ToPlane1&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Normalize().Multiply(&nbsp;correction&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;endPoint0&nbsp;=&nbsp;ToPlane1.Add(&nbsp;correctionVector&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;endPoint1&nbsp;=&nbsp;ToPlane2.Subtract(&nbsp;correctionVector&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(&nbsp;endPoint0,&nbsp;endPoint1&nbsp;);\n}\n</pre>\n\n**Response:** I have a few questions:\n \n1. Where did you come up with the `const double correction = 21.130014403 / 304.8` value?\n2. How do you distinguish between section vs. callout markers since they are both of category `OST_Viewers`?\n3. Would this work for section markers that are only references (such as ones that reference drafting views)?\n4. How do you know which endpoint is associated with the tail and which one is associated with the head?\n\n**Answer 1:** The bounding box of a section line is the result of a number of elements:\n\n- the line\n- the section head\n- the reference label text\n- the cycle symbol\n\n<center>\n<img src=\"img/section_marker_bounding_box.png\" alt=\"Section marker bounding box\" width=\"490\"/>\n</center>\n\nIn the method, I \"hide\" 2 and 3.\nYou can't hide the cycle symbol, so the result is too large.\nI simply added the resulting line without the correction to the project and measured the surplus length.\nAfter checking that it is always the same, I implemented the constant  `correction = 21.130014403 / 304.8`.\n\nThe number 304.8 is the number of millimetres in a foot, so the division by that number converts from feet to mm:\n\n<pre>\n  inch = 25.4\n  foot = 12 * inch = 304.8\n  length_in_mm = length_in_feet / foot\n</pre>\n \n**Answer 2:** I didn't distinguish between section vs. callout markers, I merely presumed you had a section marker.\n\nThere are 2 ways to test:\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">if</span>(&nbsp;_vType.FamilyName&nbsp;==&nbsp;<span style=\"color:#a31515;\">&quot;Section&quot;</span>&nbsp;)\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;_viewFromSection.GetType()&nbsp;\n  &nbsp;&nbsp;==&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">ViewSection</span>&nbsp;)&nbsp;)\n</pre>\n\nCallouts are PlanViews or Elevations, as far as I know.\n \n**Answer 3:** I don't know.\n \n**Answer 4:** I'm afraid that is truly hidden. The Section Head and Tail stay in the same position when flipping the section, but the viewDirection and RightDirection changes.\n\nThe most you can get is a line in the View.RightDirection\n \n<pre class=\"code\">\n  <span style=\"color:#2b91af;\">XYZ</span>&nbsp;_direction&nbsp;=&nbsp;ToPlane2.Subtract(&nbsp;ToPlane1&nbsp;).\n  &nbsp;&nbsp;Normalize();\n   \n  <span style=\"color:blue;\">return</span>&nbsp;_direction.IsAlmostEqualTo(&nbsp;ViewBasisX&nbsp;)&nbsp;\n  &nbsp;&nbsp;?&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(&nbsp;endPoint0,&nbsp;endPoint1&nbsp;)&nbsp;\n  &nbsp;&nbsp;:&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(&nbsp;endPoint1,&nbsp;endPoint0&nbsp;);\n</pre>\n\nMany thanks to Frank for this tricky solution, and many other extremely helpful and in-depth answers in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) as well!"
  }
]