[
  {
    "original_filename": "1566_align_grid",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<!--\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n</head>\n\n<!---\n\n- rotate grid to horizontal or vertical\n  13048285 [Grids Off-Axis]\n  https://forums.autodesk.com/t5/revit-api-forum/grids-off-axis/m-p/7129065\n  https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdSetGridEndpoint.cs\n\nAligning a Slightly Off-Axis Grid using #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/aligngrid\n\nHere is a follow-up on the recent discussion on how to modify a grid curve end point using <code>Grid.SetCurveInView</code>.\nIn the Revit API discussion forum thread on off-axis grids causing warnings in Revit, an attempt to use the same approach fails. Instead, Fair59 presents a solution using <code>RotateElement</code> to align an almost horizontal or almost vertical grid that is slightly off-axis...\n\n-->"
  },
  {
    "original_filename": "1566_align_grid",
    "header_text": "Aligning a Slightly Off-Axis Grid",
    "local_header_href": "#aligning-a-slightly-off-axis-grid",
    "chunk_text": "### Aligning a Slightly Off-Axis Grid\n\nHere is a follow-up on the recent discussion on how\nto [modify a grid curve end point](http://thebuildingcoder.typepad.com/blog/2017/05/sdk-update-rvtsamples-and-modifying-grid-end-point.html#4) using\n`Grid.SetCurveInView`.\n\nIn the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [off-axis grids](https://forums.autodesk.com/t5/revit-api-forum/grids-off-axis/m-p/7129065) causing\nwarnings in Revit, an attempt to use the same approach fails.\n\nInstead, Fair59 presents a solution using `RotateElement` to align an almost horizontal or almost vertical grid that is slightly off-axis:\n\n**Question:** I have models with `Grid` elements that produce off-axis warnings.\nSnooping the `Grid.Lines` shows direction vectors that are microscopically off horizontal/vertical.\nI have been unsuccessful in changing the `XYZ` `Direction`, which is read-only.\n\nIs it possible to adjust the direction vector, or the start and end points, to resolve the off-axis error? \n\n**Answer:** The solution\nto  [modify a grid curve end point](http://thebuildingcoder.typepad.com/blog/2017/05/sdk-update-rvtsamples-and-modifying-grid-end-point.html#4) might\nbe exactly what you need.\n\n**Response:** That looks like precisely what is required.\nHowever, on grids that are microscopically off-axis, it fails, saying \"The curve is unbound or not coincident with the original one of the datum plane\".\n\n**Answer:** The exception message basically says that your new curve doesn't lie on the old curve, meaning that you can't change the direction this way.\n\nThe solution is to rotate the `Grid` with `ElementTransformUtils.RotateElement`.\n\n**Response:** That would be a reasonable solution. I suspect that the error is not from user input, but a result of Revit's accuracy limitations and rounding issues. In my case the variation is microscopic, so determining the relative rotation increment, rather than being able to set the absolute angle will just push the rounding error further out. This is the off-axis grid:\n\n<center>\n<img src=\"img/grid_off_axis_error.png\" alt=\"Grid off-axis error\" width=\"498\">\n</center>\n\nThe highlighted value should be 1.0 but this `Direction` property is read-only.\n\n**Answer:** It is maybe a rounding issue, but Revit gives you a warning in the Warning-Review list, so it would be prudent to correct the issue.\n\nHere is the method `AlignOffAxisGrid` that does so:\n\n<pre class=\"code\">\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;Align&nbsp;the&nbsp;given&nbsp;grid&nbsp;horizontally&nbsp;or&nbsp;vertically&nbsp;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;if&nbsp;it&nbsp;is&nbsp;very&nbsp;slightly&nbsp;off&nbsp;axis,&nbsp;by&nbsp;Fair59&nbsp;in</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;https://forums.autodesk.com/t5/revit-api-forum/grids-off-axis/m-p/7129065</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:blue;\">void</span>&nbsp;AlignOffAxisGrid(\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Grid</span>&nbsp;grid&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:green;\">//Grid&nbsp;grid&nbsp;=&nbsp;doc.GetElement(&nbsp;</span>\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;&nbsp;sel.GetElementIds().FirstOrDefault()&nbsp;)&nbsp;as&nbsp;Grid;</span>\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;grid.Document;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;direction&nbsp;=&nbsp;grid.Curve\n&nbsp;&nbsp;&nbsp;&nbsp;.GetEndPoint(&nbsp;1&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Subtract(&nbsp;grid.Curve.GetEndPoint(&nbsp;0&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Normalize();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;distance2hor&nbsp;=&nbsp;direction.DotProduct(&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisY&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;distance2vert&nbsp;=&nbsp;direction.DotProduct(&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisX&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;angle&nbsp;=&nbsp;0;\n \n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Maybe&nbsp;use&nbsp;another&nbsp;criterium&nbsp;then&nbsp;&lt;0.0001</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;max_distance&nbsp;=&nbsp;0.0001;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:#2b91af;\">Math</span>.Abs(&nbsp;distance2hor&nbsp;)&nbsp;&lt;&nbsp;max_distance&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;vector&nbsp;=&nbsp;direction.X&nbsp;&lt;&nbsp;0&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?&nbsp;direction.Negate()&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;direction;\n \n&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Math</span>.Asin(&nbsp;-vector.Y&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:#2b91af;\">Math</span>.Abs(&nbsp;distance2vert&nbsp;)&nbsp;&lt;&nbsp;max_distance&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;vector&nbsp;=&nbsp;direction.Y&nbsp;&lt;&nbsp;0&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?&nbsp;direction.Negate()&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;direction;\n \n&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Math</span>.Asin(&nbsp;vector.X&nbsp;);\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;angle.CompareTo(&nbsp;0&nbsp;)&nbsp;!=&nbsp;0&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;correctGrid&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementTransformUtils</span>.RotateElement(&nbsp;doc,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid.Id,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(&nbsp;grid.Curve.GetEndPoint(&nbsp;0&nbsp;),&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid.Curve.GetEndPoint(&nbsp;0&nbsp;).Add(&nbsp;<span style=\"color:#2b91af;\">XYZ</span>.BasisZ&nbsp;)&nbsp;),&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n}\n</pre>\n\n**Response:** Many thanks, that has indeed resolved the error. \n\nMany thanks to Fair59 for this efficient solution!\n\nI added it \nto [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples)\nmodule [CmdSetGridEndpoint.cs](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdSetGridEndpoint.cs)\nin [release 2018.0.133.1](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2018.0.133.1),\ncf. the [diff to the previous version](https://github.com/jeremytammik/the_building_coder_samples/compare/2018.0.133.0...2018.0.133.1)."
  }
]