[
  {
    "original_filename": "1581_edge_refplane_column",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- RevitLookup 2018.0.0.3\n  https://github.com/jeremytammik/RevitLookup/releases/tag/2018.0.0.3\n  merged pull request [#36](https://github.com/jeremytammik/RevitLookup/pull/36) from [@Andrey-Bushman](https://github.com/andrey-bushman): switch target platform to.Net 4.6 and replace Revit 2017 NuGet package by Revit 2018.1 NuGet package\n  [Q] why do you require .net 4.6? this is not required by revit, is it? does the NuGet package need this?\n  [A] Because I read about .net 4.6 [here](https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2018/ENU/Revit-API/files/GUID-FEF0ED40-8658-4C69-934D-7F83FB5D5B63-htm.html):\n  Revit's binaries are built using .NET 4.5.2. However, Revit uses the runtime from .NET 4.6.\n  [Q] why do you add so many new revit api dll references? adwindows, macros, uimacros, IFC...? does the NuGet package need this? i prefer keeping RevitLookup as minimal as possible, for obvious reasons... i would prefer leaving the .net version as required by revit, and only reference the necessary revit api dlls, though.\n  [A] These DLL files were added by NuGet packages. The RevitAPI.dll and RevitAPIUI.dll libraries are used by Revit2018DevTools - this is one of my NuGet packages, it is used by Revit2018AddInTemplateSet templates.\n  Additional references don't take a place, but it is convenient when they already added instead of requiring the programmer to add them each time manually. Creating a NuGet package for each DLL and then downloading each one separately is inconvenient and annoying to the developers. I asked some of them about it. Therefore they are the part of my NuGet packages.\n\n- determine outer loop\n  13179537 [Is the first Edgeloop still the outer loop?]\n  https://forums.autodesk.com/t5/revit-api-forum/is-the-first-edgeloop-still-the-outer-loop/m-p/7225379\n\n- https://forums.autodesk.com/t5/revit-api-forum/locationcurve-for-steel-column/m-p/7327197\n\n- https://forums.autodesk.com/t5/revit-api-forum/reference-plane-from-reference-point/m-p/7329237\n\nDetermine outer edge loop #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/edge_refplane_column\nDetermining location curve for a steel column #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/edge_refplane_column\nDetermining reference plane from refpoint #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/edge_refplane_column\n\nA whole bunch of exciting Revit API topics to start the week\n&ndash; RevitLookup updated to use NuGet Revit API package\n&ndash; Determining the outer-most <code>EdgeLoop</code>\n&ndash; How to determine the location curve for a steel column\n&ndash; Determining a reference plane from a reference point...\n\n--->"
  },
  {
    "original_filename": "1581_edge_refplane_column",
    "header_text": "Edge Loop, Point Reference Plane and Column Line",
    "local_header_href": "#edge-loop-point-reference-plane-and-column-line",
    "chunk_text": "### Edge Loop, Point Reference Plane and Column Line\n\nA whole bunch of exciting Revit API topics to start the week:\n\n- [RevitLookup updated to use NuGet Revit API package](#2)\n- [Determining the outer-most `EdgeLoop`](#3)\n- [How to determine the location curve for a steel column](#4)\n- [Determining a reference plane from a reference point](#5)\n- [Beware of multiple outer loops](#6)\n\n####<a name=\"2\"></a>RevitLookup Updated to use NuGet Revit API Package\n\nAndrey Bushman updated RevitLookup with [pull request #36](https://github.com/jeremytammik/RevitLookup/pull/36) to\nswitch the target platform to .NET 4.6 and replace the Revit 2017 NuGet package by the Revit 2018.1 NuGet package.\n\n**Question:** Why do you require .NET 4.6? This is not required by the Revit API, is it? Does the NuGet package need this?\n\n**Answer:** Because I read about .NET 4.6 in the  [official Revit development requirements](https://knowledge.autodesk.com/search-result/caas/cloudHelp/cloudhelp/2018/ENU/Revit-API/files/GUID-FEF0ED40-8658-4C69-934D-7F83FB5D5B63-htm.html). They say: Revit's binaries are built using .NET 4.5.2. However, Revit uses the runtime from .NET 4.6.\n\n**Question:** Why do you add so new Revit API DLL references? AdWindows, Macros, UIMacros, IFC...? Does the NuGet package need this? I prefer keeping RevitLookup as minimal as possible, for obvious reasons... I would prefer leaving the .NET version as required by Revit, and only reference the necessary Revit API DLLs.\n\n**Answer:** These DLL references are automatically added by NuGet packages. The RevitAPI.dll and RevitAPIUI.dll libraries are used by Revit2018DevTools &ndash; this is one of my NuGet packages, it is used by Revit2018AddInTemplateSet templates.\n\nAdditional references don't take any space, and it is convenient when they are already added instead of requiring the programmer to add them each time manually. Creating a NuGet package for each DLL and then downloading each one separately is inconvenient and annoying for developers. I asked some of them about it. Therefore, they are the part of my NuGet packages.\n\nMany thanks to Andrey for this update, included\nin [RevitLookup 2018.0.0.3](https://github.com/jeremytammik/RevitLookup/releases/tag/2018.0.0.3).\n\n\n####<a name=\"3\"></a>Determining the Outer-Most EdgeLoop\n\n[Richard Thomas](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) shared a nice solution to the question raised in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\nasking [is the first EdgeLoop still the outer loop?](https://forums.autodesk.com/t5/revit-api-forum/is-the-first-edgeloop-still-the-outer-loop/m-p/7225379)\n\n**Question:** I try to determine for all types of surfaces what is the outer `EdgeLoop`.\n \nIs it always the first one returned by `face.EdgeLoops`?\n \nIf not, how to find it?\n \n**Answer:** The Building Coder discussed how to\ndetermine [2D polygon areas and outer loop](http://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html) by area comparison.\n\nRichard presents an alternative solution based on a simple max and min calculation. In his words:\n\nThe area approach mentioned there is probably more reliable, but I had an alternate idea based on getting all co-ordinates linked to the edge loops they are from and then finding the minimums in a certain direction. Below, I've taken `min.x`, but but same would apply for `min.y`, `max.x` and `max.y`.\n \nI could not think of a situation where if you convert the 3D co-ordinates of each edge curve to a co-ordinate system of the plane you would end up with a min.x for the outer loop greater than the min.x for the inner loop. Similarly, the max.x of the outer loop should be greater than the max.x of the inner loop. This appeared to be true for most cases but then there was the issue of circular curves where the two end points could be further back than a point projecting into the centre of the curve. So, I decided to treat cyclic curves differently by checking for min.x along the curve.\n \nI came up with the two below functions, one for planar faces and the other for faces in general. They both seem to give reliable results on the cases in the image below (based on expected edge counts for the outer loops). However, there may be a case that fails. The parts related to co-ordinate transformations may need looking at (there may be better approaches). I checked the z of each transformed point to see that it was 0 or virtually 0, so seems to be as expected.\n \nFor the more generalised method I'm using API functionality which projects a point onto a face, I was expecting some possible intersection errors since I'm checking points on the boundary of the face. I've not checked such things in detail.\n \nIn summary, the area method mentioned in link is likely better and more reliable; not sure which is faster.\n\n<center>\n<img src=\"img/slabtypes.png\" alt=\"Slab types\" width=\"500\"/>\n</center>\n\n<pre class=\"code\">\n<span style=\"color:blue;\">Public</span>&nbsp;<span style=\"color:blue;\">Shared</span>&nbsp;<span style=\"color:blue;\">Function</span>&nbsp;Run(<span style=\"color:blue;\">ByVal</span>&nbsp;commandData&nbsp;<span style=\"color:blue;\">As</span>&nbsp;Autodesk.Revit.UI.<span style=\"color:#2b91af;\">ExternalCommandData</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;Autodesk.Revit.UI.<span style=\"color:#2b91af;\">Result</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IntApp&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">UIApplication</span>&nbsp;=&nbsp;commandData.Application\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IntUIDoc&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>&nbsp;=&nbsp;IntApp.ActiveUIDocument\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;IntUIDoc&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Failed&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IntDoc&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;=&nbsp;IntUIDoc.Document\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;R&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Reference</span>&nbsp;=&nbsp;<span style=\"color:blue;\">Nothing</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Try</span>\n&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;=&nbsp;IntUIDoc.Selection.PickObject(<span style=\"color:#2b91af;\">Selection</span>.ObjectType.Face)\n&nbsp;&nbsp;<span style=\"color:blue;\">Catch</span>&nbsp;ex&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Exception</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Try</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;R&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Cancelled&nbsp;<span style=\"color:blue;\">Else</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;F_El&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;=&nbsp;IntDoc.GetElement(R.ElementId)\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;F_El&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Failed&nbsp;<span style=\"color:blue;\">Else</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;F&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;=&nbsp;<span style=\"color:blue;\">TryCast</span>(F_El.GetGeometryObjectFromReference(R),&nbsp;<span style=\"color:#2b91af;\">Face</span>)\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;F&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Failed&nbsp;<span style=\"color:blue;\">Else</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;EA1&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;=&nbsp;PlannerFaceOuterLoop(F)\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;EA2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;=&nbsp;OuterLoop(F)\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Succeeded\n<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n \n<span style=\"color:blue;\">Public</span>&nbsp;<span style=\"color:blue;\">Shared</span>&nbsp;<span style=\"color:blue;\">Function</span>&nbsp;OuterLoop(F&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MinU&nbsp;=&nbsp;<span style=\"color:blue;\">Function</span>(C&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Curve</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;C.IsCyclic&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Min&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;<span style=\"color:blue;\">Double</span>.NaN\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">For</span>&nbsp;I&nbsp;=&nbsp;0&nbsp;<span style=\"color:blue;\">To</span>&nbsp;20\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Param&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;I&nbsp;/&nbsp;20\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;CuvPt&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.Evaluate(Param,&nbsp;<span style=\"color:blue;\">True</span>)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IntersectionResult</span>&nbsp;=&nbsp;F.Project(CuvPt)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;IR&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;=&nbsp;<span style=\"color:blue;\">False</span>&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;Min&nbsp;=&nbsp;<span style=\"color:blue;\">Double</span>.NaN&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Min&nbsp;=&nbsp;IR.UVPoint.U\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;IR.UVPoint.U&nbsp;&lt;&nbsp;Min&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Min&nbsp;=&nbsp;IR.UVPoint.U\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Next</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;Min\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Pt1&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.GetEndPoint(0)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Pt2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.GetEndPoint(1)\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IR1&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IntersectionResult</span>&nbsp;=&nbsp;F.Project(Pt1)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;IR2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IntersectionResult</span>&nbsp;=&nbsp;F.Project(Pt2)\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;IR1&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">OrElse</span>&nbsp;IR2&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:blue;\">Double</span>.NaN\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;IR1.UVPoint.U&nbsp;&lt;&nbsp;IR2.UVPoint.U&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;IR1.UVPoint.U\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;IR2.UVPoint.U\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Loops&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>)\n&nbsp;&nbsp;Loops&nbsp;=&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;F.EdgeLoops\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Select</span>&nbsp;L\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Cv&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>))\n&nbsp;&nbsp;Cv&nbsp;=&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;Loops\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L3&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Edge</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;L2\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Let</span>&nbsp;Mu&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;MinU(L3.AsCurve)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Where</span>&nbsp;Mu&nbsp;&lt;&gt;&nbsp;<span style=\"color:blue;\">Double</span>.NaN\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Select</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>)(L2,&nbsp;Mu)\n \n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Out&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>)&nbsp;=&nbsp;Cv.ToList.Find(<span style=\"color:blue;\">Function</span>(Jx)&nbsp;Jx.Item2&nbsp;=&nbsp;Cv.Min(<span style=\"color:blue;\">Function</span>(Jv)&nbsp;Jv.Item2))\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;Out&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:blue;\">Nothing</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;Out.Item1\n&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n \n<span style=\"color:blue;\">Public</span>&nbsp;<span style=\"color:blue;\">Shared</span>&nbsp;<span style=\"color:blue;\">Function</span>&nbsp;PlannerFaceOuterLoop(F&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;PF&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">PlanarFace</span>&nbsp;=&nbsp;<span style=\"color:blue;\">TryCast</span>(F,&nbsp;<span style=\"color:#2b91af;\">PlanarFace</span>)\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;PF&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Else</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;FN&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;PF.FaceNormal\n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;T&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Transform</span>.Identity\n&nbsp;&nbsp;T.BasisZ&nbsp;=&nbsp;FN\n&nbsp;&nbsp;T.BasisX&nbsp;=&nbsp;PF.XVector\n&nbsp;&nbsp;T.BasisY&nbsp;=&nbsp;PF.YVector\n&nbsp;&nbsp;T.Origin&nbsp;=&nbsp;PF.Origin\n \n&nbsp;&nbsp;<span style=\"color:green;\">&#39;Dim&nbsp;Zeds&nbsp;As&nbsp;New&nbsp;List(Of&nbsp;Double)</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;MinU&nbsp;=&nbsp;<span style=\"color:blue;\">Function</span>(C&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Curve</span>)&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;C.IsCyclic&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Min&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;<span style=\"color:blue;\">Nothing</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">For</span>&nbsp;I&nbsp;=&nbsp;0&nbsp;<span style=\"color:blue;\">To</span>&nbsp;20\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Param&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;I&nbsp;/&nbsp;20\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;CuvPt&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.Evaluate(Param,&nbsp;<span style=\"color:blue;\">True</span>)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;XYZt&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;T.Inverse.OfPoint(CuvPt)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;I&nbsp;=&nbsp;0&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Min&nbsp;=&nbsp;XYZt.X\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;XYZt.X&nbsp;&lt;&nbsp;Min&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Min&nbsp;=&nbsp;XYZt.X\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Next</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;Min\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Pt1&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.GetEndPoint(0)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Pt2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&nbsp;=&nbsp;C.GetEndPoint(1)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;XYZp&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>()&nbsp;=&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(1)&nbsp;{}\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XYZp(0)&nbsp;=&nbsp;T.Inverse.OfPoint(Pt1)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XYZp(1)&nbsp;=&nbsp;T.Inverse.OfPoint(Pt2)\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">&#39;&nbsp;Zeds.Add(XYZp(0).Z)</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">&#39;&nbsp;Zeds.Add(XYZp(1).Z)</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;XYZp(0).X&nbsp;&lt;&nbsp;XYZp(1).X&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;XYZp(0).X\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;XYZp(1).X\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Loops&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>)\n&nbsp;&nbsp;Loops&nbsp;=&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;F.EdgeLoops\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Select</span>&nbsp;L\n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Cv&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>))\n&nbsp;&nbsp;Cv&nbsp;=&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L2&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;Loops\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">From</span>&nbsp;L3&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Edge</span>&nbsp;<span style=\"color:blue;\">In</span>&nbsp;L2\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Let</span>&nbsp;Mu&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">Double</span>&nbsp;=&nbsp;MinU(L3.AsCurve)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Select</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>)(L2,&nbsp;Mu)\n \n \n&nbsp;&nbsp;<span style=\"color:blue;\">Dim</span>&nbsp;Out&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Tuple</span>(<span style=\"color:blue;\">Of</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>,&nbsp;<span style=\"color:blue;\">Double</span>)&nbsp;=&nbsp;Cv.ToList.Find(<span style=\"color:blue;\">Function</span>(Jx)&nbsp;Jx.Item2&nbsp;=&nbsp;Cv.Min(<span style=\"color:blue;\">Function</span>(Jv)&nbsp;Jv.Item2))\n&nbsp;&nbsp;<span style=\"color:blue;\">If</span>&nbsp;Out&nbsp;<span style=\"color:blue;\">Is</span>&nbsp;<span style=\"color:blue;\">Nothing</span>&nbsp;<span style=\"color:blue;\">Then</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;<span style=\"color:blue;\">Nothing</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">Else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">Return</span>&nbsp;Out.Item1\n&nbsp;&nbsp;<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">If</span>\n<span style=\"color:blue;\">End</span>&nbsp;<span style=\"color:blue;\">Function</span>\n</pre>\n\nI like Richard's idea, so I rewrote his functions in C# and added them\nto [The Building Coder samples](https://github.com/jeremytammik/the_building_coder_samples).\n\nInstead of using `C.Evaluate` twenty times over, I call the curve `Tessellate` method. That also handles the case of a linear curve gracefully, returning just the two end points, so the `MinU` function can be shortened and simplified:\n \n<pre class=\"code\">\n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MinU(&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;C,&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;F&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;C.Tessellate()\n&nbsp;&nbsp;&nbsp;&nbsp;.Select&lt;<span style=\"color:#2b91af;\">XYZ</span>,&nbsp;<span style=\"color:#2b91af;\">IntersectionResult</span>&gt;(&nbsp;p&nbsp;=&gt;&nbsp;F.Project(&nbsp;p&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Min&lt;<span style=\"color:#2b91af;\">IntersectionResult</span>&gt;(&nbsp;ir&nbsp;=&gt;&nbsp;ir.UVPoint.U&nbsp;);\n}\n \n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:blue;\">double</span>&nbsp;MinX(&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;C,&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;Tinv&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;C.Tessellate()\n&nbsp;&nbsp;&nbsp;&nbsp;.Select&lt;<span style=\"color:#2b91af;\">XYZ</span>,&nbsp;<span style=\"color:#2b91af;\">XYZ</span>&gt;(&nbsp;p&nbsp;=&gt;&nbsp;Tinv.OfPoint(&nbsp;p&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.Min&lt;<span style=\"color:#2b91af;\">XYZ</span>&gt;(&nbsp;p&nbsp;=&gt;&nbsp;p.X&nbsp;);\n}\n \n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;OuterLoop(&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;F&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;eaMin&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">EdgeArrayArray</span>&nbsp;loops&nbsp;=&nbsp;F.EdgeLoops;\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;uMin&nbsp;=&nbsp;<span style=\"color:blue;\">double</span>.MaxValue;\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;a&nbsp;<span style=\"color:blue;\">in</span>&nbsp;loops&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;uMin2&nbsp;=&nbsp;<span style=\"color:blue;\">double</span>.MaxValue;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Edge</span>&nbsp;e&nbsp;<span style=\"color:blue;\">in</span>&nbsp;a&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;min&nbsp;=&nbsp;MinU(&nbsp;e.AsCurve(),&nbsp;F&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;min&nbsp;&lt;&nbsp;uMin2&nbsp;)&nbsp;{&nbsp;uMin2&nbsp;=&nbsp;min;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;uMin2&nbsp;&lt;&nbsp;uMin&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uMin&nbsp;=&nbsp;uMin2;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eaMin&nbsp;=&nbsp;a;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;eaMin;\n}\n \n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;PlanarFaceOuterLoop(&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;F&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">PlanarFace</span>&nbsp;face&nbsp;=&nbsp;F&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">PlanarFace</span>;\n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;face&nbsp;==&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;T&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Transform</span>.Identity;\n&nbsp;&nbsp;T.BasisZ&nbsp;=&nbsp;face.FaceNormal;\n&nbsp;&nbsp;T.BasisX&nbsp;=&nbsp;face.XVector;\n&nbsp;&nbsp;T.BasisY&nbsp;=&nbsp;face.YVector;\n&nbsp;&nbsp;T.Origin&nbsp;=&nbsp;face.Origin;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transform</span>&nbsp;Tinv&nbsp;=&nbsp;T.Inverse;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;eaMin&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">EdgeArrayArray</span>&nbsp;loops&nbsp;=&nbsp;F.EdgeLoops;\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;uMin&nbsp;=&nbsp;<span style=\"color:blue;\">double</span>.MaxValue;\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">EdgeArray</span>&nbsp;a&nbsp;<span style=\"color:blue;\">in</span>&nbsp;loops&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;uMin2&nbsp;=&nbsp;<span style=\"color:blue;\">double</span>.MaxValue;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Edge</span>&nbsp;e&nbsp;<span style=\"color:blue;\">in</span>&nbsp;a&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;min&nbsp;=&nbsp;MinX(&nbsp;e.AsCurve(),&nbsp;Tinv&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;min&nbsp;&lt;&nbsp;uMin2&nbsp;)&nbsp;{&nbsp;uMin2&nbsp;=&nbsp;min;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;uMin2&nbsp;&lt;&nbsp;uMin&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uMin&nbsp;=&nbsp;uMin2;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eaMin&nbsp;=&nbsp;a;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;eaMin;\n}\n</pre>\n \nI added them\nto [The Building Coder samples release 2018.0.134.3](https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2018.0.134.3)\nmodule [CmdSlabBoundaryArea.cs L29-L102](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdSlabBoundaryArea.cs#L29-L102).\n \nMany thanks to Richard for implementing, testing and sharing this simple approach!\n\n\n####<a name=\"4\"></a>How to Determine the Location Curve for a Steel Column \n\nRichard also answered \nanother [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non retrieving the [location curve of a steel column](https://forums.autodesk.com/t5/revit-api-forum/xyz-question/m-p/6460982):\n\n**Question:** How can I get the location curve for a steel member column?\n\n<center>\n<img src=\"img/steel_column_location_curve.png\" alt=\"Steel column location curve\" width=\"227\"/>\n</center>\n\n**Answer:**  When searching for an answer to a question like this, you should always start by first checking the examples provided by the official Revit SDK and the developer guide. I count 58 occurrences of `LocationCurve` in the SDK samples. The Building Coder also includes 64 different examples of accessing the `LocationCurve` of an element.\n\nHowever, there are some twists involved specifically with steel columns, so this is a trick question.\n \nA vertical column will have a location point and no curve at all.\n\nFurthermore, its Z component will be zero, regardless what level it resides on.\n \nA slanted column, on the other hand, is equipped with a location curve.\n \nFor vertical columns, you can derive end points via level parameters and offsets. Getting such information is not generally as easy as just getting a location curve. It follows the below procedure:\n \nCheck what type of column you are dealing with via `SLANTED_COLUMN_TYPE_PARAM` (Int32); it takes its value  from the `SlantedOrVerticalColumnType` enumeration.\n\nDetermine the start and end level elements from:\n\n- `FAMILY_TOP_LEVEL_PARAM` (ElementID)\n- `FAMILY_BASE_LEVEL_PARAM` (ElementID)\n\nConsider the `Elevation` or `ProjectElevation` parameters of those level elements (depending on need).\n\nDetermine the offsets of the column ends from the corresponding levels via:\n\n- `FAMILY_BASE_LEVEL_OFFSET_PARAM` (Double)\n- `FAMILY_TOP_LEVEL_OFFSET_PARAM` (Double)\n\nAdd those to the numerical level of each end.\n \nAlternatively, change `SLANTED_COLUMN_TYPE_PARAM` from `0` to `1` or `2`, which stands for `angle driven` and `endpoint driven`. Then, the column becomes equipped with a location curve and you can extract information from that.\n \nI favour the first longer approach because it is purely reading the database, not transacting with it.\n\nThe above-mentioned built-in parameters have changed for consistency; older versions of Revit use ones specific to columns. Check the API documentation for details on this.\n\nFinally, for the sake of completeness, here are previous discussions by The Building Coder on some aspects of slanted columns that illuminate further:\n \n- [Creating a slanted column](http://thebuildingcoder.typepad.com/blog/2009/06/creating-a-slanted-column.html)\n- [Slanted column cross section rotation](http://thebuildingcoder.typepad.com/blog/2011/03/slanted-column-cross-section-rotation.html)\n\n\n####<a name=\"5\"></a>Determining a Reference Plane from a Reference Point\n\nLast but not least, another very useful and illuminating solution that deserves mentioning is from Fair59, once again, in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread on obtaining \na [reference plane from reference point](https://forums.autodesk.com/t5/revit-api-forum/reference-plane-from-reference-point/m-p/7329237):\n\n**Question:** In the Revit family environment, I am drawing two reference points `RefArrPts` and drawing a reference line `crv` that connects the two points. In the next step, I extract the reference points from the reference line `CrvRefPts`. In the last step, I try to extract the XY plane `plnRef` from the reference points `CrvRefPts`. The returned value is of type `REFERENCE`, the element id of `plnRef` is the same element id of the `CrvStRefPt`. The method `GetCoordinatePlaneReferenceXY` states that it returns a reference to the XY plane of the coordinate system, but it is returning a reference to the point instead.\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">CurveByPoints</span>&nbsp;crv&nbsp;=&nbsp;RvtDoc.FamilyCreate\n&nbsp;&nbsp;&nbsp;&nbsp;.NewCurveByPoints(&nbsp;RefArrPts&nbsp;);\n \n&nbsp;&nbsp;crv.IsReferenceLine&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePointArray</span>&nbsp;CrvRefPts&nbsp;=&nbsp;crv.GetPoints();\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePoint</span>&nbsp;CrvStRefPt&nbsp;=&nbsp;CrvRefPts.get_Item(&nbsp;0&nbsp;);\n&nbsp;&nbsp;plnRef&nbsp;=&nbsp;CrvStRefPt.GetCoordinatePlaneReferenceXY();\n</pre>\n\nWhat am I doing wrong? Any guidance would be greatly appreciated.\n\nThe line I am drawing is not orthogonal; therefore, I need to extract the plane from the curve end points so that the plane is perpendicular to the line. If I extract the plane from the original two points, I will get planes orthogonal to the world coordinates, which is not useful to me.\n\n<center>\n<img src=\"img/EndPt_Planes_01-01.jpg\" alt=\"Reference point planes\" width=\"624\"/>\n</center>\n\nThe reason for extracting these planes is to draw geometry on them (via the API) and then allow the user to move the line and have the constrained geometry update.\n\nThe steps the user would execute are as follows:\n\n1. Run a command that draws the line and the geometry on the reference planes.\n2. Move the line as desired within the model; all geometry will update. \n\n**Answer:** You can easily generate pure geometric planes yourself like this:\n \n<pre class=\"code\">\n  XYZ p1 = first point\n  XYZ q2 = second point\n  XYZ v = p2 - p1\n  XYZ normal = v.Normalise\n  Plane plane1 = Plane.Create( p1, normal )\n  Plane plane2 = Plane.Create( p2, normal )\n</pre>\n\nIf you require a reference to an existing plane element in the model, you could search all of them for one with a matching origin and normal vector.\n\nThe planes you are after are faces of the solid of the reference line, the solid returned by `crv.get_geometry`. Unfortunately, they don't have a reference. If you require a reference to host the geometry, then you'd have to host two extra reference points on the reference line and use the references from those.\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePoint</span>&nbsp;rPnt0&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePoint</span>&nbsp;rPnt1&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">SubTransaction</span>&nbsp;st&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">SubTransaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;st.Start();\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PointLocationOnCurve</span>&nbsp;location&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PointLocationOnCurve</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PointOnCurveMeasurementType</span>.NormalizedCurveParameter,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,&nbsp;<span style=\"color:#2b91af;\">PointOnCurveMeasureFrom</span>.Beginning&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PointOnEdge</span>&nbsp;pointOnEdge&nbsp;=&nbsp;doc.Application.Create\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.NewPointOnEdge(&nbsp;crv.GeometryCurve.Reference,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;location&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;rPnt0&nbsp;=&nbsp;doc.FamilyCreate.NewReferencePoint(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pointOnEdge&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;location&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PointLocationOnCurve</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PointOnCurveMeasurementType</span>.NormalizedCurveParameter,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1,&nbsp;<span style=\"color:#2b91af;\">PointOnCurveMeasureFrom</span>.Beginning&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;pointOnEdge&nbsp;=&nbsp;doc.Application.Create.NewPointOnEdge(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crv.GeometryCurve.Reference,&nbsp;location&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;rPnt1&nbsp;=&nbsp;doc.FamilyCreate.NewReferencePoint(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pointOnEdge&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;st.Commit();\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePointArray</span>&nbsp;CrvRefPts&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ReferencePointArray</span>();\n \n&nbsp;&nbsp;CrvRefPts.Append(&nbsp;rPnt0&nbsp;);\n&nbsp;&nbsp;CrvRefPts.Append(&nbsp;rPnt1&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ReferencePoint</span>&nbsp;CrvStRefPt&nbsp;=&nbsp;CrvRefPts.get_Item(&nbsp;0&nbsp;);\n&nbsp;&nbsp;plnRef&nbsp;=&nbsp;CrvStRefPt.GetCoordinatePlaneReferenceYZ();\n</pre>\n\nMany thanks to Fair59 for explaining this and sharing the solution!\n\n\n####<a name=\"6\"></a>Beware of Multiple Outer Loops\n\nAdrian Esdaile added \na [warning in his comment below](http://thebuildingcoder.typepad.com/blog/2017/08/edge-loop-point-reference-plane-and-column-line.html#comment-3491949399) that\nyou should definitely be aware of:\n\nIn reference to the question about Outer loops: Unfortunately, the quirky nature of Revit will defeat you here. It is entire possible to create valid geometry in Revit composed of TWO (yes, TWO, or more...) OUTER loops. How this will behave with your code (or indeed ANY code!) is questionable.\n\nFor example &ndash; create a Floor in Sketch mode, create two 'islands' of floor, click OK... done! Revit calls this ONE floor object, but it's clearly TWO separate pieces &ndash; that behave as one. It is considered VERY POOR DRAFTING to create floors like this; but \"users gonna use\" if you give them a chance, and it's a quick and lazy way of doing things.\n\nIn a perfect world, Revit would slap you with an error for trying to create a daft and confusing object like this; but this world (and Revit, bless its binary heart) is far from perfect.\n\nFor an example of unimaginably bad practice in Revit drafting (but very common in the field, dammit...) See this [example file](zip/floors_of_unimaginable_evil.zip) I call\n&ndash; [floors_of_unimaginable_evil.rvt](zip/floors_of_unimaginable_evil.rvt):\n\n<center>\n<img src=\"img/floors_of_unimagnable_evil_rvt.png\" alt=\"Floors of unimagnable evil\" width=\"500\"/>\n</center>\n\nLook at the image above &ndash; there is something terribly wrong with the area reported for this floor... and what about the volume...? Huh? Why would someone do that? Doesn't matter why, but \"users gonna use\" as I said &ndash; if Revit allows it, users WILL do it! RVT 2016 format, by the way. Feel free to use this file as a test case for 'what can happen' :-D\n\nYes, I've used a Floor in this example, but Revit is not consistent in when it will or won't allow multiple curves to count as single curve. I suspect you can do this with columns, too, as a column might be defined by a swept blend... which greatly expands the possibilities for evil.\n\n**Response:** Obviously, it is not that hard to test whether a Revit so-called edge loop consists of multiple disjoint loops, but it places substantial additional burden on the programmer.\n\nMy preferred way to deal with this (or at least protect myself as an add-in developer) would be to implement a reliable model checking algorithm, run automatically at regular intervals as well as before saving the BIM project, that checks for and warns about weird user input of this kind.\n\nObviously, the number of creative and involuntarily evil things that users can get up to is absolutely unlimited, so the number of checks performed would grow with time as new evil possibilities are discovered and discouraged."
  }
]