[
  {
    "original_filename": "1609_whats_new_2018_2",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\nRevit 2018.2 @AutodeskRevit product, #RevitAPI and SDK update #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/rvt2018_2\n\nLet's discuss the Revit API enhancements added since the initial release of Revit 2018\n&ndash; Revit 2018.2 Product Update and Resolved API Issues\n&ndash; Revit 2018.2 SDK Update\n&ndash; Major Additions to the Revit 2018.1 API\n&ndash; Material API additions\n&ndash; Geometry API additions\n&ndash; BrowserOrganization API additions\n&ndash; IFC additions\n&ndash; Rebar API additions\n&ndash; Major Additions to the Revit 2018.2 API\n&ndash; Fabrication API additions...\n\n--->"
  },
  {
    "original_filename": "1609_whats_new_2018_2",
    "header_text": "What's New in the Revit 2018.2 API",
    "local_header_href": "#whats-new-in-the-revit-20182-api",
    "chunk_text": "### What's New in the Revit 2018.2 API\n\nLet's discuss the Revit API enhancements added since the initial release of Revit 2018.\n\nBefore getting to that, let me briefly mention the new AUGI material pointing\nout [101 Best Practice Tips for Revit Model Management](https://issuu.com/iuidesign/docs/101_revit_tips-iftikhar_ismail), \nin case you are interested in such things.\n\n- [Revit 2018.2 Product Update and Resolved API Issues](#2)\n- [Revit 2018.2 SDK Update](#3)\n- [What's New in Previous Versions](#4)\n- [Major Additions to the Revit 2018.1 API](#5)\n    - [Material API additions](#5.1)\n        - [Editing the properties of an Appearance Asset](#5.1.1)\n        - [Editing AssetProperty values](#5.1.2)\n        - [Connected Assets](#5.1.3)\n        - [Validation](#5.1.4)\n        - [Schemas & Property Names](#5.1.5)\n        - [Utilities](#5.1.6)\n    - [Geometry API additions](#5.2)\n        - [Surface API additions](#5.2.1)\n        - [Curve API additions](#5.2.2)\n    - [BrowserOrganization API additions](#5.3)\n    - [IFC additions](#5.4)\n    - [Rebar API additions](#5.5)\n        - [BarTypeDiameterOptions](#5.5.1)\n        - [GetDistributionPath()](#5.5.2)\n        - [RebarUpdateCurvesData](#5.5.3)\n- [Major Additions to the Revit 2018.2 API](#6)\n    - [Fabrication API additions](#6.1)\n        - [FabricationNetworkChangeService](#6.1.1)\n        - [FabricationNetworkChangeServiceResult](#6.1.2)\n        - [FabricationPartSizeMap](#6.1.3)\n    - [Other API additions](#6.2)\n        - [RevitLinkType API addition](#6.2.1)\n\n####<a name=\"2\"></a>Revit 2018.2 Product Update and Resolved API Issues\n\nI installed the Revit 2018.2 product update last week from\nthe [Autodesk Revit 2018 Product Updates](https://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-revit-2018-product-updates.html?v=2018).\n\nIn the process, I checked out\nthe [release notes](http://revit.downloads.autodesk.com/download/2018_2_RVT/Docs/RelNotes/Autodesk_Revit_2018_2_ReleaseNotes.html) to\nanalyse what API issues have been addressed in the various 2018 updates, and extracted the following list of *reported issues resolved within Revit 2018*:\n\n- 2018.0.2 Hot Fix &ndash; API:\n    - Improved stability when using the API to print or export from modal dialogs.\n- 2018.2 Update &ndash; Resolved Issues &ndash; API:\n    - Enabled the FabricationPart.GeometryChecksum property to simplify the checking of fabrication part geometry.\n    - Fixed an issue so that the crop box is correctly set using the API.\n    - Improved stability when placing a wall-hosted family on a ceiling through Dynamo.\n- 2018.1.1 Hot Fix &ndash; API:\n    - Fixed an issue so that the extents of a crop box are correctly set using the API.\n- 2018.1 Update &ndash; Improvements\n    - Integrated Materials API.\n- 2018.0.2 Hot Fix &ndash; API:\n    - Improved stability when using the API to print or export from modal dialogs.\n\nAs we shall see below, a number of other enhancements have also been added.\n\n####<a name=\"3\"></a>Revit 2018.2 SDK Update\n\nNext, I visited \nthe [Revit Developer Centre](http://www.autodesk.com/developrevit) to \ndownload and install\nthe [Revit 2018.2 SDK (Update December 6, 2017)](http://download.autodesk.com/us/revit-sdk/REVIT_2018_2_SDK.msi) (msi &ndash; 369528Kb).\n\n<center>\n<img src=\"img/revit_2018_2_sdk.png\" alt=\"Revit 2018.2 SDK\" width=\"604\"/>\n</center>\n\nAs far as I can tell, it has no differences at all to the previous version in the `Samples` collection.\n\nThe only changes I see affect the help file and *changes and additions* document.\n\n<pre>\nC:\\a\\lib\\revit>dir 2018.1\\SDK\n27/07/17  14:21      53'781 Revit Platform API Changes and Additions.docx\n27/07/17  17:02  48'063'436 RevitAPI.chm\n\nC:\\a\\lib\\revit>dir 2018.2\\SDK\n05/12/17  13:31      55'881 Revit Platform API Changes and Additions.docx\n05/12/17  15:05  48'155'903 RevitAPI.chm\n</pre>\n\nStudying those in more depth, I do notice significant enhancements.\n\nI also notice that I did not document the updates listed in the corresponding *changes and additions* document for Revit 2018.1.\n\nSo here goes:"
  },
  {
    "original_filename": "1609_whats_new_2018_2",
    "header_text": "<a name=\"4\"></a>What's New in Previous Versions",
    "local_header_href": "#a-name4awhats-new-in-previous-versions",
    "chunk_text": "#### <a name=\"4\"></a>What's New in Previous Versions\n\nHere are links to discussions of *What's New in the Revit API* for previous versions:\n\n- [What's New in the Revit 2010 API](http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2010-api.html)\n- [What's New in the Revit 2011 API](http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2011-api.html)\n- [What's New in the Revit 2012 API](http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2012-api.html)\n- [What's New in the Revit 2013 API](http://thebuildingcoder.typepad.com/blog/2013/03/whats-new-in-the-revit-2013-api.html)\n- [What's New in the Revit 2014 API](http://thebuildingcoder.typepad.com/blog/2013/04/whats-new-in-the-revit-2014-api.html)\n- [What's New in the Revit 2015 API](http://thebuildingcoder.typepad.com/blog/2014/04/whats-new-in-the-revit-2015-api.html)\n- [What's New in the Revit 2016 API](http://thebuildingcoder.typepad.com/blog/2015/04/whats-new-in-the-revit-2016-api.html)\n- [What's New in the Revit 2017 API](http://thebuildingcoder.typepad.com/blog/2016/04/whats-new-in-the-revit-2017-api.html)\n- [What's New in the Revit 2017.1 API](http://thebuildingcoder.typepad.com/blog/2016/11/whats-new-in-the-revit-20171-api.html)\n- [What's New in the Revit 2018 API](http://thebuildingcoder.typepad.com/blog/2017/04/whats-new-in-the-revit-2018-api.html)\n- [Revit 2018.1 and the Visual Materials API](http://thebuildingcoder.typepad.com/blog/2017/08/revit-20181-and-the-visual-materials-api.html)\n- [Revit 2018.1.1 and 2018.1 API Docs Online](http://thebuildingcoder.typepad.com/blog/2017/09/revit-201811-fixes-cropbox-setting.html)\n- [Revit 2018.1 Visual Materials API](http://thebuildingcoder.typepad.com/blog/2017/11/modifying-material-visual-appearance.html)\n\n<center>\n<div style=\"border-style:solid; border-width:2px 0px 2px 0px\">\n<a name=\"5\"></a><h3 style=\"font-weight: bold\">Major Additions to the Revit 2018.1 API</h3>\n</div>\n</center>\n\n###<a name=\"5.1\"></a>Material API additions\n\n####<a name=\"5.1.1\"></a>Editing the properties of an Appearance Asset\n\nNew Revit API capabilities have been introduced to edit the properties contained in an appearance asset of a material. These properties appear in the Appearance tab of the Materials dialog and govern the appearance of the material in realistic views and rendering.\n\nEditing the properties in an appearance Asset requires establishment of an edit scope. The new class\n\n- Autodesk.Revit.DB.Visual.AppearanceAssetEditScope\n\nallows an application to create and maintain an editing session for an appearance asset. The scope provides access to an editable Asset object whose properties may be changed. Once all of the desired changes have been made to the asset's properties, the edit scope should be committed, which causes the changes to be sent back into the document. (This is the only part of the process when a transaction must be opened).\n\nThe new class has the following methods:\n\n- AppearanceAssetEditScope.Start() &ndash; Starts the edit scope for the asset contained in a particular AppearanceAssetElement. The editable Asset is returned from this method.\n- AppearanceAssetEditScope.Commit() &ndash; Finishes the edit scope: all changes made during the edit scope will be committed. Provides an option to forces the update of all open views.\n- AppearanceAssetEditScope.Cancel() &ndash; Cancels the edit scope and discards any changes.\n\n####<a name=\"5.1.2\"></a>Editing AssetProperty values\n\nThe following properties are now writeable from within an AppearanceAssetEditScope, to support modification of an asset property's stored value:\n\n- AssetPropertyString.Value\n- AssetPropertyBoolean.Value\n- AssetPropertyString.Value\n- AssetPropertyInteger.Value\n- AssetPropertyDouble.Value\n- AssetPropertyFloat.Value\n- AssetPropertyEnum.Value\n- AssetPropertyDistance.Value\n\nIn addition, the following new methods have been added to support modification of property values:\n\n- AssetPropertyDouble3.SetValueAsXYZ()\n- AssetPropertyDouble4.SetValueAsDoubles()\n- AssetPropertyDouble4.SetValueAsColor()\n\nAssetPropertyList now has new methods to allow changes to the members of the list:\n\n- AssetPropertyList.AddNewAssetPropertyDouble()\n- AssetPropertyList.InsertNewAssetPropertyDouble()\n- AssetPropertyList.AddNewAssetAsColor()\n- AssetPropertyList.InsertNewAssetAsColor()\n- AssetPropertyList.AddNewAssetPropertyInteger()\n- AssetPropertyList.InsertNewAssetPropertyInteger()\n- AssetPropertyList.RemoveAssetProperty()\n\n####<a name=\"5.1.3\"></a>Connected Assets\n\nConnected assets are associated to properties in appearance assets, and represent subordinate objects encapsulating a collection of related properties. One example of a connected asset is the \"Unified Bitmap\" representing an image and its mapping parameters and values. AssetProperty offers new methods to provide the ability to modify, add or delete the asset connected to a property:\n\n- AssetProperty.GetSingleConnectedAsset() &ndash; Gets the single connected asset of this property.\n- AssetProperty.RemoveConnectedAsset() &ndash; Removes the single connected asset of this property.\n- AssetProperty.AddConnectedAsset (String schemaId) &ndash; Create a new default asset of schema type and connects it to this property.\n- AssetProperty.AddCopyAsConnectedAsset() &ndash; Connects the property to a copy of the asset.\n\n####<a name=\"5.1.4\"></a>Validation\n\nInputs to change the value of asset properties are validated against the requirements of the associated schema. \n\nThe new methods:\n\n- AssetPropertyString.IsValidValue(String)\n- AssetPropertyInteger.IsValidValue (int)\n- AssetPropertyEnum.IsValidValue (int)\n- AssetPropertyDouble.IsValidValue (double)\n- AssetPropertyFloat.IsValidValue (float)\n- AssetPropertyDistance.IsValidValue (double)\n- AssetPropertyDouble3.IsValidValue (XYZ)\n- AssetPropertyDouble4.IsValidValue (IList&lt;double&gt;)\n- AssetPropertyDouble4.IsValidValue (Color)\n\nidentify if the input value is a valid value that can be set to the given asset property.\n\nThe new method: \n\n- AssetProperty.IsEditable()\n\nidentifies whether the AssetProperty can currently be edited.\n\n####<a name=\"5.1.5\"></a>Schemas & Property Names\n\nAppearance asset properties are aligned with specific schemas. Each schema contains necessary properties which define how the appearance of the material will be generated. There are 14 standard material schemas:\n\n- Ceramic\n- Concrete\n- Generic\n- Glazing\n- Hardwood\n- MasonryCMU\n- Metal\n- MetallicPaint\n- Mirror\n- PlasticVinyl\n- SolidGlass\n- Stone\n- WallPaint\n- Water\n\nIn addition, there are 5 schemas representing \"advanced\" materials &ndash; these may be encountered as a result of import from other Autodesk products:\n\n- AdvancedLayered\n- AdvancedMetal\n- AdvancedOpaque\n- AdvancedTransparent\n- AdvancedWood\n\nFinally, there are 10 schemas used for the aspects of the connected assets:\n\n- BumpMap\n- Checker\n- Gradient\n- Marble\n- Noise\n- Speckle\n- Tile\n- UnifiedBitmap\n- Wave\n- Wood\n\nThe new method:\n\n- AssetProperty.IsValidSchemaIdentifier(String schemaName)\n\nidentifies if the input name is a valid name for a supported schema.\n\nTo assist in creating code accessing and manipulating the properties of a given schema, predefined properties have been introduced to allow a compile-time reference to a property name without requiring you to transcribe it as a string in your code. These predefined property names are available in static classes named similar to the schema names, above, e.g. Autodesk.Revit.DB.Visual.Ceramic.\n\n####<a name=\"5.1.6\"></a>Utilities\n\nThe new method:\n\n- Application.GetAssets(AssetType)\n\nreturns a list of assets available to the session.\n\nThe new method: \n\n- AppearanceAssetElement.Duplicate()\n\ncreates a copy of an appearance asset element and the asset contained by it.\n\nThe new operator: \n\n- Asset.operator[]\n\naccesses a particular AssetProperty associated to the given asset. \n\n###<a name=\"5.2\"></a>Geometry API additions\n\n####<a name=\"5.2.1\"></a>Surface API additions\n\nTwo new methods allow projecting a point onto a surface:\n\n- Surface.Project() &ndash; Projects a 3D point orthogonally onto a surface (to find the nearest point).\n- Surface.ProjectWithGuessPoint() &ndash; Projects a 3D point orthogonally onto a surface (to find the nearest point). This method is meant to be used when a good approximate solution for the projection is available.\n\n####<a name=\"5.2.2\"></a>Curve API additions\n\nThe new class:\n\n- ClosestPointsPairBetweenTwoCurves\n\ncaptures the results of computation of closest points between two generic curves.\n\nIt has the following properties:\n\n- ClosestPointsPairBetweenTwoCurves.XYZPointOnFirstCurve &ndash; The point on the first curve in 3d coordinates.\n- ClosestPointsPairBetweenTwoCurves.XYZPointOnSecondCurve &ndash; The point on the second curve in 3d coordinates.\n- ClosestPointsPairBetweenTwoCurves.ParameterOnFirstCurve &ndash; 1d raw (not normalized) parameter of the point on first curve.\n- ClosestPointsPairBetweenTwoCurves.ParameterOnSecondCurve &ndash; 1d raw (not normalized) parameter of the point on second curve.\n- ClosestPointsPairBetweenTwoCurves.Distance &ndash; Distance (as a double) from the point on the first curve to the point on the second curve.\n\nThe new Curve method:\n\n- Curve.ComputeClosestPoints()\n\noutputs a list of closest points between two generic curves using ClosestPointsPairBetweenTwoCurves.\n\n###<a name=\"5.3\"></a>BrowserOrganization API additions\n\nThe new enumerated value: \n\n- BrowserOrganizationType.Schedules \n\ncorresponds to the type of the browser organization definition for schedules. \n\nThe new method:\n\n- BrowserOrganization.GetCurrentBrowserOrganizationForSchedules() \n\ngets the BrowserOrganization that applies to the Schedules section of the project browser.\n\n###<a name=\"5.4\"></a>IFC additions\n\nThe new functions:\n\n- IFCImportOptions.GetExtraOptions()\n- IFCImportOptions.SetExtraOptions()\n\nallow for passing in arbitrary options for custom IFC importers. Users can pass in a string to string map specifying extra data they wish to pass for IFC import.\n\n###<a name=\"5.5\"></a>Rebar API additions\n\n####<a name=\"5.5.1\"></a>BarTypeDiameterOptions\n\nThe new options class:\n\n- BarTypeDiameterOptions\n\nallows creation of a new set of diameter values for a RebarBarType. It can be used when copying the diameter information as a bulk of data from one RebarBarType to another.\n\nThe diameter options can be set for a RebarBarType with the new method:\n\n- Autodesk.Revit.DB.Structure.RebarBarType.setBarTypeDiameters \n\nwhich sets all input diameters from the input BarTypeDiameterOptions in the current RebarBarType.\n\n####<a name=\"5.5.2\"></a>GetDistributionPath()\n\nThe new method:\n\n- Autodesk.Revit.DB.Structure.RebarHandlePositionData.GetDistributionPath()\n\ngets the distribution path currently stored in the rebar.\n\nFor a free form rebar set the distance between two consecutive bars may be different if it is calculated between different points on bars. The distribution path is an array of curves with the property that based on these curves the set was calculated to respect the layout rule and number of bars or spacing.\n\n####<a name=\"5.5.3\"></a>RebarUpdateCurvesData\n\nSeveral new properties have been added to Autodesk.Revit.DB.Structure.RebarUpdateCurvesData:\n\n- Autodesk.Revit.DB.Structure.RebarUpdateCurvesData.HostMirrored &ndash; If true, then host of the rebar was mirrored (along with the rebar) before the most recent regeneration.\n- Autodesk.Revit.DB.Structure.RebarUpdateCurvesData.IsReversed &ndash; Used to store the state of the bar referring to the direction of the bars. This is useful when using face intersection to calculate bars. After mirroring, curves created from intersecting faces may be reversed, so we use this to store the state and keep the rebar pointing in the correct direction.\n- Autodesk.Revit.DB.Structure.RebarUpdateCurvesData.ErrorMessage &ndash; The reason for calculation failure. If the calculation fails, this message will be shown in an error, or warning if we are editing the constraints.\n\n<center>\n<div style=\"border-style:solid; border-width:2px 0px 2px 0px\">\n<a name=\"6\"></a><h3 style=\"font-weight: bold\">Major Additions to the Revit 2018.2 API</h3>\n</div>\n</center>\n\n###<a name=\"6.1\"></a>Fabrication API additions\n\nNew APIs have been added to change the service or size of a selection of fabrication parts. \n\n####<a name=\"6.1.1\"></a>FabricationNetworkChangeService\n\nThe new class:\n\n- Autodesk.Revit.DB.Fabrication.FabricationNetworkChangeService \n\nexposes the ability to change the service or size of a selection of fabrication parts.\n\nIt has the following methods:\n\n- FabricationNetworkChangeService.Create() &ndash; Creates a new instance of a fabrication change service.\n- FabricationNetworkChangeService.ChangeService() &ndash; Changes the service of a selection of element identifiers to the passed in service and group identifiers.\n- FabricationNetworkChangeService.ChangeSize() &ndash; Changes the size of a selection of element identifiers to the passed in map of sizes.\n- FabricationNetworkChangeService.SetSelection() &ndash; The set of element identifiers of fabrication parts to change the service or size for.\n- FabricationNetworkChangeService.SetServiceId() &ndash; Sets the fabrication service identifier to change the elements to.\n- FabricationNetworkChangeService.SetGroupId() &ndash; Sets the fabrication group identifier to change the elements to.\n- FabricationNetworkChangeService.GetInLinePartTypes() &ndash; Gets a set of element identifiers of fabrication part types for in-line parts.\n- FabricationNetworkChangeService.SetMapOfInLinePartTypes() &ndash; Sets the mapping of fabrication part types for in-line parts for the service and group to change to.\n- FabricationNetworkChangeService.GetMapOfAllSizesForStraights() &ndash; Gets a set of FabricationPartSizeMapSet of all straight sizes for all services.\n- FabricationNetworkChangeService.SetMapOfSizesForStraights() &ndash; Sets the mapping for sizes of fabrication part straights to change the sizes to.\n- FabricationNetworkChangeService.Apply() &ndash; Applies the previously set changes to the selection of fabrication parts to change the size, change the service, or both.\n- FabricationNetworkChangeService.GetElementsThatFailed() &ndash; Gets the set of fabrication parts that had failures. Possible reasons are: there was no corresponding part in the service, the size was out of range, or a connection could not be made.\n- FabricationNetworkChangeService.GetStraightsThatWereNotChanged() &ndash; Gets the set of fabrication part straights that were not changed. Possible reasons are: there was no corresponding part in the service, or the size was out of range.\n\n####<a name=\"6.1.2\"></a>FabricationNetworkChangeServiceResult\n\nThe new enum:\n\n- Autodesk.Revit.DB.Fabrication.FabricationNetworkChangeServiceResult\n\nprovides a result status from applying changes to the service or size of fabrication parts.\n\nIt has the following values:\n\n- Success &ndash; The change was successful.\n- PartialFailure &ndash; The change contained partial failures and will need to be fixed manually.\n- UserAborted &ndash; The change was aborted by the user.\n- InvalidSelection &ndash; The selection of fabrication parts was invalid.\n\n####<a name=\"6.1.3\"></a>FabricationPartSizeMap\n\nThe new class:\n\n- Autodesk.Revit.DB.Fabrication.FabricationPartSizeMap\n\nrepresents the fabrication part size map for straights. This class allows is an input to several functions of FabricationNetworkServiceChange, and allows multiple straights of different sizes to be changed at once. \n\nIt has the following properties:\n\n- FabricationPartSizeMap.WidthDiameter &ndash; Gets or sets the width or diameter of the straight\n- FabricationPartSizeMap.Depth &ndash; Gets or sets the depth of the straight.\n- FabricationPartSizeMap.IsProductList &ndash; Gets or sets whether the sizes are for a product listed fabrication part.\n- FabricationPartSizeMap.ProfileType &ndash; Gets or sets the shape of the straight.\n- FabricationPartSizeMap.ServiceId &ndash; Gets or sets the service identifier of the straight.\n- FabricationPartSizeMap.GroupId &ndash; Gets or sets the group identifier of the straight.\n- FabricationPartSizeMap.MappedWidthDiameter &ndash; Gets or sets the mapped width or diameter of the straight.\n- FabricationPartSizeMap.MappedDepth &ndash; Gets or sets the mapped depth of the straight.\n- FabricationPartSizeMap.IsMappedProductList &ndash; Gets or sets whether the mapped sizes are for a product listed fabrication part.\n- FabricationPartSizeMap.MappedProfileType &ndash; Gets or sets the mapped shape of the straight.\n- FabricationPartSizeMap.MappedServiceId &ndash; Gets or sets the mapped service identifier of the straight.\n- FabricationPartSizeMap.AllowMultipleServiceSizes &ndash; Gets or sets the state flag to allow multiple services to include the same size.\n\n####<a name=\"6.2\"></a>Other API additions\n\n####<a name=\"6.2.1\"></a>RevitLinkType API addition\n\nThe new method:\n\n- RevitLinkType.GetLinkedFileStatus()\n\nreturns the LinkedFileStatus enum value indicating the link's load status (loaded, unloaded, missing, etc.). This function returns the same value as ExternalFileReference.GetLinkedFileStatus() but can be called on Collaboration for Revit links."
  }
]