[
  {
    "original_filename": "1610_analyticalmodelsupport",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- 13540959 [GetAnalyticalModelSupports how to use this]\n  https://forums.autodesk.com/t5/revit-api-forum/getanalyticalmodelsupports-how-to-use-this/m-p/7503547\n  /a/doc/revit/tbc/git/a/1608_analyticalmodelsupport.md\n\nHow to Use GetAnalyticalModelSupports in the #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/analyticalmodelsupport\n\nI'm trying to retrieve connected framing elements through the API.\nMy end goal is to select a beam and retrieve the element id of the elements its ends are framing into.\nI have been able to do this by checking location intersection of all other beams, but this scales by <code>n^2</code> based on the number of beams for the check.\nI read the article on finding connected structural elements, but I'm confused on the actual implementation of it.\nHas anybody come across a working example showing how to\ncall <code>GetAnalyticalModelSupports</code>? ...\n\n--->"
  },
  {
    "original_filename": "1610_analyticalmodelsupport",
    "header_text": "How to Use GetAnalyticalModelSupports",
    "local_header_href": "#how-to-use-getanalyticalmodelsupports",
    "chunk_text": "### How to Use GetAnalyticalModelSupports\n\nI highlight yet another thread from \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160),\non [how to use GetAnalyticalModelSupports](https://forums.autodesk.com/t5/revit-api-forum/getanalyticalmodelsupports-how-to-use-this/m-p/7503547),\nanswered by Dragos Turmac, Autodesk Software Engineer, and with additional usage hints by J. Peele, who also raised the question in the first place:\n\n**Question:** I'm trying to retrieve connected framing elements through the API.\n\nMy end goal is to select a beam and retrieve the element id of the elements its ends are framing into.\n \nI have been able to do this by checking location intersection of all other beams, but this scales by `n^2` based on the number of beams for the check.\n \nI read the article \non [finding connected structural elements](http://thebuildingcoder.typepad.com/blog/2011/01/finding-connected-structural-elements.html), \nbut I'm confused on the actual implementation of it.\n\nHas anybody come across a working example showing how to\ncall [`GetAnalyticalModelSupports`](http://www.revitapidocs.com/2018.1/15f01976-9e34-8850-6fa8-79c77a7ed3a4.htm)?\n\nI'm not sure what objects have this property since they all seem to inherit it. Or am I missing an import?\n \nI'm working in Python. Here is the code so far:\n\n<pre class=\"prettyprint\">\n  import clr\n  clr.AddReference('ProtoGeometry')\n  from Autodesk.DesignScript.Geometry import *\n  \n  # Import RevitAPI\n  clr.AddReference('RevitAPI')\n  import Autodesk\n  from Autodesk.Revit.DB import *\n  \n  # Import ToDSType(bool) extension method\n  clr.AddReference('RevitNodes')\n  import Revit\n  clr.ImportExtensions(Revit.Elements)\n  \n  from Autodesk.Revit.DB.Structure import *\n  \n  # The inputs to this node will be stored as a list in the IN variables.\n  dataEnteringNode = IN\n  \n  if isinstance(IN[0], list):\n    elements = [UnwrapElement(i) for i in IN[0]]\n  else:\n    elements = [UnwrapElement(IN[0])]\n  \n  AnalyticalEl = [element.GetAnalyticalModel() for element in elements]\n  \n  # Assign your output to the OUT variable.\n  OUT = AnalyticalEl;\n</pre>\n\nThanks so much for any help you can give.\n\n**Answer:** Does this snippet work for you and answer your question?\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">AnalyticalModel</span>&nbsp;model\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;aWallFoundation.GetAnalyticalModel()&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">AnalyticalModel</span>;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;==&nbsp;model&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">continue</span>;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;<span style=\"color:#2b91af;\">AnalyticalModelSupport</span>&gt;&nbsp;supports&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;model.GetAnalyticalModelSupports();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;ids&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">AnalyticalModelSupport</span>&nbsp;m&nbsp;<span style=\"color:blue;\">in</span>&nbsp;supports&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;ids.Add(&nbsp;m.GetSupportingElement()&nbsp;);\n&nbsp;&nbsp;}\n</pre>\n\n**Response:** Finally got it working yesterday.\n\nThis code does the trick, though the problem was a conceptual oversight on my part.\n\nI was imagining the supports would be similar to what pressing tab on a beam element does; however, it seems the supports are actually the members involved in the gravity load path.\n\nMore importantly, the analytical supports will be null if Revit has 'Automatic Member Supports' turned off (as it should be, Revit is unusably slow on large projects with it on).\n\nI had to run a manual support check before anything would show up.\n \nHope this helps anyone having similar issue to what I ran into. Also, if there is any way to programmatically get the connected beams similar to how tab behaviour works, I would still be interested to learn how.\n\nMany thanks to Dragos and J. for raising and solving this issue!\n\n<center>\n<img src=\"img/rst_framing_supports.png\" alt=\"Structural framing supports\" width=\"323\"/>\n</center>"
  }
]