[
  {
    "original_filename": "1626_newfamilysymbolprofile",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<!--\n<script src=\"run_prettify.js\" type=\"text/javascript\"></script>\n<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\" type=\"text/javascript\"></script>\n-->\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- implemented NewFamilySymbolProfile sample app\n  https://github.com/jeremytammik/NewFamilySymbolProfile\n  13871503 [Sweep Profile From Family]\n  https://forums.autodesk.com/t5/revit-api-forum/sweep-profile-from-family/m-p/7751112\n  https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115\n\nNewFamilySymbolProfile sample #RevitAPI add-in @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/newfamilysymbolprofile\n\nQuestions on how to use <code>NewFamilySymbolProfile</code> have come up a couple of times in the Revit API discussion forum.\nThe short answer is: retrieve the family symbol from the profile family, then call the creation application <code>NewFamilySymbolProfile</code> method.\nI implemented a new sample add-in for you to demonstrate the steps using the <i>Profiles_L-Angles.rfa</i> profile family...\n\n--->"
  },
  {
    "original_filename": "1626_newfamilysymbolprofile",
    "header_text": "NewFamilySymbolProfile Sample Add-In",
    "local_header_href": "#newfamilysymbolprofile-sample-add-in",
    "chunk_text": "### NewFamilySymbolProfile Sample Add-In\n\nI've been answering rather a lot of queries in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) lately,\nleading me to once again become [top solution author](#2); here is one of the latest:\n\n####<a name=\"1\"></a>How to use NewFamilySymbolProfile\n\nQuestions on how to use `NewFamilySymbolProfile` have come up a couple of times, e.g., in the following threads:\n\n- [Load profile for `NewSweep` command](https://forums.autodesk.com/t5/revit-api-forum/load-profile-for-newsweep-command/td-p/5117864)\n- [Sweep using profile family](https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115)\n- [Sweep profile from family](https://forums.autodesk.com/t5/revit-api-forum/sweep-profile-from-family/m-p/7751112)\n\nIn the second, Revitalizer provides a succinct answer, saying:\n\n> The next step after retrieving the family symbol from the profile family is to call\n> the [`Autodesk.Revit.Creation.Application` `NewFamilySymbolProfile` method](http://www.revitapidocs.com/2018.1/0fd22223-8ca8-2955-e2ee-7d83d853ee8f.htm):\n\n<pre class=\"code\">\n  FamilySymbolProfile\n    Application.NewFamilySymbolProfile(\n      FamilySymbol familySymbol )\n</pre>\n \nHowever, the first two thread answers were insufficiently complete and clear, hence the third follow-up thread.\n\n**Question:** I want to pass a profile from an existing profile family to `FamilyCreate.NewSweep`.\n\nI looked at the thread\non [loading a profile for the `NewSweep` command](https://forums.autodesk.com/t5/revit-api-forum/load-profile-for-newsweep-command/td-p/5117864).\n\nJeremy's comments from this post indicate that the profile family cannot be passed directly, but that the profile geometry needs to be recreated. Am I reading this correctly?\n\nYou can certainly retrieve a profile for a sweep operation from a family file.\n\nHowever, the family file does not provide any provision for storing a profile per se, so you will have to make use of the other geometrical options available in that context to define some kind of geometry specifying the sweep profile.\n\nYou can then parse that geometry, extract the profile information, and put together the required curve array in your add-in.\n\nAs mentioned in some other Sweep posts, there are many samples that create a new profile, but none that accept a `FamilySymbolProfile` directly.\n\nCan this be done?\n\n**Answer:** This question was actually answered in the thread\non [sweep using profile family](https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115).\n\nOne first needs to create a `FamilySymbolProfile` object from the `FamilySymbol` generated by loading the profile Family, then use the  `FamilyFactory.NewSweep` method passing in the `FamilySymbolProfile` as `SweepProfile`.\n\nI implemented a new sample\nadd-in [NewFamilySymbolProfile](https://github.com/jeremytammik/NewFamilySymbolProfile) for\nyou to demonstrate the steps using the *Profiles_L-Angles.rfa* profile family.\n\n- C:/Users/All Users/Autodesk/RVT 2018/Libraries/UK/Profiles/Framing/Steel/Profiles_L-Angles.rfa\n\n<center>\n<img src=\"img/l_angle_rfa.png\" alt=\"UK Profiles Framing Steel Profiles_L-Angles.rfa\" width=\"177\"/>\n</center>\n\nHere is the code:\n\n<pre class=\"code\">\n<span style=\"color:blue;\">#region</span>&nbsp;Namespaces\n<span style=\"color:blue;\">using</span>&nbsp;System.Collections.Generic;\n<span style=\"color:blue;\">using</span>&nbsp;System.Diagnostics;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.ApplicationServices;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.Attributes;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.DB;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.UI;\n<span style=\"color:blue;\">#endregion</span>\n \n<span style=\"color:blue;\">namespace</span>&nbsp;NewFamilySymbolProfile\n{\n&nbsp;&nbsp;[<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;<span style=\"color:#2b91af;\">TransactionMode</span>.Manual&nbsp;)]\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">class</span>&nbsp;<span style=\"color:#2b91af;\">Command</span>&nbsp;:&nbsp;<span style=\"color:#2b91af;\">IExternalCommand</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">const</span>&nbsp;<span style=\"color:blue;\">string</span>&nbsp;_filepath&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;C:/Users/All&nbsp;Users/Autodesk&quot;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;/RVT&nbsp;2018/Libraries/UK/Profiles/Framing/Steel&quot;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;/Profiles_L-Angles.rfa&quot;</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>&nbsp;Execute(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ExternalCommandData</span>&nbsp;commandData,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">ref</span>&nbsp;<span style=\"color:blue;\">string</span>&nbsp;message,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementSet</span>&nbsp;elements&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIApplication</span>&nbsp;uiapp&nbsp;=&nbsp;commandData.Application;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UIDocument</span>&nbsp;uidoc&nbsp;=&nbsp;uiapp.ActiveUIDocument;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Application</span>&nbsp;app&nbsp;=&nbsp;uiapp.Application;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;uidoc.Document;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;profile_doc&nbsp;=&nbsp;app.OpenDocumentFile(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_filepath&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;The&nbsp;profile&nbsp;document&nbsp;contains&nbsp;no&nbsp;family&nbsp;sybols:</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;symbols\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;profile_doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">FamilySymbol</span>&nbsp;)&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Debug</span>.Assert(&nbsp;0&nbsp;==&nbsp;symbols.GetElementCount(),&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;expected&nbsp;no&nbsp;family&nbsp;symbol&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Load&nbsp;the&nbsp;profile&nbsp;family&nbsp;to&nbsp;generate&nbsp;them:</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilySymbol</span>&nbsp;profile_symbol&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Load&nbsp;Profile&nbsp;Family&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Family</span>&nbsp;family;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;doc.LoadFamily(&nbsp;_filepath,&nbsp;<span style=\"color:blue;\">out</span>&nbsp;family&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ISet</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;ids&nbsp;=&nbsp;family.GetFamilySymbolIds();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;id&nbsp;<span style=\"color:blue;\">in</span>&nbsp;ids&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profile_symbol&nbsp;=&nbsp;doc.GetElement(&nbsp;id&nbsp;)&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">FamilySymbol</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Debug</span>.Print(&nbsp;profile_symbol.Name&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Generate&nbsp;the&nbsp;family&nbsp;symbol&nbsp;profile:</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilySymbolProfile</span>&nbsp;fsp&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;profile_symbol&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Create&nbsp;FamilySymbolProfile&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fsp&nbsp;=&nbsp;app.Create.NewFamilySymbolProfile(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profile_symbol&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Succeeded;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n}\n</pre>\n\nThe comments explain all the important steps.\n \n####<a name=\"2\"></a>Top Solution Author\n\nAs said, I have been answering rather a lot of queries lately, leading to a new top solution author record score of 37, afaik:\n\n<center>\n<img src=\"img/2018-02-08_top_solution_author_37.png\" alt=\"Top solution author\" width=\"231\"/>\n</center>"
  }
]