[
  {
    "original_filename": "1691_floor_area_why_hide",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- 14660821 [Get the Floor Area above a Room]\n  https://forums.autodesk.com/t5/revit-api-forum/get-the-floor-area-above-a-room/m-p/8295372\n\n- very illuminating discussion on:\n  mysterious element hiding activity performed by Revit in a newly created 3D view, what is causing it, how to resolve it\n  [Made a new 3DView. It's empty. Why?](https://forums.autodesk.com/t5/revit-api-forum/made-a-new-3dview-it-s-empty-why/m-p/8285271)\n  the kind of problems a newbie to Revit runs into, in spite of being experienced in other CAD systems:\n  > I've coded in CATIA, Rhino, AutoCAD, and Maya for years without any issues, but I've never had such trouble than when I want to do the simplest things in Revit.\n  Fair59 explains in loving, detailed, didactic depth... very many thanks indeed for your continued invaluable support!\n\nFloor area above room and mysterious hidden elements in new 3D view in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/floorarea\n\nToday, we focus on two pure programming questions from the Revit API discussion forum\n&ndash; Area of an exterior floor above a room\n&ndash; Mysterious element hiding activity...\n\n-->"
  },
  {
    "original_filename": "1691_floor_area_why_hide",
    "header_text": "Floor Area Above Room and Mysterious Hide",
    "local_header_href": "#floor-area-above-room-and-mysterious-hide",
    "chunk_text": "### Floor Area Above Room and Mysterious Hide\n\nToday, let's take a break from the last two\nday's [Forge](https://autodesk-forge.github.io)\n[Design Automation API](https://forge.autodesk.com/en/docs/design-automation/v2/overview) for Revit explorations\non [swallowing warnings](http://thebuildingcoder.typepad.com/blog/2018/09/swallowing-stairsautomation-warnings.html)\nand [auto-running an add-in](http://thebuildingcoder.typepad.com/blog/2018/09/auto-run-an-add-in-for-design-automation.html) and\nfocus on two pure programming questions from\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread instead:\n\n- [Area of an exterior floor above a room](#2) \n- [Mysterious element hiding activity](#3)"
  },
  {
    "original_filename": "1691_floor_area_why_hide",
    "header_text": "<a name=\"2\"></a> Area of an Exterior Floor Above a Room",
    "local_header_href": "#a-name2a-area-of-an-exterior-floor-above-a-room",
    "chunk_text": "#### <a name=\"2\"></a> Area of an Exterior Floor Above a Room\n\nSicheng Zhu asked how\nto [get the floor area above a room](https://forums.autodesk.com/t5/revit-api-forum/get-the-floor-area-above-a-room/m-p/8295372):\n\n**Question:** I want to get the exterior floor area above a room, assuming that the floors are modelled separately and I already know which floor is an exterior floor:\n\n<center>\n<img src=\"img/findexteriorfloorarea0.png\" alt=\"Find exterior floor area above room\" width=\"400\">\n</center>\n\nI want a common solution. Sometimes the floor area is the same as the room area. Sometimes its projection is within the room boundaries. Sometimes they have intersections:\n\n<center>\n<img src=\"img/findexteriorfloorarea1.png\" alt=\"Find exterior floor area above room\" width=\"400\">\n</center>\n\nPerhaps we can use the class `SolidCurveIntersection` to get the intersected curves and discuss in situations?\n\nPerhaps you can figure out some better solutions?\n\n**Answer:** Thank you for your interesting query.\n\nFor a completely generic solution, it seems to me that you will require a 2D Boolean operation.\n\nThe Revit geometry API does not provide that built-in, but you can\neasily [integrate an external 2D Boolean operations library](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.2).\n\nOnce you have the 2D Boolean operations in place, you can easily create two overlapping horizontal polygons:\n\n- Retrieving the room boundary curves and creating a contiguous curve loop from them.\n- Projecting the floor boundary curves, projecting them onto the room top surface, and creating a contiguous curve loop from them.\n\nHere is an example of [projecting and transforming a polygon in Revit](http://thebuildingcoder.typepad.com/blog/2008/12/polygon-transformation.html).\n\nThis assumes your wall segments are straight, and not curved.\n\nIf they are curved, I would suggest using the curve tessellation provided by the Revit geometry API to convert them to straight segments.\n\nWith two overlapping 2D polygons and a 2D Boolean operation in place, I hope your problem is perfectly solved in a totally 'common' way."
  },
  {
    "original_filename": "1691_floor_area_why_hide",
    "header_text": "<a name=\"3\"></a> Mysterious Element Hiding Activity",
    "local_header_href": "#a-name3a-mysterious-element-hiding-activity",
    "chunk_text": "#### <a name=\"3\"></a> Mysterious Element Hiding Activity\n\nI would also like to highlight one more\nof Frank [@Fair59](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/2083518) Aarssen's very illuminating answers.\n\nThis one explores the mysterious element hiding activity performed by Revit in a newly created 3D view, what is causing it, how to resolve it:\n\n- [Made a new 3DView. It's empty. Why?](https://forums.autodesk.com/t5/revit-api-forum/made-a-new-3dview-it-s-empty-why/m-p/8285271)\n\nIt also demonstrates the kind of problems a newbie to Revit commonly runs into, in spite of being experienced in other CAD systems:\n\n> I've coded in CATIA, Rhino, AutoCAD, and Maya for years without any issues, but I've never had such trouble than when I want to do the simplest things in Revit.\n\nFair59 explains in with care and loving, detailed, didactic depth...\n\n**Question:** I created a new 3D view.\n\nBut it doesn't anything.\n\nWhy?\n\nPlease help.\n\nNote: When I iterate through all the objects found using a `FilteredElementCollector` on that specific 3d View, it returns over 9000 elements with their respective element ids.  That means there is geometry in that view, but for some reason it's not visible in 3D.\n\nI tried various ViewOrientations and nothing appears in my view.\n\nNothing is working.\n\nThis seems really dumb and simple.  Does anyone have a simple portion of Revit API code that makes a 3D view, and has objects in it?  What is the proper way to make a 3D View in these API's?\n\nI've coded in CATIA, Rhino, AutoCAD, and Maya for years without any issues, but I've never had such trouble than when I want to do the simplest things in Revit.\n\n**Answer:** Yes, indeed, it can help a lot if you can manage to forget what you know about programming other CAD systems before diving into the Revit API... [Revit and its API is different](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.41).\n\nFirst of all, you might want to make a list of the error elements to see the Revit classes to which they belong:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;errorIds;\n&nbsp;&nbsp;StringBuilder&nbsp;sb&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;StringBuilder();\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;id&nbsp;<span style=\"color:blue;\">in</span>&nbsp;errorIds&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;=&nbsp;doc.GetElement(&nbsp;id&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;sb.AppendLine(&nbsp;<span style=\"color:blue;\">string</span>.Format(&nbsp;<span style=\"color:#a31515;\">&quot;&lt;{0}&gt;&nbsp;{1}&nbsp;&nbsp;[{2}]&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id,&nbsp;e.Name,&nbsp;e.GetType()&nbsp;)&nbsp;);\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;debug&quot;</span>,&nbsp;sb.ToString()&nbsp;);\n</pre>\n\nI think you should make your own ViewFamilyType, without ViewTemplate so all elements are Visible on creation.\n\nYou can then hide all elements (that can be hidden) except the error elements.\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;errorIds;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>&nbsp;viewFamilyType&nbsp;=&nbsp;(&nbsp;<span style=\"color:blue;\">from</span>&nbsp;v&nbsp;<span style=\"color:blue;\">in</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Cast&lt;<span style=\"color:#2b91af;\">ViewFamilyType</span>&gt;()\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">where</span>&nbsp;v.ViewFamily&nbsp;==&nbsp;<span style=\"color:#2b91af;\">ViewFamily</span>.ThreeDimensional\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">select</span>&nbsp;v&nbsp;).First();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View3D</span>&nbsp;view;\n&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">TransactionGroup</span>&nbsp;tg&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">TransactionGroup</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;tg.Start(&nbsp;<span style=\"color:#a31515;\">&quot;create&nbsp;Error&nbsp;View&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Create&nbsp;Issues&nbsp;View&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;create&nbsp;new&nbsp;ViewFamilyType&nbsp;without&nbsp;ViewTemplate</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>&nbsp;my_type&nbsp;=&nbsp;viewFamilyType\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Duplicate(&nbsp;<span style=\"color:#a31515;\">&quot;Error_View&quot;</span>&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">ViewFamilyType</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;my_type.get_Parameter(&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.DEFAULT_VIEW_TEMPLATE&nbsp;).Set(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>.InvalidElementId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view&nbsp;=&nbsp;<span style=\"color:#2b91af;\">View3D</span>.CreateIsometric(&nbsp;doc,&nbsp;my_type.Id&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Hide&nbsp;DWG,&nbsp;Analytical&nbsp;Categories,&nbsp;Annotaion</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.AreImportCategoriesHidden&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.AreAnalyticalModelCategoriesHidden&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.AreCoordinationModelHandlesHidden&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.AreAnnotationCategoriesHidden&nbsp;=&nbsp;<span style=\"color:blue;\">true</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Hide&nbsp;RVT&nbsp;Links</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.SetCategoryHidden(&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ElementId</span>(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_RvtLinks&nbsp;),&nbsp;<span style=\"color:blue;\">true</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;show&nbsp;Parts</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.get_Parameter(&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.VIEW_PARTS_VISIBILITY&nbsp;).Set(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;elemsInView\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc,&nbsp;view.Id&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Excluding(&nbsp;errorIds&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;elemsToHide&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">List</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;();\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;<span style=\"color:blue;\">in</span>&nbsp;elemsInView&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;e.CanBeHidden(&nbsp;view&nbsp;)&nbsp;)&nbsp;elemsToHide.Add(&nbsp;e.Id&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;hide&nbsp;elements&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.HideElements(&nbsp;elemsToHide.ToList()&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;tg.Assimilate();\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">this</span>.ActiveUIDocument.ActiveView&nbsp;=&nbsp;view;\n&nbsp;&nbsp;<span style=\"color:blue;\">this</span>.ActiveUIDocument.ShowElements(&nbsp;errorIds&nbsp;);\n</pre>\n\nLast thing to check (if needed) visibility of worksets; turn on all worksets, e.g., using `view.SetWorksetVisibility`.\n\n**Response:** Thank you for your detailed answer.  I like your approach.\n\nI have a few questions.\n\n- It looks like we are duplicating the first view found via the filter criteria, so the file is basically taking an existing view and duplicating it.\nIs that better than the `Create` method?\n- Then you are getting a parameter and setting it to an ElementId enumeration of invalid element?  Why?  Is ElementId.InvalidElementId not an enumeration?\n- What is this line setting the `VIEW_PARTS_VISIBILITY` parameter doing exactly?  Why `2`?\n\n<pre class=\"code\">\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view.get_Parameter(&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.VIEW_PARTS_VISIBILITY&nbsp;).Set(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;);\n</pre>\n\nAll of this is really good.  I'll try it out.  I have seen most of what you are providing, but never employed it in that way.  Much smarter looping and filtering in your suggestion than my original code, but I'm still negotiating how Revit works.\n\n**Answer:** *Regarding 'Why duplicate?'*\n\nIt is not duplicating an existing view, but duplicating an existing `ViewFamilyType`.\n\nBecause I don't know which elements are on the `errorId` list, I want to make sure that all elements are visible. A view has a `ViewFamilyType`. The `ViewFamilyType` can have a `ViewTemplate` (which regulates visibility / non-visibility of categories)  assigned to it, that will be applied to newly created views. As I want all elements visible, I want to use a `ViewFamilyType` without a `ViewTemplate`. To avoid messing with the model, I duplicate the first `ViewFamilyType` found, and remove the `ViewTemplate` from it.\n\n<pre class=\"code\">\n&nbsp;&nbsp;my_type.get_Parameter(\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.DEFAULT_VIEW_TEMPLATE&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Set(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>.InvalidElementId&nbsp;);\n</pre>\n\n`ElementId.InvalidElementId` is the equivalent to null for an ElementId value, meaning, do not assign a `ViewTemplate`.\n\nThen I use this `ViewFamilyType` to create the 3D view.\n\n*Regarding `BuiltInParameter.VIEW_PARTS_VISIBILITY`*:\n\nRevit has the possibility to [divide (system) families into `Parts`](htttp://help.autodesk.com/view/RVT/2018/ENU/?guid=GUID-DA150C6B-996C-4C70-9E8C-3C536C232851).\n\nA view can show either the original element, the parts, or both. By setting the `BuiltInParameter` to `2`, I set the view to show the original element and the parts.\n\nOnce again, very many thanks indeed to Fair59 for your continued invaluable support!"
  }
]