[
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- https://forums.autodesk.com/t5/revit-api-forum/efficiently-find-the-sum-of-room-areas-with-f-tailoryourbim-com/m-p/8348542\n  [Find Sum Area Of Rooms / 空間面積總合](https://tailoryourbim.com/2018/10/20/find-sum-area-of-rooms-%E7%A9%BA%E9%96%93%E9%9D%A2%E7%A9%8D%E7%B8%BD%E5%90%88)\n  [Finding The Sum of Areas](https://forums.autodesk.com/t5/revit-architecture-forum/finding-the-sum-of-areas/m-p/7860005)\n\n- https://forums.autodesk.com/t5/forums/replypage/board-id/160/message-id/34351\n  [Efficiently Control View for Design Option Elements with F# - tailoryourbim.com]()\n  After the last post about efficiently find the sum of room areas, in the new post we'll see about how to control the color of the elements within Design Options in active view:\n  [View Control for Design Option Elements / 圖形取代設計選項中的物件顏色](http://tailoryourbim.com/2018/10/27/view-control-for-design-option-elements-%e5%9c%96%e5%bd%a2%e5%8f%96%e4%bb%a3%e8%a8%ad%e8%a8%88%e9%81%b8%e9%a0%85%e4%b8%ad%e7%9a%84%e7%89%a9%e4%bb%b6%e9%a1%8f%e8%89%b2/)\n  When we work with design options in Revit, we often have more than one design option group in the same model file. By default in Revit 2017, I haven't found a way to display them distinctivly in view. Writing a small external command as posted here might help at work.\n\n- create legend view\n  http://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html#comment-4158350001\n  Håvard Dagsvik\n  Old post and still no methods for creating legend views and components.\n  But it an be done by copying a legend view and component from a background file using ElementTransformUtils. In the background file group an instance of a legend component. Copy the GroupType and the legend view from the file. Once copied place the GroupType in the copied legend view and ungroup it.\n  Ungroup will leave you with a \"new\" legend component in your new legend view.\n  This way you can create a legend view incl component from scratch.\n  A bit of a hack but it works.\n\n- Forge - RVT to IFC\n  According to the Nexus team,\n  https://autodesk.slack.com/archives/C1B7QGXQE/p1515646460000003\n  https://autodesk.slack.com/archives/C1B7QGXQE/p1515661878000256\n  https://autodesk.slack.com/archives/C1B7QGXQE/p1515663483000604\n  https://jira.autodesk.com/browse/RVTLMV-14\n\n- lat/long in IFC exported from Revit\n\n- takeoff with no fitting\n\nTailor Your BIM with F#, Forge IFC tranlation, lat/long in IFC and takeoff creation in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/fstakeoff\n\nI have a whole bunch of exciting overdue topics lined up.\nLet's start with these\n&ndash; Tailor Your BIM sums room areas with F#\n&ndash; Control view for design option elements with F#\n&ndash; Copy legend view and component from background file\n&ndash; Forge RVT to IFC translation defaults to 2x3\n&ndash; Latitude and longitude in Revit IFC export\n&ndash; Takeoff creation requires branch duct...\n\n-->"
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "Tailor Your BIM with F#, Forge, IFC and Takeoffs",
    "local_header_href": "#tailor-your-bim-with-f-forge-ifc-and-takeoffs",
    "chunk_text": "### Tailor Your BIM with F#, Forge, IFC and Takeoffs\n\nI have a whole bunch of exciting overdue topics lined up.\n\nLet's start with these:\n\n- [Tailor Your BIM sums room areas with F#](#2) \n- [Control view for design option elements with F#](#3) \n- [Copy legend view and component from background file](#4) \n- [Forge RVT to IFC translation defaults to 2x3](#5) \n- [Latitude and longitude in Revit IFC export](#6) \n- [Takeoff creation requires branch duct](#7) \n\n<center>\n<img src=\"img/takeoff_curve_connector.png\" alt=\"Takeoff curve connector\" width=\"224\">\n</center>"
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"2\"></a> Tailor Your BIM Sums Room Areas with F&#35;",
    "local_header_href": "#a-name2a-tailor-your-bim-sums-room-areas-with-f35",
    "chunk_text": "#### <a name=\"2\"></a> Tailor Your BIM Sums Room Areas with F&#35;\n\n[Ching](https://tailoryourbim.com/about)-[Hua Chen](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/5219233) shared\nseveral nice F# Revit API macros on\nhis blog [Tailor Your BIM](https://tailoryourbim.com).\n\nAs you know, the .NET framework enables you to use any supported programming language you like, and F# is a fully viable option with some advantages.\n\nChing pointed out his blog and new post in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [efficiently finding the sum of room areas with F#](https://forums.autodesk.com/t5/revit-api-forum/efficiently-find-the-sum-of-room-areas-with-f-tailoryourbim-com/m-p/8348542):\n\nWhile working on Revit, I noticed there could be a few possibilities to improve the efficiency when retrieving the sum of room areas by writing external commands. I posted an external command with F# and Revit API that instantly reports the sum of selected room areas. I would like to share this knowledge with you:\n\n- [Find sum of room areas / 空間面積總合](https://tailoryourbim.com/2018/10/20/find-sum-area-of-rooms-%E7%A9%BA%E9%96%93%E9%9D%A2%E7%A9%8D%E7%B8%BD%E5%90%88) <br/>(alternating Chinese and English text)\n\nThis solution also addresses a related thread in the Revit Architecture forum \non [finding the sum of areas](https://forums.autodesk.com/t5/revit-architecture-forum/finding-the-sum-of-areas/m-p/7860005)."
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"3\"></a> Control View for Design Option Elements with F&#35;",
    "local_header_href": "#a-name3a-control-view-for-design-option-elements-with-f35",
    "chunk_text": "#### <a name=\"3\"></a> Control View for Design Option Elements with F&#35;\n\nChing followed that up with a second post\non an [efficient control view for Design Option elements with F#](https://forums.autodesk.com/t5/revit-api-forum/efficiently-control-view-for-design-option-elements-with-f/m-p/8365817#M34366),\nsaying:\n\nAfter the last post about efficiently find the sum of room areas, in the new post, we'll see how to control the colour of the elements within Design Options in the active view:\n\n- [View control for Design Option elements / <br/>圖形取代設計選項中的物件顏色](http://tailoryourbim.com/2018/10/27/view-control-for-design-option-elements-%e5%9c%96%e5%bd%a2%e5%8f%96%e4%bb%a3%e8%a8%ad%e8%a8%88%e9%81%b8%e9%a0%85%e4%b8%ad%e7%9a%84%e7%89%a9%e4%bb%b6%e9%a1%8f%e8%89%b2/)\n\nWhen we work with design options in Revit, we often have more than one design option group in the same model file. By default, in Revit 2017, I haven't found a way to display them distinctively in the view. Writing a small external command as posted here might help at work.\n\nMany thanks to Ching for these nice contributions!"
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"4\"></a> Copy legend view and component from background file",
    "local_header_href": "#a-name4a-copy-legend-view-and-component-from-background-file",
    "chunk_text": "#### <a name=\"4\"></a> Copy legend view and component from background file\n\nHåvard Dagsvik shared a new suggestion for creating a legend view in\na [comment](http://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html#comment-4158350001)\non [duplicating a legend component](https://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html):\n\nOld post and still no methods for creating legend views and components.\n\nBut it can be done by copying a legend view and component from a background file using `ElementTransformUtils`. In the background file group an instance of a legend component. Copy the GroupType and the legend view from the file. Once copied place the GroupType in the copied legend view and ungroup it.\n\nUngroup will leave you with a 'new' legend component in your new legend view.\n\nThis way you can create a legend view incl. component from scratch.\n\nA bit of a hack but it works.\n\n**Answer:** Yes, sorry that nothing has happened yet in this area.\n\nI have collected a bunch of existing wishes for this and submitted them in the wish list item *CF-4442 [API support for legends -- 07320991]*.\n\nHave you checked whether a wish list item for this functionality has also been submitted to the Revit Idea Station?\n\nThat is one of the main driving forces for setting priorities on developer wishes.\n\nPlease do so, submit it if it does not exist, vote for it if it does, and let me know, so I can add that input to the development issue as well.\n\n**Response:** The biggest wish regarding legends would be to add support for using standard tags on Legend Components. So, a Door Tag for a door legend, etc. It's the one thing I've been checking in new Revit versions since 2009. Basically, be able to tag the Type Properties of a component.\nA couple of threads on that here:\n\n- [Allow tags in legend views](https://forums.autodesk.com/t5/revit-ideas/allow-tags-in-legend-views/idi-p/6598921)\n- [Tag Legend Component](https://forums.autodesk.com/t5/revit-ideas/tag-legend-component/idi-p/7952189)\n\nHere is the API request\n\n- [API for creating Legend views and Legend components](https://forums.autodesk.com/t5/revit-ideas/api-for-creating-legend-views-and-legend-components/idi-p/8352835)\n\nMany thanks to Håvard for his valuable input.\n\nI added his notes to the wish list item as well."
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"5\"></a> Forge RVT to IFC Translation Defaults to 2x3",
    "local_header_href": "#a-name5a-forge-rvt-to-ifc-translation-defaults-to-2x3",
    "chunk_text": "#### <a name=\"5\"></a> Forge RVT to IFC Translation Defaults to 2x3\n\nNow for some IFC related notes.\n\n**Question:** Regarding translation of RVT to IFC via Forge Model Derivative: are there any known issues, limitations or good practices, pls?\n\n**Answer:** The Revit extractor will look for saved IFC Export Setup Options stored in RVT files including built-in and user created setups to do the RVT to IFC translation.\n\nThey can specify a name of the IFC export settings in the `output.advanced.exportSettingName` field of the POST body while calling the Forge MD POST Jobs API.\n\nCurrently, user modified IFC Mapping Files are not supported.\n\nHowever, there is currently a known issue with the `output.advanced.exportSettingName`. Unfortunately, the specified IFC Exporting option will not be assigned properly to the Revit extractor. Afaik, we can currently only get the file exported in the default IFC 2x3 format."
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"6\"></a> Latitude and Longitude in Revit IFC Export",
    "local_header_href": "#a-name6a-latitude-and-longitude-in-revit-ifc-export",
    "chunk_text": "#### <a name=\"6\"></a> Latitude and Longitude in Revit IFC Export\n\nHere is another little IFC related issue, while we are at it:\n\nQ: How is the lat/long information from an IFC exported from Revit read by Navisworks?\n\nThis image shows what we see in Revit and how it shows up in Navisworks via the IFC export:\n\n<center>\n<img src=\"img/lat_long_in_nw_from_rvt_ifc.jpg\" alt=\"IFC lat/long information\" width=\"1099\">\n</center>\n\nHow is this information exported to IFC? Is any formula applied to these values?\n\n**Answer:** Lat/long is stored in IFC as a quadruple of integers: degrees, minutes, seconds, and millionths of a second.\n\nThe fourth value is new to IFC2x3 and was added after a request from us.\n\nNavisworks seems to just be displaying the raw values.\n\nMaybe Navisworks needs to parse this information more correctly."
  },
  {
    "original_filename": "1698_takeoff_forge_ifc",
    "header_text": "<a name=\"7\"></a> Takeoff Creation Requires Branch Duct",
    "local_header_href": "#a-name7a-takeoff-creation-requires-branch-duct",
    "chunk_text": "#### <a name=\"7\"></a> Takeoff Creation Requires Branch Duct\n\n**Question:** I want to programmatically connect a takeoff fitting onto the body of a duct, the other end of takeoff may or may not be connected to another duct's connector:\n\n<center>\n<img src=\"img/duct_takeoff.png\" alt=\"Duct takeoff\" width=\"416\">\n</center>\n\nIn this image, I draw a 12' long and 2' diameter duct from (0, 0, 0) to (12, 0, 0) at 3' height and attach a takeoff to the middle of this duct.\n\nThat gives the following connector locations on these two elements:\n\n<pre>\n  TAKEOFF\n    connector #1: (6, 1.3333, 3)\n    connector #2: (6, 1, 3)\n  DUCT\n    connector #1: (12, 0, 3)\n    connector #2: (6, 0, 3)\n    connector #3: (0, 0, 3)\n</pre>\n\nI've noticed that the duct in the image by default has two connectors which are connector #1 and connector #3. The connector #2 is added when connecting with a takeoff.\n\nWhat are the steps to attach a takeoff fitting onto a duct body by using Revit API?\n\n**Answer:** Have you looked at the AutoRoute sample in the Revit SDK, and tried using `NewTakeoffFitting` instead of `NewTeeFitting`?\n\n**Response:** Yes, I looked at these functions. `NewTakeoffFitting` requires a `Connector` and a `MEPCurve` as arguments; both cannot be null, otherwise it throws an `ArgumentNullException`.\n\nIn example above, I purposely draw a takeoff which only attaches to one duct and does not connect to another duct or fitting (Connector). Revit allows the creation of systems like this. Do API functions allow me to create this as well?\n\n**Answer:** How did you create that tap in the UI?  I don't think that Revit will let you place a tap fitting connected on a duct without actually routing a duct, and I think the API has the same limitation.\n\n**Response:** One way is to make sure the routing preferences uses tap, draw two connected ducts so it creates a tap, then delete one duct. I have not tried to connect a takeoff directly on the body of duct, not sure if that can be done.\n\nMy task is to capture the state of the user's design and enable the user to restore and recreate the exact same design and same drawing later reading back the data we stored. The user's design may not be the final design yet, so the source drawing can be anything that Revit allows. So, what is shown on the image is a valid drawing that our plugin needs to recreate on a project drawing.\n\nI can handle other fitting types when they are not connecting to other element on some of their connectors. When the connection is needed, I just call `Connector.ConnectTo`. I am not sure what to do with takeoff when it needs to attach to a duct body at a location like that.\n\nSo, right now, our plugin handles takeoff in special condition. I use the `NewTakeoffFitting` function to create it, but if it does not connect to a duct body and another connector, the plugin will just not draw it at all.\n\nMaybe the other question to ask is: when can I use the API to create the third connector in a duct element without breaking this duct into two?\n\n**Answer:** I think you'll have to do as you suggest: route a branch duct to create the tap off the main, then delete the branch duct.  When you place a takeoff fitting, it should be creating the third connector, and not break the main into two pieces.  \n\n**Response:** Which API function is used to create the third connector in a duct for the case above? \n\n**Answer:** Revit handles the curve connectors automagically. Any time there is a tap on an element, the third (or additional) connectors are added. When the tap(s) are removed, the connectors are automatically removed.  I wouldn't expect there to be a way to add/remove connectors independent of taps.\n\n`NewTakeoffFitting` seems to be the only function to connect takeoff for now.\n\nFor the takeoff to be placed, the API function needs to have a temporary branch duct to create the takeoff. Once created, the branch duct can be removed. I don't believe the ability to create a curve connector is exposed to the API.\n\nThe Building Coder presented two examples of creating takeoffs a long time ago:\n\n- [Use of NewTakeOffFitting on a Duct](http://thebuildingcoder.typepad.com/blog/2011/02/use-of-newtakeofffitting-on-a-duct.html)\n- [Use of NewTakeOffFitting on a Pipe](http://thebuildingcoder.typepad.com/blog/2011/04/use-of-newtakeofffitting-on-a-pipe.html)"
  }
]