[
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n\ntwitter:\n\nSetting the material texture path in EditScope in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/texturepath\n\nLukáš Kohout brought up an interesting and important issue on changing material texture path with <code>EditScope</code>\n&ndash; How to set the material texture path?\n&ndash; Suggestions\n&ndash; Solution and sample material\n&ndash; <code>ChangeRenderingTexturePath</code> method\n&ndash; Step by step guide\n&ndash; Test run...\n\nlinkedin:\n\nSetting the material texture path in EditScope in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/texturepath\n\nLukáš Kohout brought up an interesting and important issue on changing material texture path with EditScope:\n\n- How to set the material texture path?\n- Suggestions\n- Solution and sample material\n- <code>ChangeRenderingTexturePath</code> method\n- Step by step guide\n- Test run...\n\n-->"
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "Set Material Texture Path in EditScope",
    "local_header_href": "#set-material-texture-path-in-editscope",
    "chunk_text": "### Set Material Texture Path in EditScope\n\nLukáš [kohoulu3](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/767846) Kohout\nbrought up an interesting and important issue in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [changing material texture path with `EditScope`](https://forums.autodesk.com/t5/revit-api-forum/changing-material-texture-path-with-editscope/m-p/8017578) that\nI wanted to highlight last year. Here it is, finally:\n\n- [How to set the material texture path?](#2) \n- [Suggestions](#3) \n- [Solution and sample material](#4) \n- [`ChangeRenderingTexturePath` method](#5) \n- [Step by step guide](#6) \n- [Test run](#7)"
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"2\"></a> How to Set the Material Texture Path?",
    "local_header_href": "#a-name2a-how-to-set-the-material-texture-path",
    "chunk_text": "#### <a name=\"2\"></a> How to Set the Material Texture Path?\n\nI am trying to set material texture path using following code (Revit 2018):\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">void</span>&nbsp;ChangeRenderingTexturePath(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Material</span>&nbsp;mat,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;texturePath&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetElement</span>&nbsp;appearanceAsset\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">AppearanceAssetElement</span>)&nbsp;doc.GetElement(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;renderingAsset&nbsp;=&nbsp;appearanceAsset\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetRenderingAsset();\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;size&nbsp;=&nbsp;renderingAsset.Size;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">for</span>(&nbsp;<span style=\"color:blue;\">int</span>&nbsp;assetIdx&nbsp;=&nbsp;0;&nbsp;assetIdx&nbsp;&lt;&nbsp;size;&nbsp;assetIdx++&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;aProperty&nbsp;=&nbsp;renderingAsset[assetIdx];\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;aProperty.NumberOfConnectedProperties&nbsp;&lt;&nbsp;1&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">continue</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;aProperty.GetConnectedProperty(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Asset</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;connectedAsset.Name&nbsp;==&nbsp;<span style=\"color:#a31515;\">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>&nbsp;path&nbsp;=&nbsp;connectedAsset.FindByName(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>&nbsp;editScope&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset&nbsp;=&nbsp;editScope.Start(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Exception&nbsp;thrown,&nbsp;asset&nbsp;is&nbsp;read&nbsp;only,&nbsp;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;need&nbsp;to&nbsp;use&nbsp;editScope</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editScope.Commit(&nbsp;<span style=\"color:blue;\">true</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n</pre>\n\nI know that editScope accepts only ElementId (specifically AppearanceElementAsset.Id), but with this I cannot get to edit the texture path that is saved in `RenderingAsset` of the `AppearanceAsset`.\n\nDo anyone know any way to get around this?\n\nFinally, we can create materials with API, but without textures? Does not make sense.\n\nI am using the latest Revit 2018 API with the asset editing functionality included.\n\nI am able to duplicate and edit `AppearanceAsset`.\n\nI have searched The Building Coder and read both the relevant posts:\n\n- [Modifying Material Visual Appearance](http://thebuildingcoder.typepad.com/blog/2017/11/modifying-material-visual-appearance.html)\n- [Material Texture Path](http://thebuildingcoder.typepad.com/blog/2017/10/material-texture-path.html)\n\nThe way I obtain the current texture path is taken directly from the latter.\n\nProblem with the texture path as I see it is, that it is not directly contained in the `AppearanceAsset` but in the connected `RenderingAsset`. And to that I cannot get through the `EditScope`. `RenderingAsset` has no `ElementId` and cannot be used in the `AppearanceAssetEditScope.Start` function.\n\nException message:\n\n<pre>\n  An exception of type 'Autodesk.Revit.Exceptions.InvalidOperationException' occurred in RevitAPI.dll but was not handled in user code.\n  Additional information: The asset property is not editable. Asset can be edited only in an edit scope.\n</pre>\n\nProblem is that the returned asset from `AppearanceAssetEditScope.Start` does not contain the desired `UnifiedBitmapSchema` property. That property is contained only in the `RenderingAsset`."
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"3\"></a> Suggestions",
    "local_header_href": "#a-name3a-suggestions",
    "chunk_text": "#### <a name=\"3\"></a> Suggestions\n\nThe only editable asset inside the edit scope is the one returned from `AppearanceAssetEditScope.Start`, and those connected assets which it directly returns.\n \nI think if you reverse your code and get the `UnifiedBitmapSchema` from the returned asset from `Start`, you will be able to change it.\n\nI'd recommend starting from the code snippet which shows how to do this, available from the [help documentation on `GetSingleConnectedAsset`](Http://www.revitapidocs.com/2018.1/3a190829-9269-0e56-8b9b-a53b89de35a6.htm)."
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"4\"></a> Solution and Sample Material",
    "local_header_href": "#a-name4a-solution-and-sample-material",
    "chunk_text": "#### <a name=\"4\"></a> Solution and Sample Material\n\nThanks Jeremy. Finally, I got it to work. It was quite simple, actually, in the end.\n\nThere is just one small change from the code snippet I posted at first.\n\nHere is the (MaterialTexturePath.zip archive)[zip/lk_MaterialTexturePath.zip] containing\nthe entire sample Visual Studio solution with detailed guide as well as a sample project and texture to demonstrate.\n\nI hope that someone finds this useful."
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"5\"></a> ChangeRenderingTexturePath Method",
    "local_header_href": "#a-name5a-changerenderingtexturepath-method",
    "chunk_text": "#### <a name=\"5\"></a> ChangeRenderingTexturePath Method\n\nHere is the final code:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">void</span>&nbsp;ChangeRenderingTexturePath(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;As&nbsp;there&nbsp;is&nbsp;only&nbsp;one&nbsp;material&nbsp;in&nbsp;the&nbsp;sample&nbsp;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;project,&nbsp;we&nbsp;can&nbsp;use&nbsp;FilteredElementCollector&nbsp;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;and&nbsp;grab&nbsp;the&nbsp;first&nbsp;result</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Material</span>&nbsp;mat&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">Material</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.FirstElement()&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Material</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Fixed&nbsp;path&nbsp;for&nbsp;new&nbsp;texture</span>\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Texture&nbsp;included&nbsp;in&nbsp;sample&nbsp;files</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;texturePath&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.Combine(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Environment</span>.GetFolderPath(&nbsp;<span style=\"color:#2b91af;\">Environment</span>.<span style=\"color:#2b91af;\">SpecialFolder</span>.Desktop&nbsp;),&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;new_texture.png&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Changing&nbsp;material&nbsp;texture&nbsp;path&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>&nbsp;editScope&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">AppearanceAssetEditScope</span>(&nbsp;doc&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;editableAsset&nbsp;=&nbsp;editScope.Start(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Getting&nbsp;the&nbsp;correct&nbsp;AssetProperty</span>\n<span style=\"color:blue;\">#if</span>&nbsp;VERSION2018\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetProperty</span>&nbsp;assetProperty&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset[<span style=\"color:#a31515;\">&quot;generic_diffuse&quot;</span>];\n<span style=\"color:blue;\">#elif</span>&nbsp;VERSION2019\n<span style=\"color:gray;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AssetProperty&nbsp;assetProperty&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset.FindByName(&quot;generic_diffuse&quot;);\n</span><span style=\"color:blue;\">#endif</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;assetProperty\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetConnectedProperty(&nbsp;0&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Asset</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Getting&nbsp;the&nbsp;right&nbsp;connected&nbsp;Asset</span>\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;connectedAsset.Name&nbsp;==&nbsp;<span style=\"color:#a31515;\">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>&nbsp;path&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;connectedAsset.FindByName(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;)&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">AssetPropertyString</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;path.IsValidValue(&nbsp;texturePath&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editScope.Commit(&nbsp;<span style=\"color:blue;\">true</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;Material&nbsp;texture&nbsp;path&quot;</span>,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Material&nbsp;texture&nbsp;path&nbsp;changed&nbsp;to:\\n&quot;</span>&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;texturePath&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Dispose();\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n</pre>"
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"6\"></a> Step by Step Guide",
    "local_header_href": "#a-name6a-step-by-step-guide",
    "chunk_text": "#### <a name=\"6\"></a> Step by Step Guide\n\nHere are the steps to reproduce the solution:\n\nGoal:\n\n- I want to create materials in Revit programmatically, so would not have to create thousands of materials (NCS palette) by hand.\n\nThat is quite simple with the new Revit 2018.1 API and the sample code provided.\n\nFurthermore, for some materials, I want to change the texture as well, and that was bit of a problem.\n\nSolution:\n\n- Retrieve the \"generic_diffuse\" `AssetProperty` from the asset returned from `AppearanceAssetEditScope.Start`.\n- Retrieve the first `ConnectedProperty` as `Asset`.\n- From that, retrieve the `UnifiedBitmap.UnifiedbitmapBitmap` `AssetPropertyString`.\n- Set its value.\n\nGuide to reproduce the solution:\n\n1. Open MaterialTexturePath.sln in Visual Studio.\n2. Reload references RevitAPI.dll, RevitAPIUI.dll and RevitAddinUtility.dll from your local folder (usually, where you have Revit installed).\n3. Build the project for the Revit version you want; works only for Revit 2018 and Revit 2019.\n4. Copy contents of the output folder to *C:\\ProgramData\\Autodesk\\Revit\\Addins\\&lt;revit_version&gt;*.\n5. Copy the sample texture (new_texture.png file) to your desktop.\n6. Open the sample project.\n7. Go to Manage/Materials and see the texture path in the only present material in the project.\n8. Navigate to the Add-Ins ribbon tab and click the Change texture path button.\n9. Go to Manage/Materials again and note that the texture path changed."
  },
  {
    "original_filename": "1735_editscope_texture",
    "header_text": "<a name=\"7\"></a> Test Run",
    "local_header_href": "#a-name7a-test-run",
    "chunk_text": "#### <a name=\"7\"></a> Test Run\n\nHere are screen snapshots illustrating some of the steps from my test run:\n\nStore the sample texture file on desktop:\n\n<center>\n<img src=\"img/material_texture_path_texture.png\" alt=\"Sample texture file on desktop\" width=\"88\">\n</center>\n\nOpen the sample model and observe the instructions:\n\n<center>\n<img src=\"img/material_texture_path_instruction.png\" alt=\"Instructions\" width=\"475\">\n</center>\n\nThe sample model contains one single sample material:\n\n<center>\n<img src=\"img/material_texture_path_sample.png\" alt=\"Sample material\" width=\"500\">\n</center>\n\nClick the sample command in its custom ribbon panel:\n\n<center>\n<img src=\"img/material_texture_path_cmd.png\" alt=\"Ribbon panel and command\" width=\"245\">\n</center>\n\nThe add-in displays a message on completion:\n\n<center>\n<img src=\"img/material_texture_path_msg.png\" alt=\"Result message\" width=\"372\">\n</center>\n\nThe sample material texture is updated:\n\n<center>\n<img src=\"img/material_texture_path_sample_updated.png\" alt=\"Updated sample material\" width=\"500\">\n</center>\n\nMany thanks to Lukáš for his research, putting together and documenting this sample so well!"
  }
]