[
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\ntwitter:\n\nFace.Intersect face treats faces as unbounded; handling that, source code colourisation and updated add-in wizard for the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/faceintersect\n\nMy work on setting up a new PC is nearing completion.\nThere is also a need to clarify the use of the <code>Face.Intersect(Face)</code> method\n&ndash; The unbounded <code>Face.Intersect</code> method\n&ndash; Making use of the unbounded face intersection\n&ndash; Rectangular face intersection ideas\n&ndash; Copy as HTML update\n&ndash; Visual Studio Revit add-in wizard update...\n\nlinkedin:\n\nFace.Intersect face treats faces as unbounded; handling that, source code colourisation and updated add-in wizard for the #RevitAPI\n\nhttp://bit.ly/faceintersect\n\nMy work on setting up a new PC is nearing completion.\n\nThere is also a need to clarify the use of the Face.Intersect(Face) method:\n\n- The unbounded Face.Intersect method\n- Making use of the unbounded face intersection\n- Rectangular face intersection ideas\n- Copy as HTML update\n- Visual Studio Revit add-in wizard update...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<p style=\"font-size: 80%; font-style:italic\"></p>\n\n-->"
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Face Intersect Face is Unbounded",
    "local_header_href": "#face-intersect-face-is-unbounded",
    "chunk_text": "### Face Intersect Face is Unbounded\n\nMy work on setting up a new PC is nearing completion.\n\nThere is also a need to clarify the use of the `Face.Intersect(Face)` method:\n\n- [The unbounded `Face.Intersect` method](#2)\n- [Making use of the unbounded face intersection](#3)\n- [Rectangular face intersection ideas](#4)\n- [Copy as HTML update](#5)\n- [Visual Studio Revit add-in wizard update](#6)"
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "The Unbounded Face.Intersect Method",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> The Unbounded Face.Intersect Method\n\nSeveral [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) threads are discussing the status of\nthe [Face.Intersect (Face) method](https://www.revitapidocs.com/2020/91f650a2-bb95-650b-7c00-d431fa613753.htm):\n\n- [Surprising results from `Face.Intersect(Face)` method](https://forums.autodesk.com/t5/revit-api-forum/surprising-results-from-face-intersect-face-method/m-p/8992586)\n- [Problems with `Intersect` method (`Face`)](https://forums.autodesk.com/t5/revit-api-forum/problems-with-intersect-method-face/m-p/8992566)\n- [Get connection type and geometry between two elements from the model](https://forums.autodesk.com/t5/revit-api-forum/get-conection-type-and-geometry-between-two-elements-from-the/m-p/6465671)\n- [`Face` class `Intersect` method problem](https://forums.autodesk.com/t5/revit-api-forum/face-class-intersect-method-problem/m-p/7460720)\n\nBriefly, the main problem is this:\n\n**Question:** This issue was mentioned in 2016, in the third thread listed above, but it is worth bringing up again, as the issue hasn't been resolved yet in 2018.\n\nAs far as I can tell, the `Face.Intersect(face)` method always returns `FaceIntersectionFaceResult.Intersecting`.\n\nWhen I run the code below in a view with a single wall and single floor, each face to face test returns an intersection:\n\n<center>\n<img src=\"img/face_intersect_face_1.png\" alt=\"Non-intersecting faces\" width=\"657\">\n</center>\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>&nbsp;Execute(\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ExternalCommandData</span>&nbsp;commandData,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">ref</span>&nbsp;<span style=\"color:blue;\">string</span>&nbsp;message,\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementSet</span>&nbsp;elements&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;list&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commandData.Application.ActiveUIDocument.Document,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commandData.View.Id&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Where(&nbsp;e&nbsp;=&gt;&nbsp;e&nbsp;<span style=\"color:blue;\">is</span>&nbsp;<span style=\"color:#2b91af;\">Wall</span>&nbsp;||&nbsp;e&nbsp;<span style=\"color:blue;\">is</span>&nbsp;<span style=\"color:#2b91af;\">Floor</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;f1&nbsp;<span style=\"color:blue;\">in</span>&nbsp;list.First()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.get_Geometry(&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Options</span>()&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfType&lt;<span style=\"color:#2b91af;\">Solid</span>&gt;().First()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Faces.OfType&lt;<span style=\"color:#2b91af;\">Face</span>&gt;()&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;f2&nbsp;<span style=\"color:blue;\">in</span>&nbsp;list.Last()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.get_Geometry(&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Options</span>()&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfType&lt;<span style=\"color:#2b91af;\">Solid</span>&gt;().First()\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Faces.OfType&lt;<span style=\"color:#2b91af;\">Face</span>&gt;()&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;f1.Intersect(&nbsp;f2&nbsp;)&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;==&nbsp;<span style=\"color:#2b91af;\">FaceIntersectionFaceResult</span>.Intersecting&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBox</span>.Show(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Intersects&quot;</span>,&nbsp;<span style=\"color:#a31515;\">&quot;Continue&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBoxButtons</span>.OKCancel,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBoxIcon</span>.Exclamation&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;==&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">DialogResult</span>.Cancel&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Succeeded;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:#2b91af;\">Result</span>.Succeeded;\n&nbsp;&nbsp;}\n</pre>\n\n**Answer:** Thank you for your report and reproducible case.\n\nI see the same behaviour in Revit 2019 as well.\n\nI added some code to The Building Coder samples\nin [CmdIntersectJunctionBox.cs](https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdIntersectJunctionBox.cs#L27-L116) to\ntest and report in more depth:\n\n<pre class=\"code\">\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;Return&nbsp;all&nbsp;faces&nbsp;from&nbsp;first&nbsp;solid&nbsp;&nbsp;</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;of&nbsp;the&nbsp;given&nbsp;element.</span>\n<span style=\"color:gray;\">///</span><span style=\"color:green;\">&nbsp;</span><span style=\"color:gray;\">&lt;/</span><span style=\"color:gray;\">summary</span><span style=\"color:gray;\">&gt;</span>\n<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Face</span>&gt;&nbsp;GetFaces(&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;e&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Options</span>&nbsp;opt&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Options</span>();\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Face</span>&gt;&nbsp;faces&nbsp;=&nbsp;e\n&nbsp;&nbsp;&nbsp;&nbsp;.get_Geometry(&nbsp;opt&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfType&lt;<span style=\"color:#2b91af;\">Solid</span>&gt;()\n&nbsp;&nbsp;&nbsp;&nbsp;.First()\n&nbsp;&nbsp;&nbsp;&nbsp;.Faces\n&nbsp;&nbsp;&nbsp;&nbsp;.OfType&lt;<span style=\"color:#2b91af;\">Face</span>&gt;();\n&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;n&nbsp;=&nbsp;faces.Count();\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Debug</span>.Print(&nbsp;<span style=\"color:#a31515;\">&quot;{0}&nbsp;has&nbsp;{1}&nbsp;face{2}.&quot;</span>,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;e.GetType().Name,&nbsp;n,&nbsp;<span style=\"color:#2b91af;\">Util</span>.PluralSuffix(&nbsp;n&nbsp;)&nbsp;);\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;faces;\n}\n \n<span style=\"color:blue;\">void</span>&nbsp;TestIntersect(&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">View</span>&nbsp;view&nbsp;=&nbsp;doc.ActiveView;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;list&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc,&nbsp;view.Id&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsNotElementType()\n&nbsp;&nbsp;&nbsp;&nbsp;.Where(&nbsp;e&nbsp;=&gt;&nbsp;e&nbsp;<span style=\"color:blue;\">is</span>&nbsp;<span style=\"color:#2b91af;\">Wall</span>&nbsp;||&nbsp;e&nbsp;<span style=\"color:blue;\">is</span>&nbsp;<span style=\"color:#2b91af;\">Floor</span>&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;n&nbsp;=&nbsp;list.Count();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;floor&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;wall&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;2&nbsp;==&nbsp;n&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;floor&nbsp;=&nbsp;list.First()&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Floor</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;==&nbsp;floor&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;floor&nbsp;=&nbsp;list.Last()&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Floor</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wall&nbsp;=&nbsp;list.First()&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Wall</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wall&nbsp;=&nbsp;list.Last()&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Wall</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;==&nbsp;floor&nbsp;||&nbsp;<span style=\"color:blue;\">null</span>&nbsp;==&nbsp;wall&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Util</span>.ErrorMsg(&nbsp;<span style=\"color:#a31515;\">&quot;Please&nbsp;run&nbsp;this&nbsp;command&nbsp;in&nbsp;a&nbsp;&quot;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;document&nbsp;with&nbsp;just&nbsp;one&nbsp;floor&nbsp;and&nbsp;one&nbsp;wall&nbsp;&quot;</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;with&nbsp;no&nbsp;mutual&nbsp;intersection&quot;</span>&nbsp;);\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Options</span>&nbsp;opt&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Options</span>();\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Face</span>&gt;&nbsp;floorFaces&nbsp;=&nbsp;GetFaces(&nbsp;floor&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Face</span>&gt;&nbsp;wallFaces&nbsp;=&nbsp;GetFaces(&nbsp;wall&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;0;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;f1&nbsp;<span style=\"color:blue;\">in</span>&nbsp;floorFaces&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:blue;\">var</span>&nbsp;f2&nbsp;<span style=\"color:blue;\">in</span>&nbsp;wallFaces&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;f1.Intersect(&nbsp;f2&nbsp;)&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;==&nbsp;<span style=\"color:#2b91af;\">FaceIntersectionFaceResult</span>.Intersecting&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++n;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBox</span>.Show(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Intersects&quot;</span>,&nbsp;<span style=\"color:#a31515;\">&quot;Continue&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBoxButtons</span>.OKCancel,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">MessageBoxIcon</span>.Exclamation&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;==&nbsp;System.Windows.Forms.<span style=\"color:#2b91af;\">DialogResult</span>.Cancel&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Debug</span>.Print(&nbsp;<span style=\"color:#a31515;\">&quot;{0}&nbsp;face-face&nbsp;intersection{1}.&quot;</span>,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n,&nbsp;<span style=\"color:#2b91af;\">Util</span>.PluralSuffix(&nbsp;n&nbsp;)&nbsp;);\n&nbsp;&nbsp;}\n}\n</pre>\n\nHere is a simple test model with a disjunct floor and wall:\n\n<center>\n<img src=\"img/floor_wall_disjunct.png\" alt=\"Disjunct floor and wall\" width=\"388\">\n</center>\n\nMy sample code reports:\n\n<pre>\n  Floor has 7 faces.\n  Wall has 6 faces.\n  38 face-face intersections.\n</pre>\n\nSo, in fact, not every face-to-face test reports an intersection, because 7*6 equals 42.\n\nOnly the vast majority do &nbsp; :-)\n\nI logged the issue *REVIT-133627 [Face.Intersect returns false positives]* with our development team to explore this further and provide an explanation.\n\nThis turned out to be a duplicate of an existing older issue, *REVIT-58034 [API Face.Intersect(Face) returns true even if two faces don't intersect with each other]* and was therefore closed again.\n\nThe development team replied:\n\n> We are aware of this issue.\nThis function does indeed not do what one expects.\nAt most, it computes intersections between the underlying (unbounded) surfaces, not the (bounded) faces lying in the surfaces.\nAs a first step, the documentation will be updated to reflect this fact.\nThen, we'll see whether resources can be found to fully implement the face intersection functionality, or remove the incomplete functionality.\n\nAs a result, *REVIT-58034* was renamed. Currently, the following related tickets have all been closed:\n\n- REVIT-58034 [Improve documentation for API Face.Intersect(Face) to reflect what the function actually does] \n- REVIT-133627 [Face.Intersect returns false positives] \n- REVIT-133819 [Improve API Face.Intersect(Face) to actually intersect faces, not underlying surfaces]"
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Making Use of the Unbounded Face Intersection",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Making Use of the Unbounded Face Intersection\n\nFrank [@Fair59](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/2083518) Aarssen adds:\n\nI have previously plotted the intersections using the `ByRef` curve overload and found this to be the case, as explained in the thread \non the [`Face` class `Intersect` method problem](https://forums.autodesk.com/t5/revit-api-forum/face-class-intersect-method-problem/m-p/7460720):\n\n> Apparently, the intersecting faces are considered infinite with therefore many possible intersections beyond the range of the element itself. \n\n> In this image, the green lines are plotted using curves from the overload `Face.Intersect(ByVal Face, ByRef Curve)`:\n\n<center>\n<img src=\"img/face_intersect_wall_intersects.png\" alt=\"Unbounded face intersections between two walls\" width=\"930\">\n</center>\n\n> Hard to understand at first why they all exist, but once you trace along parallel to the faces, you can see all are valid.\n\nIn actual fact, an API user may prefer to find this form of intersection, rather than be told no intersection exists (due to the bounds of the face preventing it).\n\nYou can always compare points on the original face to those on the curve intersect result to check if there is an actual intersection.\n\nHowever, if no results were given, then that would not be useful at all.\n\nProbably, there should be a bound versus unbound option, perhaps."
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Rectangular Face Intersection Ideas",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Rectangular Face Intersection Ideas\n\nThe sample images shown above all include rectangular wall faces.\n\nIf the potentially intersecting faces  are rectangular, the problem can presumably be reduced to a pretty simple query.\n\nOne approach would be to retrieve the intersection curves of the unbounded faces and test whether they lie on the bounded faces, as suggested above by Frank.\n\nAlternatively, a DIY solution may also be feasible and more efficient.\n\nAfter all, a rectangular face can be seen as two coplanar triangles, and the intersection of 3D triangles is a pretty common requirement.\n\nHere are some useful-looking results that showed up in a couple of quick Internet searches:\n\n- [A Fast Triangle-Triangle Intersection Test](https://web.stanford.edu/class/cs277/resources/papers/Moller1997b.pdf)\n- [Efficient AABB/triangle intersection in C#](https://stackoverflow.com/questions/17458562/efficient-aabb-triangle-intersection-in-c-sharp)\n- [How do I find the Intersection of two 3D triangles?](https://math.stackexchange.com/questions/1220102/how-do-i-find-the-intersection-of-two-3d-triangles)\n- [Algorithms for ray (or segment) and triangle intersection, triangle-plane and triangle-triangle intersection](http://geomalgorithms.com/a06-_intersect-2.html)\n\nIf anyone would like to share a reliable, robust, and efficient 3D triangle or rectangle intersection algorithm, please let us know.\n\nThank you!"
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Copy as HTML Update",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> Copy as HTML Update\n\nI implemented and installed a couple of \ndifferent [source code colourizer tools](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.36) in\nthe past.\n\nThis spring, I set up \nthe [PowerTools 2015 Copy HTML Markup](https://thebuildingcoder.typepad.com/blog/2019/04/close-doc-and-zero-doc-rvtsamples.html#4) functionality.\n\nOn the new computer, I updated to Visual Studio 2017 instead of Visual Studio 2015.\n\nAccordingly, I update the code colouriser\nto [Productivity Power Tools 2017/2019](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerPack2017)."
  },
  {
    "original_filename": "1773_face_intersect_face",
    "header_text": "Visual Studio Revit Add-In Wizard Update",
    "local_header_href": "#6",
    "chunk_text": "####<a name=\"6\"></a> Visual Studio Revit Add-In Wizard Update\n\nIn the same vein, I reinstalled\nthe [Visual Studio Revit Add-In Wizards](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.20),\nagain, slightly updated for Visual Studio 2017, captured\nin [VisualStudioRevitAddinWizard release 2020.0.0.2)](https://github.com/jeremytammik/VisualStudioRevitAddinWizard/releases/tag/2020.0.0.2)."
  }
]