[
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n</head>\n\n<!---\n\n\ntwitter:\n\n- post the news about Design Automation webinars\n  https://forge.autodesk.com/blog/design-automation-api-webinar-series-register-now\n  /a/doc/revit/tbc/git/a/img/da_for_air3.png\n \n- Nice sample showing two stacked ribbon items versus 3:\n  24x24 StackedItems\n  https://forums.autodesk.com/t5/revit-api-forum/24x24-stackeditems/m-p/9168470\n\n- Very important hint from Fair59 on reinitialising the filtered element collector\n  https://forums.autodesk.com/t5/revit-api-forum/collection-of-elements-created-using-elementworksetfilter-giving/m-p/9164018\n  This misunderstanding caused a similar problem in another recent case...\n\nPainless introduction to Forge Design Automation API, creating two stacked ribbon items, reinitialising filtered element collectors and picking a face in a linked file using the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon http://bit.ly/pickfaceinlink\n\nThe ultimatively painless introduction to the Forge Design Automation API, a solution for creating two stacked ribbon items, reinitialising filtered element collectors and picking a face in a linked file\n&ndash; Forge Design Automation API webinars\n&ndash; Stacking two 24x24 ribbon items\n&ndash; Reinitialising the filtered element collector\n&ndash; Use <code>CreateReferenceInLink</code> to select a face in a linked file...\n\nlinkedin:\n\nPainless introduction to Forge Design Automation API, creating two stacked ribbon items, reinitialising filtered element collectors and picking a face in a linked file using the #RevitAPI\n\nhttp://bit.ly/pickfaceinlink\n \n- Forge Design Automation API webinars\n- Stacking two 24x24 ribbon items\n- Reinitialising the filtered element collector\n- Use CreateReferenceInLink to select a face in a linked file...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<p style=\"font-size: 80%; font-style:italic\"></p>\n\n-->"
  },
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Design Automation API, Stacks, Collectors and Links",
    "local_header_href": "#design-automation-api-stacks-collectors-and-links",
    "chunk_text": "### Design Automation API, Stacks, Collectors and Links\n\nIf you are looking for the ultimatively painless introduction to the Forge Design Automation API, you are in luck: the Design Automation webinars are coming up soon.\n\nIf you are more interested in the desktop Revit API, the solution for creating two stacked ribbon items instead of three might be more to your taste.\n\nIn either case, the tip on reinitialising a filtered element collector before reusing it is importantissimo in both contexts:\n\n- [Forge Design Automation API webinars](#2)\n- [Stacking two 24x24 ribbon items](#3)\n- [Reinitialising the filtered element collector](#4)\n- [Use `CreateReferenceInLink` to select a face in a linked file](#5)\n\n<center>\n<img src=\"img/da_for_air3.png\" alt=\"Forge Design Automation API for AutoCAD, Inventor, Revit and 3DS Max\" width=\"400\"> <!--800-->\n</center>"
  },
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Forge Design Automation API Webinars",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Forge Design Automation API Webinars\n\nA new series of webinars on\nthe [Forge Design Automation APIs for AutoCAD, Inventor, Revit and 3DS Max](https://forge.autodesk.com/en/docs/design-automation/v3/developers_guide/overview/) is\ncoming up.\n\nYou can register now to participate and also to gain access to the recordings that will be posted after the live events.\n\nThere is still time to get hands on with the new Design Automation APIs.\nFour webinars are scheduled in December that will cover each of the Design Automation APIs in depth.\nThe recordings will be posted after so be sure to register to take advantage.\n\nAll webinars begin at 8:00 AM Pacific Standard Time.\n\n- <u>AutoCAD</u> &ndash; December 5\n<br/>Design Automation API for AutoCAD on Forge &ndash; <u>Albert Szilvasy</u>, software Architect will share details about the new and updated API.\n<br/>This webinar discusses how the Design Automation for AutoCAD empowers customers and partners to get more work done more quickly, reliably and collaboratively using cloud-based web services.\nWe will demonstrate the ability to run scripts on your design files, leveraging the scale of the Forge Platform to automate repetitive tasks.\n&ndash; [Register](https://autodesk.zoom.us/webinar/register/WN_n-yZWaSNSW-OIMJRDdJBZw)\n- <u>Revit</u> &ndash; December 10\n<br/>Design Automation API for REVIT on Forge &ndash; <u>Sasha Crotty</u>, Senior Product Manager, Revit Platform & Services to share updates on this API.\n<br/>This webinar discusses how the Design Automation for Revit empowers customers and partners to get more work done more quickly, reliably and collaboratively using cloud-based web services.\nWe will demonstrate how you can automate your most common, manual, and error-prone work to improve responsiveness and free up your time so you can focus on more valuable work. \n&ndash; [Register](https://autodesk.zoom.us/webinar/register/WN_50PU3thnSfC8m-Rh2PE2Ag)\n- <u>Inventor</u> &ndash; December 11\n<br/>Design Automation API for Inventor on Forge &ndash; <u>Andrew Akenson</u>, software Architect will shares details about the new and updated APIs added to the Design Automation for Inventor on Forge.\n<br/>This webinar discusses how the Design Automation for Inventor empowers customers and partners to get more work done more quickly, reliably and collaboratively using cloud-based web services.\nWe will demonstrate how you can automate your most common, manual, and error-prone work to improve responsiveness and free up your time so you can focus on more valuable work.\n&ndash; [Register](https://autodesk.zoom.us/webinar/register/WN_8poFofy4QWCfq0ciL0AYjg)\n- <u>3DS Max</u> &ndash; December 12\n<br/>Design Automation API for 3ds Max on Forge &ndash; <u>Kevin Vandecar</u>, Developer Advocate on the Forge Partner Development team will share details about the newly launched Design Automation API for 3ds Max on Forge.\n<br/>In this webinar, we will discuss how the Design Automation for 3ds Max empowers customers and partners to get more work done more quickly, reliably and collaboratively using cloud-based web services.\nUsing automation routines, you can build custom solutions using 3ds Max in the cloud.\nNo local resources are needed, so it could be a commercial website/configurator type webapp, or it could be a pipeline automation that run from your in-house tools.\nThe sky (or rather the cloud) is the limit.\nWe will demonstrate how you can easily automate common workflows in 3ds Max.\n&ndash; [Register](https://autodesk.zoom.us/webinar/register/WN_7jTFtqz3Tte76LswrUACvw)"
  },
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Stacking Two 24x24 Ribbon Items",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Stacking Two 24x24 Ribbon Items\n\nJameson Nyp, BIM Manager and IS Director at [Telios Engineering](https://teliospc.com) in Dallas, Texas, shares a nice solution for stacking two ribbon items in\nhis [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [24x24 StackedItems](https://forums.autodesk.com/t5/revit-api-forum/24x24-stackeditems/m-p/9168470):\n\n**Question:** This may be an easy one, but so far I am struggling to find anything specific about it.\n\nHow do you make a `StackedItem` where the icons are 24x24 when there are only 2 in the stack?\n\nIt seems like it should be possible, as it is used multiple times in the modify tab:\n\n<center>\n<img src=\"img/modify_tab_icon_sizes.png\" alt=\"Modify tab icon sizes\" width=\"246\"> <!--246-->\n</center>\n\nI have been able to set the `ShowText` property to false to get the 3 stacked icons, but when I use the same methodology with the 2-icon stack, it remains 16x16, regardless of the icon resolution.\n\nI tried to obtain and change the button's height and width, minWidth and minHeight through the Autodesk.Window.RibbonItem object to no avail.\n\nHas anyone had any success in creating these icons?\n\n**Answer:** I found a solution.\n\nIn order to display the button at the 24x24 size, the Autodesk.Windows.RibbonItem.Size needs to be manually set to Autodesk.Windows.RibbonItemSize.Large enum and a 24x24 icon needs to be set to the button's `LargeImage` property.\n\nHere is a code sample:\n\n<pre class=\"code\">\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.UI;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Windows;\n<span style=\"color:blue;\">using</span>&nbsp;System.Collections.Generic;\n<span style=\"color:blue;\">using</span>&nbsp;System.IO;\n<span style=\"color:blue;\">using</span>&nbsp;System.Reflection;\n<span style=\"color:blue;\">using</span>&nbsp;System.Windows.Media.Imaging;\n<span style=\"color:blue;\">using</span>&nbsp;YourCustomUtilityLibrary;\n \n<span style=\"color:blue;\">namespace</span>&nbsp;ReallyCoolAddin\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">class</span>&nbsp;<span style=\"color:#2b91af;\">StackedButton</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;Autodesk.Revit.RibbonItem&gt;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create(&nbsp;<span style=\"color:#2b91af;\">RibbonPanel</span>&nbsp;ribbonPanel&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Get&nbsp;Assembly</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Assembly</span>&nbsp;assembly&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Assembly</span>.GetExecutingAssembly();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;assemblyLocation&nbsp;=&nbsp;assembly.Location;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Get&nbsp;DLL&nbsp;Location</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;executableLocation&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.GetDirectoryName(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assemblyLocation&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;dllLocationTest&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.Combine(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;executableLocation,&nbsp;<span style=\"color:#a31515;\">&quot;TestDLLName.dll&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Image</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb1Image&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.16x16_Button1.ico&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb2Image&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.16x16_Button2.ico&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb1LargeImage&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.24x24_Button1.ico&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb2LargeImage&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.24x24_Button2.ico&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Button&nbsp;Name</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;buttonName1&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;ButtonTest1&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;buttonName2&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;ButtonTest2&quot;</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Create&nbsp;push&nbsp;buttons</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>&nbsp;buttondata1&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttonName1,&nbsp;buttonTextTest,&nbsp;dllLocationTest,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Command1&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata1.Image&nbsp;=&nbsp;pb1Image;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata1.LargeImage&nbsp;=&nbsp;pb1LargeImage;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>&nbsp;buttondata2&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttonName2,&nbsp;buttonTextTest,&nbsp;dllLocationTest,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Command2&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata2.Image&nbsp;=&nbsp;pb2Image;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata2.LargeImage&nbsp;=&nbsp;pb2LargeImage;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Create&nbsp;StackedItem</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;Autodesk.Revit.RibbonItem&gt;&nbsp;ribbonItem&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;ribbonPanel.AddStackedItems(&nbsp;buttondata1,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata2&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Find&nbsp;Autodes.Windows.RibbonItems</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UTILRibbonItem&nbsp;utilRibbon&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;UTILRibbonItem();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;btnTest1&nbsp;=&nbsp;utilRibbon.getButton(&nbsp;<span style=\"color:#a31515;\">&quot;Tab&quot;</span>,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Panel&quot;</span>,&nbsp;buttonName1&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;btnTest2&nbsp;=&nbsp;utilRibbon.getButton(&nbsp;<span style=\"color:#a31515;\">&quot;Tab&quot;</span>,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Panel&quot;</span>,&nbsp;buttonName2&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Size&nbsp;and&nbsp;Text&nbsp;Visibility</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest1.Size&nbsp;=&nbsp;<span style=\"color:#2b91af;\">RibbonItemSize</span>.Large;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest1.ShowText&nbsp;=&nbsp;<span style=\"color:blue;\">false</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest2.Size&nbsp;=&nbsp;<span style=\"color:#2b91af;\">RibbonItemSize</span>.Large;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest2.ShowText&nbsp;=&nbsp;<span style=\"color:blue;\">false</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Return&nbsp;StackedItem</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;ribbonItem;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n}\n</pre>\n\nMany thanks to Jameson for raising and solving this issue."
  },
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Reinitialising the Filtered Element Collector",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Reinitialising the Filtered Element Collector\n\nYet another important hint\nfrom Frank [@Fair59](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/2083518) Aarssen\non reinitialising the filtered element collector\nfor [collection of elements created using `ElementWorksetFilter` giving incorrect count](https://forums.autodesk.com/t5/revit-api-forum/collection-of-elements-created-using-elementworksetfilter-giving/m-p/9164018):\n\nYou need to reinitialise a filtered element collector before reusing it.\nAll the filters that you add to it are accumulated.\nIf they are mutually exclusive, you will get zero results.\n\n**Question:** I'm trying to retrieve empty worksets, but the count method of the collection of elements in a particular workset is not giving correct results.\nHere is my code:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;fec&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredWorksetCollector</span>&nbsp;fwc&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredWorksetCollector</span>(&nbsp;doc&nbsp;);\n \n&nbsp;&nbsp;fwc.OfKind(&nbsp;<span style=\"color:#2b91af;\">WorksetKind</span>.UserWorkset&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:blue;\">try</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;msg&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;count&nbsp;=&nbsp;0;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;doc&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style=\"color:#a31515;\">&quot;Check&nbsp;Empty&nbsp;Worksets&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Workset</span>&nbsp;w&nbsp;<span style=\"color:blue;\">in</span>&nbsp;fwc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementWorksetFilter</span>&nbsp;ewf&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ElementWorksetFilter</span>(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w.Id,&nbsp;<span style=\"color:blue;\">false</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;elemIds&nbsp;=&nbsp;fec.WherePasses(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ewf&nbsp;).ToElementIds();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;foundElems&nbsp;=&nbsp;elemIds.Count;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;Elements:&quot;</span>,&nbsp;w.Name&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;:&nbsp;&quot;</span>&nbsp;+&nbsp;foundElems.ToString()&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;foundElems&nbsp;==&nbsp;0&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;msg&nbsp;+=&nbsp;count.ToString()&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;.&nbsp;&quot;</span>&nbsp;+&nbsp;w.Name&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;\\n&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;count&nbsp;==&nbsp;0&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;msg&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;None&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;Empty&nbsp;Worksets:&nbsp;&quot;</span>,&nbsp;msg&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();\n&nbsp;&nbsp;&nbsp;&nbsp;t.Dispose();\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">catch</span>(&nbsp;<span style=\"color:#2b91af;\">Exception</span>&nbsp;e&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;Error&quot;</span>,&nbsp;e.ToString()&nbsp;);\n&nbsp;&nbsp;}\n</pre>\n\n**Answer:** A `FilteredElementCollector` isn't a static variable, but a dynamic collection.\n\nEvery time you apply a filter, the elements that don't pass the filter are removed from the collection.\n\nSo, after the first pass of the `foreach` loop, the collector only contains the elements belonging to the first workset.\n\nAll those elements aren't part of the second workset (2nd pass) and therefore the collector is empty after the second pass. \n\nSolution: reinitialize the collector in every pass:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Workset</span>&nbsp;w&nbsp;<span style=\"color:blue;\">in</span>&nbsp;fwc&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementWorksetFilter</span>&nbsp;ewf&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">ElementWorksetFilter</span>(\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w.Id,&nbsp;<span style=\"color:blue;\">false</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;elemIds&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;doc&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.WherePasses(&nbsp;ewf&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.ToElementIds();\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;foundElems&nbsp;=&nbsp;elemIds.Count;\n \n&nbsp;&nbsp;&nbsp;&nbsp;count++;\n \n&nbsp;&nbsp;&nbsp;&nbsp;msg&nbsp;+=&nbsp;foundElems.ToString()&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;.&nbsp;&quot;</span>&nbsp;+&nbsp;w.Name&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;\\n&quot;</span>;\n&nbsp;&nbsp;}\n</pre>\n\nMany thanks to Fair59 for yet another invaluable hint.\n\nBy the way, you might also want\nto [simplify your transaction handling by wrapping it in a `using` statement](https://thebuildingcoder.typepad.com/blog/2012/04/using-using-automagically-disposes-and-rolls-back.html).\nHowever, I also wonder whether you need any transaction at all for this read-only operation.\n\nThis misunderstanding caused a similar initial problem in another recent case involving \na [material assets collector for appearance, structural (physical) and thermal](https://forums.autodesk.com/t5/revit-api-forum/material-assets-collector-appearance-structural-physical-amp/m-p/7256944)."
  },
  {
    "original_filename": "1803_da_webinar_ri_stack",
    "header_text": "Use CreateReferenceInLink to Select a Face in a Linked File",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> Use CreateReferenceInLink to Select a Face in a Linked File\n\nBack in 2012, we discussed a pretty convoluted solution \nfor [selecting a face in a linked file](https://thebuildingcoder.typepad.com/blog/2012/05/selecting-a-face-in-a-linked-file.html#comment-4704876157).\n\nJoshua Lumley added a [comment](https://thebuildingcoder.typepad.com/blog/2012/05/selecting-a-face-in-a-linked-file.html#comment-4704877758) to\nthat old post, pointing out that:\n\n> The `CreateReferenceInLink` was added after that discussion, in Revit 2014.\n\n> To select any face anywhere, all you need is this:\n\n<pre class=\"code\">\n<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">static</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;SelectFace(&nbsp;<span style=\"color:#2b91af;\">UIApplication</span>&nbsp;uiapp&nbsp;)\n{\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;doc&nbsp;=&nbsp;uiapp.ActiveUIDocument.Document;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">IEnumerable</span>&lt;<span style=\"color:#2b91af;\">Document</span>&gt;&nbsp;doc2&nbsp;=&nbsp;GetLinkedDocuments(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;doc&nbsp;);\n \n&nbsp;&nbsp;Autodesk.Revit.UI.Selection.<span style=\"color:#2b91af;\">Selection</span>&nbsp;sel&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;uiapp.ActiveUIDocument.Selection;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Reference</span>&nbsp;pickedRef&nbsp;=&nbsp;sel.PickObject(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;Autodesk.Revit.UI.Selection.<span style=\"color:#2b91af;\">ObjectType</span>.PointOnElement,&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;Please&nbsp;select&nbsp;a&nbsp;Face&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;elem&nbsp;=&nbsp;doc.GetElement(&nbsp;pickedRef.ElementId&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Type</span>&nbsp;et&nbsp;=&nbsp;elem.GetType();\n \n&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">RevitLinkType</span>&nbsp;)&nbsp;==&nbsp;et&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">RevitLinkInstance</span>&nbsp;)&nbsp;==&nbsp;et&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">Instance</span>&nbsp;)&nbsp;==&nbsp;et&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;d&nbsp;<span style=\"color:blue;\">in</span>&nbsp;doc2&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;elem.Name.Contains(&nbsp;d.Title&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Reference</span>&nbsp;pickedRefInLink&nbsp;=&nbsp;pickedRef\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.CreateReferenceInLink();\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;myElement&nbsp;=&nbsp;d.GetElement(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pickedRefInLink.ElementId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;myGeometryObject&nbsp;=&nbsp;myElement\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetGeometryObjectFromReference(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pickedRefInLink&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;myGeometryObject;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;myElement&nbsp;=&nbsp;doc.GetElement(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pickedRef.ElementId&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Face</span>&nbsp;myGeometryObject&nbsp;=&nbsp;myElement\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetGeometryObjectFromReference(&nbsp;pickedRef&nbsp;)&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Face</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;myGeometryObject;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">null</span>;\n}\n</pre>\n\nMany thanks to Joshua for this important update."
  }
]