[
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n</head>\n\n<!---\n\n- [24x24 StackedItems](https://forums.autodesk.com/t5/revit-api-forum/24x24-stackeditems/m-p/9337695)\n\n- 10549372 [Add a new custom Ribbon Panel to a Revit built-in tab]\n  https://forums.autodesk.com/t5/revit-api-forum/add-a-new-custom-ribbon-panel-to-a-revit-built-in-tab/td-p/5538772\n\n- https://forums.autodesk.com/t5/revit-api-forum/revit-journal-file-encoding/m-p/9330501\nАндрей Павлов\n[apavlovY5SDS](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/7264445)\nRevit Journal file encoding\n**Question:** What is the Revit journal file encoding?\nDefault filepath *C:\\Users\\{Username}\\AppData\\Local\\Autodesk\\Revit\\Autodesk Revit 2020\\Journals*.\nI have trouble decoding Cyrillic characters.\n**Answer:** Windows-1251, confidence 0.9824519, tested with [errepi/ude](https://github.com/errepi/ude), a C# port of the Mozilla Universal Charset Detector.\n\ntwitter:\n\n24x24 StackedItem, ribbon item utils and journal encoding in the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon http://bit.ly/24x24ribbonitem\n\nLet's start the week with some ribbon button item and encoding topics\n&ndash; How to create 24x24 stacked ribbon items\n&ndash; Update on moving a ribbon button between panels\n&ndash; Revit journal file character encoding...\n\nlinkedin:\n\n24x24 StackedItem, ribbon item utils and journal encoding in the #RevitAPI\n\nhttp://bit.ly/24x24ribbonitem\n\nLet's start this week's posting with some ribbon button item and encoding topics:\n\n- How to create 24x24 stacked ribbon items\n- Update on moving a ribbon button between panels\n- Revit journal file character encoding...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"100\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "24x24 StackedItem, Ribbon Utils, Journal Encoding",
    "local_header_href": "#24x24-stackeditem-ribbon-utils-journal-encoding",
    "chunk_text": "### 24x24 StackedItem, Ribbon Utils, Journal Encoding\n\nLet's start the week with some ribbon button item and encoding topics:\n\n- [How to create 24x24 stacked ribbon items](#2)\n- [Update on moving a ribbon button between panels](#3)\n- [Revit journal file character encoding](#4)"
  },
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "<a name=\"2\"></a>How to Create 24x24 Stacked Ribbon Items",
    "local_header_href": "#a-name2ahow-to-create-24x24-stacked-ribbon-items",
    "chunk_text": "#### <a name=\"2\"></a>How to Create 24x24 Stacked Ribbon Items\n\nJameson [jnyp](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/4918309) Nyp raised and solved this issue in \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [24x24 StackedItems](https://forums.autodesk.com/t5/revit-api-forum/24x24-stackeditems/m-p/9337695):\n\n**Question:** This may be an easy one, but so far I am struggling to find anything specific about it.\nHow do you make a `StackedItem` where the icons are 24x24 when there are only 2 in the stack?\nIt seems like it should be possible as it is used multiple times in the modify tab (see example below).\n\n<center>\n<img src=\"img/icon_sizes.png\" alt=\"Icon sizes\" title=\"Icon sizes\" width=\"246\"/>\n<p style=\"font-size: 80%; font-style:italic\">Icon sizes</p>\n</center>\n\nI have been able to set the `ShowText` property to false to get the 3 stacked icons, but when I use the same methodology with the 2 icon stack it remains 16x16 regardless of the icon resolution.\nI have tried to obtain and change the button's height and width, minWidth and minHeight through the Autodesk.Window.RibbonItem object to no avail.\nHas anyone had any success in creating these icons?\n\n**Solution:** I found a solution.\nIn order to display the button at the 24x24 size the Autodesk.Windows.RibbonItem.Size needs to be manually set to Autodesk.Windows.RibbonItemSize.Large enum and a 24x24 icon needs to be set to the LargeImage property of the button.\nI have included a code example below.\nForgive me for any poor coding techniques.\nI am only a couple months into my C# developer life.\n \n<pre class=\"code\">\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Revit.UI;\n<span style=\"color:blue;\">using</span>&nbsp;Autodesk.Windows;\n<span style=\"color:blue;\">using</span>&nbsp;System.Collections.Generic;\n<span style=\"color:blue;\">using</span>&nbsp;System.IO;\n<span style=\"color:blue;\">using</span>&nbsp;System.Reflection;\n<span style=\"color:blue;\">using</span>&nbsp;System.Windows.Media.Imaging;\n<span style=\"color:blue;\">using</span>&nbsp;YourCustomUtilityLibrary;\n \n<span style=\"color:blue;\">namespace</span>&nbsp;ReallyCoolAddin\n{\n&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:blue;\">class</span>&nbsp;<span style=\"color:#2b91af;\">StackedButton</span>\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">public</span>&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;Autodesk.Revit.RibbonItem&gt;&nbsp;Create(&nbsp;<span style=\"color:#2b91af;\">RibbonPanel</span>&nbsp;ribbonPanel&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Get&nbsp;Assembly</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Assembly</span>&nbsp;assembly&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Assembly</span>.GetExecutingAssembly();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;assemblyLocation&nbsp;=&nbsp;assembly.Location;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Get&nbsp;DLL&nbsp;Location</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;executableLocation&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.GetDirectoryName(&nbsp;assemblyLocation&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;dllLocationTest&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Path</span>.Combine(&nbsp;executableLocation,&nbsp;<span style=\"color:#a31515;\">&quot;TestDLLName.dll&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Image</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb1Image&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.16x16_Button1.ico&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb2Image&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.16x16_Button2.ico&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb1LargeImage&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.24x24_Button1.ico&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BitmapSource</span>&nbsp;pb2LargeImage&nbsp;=&nbsp;UTILImage.GetEmbeddedImage(&nbsp;assembly,&nbsp;<span style=\"color:#a31515;\">&quot;Resources.24x24_Button2.ico&quot;</span>&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Button&nbsp;Name</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;buttonName1&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;ButtonTest1&quot;</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;buttonName2&nbsp;=&nbsp;<span style=\"color:#a31515;\">&quot;ButtonTest2&quot;</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Create&nbsp;push&nbsp;buttons</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>&nbsp;buttondata1&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>(&nbsp;buttonName1,&nbsp;buttonTextTest,&nbsp;dllLocationTest,&nbsp;<span style=\"color:#a31515;\">&quot;Command1&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata1.Image&nbsp;=&nbsp;pb1Image;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata1.LargeImage&nbsp;=&nbsp;pb1LargeImage;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>&nbsp;buttondata2&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">PushButtonData</span>(&nbsp;buttonName2,&nbsp;buttonTextTest,&nbsp;dllLocationTest,&nbsp;<span style=\"color:#a31515;\">&quot;Command2&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata2.Image&nbsp;=&nbsp;pb2Image;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttondata2.LargeImage&nbsp;=&nbsp;pb2LargeImage;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Create&nbsp;StackedItem</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">IList</span>&lt;Autodesk.Revit.RibbonItem&gt;&nbsp;ribbonItem&nbsp;=&nbsp;ribbonPanel.AddStackedItems(&nbsp;buttondata1,&nbsp;buttondata2&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Find&nbsp;Autodes.Windows.RibbonItems</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UTILRibbonItem&nbsp;utilRibbon&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;UTILRibbonItem();\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;btnTest1&nbsp;=&nbsp;utilRibbon.getButton(&nbsp;<span style=\"color:#a31515;\">&quot;Tab&quot;</span>,&nbsp;<span style=\"color:#a31515;\">&quot;Panel&quot;</span>,&nbsp;buttonName1&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">var</span>&nbsp;btnTest2&nbsp;=&nbsp;utilRibbon.getButton(&nbsp;<span style=\"color:#a31515;\">&quot;Tab&quot;</span>,&nbsp;<span style=\"color:#a31515;\">&quot;Panel&quot;</span>,&nbsp;buttonName2&nbsp;);\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Set&nbsp;Size&nbsp;and&nbsp;Text&nbsp;Visibility</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest1.Size&nbsp;=&nbsp;<span style=\"color:#2b91af;\">RibbonItemSize</span>.Large;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest1.ShowText&nbsp;=&nbsp;<span style=\"color:blue;\">false</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest2.Size&nbsp;=&nbsp;<span style=\"color:#2b91af;\">RibbonItemSize</span>.Large;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;btnTest2.ShowText&nbsp;=&nbsp;<span style=\"color:blue;\">false</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;Return&nbsp;StackedItem</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;ribbonItem;\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;}\n}\n</pre>\n\n**Question:** Hi Jameson, in your code above, you use a `UTILRibbonItema` class.\n\nWhat is the that?\n\nI wasn't able to find it anywhere on the Internet.\n\n**Answer:** The `UTILRibbonItem` class is a helper class that I use to go find RibbonItems through the Autodesk.Windows (AW) API.\n\nIt goes in to the AW and recursively searches through the tabs, panels and buttons to find the button you feed to it.\n\nTaking all of the logic and putting it in its own class allows for easier reuse.\n\nA larger discussion of what that class contains can be found in the other discussion thread\non [adding a new custom ribbon panel to a Revit built-in tab](https://forums.autodesk.com/t5/revit-api-forum/add-a-new-custom-ribbon-panel-to-a-revit-built-in-tab/td-p/5538772)\n\nHere is a basic implementation:\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">using</span>&nbsp;AW&nbsp;=&nbsp;Autodesk.Windows;\n   \n  <span style=\"color:blue;\">public</span>&nbsp;AW.<span style=\"color:#2b91af;\">RibbonItem</span>&nbsp;GetButton(&nbsp;<span style=\"color:blue;\">string</span>&nbsp;tabName,&nbsp;\n  &nbsp;&nbsp;<span style=\"color:blue;\">string</span>&nbsp;panelName,&nbsp;<span style=\"color:blue;\">string</span>&nbsp;itemName&nbsp;)\n  {\n  &nbsp;&nbsp;AW.<span style=\"color:#2b91af;\">RibbonControl</span>&nbsp;ribbon&nbsp;=&nbsp;AW.<span style=\"color:#2b91af;\">ComponentManager</span>.Ribbon;\n  &nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;AW.<span style=\"color:#2b91af;\">RibbonTab</span>&nbsp;tab&nbsp;<span style=\"color:blue;\">in</span>&nbsp;ribbon.Tabs&nbsp;)\n  &nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;tab.Name&nbsp;==&nbsp;tabName&nbsp;)\n  &nbsp;&nbsp;&nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;AW.<span style=\"color:#2b91af;\">RibbonPanel</span>&nbsp;panel&nbsp;<span style=\"color:blue;\">in</span>&nbsp;tab.Panels&nbsp;)\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;panel.Source.Title&nbsp;==&nbsp;panelName&nbsp;)\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;panel.FindItem(&nbsp;<span style=\"color:#a31515;\">&quot;CustomCtrl_%CustomCtrl_%&quot;</span>&nbsp;\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;tabName&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;%&quot;</span>&nbsp;+&nbsp;panelName&nbsp;+&nbsp;<span style=\"color:#a31515;\">&quot;%&quot;</span>&nbsp;+&nbsp;itemName,&nbsp;\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">true</span>&nbsp;)&nbsp;<span style=\"color:blue;\">as</span>&nbsp;AW.<span style=\"color:#2b91af;\">RibbonItem</span>;\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n  &nbsp;&nbsp;&nbsp;&nbsp;}\n  &nbsp;&nbsp;}\n  &nbsp;&nbsp;<span style=\"color:blue;\">return</span>&nbsp;<span style=\"color:blue;\">null</span>;\n  }\n</pre>\n\nJust beware that the AW API is not a documented API, so use it at your own risk as it can be changed without letting anyone know.\n\nMany thanks to Jameson for implementing and sharing this nice clean solution, and congratulations on such prowess \"only a couple months into his C# developer life\"!"
  },
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "<a name=\"3\"></a>Update on Moving a Ribbon Button Between Panels",
    "local_header_href": "#a-name3aupdate-on-moving-a-ribbon-button-between-panels",
    "chunk_text": "#### <a name=\"3\"></a>Update on Moving a Ribbon Button Between Panels\n\nJameson's links above prompted me to revisit \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [adding a new custom ribbon panel to a Revit built-in tab](https://forums.autodesk.com/t5/revit-api-forum/add-a-new-custom-ribbon-panel-to-a-revit-built-in-tab/td-p/5538772) \nthat I referred to here on the blog in 2014 in the article\non [moving an external command button within the ribbon](https://thebuildingcoder.typepad.com/blog/2014/07/moving-an-external-command-button-within-the-ribbon.html).\n\nI noticed that the thread was updated after the initial publication.\nAbove all, the link to the sample code provided back then is no longer valid, so here is\na [local copy of it, RibbonMoveExample.zip](zip/RibbonMoveExample.zip).\n\nThanks again to Scott for sharing it back then."
  },
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "<a name=\"4\"></a>Revit Journal File Character Encoding",
    "local_header_href": "#a-name4arevit-journal-file-character-encoding",
    "chunk_text": "#### <a name=\"4\"></a>Revit Journal File Character Encoding\n\nFinally, a quick note on the Revit journal file character encoding shared\nby Андрей [apavlovY5SDS](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/7264445) Павлов (Andrey Pavlov) in\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [Revit journal file encoding](https://forums.autodesk.com/t5/revit-api-forum/revit-journal-file-encoding/m-p/9330501):\n\n**Question:** What is the Revit journal file encoding?\n\nThe default file path is *C:\\Users\\ {Username} \\AppData\\Local\\Autodesk\\Revit\\Autodesk Revit 2020\\Journals*.\n\nI have trouble decoding Cyrillic characters.\n\n**Answer:** Windows-1251, confidence 0.9824519, tested\nwith [errepi/ude](https://github.com/errepi/ude),\na C# port of the Mozilla Universal Charset Detector.\n\nMany thanks to Andrey for raising and clarifying this issue.\n\n<!---"
  },
  {
    "original_filename": "1823_24x24_stackeditem",
    "header_text": "<a name=\"5\"></a>Adjusting versus Recreating Wall Location Curve",
    "local_header_href": "#a-name5aadjusting-versus-recreating-wall-location-curve",
    "chunk_text": "#### <a name=\"5\"></a>Adjusting versus Recreating Wall Location Curve\n\nHarald Schmidt pointed out an interesting aspect and important enhancement to the old discussion of how\nto [edit wall length](https://thebuildingcoder.typepad.com/blog/2010/08/edit-wall-length.html) in\nhis [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [adjusting Wall.LocationCurve.Curve results in unexpected behaviour](https://forums.autodesk.com/t5/revit-api-forum/adjusting-wall-locationcurve-curve-results-in-unexpected/m-p/9328145):\n\n**Question:** My add-in adjusts walls lines slightly (moves and rotates them a bit, and also slightly adjusts their length).\n\nUsing `wall.Location.Move` and `wall.Location.Rotate` enables adjusting the location and rotation of the walls, but not their length.\n\nSo, we decided to follow the approach suggested 10 years ago by The Building Coder to [\nto [edit wall length](https://thebuildingcoder.typepad.com/blog/2010/08/edit-wall-length.html) by\ncreating a completely new wall location line from scratch like this:\n\n<pre class=\"code\">\n  // get the current wall location\n  LocationCurve wallLocation = myWall.Location \n    as LocationCurve;\n \n  // get the points\n  XYZ pt1 = wallLocation.Curve.get_EndPoint( 0 );\n  XYZ pt2 = wallLocation.Curve.get_EndPoint( 1 );\n \n  // change one point, e.g. move 1000 mm on X axis\n \n  pt2 = pt2.Add( new XYZ( 0.01 ), 0, 0 ) );\n \n  // create a new LineBound\n  Line newWallLine = app.Create.NewLineBound( \n    pt1, pt2 );\n \n  // update the wall curve\n  wallLocation.Curve = newWallLine;\n</pre>\n\nThis works fine for single walls, but fails in many cases where the wall has hosted elements like windows, and even in complex scenarios with multiple walls.\n\nNote: the movement is always less than about some mm!\n\nTo show you what I mean, I wrote a short macro embedded in the RVT attached.\n\nThe macro `LocationLineReset` just moves the wall inside the RVT by approx. 3 mm using the method suggested by The Building Coder:\n\n<center>\n<img src=\"img/adjust_wall_locationcurve_curve_macros.png\" alt=\"Adjust wall LocationCurve curve macros\" title=\"Adjust wall LocationCurve curve macros\" width=\"600\"/> 1104\n</center>\n\nThe result is the following:\n\n<center>\n<img src=\"img/adjust_wall_locationcurve_curve_error.png\" alt=\"Adjust wall LocationCurve curve error\" title=\"Adjust wall LocationCurve curve error\" width=\"600\"/> 840\n</center>\n\nThis seem like an unexpected behavior.\nThe window is now located outside the wall, although the wall has moved only about 3mm.\nIs this a bug?\n\nIf I use the second macro `ShiftWall`, which just calls `wall.LocationCurve.Move` to create an equivalent translation comparable to the former marco, the result is fine.\n\nIs there any method to adjust the length of the wall except resetting the `wall.LocationCurve.Curve` by creating a new curve using `Line.CreateBound`? That would solve our issue as well.\n\n**Answer:** Thank you for your interesting observation and careful analysis.\n\nI looked at your macros and can reproduce what you say.\n\nBesides the macro you list, `LocationLineReset`, there is another one that slightly moves the existing location line instead of creating a new one, `ShiftWall`.\n\nThat latter macro completes successfully:\n\n<pre class=\"code\">\n  public void LocationLineReset()\n  {\n    doc = this.Application.ActiveUIDocument.Document;\n    Wall wall = doc.GetElement( new ElementId( 305891 ) ) as Wall;\n    TransactionStatus status;\n    using ( Transaction trans = new Transaction( doc, \"bla\" ) )\n    {\n      trans.Start();\n      LocationCurve locationCurve = wall.Location as LocationCurve;\n      Line wallLine = locationCurve.Curve as Line;\n      \n      XYZ startPoint = wallLine.GetEndPoint(0);\n      XYZ endPoint = wallLine.GetEndPoint(1);\n\n      XYZ minimalMoveVector = new XYZ( 0.01 /* =~ 3mm*/, 0.01, 0.0);\n      startPoint += minimalMoveVector;\n      endPoint += minimalMoveVector;\n      \n      locationCurve.Curve = Line.CreateBound( startPoint, endPoint );\n      status = trans.Commit();\n    }\n    \n    if( status != TransactionStatus.Committed ) \n      MessageBox.Show( \"Commit failed\" );\n  }\n  \n  public void ShiftWall()\n  {\n    doc = this.Application.ActiveUIDocument.Document;\n    Wall wall = doc.GetElement( new ElementId( 305891 ) ) as Wall;\n    TransactionStatus status;\n    bool bSuccess = false;\n    using ( Transaction trans = new Transaction( doc, \"bla\" ) )\n    {\n      trans.Start();\n\n      XYZ minimalMoveVector = new XYZ( 0.01 /* =~ 3mm*/, 0.01, 0.0);\t\t\t\t\n      bSuccess = wall.Location.Move( minimalMoveVector );\n      \n      status = trans.Commit();\n    }\n    \n    if( status == TransactionStatus.Committed && bSuccess) \n      MessageBox.Show( \"Shift succeeded\" );\n  }\n</pre>\n\nI would assume that during the process of resetting the wall location line from scratch, the window position gets completely lost.\n\nWhen you simply perform a small adjustment to the existing location line, the window position is retained and adjusted accordingly.\n\nTherefore, I would suggest using the latter approach whenever possible.\n\nYou could even make use of the latter approach in several steps, adjust first one and then the other location line endpoint.\n\nI hope this enables you to handle all required situations.\n\n\nSetEndPoint method\n\n\n  public void ShortenWall()\n  {\n    Document doc = this.Application.ActiveUIDocument.Document;\n    Wall wall = doc.GetElement( new ElementId( 305891 ) ) as Wall;\n    TransactionStatus status;\n    using ( Transaction trans = new Transaction( doc ) )\n    {\n      trans.Start( \"Shorten Wall\");\n      \n      LocationCurve lc = wall.Location as LocationCurve;\n      Line ll = lc.Curve as Line;\n      \n      double pstart = ll.GetEndParameter(0);\n      double pend = ll.GetEndParameter(1);\n      double pdelta = 0.05 * (pend - pstart);\n      \n      lc.Curve.MakeBound(pstart + pdelta, pend - pdelta); // no observable change to wall\n      \n      (wall.Location as LocationCurve).Curve.MakeUnbound();\n      \n      (wall.Location as LocationCurve).Curve.MakeBound( // no observable change to wall\n        pstart + pdelta, pend - pdelta);\n  \n      status = trans.Commit();\n    }\n    \n    if( status == TransactionStatus.Committed) \n      MessageBox.Show( \"Shorten Wall succeeded\" );\n  }\n  \n--->"
  }
]