[
  {
    "original_filename": "1847_split_pipe",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- https://github.com/jeremytammik/Pipe-Split\n  /a/src/rvt/Pipe-Split/\n\n- split a conduit\n  https://forums.autodesk.com/t5/revit-api-forum/trouble-of-my-own-implementation-of-breakcurve-on-conduit/m-p/8426899/highlight/false\n  16561381 [Programatically Place Conduit Fitting]\n\n- split pipe into lengths\n  14201186 [Need to call command Split Element (SL) with defined filter and length]\n\n\ntwitter:\n\nTutorial on splitting a pipe, calling the SL split element command and splitting a conduit in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon https://bit.ly/splitpipetutor\n\nToday, let's focus on splitting pipes and other things, starting with a nicely structured tutorial\n&ndash; Abdelaziz' split pipe tutorial\n&ndash; Calling the SL split element command\n&ndash; Splitting a conduit...\n\nlinkedin:\n\nTutorial on splitting a pipe, calling the SL split element command and splitting a conduit in the #RevitAPI \n\nhttps://bit.ly/splitpipetutor\n\nToday, let's focus on splitting pipes and other things, starting with a nicely structured tutorial:\n\n- Abdelaziz' split pipe tutorial\n- Calling the SL split element command\n- Splitting a conduit...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1847_split_pipe",
    "header_text": "Split Pipe Tutorial and Related Cases",
    "local_header_href": "#split-pipe-tutorial-and-related-cases",
    "chunk_text": "### Split Pipe Tutorial and Related Cases\n\nToday, let's focus on splitting pipes and other things, starting with a nicely structured tutorial shared\nby Abdelaziz [Zizobiko25](https://github.com/Zizobiko25) Fadoul:\n\n- [Abdelaziz' split pipe tutorial](#3)\n- [Calling the SL split element command](#4)\n- [Splitting a conduit](#5)\n- [George Floyd in Memoriam](#6)"
  },
  {
    "original_filename": "1847_split_pipe",
    "header_text": "Abdelaziz' Split Pipe Tutorial",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Abdelaziz' Split Pipe Tutorial\n\nHi folks,\n\nHope you are all safe and keeping well.\n\nAs there is no explicit SDK sample for splitting pipe instances into standard lengths without using the fabrication configurations, so I thought to share with you the below snippet. This is built upon a contribution that I came across on this platform, and uses functions that are developed on other samples (e.g. Find connected element, etc.), however, I thought to enhance it and explain the steps to achieve such a task. The fundamental idea for this is to delete the selected pipe and replace it with the creation of 2 pipes instead. \n\n1-\tEstablish a new transaction: As this is going to modify the Revit document, then we need to have it done within a transaction context.\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">using</span>(&nbsp;<span style=\"color:#2b91af;\">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Transaction</span>(&nbsp;activeDoc.Document&nbsp;)&nbsp;)\n  {\n  &nbsp;&nbsp;tx.Start(&nbsp;<span style=\"color:#a31515;\">&quot;split&nbsp;pipe&quot;</span>&nbsp;);\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;systemtype&nbsp;=&nbsp;system.GetTypeId();\n  &nbsp;&nbsp;SplitPipe(&nbsp;pipes[&nbsp;0&nbsp;],&nbsp;system,&nbsp;activeDoc,&nbsp;systemtype,&nbsp;pipeType&nbsp;);\n  &nbsp;&nbsp;tx.Commit();\n  }\n</pre>\n\n2-\tWe then obtain the selected pipe basic data including its length, associated level Id and system Id.\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;levelId&nbsp;=&nbsp;segment.get_Parameter(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.RBS_START_LEVEL_PARAM&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;  .AsElementId();\n \n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;system.LevelId;</span>\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;systemtype&nbsp;=&nbsp;_system.GetTypeId();\n \n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;selecting&nbsp;one&nbsp;pipe&nbsp;and&nbsp;taking&nbsp;its&nbsp;location.</span>\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;c1&nbsp;=&nbsp;(segment.Location&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">LocationCurve</span>).Curve;&nbsp;\n \n&nbsp;&nbsp;<span style=\"color:green;\">//Pipe&nbsp;diameter</span>\n&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;pipeDia&nbsp;=&nbsp;<span style=\"color:#2b91af;\">UnitUtils</span>.ConvertFromInternalUnits(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;segment.get_Parameter(&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.RBS_PIPE_DIAMETER_PARAM&nbsp;).AsDouble(),\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">DisplayUnitType</span>.DUT_MILLIMETERS&nbsp;);  \n</pre>\n\n3-\tWe then compare the obtained length, including the fitting length, with the standard length that we want to assign (for instance, 6m here).\nIf it is longer than that, then we proceed. \n\n<pre class=\"code\">\n  <span style=\"color:green;\">//Standard&nbsp;length</span>\n  <span style=\"color:blue;\">double</span>&nbsp;l&nbsp;=&nbsp;6000;\n   \n  <span style=\"color:green;\">//Coupling&nbsp;length</span>\n  <span style=\"color:blue;\">double</span>&nbsp;fittinglength&nbsp;=&nbsp;(1.1&nbsp;*&nbsp;pipeDia&nbsp;+&nbsp;14.4);\n   \n  <span style=\"color:green;\">//&nbsp;finding&nbsp;the&nbsp;length&nbsp;of&nbsp;the&nbsp;selected&nbsp;pipe.</span>\n  <span style=\"color:blue;\">double</span>&nbsp;len&nbsp;=&nbsp;<span style=\"color:#2b91af;\">UnitUtils</span>.ConvertFromInternalUnits(&nbsp;segment.get_Parameter(&nbsp;<span style=\"color:#2b91af;\">BuiltInParameter</span>.CURVE_ELEM_LENGTH&nbsp;).AsDouble(),&nbsp;<span style=\"color:#2b91af;\">DisplayUnitType</span>.DUT_MILLIMETERS&nbsp;);\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;len&nbsp;&lt;=&nbsp;l&nbsp;)\n  &nbsp;&nbsp;<span style=\"color:blue;\">return</span>;\n</pre>\n\n4-\tWe then determine the splitting point by taking the fracture between the required length to the total length.\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">var</span>&nbsp;startPoint&nbsp;=&nbsp;c1.GetEndPoint(&nbsp;0&nbsp;);\n  <span style=\"color:blue;\">var</span>&nbsp;endPoint&nbsp;=&nbsp;c1.GetEndPoint(&nbsp;1&nbsp;);\n   \n  <span style=\"color:#2b91af;\">XYZ</span>&nbsp;splitpoint&nbsp;=&nbsp;(endPoint&nbsp;-&nbsp;startPoint)&nbsp;*&nbsp;(l&nbsp;/&nbsp;len);\n   \n  <span style=\"color:blue;\">var</span>&nbsp;newpoint&nbsp;=&nbsp;startPoint&nbsp;+&nbsp;splitpoint;\n   \n  <span style=\"color:#2b91af;\">Pipe</span>&nbsp;pp&nbsp;=&nbsp;segment&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">Pipe</span>;\n   \n  <span style=\"color:green;\">//&nbsp;Find&nbsp;two&nbsp;connectors&nbsp;which&nbsp;pipe&#39;s&nbsp;two&nbsp;ends&nbsp;connector&nbsp;connected&nbsp;to.&nbsp;</span>\n  <span style=\"color:#2b91af;\">Connector</span>&nbsp;startConn&nbsp;=&nbsp;FindConnectedTo(&nbsp;pp,&nbsp;startPoint&nbsp;);\n  <span style=\"color:#2b91af;\">Connector</span>&nbsp;endConn&nbsp;=&nbsp;FindConnectedTo(&nbsp;pp,&nbsp;endPoint&nbsp;);\n</pre>\n\n5-\tWe are then able to create the first and second pipe segments using the command create:\n\n<pre class=\"code\">\n  <span style=\"color:green;\">//&nbsp;creating&nbsp;first&nbsp;pipe&nbsp;</span>\n  <span style=\"color:#2b91af;\">Pipe</span>&nbsp;pipe&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n  <span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;_pipeType&nbsp;)\n  {\n  &nbsp;&nbsp;pipe&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Pipe</span>.Create(&nbsp;_activeDoc.Document,&nbsp;\n  &nbsp;&nbsp;&nbsp;&nbsp;_pipeType.Id,&nbsp;levelId,&nbsp;startConn,&nbsp;newpoint&nbsp;);\n  }\n   \n  <span style=\"color:#2b91af;\">Connector</span>&nbsp;conn1&nbsp;=&nbsp;FindConnector(&nbsp;pipe,&nbsp;newpoint&nbsp;);\n   \n  <span style=\"color:green;\">//Check&nbsp;+&nbsp;fitting</span>\n  <span style=\"color:#2b91af;\">XYZ</span>&nbsp;fittingend&nbsp;=&nbsp;(endPoint&nbsp;-&nbsp;startPoint)&nbsp;\n  &nbsp;&nbsp;*&nbsp;((l&nbsp;+&nbsp;(fittinglength&nbsp;/&nbsp;2))&nbsp;/&nbsp;len);\n   \n  <span style=\"color:green;\">//New&nbsp;point&nbsp;after&nbsp;the&nbsp;fitting&nbsp;gap</span>\n  <span style=\"color:blue;\">var</span>&nbsp;endOfFitting&nbsp;=&nbsp;startPoint&nbsp;+&nbsp;fittingend;\n   \n  <span style=\"color:#2b91af;\">Pipe</span>&nbsp;pipe1&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Pipe</span>.Create(&nbsp;_activeDoc.Document,&nbsp;\n  &nbsp;&nbsp;systemtype,&nbsp;_pipeType.Id,&nbsp;levelId,&nbsp;endOfFitting,&nbsp;\n  &nbsp;&nbsp;endPoint&nbsp;);\n   \n  <span style=\"color:green;\">//&nbsp;Copy&nbsp;parameters&nbsp;from&nbsp;previous&nbsp;pipe&nbsp;to&nbsp;the&nbsp;following&nbsp;Pipe.&nbsp;</span>\n  CopyParameters(&nbsp;pipe,&nbsp;pipe1&nbsp;);\n  <span style=\"color:#2b91af;\">Connector</span>&nbsp;conn2&nbsp;=&nbsp;FindConnector(&nbsp;pipe1,&nbsp;endOfFitting&nbsp;);\n  _&nbsp;=&nbsp;_activeDoc.Document.Create.NewUnionFitting(&nbsp;conn1,&nbsp;conn2&nbsp;);\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;!=&nbsp;endConn&nbsp;)\n  {\n  &nbsp;&nbsp;<span style=\"color:#2b91af;\">Connector</span>&nbsp;pipeEndConn&nbsp;=&nbsp;FindConnector(&nbsp;pipe1,&nbsp;endPoint&nbsp;);\n  &nbsp;&nbsp;pipeEndConn.ConnectTo(&nbsp;endConn&nbsp;);\n  }\n</pre>\n\n6-\tOnce this is done successfully, we can then delete the original pipe segment\n\n<pre class=\"code\">\n  <span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">ElementId</span>&gt;&nbsp;deletedIdSet&nbsp;\n  &nbsp;&nbsp;=&nbsp;_activeDoc.Document.Delete(&nbsp;segment.Id&nbsp;);\n   \n  <span style=\"color:blue;\">if</span>(&nbsp;0&nbsp;==&nbsp;deletedIdSet.Count&nbsp;)\n  {\n  &nbsp;&nbsp;<span style=\"color:blue;\">throw</span>&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">Exception</span>(&nbsp;<span style=\"color:#a31515;\">&quot;Deleting&nbsp;the&nbsp;selected&nbsp;elements&nbsp;in&nbsp;Revit&nbsp;failed.&quot;</span>&nbsp;);\n  }\n</pre>\n\nLink to the full code is accessible from\nthe [Pipe-Split GitHub repository](https://github.com/Zizobiko25/Pipe-Split).\n\nHope this useful for someone. Give me a shout if you have any questions.\n\nThanks, Abdelaziz\n\nMany thanks to *You*, Abdelaziz, for putting together and sharing this very nice and clean solution and helpful explanation!"
  },
  {
    "original_filename": "1847_split_pipe",
    "header_text": "Calling the SL Split Element Command",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Calling the SL Split Element Command\n\nWhile on the topic of splitting things, here is another related old case, 14201186 *Need to call command Split Element (SL) with defined filter and length*:\n\n**Question:** I wanted to call the Split Element (SL) command through API and wants to give the filter to select only Pipe with predefined length to split.\n\nCan you please help us with this?\n\n**Answer:** You can call many built-in Revit commands using\nthe [`PostCommand` API](http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.3).\n\nHowever, this just launches the built-in command as is, prompting the user for all further input and other interaction.\n\nTherefore, if you wish to drive this completely automatically, it will be hard to make use of the built-in command.\n\n<!--\nobsolete:\n\nHere is a discussion of the basics of [creating and modifying pipes through the API](\n\nhttp://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2015/ENU/Revit-API/files/GUID-0B91BAE8-59FD-4D4B-84E6-53B6A21DE00A-htm.html?_ga=2.49832166.1581756714.1525612885-2130181328.1465883366\n-->\n\nThe specific question of splitting a pipe into shorter segments of a given length has been discussed repeatedly in the Revit API discussion forum:\n\n- [Split a pipe at a specific lenght](https://forums.autodesk.com/t5/revit-api-forum/split-a-pipe-at-a-specific-lenght/m-p/5533100)\n- [Pipe / Duct spliting using the Revit API](https://forums.autodesk.com/t5/revit-api/pipe-duck-spliting-using-the-revit-api/m-p/3312303)\n- [Split Ducts with Union](https://forums.autodesk.com/t5/revit-api/split-ducts-with-union/m-p/5489135)"
  },
  {
    "original_filename": "1847_split_pipe",
    "header_text": "Splitting a Conduit",
    "local_header_href": "#5",
    "chunk_text": "####<a name=\"5\"></a> Splitting a Conduit\n\nAnother more recent related case is 16561381 *Programmatically Place Conduit Fitting*, on splitting a conduit:\n\n**Question:** We would like to know how to programmatically place a conduit fitting at a certain location on a piece of conduit.\nBasically, we want to exactly what this tool does (screenshots included as well) but we do not want the user to have to click where they place it &ndash; we want to programmatically control it's placement on a piece of conduit.\n\n<center>\n<img src=\"img/place_conduit_fitting_1.png\" alt=\"Place conduit fitting\" title=\"Place conduit fitting\" width=\"529\"/> <!-- 529 -->\n<img src=\"img/place_conduit_fitting_2.png\" alt=\"Place conduit fitting\" title=\"Place conduit fitting\" width=\"190\"/> <!-- 190 -->\n</center>\n\nWe have been unable to find anything within the API or forums which accomplish this. Please advise on how this can be done.\n\nTool help info:\n\n- [Add Conduit Fittings](https://help.autodesk.com/view/RVT/2019/ENU/?guid=GUID-12A049FB-F779-4184-97A9-2E700945DE66)\n\n**Answer:** I believe that one possible approach to achieve this would be to place the fitting in the appropriate position in the model first using `NewFamilyInstance`, and then connect it to the neighbouring conduits.\nI would expect them to adjust automatically.\n\nI discovered and demonstrated that approach in the series of posts\non [implementing a rolling offset](http://thebuildingcoder.typepad.com/blog/2014/01/final-rolling-offset-using-pipecreate.html).\n\nTo make sure I am not missing anything, I am checking with the development team for you as well.\n\nMeanwhile, here are some other discussions on placing similar fittings:\n\n- [Cable Tray Orientation and Fittings](http://thebuildingcoder.typepad.com/blog/2010/05/cable-tray-orientation-and-fittings.html)\n- [Use of NewTakeOffFitting on a Duct](http://thebuildingcoder.typepad.com/blog/2011/02/use-of-newtakeofffitting-on-a-duct.html)\n- [Set Elbow Fitting Type](http://thebuildingcoder.typepad.com/blog/2011/02/set-elbow-fitting-type.html)\n- [Use of NewTakeOffFitting on a Pipe](http://thebuildingcoder.typepad.com/blog/2011/04/use-of-newtakeofffitting-on-a-pipe.html)\n- [Simpler Rolling Offset Using NewElbowFitting](http://thebuildingcoder.typepad.com/blog/2014/01/newelbowfitting-easily-places-rolling-offset-elbow-fittings.html)\n- [NewCrossFitting Connection Order](http://thebuildingcoder.typepad.com/blog/2014/10/newcrossfitting-connection-order.html)\n\nThe development team added some more detailed advice:\n\nYou can use `Document.Create.NewElbowFitting` taking two `Connector` arguments.\n\nDepending on the orientation of the MEP Curves it might fail and then require a Transition or a Union instead.\n\nIf there are three connectors, it requires a Tee; if there are four connectors, it requires a Cross.\n\nIt uses the family routing settings to assign the type and the `size_lookup` in the fitting family to determine the geometrical representation of the FamilyInstance.\n\nSo, in case of different diameters to connect, it will create other objects in between, such as transitions (e.g., for pipes or ducts) or a junction box (e.g., for conduits).\n\n**Response:** We are already doing something similar, but it seems wildly inefficient, and I was hoping the API provided something we were missing as Pipe (and other curve based families) seem to have 'special' methods that conduit lacks.\n\n[Trouble of my own implementation of BreakCurve on Conduit](https://forums.autodesk.com/t5/revit-api-forum/trouble-of-my-own-implementation-of-breakcurve-on-conduit/m-p/8426899)\n\nTo be sure, we did research this thoroughly but as noted above our implementation has a 'clunky' feel to it when compared to the ease of the fitting tool in the UI (although watching updater messages shows Revit may be handling it in a similar way we are). We are under a time crunch at the moment and hope this methodology will ease some of the 'heartburn' we are experiencing with fittings on sloped conduit as well.\n\n**Answer:** Yes, it does indeed look as if the Revit API forum thread you pointed out covers it pretty well.\n\nI'm afraid I have nothing constructive to add to that, and, as you say, Revit probably does something similar internally as well."
  },
  {
    "original_filename": "1847_split_pipe",
    "header_text": "George Floyd in Memoriam",
    "local_header_href": "#6",
    "chunk_text": "####<a name=\"6\"></a> George Floyd in Memoriam\n\n\"It's my face man\n<br/>I didn't do nothing serious man\n<br/>please\n<br/>please\n<br/>please I can't breathe\n<br/>please man\n<br/>please somebod\n<br/>please man\n<br/>I can't breathe\n<br/>I can't breathe\n<br/>please\n<br/>(inaudible)\n<br/>man can't breathe, my face\n<br/>just get u\n<br/>I can't breathe\n<br/>please (inaudible)\n<br/>I can't breathe sh*t\n<br/>I will\n<br/>I can't move\n<br/>mama\n<br/>mama\n<br/>I can't\n<br/>my knee\n<br/>my nuts\n<br/>I'm through\n<br/>I'm through\n<br/>I'm claustrophobic\n<br/>my stomach hurt\n<br/>my neck hurts\n<br/>everything hurts\n<br/>some water or something\n<br/>please\n<br/>please\n<br/>I can't breathe officer\n<br/>don't kill me\n<br/>they gon' kill me man\n<br/>come on man\n<br/>I cannot breathe\n<br/>I cannot breathe\n<br/>they gon' kill me\n<br/>they gon kill me\n<br/>I can't breathe\n<br/>I can't breathe\n<br/>please sir\n<br/>please\n<br/>please\n<br/>please I can't breathe\""
  }
]