[
  {
    "original_filename": "1887_sheet_view_geom_text",
    "header_text": "Introduction",
    "local_header_href": "#introduction",
    "chunk_text": "<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"bc.css\">\n<script src=\"https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js\" type=\"text/javascript\"></script>\n</head>\n\n<!---\n\n- how to extract the geometry and the texts of the title block in a sheetview?\n  https://forums.autodesk.com/t5/revit-api-forum/how-to-extract-the-geometry-and-the-texts-of-the-title-block-in/m-p/9998687\n  /a/doc/revit/tbc/git/a/img/pm_sheet_view_text_geom.jpg\n  [XPS or the Open XML Paper Specification] https://en.wikipedia.org/wiki/Open_XML_Paper_Specification\n\n- Getting element coordiantes on sheet \n  https://forums.autodesk.com/t5/revit-api-forum/getting-element-coordiantes-on-sheet/m-p/9989539#M52411\n\n- Export 2d sheets as images with high quality\n  https://forums.autodesk.com/t5/revit-api-forum/export-2d-sheets-as-images-with-high-quality/m-p/9989471#M52410\n\ntwitter:\n\nAccessing and exporting sheet view coordinates, transforms, images and title block data, including the title block geometry and text values with the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://autode.sk/exportsheetview\n\nToday, we look at accessing and exporting sheet view coordinates, transforms, images and title block data, including the title block geometry and text values\n&ndash; Extracting title block geometry and text\n&ndash; Element coordinates on sheet\n&ndash; Export view as high quality image...\n\nlinkedin:\n\nAccessing and exporting sheet view coordinates, transforms, images and title block data, including the title block geometry and text values with the #RevitAPI\n\nhttp://autode.sk/exportsheetview\n\nToday, we look at accessing and exporting sheet view coordinates, transforms, images and title block data, including the title block geometry and text values:\n\n- Extracting title block geometry and text\n- Element coordinates on sheet\n- Export view as high quality image...\n\n#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk\n\nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\n\n<center>\n<img src=\"img/\" alt=\"\" title=\"\" width=\"600\"/>\n<p style=\"font-size: 80%; font-style:italic\"></p>\n<p style=\"font-size: 80%; font-style:italic\">\n<a href=\"\"></a>\n</p>\n</center>\n\n-->"
  },
  {
    "original_filename": "1887_sheet_view_geom_text",
    "header_text": "Sheet View Xform, Coords, Img Export and Title Block",
    "local_header_href": "#sheet-view-xform-coords-img-export-and-title-block",
    "chunk_text": "### Sheet View Xform, Coords, Img Export and Title Block\n\nToday, we look at accessing and exporting sheet view coordinates, transforms, images and title block data, including the title block geometry and text values:\n\n- [Extracting title block geometry and text](#2)\n- [Element coordinates on sheet](#3)\n- [Export view as high quality image](#4)"
  },
  {
    "original_filename": "1887_sheet_view_geom_text",
    "header_text": "Extracting Title Block Geometry and Text",
    "local_header_href": "#2",
    "chunk_text": "####<a name=\"2\"></a> Extracting Title Block Geometry and Text\n\nHere is a lengthy in-depth look at accessing, extracting and exporting title block geometry and text from \nthe [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread\non [how to extract the geometry and the texts of the title block in a sheetview](https://forums.autodesk.com/t5/revit-api-forum/how-to-extract-the-geometry-and-the-texts-of-the-title-block-in/m-p/9998687),\nwith several interesting new insights provided once again by \nRichard [RPThomas108](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) Thomas,\ne.g., the possibility of programmatically exploiting the Revit print to `XPS` functionality:\n\n**Question:** I want to extract all visible text and geometry in this image of a sheet view with its title block, including correct placement of all attributes:\n\n<center>\n<img src=\"img/pm_sheet_view_text_geom.jpg\" alt=\"Sheet view title block geometry and text\" title=\"Sheet view title block geometry and text\" width=\"500\"/> <!-- 1154 -->\n</center>\n\nTo be more precise, I want to recreate an identical representation of the sheet view in my own exportable non-Revit document.\n\n**Answer:** If you want to access the text and visible geometry to recreate a facsimile outside of Revit, you might be able to access text and geometry separately, e.g., using a filtered element collector for real data and a screen snapshot for the appearance.\n\nMost of the text data can be accessed using built-in parameters.\n\nThe Title Block is a Revit family, so its geometry can be accessed by reading it from the family definition.\n\nYou can Filter for specific elements and retrieve their parameters, e.g., using:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;collector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;document&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;lines&nbsp;=&nbsp;collector\n&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfCategory(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_Lines&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.ToElements();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;texts&nbsp;=&nbsp;collector\n&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfCategory(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_TextNotes&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.ToElements();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;filledRegions&nbsp;=&nbsp;collector\n&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.OfCategory(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_FilledRegion&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.ToElements();\n \n&nbsp;&nbsp;<span style=\"color:green;\">//etc.</span>\n</pre>\n\nPlease note that the call to `ToElements` is very often a waste of performance time and memory space.\nAvoid it when you can, i.e., mostly.\n\n**Response:** Yes, I want to create a facsimile outside of Revit.\n\nI managed to extract the content of the views that compose it but at real size and not yet find how to extract the cartridge and its content.\n\nThe solution you suggest above does not work, the filtered element collector result lists are empty.\n\n**Answer:** As always, you can use RevitLookup to analyse the properties and other attributes of the Revit elements you are trying to retrieve with the filtered element collector.\nThat will show you which filters you need to apply to extract the desired elements.\nIf the filter returns no elements, you are applying too restrictive or downright erroneous filters.\n\n**Response:** On the FamilyInstance of my ViewSheet, it finds neither `OST_Lines` nor `OST_TextNodes` (for the extract the Title Block).\n\nDo you have a filter syntax that could find them ?\n\n**Answer:** The most efficient way to define such a filter is for you to pick the elements you are filtering for and explore their properties using RevitLookup, cf., [how to research to find a Revit API solution](https://thebuildingcoder.typepad.com/blog/2017/01/virtues-of-reproduction-research-mep-settings-ontology.html#3).\n\n**Response:** I have already explored the viewsheet and the associated family instance as well as the symbol and the family.\nNone has geometry.\n\n**Answer:** The family definition document of the title block will contain the geometry.\nYou have to open the family for editing.\nIt may have various nested annotation symbols that also need to be traversed.\n\nBesides that, there is the issue of items such as images and schedules.\n\nIt would probably be easier to read the fixed document sequence of a printed `xps` file, cf.,\n[XPS or the Open XML Paper Specification](https://en.wikipedia.org/wiki/Open_XML_Paper_Specification).\n\nThis is an XML file containing path data represented in a mini language similar to what you get in `Xaml` and 'Glyphs' entries for text objects with render transforms to give their positions.\nIt takes a while to print an XPS, but if it is only the title block, it may be quicker.\nYou would still have to interpret the xml, but, as difficult to impossible tasks go, it is slightly less impossible.\n\n`XPS` is a `zip` file; change the extension to `Zip` and unpack it, or, alternatively, there are namespaces for reading packages for such directly (System.IO.Packaging).\n\nI don't envy your task, I usually just print a `pdf` when I want a copy of something.\n\n`HPGL` is another historic plotter vector format that could be easily interpreted.\n\n**Response:** My project is to export a viewsheet in `svg` format.\nCurrently, my code correctly exports all viewports, but I still have the title block (drawing and data) to export.\nIf I understand correctly, there is no way to export the title block (curve and position of the data)?\n\n**Answer:** As you've noted, `Element.Geometry` is null for title blocks.\n\nThe only approach I know of with the Revit API would be to open the title block family using `Document.EditFamily` and extract such lines from the plan view within that. As noted above, however, this family could also contain revision schedule that you can't extract lines from and other nested generic annotation families and images. The parameter text values would not be correct, but from the text strings used in Labels and parameter names you can sometimes infer such a relationship (between text locations in your title block family and positions on your ViewSheet in the project). If label has a preview parameter value (which is often the case), then this can't be done. Also, the placement of multiple parameters with line breaks etc. in the same label add to complexity. You don't get a description of these with the API (which parameters used in which label).\n\nIdeally, this task would be suited to `CustomExporter`, but I believe from previous discussions that this doesn't support ViewSheets.\n\n`XLST` could potentially be used to convert the `XPS` path data previously noted to `SVG`, although I know of no existing templates for such.\n\nAnother potential long winded option would be to export the sheet with only the title block showing to `DWG` and import that on a drafting view to analyse the geometry. Not sure it is a good option, but could be done. DWG links favour polylines: any lines of the same layer joined together will be grouped into polylines. Text object positions could only be found by exploding the dwg (not sure if there is API function for that).\n\n**Response:** I confirm that `CustomExporter2D` does not work on ViewSheets.\n\nI tested the other approach:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:green;\">//&nbsp;vs&nbsp;=&nbsp;current&nbsp;view&nbsp;(Viewsheet)</span>\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;El&nbsp;=&nbsp;doc.GetElement(&nbsp;vs.Id&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>&nbsp;FI&nbsp;=&nbsp;<span style=\"color:blue;\">null</span>;\n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">ElementId</span>&nbsp;ElI&nbsp;<span style=\"color:blue;\">in</span>&nbsp;El.GetDependentElements(&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;El1&nbsp;=&nbsp;El.Document.GetElement(&nbsp;ElI&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;FI&nbsp;=&nbsp;El1&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">FamilyInstance</span>;\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;FI&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">break</span>;\n&nbsp;&nbsp;}\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilySymbol</span>&nbsp;FS&nbsp;=&nbsp;FI.Symbol;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">Document</span>&nbsp;DocFamily&nbsp;=&nbsp;doc.EditFamily(&nbsp;FS.Family&nbsp;);\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilyManager</span>&nbsp;famManager&nbsp;=&nbsp;DocFamily.FamilyManager;\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FamilyTypeSet</span>&nbsp;famTypes&nbsp;=&nbsp;famManager.Types;\n&nbsp;&nbsp;<span style=\"color:blue;\">int</span>&nbsp;nb&nbsp;=&nbsp;famTypes.Size;\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;collector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;docFamily&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:blue;\">foreach</span>(&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;ElF&nbsp;<span style=\"color:blue;\">in</span>&nbsp;collector&nbsp;)\n&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">DetailLine</span>&nbsp;line&nbsp;=&nbsp;ElF&nbsp;<span style=\"color:blue;\">as</span>&nbsp;<span style=\"color:#2b91af;\">DetailLine</span>;\n \n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;line&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Curve</span>&nbsp;curve&nbsp;=&nbsp;line.GeometryCurve;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">Line</span>&nbsp;LI&nbsp;=&nbsp;(<span style=\"color:#2b91af;\">Line</span>)&nbsp;curve;\n \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">if</span>(&nbsp;LI&nbsp;!=&nbsp;<span style=\"color:blue;\">null</span>&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;XD&nbsp;=&nbsp;(LI.GetEndPoint(&nbsp;0&nbsp;).X&nbsp;*&nbsp;25.4&nbsp;*&nbsp;12);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;YD&nbsp;=&nbsp;(LI.GetEndPoint(&nbsp;0&nbsp;).Y&nbsp;*&nbsp;25.4&nbsp;*&nbsp;12);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;XF&nbsp;=&nbsp;(LI.GetEndPoint(&nbsp;1&nbsp;).X&nbsp;*&nbsp;25.4&nbsp;*&nbsp;12);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">double</span>&nbsp;YF&nbsp;=&nbsp;(LI.GetEndPoint(&nbsp;1&nbsp;).Y&nbsp;*&nbsp;25.4&nbsp;*&nbsp;12);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deb.Write(&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#a31515;\">&quot;&nbsp;&lt;line&nbsp;x1=\\&quot;{0}\\&quot;&nbsp;y1=\\&quot;{1}\\&quot;&nbsp;x2=\\&quot;{2}\\&quot;&nbsp;y2=\\&quot;{3}\\&quot;&nbsp;style=\\&quot;stroke-width:{4};&nbsp;stroke:rgb({5},&nbsp;{6},&nbsp;{7})\\&quot;&nbsp;{8}/&gt;\\n&quot;</span>,\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XD,&nbsp;V&nbsp;-&nbsp;YD,&nbsp;XF,&nbsp;V&nbsp;-&nbsp;YF,&nbsp;1,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;<span style=\"color:#a31515;\">&quot;&quot;</span>&nbsp;);\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;}\n&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:blue;\">else</span>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:#2b91af;\">TaskDialog</span>.Show(&nbsp;<span style=\"color:#a31515;\">&quot;Test&quot;</span>,&nbsp;<span style=\"color:#a31515;\">&quot;No&nbsp;Line&quot;</span>&nbsp;);\n&nbsp;&nbsp;}\n</pre>\n\nThis code extracts only 33 lines and nothing else.\n\nHow to have access to the text positions?\n\n\n<center>\n<img src=\"img/pm_sheet_view_text_geom_2.jpg\" alt=\"Sheet view title block geometry and text\" title=\"Sheet view title block geometry and text\" width=\"500\"/> <!-- 1154 -->\n</center>\n\n**Answer:** Your code extracts nothing but lines, because that is exactly what you have instructed it to do.\n\nYou can expand you code to analyse other elements besides lines.\n\nAlternatively, and probably more effectively, you can analyse your family definition document interactively using RevitLookup to discover what other elements it contains.\n\n**Response:** This family is internal (A0 metric).\n\nHow can I use RevitLookup to explore this family?\n\n<center>\n<img src=\"img/pm_sheet_view_text_geom_3.jpg\" alt=\"Snoop title block family\" title=\"Snoop title block family\" width=\"500\"/> <!-- 1154 -->\n</center>\n\n**Answer:** Application &gt; Documents &gt; select the family definition document.\n\n**Response:** Ok, I found some `TextNode`, `TextElement` and `ImageInstance` elements.\n\nBut my filters are not working.\n\nIs there any documentation of element filtering?\n\nMy code:\n\n<pre class=\"code\">\n&nbsp;&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>&nbsp;collector&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style=\"color:blue;\">new</span>&nbsp;<span style=\"color:#2b91af;\">FilteredElementCollector</span>(&nbsp;DocFamily&nbsp;);\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;lines&nbsp;=&nbsp;collector\n&nbsp;&nbsp;&nbsp;&nbsp;.OfCategory(&nbsp;<span style=\"color:#2b91af;\">BuiltInCategory</span>.OST_Lines&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.ToElements();\n \n&nbsp;&nbsp;<span style=\"color:#2b91af;\">ICollection</span>&lt;<span style=\"color:#2b91af;\">Element</span>&gt;&nbsp;texts&nbsp;=&nbsp;collector\n&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style=\"color:blue;\">typeof</span>(&nbsp;<span style=\"color:#2b91af;\">TextNote</span>&nbsp;)&nbsp;)\n&nbsp;&nbsp;&nbsp;&nbsp;.ToElements();\n</pre>\n\nThey return no elements.\n\nWhere is the error?\n\n**Answer:** You really do need to learn to search the Internet.\n\nIn this case, for instance, you can just search\nfor [Revit API filtered element collector](https://duckduckgo.com/?q=revit+api+filtered+element+collector).\n\nPlease practice this for a bit before asking the next question.\n\nThe specific problem that you ran into was discussed in the note\non [reinitialising the filtered element collector](https://thebuildingcoder.typepad.com/blog/2019/11/design-automation-api-stacks-collectors-and-links.html#4).\n\nHappily, that seems to have resolved the problem for the moment, with no further response so far."
  },
  {
    "original_filename": "1887_sheet_view_geom_text",
    "header_text": "Element Coordinates on Sheet",
    "local_header_href": "#3",
    "chunk_text": "####<a name=\"3\"></a> Element Coordinates on Sheet\n\nRichard helped with two other sheet related issues as well.\n\nOne is\non [Getting element coordinates on sheet](https://forums.autodesk.com/t5/revit-api-forum/getting-element-coordiantes-on-sheet/m-p/9989539).\n\nTo cut a long story short, here is his final answer:\n\n> I think you have just wrongly assumed the other two points of the bounding box, i.e., two points represent more than one unique rectangle. If you get all four points of the bounding box corners on plan without transformation and then transform them you can draw lines between them as below. I think what confused me when I looked at this originally was the double door families. Note however that in the case of the sample file all doors were parallel with the internal coordinate system. If your door instances were rotated (hosted on a non-vertical or non-horizontal directional wall) the bounding box would still be orientated to the internal system not rotated with the door. So, that aspect may add a layer of confusion, you would have to orientate the bounding box using the door instance transform first. This may not be possible actually since original two points circumscribe door with a box parallel to internal system, so when rotated this would be meaningless. In such a circumstance you likely need to build your own bounding box within the new orientation by looking at max/mins you get for the geometry in the new system.\n\n> You can't get the rotation of a scope box but if you set a view to one then you can compare 1,0,0 to the right direction of the view to get scope box rotation. This should not be required here because the view right direction is used so transform should already incorporate it. Useful to know however that the orientation of a scope box can be found this way (using one of those transaction rollback workflows). The alternative may be to interrogate the geometry of the scope box to find direction of lines around the scope box bounding box centre (for the top or bottom rectangle of the cube). Although you likely couldn't get a full rotation between 0 and 2Pi for this due to symmetry. Depends on how geometry of cube is constructed in terms of line directions there may be some non-symmetrical pattern of this (looking at all 12 lines etc.).\n\n<center>\n<img src=\"img/element_coordinates_on_sheet.png\" alt=\"Element coordinates on sheet\" title=\"Element coordinates on sheet\" width=\"600\"/> <!-- 1013 -->\n</center>\n\n<pre class=\"code\">\n  <span style=\"color:blue;\">Dim</span>&nbsp;Dr&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Element</span>&nbsp;=&nbsp;Doors(DRi)\n  <span style=\"color:blue;\">Dim</span>&nbsp;BB&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">BoundingBoxXYZ</span>&nbsp;=&nbsp;Dr.BoundingBox(V)\n  <span style=\"color:blue;\">Dim</span>&nbsp;BL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(BB.Min.X,&nbsp;BB.Min.Y,&nbsp;0)\n  <span style=\"color:blue;\">Dim</span>&nbsp;BR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(BB.Max.X,&nbsp;BB.Min.Y,&nbsp;0)\n  <span style=\"color:blue;\">Dim</span>&nbsp;TL&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(BB.Min.X,&nbsp;BB.Max.Y,&nbsp;0)\n  <span style=\"color:blue;\">Dim</span>&nbsp;TR&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:blue;\">New</span>&nbsp;<span style=\"color:#2b91af;\">XYZ</span>(BB.Max.X,&nbsp;BB.Max.Y,&nbsp;0)\n  BL&nbsp;=&nbsp;T.Inverse.OfPoint(BL).Multiply(1&nbsp;/&nbsp;Scale)&nbsp;+&nbsp;Offset\n  BR&nbsp;=&nbsp;T.Inverse.OfPoint(BR).Multiply(1&nbsp;/&nbsp;Scale)&nbsp;+&nbsp;Offset\n  TL&nbsp;=&nbsp;T.Inverse.OfPoint(TL).Multiply(1&nbsp;/&nbsp;Scale)&nbsp;+&nbsp;Offset\n  TR&nbsp;=&nbsp;T.Inverse.OfPoint(TR).Multiply(1&nbsp;/&nbsp;Scale)&nbsp;+&nbsp;Offset\n   \n  <span style=\"color:blue;\">Dim</span>&nbsp;LN_B&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Line</span>&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(BL,&nbsp;BR)\n  <span style=\"color:blue;\">Dim</span>&nbsp;LN_R&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Line</span>&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(BR,&nbsp;TR)\n  <span style=\"color:blue;\">Dim</span>&nbsp;LN_T&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Line</span>&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(TR,&nbsp;TL)\n  <span style=\"color:blue;\">Dim</span>&nbsp;LN_L&nbsp;<span style=\"color:blue;\">As</span>&nbsp;<span style=\"color:#2b91af;\">Line</span>&nbsp;=&nbsp;<span style=\"color:#2b91af;\">Line</span>.CreateBound(TL,&nbsp;BL)\n   \n  doc.Create.NewDetailCurve(AcView,&nbsp;LN_B)\n  doc.Create.NewDetailCurve(AcView,&nbsp;LN_R)\n  doc.Create.NewDetailCurve(AcView,&nbsp;LN_T)\n  doc.Create.NewDetailCurve(AcView,&nbsp;LN_L)\n</pre>"
  },
  {
    "original_filename": "1887_sheet_view_geom_text",
    "header_text": "Export View as High Quality Image",
    "local_header_href": "#4",
    "chunk_text": "####<a name=\"4\"></a> Export View as High Quality Image\n\nAnother interested thread addressed by Richard is on how\nto [export 2D sheets as images with high quality](https://forums.autodesk.com/t5/revit-api-forum/export-2d-sheets-as-images-with-high-quality/m-p/9989471),\nwrapping up with:\n\n> Without the annotation objects visible here are two images of the same view (not from exports); the top is set to 1:1000 and the bottom 1:200.\n\n> The line weights are scaled in relation to paper space units, so if you set to 1:1 etc., then your lines end up thinner, which may carry through to images exported if you can temporarily set this before export:\n\n<center>\n<img src=\"img/export_sheet_as_image_1.png\" alt=\"Sheet as image\" title=\"Sheet as image\" width=\"600\"/> <!-- 769 -->\n<br/>\n<img src=\"img/export_sheet_as_image_2.png\" alt=\"Sheet as image\" title=\"Sheet as image\" width=\"600\"/> <!-- 761 -->\n</center>\n\n####<a name=\"4.1\"></a> Mustafa Salaheldin Ali adds:\n\n> This works fine if you are exporting from a normal view, as changing the scale is not an issue.\n\n> However, you canâ€™t change the scale in the case of Sheets, because that will affect the viewport size and location."
  }
]